### ISSUE TITLE
Windows Python help raises NameError because of missing underscore

### ISSUE THREAD

**Issue by vedgar** [python/cpython#120257] opened 2024-06-08 05:50 UTC
# Bug report

### Bug description:

in Lib\_pyrepl\pager.py, line 38, a function tempfilepager is called. However, there is no such function, but thanks to newly added suggestions, I see there is a tempfile_pager function, which obviously should have been called instead.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment] 2024-06-08 05:52
Hello, thanks for the report and for testing the beta!
This is a duplicate of https://github.com/python/cpython/issues/119185. It has been fixed in #118881

**Closed as not planned by Eclips4** 2024-06-08 05:52 UTC
Labels: type-bug
