### ISSUE TITLE
Don't needlessly repeat Sphinx directives

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118030] opened 2024-04-18 08:16 UTC
# Documentation

If you repeat Sphinx directives they are separated by an empty line. For example:

https://github.com/python/cpython/blob/f70395786f6da2412d7406606feb64347fc71262/Doc/library/typing.rst?plain=1#L1974-L1975

Renders with a newline:

![image](https://github.com/python/cpython/assets/65588599/b8cababc-af5e-4f26-bd45-5c3dffa3b8b4)

Could be changed to:

```rst
.. data:: ParamSpecArgs
          ParamSpecKwargs
```

Which renders without a newline:

![image](https://github.com/python/cpython/assets/65588599/bb38f6ea-a6f4-403e-b404-4bcb18623fa9)

Regexes:

- `   \.\. attribute::.*\n   \.\. attribute::`: 35 matches
- `   \.\. data::.*\n   \.\. data::`: 2 matches
- `   \.\. decorator::.*\n   \.\. decorator::`: 1 match
- `   \.\. index::.*\n   \.\. index::`: 3 matches
- `   \.\. method::.*\n   \.\. method::`: 3 matches
- ~`   \.\. versionadded::.*\n   \.\. versionadded::`: 1 match~
- ~`   \.\. versionchanged::.*\n   \.\. versionchanged::`: 1 match~
- `\.\. attribute::.*\n\.\. attribute::`:  4 matches
- `\.\. data::.*\n\.\. data::`: 6 matches
- `\.\. describe::.*\n\.\. describe::`: 1 match
- `\.\. exception::.*\n\.\. exception::`: 1 match
- `\.\. function::.*\n\.\. function::`: 11 matches
- `\.\. index::.*\n\.\. index::`: 2 matches
- `\.\. method::.*\n\.\. method::`: 2 matches
- `\.\. module::.*\n\.\. module::`: 1 match
- `\.\. moduleauthor::.*\n\.\. moduleauthor::`: 13 matches
- `\.\. opcode::.*\n\.\. opcode::`: 1 match
- `\.\. option::.*\n\.\. option::`: 17 matches
- `\.\. sectionauthor::.*\n\.\. sectionauthor::`: 26 matches
- ~`\.\. versionadded::.*\n\.\. versionadded::`: 4 matches~

### Linked PRs
* gh-118154
* gh-118155

**Comment by nineteendo** [comment] 2024-04-18 08:31
@AlexWaygood, what should we do here?

**Comment by hugovk** [comment] 2024-04-18 09:10
The original is better.

These are two method definitions, so a gap helps separate them when there's no description.

We can also consider accessibility and look at the HTML.

Here's the original: one `<dl class="py method">` per method.

![image](https://github.com/python/cpython/assets/1324225/18c80df0-189a-4b81-a8b8-7cfd84318887)

And the suggestion: only one `<dl class="py method">` for both methods.

![image](https://github.com/python/cpython/assets/1324225/c319d2d4-fe95-445a-acf3-f217ade6badf)

The original means we have consistent semantics, which is important for non-visual users with screen-readers or braille displays.

**Comment by AlexWaygood** [comment] 2024-04-18 09:18
I agree with @hugovk -- if it's two different method definitions, or two different attribute definitions, then they _should_ be separated by a newline.

_Maybe_ some of the `.. moduleauthor::` and `.. section::` directives could be combined, but it's hard to say for certain without looking at specific instances.

**Comment by nineteendo** [comment] 2024-04-18 09:32
> These are two method definitions, so a gap helps separate them when there's no description.

Sorry, I should have clarified this: the description from the second method belongs to **BOTH** methods:

> A number of Unix commands allow the user to intermix optional arguments with positional arguments. The [parse_intermixed_args()](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_intermixed_args) and [parse_known_intermixed_args()](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_known_intermixed_args) methods support this parsing style.

If there's a gap between, it looks like the description is missing, and it takes up vertical sceen space.

**Comment by nineteendo** [comment] 2024-04-18 09:51
Maybe this is a better example:

![image](https://github.com/python/cpython/assets/65588599/9e994590-ccc9-4dfa-9ad6-3ae6d56588c6)

**Comment by hugovk** [comment] 2024-04-18 10:00
For that example, we could duplicate the description for each, and specialise it. I don't have a strong opinion, I think it might be clear enough as it is.

Back to the `argparse` one for a moment. That style is quite common in the Python docs: the text talks more generally about the module and introduces methods as it covers each concept. It would be a bigger discussion if we wanted to change that.

I don't think we can make sweeping changes here.

**Comment by nineteendo** [comment] 2024-04-18 10:15
But here duplicating the description doesn't make sense:

![image](https://github.com/python/cpython/assets/65588599/b8cababc-af5e-4f26-bd45-5c3dffa3b8b4)

**Comment by nineteendo** [comment] 2024-04-18 10:18
Also note that we already do this in other cases (consistency would be welcome):

![image](https://github.com/python/cpython/assets/65588599/b48bc37e-09da-44ed-ae74-fc6968024fa0)

**Comment by nineteendo** [comment] 2024-04-18 10:51
@hugovk

**Comment by AlexWaygood** [comment] 2024-04-18 11:04
@nineteendo, I really appreciate your energy and enthusiasm for improving CPython, it's great to see. Please consider being a little more respectful of other people's time, though :-)

Hugo and I are both volunteers working on CPython in our free time outside of our regular jobs. Neither of us is paid to help maintain CPython (very few people are). We both maintain several other open-source projects in our free time, as well.

Hugo's already subscribed to this thread; he received a notification about your latest comments before you pinged him again a second time and I'm sure he'll respond when he has a moment. But it's pretty normal in open source to sometimes have to wait a few days for a response to a question. Folks often have other stuff going on in their lives than just CPython. Repeatedly pinging a maintainer after just half an hour without a response is, if anything, likely to make them get annoyed and switch off notifications entirely.

Again, I really appreciate your energy and enthusiasm and don't want to _dampen_ that -- but the pace of open-source _is_ sometimes a bit slower than what you seem to expect right now :-)

**Comment by nineteendo** [comment] 2024-04-18 11:36
OK, understood. When should I post a reminder? One week, one month, ...?

**Comment by AlexWaygood** [comment] 2024-04-18 11:38
If it's a simple question or a review request for a simple PR, I think sending a ping after a week should be fine. If it's a review request for a more complex PR, I generally try to wait at least two weeks before checking in again.

**Comment by nineteendo** [comment] 2024-04-22 14:34
Thanks for taking the time anyway despite my impatience. I'll already make a pull request for `typing`.

**Comment by nineteendo** [comment] 2024-04-24 05:53
> I also couldn't find any specific accessibility advice either way for this

Could we create that for future additions to the docs? Then the situation doesn't get any worse.

We should decide for which directives it applies though. I wouldn't do it here for example:

![image](https://github.com/python/cpython/assets/65588599/8152e173-c9a0-4a55-a356-4066db054d9b)

**Comment by nineteendo** [comment] 2024-05-06 15:02
Let's discuss this further here: https://discuss.python.org/t/group-definitions/52745.

**Comment by gvanrossum** [comment] 2024-05-06 18:00
> Vertical screen space isn't a finite resource or something we need to minimise, and can be useful to improve clarity/readability. And newlines are small.

I object to this claim. Vertical space *is* a finite resource -- scrolling sucks. Python itself was designed to minimize needless use of vertical space (no braces). When a single description applies to two preceding headings, the headings should not be separated by extra whitespace, to emphasize the grouping.

(Not saying that I endorse a mass changeover.)

**Comment by erlend-aasland** [comment] 2024-05-30 21:44
Let's close this; the issue is too broad and there are no actionable items.

**Closed as completed by erlend-aasland** 2024-05-30 21:44 UTC
Labels: docs
