### ISSUE TITLE
List comprehensions sometimes call `iter(iter(v))` instead of just `iter(v)`

### ISSUE THREAD

**Issue by DemiMarie** [python/cpython#128211] opened 2024-12-24 04:19 UTC
# Bug report

### Bug description:

A development version of the Qubes OS updater gave the following traceback:

```python
Dec 23 21:53:01 dom0 widget-wrapper[25404]: Traceback (most recent call last):
Dec 23 21:53:01 dom0 widget-wrapper[25404]:   File "/usr/lib/python3.13/site-packages/qui/updater/updater.py", line 215, in next_clicked
Dec 23 21:53:01 dom0 widget-wrapper[25404]:     vms_to_update = self.intro_page.get_vms_to_update()
Dec 23 21:53:01 dom0 widget-wrapper[25404]:   File "/usr/lib/python3.13/site-packages/qui/updater/intro_page.py", line 147, in get_vms_to_update
Dec 23 21:53:01 dom0 widget-wrapper[25404]:     return self.list_store.get_selected()
Dec 23 21:53:01 dom0 widget-wrapper[25404]:            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
Dec 23 21:53:01 dom0 widget-wrapper[25404]:   File "/usr/lib/python3.13/site-packages/qui/updater/utils.py", line 306, in get_selected
Dec 23 21:53:01 dom0 widget-wrapper[25404]:     selected_rows = [row for row in self if row.selected]
Dec 23 21:53:01 dom0 widget-wrapper[25404]:                                     ^^^^
Dec 23 21:53:01 dom0 widget-wrapper[25404]: TypeError: 'UpdateListIter' object is not iterable
```

However, this makes no sense.  The code can be found at <https://github.com/QubesOS/qubes-desktop-linux-manager/blob/a3e4d177785bbc1b1ee72bd7cd83ef7b8a4e8827/qui/updater/utils.py#L300-L309>, where `self` is an `ListWrapper` instance.  Its `__iter__` method returns an `UpdateListIter`, which is a valid iterator.   However, `UpdateListIter` does _not_ have its own `__iter__` method.  Adding a method that returns `self` makes the problem go away.

A small reproducer is below:

```python
class B:
    def __next__(self):
        raise StopIteration
class A:
    def __iter__(self):
         return B()
# works
for i in A():
    print(i)
# BUG: should print [], but instead raises TypeError
print([i for i in A()])
```

On Python 3.12, this works (and prints `[]`).  On Python 3.13, this raises `TypeError`.

At least some standard library iterators (such as `iter([])` have an `__iter__(self)` that returns `self`, as shown by the following program printing `True` on both 3.13 and 3.14:

```python3
a = iter([])
print(a is iter(a))
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by TeamSpen210** [comment] 2024-12-24 05:30
See #89413 and #29170 - in 3.11, the docs were changed to indicate that iterators must define `__iter__` also, but the interpreter hasn't reliably checked for this. This was also brought up recently in #128161. 3.13 is just taking advantage of this to fix a different issue.

**Comment by Eclips4** [comment] 2024-12-24 09:18
Duplicate of #128161

**Closed as not planned by Eclips4** 2024-12-24 09:18 UTC
Labels: type-bug

**Comment by terryjreedy** [comment] 2024-12-24 18:12
The idea that iterators should be iterable is not recent, but was part of the design introduced, I believe, in 2.2.
