### ISSUE TITLE
`glob.glob("**", root_dir=root, recursive=True)` doesn't return root

### ISSUE THREAD

**Issue by barneygale** [python/cpython#116320] opened 2024-03-04 18:58 UTC
# Bug report

### Bug description:

```shell
$ mkdir my_dir
$ touch my_dir/my_file
```

```python
>>> import glob
>>> glob.glob('my_dir/**', recursive=True)
['my_dir/', 'my_dir/my_file']
>>> glob.glob('**', root_dir='my_dir/', recursive=True)
['my_file']  # should include './'
```

I think the `**` wildcard should match any number of file or directory segments, including zero. And it usually does! Unless the pattern *begins* with `**`, in which case this wildcard seems to match *at least one* file or directory segments.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by Privat33r-dev** [comment] 2024-03-04 19:49
```python
>>> glob.glob('**', root_dir='my_dir/', recursive=True)
['my_file', './']
```

> If recursive is true, the pattern “**” will match any files and zero or more directories, subdirectories and symbolic links to directories

It functions according to [Docs](https://docs.python.org/3/library/glob.html). In case if you prefix `**` with `./`, it will return `./` as well. I find it useful for the developers to have a choice, not everyone would want a current directory in a list of files.

Btw, it appears to be a duplicate of #106747

**Comment by barneygale** [comment] 2024-03-04 19:59
> I find it useful for the developers to have a choice, not everyone would want a current directory in a list of files.

If you want at least one segment, you can spell that with `**/*`, right?

**Comment by Privat33r-dev** [comment] 2024-03-04 20:23
> > I find it useful for the developers to have a choice, not everyone would want a current directory in a list of files.
> 
> If you want at least one segment, you can spell that with `**/*`, right?

Right. Currently did some testing, Python's behaviour doesn't much Linux's.

**Comment by barneygale** [comment] 2024-03-05 00:01
If you think my conduct isn't good enough you can share specific information in confidence with the PSF. Why are you making nonspecific allegations in public? Doing so makes me feel pretty shitty about my work on CPython but without any way to refute what you're saying. I don't think I'm uncompromising or that I don't listen to feedback, but now anyone reading this thread might think so and I can't really defend myself. It's not a nice feeling.

**Comment by serhiy-storchaka** [comment] 2024-03-05 08:14
`glob.glob(pattern, root_dir=root_dir)` is equivalent to `os.chdir(root_dir); glob.glob(pattern)`, except that it does not actually change the process-wide current working directory.

In Bash, `**` does not produce the current directory (or empty string). You can check it with `(shopt -s globstar; echo **)`. `glob.glob()` was intended to produce the same result.

So this is a documentation issue at most.

**Closed as not planned** 2024-03-05 14:05 UTC
Labels: type-bug
