### ISSUE TITLE
-V combined with other options exits the interpreter

### ISSUE THREAD

**Issue by EvanCarroll** [python/cpython#113825] opened 2024-01-08 20:20 UTC
# Bug report

### Bug description:

I saw [a new user intending to use `-v` to get added verbosity in a Bash script](https://discord.com/channels/497217746195578890/497218168327241769/1193991791507148841). Instead they used capital `-V`. This resulted in python printing out the version and quietly exiting. This behavior is undocumented in `--help` (doesn't mention silent abort)

```python
❯ python -VV -c'print(42)'
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
❯ python -V -c'print(42)'
Python 3.11.2
```

This behavior violates Zen,

> In the face of ambiguity, refuse the temptation to guess.
> There should be one-- and preferably only one --obvious way to do it.[[a]](https://en.wikipedia.org/wiki/Zen_of_Python#cite_note-7)

In this case, there are two conflicting commands, and so Python just _ignores_ one `-c'print(42)'`. I think a better behavior would be,

* error or warn "additional arguments are ignored %args" or,
*  error that `-V` ignores any other arguments (and require the user to strip them).
* or,  as  `perl` and `ruby` both define `-V` to print the version and continue as normal (which is fine because then `-V` is defined in isolation of other options). Only Python disables other arguments with `-V`.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by hugovk** [comment] 2024-01-08 22:08
> I saw [a new user intending to use `-v` to get added verbosity in a Bash script](https://discord.com/channels/497217746195578890/497218168327241769/1193991791507148841).

This link doesn't work for me, maybe I'm not a member of whichever server it is. 


> Instead they used capital `-V`. This resulted in python printing out the version and quietly exiting. This behavior is undocumented in `--help` (doesn't mention silent abort)

For reference, `--help` says:

```
-v     : verbose (trace import statements); also PYTHONVERBOSE=x
         can be supplied multiple times to increase verbosity
-V     : print the Python version number and exit (also --version)
         when given twice, print more information about the build
```

**Comment by ericvsmith** [comment] 2024-01-09 00:17
I think everything here is working as intended and documented, so I'm going to close this.

**Closed as not planned by ericvsmith** 2024-01-09 00:17 UTC
Labels: type-bug

**Comment by EvanCarroll** [comment] 2024-01-09 01:34
My documentation for `-V`,

> `-V`     : print the Python version number and exit (also --version)
>         when given twice, print more information about the build
