### ISSUE TITLE
PEP-484 "numeric tower" approach makes it hard/impossible to specify contracts in documentation

### ISSUE THREAD

**Issue by d47afb43-3ef9-466e-80a2-bd09de11d97d** [python/cpython#91390] opened 2022-04-05 20:26 UTC
BPO | [47234](https://bugs.python.org/issue47234)
--- | :---
Nosy | @rhettinger, @stevendaprano, @JelleZijlstra, @AlexWaygood

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-04-05.20:26:08.691>
labels = []
title = 'PEP-484 "numeric tower" approach makes it hard/impossible to specify contracts in documentation'
updated_at = <Date 2022-04-08.12:54:15.235>
user = 'https://bugs.python.org/tfish2'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.12:54:15.235>
actor = 'tfish2'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2022-04-05.20:26:08.691>
creator = 'tfish2'
dependencies = []
files = []
hgrepos = []
issue_num = 47234
keywords = []
message_count = 6.0
messages = ['416814', '416817', '416818', '416967', '416981', '416982']
nosy_count = 5.0
nosy_names = ['rhettinger', 'steven.daprano', 'JelleZijlstra', 'AlexWaygood', 'tfish2']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47234'
versions = []
```

</p></details>

**Comment by rhettinger** [comment] 2022-04-25 00:22
Closing this as being unspecific and unactionable.  

To develop the ideas further consider launching a discussion on python-ideas or the typing-sig.  If something matures, it would likely require a PEP because it changes changes decisions made in earlier typing PEPs.  

One cannot just wish away the differences between reals in mathematics, Real in numbers.py, floats as used in typing, and the concrete float type implemented in the core language.  There are practical limits on how much they can be harmonized without breaking existing code and tools.

**Closed as completed by rhettinger** 2022-04-25 00:22 UTC
Labels: topic-typing

**Comment by fischbacher** [comment] 2022-05-01 20:58
(I would like to comment on this claim:

"One cannot just wish away the differences between reals in mathematics, Real in numbers.py, floats as used in typing, and the concrete float type implemented in the core language. There are practical limits on how much they can be harmonized without breaking existing code and tools."

Right now, we are in a situation where this function...:

def float_identity(x: float) -> float:
  return float(x)

...fails to give two important guarantees:

1. If `x` is a value recognized as being a float by static type checking, we could deduce:
    (x == x) <= (float_identity(x) == x).  (I.e.: if x is equal to itself, then float_identity(x) must also be equal to x.)

2. If `x` is a value recognized as being a float by static type checking, `float_identity` will actually return a value.

Note that this Python-specific problem that `float` currently means two observably-different things is not(!) shared by any other major programming language: All of C, C++, C#, Java, R[n]RS Scheme, Common Lisp, Haskell, all ML dialects, and quite a few more have *one* notion of "float". So, this is very much not about "wish[ing] away the differences between reals in mathematics ... and the concrete float type implemented in the core language"! Every other major language has come up with a satisfactory solution here - in the sense that authors have some authoritative reference documentation available that explains what a "float" is and how it works. (It might have a different name, such as "double", but the general contract always is: You can rely on these floating point numbers to behave as specified in the IEEE-754 floating point standard).

Python actually also has a notion of IEEE-754-1985 binary64 compliant floating point numbers - these are objects satisfying isinstance(type(x), float), which includes instances of subclasses such as numpy.float64.

Python is special - and indeed unique - in that it has a *second* notion of `float`, which is something entirely different.
Even worse, the way this second notion of float was introduced makes it currently impossible to express the claim
"this function is guaranteed to return an instance of the class `float`" as a static type annotation.

Ad: "To develop the ideas further consider launching a discussion on python-ideas or the typing-sig" - such procedural detail changes nothing about the observation that this quite clearly is a relevant open bug.

Python is a popular programming language in higher education. One important aspect of teaching computing is teaching the skill to reason about the behavior of code. With discrepancies such as this that convey a message along the lines of "reasoning about code is difficult, so let's just forget about that", Python unnecessarily positions itself as unsuitable for teaching computing.

**Comment by stevendaprano** [comment] 2022-05-02 01:33
Thomas, I agree with you that the current situation is broken by design. 
At the time it was suggested, I had grave misgivings about the wisdom of 
treating float as an alias for Union[float, int] instead of creating a 
new static type, but I got seduced by the convenience of not having to 
import from typing.

It means that if a value type-checks statically as a float, you cannot 
tell if it has float methods fromhex() and is_integer(). You cannot even 
pass such a "static float" to float() safely.

But it is very hard to change the statis quo in Python, even when it is 
broken. Some people will dispute that it is broken. Expect to be accused 
of prioritising theoretical purity over practicality. You cannot counter 
that with theoretical arguments. You have to find practical, real-world 
examples.

More reasonably, we can't easily break backwards compatibility for those 
who are currently relying on small ints to statically type check as 
floats. Even if we all agreed with you that this was a problem that 
needs fixing, we can't easily fix it.

What can be done? On the bug tracker, nothing. If you wish to persevere, 
I recommend you start with the Typing SIG mailing list. If you can get 
the typing community, or the numpy/scipy/pandas community, to agree that 
this design is a mistake, and agree that it should be changed, then we 
can move forward with a PEP to deprecate the current behaviour and 
eventually change it.

Without agreement from the typing and/or numpy communities, I will say 
you have no hope of getting change here.
