### ISSUE TITLE
系统调用bug

### ISSUE THREAD

**Issue by liuzhongyi2** [python/cpython#122092] opened 2024-07-21 14:58 UTC
# Bug report

### Bug description:

import subprocess

# 执行 Bash 命令并获取输出
print(subprocess.check_output(['bash', '-c', 'compgen -c']))
打印了许多\n

### CPython versions tested on:

3.11

**Comment by nineteendo** [comment] 2024-07-21 15:18
Translation:

> System call bugs
> 
> ```python
> import subprocess
> 
> # Execute the Bash command and get the output
> print(subprocess.check_output(['bash', '-c', 'compgen -c'])) # Printed many \n
> ```

Note sure what the problem is here, `print()` simply prints the output of the bash command.

**Comment by ZeroIntensity** [comment] 2024-07-21 15:31
Not a CPython issue, simply user-error :stuck_out_tongue:. `check_output` returns `bytes`, not a `str`, meaning that things like `\n` are not formatted by `print()`. You need to call `.decode()`:

```py
print(subprocess.check_output(['bash', '-c', 'compgen -c']).decode("utf-8"))
```

**Comment by LJS08** [comment] 2024-07-21 15:39
请更详细的描述该问题。
或许这并不是 CPython 的问题
Please provide a more detailed description of the issue.
Maybe this is not an issue with CPython.

**Comment by picnixz** [comment] 2024-07-21 16:05
Closing as invalid (not an issue with CPython itself but rather with how to use it).

**Closed by picnixz** 2024-07-21 16:05 UTC
Labels: type-bug
