### ISSUE TITLE
Improve the docs regarding the migration from imp to importlib 

### ISSUE THREAD

**Issue by alexprengere** [python/cpython#104212] opened 2023-05-05 18:37 UTC
Now that the `imp` removal has [landed on main](https://github.com/python/cpython/commit/e1f14643dc0e6024f8df9ae975c3b05912a3cb28), users migrating to Python3.12 will likely need help to move to `importlib`.
The current [imp docs](https://docs.python.org/3/library/imp.html) have tips on how to do just that. Great!

One caveat: the `imp.load_source` has been removed from the docs a long time ago, now it is only visible is the [Python2 version of the docs](https://docs.python.org/2.7/library/imp.html#imp.load_source). So users of `imp.load_source` cannot rely on the docs to help them migrate, and have to Google this. The [first results](https://stackoverflow.com/questions/69884878/replacing-imp-with-importlib-maintaining-old-behavior) on stackoverflow are a bit wrong:

* many point to `SourceFileLoader(...).load_module()`, but this is also deprecated and slated for removal in 3.12 (according to [the warning](https://github.com/python/cpython/blob/3.11/Lib/importlib/_bootstrap.py#L281-L282))
* some solutions point to `importlib.util.spec_from_file_location`, but this does not work with files that do not end with ".py"

The solution that I think is the best translation:

```python
def imp_load_source(module_name, module_path):
    loader = SourceFileLoader(module_name, module_path)
    module = types.ModuleType(loader.name)
    loader.exec_module(module)
    return module
```

I think it would be beneficial to have that kind of information in the docs. Unfortunately, `imp.load_source` is not officially documented, but there are several GitHub issues and SO threads discussing how to migrate code to `importlib`. IMO, we should do one of:

* add it back to the docs, with explanations on how to migrate it to `importlib`
* just document the migration in the [release notes](https://docs.python.org/3.12/whatsnew/3.12.html), in the section "Porting to Python 3.12"

What do you think?

### Linked PRs
* gh-105755
* gh-105905
* gh-105951
* gh-105952
* gh-105978
* gh-106083

**Comment by warsaw** [comment] 2023-05-05 21:30
Maybe we need a porting guide in the importlib docs for porting older imp and other APIs to importlib?  I don't like that `imp` module has been deleted but the docs are still there.

**Comment by hugovk** [comment] 2023-05-05 21:39
Good idea! 

In fact we were just discussing this earlier today and thought about putting a migration guide in both the `imp` and `importlib` docs and in the 3.12 porting guide. 

cc @vstinner

**Comment by terryjreedy** [comment] 2023-05-05 22:00
In current 3.12, 'imp' is no longer present in the module index, which suggests that it is gone.

**Comment by vstinner** [comment] 2023-05-05 23:38
I don't know the importlib design, so maybe it doesn't make sense, but... Would it make sense to add a imp_load_source() function to importlib? Maybe under a different name.

**Comment by vstinner** [comment] 2023-05-05 23:47
My own use case of load_module(): old code written first for Python 2 using imp then ported to SourceLoader. It's a short script which looks for "test_xxx.py" files and then run them. Stupid but simple pytest-like, good enough for my needs: https://github.com/vstinner/hachoir/blob/0a030e3c8045441a0c30a04475a94f3aadd818ed/runtests.py#L72

I was already annoyed to have to port to them a first date to get rid of imp. So the code should be updated again?

**Comment by CAM-Gerlach** [comment] 2023-05-06 03:30
> Would it make sense to add a imp_load_source() function to importlib?

Just to note, see, e.g., #58756 for some previous discussion of this.

**Comment by vstinner** [comment] 2023-06-13 22:33
Minor step forward: I documented how to replace removed ``imp.new_module()``: https://github.com/python/cpython/commit/457a459c7804950d4c27a243b176eb933ec87a06

**Comment by brettcannon** [comment] 2023-06-16 00:03
> * some solutions point to `importlib.util.spec_from_file_location`, but this does not work with files that do not end with ".py"

That's actually only true if you don't pass in the loader you need to use as the code has to guess as what you're after. You can use either `importlib.util.spec_from_loader()` or `importlib.util.spec_from_file_location()`, they just need different specifics to do the right thing.

**Comment by vstinner** [comment] 2023-06-19 11:22
Each time that I have to dig into importlib internals, I'm lost, so I took some notes at: https://pythondev.readthedocs.io/import.html

**Comment by vstinner** [comment] 2023-06-19 14:09
I'm not sure that this fix was correct in the [gsutil-mirrors/boto project](https://github.com/gsutil-mirrors/boto/commit/ad7ba44d1640419e668a73032a6cd9e32e28a939): replace imp.find_module() with ``importlib.machinery.PathFinder().find_spec()`` (ok), and replace imp.load_module() with ``importlib.util.module_from_spec(spec)``: here there is a missing exec_module() call, no?

**Comment by vstinner** [comment] 2023-06-19 14:13
I enhanced the documentation on how to port existing code from imp to importlib: commit https://github.com/python/cpython/commit/7a56a4148c521969d64164d2776641f19e3ca9e8

**Comment by brettcannon** [comment] 2023-06-19 20:56
> replace imp.find_module() with `importlib.machinery.PathFinder().find_spec()` (ok), and replace imp.load_module() with `importlib.util.module_from_spec(spec)`: here there is a missing exec_module() call, no?

Correct, you need to find the spec and then once you have it you can use it to load the module. If someone called `find_spec()` and it succeeded, then they should use the loader from that spec to import the code. See https://docs.python.org/3/library/importlib.html#approximating-importlib-import-module for details.

**Comment by vstinner** [comment] 2023-06-20 23:08
The ``imp`` removal was discussed or mentioned in:

* https://discuss.python.org/t/how-do-i-migrate-from-imp/27885
* https://discuss.python.org/t/experience-with-python-3-11-in-fedora/12911
* https://discuss.python.org/t/lets-be-more-careful-with-planned-removals/28109

See also issues:

* https://github.com/python/cpython/issues/97850
* https://github.com/python/cpython/issues/98040

**Comment by vstinner** [comment] 2023-06-20 23:10
Rather than having this "porting guide" in What's New in Python 3.12, maybe it can/should be moved to the importlib documentation directly?

The subprocess documentation explains how to port code from removed functions like popen2.Popen3: https://docs.python.org/dev/library/subprocess.html#replacing-os-popen-os-popen2-os-popen3

**Comment by brettcannon** [comment] 2023-06-20 23:30
> Rather than having this "porting guide" in What's New in Python 3.12, maybe it can/should be moved to the importlib documentation directly?

It could be, but I think it should get removed once 3.11 reaches EOL.



> The subprocess documentation explains how to port code from removed functions like popen2.Popen3: https://docs.python.org/dev/library/subprocess.html#replacing-os-popen-os-popen2-os-popen3

That should probably be removed at this point as no one knows what those modules even do anymore.

**Comment by vstinner** [comment] 2023-06-21 22:18
I proposed PR #105951 to add recipes to replace the following removed imp functions: load_source(), load_compiled(), load_dynamic(), load_package(), init_builtin(). These functions are special because you can specify a path from where the module is loaded. These functions are like "implementation details" of load_module() which should be used with find_module().

To compare it to importlib design, find_module() produces something like an importlib "spec" (ModuleSpec), and load_module() implements different importlib "loaders" depending on the module type. The problem is that there is no 1-to-1 mapping between imp and importlib since these two modules have very different design on purpose.

I'm not comfortable with adding such long wall of text just to update code using imp in What's New in Python 3.12. I'm not convinced that init_builtin() or load_dynamic() are commonly used. These functions are more like internal functions used by the ``imp.load_module()`` function.

I'm not sure neither *how* find_module() was used with load_module() to load modules. Is the use case to specify a search path which is not in ``sys.path``? Why not putting the path in ``sys.path`` and simply use ``importlib.import_module()``?

I still consider that imp.load_source() is different and remains a relevant use case on its own. So I proposed PR #105978 to just document a recipe to replace this one.

**Comment by brettcannon** [comment] 2023-06-23 23:34
> I'm not sure neither _how_ find_module() was used with load_module() to load modules. Is the use case to specify a search path which is not in `sys.path`?

I think so.



> Why not putting the path in `sys.path` and simply use `importlib.import_module()`?

Worried they would forget to clean up `sys.path` after importing the one file they wanted?

**Comment by vstinner** [comment] 2023-06-25 15:15
> add it back to the docs, with explanations on how to migrate it to importlib
> just document the migration in the [release notes](https://docs.python.org/3.12/whatsnew/3.12.html), in the section "Porting to Python 3.12"

That's now done in What's New in Python 3.12, but under the "Removed" section, where removals are mentioned. I dislike documenting the same removal at two places.

https://docs.python.org/dev/whatsnew/3.12.html#removed

I just wrote a 3.12 backport for my second doc change: PR #106083. It'ss going to be merged soon.

I added a recipe to replace imp.load_source(). I consider that this documentation issue is now solved and I close the issue.

If someone wants a more complete explanation for a specific removed imp function, please open a new issue.

Thanks @alexprengere for the bug report, thanks @brettcannon and @arhadthedev for the reviews.

**Closed as completed by vstinner** 2023-06-25 15:15 UTC
Labels: docs, 3.11, 3.12
