### ISSUE TITLE
HelpFormatter does not properly consider extra indentation from subparsers when printing arguments

### ISSUE THREAD

**Issue by mathgeniuszach** [python/cpython#119021] opened 2024-05-13 22:20 UTC
# Bug report

### Bug description:

Consider the following code,
```python
import argparse
parser = argparse.ArgumentParser(prog="prog")
subparsers = parser.add_subparsers(metavar="mode")
a = subparsers.add_parser("option-a-here", help="helpful help")
b = subparsers.add_parser("option-b-here", help="super helpful help")
parser.parse_args()
```
Which produces this output, where even though there is more than enough room to print the descriptions after the arguments, it places them on the next line instead.
```
usage: prog [-h] mode ...

positional arguments:
  mode
    option-a-here
                 helpful help
    option-b-here
                 super helpful help

options:
  -h, --help     show this help message and exit
```
While with this code instead,
```python
import argparse
parser = argparse.ArgumentParser(prog="prog")
parser.add_argument("--option-a", help="helpful help")
parser.add_argument("--option-b", help="super helpful help")
parser.parse_args()
```
The program correctly places them on the same line:
```
usage: prog [-h] [--option-a OPTION_A] [--option-b OPTION_B]

options:
  -h, --help           show this help message and exit
  --option-a OPTION_A  helpful help
  --option-b OPTION_B  super helpful help
```
I believe this is an error with [ `HelpFormatter.add_argument()`](https://github.com/python/cpython/blob/e04cd964eb4eee1b0ae5b2c34727abce6c0fb7f0/Lib/argparse.py#L259), where the indent/dedent coming from [`HelpFormatter._iter_indented_subactions()`](https://github.com/python/cpython/blob/e04cd964eb4eee1b0ae5b2c34727abce6c0fb7f0/Lib/argparse.py#L602) is neither evaluated by [`_SubParserAction._get_subactions()`](https://github.com/python/cpython/blob/e04cd964eb4eee1b0ae5b2c34727abce6c0fb7f0/Lib/argparse.py#L1183) nor considered by [`self._current_indent`](https://github.com/python/cpython/blob/e04cd964eb4eee1b0ae5b2c34727abce6c0fb7f0/Lib/argparse.py#L270).

### CPython versions tested on:

3.11, 3.12, 3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-119616

**Comment by olgarithms** [comment] 2024-05-20 15:27
I'd like to work on this!

**Comment by serhiy-storchaka** [comment] 2024-09-23 17:33
This may be a duplicate of #87041. Will see if the solution for that issue fixes also this issue.

**Comment by serhiy-storchaka** [comment] 2024-09-23 19:30
Indeed, #124230 fixed this. The help output now:
```
usage: prog [-h] mode ...

positional arguments:
  mode
    option-a-here  helpful help
    option-b-here  super helpful help

options:
  -h, --help       show this help message and exit
```
contain subparser helps on the same line.

**Closed as not planned by serhiy-storchaka** 2024-09-23 19:30 UTC
Labels: type-bug, stdlib
