### ISSUE TITLE
The pprint module should use the terminal width, where available

### ISSUE THREAD

**Issue by orf** [python/cpython#105630] opened 2023-06-10 16:00 UTC
# Feature or enhancement

Make `pprint.pprint()` use the terminal width if available.

# Pitch

Currently `pprint.pprint()` and other methods have a default `width` argument of `80`. If you use are debugging on a terminal wider than that then your output is often needlessly split across lines.

You can of course remember to pass `width=some_bigger_number` each time, but then if you're shifting your terminal size as you're debugging then you need to keep adjusting it. It's a bit annoying.

Let's just use the terminal width, if available, and fall back to the current default of `80` if not?

# Previous discussion

https://discuss.python.org/t/the-pprint-module-should-use-the-terminal-width-where-available/27658

### Linked PRs
* gh-105631

**Comment by serhiy-storchaka** [comment] 2023-06-11 07:11
This is a duplicate of #74182.

**Closed as not planned by serhiy-storchaka** 2023-06-11 07:11 UTC
Labels: type-feature, stdlib, 3.13

**Comment by arhadthedev** [comment] 2023-06-11 08:46
@serhiy-storchaka Should we close the associated PR then? For now, I rebound it to the issue you referred to revive it if the opinion there changes.
