### ISSUE TITLE
descriptor 'st_size' for 'os.stat_result' objects doesn't apply to a 'os.stat_result' object

### ISSUE THREAD

**Issue by selfDepolyed** [python/cpython#113337] opened 2023-12-20 22:39 UTC
# Bug report

### Bug description:

The issue below occurs when calling pefile.PE from an embedded python code in C using cython.

Unfortunately, I cannot provide the full code to reproduce this issue.
C calling cpython code:
```C_Code.c 
int Somefunc(){
    thread_handle = CreateThread(NULL, 0, initFileAnalyzer, info, 0, &thread_id);
    return 0;
}

void initFileAnalyzer(pscannerCommands info){
    PyGILState_STATE gstate;
    gstate = PyGILState_Ensure();
    PyThreadState* save_tstate = PyThreadState_Get();
    assert(save_tstate != NULL);

    PyInterpreterConfig config = {
        .use_main_obmalloc = 0,
        .allow_fork = 0,
        .allow_exec = 0,
        .allow_threads = 1,
        .allow_daemon_threads = 1,
        .check_multi_interp_extensions = 1,
        .gil = PyInterpreterConfig_OWN_GIL,
    };
    PyThreadState* tstate = NULL;
    PyStatus status = Py_NewInterpreterFromConfig(&tstate, &config);
    if (PyStatus_Exception(status)) {
        return;
    }

    externalCythonCode(info);
    PyGILState_Release(gstate);
}
```

```cpython_external.pyx
cdef public char *externalCythonCode(pscannerCommands info):
    # do some stuff
    analyzepeFile()
    return "success"

cdef char *analyzepeFile():
    exe = None
    try:
	exe = pefile.PE(b"currentPefile.exe")
    except (pefile.PEFormatError, Exception) as e:
	print("Failed: ", e)
	return "failed"
```
analyzepeFile throws the following exception: `Failed: descriptor 'st_size' for 'os.stat_result' objects doesn't apply to a 'os.stat_result' object`

I tried to get the internal pefile module causing the exception, but if I call pefile.PE without try and except, I get `--- Logging error ---` without any trace output.

This exception is occuring in python v3.12.1 which I recently upgraded. When using 3.12.0, pefile.PE were throwing `_abc_impl is set to a wrong type` exception.

My current python version is 3.12.1 and pefile v2023.2.7

I cannot downgrade from python v3.12 as Py_NewInterpreterFromConfig/Creating seprate GILs was introduced in this version.

If you want any other information, please let me know.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment] 2023-12-21 21:34
The error seems to indicate that you have two different "os.stat_result" types in your program. Given the code fragment you shared it is likely that this is due to reusing a reference from one sub interpreter in another sub interpreter.

Beyond that it is close to impossible to tell what's going on because you haven't shared a complete reproducer.

**Comment by selfDepolyed** [comment] 2023-12-22 03:49
is there a way to find the other os.stat_result? and why am I only getting this in python 3.12.1?

**Comment by ronaldoussoren** [comment] 2023-12-22 07:55
The error in 3.12.0 feels similar to me, that seems to be a type mismatch (method invoked with 'self' not being the instance of the correct class).

Two things you could check is if all extension modules you use (including Cython ones) support sub interpreters and if you store references in globals somewhere.

**Comment by selfDepolyed** [comment] 2023-12-22 23:40
I don't use classes to have self in my code. I simply am calling externalCythonCode() which contains a number of nested cython functions.

**Comment by ronaldoussoren** [comment] 2023-12-23 11:32
You need to check if Cython supports sub interpreters in the first place. I am not a Cython user, let alone an expert on it, but a quick google a browse in their issue tracker gives me the impression that they might not support this in the first place.

**Comment by ronaldoussoren** [comment] 2023-12-23 11:44
@da-woods, do you know if Cython supports sub interpreters?

**Comment by da-woods** [comment] 2023-12-23 11:59
@ronaldoussoren Probably not. We're slowly working on enabling isolated module state which I think is probably the requirement for it. But it's a long way from done.

To give  yourself the best possible chance of it working, you could try defining the C macro `CYTHON_USE_MODULE_STATE` when compiling the Cython module (https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#c-macro-defines). This enables the current work on isolated module state. However, it's nowhere near complete.

**Comment by ronaldoussoren** [comment] 2023-12-23 12:05
> @ronaldoussoren Probably not. We're slowly working on enabling isolated module state which I think is probably the requirement for it. But it's a long way from done.
> 
> To give yourself the best possible chance of it working, you could try defining the C macro `CYTHON_USE_MODULE_STATE` when compiling the Cython module (https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#c-macro-defines). This enables the current work on isolated module state. However, it's nowhere near complete.

Thanks for your quick response.

@selfDepolyed, see the response above by one of the Cython developers. You might get a better result with defining `CYTHON_USE_MODULE_STATE` while building the Cython-using extension module, but Cython's support for sub interpreters is not yet finished.

The problems you're seeing are almost certainly related to this and not due to bugs in CPython's sub interpreter support. I'm therefore closing this issue.

**Closed as completed by ronaldoussoren** 2023-12-23 12:05 UTC
Labels: type-bug, topic-subinterpreters

**Comment by selfDepolyed** [comment] 2023-12-23 20:04
@da-woods, can you provide an ETA for sub-interpreter support for cython? 2024/2025? or even more?

**Comment by selfDepolyed** [comment] 2023-12-23 21:21
> The other thing I spot (looking at what is provided in the example) is that you never actually import the Cython module, and certainly not in your newly created interpreter. Even `cdef public` functions still require the module they are in to be imported before use to set up things like global string constants.
> 
> If you did try to import the module then I suspect it'd fail because Cython doesn't yet set [`Py_mod_multiple_interpreters`](https://docs.python.org/3/c-api/module.html#c.Py_mod_multiple_interpreters).

Do you mean, I haven't imported pefile or mycython.pyx module? if so, how do I import the modules in the sub interpreter? I have imported the cython modules in my int main function prior to creating sub-interpreters/Py_NewInterpreterFromConfig.

**Comment by da-woods** [comment] 2023-12-23 21:30
2025 is maybe realistic although it's hard to know.

There are bits of it that will probably never work though. For example

```
cdef public char *externalCythonCode(pscannerCommands info):
```

This has a fixed signature and nowhere to pass in the module state. Therefore if this function (or anything it calls) uses the module state (e.g. to access the `pefile` global) then it's **fundamentally incompatible** with multiple subinterpreters.

>  I have imported the cython modules in my int main function prior to creating sub-interpreters/Py_NewInterpreterFromConfig.

No. This is wrong. The sub-interpretters do not share imported modules. That's the whole point of them.

**Comment by selfDepolyed** [comment] 2023-12-23 22:34
@da-woods, is there any documentation or can you tell me how do I import cython modules in sub interpreters?

**Comment by selfDepolyed** [comment] 2023-12-23 23:54
Yep, I imported my cython module with `pmodule = PyImport_ImportModule("cython_module");` after calling `Py_NewInterpreterFromConfig`, and got the following error: `ImportError: module commonmodules does not support loading in subinterpreters`. Though I still wonder, why does my cython code works mostly except when calling pefile.PE
