### ISSUE TITLE
locals are not passed to inner function defined in exec()

### ISSUE THREAD

**Issue by sinoleao-1** [python/cpython#92681] opened 2022-05-11 16:56 UTC
**Bug report**

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

With following code, f1 is OK, but f2 failed with the error "name 'a' is not defined"

```
 def f1():
    a = "hello"
    exec("print(a)")
 
 def f2():
    a = "hello"
    exec("def inner(): print(a)\ninner()")
 
 f1()
 f2()
```
**Your environment**

- CPython versions tested on:
Python 3.5.2 (default, Aug 10 2017, 23:51:58)
[GCC 4.4.3] on linux

- Operating system and architecture:
Linux 3.10.0-1160.25.1.el7.x86_64

**Comment by sinoleao-1** [comment] 2022-05-11 17:18
Did the investigation with the code below, looks like the code executed by exec() inherits locals and globals from its caller method. The inner method can inherit globals further, but cannot inherit locals.

```
def f1():
   a = "hello"
   exec("print('locals:', str(locals()))")
   exec("print('globals:', str(list(globals().keys())))")

def f2():
   a = "hello"
   exec("def inner():print('locals:', str(locals()))\ninner()")
   exec("def inner():print('globals:', str(list(globals().keys())))\ninner()")

if __name__ == '__main__':
   f1()
   f2()

output:
locals: {'a': 'hello'}
globals: ['__file__', '__builtins__', '__loader__', '__name__', '__package__', '__spec__', '__cached__', '__doc__', 'f1', 'f2']
locals: {}
globals: ['__file__', '__builtins__', '__loader__', '__name__', '__package__', '__spec__', '__cached__', '__doc__', 'f1', 'f2']
```

**Comment by sweeneyde** [comment] 2022-05-12 00:22
I think this behavior is explained by [the docs](https://docs.python.org/3/library/functions.html#exec) in the following sentence:

> If exec gets two separate objects as globals and locals, the code will be executed as if it were embedded in a class definition.

The behavior you notice is consistent with that:

```python

class Somthing:
    a = "hello"
    def inner():
        print(a)
    inner()

# result: NameError: name 'a' is not defined
```

**Comment by sweeneyde** [comment] 2022-05-14 05:36
It looks like that language was added in commit https://github.com/python/cpython/commit/83efd6cbb697fec5412ea7a987222baf18349a91 for issue https://github.com/python/cpython/issues/57766

@terryjreedy, do you think this needs further clarification in the docs? I could see how this text at the top of the paragraph could be misleading:

>    In all cases, if the optional parts are omitted, the code is executed in the current scope.

**Comment by sweeneyde** [comment] 2022-05-23 10:36
Closing as a duplicate of https://github.com/python/cpython/issues/68988.

**Closed as not planned by sweeneyde** 2022-05-23 10:36 UTC
Labels: docs
