### ISSUE TITLE
argparse: TypeError when adding an argument using parameters store_true, default and type

### ISSUE THREAD

**Issue by nessita** [python/cpython#96220] opened 2022-08-24 02:05 UTC
I'm building a custom argparse/configparser combined config manager to replace a deprecated dependency used in a project I'm porting to Python 3 (I did find [ConfigArgParse](https://pypi.org/project/ConfigArgParse/) though I would rather to not use a third party lib for this yet).

When constructing the ArgumentParser and adding arguments to it, I was puzzled by the following exception being raised after calling `add_argument`:

```python
TypeError: __init__() got an unexpected keyword argument 'type'
```

The minimal code to reproduce the error I got is:

```python
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--foo', default='False', action='store_true', type=bool)
```

Complete exception:

```
/usr/lib/python3.8/argparse.py in add_argument(self, *args, **kwargs)
   1378         if not callable(action_class):
   1379             raise ValueError('unknown action "%s"' % (action_class,))
-> 1380         action = action_class(**kwargs)
   1381
   1382         # raise an error if the action type is not callable

TypeError: __init__() got an unexpected keyword argument 'type'
```

After some investigation, I found out that the code raising this exception is the `argparse._StoreTrueAction` when called with the parameters passed to `add_argument`. I did some googling and I did find this related [stackoverflow post](https://stackoverflow.com/questions/33574270/typeerror-init-got-an-unexpected-keyword-argument-type-in-argparse), where the OP seems to be confused by wanting to use `store_true` with int/str options. My case is different in that my options are indeed bool options, and I do want the parser to `store_true` when the option is passed, and to treat the default `'False'` as bool.

A fair question you may ask is why my default is the string `'False'` instead of the `False` value: this is a side-effect of grabbing all the config options from config files (using `ConfigParser`), and having the default values being fetched as strings. While I could convert this value to bool before passing it to `add_argument`, I was making use of the following documented feature of argparse:

> If the default value is a string, the parser parses the value as if it were a command-line argument. In particular, the parser applies any [type](https://docs.python.org/3.8/library/argparse.html#type) conversion argument, if provided, before setting the attribute on the [Namespace](https://docs.python.org/3.8/library/argparse.html#argparse.Namespace) return value.

I'm aware this can be solved with a workaround in my code, and in a way the `'False'` default is incorrect, so I would totally understand if this issue is closed as Invalid. Thanks!

- CPython versions tested on: 3.8
- Operating system and architecture:  Linux 5.4.0-124-generic x86_64

**Comment by mahdy786** [comment] 2022-08-24 02:11
Hi Nessit 
The problem your facing has already been solved here https://stackoverflow.com/questions/33574270/typeerror-init-got-an-unexpected-keyword-argument-type-in-argparse

**Comment by nessita** [comment] 2022-08-24 18:20
Hi @mahdy786, thank you for trying to help. I have referenced that stackoverflow post in my bug report, and as I mentioned originally, it does not quite match the issue I'm having. In the post, the OP is operating with strings and ints, so `store_true` (or `store_false`) make no sense. In my use case, I'm indeed working with booleans and I'd like to use both `type` *and* `store_true` for the reasons explained above.

**Comment by hpaulj** [comment] 2022-11-04 19:13
The use, or non-use, of the 'type=bool' is documented under 'type'.  `bool('False')` will not do what you want.

In the linked SO, the issue isn't `type=int`.  Any use of `type` with 'store_true' will raise this error.  The error is raised by signature of the `_StoreTrueAction` class.  It does not accept `type` as a keyword parameter.

This action subclass does not take any arguments (`nargs=0`), so there's nothing to convert via the `type`.  So it doesn't expect or need this parameter. 

We could get around this `TypeError` by setting the `type` after the `add_argument`.  But as this demonstrates,  `bool('False')` is still `True`:

     In [78]: p = argparse.ArgumentParser()
     In [79]: a = p.add_argument('--foo',action='store_true', default="False")  
     In [80]: a.type=bool
     In [81]: p.parse_args([])
     Out[81]: Namespace(foo=True)])

You could write your own custom `type` function that converts the string 'False' to boolean `False`.  That kind of function has been suggested in other bug/issues, but we've rejected making it part of argparse.   But I think the real solution is to make your  'config grabber' smarter.  'store_true' cannot, and should not, accept a `type` parameter.

**Comment by nessita** [comment] 2023-03-08 17:51
Thank you @hpaulj for your response. I do understand that currently `store_true` is the one raising the error and that `_StoreTrueAction` does not accept `type` as keyword parameter. Perhaps I could file a new issue for the error to be clearer and a bit more user friendly? (it took me a while to understand what was going on).

And indeed I have written my own custom `type` function that converts the string 'False' to boolean False (I called it `boolean_parser` in my solution below). Given your response, I guess we can close this issue as invalid?

In any case, for any future reader that has the same issue, I'm sharing my workaround here:

```python
def boolean_parser(value):
    value = getattr(value, 'lower', lambda: None)()
    if value in ('1', 'yes', 'true', 'on'):
        result = True
    elif value in ('0', 'no', 'false', 'off'):
        result = False
    else:
        raise argparse.ArgumentTypeError(
            '%r is not a valid boolean-like value.' % value
        )
    return result


class _StoreTrueAction(argparse.Action):
    """Re-implement from upstream.

    https://github.com/python/cpython/issues/96220

    """

    def __init__(
        self,
        option_strings,
        dest,
        default=False,
        type=boolean_parser,
        required=False,
        help=None,
        metavar=None,
    ):
        super(_StoreTrueAction, self).__init__(
            option_strings=option_strings,
            dest=dest,
            nargs=0,
            const=True,
            default=default,
            type=type,
            required=required,
            help=help,
            metavar=metavar,
        )

    def __call__(self, parser, namespace, values, option_string=None):
        setattr(namespace, self.dest, self.const)

```

**Comment by serhiy-storchaka** [comment] 2024-09-25 19:40
Closing as this is not a bug in argparse. The `store_true` action cannot be used with `type` because it does not take any value.

**Closed as not planned by serhiy-storchaka** 2024-09-25 19:40 UTC
Labels: type-bug, stdlib, invalid
