### ISSUE TITLE
enum.auto() can have incorrect behavior when used in a tuple

### ISSUE THREAD

**Issue by LexouDuck** [python/cpython#122607] opened 2024-08-02 11:58 UTC
# Bug report

### Bug description:

So, what began as a simple mistake became an interesting debugging session with an equally interesting discovery.

Essentially, out of force of habit from other programming languages, i defined an enum, but put an extraneous comma at the end of each enum item declaration line. This means each enum item was actually assigned a tuple rather than an int, and this made auto() behave weirdly, but only on my android phone, using termux, but not on my linux laptop.

Here is a minimal reproducible example:

```python
#!/usr/bin/env python3
from enum import Enum, auto

class Bad(Enum):
    a = 0,
    b = auto(),
    c = auto(),
    d = auto(),
    e = auto(),

print(f"{Bad.a=}")
print(f"{Bad.b=}")
print(f"{Bad.c=}")
print(f"{Bad.d=}")
print(f"{Bad.e=}")
```

And here is the output:
```
Bad.a=<Bad.a: (0,)>
Bad.b=<Bad.b: (1,)>
Bad.c=<Bad.c: (2,)>
Bad.d=<Bad.c: (2,)>
Bad.e=<Bad.c: (2,)>
```

Now, when I created this example script, i got the following warning (which i did not see earlier, because the program in which the bug originally occurred uses curses interface, so the logging was obscured)
```
DeprecationWarning: In 3.13 the default `auto()`/`_generate_next_value_` will require all values to be sortable and support adding +1    and the value returned will be the largest value in the enum incremented by 1
```
So it is good to hear that a fix is implemented in python3.13, although in any case we should not be seeing any platform-dependent behavior, even on older python versions.

Thanks in advance.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux, Other

**Comment by picnixz** [comment] 2024-08-02 12:16
Do you mean to say that the bug is only present on termux but not on your Linux laptop? (just to confirm)

**Comment by LexouDuck** [comment] 2024-08-02 14:39
Indeed, this strange behavior only occurs on termux.

On my Linux machine (with python 3.10.2), here is the output I get:
```
Bad.a=<Bad.a: (0,)>
Bad.b=<Bad.b: (<enum.auto object at 0x7d250328c970>,)>
Bad.c=<Bad.c: (<enum.auto object at 0x7d250328c940>,)>
Bad.d=<Bad.d: (<enum.auto object at 0x7d250328c9a0>,)>
Bad.e=<Bad.e: (<enum.auto object at 0x7d250328e6e0>,)>
```

**Comment by ZeroIntensity** [comment] 2024-08-02 14:55
3.11 and 3.12 don't officially support Android, and the reproducer fails on 3.13, per the deprecation warning. I don't think there's anything that can be done :(

**Comment by picnixz** [comment] 2024-08-11 03:56
@ethanfurman I assigned you because IIRC, you were the Enum expert. Should this issue be closed as not planned, reported to tmux instead or be considered as a bug in CPython? (sorry if I assigned you wrongly but it was mainly to make you aware of the issue).

**Comment by ZeroIntensity** [comment] 2024-08-11 15:59
I'm also going to ping @mhsmith, the author of PEP 738 (Android support).

**Comment by mhsmith** [comment] 2024-08-11 16:10
I've tested on macOS and Linux, and it looks like this is not a difference between Android and other platforms, but actually a difference between Python 3.10 and 3.11/3.12.

**Comment by ethanfurman** [comment] 2024-08-11 19:15
Apologies for not seeing this earlier.

The different behavior is due to a change in how `auto()` is processed in 3.11+ -- previously, it wasn't evaluated when part of a tuple, and in 3.11+ it is.

In 3.13 it will fail with

```
Traceback (most recent call last):
  ...
TypeError: unable to increment (0,)
```

In the OP the values are listed as `0,`, `1,`, `2,`, `2,`, `2,` -- is that a typo?  They should be `0,`, `1,`, `2,`, `3,`, `4,`

**Comment by LexouDuck** [comment] 2024-08-12 04:43
> In the OP the values are listed as `0,`, `1,`, `2,`, `2,`, `2,` -- is that a typo? They should be `0,`, `1,`, `2,`, `3,`, `4,`

It is not a typo, it is a direct copy-paste of the output I get when running this on Android (termux) with python3.10. In fact, I originally spotted this behavior because I was shocked that doing `(Bad.c == Bad.e)` was returning `True`.

**Comment by mhsmith** [comment] 2024-08-12 10:59
I can reproduce that as well, but it's not platform dependent – it happens on all platforms on Python 3.11, while the expected sequence is returned on Python 3.12. 

So I'll rename the issue, but I'll leave it to someone who knows more about the `enum` module to decide if this requires any action.

**Comment by ZeroIntensity** [comment] 2024-08-12 11:00
I'm guessing there's nothing that can be done as 3.11 is security-only.

**Comment by picnixz** [comment] 2024-08-12 11:09
I'll let Ethan decide/confirm that it works as intended on 3.12+ (and if so, then we'll need to close this issue since 3.11 won't get a bug-fix for this one).

**Comment by picnixz** [comment] 2024-12-02 15:40
I'll close this one since 3.11 is security-only. Now, on 3.12.6, I get:

```py
Bad.a=<Bad.a: (0,)>
Bad.b=<Bad.b: (1,)>
Bad.c=<Bad.c: (2,)>
Bad.d=<Bad.d: (3,)>
Bad.e=<Bad.e: (4,)>
```

+ the warning. So it seems ok to me. Closing as `not an issue`.

**Closed as not planned by picnixz** 2024-12-02 15:40 UTC
Labels: type-bug, stdlib
