### ISSUE TITLE
plistlib unable to parse plist comments containing --

### ISSUE THREAD

**Issue by bjo0** [python/cpython#95722] opened 2022-08-05 20:19 UTC
plistlib unable to parse plist comments containing `--`.

For example, this is a valid plist comment:
```xml
    <!-- --------------------------------- -->
```

But plist lib throws this error:
```
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 11
```

I think maybe when it sees `--`, it expects that you are going to close the comment.

**Comment by ronaldoussoren** [comment] 2022-08-06 10:38
See the XML specification: https://www.w3.org/TR/xml/#sec-comments

This comment is not well-formed, which is why it is rejected by the XML parser used by plistlib.

**Comment by ronaldoussoren** [comment] 2022-08-07 12:21
I'm closing this issue because this is IMO not a bug in plistlib, but malformed input.

**Closed as not planned by ronaldoussoren** 2022-08-07 12:21 UTC
Labels: type-bug

**Comment by bjo0** [comment] 2022-08-08 20:40
To close the loop, the relevant portion of the document is:

> For compatibility, the string " -- " (double-hyphen) must not occur within comments.] Parameter entity references must not be recognized within comments.

> for compatibility: [Definition: Marks a sentence describing a feature of XML included solely to ensure that XML remains compatible with SGML.]

Note that Apple's plist parser does permit such comments, so this may be a source of future issues if neither system changes.
