### ISSUE TITLE
3.12 regression: cannot create weak reference to 'typing.TypeVar' object

### ISSUE THREAD

**Issue by encukou** [python/cpython#106403] opened 2023-07-04 09:56 UTC
This works in Python 3.11, but fails in 3.12b3:
```python
import weakref
import typing
weakref.ref(typing.TypeVar('T'))
```

I'm assuming it's an unintentional side effect of the PEP-695 implementation? Unfortunately I don't have time to investigate right now, let me know if I should.

Reported in https://github.com/cloudpipe/cloudpickle/issues/507

### Linked PRs
* gh-106418
* gh-106635

**Comment by JelleZijlstra** [comment] 2023-07-04 14:23
Fixing.

The new `typing.TypeAliasType` is also not weakrefable:
```
>>> type T = int
>>> weakref.ref(T)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot create weak reference to 'typing.TypeAliasType' object
```

But neither is the existing UnionType:
```
>>> weakref.ref(int | str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot create weak reference to 'types.UnionType' object
```

So maybe that's fine?

**Comment by ogrisel** [comment] 2023-07-06 09:46
@JelleZijlstra

> So maybe that's fine?

I suspect that this might cause problems with `cloudpickle` when executing interactively defined functions with type annotations in there signatures on remote Python workers (e.g. in Dask, Ray or PySpark).

I did not have time to investigate the details myself yet but @musicinmybrain tried to test your fix in cloudpickle in https://github.com/cloudpipe/cloudpickle/issues/507#issuecomment-1622092351 and there are still segfaults to debug.

**Comment by JelleZijlstra** [comment] 2023-07-11 15:44
I merged my PR that re-adds weakref support for TypeVars. I haven't tried to debug the segfaults in the cloudpickle tests, but let me know if those can be minified to something that shows the issue is in CPython.

**Comment by Yhg1s** [comment] 2023-07-31 13:10
Closing this as the original report is (believed to be) fixed. If the other cloudpickle issues are caused by bugs in 3.12 it probably deserves its own issue.

**Closed as completed by Yhg1s** 2023-07-31 13:10 UTC
Labels: type-bug, topic-typing, 3.12, 3.13
