### ISSUE TITLE
Unable to load files using pickle and multiple modules

### ISSUE THREAD

**Issue by user529481** [python/cpython#123547] opened 2024-09-01 01:40 UTC
# Bug report

### Bug description:

The issue relates to pickling objects defined in one module, then trying to unpickle the objects from the another module. It apparently trips up lots of users, as there are constant questions about it on StackOverflow. 

Below are some found on the first page of Google from searching "pickle.load() AttributeError: Can't get attribute"

https://stackoverflow.com/questions/27732354/unable-to-load-files-using-pickle-and-multiple-modules
https://stackoverflow.com/questions/75074877/get-cant-get-attribute-error-while-loading-my-pickel-file
https://stackoverflow.com/questions/50465106/attributeerror-when-reading-a-pickle-file
https://stackoverflow.com/questions/78445171/why-my-pickled-class-giving-me-attributeerror-cant-get-attribute-myclass
https://stackoverflow.com/questions/50394432/pickle-attributeerror-cant-get-attribute-wishart-on-module-main-from
https://stackoverflow.com/questions/71876497/pickle-error-attributeerror-cant-get-attribute-on-module-main-built-i
https://stackoverflow.com/questions/66297657/cant-get-attribute-when-pickling-object
https://stackoverflow.com/questions/69653835/attribute-error-pickle-load-seldon-deployment

There are more from other sites. A trivial fix is to replace pickle with dill, and everything magically works. So I'm wondering if it's worthwhile fixing the default of behavior of pickle so this issue doesn't arise. 

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux, macOS

**Comment by ericvsmith** [comment] 2024-09-01 09:41
Please discuss this feature request on https://discuss.python.org/c/ideas/6

**Comment by serhiy-storchaka** [comment] 2024-09-04 14:25
This works as intended. https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled

```rst
Note that functions (built-in and user-defined) are pickled by fully
:term:`qualified name`, not by value. [#]_  This means that only the function name is
pickled, along with the name of the containing module and classes.  Neither
the function's code, nor any of its function attributes are pickled.  Thus the
defining module must be importable in the unpickling environment, and the module
must contain the named object, otherwise an exception will be raised. [#]_

Similarly, classes are pickled by fully qualified name, so the same restrictions in
the unpickling environment apply.  Note that none of the class's code or data is
pickled, so in the following example the class attribute ``attr`` is not
restored in the unpickling environment::

   class Foo:
       attr = 'A class attribute'

   picklestring = pickle.dumps(Foo)

These restrictions are why picklable functions and classes must be defined at
the top level of a module.

Similarly, when class instances are pickled, their class's code and data are not
pickled along with them.  Only the instance data are pickled.  This is done on
purpose, so you can fix bugs in a class or add methods to the class and still
load objects that were created with an earlier version of the class.  If you
plan to have long-lived objects that will see many versions of a class, it may
be worthwhile to put a version number in the objects so that suitable
conversions can be made by the class's :meth:`~object.__setstate__` method.
```

**Comment by picnixz** [comment] 2024-09-05 12:19
As suggested by Eric, you should ask the community on [discuss.python.org/c/ideas/6](https://discuss.python.org/c/ideas/6). This is a non-trivial feature that requires more than just a yes/no from a core dev I think. The SO posts are definitely worth being linked as previous discussions, but we should have a dedicated discussion on Discourse IMO.

I will close the issue as `not planned` for now but we'll re-open it once it has gathered sufficient support on Discourse. Multiple questions need to be addressed and I feel that this would warrant either a new protocol or even a PEP.

**Closed as not planned by picnixz** 2024-09-05 12:19 UTC
Labels: type-feature, stdlib
