### ISSUE TITLE
cannot access python download on any device

### ISSUE THREAD

**Issue by CLASSIFIED12323e13** [python/cpython#127308] opened 2024-11-26 22:38 UTC
# Bug report

### Bug description:

I have tried downloading python on windows today (11/26/2024) however when i click download it returns Access to www.python.org was deniedYou don't have authorization to view this page. HTTP ERROR 403 so i try downloading on my phone using data and get the same thing it also does not matter what os i chose it will tell me the same thing please help i want to be able to practice writing in python i will be honest i am just starting out and do not know mutch

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by tomasr8** [comment] 2024-11-26 22:50
Related issue: https://github.com/python/cpython/issues/127307

**Comment by Eclips4** [comment] 2024-11-26 22:53
Duplicate of #127307

**Closed as not planned by Eclips4** 2024-11-26 22:53 UTC
Labels: type-bug
