### ISSUE TITLE
Dark theme seems to not work properly for 3.8 and 3.9 docs

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#116837] opened 2024-03-14 21:47 UTC
# Documentation

This is what I see in the [3.12 docs](https://docs.python.org/3.12/library/ast.html) with the dark theme selected:
 
![obrazek](https://github.com/python/cpython/assets/8739637/6178d234-5884-4ad8-9ea5-f5e64bc52a89)

And this is what I see on 3.8 and 3.9:
![obrazek](https://github.com/python/cpython/assets/8739637/c05b8eb0-db0b-49f1-b697-1da5a8e91cf7)

I see this in both Chrome and Firefox. It seems that for whatever reason the `pygments_dark.css` is not being loaded for 3.8 and 3.9:
![obrazek](https://github.com/python/cpython/assets/8739637/0683366f-3762-475f-b4aa-779fc0e87e4b)

**Comment by hugovk** [comment] 2024-03-14 21:58
This is a duplicate of https://github.com/python/cpython/issues/115349 which has been fixed, and will be deployed when the next 3.8 and 3.9 releases go out, which I think should be quite soon.

In the meantime, you can switch to the light theme, or visit the docs for 3.10 or later.

**Closed as not planned by hugovk** 2024-03-14 21:58 UTC
Labels: docs
