### ISSUE TITLE
unittest: `self` is not passed with specced/autospecced `PropertyMock`

### ISSUE THREAD

**Issue by WilliamDEdwards** [python/cpython#100291] opened 2022-12-16 13:17 UTC
# Bug report

`self` is not passed with specced/autospecced `PropertyMock`.

## MRE

```python 
# test.py

import module
from unittest import mock

def test_a():
  def thing_side_effect(self):
    pass

  with mock.patch('module.class_.thing', new=mock.PropertyMock(side_effect=thing_side_effect, autospec=True)):
    module.class_().thing()

# module.py

class class_:
  @property
  def thing(self):
    return
```

The issue also occurs with:

* `spec` instead of `autospec`: `mock.patch('module.class.thing', new=mock.PropertyMock(side_effect=thing_side_effect, spec=class.thing))`
* `spec` and `new_callable` instead of `new`: `mock.patch('module.class.thing', spec=mock.create_autospec(class.thing, side_effect=thing_side_effect, new_callable=mock.PropertyMock)`

## Result

    TypeError: thing_side_effect() missing 1 required positional argument: 'self'

However, the same notation works for non-`PropertyMock`s:

```python 
# test.py

import module
from unittest import mock
import pytest

def test_a():
  def thing_side_effect(self):
    pass

  with mock.patch('module.class_.thing', side_effect=thing_side_effect, autospec=True):
    module.class_().thing()

# module.py

class class_:
  def thing(self):
    return
```

# Your environment

- CPython versions tested on: 3.10
- Operating system and architecture: macOS

**Comment by JosephSBoyle** [comment] 2022-12-22 13:00
It seems that this is in fact the intended behaviour of PropertyMock[0] (emphasis mine):
>  Fetching a `PropertyMock` instance from an object calls the mock, **with
    no args**. Setting it calls the mock with the value being set.

Below is a complete example that hopefully may help you @WilliamDEdwards .

```python
#test.py 

import module
from unittest import mock


def test_property_with_side_effect():
    """Test mocking a property with a new callable side-effect that sets an instance flag."""

    def thing_side_effect(self):
        self.flag = True

    with mock.patch('module.class_.thing', new_callable=mock.PropertyMock) as mock_property:
        instance = module.class_()
        mock_property.__get__ = mock.Mock(side_effect=thing_side_effect(instance))
        
        instance.thing

    assert instance.flag


# module.py
class class_:
    @property
    def thing(self):
        return

```

[0]. https://github.com/python/cpython/blob/67b4d2772c5124b908f8ed9b13166a79bbeb88d2/Lib/unittest/mock.py#L2920
[1]. Note: your example tries to _call_ the mock which I don't think is your intention.

```python
module._class().thing() # -> `.thing` is what I presume you want
```

**Comment by carljm** [comment] 2022-12-22 18:14
Thanks for the analysis @JosephSBoyle. Since this is documented as intended behavior, I think backward-compatibility prevents changing it, even if reasonable arguments could be made for the other behavior (passing `self`.) So I'm going to close the issue.

**Closed as not planned** 2022-12-22 18:14 UTC
Labels: type-bug, stdlib
