### ISSUE TITLE
3.12 starts to return an error when all tests in a test file are skipped

### ISSUE THREAD

**Issue by fishy** [python/cpython#113661] opened 2024-01-02 18:15 UTC
# Bug report

### Bug description:

See https://github.com/apache/thrift/blob/5cf71b2beec3c67a4c8452ddabbbc6ae43fff16f/lib/py/test/test_sslsocket.py for a full example, we skipped all tests in that file via:

```python
@unittest.skip("failing SSL test to be fixed in subsequent pull request")
class TSSLSocketTest(unittest.TestCase):
    ...
```

On python 3.11 this is fine with:

```
/usr/bin/python3 test/test_sslsocket.py
sssssssssss
----------------------------------------------------------------------
Ran 11 tests in 0.000s

OK (skipped=11)
```

But on python 3.12, this starts to become an error:

```
/opt/hostedtoolcache/Python/3.12.1/x64/bin/python test/test_sslsocket.py
WARNING:thrift.transport.sslcompat:using legacy validation callback
sssssssssss
----------------------------------------------------------------------
Ran 0 tests in 0.000s

NO TESTS RAN (skipped=11)
make[1]: *** [Makefile:645: py3-test] Error 5
```

I have to add a not-skipped dummy test to work around this (https://github.com/apache/thrift/pull/2914/files)

Is this an intentional change? I found it weird that we consider a skipped test as a failure.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-113856
* gh-113875

**Comment by terryjreedy** [comment] 2024-01-02 23:02
The change is quite intentional.  See  #98903.

@vstinner The issue PR  #98904 added 4 new exit codes -- 2, 3, 4, and 130 --  to libregtest.main, since moved to libregtest.results.  As far as I can detect, they are not mentioned in What's New 3.12.  I think they should be.  But what needs to be said?  Just the new error situations, or the numbers also? 

To add confusion, the *unittest.main* [doc](https://docs.python.org/3.13/library/unittest.html#unittest.main) says that all-skipped has exit code 5, whereas you added 4.  The other additions are not mentioned and there is no new-in 3.12 notice.  Are these errors and omissions?

#106584 quoted 5 from the doc.  I changed this to 4 from the code, but then realized that unittest is not regrtest so wonder if that change is correct.  Is does not matter in a sense because neither constant appears in the code example or the patch.

**Comment by fishy** [comment] 2024-01-02 23:08
I would argue that the original issue https://github.com/python/cpython/issues/98903 is different from the end result in 3.12.

I can understand the rationale to fail a test if "no test is run", with the intention to catch typos. But "all tests are intentionally skipped" is quite different from "there are not really any tests in the file because of typos", and it should not be too hard to distinguish between the 2 cases?

The original bug report also says:

>it displays "NO TEST RUN" but the exit code is a success

Which reinforces my believe that this end result (that it fails when all tests were skipped) is unintentional, as that used to display "OK (skipped=N)" in 3.11.

**Comment by fishy** [comment] 2024-01-02 23:13
Also looking into [the PR](https://github.com/python/cpython/pull/98904/files), its definition of `no_tests_run` is:

```py
    def no_tests_run(self):
        return not any((self.good, self.bad, self.skipped, self.interrupted,
                        self.environment_changed))
```

Which seems to suggest that when there were skipped tests, it's supposed to return `False`? So failing a test for the reason of `NO TESTS RUN` with skipped tests seem to be a bug?

**Comment by zware** [comment] 2024-01-03 03:54
> The change is quite intentional. See #98903.
> 
> @vstinner The issue PR #98904 added 4 new exit codes -- 2, 3, 4, and 130 -- to libregtest.main, since moved to libregtest.results. As far as I can detect, they are not mentioned in What's New 3.12. I think they should be. But what needs to be said? Just the new error situations, or the numbers also?
> 
> To add confusion, the _unittest.main_ [doc](https://docs.python.org/3.13/library/unittest.html#unittest.main) says that all-skipped has exit code 5, whereas you added 4. The other additions are not mentioned and there is no new-in 3.12 notice. Are these errors and omissions?

#98903 and its related changes are about the CPython test suite and its `regrtest` runner, it is unrelated to `unittest`.

> #106584 quoted 5 from the doc. I changed this to 4 from the code, but then realized that unittest is not regrtest so wonder if that change is correct.

It was not; I've reverted the change to the comment in #106584.

All that said, @terryjreedy is correct that the behavior here is as desired: generally speaking, if all of your tests are skipped, you aren't actually testing what you think you are and your test runner should complain about it.  See #62432/#102051 for the original discussion.  We should have added a whatsnew entry about it at the time, though.

**Comment by carljm** [comment] 2024-01-03 04:52
@zware I don't see any discussion of the "nonzero tests found but all skipped" situation in any of the threads you linked. 

I don't find the argument "if all tests are skipped you aren't testing what you think you are" to be convincing. I can imagine many reasons why all tests found in a particular test run might be skipped, which should not be considered an error. I can't really imagine when I'd ever want that situation to be reported as an error. The whole point of skipping a test is that it shouldn't cause the run to fail.

I find "no tests _found_ is an error" a useful behavior, and quite different. 

Unless someone has a link to previous discussion of the "all skipped" scenario that makes it clear this was intentional and has good rationale, I think the behavior reported here is both a bug and a regression that should be fixed and backported.

**Comment by AlexWaygood** [comment] 2024-01-04 18:31
Not proposing that we close this as a duplicate (as this issue has more discussion), but is this the same issue that was reported in #113267?

**Comment by carljm** [comment] 2024-01-04 18:53
It seems plausible that the cause could the same / related (I haven't dug into the implementation details here), but the symptoms are definitely distinct, so I wouldn't consider them the same issue.

**Comment by vstinner** [comment] 2024-01-08 17:27
I'm using "No tests ran" and exit code 4 to detect typos in the -m parameter. For example, ``./python -m test test_os -m test_acces``: `test_acces` (missing trailing S) instead of `test_access`.

Maybe we should not consider that "no tests were run" if at least one test was skipped?

For example, replace:

```py
    def no_tests_run(self):
        return not any((self.good, self.bad, self.skipped, self.interrupted,
                        self.environment_changed))
```

with:

```py
    def no_tests_run(self):
        return not any((self.good, self.bad, self.skipped, self.interrupted,
                        self.environment_changed)) and (not self.skipped)
```

**Comment by vstinner** [comment] 2024-01-08 17:30
> Maybe we should not consider that "no tests were run" if at least one test was skipped?

We can also use a different heuristic using "are tests filtered?" condition. For example, are `-m` and/or `-i` command line options used? See `RunTests.match_tests` member.

Note: `RunTests.match_tests_dict` is different, it's used by the ``--rerun`` feature.

**Comment by zware** [comment] 2024-01-08 18:11
To be clear, this issue has nothing to do with the CPython test suite (aka `libregrtest`, aka `python -m test`), it's about `unittest` (`python -m unittest`, `unittest.main()`) only.

> @zware I don't see any discussion of the "nonzero tests found but all skipped" situation in any of the threads you linked.

Sorry, that's #106584, which to be fair has next to no discussion.  cc author @EliseevEgor and committer @hugovk.

**Comment by vstinner** [comment] 2024-01-08 18:15
> To be clear, this issue has nothing to do with the CPython test suite

Oh. Now I'm confused.

@fishy: Would you mind to write a short reproducer of your issue?

> See https://github.com/apache/thrift/blob/5cf71b2beec3c67a4c8452ddabbbc6ae43fff16f/lib/py/test/test_sslsocket.py for a full example, we skipped all tests in that file via (...)

This example uses a third party module, so it's not easy to run without having to install Apache Thrift.

**Comment by hugovk** [comment] 2024-01-08 19:24
> Sorry, that's #106584, which to be fair has next to no discussion. cc author @EliseevEgor and committer @hugovk.

cc committer @ambv (I closed the issue two months later).

**Comment by zware** [comment] 2024-01-08 19:55
:man_facepalming: Sorry for the noise, Hugo.

**Comment by fishy** [comment] 2024-01-08 21:25
Here is a minimal reproducible example:

`test_foo.py`:
```python
import unittest

@unittest.skip("skip all tests")
class FooTest(unittest.TestCase):
    def test_bar1(self):
        self.assertEqual(0, 0)

    def test_bar2(self):
        self.assertEqual(1, 1)


if __name__ == '__main__':
    unittest.main()
```

```sh
fishy@penguin:~/test$ python3.12 test_foo.py 
ss
----------------------------------------------------------------------
Ran 0 tests in 0.000s

NO TESTS RAN (skipped=2)
fishy@penguin:~/test$ echo $?
5
fishy@penguin:~/test$ python3.12 --version
Python 3.12.1
fishy@penguin:~/test$ python3.11 test_foo.py 
ss
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK (skipped=2)
fishy@penguin:~/test$ echo $?
0
fishy@penguin:~/test$ python3.11 --version
Python 3.11.7
```

**Comment by vstinner** [comment] 2024-01-08 23:30
> NO TESTS RAN (skipped=2)

Oh right, that message comes from `Lib/unittest/runner.py`. It's the recent change: commit 76632b836cf81a95301f4eb1fa43682e8d9ffa67 of issue gh-62432.

**Comment by gpshead** [comment] 2024-01-09 00:13
> Maybe we should not consider that "no tests were run" if at least one test was skipped?

+1 this works for me.  The largest issue the feature was intended to flag was the overlooked unintentional no-op situation.  TestCase's and test definitions were found in the case of skips.

**Comment by gpshead** [comment] 2024-01-09 21:35
thanks for the report and PR!

**Closed as completed by gpshead** 2024-01-09 21:35 UTC
Labels: type-bug, tests, stdlib, 3.12, 3.13
