### ISSUE TITLE
compile(optimize=2) doesn't del docstrings/asserts, ignores -OO & PYTHONOPTIMIZE=2

### ISSUE THREAD

**Issue by dreamflow** [python/cpython#112909] opened 2023-12-09 22:33 UTC
# Bug report

### Bug description:

```python
import ast
py_test_source = '''
def test() :
    """docstring"""
    assert True
    ...
'''
ast_obj = compile( # https://docs.python.org/library/functions.html#compile
    source = py_test_source ,
    filename = "" ,
    mode = "exec" ,
    flags = ast.PyCF_ONLY_AST ,
    dont_inherit = 1 ,
    optimize = 2 ,
) 
print( ast.unparse( ast_obj ) )
```
as i understand the [compile() documentation](https://docs.python.org/library/functions.html#compile
) ,
the above example should remove the docstring ,
and the assert line , but it doesn't .

setting the env var `PYTHONOPTIMIZE=2` and then
running python with the cmdLine option `-OO`
this time with
a) `compile( ... , dont_inherit=False , ... )` without optimize
b) `compile( ... , dont_inherit=0 , ... )` without optimize
c) `compile( ... )` without : dont_inherit , optimize
didn't chage the outcome :
compile() never removes docstrings/asserts .

looks like `compile()` ignores its arg `optimize=2`
and `-OO` and `PYTHONOPTIMIZE=2` .

### CPython versions tested on:

3.11.5

### Operating systems tested on:

Windows 10 (22H2) 64bit

**Comment by terryjreedy** [comment] 2023-12-10 00:26
The doc says "The argument optimize specifies the optimization level of the compiler;".  With the `PyCF_ONLY_AST, you are only running the parser, not the compiler itself.  If the parser stripped docstrings and assert statements, then unparse would not work right.  Also, `def f(): "docstring"` would not compile as the docstring is, here, the required non-empty suite.

 If you compile to a code object and exec the code object, the resulting `test` function object will not have a docstring or assert.
```python
test = '''\
def test() :
    """docstring"""
    assert False
'''

exec(compile( 
    source = test,
    filename = "" ,
    mode = "exec" ,
#    flags = ast.PyCF_ONLY_AST ,
    dont_inherit = 1 ,
    optimize = 2 ,
))

print(test.__doc__, test())  # prints `None None`
```
Perhaps the doc could be clearer to Python learners, but I am not sure how.

**Comment by dreamflow** [comment] 2023-12-10 02:26
thank you terryjreedy for the detailed explanation 🙂
now i understand , compile() and compiler
are different things .

 > Perhaps the doc could be clearer to Python learners, but I am not sure how.

something like ? :
```
when the source is compiled into an AST object ,
optimization levels 1 and 2 are not available ,
asserts and docstrings are not removed .
```

**Comment by carljm** [comment] 2023-12-17 01:17
This is a duplicate of #108113. In #108154 @iritkatriel added `PyCF_OPTIMIZED_AST` to solve this (but for Python 3.13+ only.)

**Closed as not planned by carljm** 2023-12-17 01:17 UTC
Labels: pending
