### ISSUE TITLE
pathlib.Path.parents negative indexing is wrong for absolute paths

### ISSUE THREAD

**Issue by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [python/cpython#89577] opened 2021-10-08 18:11 UTC
BPO | [45414](https://bugs.python.org/issue45414)
--- | :---
Nosy | @MojoVampire, @pganssle

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-08.18:11:18.885>
labels = ['type-bug', 'library', '3.10', '3.11']
title = 'pathlib.Path.parents negative indexing is wrong for absolute paths'
updated_at = <Date 2021-10-08.21:19:51.055>
user = 'https://github.com/MojoVampire'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-08.21:19:51.055>
actor = 'josh.r'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-10-08.18:11:18.885>
creator = 'josh.r'
dependencies = []
files = []
hgrepos = []
issue_num = 45414
keywords = []
message_count = 4.0
messages = ['403488', '403493', '403497', '403507']
nosy_count = 2.0
nosy_names = ['josh.r', 'p-ganssle']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45414'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by brettcannon** [comment] 2022-06-03 21:35
Closing as a duplicate of https://github.com/python/cpython/issues/93156 .

**Closed as not planned by brettcannon** 2022-06-03 21:35 UTC
Labels: type-bug, stdlib, 3.11, 3.10
