### ISSUE TITLE
Possible to nest interactive help

### ISSUE THREAD

**Issue by maxvfischer** [python/cpython#124202] opened 2024-09-18 07:18 UTC
# Bug report

### Bug description:

When using `F1` to trigger the `interactive help`, it's possible to nest multiple `interactive help`. To exit this nesting, you need to exit them one by one, until you're out in the interactive shell again. This only happens when you trigger it by `F1`, not when you write `help`.

### To replicate

1. Click `F1` 3 times, see that the `interactive help` is opened 3 times
2. Write `exit` 3 times to get back to the interactive shell again

```python
Python 3.13.0rc2 (main, Sep 12 2024, 21:11:23) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Welcome to Python 3.13's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.13/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q", "quit" or "exit".

help> Welcome to Python 3.13's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.13/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q", "quit" or "exit".

help> Welcome to Python 3.13's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.13/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q", "quit" or "exit".

help> exit

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.
help> exit

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.
help> exit

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.
>>>
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by mbyrnepr2** [comment] 2024-09-18 10:29
This looks like a duplicate of https://github.com/python/cpython/issues/121584.

**Comment by skirpichev** [comment] 2024-09-18 10:42
#123024 also seems related.  Closing as duplicate.

**Closed as not planned by skirpichev** 2024-09-18 10:42 UTC
Labels: type-bug, topic-repl
