### ISSUE TITLE
Simple regex appears to take exponential time in length of input

### ISSUE THREAD

**Issue by 2ffa5556-a031-4245-ba20-2f5ff5fe2127** [python/cpython#88865] opened 2021-07-21 15:21 UTC
BPO | [44699](https://bugs.python.org/issue44699)
--- | :---
Nosy | @ezio-melotti
Files | <li>[regex_test.py](https://bugs.python.org/file50169/regex_test.py "Uploaded as text/plain at 2021-07-21.15:21:57 by brezniczky"): Regex time consumption demonstration</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-21.15:21:57.807>
labels = ['expert-regex', '3.8', 'performance']
title = 'Simple regex appears to take exponential time in length of input'
updated_at = <Date 2021-07-21.16:17:46.112>
user = 'https://bugs.python.org/brezniczky'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-21.16:17:46.112>
actor = 'brezniczky'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Regular Expressions']
creation = <Date 2021-07-21.15:21:57.807>
creator = 'brezniczky'
dependencies = []
files = ['50169']
hgrepos = []
issue_num = 44699
keywords = []
message_count = 5.0
messages = ['397948', '397949', '397951', '397952', '397953']
nosy_count = 3.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'brezniczky']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue44699'
versions = ['Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment] 2022-04-22 17:31
Closed as "not a bug".

**Closed as completed** 2022-04-22 18:25 UTC
Labels: performance, topic-regex, 3.8 (EOL)
