### ISSUE TITLE
GDB tests fail in FreeBSD-13.2 aarch64

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#111867] opened 2023-11-08 20:45 UTC
# Bug report

### Bug description:

```pytb
./python -m test test_gdb -v
== CPython 3.13.0a1+ (heads/main:24b5cbd3dc, Apr 7 2023, 05:28:07) [Clang 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386
== FreeBSD-13.2-RELEASE-arm64-aarch64-64bit-ELF little-endian
== Python build: debug
== cwd: /home/freebsd/cpython/build/test_python_worker_56129æ
== CPU count: 4
== encodings: locale=UTF-8 FS=utf-8
== resources: all test resources are disabled, use -u option to unskip tests

Using random seed: 2500963288
0:00:00 load avg: 0.23 Run 5 tests sequentially
0:00:00 load avg: 0.23 [1/5] test_gdb.test_backtrace
gdb version 13.2:
    GNU gdb (GDB) 13.2 [GDB v13.2 for FreeBSD]
    Copyright (C) 2023 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    path: /usr/local/bin/gdb

test_bt (test.test_gdb.test_backtrace.PyBtTests.test_bt)
Verify that the "py-bt" command works ... skipped "'(unable to read python frame information)' found in gdb output"
test_bt_full (test.test_gdb.test_backtrace.PyBtTests.test_bt_full)
Verify that the "py-bt-full" command works ... skipped "'(unable to read python frame information)' found in gdb output"
test_gc (test.test_gdb.test_backtrace.PyBtTests.test_gc)
Verify that "py-bt" indicates if a thread is garbage-collecting ... FAIL
test_threads (test.test_gdb.test_backtrace.PyBtTests.test_threads)
Verify that "py-bt" indicates threads that are waiting for the GIL ... skipped "resource 'cpu' is not enabled"
test_wrapper_call (test.test_gdb.test_backtrace.PyBtTests.test_wrapper_call) ... FAIL

======================================================================
FAIL: test_gc (test.test_gdb.test_backtrace.PyBtTests.test_gc)
Verify that "py-bt" indicates if a thread is garbage-collecting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_backtrace.py", line 103, in test_gc
    self.assertIn('Garbage-collecting', gdb_output)
AssertionError: 'Garbage-collecting' not found in 'Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\nBreakpoint 2: file ./Include/internal/pycore_gc.h, line 70.\nUnable to locate python frame\n'

======================================================================
FAIL: test_wrapper_call (test.test_gdb.test_backtrace.PyBtTests.test_wrapper_call)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_backtrace.py", line 133, in test_wrapper_call
    self.assertRegex(gdb_output,
AssertionError: Regex didn't match: "<method-wrapper u?'__init__' of MyList object at " not found in 'Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\nBreakpoint 2: file Objects/descrobject.c, line 1395.\nUnable to locate python frame\n'

----------------------------------------------------------------------
Ran 4 tests in 5.538s

FAILED (failures=2, skipped=3)
0:00:07 load avg: 0.29 [2/5/1] test_gdb.test_cfunction -- test_gdb.test_backtrace failed (2 failures)
gdb version 13.2:
    GNU gdb (GDB) 13.2 [GDB v13.2 for FreeBSD]
    Copyright (C) 2023 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    path: /usr/local/bin/gdb

test_pycfunction_fastcall (test.test_gdb.test_cfunction.CFunctionTests.test_pycfunction_fastcall) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_fastcall_keywords (test.test_gdb.test_cfunction.CFunctionTests.test_pycfunction_fastcall_keywords) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_noargs (test.test_gdb.test_cfunction.CFunctionTests.test_pycfunction_noargs) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_o (test.test_gdb.test_cfunction.CFunctionTests.test_pycfunction_o) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_varargs (test.test_gdb.test_cfunction.CFunctionTests.test_pycfunction_varargs) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_varargs_keywords (test.test_gdb.test_cfunction.CFunctionTests.test_pycfunction_varargs_keywords) ... skipped "resource 'cpu' is not enabled"

----------------------------------------------------------------------
Ran 0 tests in 0.002s

NO TESTS RAN (skipped=6)
0:00:07 load avg: 0.29 [3/5/1] test_gdb.test_cfunction_full
gdb version 13.2:
    GNU gdb (GDB) 13.2 [GDB v13.2 for FreeBSD]
    Copyright (C) 2023 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    path: /usr/local/bin/gdb

test_pycfunction_fastcall (test.test_gdb.test_cfunction_full.CFunctionFullTests.test_pycfunction_fastcall) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_fastcall_keywords (test.test_gdb.test_cfunction_full.CFunctionFullTests.test_pycfunction_fastcall_keywords) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_noargs (test.test_gdb.test_cfunction_full.CFunctionFullTests.test_pycfunction_noargs) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_o (test.test_gdb.test_cfunction_full.CFunctionFullTests.test_pycfunction_o) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_varargs (test.test_gdb.test_cfunction_full.CFunctionFullTests.test_pycfunction_varargs) ... skipped "resource 'cpu' is not enabled"
test_pycfunction_varargs_keywords (test.test_gdb.test_cfunction_full.CFunctionFullTests.test_pycfunction_varargs_keywords) ... skipped "resource 'cpu' is not enabled"

----------------------------------------------------------------------
Ran 0 tests in 0.002s

NO TESTS RAN (skipped=6)
0:00:07 load avg: 0.29 [4/5/1] test_gdb.test_misc
gdb version 13.2:
    GNU gdb (GDB) 13.2 [GDB v13.2 for FreeBSD]
    Copyright (C) 2023 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    path: /usr/local/bin/gdb

test_basic_command (test.test_gdb.test_misc.PyListTests.test_basic_command)
Verify that the "py-list" command works ... skipped "'Unable to read information on python frame' found in gdb output"
test_one_abs_arg (test.test_gdb.test_misc.PyListTests.test_one_abs_arg)
Verify the "py-list" command with one absolute argument ... skipped "'Unable to read information on python frame' found in gdb output"
test_two_abs_args (test.test_gdb.test_misc.PyListTests.test_two_abs_args)
Verify the "py-list" command with two absolute arguments ... skipped "'Unable to read information on python frame' found in gdb output"
test_basic_command (test.test_gdb.test_misc.PyLocalsTests.test_basic_command) ... skipped "'Unable to read information on python frame' found in gdb output"
test_locals_after_up (test.test_gdb.test_misc.PyLocalsTests.test_locals_after_up) ... skipped "'Unable to read information on python frame' found in gdb output"
test_basic_command (test.test_gdb.test_misc.PyPrintTests.test_basic_command)
Verify that the "py-print" command works ... FAIL
test_print_after_up (test.test_gdb.test_misc.PyPrintTests.test_print_after_up) ... FAIL
test_printing_builtin (test.test_gdb.test_misc.PyPrintTests.test_printing_builtin) ... skipped "'Unable to read information on python frame' found in gdb output"
test_printing_global (test.test_gdb.test_misc.PyPrintTests.test_printing_global) ... skipped "'Unable to read information on python frame' found in gdb output"
test_down_at_bottom (test.test_gdb.test_misc.StackNavigationTests.test_down_at_bottom)
Verify handling of "py-down" at the bottom of the stack ... ok
test_pyup_command (test.test_gdb.test_misc.StackNavigationTests.test_pyup_command)
Verify that the "py-up" command works ... FAIL
test_up_at_top (test.test_gdb.test_misc.StackNavigationTests.test_up_at_top)
Verify handling of "py-up" at the top of the stack ... skipped "'(unable to read python frame information)' found in gdb output"
test_up_then_down (test.test_gdb.test_misc.StackNavigationTests.test_up_then_down)
Verify "py-up" followed by "py-down" ... FAIL

======================================================================
FAIL: test_basic_command (test.test_gdb.test_misc.PyPrintTests.test_basic_command)
Verify that the "py-print" command works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_misc.py", line 138, in test_basic_command
    self.assertMultilineMatches(bt,
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 291, in assertMultilineMatches
    self.fail(msg='%r did not match %r' % (actual, pattern))
AssertionError: 'Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\nUnable to locate python frame\nUnable to locate python frame\n' did not match ".*\\nlocal 'args' = \\(1, 2, 3\\)\\n.*"

======================================================================
FAIL: test_print_after_up (test.test_gdb.test_misc.PyPrintTests.test_print_after_up)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_misc.py", line 147, in test_print_after_up
    self.assertMultilineMatches(bt,
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 291, in assertMultilineMatches
    self.fail(msg='%r did not match %r' % (actual, pattern))
AssertionError: 'Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\nUnable to locate python frame\nUnable to locate python frame\nUnable to locate python frame\nUnable to locate python frame\nUnable to locate python frame\n' did not match ".*\\nlocal 'c' = 3\\nlocal 'b' = 2\\nlocal 'a' = 1\\n.*"

======================================================================
FAIL: test_pyup_command (test.test_gdb.test_misc.StackNavigationTests.test_pyup_command)
Verify that the "py-up" command works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_misc.py", line 95, in test_pyup_command
    self.assertMultilineMatches(bt,
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 291, in assertMultilineMatches
    self.fail(msg='%r did not match %r' % (actual, pattern))
AssertionError: 'Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\nUnable to locate python frame\nUnable to locate python frame\n' did not match '^.*\n#[0-9]+ Frame 0x-?[0-9a-f]+, for file <string>, line 12, in baz \\(args=\\(1, 2, 3\\)\\)\n#[0-9]+ <built-in method pyobject_vectorcall of module object at remote 0x[0-9a-f]+>\n$'

======================================================================
FAIL: test_up_then_down (test.test_gdb.test_misc.StackNavigationTests.test_up_then_down)
Verify "py-up" followed by "py-down"
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_misc.py", line 124, in test_up_then_down
    self.assertMultilineMatches(bt,
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 291, in assertMultilineMatches
    self.fail(msg='%r did not match %r' % (actual, pattern))
AssertionError: 'Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\nUnable to locate python frame\nUnable to locate python frame\nUnable to locate python frame\n' did not match '^.*\n#[0-9]+ Frame 0x-?[0-9a-f]+, for file <string>, line 12, in baz \\(args=\\(1, 2, 3\\)\\)\n#[0-9]+ <built-in method pyobject_vectorcall of module object at remote 0x[0-9a-f]+>\n#[0-9]+ Frame 0x-?[0-9a-f]+, for file <string>, line 12, in baz \\(args=\\(1, 2, 3\\)\\)\n$'

----------------------------------------------------------------------
Ran 13 tests in 19.518s

FAILED (failures=4, skipped=8)
0:00:28 load avg: 0.56 [5/5/2] test_gdb.test_pretty_print -- test_gdb.test_misc failed (4 failures)
gdb version 13.2:
    GNU gdb (GDB) 13.2 [GDB v13.2 for FreeBSD]
    Copyright (C) 2023 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    path: /usr/local/bin/gdb

test_NULL_ob_type (test.test_gdb.test_pretty_print.PrettyPrintTests.test_NULL_ob_type)
Ensure that a PyObject* with NULL ob_type is handled gracefully ... ok
test_NULL_ptr (test.test_gdb.test_pretty_print.PrettyPrintTests.test_NULL_ptr)
Ensure that a NULL PyObject* is handled gracefully ... ok
test_builtin_method (test.test_gdb.test_pretty_print.PrettyPrintTests.test_builtin_method) ... ok
test_builtins_help (test.test_gdb.test_pretty_print.PrettyPrintTests.test_builtins_help)
Ensure that the new-style class _Helper in site.py can be handled ... ok
test_bytes (test.test_gdb.test_pretty_print.PrettyPrintTests.test_bytes)
Verify the pretty-printing of bytes ... skipped "resource 'cpu' is not enabled"
test_corrupt_ob_type (test.test_gdb.test_pretty_print.PrettyPrintTests.test_corrupt_ob_type)
Ensure that a PyObject* with a corrupt ob_type is handled gracefully ... ok
test_corrupt_tp_flags (test.test_gdb.test_pretty_print.PrettyPrintTests.test_corrupt_tp_flags)
Ensure that a PyObject* with a type with corrupt tp_flags is handled ... ok
test_corrupt_tp_name (test.test_gdb.test_pretty_print.PrettyPrintTests.test_corrupt_tp_name)
Ensure that a PyObject* with a type with corrupt tp_name is handled ... ok
test_dicts (test.test_gdb.test_pretty_print.PrettyPrintTests.test_dicts)
Verify the pretty-printing of dictionaries ... ok
test_exceptions (test.test_gdb.test_pretty_print.PrettyPrintTests.test_exceptions) ... ERROR
test_frames (test.test_gdb.test_pretty_print.PrettyPrintTests.test_frames) ... ERROR
test_frozensets (test.test_gdb.test_pretty_print.PrettyPrintTests.test_frozensets)
Verify the pretty-printing of frozensets ... skipped "resource 'cpu' is not enabled"
test_getting_backtrace (test.test_gdb.test_pretty_print.PrettyPrintTests.test_getting_backtrace) ... ok
test_int (test.test_gdb.test_pretty_print.PrettyPrintTests.test_int)
Verify the pretty-printing of various int values ... skipped "resource 'cpu' is not enabled"
test_lists (test.test_gdb.test_pretty_print.PrettyPrintTests.test_lists)
Verify the pretty-printing of lists ... ok
test_modern_class (test.test_gdb.test_pretty_print.PrettyPrintTests.test_modern_class)
Verify the pretty-printing of new-style class instances ... ERROR
test_selfreferential_dict (test.test_gdb.test_pretty_print.PrettyPrintTests.test_selfreferential_dict)
Ensure that a reference loop involving a dict doesn't lead proxyval ... ok
test_selfreferential_list (test.test_gdb.test_pretty_print.PrettyPrintTests.test_selfreferential_list)
Ensure that a reference loop involving a list doesn't lead proxyval ... ok
test_selfreferential_new_style_instance (test.test_gdb.test_pretty_print.PrettyPrintTests.test_selfreferential_new_style_instance) ... ERROR
test_selfreferential_old_style_instance (test.test_gdb.test_pretty_print.PrettyPrintTests.test_selfreferential_old_style_instance) ... ERROR
test_sets (test.test_gdb.test_pretty_print.PrettyPrintTests.test_sets)
Verify the pretty-printing of sets ... skipped "resource 'cpu' is not enabled"
test_singletons (test.test_gdb.test_pretty_print.PrettyPrintTests.test_singletons)
Verify the pretty-printing of True, False and None ... ok
test_strings (test.test_gdb.test_pretty_print.PrettyPrintTests.test_strings)
Verify the pretty-printing of unicode strings ... skipped "resource 'cpu' is not enabled"
test_subclassing_list (test.test_gdb.test_pretty_print.PrettyPrintTests.test_subclassing_list)
Verify the pretty-printing of an instance of a list subclass ... ERROR
test_subclassing_tuple (test.test_gdb.test_pretty_print.PrettyPrintTests.test_subclassing_tuple)
Verify the pretty-printing of an instance of a tuple subclass ... ERROR
test_truncation (test.test_gdb.test_pretty_print.PrettyPrintTests.test_truncation)
Verify that very long output is truncated ... ok
test_tuples (test.test_gdb.test_pretty_print.PrettyPrintTests.test_tuples)
Verify the pretty-printing of tuples ... ok

======================================================================
ERROR: test_exceptions (test.test_gdb.test_pretty_print.PrettyPrintTests.test_exceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 193, in test_exceptions
    gdb_repr, gdb_output = self.get_gdb_repr('''
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 32, in get_gdb_repr
    gdb_output = self.get_stack_trace(source, breakpoint=BREAKPOINT_FN,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 242, in get_stack_trace
    out, err = run_gdb(*args, PYTHONHASHSEED=PYTHONHASHSEED)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 67, in run_gdb
    raise Exception(f"{cmd_text} failed with exit code {proc.returncode}, "
Exception: /usr/local/bin/gdb --batch -nx --init-eval-command 'add-auto-load-safe-path /home/freebsd/cpython/python-gdb.py' '--eval-command=set breakpoint pending yes' '--eval-command=break builtin_id' '--eval-command=set print address off' --eval-command=run '--eval-command=set print entry-values no' '--eval-command=backtrace 1' --args /home/freebsd/cpython/python -S -c '
try:
    raise RuntimeError("I am an error")
except RuntimeError as e:
    id(e)
' failed with exit code 1, expected exit code 0:
stdout='Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\n'
stderr='Unmatched \'\'\'.\ntry:: Command not found.\n\\ \\ \\ \\ raise\\ RuntimeError\\(\\"I\\ am\\ an\\ error\\"\\): Command not found.\nexcept\\ RuntimeError\\ as\\ e:: Command not found.\n\\ \\ \\ \\ id\\(e\\): Command not found.\nUnmatched \'\'\'.\nDuring startup program exited with code 1.\nNo stack.\n'

======================================================================
ERROR: test_frames (test.test_gdb.test_pretty_print.PrettyPrintTests.test_frames)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 425, in test_frames
    gdb_output = self.get_stack_trace('''
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 242, in get_stack_trace
    out, err = run_gdb(*args, PYTHONHASHSEED=PYTHONHASHSEED)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 67, in run_gdb
    raise Exception(f"{cmd_text} failed with exit code {proc.returncode}, "
Exception: /usr/local/bin/gdb --batch -nx --init-eval-command 'add-auto-load-safe-path /home/freebsd/cpython/python-gdb.py' '--eval-command=set breakpoint pending yes' '--eval-command=break builtin_id' '--eval-command=set print address off' --eval-command=run '--eval-command=set print entry-values no' '--eval-command=print (PyFrameObject*)v' --args /home/freebsd/cpython/python -S -c '
import sys
def foo(a, b, c):
    return sys._getframe(0)

f = foo(3, 4, 5)
id(f)' failed with exit code 1, expected exit code 0:
stdout='Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\n'
stderr='Unmatched \'\'\'.\nimport\\ sys: Command not found.\ndef\\ foo\\(a,\\ b,\\ c\\):: Command not found.\n\\ \\ \\ \\ return\\ sys._getframe\\(0\\): Command not found.\n: Command not found.\nf\\ =\\ foo\\(3,\\ 4,\\ 5\\): Command not found.\nUnmatched \'\'\'.\nDuring startup program exited with code 1.\nNo symbol "v" in current context.\n'

======================================================================
ERROR: test_modern_class (test.test_gdb.test_pretty_print.PrettyPrintTests.test_modern_class)
Verify the pretty-printing of new-style class instances
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 215, in test_modern_class
    gdb_repr, gdb_output = self.get_gdb_repr('''
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 32, in get_gdb_repr
    gdb_output = self.get_stack_trace(source, breakpoint=BREAKPOINT_FN,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 242, in get_stack_trace
    out, err = run_gdb(*args, PYTHONHASHSEED=PYTHONHASHSEED)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 67, in run_gdb
    raise Exception(f"{cmd_text} failed with exit code {proc.returncode}, "
Exception: /usr/local/bin/gdb --batch -nx --init-eval-command 'add-auto-load-safe-path /home/freebsd/cpython/python-gdb.py' '--eval-command=set breakpoint pending yes' '--eval-command=break builtin_id' '--eval-command=set print address off' --eval-command=run '--eval-command=set print entry-values no' '--eval-command=backtrace 1' --args /home/freebsd/cpython/python -S -c '
class Foo:
    pass
foo = Foo()
foo.an_int = 42
id(foo)' failed with exit code 1, expected exit code 0:
stdout='Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\n'
stderr="Unmatched '''.\nclass\\ Foo:: Command not found.\n\\ \\ \\ \\ pass: Command not found.\nfoo\\ =\\ Foo\\(\\): Command not found.\nfoo.an_int\\ =\\ 42: Command not found.\nUnmatched '''.\nDuring startup program exited with code 1.\nNo stack.\n"

======================================================================
ERROR: test_selfreferential_new_style_instance (test.test_gdb.test_pretty_print.PrettyPrintTests.test_selfreferential_new_style_instance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 364, in test_selfreferential_new_style_instance
    self.get_gdb_repr('''
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 32, in get_gdb_repr
    gdb_output = self.get_stack_trace(source, breakpoint=BREAKPOINT_FN,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 242, in get_stack_trace
    out, err = run_gdb(*args, PYTHONHASHSEED=PYTHONHASHSEED)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 67, in run_gdb
    raise Exception(f"{cmd_text} failed with exit code {proc.returncode}, "
Exception: /usr/local/bin/gdb --batch -nx --init-eval-command 'add-auto-load-safe-path /home/freebsd/cpython/python-gdb.py' '--eval-command=set breakpoint pending yes' '--eval-command=break builtin_id' '--eval-command=set print address off' --eval-command=run '--eval-command=set print entry-values no' '--eval-command=backtrace 1' --args /home/freebsd/cpython/python -S -c '
class Foo(object):
    pass
foo = Foo()
foo.an_attr = foo
id(foo)' failed with exit code 1, expected exit code 0:
stdout='Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\n'
stderr="Unmatched '''.\nclass\\ Foo\\(object\\):: Command not found.\n\\ \\ \\ \\ pass: Command not found.\nfoo\\ =\\ Foo\\(\\): Command not found.\nfoo.an_attr\\ =\\ foo: Command not found.\nUnmatched '''.\nDuring startup program exited with code 1.\nNo stack.\n"

======================================================================
ERROR: test_selfreferential_old_style_instance (test.test_gdb.test_pretty_print.PrettyPrintTests.test_selfreferential_old_style_instance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 351, in test_selfreferential_old_style_instance
    self.get_gdb_repr('''
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 32, in get_gdb_repr
    gdb_output = self.get_stack_trace(source, breakpoint=BREAKPOINT_FN,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 242, in get_stack_trace
    out, err = run_gdb(*args, PYTHONHASHSEED=PYTHONHASHSEED)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 67, in run_gdb
    raise Exception(f"{cmd_text} failed with exit code {proc.returncode}, "
Exception: /usr/local/bin/gdb --batch -nx --init-eval-command 'add-auto-load-safe-path /home/freebsd/cpython/python-gdb.py' '--eval-command=set breakpoint pending yes' '--eval-command=break builtin_id' '--eval-command=set print address off' --eval-command=run '--eval-command=set print entry-values no' '--eval-command=backtrace 1' --args /home/freebsd/cpython/python -S -c '
class Foo:
    pass
foo = Foo()
foo.an_attr = foo
id(foo)' failed with exit code 1, expected exit code 0:
stdout='Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\n'
stderr="Unmatched '''.\nclass\\ Foo:: Command not found.\n\\ \\ \\ \\ pass: Command not found.\nfoo\\ =\\ Foo\\(\\): Command not found.\nfoo.an_attr\\ =\\ foo: Command not found.\nUnmatched '''.\nDuring startup program exited with code 1.\nNo stack.\n"

======================================================================
ERROR: test_subclassing_list (test.test_gdb.test_pretty_print.PrettyPrintTests.test_subclassing_list)
Verify the pretty-printing of an instance of a list subclass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 227, in test_subclassing_list
    gdb_repr, gdb_output = self.get_gdb_repr('''
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 32, in get_gdb_repr
    gdb_output = self.get_stack_trace(source, breakpoint=BREAKPOINT_FN,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 242, in get_stack_trace
    out, err = run_gdb(*args, PYTHONHASHSEED=PYTHONHASHSEED)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 67, in run_gdb
    raise Exception(f"{cmd_text} failed with exit code {proc.returncode}, "
Exception: /usr/local/bin/gdb --batch -nx --init-eval-command 'add-auto-load-safe-path /home/freebsd/cpython/python-gdb.py' '--eval-command=set breakpoint pending yes' '--eval-command=break builtin_id' '--eval-command=set print address off' --eval-command=run '--eval-command=set print entry-values no' '--eval-command=backtrace 1' --args /home/freebsd/cpython/python -S -c '
class Foo(list):
    pass
foo = Foo()
foo += [1, 2, 3]
foo.an_int = 42
id(foo)' failed with exit code 1, expected exit code 0:
stdout='Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\n'
stderr="Unmatched '''.\nclass\\ Foo\\(list\\):: Command not found.\n\\ \\ \\ \\ pass: Command not found.\nfoo\\ =\\ Foo\\(\\): Command not found.\nfoo\\ +=\\ \\[1,\\ 2,\\ 3\\]: Command not found.\nfoo.an_int\\ =\\ 42: Command not found.\nUnmatched '''.\nDuring startup program exited with code 1.\nNo stack.\n"

======================================================================
ERROR: test_subclassing_tuple (test.test_gdb.test_pretty_print.PrettyPrintTests.test_subclassing_tuple)
Verify the pretty-printing of an instance of a tuple subclass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 243, in test_subclassing_tuple
    gdb_repr, gdb_output = self.get_gdb_repr('''
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/test_pretty_print.py", line 32, in get_gdb_repr
    gdb_output = self.get_stack_trace(source, breakpoint=BREAKPOINT_FN,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 242, in get_stack_trace
    out, err = run_gdb(*args, PYTHONHASHSEED=PYTHONHASHSEED)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freebsd/cpython/Lib/test/test_gdb/util.py", line 67, in run_gdb
    raise Exception(f"{cmd_text} failed with exit code {proc.returncode}, "
Exception: /usr/local/bin/gdb --batch -nx --init-eval-command 'add-auto-load-safe-path /home/freebsd/cpython/python-gdb.py' '--eval-command=set breakpoint pending yes' '--eval-command=break builtin_id' '--eval-command=set print address off' --eval-command=run '--eval-command=set print entry-values no' '--eval-command=backtrace 1' --args /home/freebsd/cpython/python -S -c '
class Foo(tuple):
    pass
foo = Foo((1, 2, 3))
foo.an_int = 42
id(foo)' failed with exit code 1, expected exit code 0:
stdout='Breakpoint 1 at 0x5db484: file Python/bltinmodule.c, line 1263.\n'
stderr="Unmatched '''.\nclass\\ Foo\\(tuple\\):: Command not found.\n\\ \\ \\ \\ pass: Command not found.\nfoo\\ =\\ Foo\\(\\(1,\\ 2,\\ 3\\)\\): Command not found.\nfoo.an_int\\ =\\ 42: Command not found.\nUnmatched '''.\nDuring startup program exited with code 1.\nNo stack.\n"

----------------------------------------------------------------------
Ran 22 tests in 46.849s

FAILED (errors=7, skipped=5)
test_gdb.test_pretty_print failed (7 errors) in 47.2 sec

== Tests result: FAILURE ==

3 tests failed:
    test_gdb.test_backtrace test_gdb.test_misc
    test_gdb.test_pretty_print

2 tests OK.

Total duration: 1 min 15 sec
Total tests: run=39 failures=6 skipped=28
Total test files: run=5/5 failed=3
Result: FAILURE

```

### CPython versions tested on:

CPython main branch

**Comment by vstinner** [comment] 2024-05-24 08:56
I cannot reproduce the issue on FreeBSD 14.0-RELEASE-p3 with GNU gdb 14.1 and Python 3.14 (yeah, 14 is the new trend in version numbers!). I close the issue.

I built Python with: `./configure --with-pydebug CFLAGS="-O0" && make`.

```
vstinner@freebsd$ ./python -m test -v test_gdb  -u all
(...)
test_print_after_up (test.test_gdb.test_misc.PyPrintTests.test_print_after_up) ... skipped "'Unable to read information on python frame' found in gdb output"
(...)
Total duration: 53.0 sec
Total tests: run=57 skipped=1
Total test files: run=5/5
Result: SUCCESS
```

**Closed as completed by vstinner** 2024-05-24 08:56 UTC
Labels: type-bug, tests, OS-freebsd
