### ISSUE TITLE
Typing: runtime-checkable protocols are broken on `main`

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#104555] opened 2023-05-16 15:22 UTC
PEP-695 protocols don't work as intended:

Here's the behaviour you get with protocols that use pre-PEP 695 syntax, which is correct:

```pycon
>>> from typing import Protocol, runtime_checkable, TypeVar
>>> T_co = TypeVar("T_co", covariant=True)
>>> @runtime_checkable
... class SupportsAbsOld(Protocol[T_co]):
...     def __abs__(self) -> T_co:
...         ...
...
>>> isinstance(0, SupportsAbsOld)
True
>>> issubclass(float, SupportsAbsOld)
True
```

And here's the behaviour you get on `main` with protocols that use PEP 695 syntax, which is incorrect:

```pycon
>>> @runtime_checkable
... class SupportsAbsNew[T_co](Protocol):
...     def __abs__(self) -> T_co:
...         ...
...
>>> isinstance(0, SupportsAbsNew)
False
>>> issubclass(float, SupportsAbsNew)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\coding\cpython\Lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\typing.py", line 1875, in _proto_hook
    raise TypeError("Protocols with non-method members"
TypeError: Protocols with non-method members don't support issubclass()
```

### Linked PRs
* gh-104556
* gh-104559

**Comment by AlexWaygood** [comment] 2023-05-16 15:38
(I'm working on a fix)

**Comment by JelleZijlstra** [comment] 2023-05-16 15:47
Thanks for catching! I suppose this is about `__type_params__`?

**Comment by AlexWaygood** [comment] 2023-05-16 15:47
> Thanks for catching! I suppose this is about `__type_params__`?

Yes.

**Comment by AlexWaygood** [comment] 2023-05-16 15:55
I'm getting very confused here. The fix for the original issue is simple, and I've fixed it. But as part of the PR, I tried adding this test, and it fails:

```py
    def test_pep695_generic_protocol_noncallable_members(self):
        @runtime_checkable
        class Spam[T](Protocol):
            x: T

        class Eggs[T]:
            def __init__(self, x: T) -> None:
                self.x = x

        self.assertIsInstance(Eggs(42), Spam)
        with self.assertRaises(TypeError):
            issubclass(Eggs, Spam)
```

But I can't reproduce the failure in the REPL:

```pycon
>>> from typing import *
>>> @runtime_checkable
... class Spam[T](Protocol):
...     x: T
... 
...     
>>> class Eggs[T]:
...     def __init__(self, x: T) -> None:
...         self.x = x
... 
...         
>>> issubclass(Eggs, Spam)
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    issubclass(Eggs, Spam)
  File "C:\Users\alexw\coding\cpython\Lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "C:\Users\alexw\coding\cpython\Lib\typing.py", line 1875, in _proto_hook
    raise TypeError("Protocols with non-method members"
TypeError: Protocols with non-method members don't support issubclass()
```

**Comment by AlexWaygood** [comment] 2023-05-16 15:57
Anyway, I'll submit a PR without that test for now...

**Comment by AlexWaygood** [comment] 2023-05-16 16:12
Okay, cool. I'll enable automerge on my PR for now, as it definitely gets us closer to correct behaviour.

**Comment by JelleZijlstra** [comment] 2023-05-16 16:21
The issue you saw also reproduces for me without PEP 695 syntax. It seems to be due to the `_allow_reckless_class_checks` check, which somehow thinks the caller is `abc` if we're in a test, but not if we're in the REPL.

**Comment by AlexWaygood** [comment] 2023-05-16 16:22
Aha, so we've discovered a bug, it just isn't a new bug.

**Comment by JelleZijlstra** [comment] 2023-05-16 16:22
It's possible this bug was introduced by the fact that Generic is now a C class, haven't tried on 3.11 yet.

**Comment by AlexWaygood** [comment] 2023-05-16 16:29
Yes, looks like the bug is new in 3.12. Running this test file passes on 3.11, but not on `main`:

```py
import unittest
from typing import runtime_checkable, Generic, Protocol, TypeVar

T = TypeVar("T")

class TestProtocols(unittest.TestCase):
    def test_pep695_generic_protocol_noncallable_members(self):
        @runtime_checkable
        class Spam(Protocol[T]):
            x: T

        class Eggs(Generic[T]):
            def __init__(self, x: T) -> None:
                self.x = x

        self.assertIsInstance(Eggs(42), Spam)
        with self.assertRaises(TypeError):
            issubclass(Eggs, Spam)


if __name__ == "__main__":
    unittest.main()
```

**Comment by AlexWaygood** [comment] 2023-05-16 16:38
Easier to keep the discussion in one place, so I'm reopening so we can continue discussing the other bug

**Comment by JelleZijlstra** [comment] 2023-05-16 16:40
A few things I found:

- The reason why Alex saw different behavior in the REPL and a test is that it matters whether you call `isinstance()` first. The issue shows up only if call `isinstance()` before you call `issubclass()`.
- The issue reproduces on a commit on main before PEP 695 was merged, so it's not due to PEP 695.
- I'm bisecting now to find the culprit.

**Comment by JelleZijlstra** [comment] 2023-05-16 17:04
```
47753ecde21b79b5c5f11d883946fda2a340e427 is the first bad commit
commit 47753ecde21b79b5c5f11d883946fda2a340e427
Author: Alex Waygood <Alex.Waygood@Gmail.com>
Date:   Wed Apr 5 10:07:30 2023 +0100

    gh-74690: typing: Simplify and optimise `_ProtocolMeta.__instancecheck__` (#103159)

 Lib/typing.py | 14 +++-----------
 1 file changed, 3 insertions(+), 11 deletions(-)
```

**Comment by AlexWaygood** [comment] 2023-05-16 17:16
> ```
> 47753ecde21b79b5c5f11d883946fda2a340e427 is the first bad commit
> commit 47753ecde21b79b5c5f11d883946fda2a340e427
> Author: Alex Waygood <Alex.Waygood@Gmail.com>
> Date:   Wed Apr 5 10:07:30 2023 +0100
> 
>     gh-74690: typing: Simplify and optimise `_ProtocolMeta.__instancecheck__` (#103159)
> 
>  Lib/typing.py | 14 +++-----------
>  1 file changed, 3 insertions(+), 11 deletions(-)
> ```

(I am, again, working on a fix :)

**Comment by AlexWaygood** [comment] 2023-05-16 17:52
Incredible stuff:

```pycon
Python 3.12.0a7+ (heads/main:1163782868, May 16 2023, 18:09:28) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import *
>>> @runtime_checkable
... class Foo(Protocol):
...     x: int
...
>>> class Bar:
...     x = 42
...
>>> issubclass(Bar, Foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\coding\cpython\Lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\typing.py", line 1875, in _proto_hook
    raise TypeError("Protocols with non-method members"
TypeError: Protocols with non-method members don't support issubclass()
>>> isinstance(Bar(), Foo)
True
>>> issubclass(Bar, Foo)
False
```

**Comment by sunmy2019** [comment] 2023-05-16 17:53
The difference here is
```
_allow_reckless_class_checks()=False   <-- raise TypeError
_allow_reckless_class_checks()=True    <-- do not raise TypeError
```

`_allow_reckless_class_checks` checks the caller

```py
def _caller(depth=1, default="__main__"):
    try:
        return sys._getframemodulename(depth + 1) or default
    except AttributeError:  # For platforms without _getframemodulename()
        pass
    try:
        return sys._getframe(depth + 1).f_globals.get("__name__", default)
    except (AttributeError, ValueError):  # For platforms without _getframe()
        pass
    return None


def _allow_reckless_class_checks(depth=3):
    """Allow instance and class checks for special stdlib modules.

    The abc and functools modules indiscriminately call isinstance() and
    issubclass() on the whole MRO of a user class, which may contain protocols.
    """
    return _caller(depth) in {"abc", "functools", None}
```

**Comment by sunmy2019** [comment] 2023-05-16 18:05
Oh sorry, ignore my previous comment.

**Comment by sunmy2019** [comment] 2023-05-16 18:19
Confirmed that the code path that does not raise TypeError goes through L606. 
https://github.com/python/cpython/blob/03e3c340a0156891a036d6dbdb9e348108826255/Modules/_abc.c#L589-L608

@AlexWaygood You are right!

**Comment by AlexWaygood** [comment] 2023-05-16 18:20
@sunmy2019 thanks for checking!

**Comment by sunmy2019** [comment] 2023-05-16 18:39
Oh, now I see the whole picture!

1. `abc.ABCMeta` cache `__subclasscheck__` results if no exception occurs.
2. `Protocol` assigns a `__subclasshook__`, which raises or does not raise exceptions depending on the caller.
3. `_ProtocolMeta.__instancecheck__` calls the `__subclasshook__` in (2) (not raising exceptions), and the result is cached by (1)
4. User call (1), and accidentally get the cached result (not the exception).

**Comment by sunmy2019** [comment] 2023-05-16 19:08
More details:

2.

The `__subclasshook__` in `Protocol` utilizes `_allow_reckless_class_checks()`. In normal cases, it is
```
_caller(0)=typing
_caller(1)=typing
_caller(2)=abc   ABCMeta.__subclasscheck__
_caller(3)=__main__         <------- _allow_reckless_class_checks()=False
```
It then raises an exception.

In the problematic scenarios:
```
_caller(0)=typing
_caller(1)=typing
_caller(2)=abc     ABCMeta.__subclasscheck__
_caller(3)=abc     ABCMeta.__instancecheck__              <------- _allow_reckless_class_checks()=True
```
It does raise an exception.

**Closed as completed** 2023-05-17 23:43 UTC
Labels: type-bug, topic-typing
