### ISSUE TITLE
Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### ISSUE THREAD

**Issue by Srushhh1303** [python/cpython#111845] opened 2023-11-08 10:27 UTC
# Bug report

### Bug description:

import tkinter as tk

Output :-
Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
How to resolve this error ??
Receiving this error on MacOs new update of Sonoma

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by AlexWaygood** [comment] 2023-11-08 10:33
Duplicate of #110950

**Closed as not planned by AlexWaygood** 2023-11-08 10:33 UTC
Labels: type-bug, OS-mac
