### ISSUE TITLE
Use "import a.b" but a.b may not be what I want, even not a module

### ISSUE THREAD

**Issue by incloud02** [python/cpython#117314] opened 2024-03-28 07:26 UTC
# Bug report

### Bug description:

```python
# __init__py
from .b import os as b  # bug
# from a.b import os as b  # bug
# But when I use“from folder.a.b import os as b" in PyCharm, it is normal
# from .c import os as b  # normal

#b.py
import os

#c.py
import os

# main.py
import a.b
print(a.b)  # <module 'os' from '***'>
```
folder  
-main.py  
-a  
--\_\_init\_\_.py  
--b.py  
--c.py

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by incloud02** [comment] 2024-03-28 09:46
> It's not clear what behavior you consider a bug, and why. Why is `from .b import os as b` a bug? Why do you consider `from .c import os as b` normal? In both cases, what behavior were you expecting? What behavior did you observe? What commands were you running? What are the contents of b.py and c.py?
> 
> Please see https://www.chiark.greenend.org.uk/~sgtatham/bugs.html for how to improve your bug report.

I think the result of  `print(a.b)`  should be `<module 'a.b'>`  instead of `<module 'os'>`,because I am importing modules.

**Comment by ericvsmith** [comment] 2024-03-28 13:11
That's the way Python works. When you import `a.b`, `a.__init__` is run, which sets `a.b` to `os`.

Since this is working as designed I'm going to close this. If you need help in understanding how importing works, I suggest you ask on https://discuss.python.org/c/users/7.

**Closed as not planned by ericvsmith** 2024-03-28 13:11 UTC
Labels: type-bug
