### ISSUE TITLE
Add `make uninstall` in to make file

### ISSUE THREAD

**Issue by 1Codealot** [python/cpython#114369] opened 2024-01-21 07:26 UTC
# Feature or enhancement

### Proposal:

Hi.

Essentially I have kinda messed up my debian OS by installing python 3.12 from source and its kind of a pain to try and remove it.

I think adding a `make uninstall` into the makefile would be great.

Thank you

### Has this already been discussed elsewhere?

No response given

**Comment by corona10** [comment] 2024-01-21 07:29
cc @erlend-aasland

**Comment by erlend-aasland** [comment] 2024-01-21 08:52
Duplicate of #85874

**Closed as not planned by erlend-aasland** 2024-01-21 08:52 UTC
Labels: type-feature
