### ISSUE TITLE
Assertion failure in build on Windows

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#114547] opened 2024-01-25 08:44 UTC
# Crash report

I get this failure on debug 64-bit build on Windows:
```
Assertion failed: STACK_LEVEL() >= 1, file D:\py\cpython\Python\ceval.c, line 857                                                
```

**Comment by AlexWaygood** [comment] 2024-01-25 14:53
I can't reproduce on my Windows machine -- what exact command did you run to get the Assertion failure?

**Comment by Eclips4** [comment] 2024-01-25 16:37
Today I've hit the same error, and error will gone after ``git clean -fdx``. This obviously related to #114247, I saw the same error message in CI fails on Windows. So, all you need to do - run ``git clean -fdx`` and then rebuilt the interpreter.

**Comment by zooba** [comment] 2024-01-25 17:20
Yeah, this tends to happen when the PYC magic needs to be updated but wasn't. Cleaning up old .pyc files usually fixes it.

**Comment by terryjreedy** [comment] 2024-01-25 17:28
I had same failure.  Thanks for the fix, which worked for me also.  Can this be closed?  Does .pyc magic need bumping?

**Comment by zooba** [comment] 2024-01-25 18:23
Provided the magic has already been bumped since alpha 3, it doesn't need to be bumped again. Probably need to ask on #114247 though (at least to inform whoever made the change that they missed it, which ought to help them recognise in future when they need to increase the number).

**Comment by AlexWaygood** [comment] 2024-01-25 18:24
#114247 _did_ bump the magic number

**Comment by zooba** [comment] 2024-01-25 18:46
Huh, that's fun then.

Is it possible that @Eclips4 tested that branch at some point, possibly after the magic number update and before some other opcode changes? I just built before and after that change and didn't see any issue.

**Comment by Eclips4** [comment] 2024-01-25 18:52
> Is it possible that @Eclips4 tested that branch at some point, possibly after the magic number update and before some other opcode changes?

You're right.

**Comment by zooba** [comment] 2024-01-25 18:58
> You're right

Phew, that's a relief. It's a far better explanation than something else going wrong.

If @serhiy-storchaka can confirm the same, I suspect we can close this.

**Comment by serhiy-storchaka** [comment] 2024-01-25 20:17
I get this during building
```
PCbuild\build.bat -e -d -p x64
```
which prints this on terminal and show pop-up. After closing pop-up, the build is reported as successful, but running `python.bat` produces the same error.

I tried to clean the build
```
PCbuild\clean.bat -d -p x64 
```
but it did not help.

I removed all `*.pyc` files, but it did not help either.

I created a new worktree, and the build was successful there.

Now, I see that `PCbuild\clean.bat` did not clear `PCbuild\amd64` and `PCbuild\obj`. The remaining files:
<details>

```
D:\PY\CPYTHON\PCBUILD\AMD64
    LICENSE.txt
    pybuilddir.txt
    python313_d.dll.lastcodeanalysissucceeded
    pythonw_uwp_d.exe
    pythonw_uwp_d.ilk
    pythonw_uwp_d.pdb
    python_uwp_d.exe
    python_uwp_d.ilk
    python_uwp_d.pdb
    vcruntime140.dll
    vcruntime140_1.dll
    _freeze_module_d.exe
    _freeze_module_d.ilk
    _freeze_module_d.pdb
```

</details>

<details>

```
D:\PY\CPYTHON\PCBUILD\OBJ
├───313amd64_Debug
│   ├───liblzma
│   │   │   liblzma.log
│   │   │   liblzma_d.Build.CppClean.log
│   │   │   liblzma_d.lib.recipe
│   │   │   
│   │   └───liblzma.tlog
│   ├───pyexpat
│   │   │   pyexpat.log
│   │   │   pyexpat_d.Build.CppClean.log
│   │   │   pyexpat_d.pyd.recipe
│   │   │   
│   │   └───pyexpat.tlog
│   ├───pylauncher
│   │   │   pylauncher.log
│   │   │   py_d.Build.CppClean.log
│   │   │   py_d.exe.recipe
│   │   │   
│   │   └───pylauncher.tlog
│   ├───pyshellext
│   │   │   pyshellext.log
│   │   │   pyshellext_d.Build.CppClean.log
│   │   │   pyshellext_d.dll.recipe
│   │   │   
│   │   └───pyshellext.tlog
│   ├───python
│   │   │   python.log
│   │   │   python_d.Build.CppClean.log
│   │   │   python_d.exe.recipe
│   │   │   
│   │   └───python.tlog
│   ├───python3dll
│   │   │   python3dll.log
│   │   │   python3_d.Build.CppClean.log
│   │   │   python3_d.dll.recipe
│   │   │   
│   │   └───python3dll.tlog
│   ├───pythoncore
│   │   │   CodeAnalysisResultManifest.txt
│   │   │   gitbranch.txt
│   │   │   gittag.txt
│   │   │   gitversion.txt
│   │   │   posixmodule.nativecodeanalysis.sarif
│   │   │   python313_d.Build.CppClean.log
│   │   │   python313_d.dll.recipe
│   │   │   pythoncore.log
│   │   │   
│   │   └───pythoncore.tlog
│   ├───pythonw
│   │   │   pythonw.log
│   │   │   pythonw_d.Build.CppClean.log
│   │   │   pythonw_d.exe.recipe
│   │   │   
│   │   └───pythonw.tlog
│   ├───pythonw_uwp
│   │   │   pythonw_exe.res
│   │   │   pythonw_uwp.log
│   │   │   pythonw_uwp_d.Build.CppClean.log
│   │   │   pythonw_uwp_d.exe.recipe
│   │   │   python_uwp.obj
│   │   │   vc141.pdb
│   │   │   vc143.pdb
│   │   │   
│   │   └───pythonw_uwp.tlog
│   │           CL.command.1.tlog
│   │           Cl.items.tlog
│   │           CL.read.1.tlog
│   │           CL.write.1.tlog
│   │           link.command.1.tlog
│   │           link.read.1.tlog
│   │           link.write.1.tlog
│   │           pythonw_uwp.lastbuildstate
│   │           rc.command.1.tlog
│   │           rc.read.1.tlog
│   │           rc.write.1.tlog
│   │           
│   ├───python_uwp
│   │   │   python_exe.res
│   │   │   python_uwp.log
│   │   │   python_uwp.obj
│   │   │   python_uwp_d.Build.CppClean.log
│   │   │   python_uwp_d.exe.recipe
│   │   │   vc141.pdb
│   │   │   vc143.pdb
│   │   │   
│   │   └───python_uwp.tlog
│   │           CL.command.1.tlog
│   │           Cl.items.tlog
│   │           CL.read.1.tlog
│   │           CL.write.1.tlog
│   │           link.command.1.tlog
│   │           link.read.1.tlog
│   │           link.write.1.tlog
│   │           python_uwp.lastbuildstate
│   │           rc.command.1.tlog
│   │           rc.read.1.tlog
│   │           rc.write.1.tlog
│   │           
│   ├───pywlauncher
│   │   │   pywlauncher.log
│   │   │   pyw_d.Build.CppClean.log
│   │   │   pyw_d.exe.recipe
│   │   │   
│   │   └───pywlauncher.tlog
│   ├───select
│   │   │   select.log
│   │   │   select_d.Build.CppClean.log
│   │   │   select_d.pyd.recipe
│   │   │   
│   │   └───select.tlog
│   ├───sqlite3
│   │   │   sqlite3.log
│   │   │   sqlite3_d.Build.CppClean.log
│   │   │   sqlite3_d.dll.recipe
│   │   │   
│   │   └───sqlite3.tlog
│   ├───unicodedata
│   │   │   unicodedata.log
│   │   │   unicodedata_d.Build.CppClean.log
│   │   │   unicodedata_d.pyd.recipe
│   │   │   
│   │   └───unicodedata.tlog
│   ├───venvlauncher
│   │   │   venvlauncher.log
│   │   │   venvlauncher_d.Build.CppClean.log
│   │   │   venvlauncher_d.exe.recipe
│   │   │   
│   │   └───venvlauncher.tlog
│   ├───venvwlauncher
│   │   │   venvwlauncher.log
│   │   │   venvwlauncher_d.Build.CppClean.log
│   │   │   venvwlauncher_d.exe.recipe
│   │   │   
│   │   └───venvwlauncher.tlog
│   ├───winsound
│   │   │   winsound.log
│   │   │   winsound_d.Build.CppClean.log
│   │   │   winsound_d.pyd.recipe
│   │   │   
│   │   └───winsound.tlog
│   ├───_asyncio
│   │   │   _asyncio.log
│   │   │   _asyncio_d.Build.CppClean.log
│   │   │   _asyncio_d.pyd.recipe
│   │   │   
│   │   └───_asyncio.tlog
│   ├───_bz2
│   │   │   _bz2.log
│   │   │   _bz2_d.Build.CppClean.log
│   │   │   _bz2_d.pyd.recipe
│   │   │   
│   │   └───_bz2.tlog
│   ├───_ctypes
│   │   │   _ctypes.log
│   │   │   _ctypes_d.Build.CppClean.log
│   │   │   _ctypes_d.pyd.recipe
│   │   │   
│   │   └───_ctypes.tlog
│   ├───_ctypes_test
│   │   │   _ctypes_test.log
│   │   │   _ctypes_test_d.Build.CppClean.log
│   │   │   _ctypes_test_d.pyd.recipe
│   │   │   
│   │   └───_ctypes_test.tlog
│   ├───_decimal
│   │   │   _decimal.log
│   │   │   _decimal_d.Build.CppClean.log
│   │   │   _decimal_d.pyd.recipe
│   │   │   
│   │   └───_decimal.tlog
│   ├───_elementtree
│   │   │   _elementtree.log
│   │   │   _elementtree_d.Build.CppClean.log
│   │   │   _elementtree_d.pyd.recipe
│   │   │   
│   │   └───_elementtree.tlog
│   ├───_freeze_module
│   │   │   abc.g.h
│   │   │   abstract.obj
│   │   │   action_helpers.obj
│   │   │   asdl.obj
│   │   │   assemble.obj
│   │   │   ast.obj
│   │   │   ast_opt.obj
│   │   │   ast_unparse.obj
│   │   │   atexitmodule.obj
│   │   │   bltinmodule.obj
│   │   │   boolobject.obj
│   │   │   bootstrap_hash.obj
│   │   │   bufferedio.obj
│   │   │   bytearrayobject.obj
│   │   │   bytesio.obj
│   │   │   bytesobject.obj
│   │   │   bytes_methods.obj
│   │   │   call.obj
│   │   │   capsule.obj
│   │   │   cellobject.obj
│   │   │   ceval.obj
│   │   │   ceval_gil.obj
│   │   │   classobject.obj
│   │   │   codecs.g.h
│   │   │   codecs.obj
│   │   │   codeobject.obj
│   │   │   compile.obj
│   │   │   complexobject.obj
│   │   │   config_minimal.obj
│   │   │   context.obj
│   │   │   descrobject.obj
│   │   │   dictobject.obj
│   │   │   dtoa.obj
│   │   │   dynamic_annotations.obj
│   │   │   dynload_win.obj
│   │   │   enumobject.obj
│   │   │   errors.obj
│   │   │   exceptions.obj
│   │   │   executor.obj
│   │   │   faulthandler.obj
│   │   │   fileio.obj
│   │   │   fileobject.obj
│   │   │   fileutils.obj
│   │   │   floatobject.obj
│   │   │   flowgraph.obj
│   │   │   formatter_unicode.obj
│   │   │   frame.obj
│   │   │   frameobject.obj
│   │   │   frozen_only.g.h
│   │   │   funcobject.obj
│   │   │   future.obj
│   │   │   gcmodule.obj
│   │   │   genericaliasobject.obj
│   │   │   genericpath.g.h
│   │   │   genobject.obj
│   │   │   getargs.obj
│   │   │   getbuildinfo.obj
│   │   │   getcompiler.obj
│   │   │   getcopyright.obj
│   │   │   getopt.obj
│   │   │   getpath.g.h
│   │   │   getpath_noop.obj
│   │   │   getplatform.obj
│   │   │   getversion.obj
│   │   │   hamt.obj
│   │   │   hashtable.obj
│   │   │   import.obj
│   │   │   importdl.obj
│   │   │   importlib.machinery.g.h
│   │   │   importlib.util.g.h
│   │   │   importlib._bootstrap.g.h
│   │   │   importlib._bootstrap_external.g.h
│   │   │   initconfig.obj
│   │   │   instrumentation.obj
│   │   │   interpreteridobject.obj
│   │   │   intrinsics.obj
│   │   │   invalid_parameter_handler.obj
│   │   │   io.g.h
│   │   │   iobase.obj
│   │   │   iterobject.obj
│   │   │   legacy_tracing.obj
│   │   │   listobject.obj
│   │   │   longobject.obj
│   │   │   marshal.obj
│   │   │   memoryobject.obj
│   │   │   methodobject.obj
│   │   │   modsupport.obj
│   │   │   moduleobject.obj
│   │   │   msvcrtmodule.obj
│   │   │   myreadline.obj
│   │   │   mysnprintf.obj
│   │   │   mystrtoul.obj
│   │   │   namespaceobject.obj
│   │   │   ntpath.g.h
│   │   │   object.obj
│   │   │   obmalloc.obj
│   │   │   odictobject.obj
│   │   │   optimizer.obj
│   │   │   os.g.h
│   │   │   parser.obj
│   │   │   pathconfig.obj
│   │   │   pegen.obj
│   │   │   pegen_errors.obj
│   │   │   peg_api.obj
│   │   │   perf_trampoline.obj
│   │   │   picklebufobject.obj
│   │   │   posixmodule.obj
│   │   │   posixpath.g.h
│   │   │   preconfig.obj
│   │   │   pyarena.obj
│   │   │   pyctype.obj
│   │   │   pyfpe.obj
│   │   │   pyhash.obj
│   │   │   pylifecycle.obj
│   │   │   pymath.obj
│   │   │   pystate.obj
│   │   │   pystrcmp.obj
│   │   │   pystrhex.obj
│   │   │   pystrtod.obj
│   │   │   Python-ast.obj
│   │   │   Python-tokenize.obj
│   │   │   pythonrun.obj
│   │   │   pytime.obj
│   │   │   rangeobject.obj
│   │   │   runpy.g.h
│   │   │   setobject.obj
│   │   │   signalmodule.obj
│   │   │   site.g.h
│   │   │   sliceobject.obj
│   │   │   specialize.obj
│   │   │   stat.g.h
│   │   │   stringio.obj
│   │   │   string_parser.obj
│   │   │   structmember.obj
│   │   │   structseq.obj
│   │   │   suggestions.obj
│   │   │   symtable.obj
│   │   │   sysmodule.obj
│   │   │   textio.obj
│   │   │   thread.obj
│   │   │   timemodule.obj
│   │   │   token.obj
│   │   │   tokenizer.obj
│   │   │   traceback.obj
│   │   │   tracemalloc.obj
│   │   │   tupleobject.obj
│   │   │   typeobject.obj
│   │   │   typevarobject.obj
│   │   │   unicodectype.obj
│   │   │   unicodeobject.obj
│   │   │   unionobject.obj
│   │   │   vc141.pdb
│   │   │   vc143.pdb
│   │   │   weakrefobject.obj
│   │   │   winconsoleio.obj
│   │   │   winreg.obj
│   │   │   zipimport.g.h
│   │   │   _collections_abc.g.h
│   │   │   _freeze_module.log
│   │   │   _freeze_module.obj
│   │   │   _freeze_module_d.Build.CppClean.log
│   │   │   _freeze_module_d.exe.recipe
│   │   │   _iomodule.obj
│   │   │   _sitebuiltins.g.h
│   │   │   _tracemalloc.obj
│   │   │   _warnings.obj
│   │   │   __hello__.g.h
│   │   │   __phello__.g.h
│   │   │   __phello__.ham.eggs.g.h
│   │   │   __phello__.ham.g.h
│   │   │   __phello__.spam.g.h
│   │   │   
│   │   └───_freeze_module.tlog
│   │           CL.command.1.tlog
│   │           Cl.items.tlog
│   │           CL.read.1.tlog
│   │           CL.write.1.tlog
│   │           link.command.1.tlog
│   │           link.read.1.tlog
│   │           link.write.1.tlog
│   │           _freeze_module.lastbuildstate
│   │           
│   ├───_hashlib
│   │   │   _hashlib.log
│   │   │   _hashlib_d.Build.CppClean.log
│   │   │   _hashlib_d.pyd.recipe
│   │   │   
│   │   └───_hashlib.tlog
│   ├───_lzma
│   │   │   _lzma.log
│   │   │   _lzma_d.Build.CppClean.log
│   │   │   _lzma_d.pyd.recipe
│   │   │   
│   │   └───_lzma.tlog
│   ├───_multiprocessing
│   │   │   _multiprocessing.log
│   │   │   _multiprocessing_d.Build.CppClean.log
│   │   │   _multiprocessing_d.pyd.recipe
│   │   │   
│   │   └───_multiprocessing.tlog
│   ├───_overlapped
│   │   │   _overlapped.log
│   │   │   _overlapped_d.Build.CppClean.log
│   │   │   _overlapped_d.pyd.recipe
│   │   │   
│   │   └───_overlapped.tlog
│   ├───_queue
│   │   │   _queue.log
│   │   │   _queue_d.Build.CppClean.log
│   │   │   _queue_d.pyd.recipe
│   │   │   
│   │   └───_queue.tlog
│   ├───_socket
│   │   │   _socket.log
│   │   │   _socket_d.Build.CppClean.log
│   │   │   _socket_d.pyd.recipe
│   │   │   
│   │   └───_socket.tlog
│   ├───_sqlite3
│   │   │   _sqlite3.log
│   │   │   _sqlite3_d.Build.CppClean.log
│   │   │   _sqlite3_d.pyd.recipe
│   │   │   
│   │   └───_sqlite3.tlog
│   ├───_ssl
│   │   │   _ssl.log
│   │   │   _ssl_d.Build.CppClean.log
│   │   │   _ssl_d.pyd.recipe
│   │   │   
│   │   └───_ssl.tlog
│   ├───_testbuffer
│   │   │   _testbuffer.log
│   │   │   _testbuffer_d.Build.CppClean.log
│   │   │   _testbuffer_d.pyd.recipe
│   │   │   
│   │   └───_testbuffer.tlog
│   ├───_testcapi
│   │   │   _testcapi.log
│   │   │   _testcapi_d.Build.CppClean.log
│   │   │   _testcapi_d.pyd.recipe
│   │   │   
│   │   └───_testcapi.tlog
│   ├───_testclinic
│   │   │   _testclinic.log
│   │   │   _testclinic_d.Build.CppClean.log
│   │   │   _testclinic_d.pyd.recipe
│   │   │   
│   │   └───_testclinic.tlog
│   ├───_testclinic_limited
│   │   │   _testclinic_limited_d.Build.CppClean.log
│   │   │   _testclinic_limited_d.pyd.recipe
│   │   │   
│   │   └───_testcli.01FDF29A.tlog
│   ├───_testconsole
│   │   │   _testconsole.log
│   │   │   _testconsole_d.Build.CppClean.log
│   │   │   _testconsole_d.pyd.recipe
│   │   │   
│   │   └───_testconsole.tlog
│   ├───_testembed
│   │   │   _testembed.log
│   │   │   _testembed_d.Build.CppClean.log
│   │   │   _testembed_d.exe.recipe
│   │   │   
│   │   └───_testembed.tlog
│   ├───_testimportmultiple
│   │   │   _testimportmultiple.log
│   │   │   _testimportmultiple_d.Build.CppClean.log
│   │   │   _testimportmultiple_d.pyd.recipe
│   │   │   
│   │   └───_testimp.36D0C52C.tlog
│   ├───_testinternalcapi
│   │   │   _testinternalcapi.log
│   │   │   _testinternalcapi_d.Build.CppClean.log
│   │   │   _testinternalcapi_d.pyd.recipe
│   │   │   
│   │   └───_testint.900342D7.tlog
│   ├───_testmultiphase
│   │   │   _testmultiphase.log
│   │   │   _testmultiphase_d.Build.CppClean.log
│   │   │   _testmultiphase_d.pyd.recipe
│   │   │   
│   │   └───_testmultiphase.tlog
│   ├───_testsinglephase
│   │   │   _testsinglephase.log
│   │   │   _testsinglephase_d.Build.CppClean.log
│   │   │   _testsinglephase_d.pyd.recipe
│   │   │   
│   │   └───_testsinglephase.tlog
│   ├───_tkinter
│   │   │   _tkinter.log
│   │   │   _tkinter_d.Build.CppClean.log
│   │   │   _tkinter_d.pyd.recipe
│   │   │   
│   │   └───_tkinter.tlog
│   ├───_uuid
│   │   │   _uuid.log
│   │   │   _uuid_d.Build.CppClean.log
│   │   │   _uuid_d.pyd.recipe
│   │   │   
│   │   └───_uuid.tlog
│   ├───_wmi
│   │   │   _wmi.log
│   │   │   _wmi_d.Build.CppClean.log
│   │   │   _wmi_d.pyd.recipe
│   │   │   
│   │   └───_wmi.tlog
│   └───_zoneinfo
│       │   _zoneinfo.log
│       │   _zoneinfo_d.Build.CppClean.log
│       │   _zoneinfo_d.pyd.recipe
│       │   
│       └───_zoneinfo.tlog
├───313win32_Debug
│   └───_freeze_module
│       │   deepfreeze_mappings.txt
│       │   pyconfig.h
│       │   _freeze_module_d.Build.CppClean.log
│       │   _freeze_module_d.exe.recipe
│       │   
│       └───_freeze_module.tlog
└───313_frozen
    └───Python
        └───frozen_modules
```

</details>

**Comment by zooba** [comment] 2024-01-25 20:41
Looks like you're getting x64 `_freeze_module` when it should be x86 by default, and if that's not rebuilding properly then you'll keep generating invalid bytecode from a previous build. I'm not sure how that would happen or how to reproduce it, but I can take a look through the cleanup code in case something jumps out.

If you have any ideas for anything else you might've done that's unusual, it might help. BTW, `-e -p x64` are the default options for build.bat, so you only need to pass `-d`.

**Comment by serhiy-storchaka** [comment] 2024-01-26 10:07
I did not do anything unusual. Few weeks ago I build it successfully, and now I just updated sources from GitHub and rebuild.

**Comment by terryjreedy** [comment] 2024-01-27 04:57
There was definitely a recent anomaly.  I have recompiled every few days for a year and a half (and a couple of days ago) without any problem.

**Comment by Eclips4** [comment] 2024-09-23 16:11
Is this still happening?

**Closed as not planned** 2024-09-23 17:00 UTC
Labels: OS-windows, build, type-crash, 3.13
