### ISSUE TITLE
Multiple ':envvar:' check warnings in Doc/using/windows.rst

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#103756] opened 2023-04-24 13:53 UTC
PR #103745 changed a spelling in Doc/using/windows.rst.  Upon encountering texts of the form ":envvar:\`XYZ\`", GitHub Actions / Docs emitted several checkwarnings of the form `'envvar' reference target not found: XYZ` where XYZ is `PATH` (multiple times),  `PATHEXT`, `TEMP`, or `%APPDATA%`.  I suspect other docs might have the same issues.

**Comment by aelsayed95** [comment] 2023-04-25 21:23
Yes, running `sphinx` in nitpicky mode, I similar errors in many files where `:envvar:` is used. It seems many env vars are missing definitions.

For `windows.rst` specifically, I see two types of undefined env-vars that generate errors:
1. Generic env vars:  `PATH`, `TEMP`, `%APPDATA%`
2. Env vars that are related to the windows python launcher or related to windows in general: `PYLAUNCHER_DRYRUN`, `PYLAUNCHER_ALLOW_INSTALL`, `PYLAUNCHER_ALWAYS_INSTALL`, `PYLAUNCHER_DEBUG`, `PATHEXT`

Group 2 needs definitions to allow `:envvar:` to link correctly to the respective env var's usage. Maybe a definition section can be added to `Doc/using/windows.rst`

For Group 1, it seems reasonable to just omit the `:envvar:` directive so that `Sphinx` doesn't attempt to find references for  and just use double ticks instead around the env var name instead?

**Comment by AA-Turner** [comment] 2023-09-22 19:27
Closing as a duplicate of #101100.

**Closed as not planned by AA-Turner** 2023-09-22 19:27 UTC
Labels: type-bug, docs
