### ISSUE TITLE
Hitting Assert for Managed Static Types During Subinterpreter Finalization

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#120765] opened 2024-06-19 22:19 UTC
# Bug report

### Bug description:

```
$ ./python
Python 3.14.0a0 (heads/main:9f741e55c16, Jun 18 2024, 16:38:50) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _interpreters
>>> _interpreters.create()
>>> exit
python: Objects/typeobject.c:307: managed_static_type_state_clear: Assertion `!_PyRuntime.types.managed_static.types[full_index].interp_count' failed.
Aborted (core dumped)
```

### CPython versions tested on:

CPython main branch

**Comment by ericsnowcurrently** [comment] 2024-06-19 23:02
Ah, I see the problem.  The code currently assumes that when the main interpreter is finalized, that no other interpreters are still around.  I'll have to fix that.

**Comment by Eclips4** [comment] 2024-06-20 19:10
Isn't it a duplicate of #113433?

**Comment by ericsnowcurrently** [comment] 2024-06-20 21:09
It's definitely closely related (and the fix for gh-113433 will fix it), but it is a slightly different problem.

**Closed as duplicate** 2024-06-26 21:57 UTC
Labels: type-crash, topic-subinterpreters, 3.13, 3.14
