### ISSUE TITLE
Test `test_c_locale_coercion` fails on macos Sonoma

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#109989] opened 2023-09-27 21:34 UTC
Repro: `./python.exe -m test test_c_locale_coercion -v`

Short output:

```
======================================================================
FAIL: test_external_target_locale_configuration (test.test_c_locale_coercion.LocaleConfigurationTests.test_external_target_locale_configuration) (env_var='LC_CTYPE', configured_locale='UTF-8')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_c_locale_coercion.py", line 273, in test_external_target_locale_configuration
    self._check_child_encoding_details(var_dict,
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_c_locale_coercion.py", line 230, in _check_child_encoding_details
    self.assertEqual(encoding_details, expected_details)
AssertionError: {'fse[36 chars]f-8:strict', 'stdout_info': 'utf-8:strict', 's[80 chars]: ''} != {'fse[36 chars]f-8:surrogateescape', 'stdout_info': 'utf-8:su[98 chars]: ''}
  {'fsencoding': 'utf-8',
   'lang': '',
   'lc_all': '',
   'lc_ctype': 'UTF-8',
   'stderr_info': 'utf-8:backslashreplace',
-  'stdin_info': 'utf-8:strict',
?                         ^^ ^

+  'stdin_info': 'utf-8:surrogateescape',
?                        ++++++ ^^^ ^^^

-  'stdout_info': 'utf-8:strict'}
?                          ^^ ^

+  'stdout_info': 'utf-8:surrogateescape'}
?                         ++++++ ^^^ ^^^


----------------------------------------------------------------------
Ran 7 tests in 0.883s

FAILED (failures=51)
test test_c_locale_coercion failed
test_c_locale_coercion failed (51 failures)

== Tests result: FAILURE ==

1 test failed:
    test_c_locale_coercion

Total duration: 924 ms
Total tests: run=7 failures=51
Total test files: run=1/1 failed=1
Result: FAILURE
```

Full output is attached below.
[out.txt](https://github.com/python/cpython/files/12743468/out.txt)

### Linked PRs
* gh-113378
* gh-113398
* gh-113399

**Comment by ronaldoussoren** [comment] 2023-09-28 18:06
The test passes for me, and AFAIC I get the same encodings in the headers as you (see details below).  The only locale related environment variable is ``LC_CTYPE=UTF-8``. 

<details><summary>Details</summary>
<p>

```
== CPython 3.13.0a0 (heads/main-dirty:91fb8daa24, Sep 28 2023, 19:47:28) [Clang 15.0.0 (clang-1500.0.40.1)]
== macOS-14.0-arm64-arm-64bit little-endian
== Python build: debug
== cwd: /Users/ronald/Projects/Forks/cpython-upstream/build/build/test_python_worker_5207æ
== CPU count: 8
== encodings: locale=UTF-8, FS=utf-8
== resources: (all disabled, use -u option)

0:00:00 load avg: 2.71 Run 1 test sequentially
0:00:00 load avg: 2.71 [1/1] test_c_locale_coercion
AVAILABLE_TARGETS = ['UTF-8']
EXPECTED_C_LOCALE_EQUIVALENTS = ['C', 'invalid.ascii']
EXPECTED_C_LOCALE_STREAM_ENCODING = 'ascii'
EXPECTED_C_LOCALE_FS_ENCODING = 'utf-8'
EXPECT_COERCION_IN_DEFAULT_LOCALE = True
_C_UTF8_LOCALES = ('C.UTF-8', 'C.utf8', 'UTF-8')
_check_nl_langinfo_CODESET = False
test_LC_ALL_set_to_C (test.test_c_locale_coercion.LocaleCoercionTests.test_LC_ALL_set_to_C) ... ok
test_PYTHONCOERCECLOCALE_not_set (test.test_c_locale_coercion.LocaleCoercionTests.test_PYTHONCOERCECLOCALE_not_set) ... ok
test_PYTHONCOERCECLOCALE_not_zero (test.test_c_locale_coercion.LocaleCoercionTests.test_PYTHONCOERCECLOCALE_not_zero) ... ok
test_PYTHONCOERCECLOCALE_set_to_one (test.test_c_locale_coercion.LocaleCoercionTests.test_PYTHONCOERCECLOCALE_set_to_one) ... skipped 'coerced LC_CTYPE locale: UTF-8'
test_PYTHONCOERCECLOCALE_set_to_warn (test.test_c_locale_coercion.LocaleCoercionTests.test_PYTHONCOERCECLOCALE_set_to_warn) ... ok
test_PYTHONCOERCECLOCALE_set_to_zero (test.test_c_locale_coercion.LocaleCoercionTests.test_PYTHONCOERCECLOCALE_set_to_zero) ... ok
test_external_target_locale_configuration (test.test_c_locale_coercion.LocaleConfigurationTests.test_external_target_locale_configuration) ... ok

----------------------------------------------------------------------
Ran 7 tests in 0.927s

OK (skipped=1)

== Tests result: SUCCESS ==
```

</p>
</details>

**Comment by sobolevn** [comment] 2023-12-05 13:30
It still fails for me:

```
» env | grep PYTHONIOENCODING
PYTHONIOENCODING=UTF-8

» ./python.exe -m test test_c_locale_coercion   
Using random seed: 4256789499
0:00:00 load avg: 3.07 Run 1 test sequentially
0:00:00 load avg: 3.07 [1/1] test_c_locale_coercion
test test_c_locale_coercion failed -- multiple errors occurred; run in verbose mode for details
test_c_locale_coercion failed (51 failures)

== Tests result: FAILURE ==

1 test failed:
    test_c_locale_coercion

Total duration: 903 ms
Total tests: run=7 failures=51
Total test files: run=1/1 failed=1
Result: FAILURE
```

Looks like `PYTHONIOENCODING` is indeed related:

```
» unset PYTHONIOENCODING
                                                                                                                                              
» ./python.exe -m test test_c_locale_coercion
Using random seed: 554831913
0:00:00 load avg: 2.19 Run 1 test sequentially
0:00:00 load avg: 2.19 [1/1] test_c_locale_coercion

== Tests result: SUCCESS ==

1 test OK.

Total duration: 843 ms
Total tests: run=7
Total test files: run=1/1
Result: SUCCESS
```

**Comment by ronaldoussoren** [comment] 2023-12-05 13:50
I can reproduce this with setting ``PYTHONIOENCODING`` to ``UTF-8``.  

This patch "fixes" the test failures, but I'm far from convinced that this is the right fix. There would at the very least need to be new tests that very the behaviour when ``PYTHONIOENCODING`` is set.

```diff
diff --git a/Lib/test/test_c_locale_coercion.py b/Lib/test/test_c_locale_coercion.py
index 71f934756e..bd103a00e8 100644
--- a/Lib/test/test_c_locale_coercion.py
+++ b/Lib/test/test_c_locale_coercion.py
@@ -257,6 +257,7 @@ def test_external_target_locale_configuration(self):
             "LC_CTYPE": "",
             "LC_ALL": "",
             "PYTHONCOERCECLOCALE": "",
+            "PYTHONIOENCODING": "",
         }
         for env_var in ("LANG", "LC_CTYPE"):
             for locale_to_set in AVAILABLE_TARGETS:
@@ -316,6 +317,7 @@ def _check_c_locale_coercion(self,
             "LC_CTYPE": "",
             "LC_ALL": "",
             "PYTHONCOERCECLOCALE": "",
+            "PYTHONIOENCODING": "",
         }
         base_var_dict.update(extra_vars)
         if coerce_c_locale is not None:
@@ -348,7 +350,8 @@ def _check_c_locale_coercion(self,
             for env_var in ("LANG", "LC_CTYPE"):
                 with self.subTest(env_var=env_var,
                                   nominal_locale=locale_to_set,
-                                  PYTHONCOERCECLOCALE=coerce_c_locale):
+                                  PYTHONCOERCECLOCALE=coerce_c_locale,
+                                  PYTHONIOENCODING=""):
                     var_dict = base_var_dict.copy()
                     var_dict[env_var] = locale_to_set
                     # Check behaviour on successful coercion
```

**Comment by ronaldoussoren** [comment] 2023-12-05 14:14
Some more research:
- PYTHONCOERCECLOCALE is handled in Python/preconfig.c
- PYTHONIOENCODING is handled in Python/initconfig.c, in particular in config_init_stdio_encoding (see below)

https://github.com/python/cpython/blob/8cdfee1bb902fd1e38d79170b751ef13a0907262/Python/initconfig.c#L1978-L2059

[PEP 538](https://peps.python.org/pep-0538/) introduced PYTHONCOERCECLOCALE and does not mention how the two settings should interact.  That said, the current behaviour is present in at least 3.9 (the earliest version I can easily test) and should IMHO be considered as correct as changing will likely cause breakage.

Looks like my patch that suppressed the test failure by unsetting ``PYTHONIOENCODING`` is the best way to fix this after all, although ideally with a new test that checks behaviour when using both variables.

@ncoghlan  and @methane, what's your opinion on the correct fix for this issue?

**Closed as completed** 2023-12-23 20:58 UTC
Labels: type-bug, tests, OS-mac
