### ISSUE TITLE
Finalization of non-exhausted asynchronous generators is deferred

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#88684] opened 2021-06-27 09:11 UTC
BPO | [44518](https://bugs.python.org/issue44518)
--- | :---
Nosy | @gvanrossum, @asvetlov, @markshannon, @serhiy-storchaka, @1st1, @gvanrossum

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-27.09:11:32.621>
labels = ['interpreter-core', '3.11', '3.9', '3.10', 'performance']
title = 'Finalization of non-exhausted asynchronous generators is deferred'
updated_at = <Date 2021-06-28.18:33:50.454>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-28.18:33:50.454>
actor = 'gvanrossum'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-06-27.09:11:32.621>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 44518
keywords = []
message_count = 6.0
messages = ['396569', '396610', '396611', '396644', '396650', '396659']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'asvetlov', 'Mark.Shannon', 'serhiy.storchaka', 'yselivanov', 'Guido.van.Rossum']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue44518'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by kumaraditya303** [comment] 2022-06-20 08:33
The extra reference is required so that the event loop can finalize the generator in the correct context. The issue is that once the generator is about to be finalized, the event loop creates a new task to finalize it in the context but since there are no awaits after iterating over the generator the task is pending.

The following script finalizes it properly as it add a sleep to switch the tasks and run the finalizer.

```py
async def gen():
    try:
        yield 1
    finally:
        print('finalize inner')

async def func():
    try:
        async for x in gen():
            break
        await asyncio.sleep(0.1) # Switch task and run the finalizer 
    finally:
        print('finalize outer')

import asyncio
asyncio.run(func())
print('END')
```

Output:
```console
finalize inner
finalize outer
END
```

**Comment by kumaraditya303** [comment] 2022-06-20 08:59
The following example demonstrates the number of context switches required to run the finalizer:

```py
async def gen():
    try:
        yield 1
    finally:
        print('finalize inner')

async def func():
    try:
        async for x in gen():
            break
        # Schedules callback to create a task on next loop iteration 
    finally:
        await asyncio.sleep(0) # Creates a task to finalize gen
        await asyncio.sleep(0) # Run the task to finalize gen
        print('finalize outer')

import asyncio
asyncio.run(func())
print('END')
``` 
Output:
```console
finalize inner
finalize outer
END
```

**Comment by kumaraditya303** [comment] 2022-07-17 14:03
This would probably require something like https://peps.python.org/pep-0533/

**Comment by gvanrossum** [comment] 2022-07-17 14:36
Could you implement a prototype? That might help the PEP move forward. @njs @1st1

**Comment by graingert** [comment] 2022-07-19 21:05
running it with plain coroutines results in:

```python
import threading

async def gen():
    try:
        yield 1
    finally:
        print('finalize inner')

async def func():
    try:
        async for x in gen():
            break
    finally:
        print('finalize outer')

import threading

coro = func()
coro.send(None)
```

```pytb
finalize inner
finalize outer
Traceback (most recent call last):
  File "/home/graingert/projects/cpython/demo.py", line 19, in <module>
    coro.send(None)
StopIteration
```

**Comment by gvanrossum** [comment] 2022-07-19 21:06
That's a rather literalist interpretation of my question. :-) I meant whether you can come up with a repro without an event loop framework, since that would presumably make reasoning about the root cause of the problem easier.

**Comment by graingert** [comment] 2022-07-19 21:12
trio documents a one-tick finalization window here: https://github.com/python-trio/trio/blob/35319b3d4b881032416bfd733e0ac5239ce4c46d/trio/_core/_asyncgens.py#L26-L30

**Comment by graingert** [comment] 2022-07-19 21:27
> In PyPy "finalize inner" is not printed at all.

This looks like it could be an asyncio bug - asyncio should use the firstiter hook to keep a reference to generators that need shutting down

**Comment by graingert** [comment] 2022-07-19 21:45
> In PyPy "finalize inner" is not printed at all.

seems that got fixed:

```python
import threading
import trio
import asyncio

async def gen(runner):
    try:
        yield 1
    finally:
        print(f'{runner=} finalize inner')

async def func(runner):
    try:
        async for x in gen(runner):
            break
    finally:
        print(f'{runner=} finalize outer')

print(f"{trio.run(func, 'trio')=}")
print(f"{asyncio.run(func('asyncio'))=}")
print(f"{func('manual').send(None)=}")  # on pypy3 this doesn't print finalize inner
```

prints:

```
$ pypy3.8 demo.py
runner='trio' finalize outer
runner='trio' finalize inner
trio.run(func, 'trio')=None
runner='asyncio' finalize outer
runner='asyncio' finalize inner
asyncio.run(func('asyncio'))=None
runner='manual' finalize outer
Traceback (most recent call last):
  File "demo.py", line 20, in <module>
    print(f"{func('manual').send(None)=}")
StopIteration
```

**Comment by kumaraditya303** [comment] 2023-04-16 07:28
The behaviour cannot be changed without significant  changes  to the interpreter. The documentation will be handled for this as part of https://github.com/python/cpython/issues/100108 so closing.

**Closed as not planned by kumaraditya303** 2023-04-16 07:28 UTC
Labels: type-bug, topic-asyncio, interpreter-core, 3.11, 3.10, 3.12

**Comment by kumaraditya303** [comment] 2023-04-16 07:44
For anyone who comes here for a possible fix which always works:
```py
import contextlib

async def gen():
    try:
        yield 1
    finally:
        print('finalize inner')

async def func():
    try:
        async with contextlib.aclosing(gen()) as g:
            async for x in g:
                break
    finally:
        print('finalize outer')

import asyncio
asyncio.run(func())
print('END')
```
