### ISSUE TITLE
TimedRotatingFileHandler not working in the desired way.

### ISSUE THREAD

**Issue by hf-16** [python/cpython#104792] opened 2023-05-23 07:30 UTC
I am using the following setting:
time_handler = TimedRotatingFileHandler(os.path.join(logger_file_path, logger_file_name), when="w0")

This should rotate logs every Monday, however the issue here is that even though the logs rotate every Monday but the log file has incomplete logs. What is the solution for this? I have this on my development server and the log file for one week should have a considerable number of logs in it, however, mine just has a total of 15 lines. 

I have tried setting the delay parameter to False as well, but I am still facing this issue with my log files not having the complete logs. How to go about this?

**Comment by ericvsmith** [comment] 2023-05-23 17:01
What does "the log file has incomplete logs" mean? Please give an example, and show all of your code that configures the log files and code that generates the log messages. If you produce a simple working example we could run, that would be helpful.

**Comment by vsajip** [comment] 2024-02-15 20:19
Well, I can't seem to reproduce what you're seeing - it seems to work as expected with this script:
```python
# timed_test_3.py
import logging
from logging.handlers import TimedRotatingFileHandler
import random
import time


logger = logging.getLogger()
path = "logs/timed_test_3.log"

formatter = logging.Formatter("[%(asctime)s][%(levelname)s][%(message)s]", "%a %Y-%m-%d %H:%M:%S")
th = TimedRotatingFileHandler(filename=path, when="w0")
th.setFormatter(formatter)

logger.addHandler(th)
logger.setLevel(logging.INFO)

i = 1
while True:
    logger.info(f"Message: %10s", i)
    i += 1
    delay_secs = random.randint(30, 60)
    time.sleep(delay_secs)

```
Here are the results after a couple of weeks:
```console
p$ first_and_last logs/timed_test_3.log*
logs/timed_test_3.log::
[Tue 2024-02-13 00:00:31][INFO][Message:       2359]
[Thu 2024-02-15 20:08:15][INFO][Message:       2022]
logs/timed_test_3.log.2024-01-30::
[Tue 2024-01-30 18:26:03][INFO][Message:          1]
[Mon 2024-02-05 23:59:31][INFO][Message:        454]
logs/timed_test_3.log.2024-02-06::
[Tue 2024-02-06 00:00:06][INFO][Message:        455]
[Mon 2024-02-12 23:59:43][INFO][Message:       2358]
```
where the `first_and_last` script just prints the first and last lines in a file. The apparent anomaly in `timed_test_3.log` (message number going from 2359 to 2022) is because the machine was restarted yesterday evening and the script started logging again from message number 1.

You might need to pare your code down to get to a minimal standalone script like mine, but which demonstrates the problem.

**Comment by vsajip** [comment] 2024-02-28 09:15
I'll close this, as no feedback has been received.

**Closed as not planned by vsajip** 2024-02-28 09:15 UTC
Labels: type-bug, stdlib, pending
