### ISSUE TITLE
`Includes/internal/pycore_code.h` uses `static_assert()` but does not inlcude `pymacro.h`

### ISSUE THREAD

**Issue by dnicolodi** [python/cpython#123747] opened 2024-09-05 21:21 UTC
# Bug report

### Bug description:

`Includes/internal/pycore_code.h` uses `static_assert()` but does not inlcude `pymacro.h`, should it?

AFAIU `pymacro.h` makes sure that `static_assert()` is correctly defined for all supported compilers and platforms. Not including it in `Includes/internal/pycore_code.h` implicitly relies on `pymacro.h` being included before or via transitive includes.

I've found this while investigating a Cython extension module build failure. Cython includes the private header and thus requires `static_macro()` to be defined.

### CPython versions tested on:

3.13, CPython main branch

### Linked PRs
* gh-123779
* gh-123785

**Comment by vstinner** [comment] 2024-09-05 21:37
In general, I would suggest to only include `<pycore_xxx.h>` headers **after** including `<Python.h>`.

**Comment by dnicolodi** [comment] 2024-09-05 21:51
Sure, the compilation error is unrelated (Cython requires only C99 which does not have `static_assert()`). This report is more about a question of principle: should CPython internal headers be independent or can they rely on `#include` order for the definitions they use?

**Comment by vstinner** [comment] 2024-09-05 22:06
Do you get the error if you include `<Python.h>` first?

**Comment by dnicolodi** [comment] 2024-09-05 22:21
Yes. But the error is unrelated to what I am trying to say.

**Comment by vstinner** [comment] 2024-09-05 22:29
> This report is more about a question of principle: should CPython internal headers be independent or can they rely on #include order for the definitions they use?

They are not independent. <Python.h> must always be included first.

**Comment by dnicolodi** [comment] 2024-09-05 22:54
Thanks. There is nothing wrong then.

**Comment by scoder** [comment] 2024-09-06 10:30
It turns out that this *is* an issue, even after `#include "Python.h"`:
https://github.com/cython/cython/issues/6385#issuecomment-2333618533
This issue was found in Cython generated code, which always includes `Python.h` but then also needs `pycore_frame.h` later, which includes `pycore_code.h`.

Since Cython code is not commonly compiled with C11 (we currently require C99), there are platforms where the resulting code does not compile

**Comment by scoder** [comment] 2024-09-06 10:31
Since it is really just an assertion that gets in the way here, I propose to comment it out for the final release.

**Comment by vstinner** [comment] 2024-09-06 11:55
I don't understand how to reproduce the issue. Can somone provide a reproducer? Does the issue only affect macOS? With which C compiler and which compiler options?

**Comment by picnixz** [comment] 2024-09-06 11:58
FTR, here's the comment concerning `static_assert` (it may help people that are too lazy to find it in the codebase):

```C
// gh-91782: On FreeBSD 12, if the _POSIX_C_SOURCE and _XOPEN_SOURCE macros are
// defined, <sys/cdefs.h> disables C11 support and <assert.h> does not define
// the static_assert() macro.
// https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255290
//
// macOS <= 10.10 doesn't define static_assert in assert.h at all despite
// having C11 compiler support.
//
// static_assert is defined in glibc from version 2.16. Compiler support for
// the C11 _Static_assert keyword is in gcc >= 4.6.
//
// MSVC makes static_assert a keyword in C11-17, contrary to the standards.
//
// In C++11 and C2x, static_assert is a keyword, redefining is undefined
// behaviour. So only define if building as C, not C++ (if __cplusplus is
// not defined), and only for C11-17.
```

**Comment by dnicolodi** [comment] 2024-09-06 13:04
> I don't understand how to reproduce the issue. Can somone provide a reproducer? Does the issue only affect macOS? With which C compiler and which compiler options?

I can reproduce the issue compiling the most simple Cython extension module:
```cython
def foo():
    return 42
```
with Cython 3.0.11 with clang from Xtools:
```sh
$ cc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
```
using an explicit `-std=c99` compilation option.

A more synthetic reproducer is trying to compile something like:
```c
#include "Python.h"
#include "internal/pycore_frame.h"
int main() { }
```
In this way:
```sh
$ cc foo.c -o foo.o -DPy_BUILD_CORE=1 $(python3.13-config --cflags) -std=c99
```
Omitting the `-std=c99` or setting it to `-std=c11` or higher the snippet compiles.

As pointed out before, the issue is that `static_assert()` is a C11 concept. CPython requires C11 thus it is fine. However, Cython requires only C99 and it includes internal CPython headers which assume C11 features.

For some reason that I have not investigated, `static_assert()` is defined when compiling with GCC on Linux or MSVC on Windows when requesting C99 compliance.

**Comment by vstinner** [comment] 2024-09-06 13:12
> Apple clang version 14.0.0 (clang-1400.0.29.202)

I cannot reproduce the issue on Linux (Fedora 40) with clang 18.1.6.

See also discussion https://github.com/capi-workgroup/decisions/issues/30

**Comment by vstinner** [comment] 2024-09-06 13:18
I wrote PR gh-123779 to avoid static_assert() in the internal header files.

**Comment by encukou** [comment] 2024-09-06 13:33
Could Cython re-`#define static_assert(EXPR, MSG)` to nothing if compiling in C99 mode?

**Comment by vstinner** [comment] 2024-09-06 14:46
Fixed by https://github.com/python/cpython/commit/ef4b69d2becf49daaea21eb04effee81328a0393.

**Comment by vstinner** [comment] 2024-09-06 14:46
Thanks for your bug report @dnicolodi!

**Closed as completed by vstinner** 2024-09-06 14:46 UTC
Labels: type-bug, release-blocker

**Comment by scoder** [comment] 2024-09-06 20:56
Thanks @vstinner
