### ISSUE TITLE
typing.get_type_hints fails when passed a class with PEP 695 type parameters and PEP 563 is enabled

### ISSUE THREAD

**Issue by mjog** [python/cpython#114053] opened 2024-01-14 11:51 UTC
# Bug report

### Bug description:

```python
from __future__ import annotations

import typing

class Test[M]:
    attr: M

print(typing.get_type_hints(Test))
```

This fails with a NameError:

```
$ poetry run python3 pep_695_get_type_hints.py
Traceback (most recent call last):
  File "/home/mjog/pep_695_get_type_hints.py", line 8, in <module>
    print(typing.get_type_hints(Test))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 2197, in get_type_hints
    value = _eval_type(value, base_globals, base_locals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 393, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 900, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'M' is not defined
```
Although `get_type_hints` does not work with imported imported type aliases, this is not imported, so I would expect it to work. Further, the documentation for the function indicates using PEP 563 should /help/, but in this case it actually causes an error.

FWIW, removing the PEP 563 import works fine, giving:

```
{'attr': M}
```

Python version:

```
$ poetry run python3 --version
Python 3.12.0
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-118009
* gh-118104
* gh-120270
* gh-120272
* gh-120474
* gh-120475
* gh-121003
* gh-121004

**Comment by mjog** [comment] 2024-01-14 21:40
Oof, looking for a workaround, I noticed this doesn't work for pre-695 generic classes either:

```
from __future__ import annotations

import typing

_M = typing.TypeVar('_M')
class Test(typing.Generic[_M]):
    attr: M

print(typing.get_type_hints(Test))
```

Gives the exact same stack trace as above.

Is this supposed to work? The docs for both `typing.get_type_hints` and PEP 563 explicitly says it should.

**Comment by mjog** [comment] 2024-01-15 07:37
Sorry, my now-hidden comment above is incorrect - it does work fine with pre-695 generic classes, I just had a type in the code.

This is only an issue with PEP 695 type parameters in conjunction with PEP 563.

**Comment by treykeown** [comment] 2024-01-19 23:31
+1, just ran into this as well.

**Comment by AlexWaygood** [comment] 2024-04-17 20:01
I suppose the problem is probably that `get_type_hints` looks things up in the global scope but doesn't look things up in the new [annotation scopes](https://docs.python.org/3/reference/executionmodel.html#annotation-scopes) introduced by PEP-695. The old way of defining TypeVars doesn't suffer from this because TypeVars were defined in the global scope; now they aren't.

**Comment by treykeown** [comment] 2024-04-25 15:14
I created a temporary workaround based off the fix by @AlexWaygood if anyone needs a hack around this in the meantime: https://gist.github.com/treykeown/65c45b3da330d2293c7fb9d2a46520ed

**Comment by AlexWaygood** [comment] 2024-06-06 11:06
The bug was fixed in `typing.get_type_hints`, but the same bug also exists in `inspect.get_annotations` when `eval_str=True` is passed:

```pycon
Python 3.14.0a0 (heads/main:eeb8f67f837, Jun  6 2024, 12:03:13) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import annotations
>>> class test[M]:
...     attr: M
...     
>>> import inspect
>>> inspect.get_annotations(test, eval_str=True)
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    inspect.get_annotations(test, eval_str=True)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexw/dev/cpython/Lib/inspect.py", line 286, in get_annotations
    value if not isinstance(value, str) else eval(value, globals, locals)
                                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'M' is not defined
```

**Closed as completed** 2024-06-25 15:55 UTC
Labels: type-bug, stdlib, topic-typing, 3.12, 3.13
