### ISSUE TITLE
action='store_false' documentation displays incorrect output example

### ISSUE THREAD

**Issue by omurad** [python/cpython#118764] opened 2024-05-08 14:47 UTC
The `store_true`/`store_false` example shows that

```
parser = argparse.ArgumentParser()
parser.add_argument('--foo', action='store_true')
parser.add_argument('--bar', action='store_false')
parser.add_argument('--baz', action='store_false')
parser.parse_args('--foo --bar'.split())
```
Returns
```
Namespace(foo=True, bar=False, baz=True)
```
`baz` should equal `False` since its action is `store_false`

### Linked PRs
* gh-118762

**Comment by nineteendo** [comment] 2024-05-08 15:00
Works as documented:

```python
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--a', action='store_true')
parser.add_argument('--b', action='store_false')
parser.add_argument('--c', action='store_false')
print(parser.parse_args('--a --b'.split()))  # Namespace(a=True, b=False, c=True)
```

**Comment by tusharsadhwani** [comment] 2024-05-08 15:20
> baz should equal `False` since its action is `store_false`

`store_false` means that if you pass `--baz`, it will be stored as `False`. Meaning its default value is `True`.

It may seem counter intuitive, but it's just the direct opposite of `store_true`, where `False` is the default and passing the flag makes it `True`.

**Comment by ericvsmith** [comment] 2024-05-08 16:31
It looks like this is working as designed and documented, so I'm going to close this.

**Closed as not planned by ericvsmith** 2024-05-08 16:31 UTC
Labels: docs

**Comment by terryjreedy** [comment] 2024-05-08 18:34
Next time, please ask about possible bugs on https://discuss.python.org/c/users/7.
