### ISSUE TITLE
`inspect.iscoroutinefunction` does not work correctly if the function is decorated

### ISSUE THREAD

**Issue by harshil21** [python/cpython#100224] opened 2022-12-13 16:31 UTC
# Bug report

If you have a decorator, and you apply that to a function, `inspect.iscoroutinefunction` will return `True` even if the decorated function is not actually async.

Here's an example:

``` python
import inspect


def log(func):
    async def decorator(*args, **kwargs):
        result = await func(*args, **kwargs)
        return result

    return decorator

class A:
    @log
    def a(self) -> None:
        pass


@log
def b() -> None:
    pass


print(inspect.iscoroutinefunction(A.a))   # True
print(inspect.iscoroutinefunction(b))   # True
```

It seems as if the function is checking if `decorator` is async instead of `a` or `b`. If I make for e.g. `b` async, and `decorator` non-async, `iscoroutinefunction` returns `False`, when in fact it should return `True`. 

I tried searching the repo for this behaviour, but I couldn't find an explanation if this is intentional or not.

### Workaround

The only workaround would be to do `inspect.iscoroutinefunction(b.__wrapped__)`, which accurately prints `False`. I think the function should have a `follow_wrapped` parameter similar to `inspect.signature`, so we know what to expect.

# Your environment

- CPython versions tested on: 3.11.0 built with [pyenv](https://github.com/pyenv/pyenv)
- Operating system and architecture: Ubuntu-Preview on WSL2

**Comment by carljm** [comment] 2022-12-15 19:03
I don't think the `follow_wrapped` feature makes sense for `inspect.iscoroutinefunction` like it does for `inspect.signature`. 

It makes sense for `inspect.signature` because decorators commonly "obscure" the signature of the wrapped function (e.g. by accepting `*args, **kwargs`), and this works fine but makes `inspect.signature` less useful on the decorated function; effectively the wrapped signature is the "real" signature of the decorator.

This is not true for `inspect.iscoroutinefunction`. As far as any caller is concerned, the "real" asyncness is the asyncness of the outer function that you actually call; the asyncness of the wrapped function is no longer relevant. Once you decorate a function with your `log` decorator, that name really does now refer to an async function, and anyone who cares to call it needs to treat it as an async function and await its return value. So `inspect.iscoroutinefunction` should, correctly and accurately, tell them it is an async function (as it does today.)

The code shown in the report is not a realistic use case for adding `follow_wrapped`, because it's just buggy and won't work. You can't do `result = await func(*args, **kwargs)` when `func` is not async. If the `log` decorator is supposed to handle decorating both sync and async functions, then internally it should call `iscoroutinefunction` on the wrapped function and handle the two cases differently. But if it does this, then why does any external caller care about whether the original wrapped function was async or not?

This feature proposal doesn't make anything new possible, since you can always "unwrap" yourself. So we should only add the `follow_wrapped` convenience if there is actually a strong use case for it.

I think we should close this unless a stronger use case is clarified.

**Comment by harshil21** [comment] 2022-12-15 20:08
Ok those are fair points, my actual use case was fixing a bug which was when we had a regular function which was supposed to be a coroutine function, but it could still be awaited because: 

1) We had a `@log` decorator which is async and awaited the wrapped function.
2) The wrapped function (unintentionally) returned a coroutine instead of the result after awaiting another coroutine.

[Here's the changes](https://github.com/python-telegram-bot/python-telegram-bot/pull/3136/files) which describes what I said above.

Even if such a parameter is not added (which I'm okay with), maybe the docs of  `inspect.iscoroutinefunction` could at least mention that it will only look at the decorated function, and not the wrapped function? Or is that expected behaviour to everyone?

**Comment by AlexWaygood** [comment] 2022-12-15 20:20
> Or is that expected behaviour to everyone?

It feels like expected behaviour to me. At the point of usage, the function you're passing in to `inspect.iscoroutinefunction` is actually, in fact, a coroutine function, so I feel like `inspect.iscoroutinefunction` is doing exactly what's asked of it. That just seems to be a fundamental truth about decorators: they can transform the object that they're decorating in arbitrary and unexpected ways, so that the object you end up with can have very different behaviour from what you might guess by looking at the source code for that object.

Apologies, but I agree with @carljm here: I think we should just close this :)

**Closed as not planned by AlexWaygood** 2022-12-15 20:20 UTC
Labels: type-bug, type-feature

**Comment by carljm** [comment] 2022-12-15 20:29
If we added a documentation note to `inspect.iscoroutinefunction`, there would be an equally strong argument to add the same note to every single function in the `inspect` module that takes a function as argument; everywhere in the standard library for that matter. It's expected behavior that something that takes a function operates on the function you give it, without first following the chain of `__wrapped__`. Cases which do follow the wrapped-chain for you are relatively few and far between, and those are called out as special behavior.

**Comment by umarbutler** [comment] 2024-03-16 01:04
I managed to workaround this by inspecting the source code of functions to check whether they contain a line that begins with `async def` followed by the function’s name (and also do not have a line beginning with `def` and the function’s name), as illustrated below:
```python
def is_async(func: Callable) -> bool:
    """Determine whether a callable is asynchronous."""
    
    # If `inspect.iscoroutinefunction` identifies the callable as asynchronous, then return `True`. If it doesn't, then try to search for a line that begins (ignoring preceeding whitespace) with `async def` followed by the callable's name and a `(` character inside its source code, returning `True` if such a line is found and there is no such line beginning with `def` (indicating that asynchronous and synchronous functions with the same name were defined in the same block as the callable).
    if inspect.iscoroutinefunction(func):
        return True
    
    try:
        source = inspect.getsource(func)
        
    except (OSError, TypeError):
        return False

    has_async_def = re.search(r'^\s*async\s+def\s+' + re.escape(func.__name__) + r'\s*\(', source, re.MULTILINE)
    
    if has_async_def:    
        has_sync_def = re.search(r'^\s*def\s+' + re.escape(func.__name__) + r'\s*\(', source, re.MULTILINE)
        
        if not has_sync_def:
            return True

    return False
```

The only catch is that this is not absolutely guaranteed to capture all asynchronous functions. `inspect.getsource` does not work for builtins, for example. Also, if you define two functions within a single decorator that have the same name, then this will also not work. Nor will it work if you change the `__name__` attribute of a function later on. 

Nevertheless, this method has sufficed for my uses and may be of some benefit to others.
