### ISSUE TITLE
Improve collections.Counter inheritance by abstracting new Counters creation

### ISSUE THREAD

**Issue by Susensio** [python/cpython#104740] opened 2023-05-22 08:32 UTC
# Feature or enhancement

Inheriting from `Counter` gives unexpected results, as each dunder method that creates a new hardcoded `Counter` object.

https://github.com/python/cpython/blob/6fba0314765d7c58a33e9859d9cd5bcc35d2fd0a/Lib/collections/__init__.py#L829

# Pitch

An example of usage
```python
class MyCounter(collections.Counter):
    def cool_feature(self):
        print("I'm a fancy Counter")

c = MyCounter('abc')
```
Using math on inherited Counter return a bare Counter, and loses any new feature:
```
>>> c.cool_feature()
I'm a fancy Counter

>>> (c + c).cool_feature()
AttributeError: 'Counter' object has no attribute 'cool_feature'
```

# Problem scope
The following methods hardcode the `Counter` class:
- `__add__`
- `__sub__`
- `__or__`
- `__and__`
- `__pos__`
- `__neg__`

# Solution

Replace every occurrence of `result = Counter()` with `result = self.__class__()`

I cannot think of any bad side effects of doing this, but I don't know if there is a better approach.

**Comment by Agent-Hellboy** [comment] 2023-05-22 10:47
Hi @AlexWaygood, I can raise a PR.

**Comment by AlexWaygood** [comment] 2023-05-22 10:56
@Agent-Hellboy, please hold off for now. Raymond is the maintainer of the `collections` module, and has thought deeply about the design of the `Counter` class, which has been in the standard library for many years. We should wait for his thoughts on this idea before creating a PR.

**Comment by Agent-Hellboy** [comment] 2023-05-22 11:07
yes, it looks like he doesn't want to allow these operations on the Custom counter as I can see he has tested some functionality for the subclass e.g https://github.com/python/cpython/blob/0a7796052acb9cec8b13f8d0a5f304f56f26ec5b/Lib/test/test_collections.py#L2227

**Comment by sunmy2019** [comment] 2023-05-22 18:32
Even if this gets fixed, it won't be released until Oct. 2024

So if you need a workaround soon, try this.

```py
MyCounter(c + c).cool_feature()
```

**Comment by pochmann** [comment] 2023-05-22 19:11
Duplicate of #96839 ?

**Comment by rhettinger** [comment] 2023-05-22 19:19
Thank you for the suggestion but current behavior was done on purpose and should be left as-is.

There is no perfect choice here.  As you noted, this means that someone writing a subclass would need to override all of the operator methods if they wanted return an instance of the subclass.  That is a little inconvenient but is completely controllable by the subclasser to achieve the exact, desired behavior.

There are several reasons for the current design.  One is that Counter was modeled after some well established behaviors in other classes.  The `set` operators behave this way — an union of `set` subclasses returns an actual set rather than the subclass.  The `int` arithmetic methods behave this way as well.  Likewise the `or` operator on dict subclass returns an exact dict rather than the subclass.

There are both theoretical and practical reasons behind this.  On the theoretical side, we get better Liskov substitutability and we follow the open-closed principle, open for extension, closed for modification.  On the practical side, we cannot know in advance the constructor signature a subclass (that is why `collections.abc.Set` had to factor-out a `_from_iterable` method). There are also some performance reasons as well.

In practice, the design choices have worked out well.  Once is a while, a subclasser is annoyed, but the rest of the time we get fast, predictable behavior.

**Closed as not planned** 2023-05-22 19:19 UTC
Labels: type-feature, stdlib
