### ISSUE TITLE
(🐞) Column marker in error message off for certain string errors

### ISSUE THREAD

**Issue by KotlinIsland** [python/cpython#102312] opened 2023-02-28 03:18 UTC
```py
"\N{a}"
```
```
👉 python test.py
  File "/test.py", line 1
    "\N{a}"
           ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-4: unknown Unicode character name
```
Here the caret is pointing to blackspace after the code

## Expected
```
👉 python test.py
  File "/test.py", line 1
    "\N{a}"
        ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-4: unknown Unicode character name
```

**Comment by arhadthedev** [comment] 2023-02-28 03:24
Reproduced in the CLI too:

```python
>>> "\N{a}"
  File "<stdin>", line 1
    "\N{a}"
```

By the way, the interpreter hangs for around five seconds on first execution of `\N{a}` with no delay on further attempts.

**Comment by KotlinIsland** [comment] 2023-02-28 03:26
@arhadthedev Am I missing something? I Can't see any caret in your repro.

**Comment by arhadthedev** [comment] 2023-02-28 03:28
@KotlinIsland Thank you, updated my initially undercopied output.

**Comment by arhadthedev** [comment] 2023-02-28 03:31
@benjaminp, @pablogsal (as parser experts)

**Comment by terryjreedy** [comment] 2023-02-28 03:41
This is likely a duplicate of #102312.

**Closed as not planned** 2023-02-28 03:48 UTC
Labels: type-bug, interpreter-core

**Comment by gvanrossum** [comment] 2023-02-28 03:50
> By the way, the interpreter hangs for around five seconds on first execution of `\N{a}` with no delay on further attempts.

Could that just be importing the (humongous) unicodedata module to resolve the name?

@terryjreedy What is it a duplicate of? Your link points to this same issue.

**Comment by gvanrossum** [comment] 2023-02-28 03:51
PS. If Benjamin is still listed as parser expert that's likely out of date.

**Comment by terryjreedy** [comment] 2023-02-28 04:01
#102310, about same problem with  b"Ā".  Sorry about bad link (now fixed).

**Comment by KotlinIsland** [comment] 2023-02-28 23:23
I don't think it's the same issue as #102310, in that issue the column marker is offset by a non ascii character, in this issue the marker appears after the string. While this issue does make an appearance in #102310, I do feel that they are distinct.
