### ISSUE TITLE
Remove deprecated keyword argument syntax for typing.TypedDict

### ISSUE THREAD

**Issue by hugovk** [python/cpython#104936] opened 2023-05-25 15:26 UTC
# Feature or enhancement

The keyword argument syntax for constructing `typing.TypedDict` types was deprecated in 3.11 and scheduled for removal in Python 3.13.

# Previous discussion

* GH-90224

**Comment by AlexWaygood** [comment] 2023-05-25 15:29
Duplicate of #104786

**Closed as not planned by AlexWaygood** 2023-05-25 15:29 UTC
Labels: type-feature, stdlib, topic-typing, 3.13
