### ISSUE TITLE
test_sysconfig fails when executed from within a venv

### ISSUE THREAD

**Issue by pganssle** [python/cpython#104097] opened 2023-05-02 18:04 UTC
# Bug report

As part of adding property-based tests to the standard library's test suite (#22863), I discovered that `test_sysconfig` apparently will fail when the test suite is executed from a virtual environment. To reproduce:

```
./python -m venv venv
venv/bin/python -m test -W test_sysconfig
```

The result:

```
0:00:00 load avg: 0.54 Run tests sequentially
0:00:00 load avg: 0.54 [1/1] test_sysconfig
test_get_makefile_filename (test.test_sysconfig.MakefileTests.test_get_makefile_filename) ... ok
test_parse_makefile (test.test_sysconfig.MakefileTests.test_parse_makefile) ... ok
test_EXT_SUFFIX_in_vars (test.test_sysconfig.TestSysConfig.test_EXT_SUFFIX_in_vars) ... ok
test_get_config_h_filename (test.test_sysconfig.TestSysConfig.test_get_config_h_filename) ... ok
test_get_config_vars (test.test_sysconfig.TestSysConfig.test_get_config_vars) ... ok
test_get_default_scheme (test.test_sysconfig.TestSysConfig.test_get_default_scheme) ... ok
test_get_path (test.test_sysconfig.TestSysConfig.test_get_path) ... ok
test_get_path_names (test.test_sysconfig.TestSysConfig.test_get_path_names) ... ok
test_get_paths (test.test_sysconfig.TestSysConfig.test_get_paths) ... ok
test_get_platform (test.test_sysconfig.TestSysConfig.test_get_platform) ... ok
test_get_preferred_schemes (test.test_sysconfig.TestSysConfig.test_get_preferred_schemes) ... ok
test_get_scheme_names (test.test_sysconfig.TestSysConfig.test_get_scheme_names) ... ok
test_ldshared_value (test.test_sysconfig.TestSysConfig.test_ldshared_value) ... ok
test_main (test.test_sysconfig.TestSysConfig.test_main) ... ok
test_nt_venv_scheme (test.test_sysconfig.TestSysConfig.test_nt_venv_scheme) ... FAIL
test_osx_ext_suffix (test.test_sysconfig.TestSysConfig.test_osx_ext_suffix) ... skipped 'OS X-specific test'
test_platform_in_subprocess (test.test_sysconfig.TestSysConfig.test_platform_in_subprocess) ... skipped 'test only relevant on MacOSX'
test_posix_venv_scheme (test.test_sysconfig.TestSysConfig.test_posix_venv_scheme) ... FAIL
test_srcdir (test.test_sysconfig.TestSysConfig.test_srcdir) ... ok
test_srcdir_independent_of_cwd (test.test_sysconfig.TestSysConfig.test_srcdir_independent_of_cwd) ... ok
test_symlink (test.test_sysconfig.TestSysConfig.test_symlink) ... ok
test_triplet_in_ext_suffix (test.test_sysconfig.TestSysConfig.test_triplet_in_ext_suffix) ... ok
test_user_similar (test.test_sysconfig.TestSysConfig.test_user_similar) ... ok
test_venv_scheme (test.test_sysconfig.TestSysConfig.test_venv_scheme) ... ok

======================================================================
FAIL: test_nt_venv_scheme (test.test_sysconfig.TestSysConfig.test_nt_venv_scheme)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../Lib/test/test_sysconfig.py", line 178, in test_nt_venv_scheme
    self.assertEqual(incpath, sysconfig.get_path('include', scheme='nt_venv'))
AssertionError: '.../venv/Include' != '/usr/local/Include'
- .../venv/Include
+ /usr/local/Include


======================================================================
FAIL: test_posix_venv_scheme (test.test_sysconfig.TestSysConfig.test_posix_venv_scheme)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../Lib/test/test_sysconfig.py", line 163, in test_posix_venv_scheme
    self.assertTrue(sysconfig_includedir.startswith(incpath + os.sep))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 24 tests in 0.116s

FAILED (failures=2, skipped=2)
test test_sysconfig failed
test_sysconfig failed (2 failures)

== Tests result: FAILURE ==

1 test failed:
    test_sysconfig

Total duration: 174 ms
Tests result: FAILURE
```

# Your environment

- CPython versions tested on: `main`
- Operating system and architecture: Linux (also happens on Ubuntu 20.04 in the CI environment)

**Comment by itamaro** [comment] 2023-05-12 04:37
confirmed this on MacOS too

is it generally expected that the test suite works in a venv?

**Comment by itamaro** [comment] 2023-05-12 04:57
fwiw, test_venv also fails when executed from a venv

**Comment by pganssle** [comment] 2023-05-12 12:54
> is it generally expected that the test suite works in a venv?

I certainly think it should. The [coverage job](https://github.com/python/cpython/blob/5b8cd5abe5924646b9ed90e7ba90085b56d5f634/.azure-pipelines/posix-steps.yml#L30-L47) (currently disabled) is executed in a `venv`, as is the [hypothesis job](https://github.com/python/cpython/blob/5b8cd5abe5924646b9ed90e7ba90085b56d5f634/.github/workflows/build.yml#L306-L388) (though if `unittest` were a bit more flexible in its ability to filter jobs we wouldn't be running these particular tests in that job anyway).

**Comment by AlexWaygood** [comment] 2023-07-01 16:59
Duplicate of #103224

**Closed as not planned by AlexWaygood** 2023-07-01 16:59 UTC
Labels: type-bug
