### ISSUE TITLE
typing.TypeAlias is not in the list of allowed plain _SpecialForm typeforms

### ISSUE THREAD

**Issue by 3f3f69a9-eb63-42d7-a515-cb2fea57e654** [python/cpython#90813] opened 2022-02-06 07:30 UTC
BPO | [46655](https://bugs.python.org/issue46655)
--- | :---
Nosy | @gvanrossum, @JelleZijlstra, @Fidget-Spinner, @GBeauregard
PRs | <li>python/cpython#31156</li><li>python/cpython#31175</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-06.07:30:06.388>
labels = ['type-bug', 'library']
title = 'typing.TypeAlias is not in the list of allowed plain _SpecialForm typeforms'
updated_at = <Date 2022-02-07.16:22:04.935>
user = 'https://github.com/GBeauregard'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-07.16:22:04.935>
actor = 'gvanrossum'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-02-06.07:30:06.388>
creator = 'GBeauregard'
dependencies = []
files = []
hgrepos = []
issue_num = 46655
keywords = ['patch']
message_count = 4.0
messages = ['412618', '412685', '412686', '412766']
nosy_count = 4.0
nosy_names = ['gvanrossum', 'JelleZijlstra', 'kj', 'GBeauregard']
pr_nums = ['31156', '31175']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46655'
versions = []
```

</p></details>

**Comment by picnixz** [comment] 2024-08-27 11:18
Closing since the issue has been fixed (I cannot reproduce it on 3.12 or main).

**Closed as completed by picnixz** 2024-08-27 11:18 UTC
Labels: type-bug, stdlib, topic-typing
