### ISSUE TITLE
Tokenizer module does not handle backslash characters correctly

### ISSUE THREAD

**Issue by 8105709d-9f52-45b8-8c28-f075da179a32** [python/cpython#90432] opened 2022-01-05 23:12 UTC
BPO | [46274](https://bugs.python.org/issue46274)
--- | :---
Nosy | @lysnikolaou, @ucodery

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-05.23:12:47.391>
labels = ['interpreter-core', '3.8', '3.9', '3.10', '3.11', '3.7']
title = 'Tokenizer module does not handle backslash characters correctly'
updated_at = <Date 2022-01-06.13:57:33.135>
user = 'https://github.com/ucodery'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-06.13:57:33.135>
actor = 'pablogsal'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Parser']
creation = <Date 2022-01-05.23:12:47.391>
creator = 'ucodery'
dependencies = []
files = []
hgrepos = []
issue_num = 46274
keywords = []
message_count = 1.0
messages = ['409811']
nosy_count = 2.0
nosy_names = ['lys.nikolaou', 'ucodery']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46274'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by asottile** [comment] 2023-05-06 19:32
another similar example -- which I believe to be the root cause of https://github.com/hhatto/autopep8/issues/669 is that these are treated differently:

```python
import sys

def f():
    pass
```

```python
import sys
\

def f():
    pass
```

the former having a `NL` token whereas the latter has a `NEWLINE`

in this particular case it throws off `pycodestyle` and then `autopep8`

**Comment by asottile** [comment] 2023-05-06 20:06
this seems to fix it, but I'm not sure if this is the right direction -- it seems overly simple of a fix for such a complicated piece of code

```diff
diff --git a/Lib/test/test_tokenize.py b/Lib/test/test_tokenize.py
index 911b53e581..2280374971 100644
--- a/Lib/test/test_tokenize.py
+++ b/Lib/test/test_tokenize.py
@@ -59,6 +59,26 @@ def test_implicit_newline(self):
         self.assertEqual(tokens[-2].type, NEWLINE)
         self.assertEqual(tokens[-1].type, ENDMARKER)
 
+    def test_line_continuation(self):
+        code = dedent("""\
+            import sys
+
+            \\
+
+            import os
+        """)
+
+        self.check_tokenize(code, """\
+    NAME       'import'      (1, 0) (1, 6)
+    NAME       'sys'         (1, 7) (1, 10)
+    NEWLINE    '\\n'          (1, 10) (1, 11)
+    NL         '\\n'          (2, 0) (2, 1)
+    NL         '\\n'          (4, 0) (4, 1)
+    NAME       'import'      (5, 0) (5, 6)
+    NAME       'os'          (5, 7) (5, 9)
+    NEWLINE    '\\n'          (5, 9) (5, 10)
+        """)
+
     def test_basic(self):
         self.check_tokenize("1 + 1", """\
     NUMBER     '1'           (1, 0) (1, 1)
diff --git a/Lib/tokenize.py b/Lib/tokenize.py
index 46d2224f5c..cf66912262 100644
--- a/Lib/tokenize.py
+++ b/Lib/tokenize.py
@@ -593,6 +593,8 @@ def _tokenize(readline, encoding):
                 elif initial.isidentifier():               # ordinary name
                     yield TokenInfo(NAME, token, spos, epos, line)
                 elif initial == '\\':                      # continued stmt
+                    if line == '\\\n':  # ignore an empty escaped line
+                        break
                     continued = 1
                 else:
                     if initial in '([{':
```

**Comment by asottile** [comment] 2023-05-24 12:45
@lysnikolaou it seems to fix that -- but also includes a regression(?) (this is 3.12.0b1):

```diff
$ diff -u <(python3.11 -mtokenize t.py) <(python3.12 -mtokenize t.py)
--- /dev/fd/63	2023-05-24 08:44:07.429455783 -0400
+++ /dev/fd/62	2023-05-24 08:44:07.429455783 -0400
@@ -2,7 +2,7 @@
 1,0-1,6:            NAME           'import'       
 1,7-1,10:           NAME           'sys'          
 1,10-1,11:          NEWLINE        '\n'           
-3,0-3,1:            NEWLINE        '\n'           
+3,0-3,1:            NL             '\n'           
 4,0-4,3:            NAME           'def'          
 4,4-4,5:            NAME           'f'            
 4,5-4,6:            OP             '('            
@@ -12,5 +12,5 @@
 5,0-5,4:            INDENT         '    '         
 5,4-5,8:            NAME           'pass'         
 5,8-5,9:            NEWLINE        '\n'           
-6,0-6,0:            DEDENT         ''             
+5,9-5,9:            DEDENT         ''             
 6,0-6,0:            ENDMARKER      ''     
```

**Comment by lysnikolaou** [comment] 2023-05-24 13:23
I think that the 3.12 version is the correct one regarding the `NEWLINE`/`NL` tokens. Regarding the location of the `DEDENT` token, I don't have a strong opinion, but feel that it could stay this way. @pablogsal What do you think?

**Comment by pablogsal** [comment] 2023-05-24 13:35
I think we can close this issue

**Comment by lysnikolaou** [comment] 2023-05-24 13:37
Thanks @pablogsal!

**Closed as completed by lysnikolaou** 2023-05-24 13:37 UTC
Labels: interpreter-core, 3.11, 3.10, 3.12

**Comment by asottile** [comment] 2023-05-25 16:17
@pablogsal then this should be reopened

**Comment by pablogsal** [comment] 2023-05-25 16:31
> @pablogsal then this should be reopened

Why? That is an expected difference

**Comment by asottile** [comment] 2023-05-25 17:28
the NEWLINE token should be a NL if this issue is resolved

**Comment by pablogsal** [comment] 2023-05-25 18:26
> the NEWLINE token should be a NL if this issue is resolved

No, that was a bug, see https://github.com/python/cpython/issues/104866

**Comment by asottile** [comment] 2023-05-25 18:41
I'm confused -- I think we're talking about different things -- are you using the source here?

https://github.com/python/cpython/issues/90432#issuecomment-1537208486

**Comment by pablogsal** [comment] 2023-05-25 19:04
> are you using the source here?

I am. The difference I was mentioning was between Python 3.11 and 3.12. Just to be clear, with 3.12:

```
./python -m tokenize < source1.py
1,0-1,6:            NAME           'import'
1,7-1,10:           NAME           'sys'
1,10-1,11:          NEWLINE        '\n'
2,0-2,1:            NL             '\n'
3,0-3,3:            NAME           'def'
3,4-3,5:            NAME           'f'
3,5-3,6:            OP             '('
3,6-3,7:            OP             ')'
3,7-3,8:            OP             ':'
3,8-3,9:            NEWLINE        '\n'
4,0-4,4:            INDENT         '    '
4,4-4,8:            NAME           'pass'
4,8-4,9:            NEWLINE        '\n'
4,9-4,9:            DEDENT         ''
5,0-5,0:            ENDMARKER      ''

./python -m tokenize < source2.py
1,0-1,6:            NAME           'import'
1,7-1,10:           NAME           'sys'
1,10-1,11:          NEWLINE        '\n'
3,0-3,1:            NL             '\n'
4,0-4,3:            NAME           'def'
4,4-4,5:            NAME           'f'
4,5-4,6:            OP             '('
4,6-4,7:            OP             ')'
4,7-4,8:            OP             ':'
4,8-4,9:            NEWLINE        '\n'
5,0-5,4:            INDENT         '    '
5,4-5,8:            NAME           'pass'
5,8-5,9:            NEWLINE        '\n'
5,9-5,9:            DEDENT         ''
6,0-6,0:            ENDMARKER      ''
```

With 3.11:

```
python -m tokenize < source1.py
1,0-1,6:            NAME           'import'
1,7-1,10:           NAME           'sys'
1,10-1,11:          NEWLINE        '\n'
2,0-2,1:            NL             '\n'
3,0-3,3:            NAME           'def'
3,4-3,5:            NAME           'f'
3,5-3,6:            OP             '('
3,6-3,7:            OP             ')'
3,7-3,8:            OP             ':'
3,8-3,9:            NEWLINE        '\n'
4,0-4,4:            INDENT         '    '
4,4-4,8:            NAME           'pass'
4,8-4,9:            NEWLINE        '\n'
5,0-5,0:            DEDENT         ''
5,0-5,0:            ENDMARKER      ''

python -m tokenize < source2.py
1,0-1,6:            NAME           'import'
1,7-1,10:           NAME           'sys'
1,10-1,11:          NEWLINE        '\n'
3,0-3,1:            NEWLINE        '\n'
4,0-4,3:            NAME           'def'
4,4-4,5:            NAME           'f'
4,5-4,6:            OP             '('
4,6-4,7:            OP             ')'
4,7-4,8:            OP             ':'
4,8-4,9:            NEWLINE        '\n'
5,0-5,4:            INDENT         '    '
5,4-5,8:            NAME           'pass'
5,8-5,9:            NEWLINE        '\n'
6,0-6,0:            DEDENT         ''
6,0-6,0:            ENDMARKER      ''
```

The difference between 3.11 and 3.12 for the "correct" version is still the location of the last DEDENT token, which is expected.

**Comment by asottile** [comment] 2023-05-25 19:59
hmmm ok but this diff doesn't show the NEWLINE -> NL: https://github.com/python/cpython/issues/90432#issuecomment-1563164283
