### ISSUE TITLE
Rewrite asyncio.to_thread tests to use IsolatedAsyncioTestCase

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#91260] opened 2022-03-23 20:42 UTC
BPO | [47104](https://bugs.python.org/issue47104)
--- | :---
Nosy | @asvetlov, @1st1, @miss-islington, @Fidget-Spinner
PRs | <li>python/cpython#32086</li><li>python/cpython#32087</li><li>python/cpython#32088</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-23.20:42:40.140>
labels = ['3.11', 'tests', '3.10', 'expert-asyncio']
title = 'Rewrite asyncio.to_thread tests to use IsolatedAsyncioTestCase'
updated_at = <Date 2022-04-06.17:56:00.892>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-06.17:56:00.892>
actor = 'kj'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests', 'asyncio']
creation = <Date 2022-03-23.20:42:40.140>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 47104
keywords = ['patch']
message_count = 4.0
messages = ['415913', '415914', '416890', '416893']
nosy_count = 4.0
nosy_names = ['asvetlov', 'yselivanov', 'miss-islington', 'kj']
pr_nums = ['32086', '32087', '32088']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47104'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by kumaraditya303** [comment] 2022-04-18 14:30
The test is failing on GH Actions too on 3.10 branch, it should be reverted.

**Comment by gpshead** [comment] 2022-04-18 22:03
Using `python -m test --matchfile /tmp/tmp_0ql3hcl test_asyncio --fail-env-changed` in a 3.10 build I got:

```
== Tests result: ENV CHANGED ==

1 test altered the execution environment:
    test_asyncio

Total duration: 2.7 sec
Tests result: ENV CHANGED
ran 2 tests/4
exit 3
Tests failed: continuing with this subtest

Tests (2):
* test.test_asyncio.test_threads.ToThreadTests.test_to_thread_concurrent
* test.test_asyncio.test_unix_events.SelectorEventLoopSignalTests.test_add_signal_handler

Bisection failed after 101 iterations and 0:04:02
```

**Comment by gpshead** [comment] 2022-04-18 22:27
```
0:00:00 load avg: 0.93 [1/2/1] test_asyncio.test_threads failed (env changed)
Warning -- threading._dangling was modified by test_asyncio.test_threads
  Before: {<weakref at 0x7f3b2e77fa10; to '_MainThread' at 0x7f3b2f107490>}
  After:  {<weakref at 0x7f3b2e77ffb0; to '_MainThread' at 0x7f3b2f107490>}
```

**Comment by gpshead** [comment] 2022-04-18 23:01
I don't think this PR is the cause, just a code tweak that causes it to be exposed more often. Other tests lead to

```
0:09:20 load avg: 1.49 [427/427/1] test_asyncio failed (env changed) (1 min 22 sec)
Warning -- threading_cleanup() failed to cleanup -1 threads (count: 0, dangling: 1)
Warning -- Dangling thread: <_MainThread(MainThread, started 140300013757632)>
```

which is an environment change warning codepath from `test.support.threading_helper` which the test_asyncio.test_threads code no longer calls.  from CI run https://github.com/python/cpython/runs/6069450575?check_suite_focus=true

**Comment by gpshead** [comment] 2022-04-18 23:22
tracked in https://github.com/python/cpython/issues/91676 now as this issue's PR is merely a tickler of a latent problem, not the cause.

**Comment by kumaraditya303** [comment] 2022-04-19 10:40
Closing as it is now tracked in https://github.com/python/cpython/issues/91676

**Closed as completed by kumaraditya303** 2022-04-19 10:40 UTC
Labels: tests, topic-asyncio, 3.11, 3.10
