### ISSUE TITLE
3.12: SEGV after import wxPython then exit

### ISSUE THREAD

**Issue by pkoning2** [python/cpython#106918] opened 2023-07-20 17:35 UTC
# Bug report

If I do "import wx" then Control/D to exit, a SEGV results.  I see this with 3.12.0b3 and 3.12.0b4 on Mac (M1, ARM).  Failure report text (from Apple's "report" popup after the failure) attached.
[pywx.log](https://github.com/python/cpython/files/12112538/pywx.log)

# Your environment

Python 3.12.0b4
Mac OS 12.6.7 (ARM-64) on MacBook Pro

**Comment by AlexWaygood** [comment] 2023-07-20 18:26
Are you sure this is a bug in Python itself, and not a bug in `wxPython`? Have you raised this issue with `wxPython`?

**Comment by pkoning2** [comment] 2023-07-20 18:43
I have not.  But it works fine in Python 3.11.

**Comment by chgnrdv** [comment] 2023-07-21 02:58
Looks like a duplicate of #105690. wxPython depends on siplib 3.7.9 which uses `PyMem_Malloc`/`PyMem_Free`.

**Closed as not planned** 2023-07-21 07:32 UTC
Labels: type-bug, pending, 3.12, 3.13
