### ISSUE TITLE
Possible memory leak related to Byte-code compilation

### ISSUE THREAD

**Issue by epigramx** [python/cpython#106911] opened 2023-07-20 09:20 UTC
In reference to #49807 I understand that the issue of using a lot of memory during compilation is a ..non-issue, but I wonder if there is currently a memory leak that keeps high ram usage the first time a program is run (after compilation) unless the program is re-run. I had a ~50MB python code file that used around 3GB of RAM retained (after the compilation) during the first run and then all that ram usage was gone on the subsequent runs.

**Comment by chgnrdv** [comment] 2023-07-23 13:46
This probably happens because of bytecode caching.
```
$ python3 -c "print(f'x = {[i for i in range(500000)]}')" > script.py
$ echo "import tracemalloc; tracemalloc.start(); import script; print('peak %.1f KiB' % (tracemalloc.get_traced_memory()[1] / 1024))" > tracemem.py
$ ls
script.py tracemem.py
$ python3 tracemem.py
peak 406678.3 KiB
$ ls
__pycache__  script.py  tracemem.py
$ python3 tracemem.py
peak 23431.7 KiB
$ rm -r __pycache__
$ python3 tracemem.py
peak 406678.3 KiB
```
`__pycache__` directory contains files with precompiled bytecode, so Python loads them directly during import on subsequent runs, rather than parsing source code again and using excess memory for building AST structures etc.

**Comment by epigramx** [comment] 2023-07-24 12:16
> This probably happens because of bytecode caching.
> 
> ```
> $ python3 -c "print(f'x = {[i for i in range(500000)]}')" > script.py
> $ echo "import tracemalloc; tracemalloc.start(); import script; print('peak %.1f KiB' % (tracemalloc.get_traced_memory()[1] / 1024))" > tracemem.py
> $ ls
> script.py tracemem.py
> $ python3 tracemem.py
> peak 406678.3 KiB
> $ ls
> __pycache__  script.py  tracemem.py
> $ python3 tracemem.py
> peak 23431.7 KiB
> $ rm -r __pycache__
> $ python3 tracemem.py
> peak 406678.3 KiB
> ```
> 
> `__pycache__` directory contains files with precompiled bytecode, so Python loads them directly during import on subsequent runs, rather than parsing source code again and using excess memory for building AST structures etc.

ok. can you think of a way to fix it, or is it impossible theoretically?

**Comment by epigramx** [comment] 2023-11-30 14:36
@iritkatriel the reply of @chgnrdv above appears to clearly say that it is expected behavior, and it requires a second run to see that RAM freed. Are you saying that's not true?

**Comment by hugovk** [comment] 2024-06-18 17:58
Closing as we don't know the Python version or steps to reproduce. We can re-open when actionable information is supplied.

**Closed as not planned by hugovk** 2024-06-18 17:58 UTC
Labels: type-bug, interpreter-core, pending
