### ISSUE TITLE
Improve error message for list.remove

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#92305] opened 2022-05-04 13:28 UTC
`list.remove` does not contains the ``repr`` of the object being removed from the list which is unhelpful. Proposed changes improves it from
Current:
```console 
>>> a = [1,2]
>>> a.remove(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: list.remove(x): x not in list
```
Proposed:
```console 
>>> a = [1,2]
>>> a.remove(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: 3 is not in list
```

**Comment by ericvsmith** [comment] 2022-05-04 14:46
It looks like the change is to include "list.remove", but remove the value being removed?

The current message similar to, for example:
```python
>>> {}.pop(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 1
```

Is there anywhere else where we include the method name in an error?

**Comment by kumaraditya303** [comment] 2022-05-04 14:56
There was a copy and paste error in the issue comment, fixed now.

**Comment by ericvsmith** [comment] 2022-05-04 17:29
Ah. That does look like an improvement. My only concern is listing the concrete type `list`, which wouldn't be true for a subclass. But I guess the message already has that problem:

```python
>>> class X(list): pass
...
>>> X().remove(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: list.remove(x): x not in list
```

**Comment by serhiy-storchaka** [comment] 2022-05-05 03:30
This is a duplicate of #48760.

**Comment by serhiy-storchaka** [comment] 2022-05-05 03:32
And #74039.

**Comment by serhiy-storchaka** [comment] 2022-05-05 03:34
And #57558.

**Closed as completed** 2022-05-05 03:34 UTC
Labels: type-feature, 3.11
