### ISSUE TITLE
gzip module writes file with bad CRC when saving large files

### ISSUE THREAD

**Issue by thomasf1** [python/cpython#100260] opened 2022-12-15 00:31 UTC
# Bug report

When trying to write a large amount of data (2.5 GB uncompressed, 250 MB compressed) with the gzip library, the CRC WRITTEN seems to be off. Smaller sizes of data did work fine. When reading the file with gzip.open it throws a gzip.BadGzipFile, with any other program, it basically says the file is corrupt. When circumventing the CRC check, the file unzips fine.

```python 
import ejson
import gzip

# users.json is about 2.5 GB
with open('users.json', 'r', encoding='utf-8') as file:
	contents = ejson.loads(file.read())

# the resulting file is about 250 MB big which seems right and decompresses fine when suppressing the CRC check
with gzip.open('users_compressed.json.gz', 'w') as file:
	file.write(ejson.dumps(contents).encode('utf-8'))
```

opening the newly written File '', I get the following: gzip.BadGzipFile: CRC check failed.

Trying to only put in half the data with the following seems to work, too:

```python 
import ejson
import gzip

with open('users.json', 'r', encoding='utf-8') as file:
	contents = ejson.loads(file.read())

# Produces a file with about 250 MB that has a bad CRC
with gzip.open('users_compressed.json.gz', 'w') as file:
	file.write(ejson.dumps(dict(list(contents.items()))).encode('utf-8'))

# Produces a file with about 125 MB that opens fine
with gzip.open('users_compressed_1.json.gz', 'w') as file:
	file.write(ejson.dumps(dict(list(contents.items())[len(contents)//2:])).encode('utf-8'))

# Produces a file with about 125 MB that opens fine
with gzip.open('users_compressed_2.json.gz', 'w') as file:
	file.write(ejson.dumps(dict(list(contents.items())[:len(contents)//2])).encode('utf-8'))
```
# environment

Python 3.10.8 on a M1 mac (macos 12.6)

Not sure how to debug it further at this point. Has anyone had similar problems?

**Comment by rhpvorderman** [comment] 2023-03-21 11:04
users.json does not look like a thing that you can share publicly. However I can download the [Human reference genome](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz) 

That is plenty big.

I used this test code
```
import sys
import gzip

with gzip.open(sys.argv[1]) as file:
    contents = file.read()

with gzip.open("test.gz", "w", compresslevel=1) as file:
  file.write(contents)
```
And run `python test_gzip.py GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz`  using python 3.10 (installed with conda)

Calling `gzip -t` on test.gz does not throw an error.

Can you try the same steps to reproduce it on your M1 mac?

**Comment by ronaldoussoren** [comment] 2023-12-10 19:56
This is likely related to #105967: on macOS linking to /usr/lib/libz.dylib the function ``zlib.crc32`` would give the wrong result when updating with more than 2GB in one call to ``crc32``. 

That bug was recently fixed by implementing a work-around for Apple's bug on our side. 

@serhiy-storchaka : Does conda link to the system libz or to a copy included with conda? 

Below an shell command that prints the load commands for the zlib extension module, with output for python 3.12 installed through our own installer:
```
$ otool -vL $(python3.12 -c 'import zlib; print(zlib.__file__)')                                                                     (gh-102362)cpython
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload/zlib.cpython-312-darwin.so (architecture x86_64):
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload/zlib.cpython-312-darwin.so (architecture arm64):
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
```

**Comment by ronaldoussoren** [comment] 2023-12-11 14:26
> @ronaldoussoren Sorry, I have no Mac.

No problem, I can test locally later this week.

**Comment by ronaldoussoren** [comment] 2023-12-16 10:56
I cannot test on locally because Apple fixed the CRC32 issue in the version of macOS I'm running, but based on code inspection I'd say this is the same issue.

**Closed as completed by ronaldoussoren** 2023-12-16 10:56 UTC
Labels: type-bug, OS-mac, stdlib
