### ISSUE TITLE
Can't Access discuss.python.org

### ISSUE THREAD

**Issue by HorridModz** [python/cpython#106841] opened 2023-07-17 22:20 UTC
# Bug report

Forgive me if this is the wrong place to ask, but I cannot access the [python discussion forums](https://discuss.python.org).

I just registered a new account (I tied it to my Github account). When I logged in, this popup came up:
![image](https://github.com/python/cpython/assets/105762560/6b7e0d61-ce85-4dde-9d36-0a9000630861)

When the popup is up, I cannot click the "Got It" button. In addition, I cannot click anything else. However, the site works fine when I am not logged in.

I did manage to log out of my account by clearing my cookies. When I logged out, the site went back to working and letting me click things. However, when I logged back in, the popup came up, and it broke the site.

I have tried clearing cookies and disabling javascript. I have not tested in another browser because the only browser I have installed is Microsoft Edge. I have not tried creating a new account.

# Your environment

- Operating system and architecture: Windows 11, Microsoft Edge

**Comment by terryjreedy** [comment] 2023-07-18 01:24
This is the wrong place, except that we would normally suggest posting on the discuss help panel.  The site works fine on Edge.  I cannot reproduce the beginner message without making a new and temporary second account.  But I must have clicked away the popup at one time.  I suggest rebooting and starting in a fresh browser window.  This usually solves key and mouse problems for me.  And do so on a separate day in case the site is having temporary problems.

**Comment by pochmann** [comment] 2023-07-18 14:43
Have you tried disabling your browser extensions?

**Comment by sunmy2019** [comment] 2023-07-19 03:23
You can continue the discussion here, while I will close this as invalid.

**Closed as not planned by sunmy2019** 2023-07-19 03:23 UTC

**Comment by HorridModz** [comment] 2023-07-21 00:11
Thanks so much! Sorry for the late reply; I did not go on Github yesterday. I checked today (after closing my browser when I logged off after asking this question and opening it today - restarting it), and it worked! I did not change anything, and my browser extensions / add-ons were not the issue. It just worked.

I was under the assumption that refreshing the page should count as a full restart, but come to think of it, I guess it makes sense that factors like caching and bugs in Edge do warrant a restart,

Thanks for the help, and I'm sorry I had to post here. Thank you for being understanding and kind :)

**Comment by HorridModz** [comment] 2023-07-22 19:08
@sunmy2019 @terryjreedy @pochmann

**Update**: This isn't an issue with that pop-up, as I first thought it was. 50% of the time I load the website, it will simply be unresponsive. If I keep the tab loaded and don't change anything, it will remain responsive. But if I navigate to a different page on the site or change the tab to a different site (for example, sometimes I look something up on the same tab, then use the back arrow to go back to the site), that 50% change of being unresponsive replays.

When the site becomes unresponsive, restarting the browser or closing the tab or opening discuss.python.org in a new tab or navigating to a different page of the discuss.python.org site will not work - the site will stay unresponsive.

Closing out of the tab, restarting the browser, and rebooting my computer seems to fix the issue for a variable amount of page navigations, and I do not know if a certain action or page navigation triggers the issue. However, this issue nevertheless soon pops back up again, and I have to repeat one of these methods.

Clearing my cookies results in funny behavior: It appears to fix the issue, but always *only once* - when I refresh the tab or open the site in a new tab or navigate to a different page on the tab, the issue immediately comes back.

Through lots of testing, I have concluded that the `discuss.python.org > Service Workers > https://discuss.python.org` cookie seems to be the culprit. To document this in a way that I can personally and consistently reproduce and observe, I have done this: 

 > *Repeat this process over and over, and it should stay consistent*: 
 > 1. Observe that the site is unresponsive.
 > 2. Remove the `discuss.python.org > Service Workers > https://discuss.python.org` cookie.
 > 3. Refresh the page, now that the the `discuss.python.org > Service Workers > https://discuss.python.org` cookie is gone.
 > 4. Observe that the site now works.
 > 5. Observe that the `discuss.python.org > Service Workers > https://discuss.python.org` cookie has been recreated upon refreshing the page.
 > 6. Refresh the page again, with the `discuss.python.org > Service Workers > https://discuss.python.org` cookie having been recreated.
 > 7. Observe that the site is unresponsive.

I tried to find out the value of this cookie, but the devtools wouldn't show me it (I'm kind of a noob at this, so maybe I'm doing it wrong). If the value of the cookie is important, tell me how to find it and I will try to follow along.
![image](https://github.com/python/cpython/assets/105762560/f08c2236-b4bc-4879-a509-ff66658a797c)

**Comment by HorridModz** [comment] 2023-07-22 19:10
Yes, blocking cookies for the site fixed the issue, further confirming my theory. However, the site does not work without them.

**Comment by HorridModz** [comment] 2023-07-22 19:20
**Update**:

I just discovered something huge: The issue **is not** caused by navigating to different pages. It's caused by loading the site twice. In other words: I am able to navigate around on the site as much as I like, but if I leave the site - whether that's by changing the tab to a different site, opening the site again in a second tab, closing the tab, or reloading the tab (which can be done manually or by closing my browser, causing the site to become unloaded).

Also, though the process of *closing out of the tab, restarting the browser, and rebooting my computer* works, just **rebooting my computer** seems to fix it.

**Comment by HorridModz** [comment] 2023-07-22 19:38
To correct my misassumptions and consolidate all this information across all these posts, I am going to write a summary of this issue. This summary may be incorrect, but it is what seems to be the cause based on all my research:

On my Windows 11 device, when using Microsoft Edge, the [python discussion forums](discuss.python.org) website has a bug that makes the site completely impossible to interact with. This issue is not caused by any of my Microsoft Edge extensions (AKA add-ons).

The issues lies in the `discuss.python.org > Service Workers > https://discuss.python.org` cookie. This cookie causes the site to not load the interactive elements - the buttons are not loaded (they do not do anything when clicked or change the cursor to a pointer when hovered over) and the scroll bar (when the page requires one) is not loaded (it does not render, going to where the scroll bar should be and performing the scrolling motion does not do anything, and the arrow keys and mouse scroll wheel do not do anything). Without the interactive elements, the site is impossible to interact with, and therefore useless as an image. Removing the cookie fixes the issue, but the cookie is regenerated the next time the page is loaded, meaning that you have to remove the cookie every time you want to open and use the website.

**Comment by HorridModz** [comment] 2023-07-22 19:54
Since I can't access the discussion forums, it would be great if someone could post it for me. I'll write the post for you:

**Title**: Can't Access discuss.python.org

**Body**:

```
I am creating this topic on behalf of another user. Since they are unable to access this website, they opened an issue on github. Please read the issue: https://github.com/python/cpython/issues/106841

Though you should still read the github issue, here is a summary of the issue written by said user:

[quote]
To correct my misassumptions and consolidate all this information across all these posts, I am going to write a summary of this issue. This summary may be incorrect, but it is what seems to be the cause based on all my research:

Summary of Issue:

On my Windows 11 device, when using Microsoft Edge, the [python discussion forums](https://github.com/python/cpython/issues/discuss.python.org) website has a bug that makes the site completely impossible to interact with. This issue is not caused by any of my Microsoft Edge extensions (AKA add-ons). This issue started occurring immediately after I created an account.

Theory of what Causes the Issue:

The issues lies in the discuss.python.org > Service Workers > https://discuss.python.org/ cookie. This cookie causes the site to not load the interactive elements - the buttons are not loaded (they do not do anything when clicked or change the cursor to a pointer when hovered over) and the scroll bar (when the page requires one) is not loaded (it does not render, going to where the scroll bar should be and performing the scrolling motion does not do anything, and the arrow keys and mouse scroll wheel do not do anything). Without the interactive elements, the site is impossible to interact with, and therefore useless as an image. Removing the cookie fixes the issue, but the cookie is regenerated the next time the page is loaded, meaning that you have to remove the cookie every time you want to open and use the website.

User Information:

Windows 11 operating system
Microsoft Edge
Browser extensions do not matter as the issue occurs even when all my extensions are disabled
My [python discussion forums](https://github.com/python/cpython/issues/discuss.python.org) account is connected to [this](https://github.com/HorridModz) Github account (I used the Log in with Github option when signing up).
[/quote]
```

**Comment by HorridModz** [comment] 2023-07-29 02:28
**Final Update**:

If anyone stumbles across this, the issue has been [solved](https://meta.discourse.org/t/cant-access-discuss-python-org/272987).
