### ISSUE TITLE
New REPL does not include globals from executed module when used with `-i`

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#120678] opened 2024-06-18 11:05 UTC
# Bug report

### Bug description:

If I have a module called `foo`.py with the following contents in the root of my CPython local clone:

```py
class Foo: pass
```

Then running `PYTHON_BASIC_REPL=1 ./python.exe -i foo.py`, I get the following behaviour: `foo.py` is executed, and the `Foo` class is available in the globals of the REPL:

```pycon
~/dev/cpython (main)⚡ % PYTHON_BASIC_REPL=1 ./python.exe -i foo.py 
>>> Foo
<class '__main__.Foo'>
```

But with the new REPL, the `Foo` class isn't available!

```pycon
~/dev/cpython (main)⚡ % ./python.exe -i foo.py 
>>> Foo
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    Foo
NameError: name 'Foo' is not defined
>>> 
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-120904
* gh-121916
* gh-121924
* gh-121929

**Comment by eryksun** [comment] 2024-06-18 11:58
It seems the new REPL doesn't get executed in the `__main__` namespace. This can be worked around manually:

```text
$ python -ic "class Foo: pass"
```
```pycon
>>> Foo
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    Foo
NameError: name 'Foo' is not defined
```

```pycon
>>> import sys
>>> from _pyrepl.simple_interact import run_multiline_interactive_console
>>> run_multiline_interactive_console(sys.modules['__main__'])
>>> Foo
<class '__main__.Foo'>
>>> dir()
['CAN_USE_PYREPL', 'Foo', '__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'interactive_console', 'os', 'sys']
```
This can be addressed in "Lib/_pyrepl/\_\_main\_\_.py". All imports and assignments in that module (e.g. `CAN_USE_PYREPL`, `interactive_console`, `os`, and `sys`) should be uniquely prefixed to avoid collisions and to allow clearing them before calling `run_interactive(mainmodule)`.

**Comment by vstinner** [comment] 2024-06-20 13:36
I marked https://github.com/python/cpython/issues/120798 as a duplicate of this issue.

**Comment by AlexWaygood** [comment] 2024-06-22 15:36
This is a regression that was caused by https://github.com/python/cpython/pull/119547.

**Comment by ambv** [comment] 2024-07-22 11:50
This is solved now, thanks everyone!

**Closed as completed by ambv** 2024-07-22 11:50 UTC
Labels: type-bug, 3.13, 3.14, topic-repl
