### ISSUE TITLE
Implement and document PEP 669.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#103082] opened 2023-03-28 14:29 UTC
Now that PEP 669 is accepted, it needs to be implemented and documented.

- [x] Implement the PEP
- [x] Decide on and implement policy for monitors seeing the code in other monitors.
- [x] Document the PEP
- [ ] Use "macro" instructions to reduce code duplication in bytecodes.c

### Linked PRs
* gh-103083
* gh-103474
* gh-103507
* gh-103561
* gh-104387
* gh-107069
* gh-107075
* gh-107772
* gh-107882
* gh-107978
* gh-108909
* gh-111048

**Comment by markshannon** [comment] 2023-04-05 11:29
Specific things to document (that aren't clear from the PEP) (from comments by @gvanrossum):

`event_set` is a "set" constructed by OR-ing various events together (a common C idiom of course but not apparent until you see their integer values).

From GVR: "The naming of the CALL and RETURN/RAISE events is a bit confusing -- we have CALL (universal), C_RETURN/PY_RETURN (per language), but then C_RAISE and RAISE -- why isn't the latter PY_RAISE, just for consistency?"

There are good reasons for this design, so they should be documented.

**Comment by pablogsal** [comment] 2023-04-18 13:28
Seems that this PR has broken the tracerefs buildbot:

https://buildbot.python.org/all/#/builders/484/builds/3091

**Comment by pablogsal** [comment] 2023-04-18 13:29
See also https://github.com/python/cpython/pull/103083#issuecomment-1505289254

**Comment by arhadthedev** [comment] 2023-05-05 11:19
@markshannon Can this issue be closed as done?

**Comment by jpe** [comment] 2023-07-13 21:33
Is there any way to get the active exception from a PY_UNWIND event callback? I was hoping the exception would be passed to the callback but it isn't. This was an issue with the old tracer function debugger / profiler support so it's not really a regression, but I was hoping to avoid the work arounds that we used with it.

Note the the signature for several of the events aren't specified -- including PY_UNWIND and EXCEPTION_HANDLED. They're easily enough determined (though my guess was wrong for PY_UNWIND), but it would be better if they were documented.

**Comment by jpe** [comment] 2023-07-14 16:39
It looks like returning DISABLE from a handler for an event >= PY_MONITORING_INSTRUMENTED_EVENTS triggers an assert in a debug build. It would probably be better to just ignore a DISABLE return value since anything else can be returned (I think) or mandate that None be returned. If the current behavior is retained, it should be documented.

Please let me know if you want me to open separate bugs for this and for other sys.monitoring issues. Otherwise, I'lll add to this bug.

**Comment by jpe** [comment] 2023-07-14 20:31
An exception raised in a EXCEPTION_HANDLED callback triggers an assert in a debug build of 3.12b4. I was using the following incorrect signature for a callback method and registering it as a bound method --

    def _py_handled_event(self, instruction_offset: int, exception: BaseException):

This was my mistake (it was a simple oversight while editing) but it the calling code should handle the exception without crashing.

**Comment by jpe** [comment] 2023-07-14 21:05
It looks like no RAISE event is emitted for a bare raise in an except: clause or at the end of a finally: clause that implicitly reraises an exception. I don't know whether this a problem with the implementation or it should simply be documented that this is to be expected. My use case is to track what exception is active so it's available to an unwind handler.

**Comment by carljm** [comment] 2023-07-18 23:11
@jpe I think opening a new issue for each separable problem will make these easier to track and triage, and less likely they'll fall through the cracks.

**Comment by AA-Turner** [comment] 2023-09-08 12:20
Is this issue now complete given #107772?

**Closed as completed** 2024-01-05 19:50 UTC
Labels: type-feature, interpreter-core, 3.12
