### ISSUE TITLE
Deadlock when mixing event loops and subprocesses

### ISSUE THREAD

**Issue by cef2f0f1-8587-4bab-9241-862a7f43a75b** [python/cpython#88056] opened 2021-04-19 18:36 UTC
BPO | [43890](https://bugs.python.org/issue43890)
--- | :---
Nosy | @ehrmann
Files | <li>[subprocess_asyncio_deadlock.py](https://bugs.python.org/file49967/subprocess_asyncio_deadlock.py "Uploaded as text/plain at 2021-04-19.18:36:19 by @ehrmann")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-19.18:36:19.433>
labels = ['type-bug', '3.8']
title = 'Deadlock when mixing event loops and subprocesses'
updated_at = <Date 2021-04-19.18:36:19.433>
user = 'https://github.com/ehrmann'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-19.18:36:19.433>
actor = 'thomas'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-04-19.18:36:19.433>
creator = 'thomas'
dependencies = []
files = ['49967']
hgrepos = []
issue_num = 43890
keywords = []
message_count = 1.0
messages = ['391386']
nosy_count = 1.0
nosy_names = ['thomas']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43890'
versions = ['Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment] 2022-04-16 12:35
Reproduced on 3.11

**Comment by kumaraditya303** [comment] 2022-04-16 12:59
So after some investigation, this issue is a duplicate of https://github.com/python/cpython/issues/90368 and if you remove the print calls it is fixed. Moreover the fix in https://github.com/python/cpython/pull/30310 fixes this issue so closing as duplicate.

Duplicate of https://github.com/python/cpython/issues/90368

**Closed as completed by kumaraditya303** 2022-04-16 12:59 UTC
Labels: type-bug, topic-asyncio, 3.11, 3.10, 3.9 (EOL)
