### ISSUE TITLE
Investigate int/float conversion costs in math functions

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#95032] opened 2022-07-20 04:10 UTC
Relative to other float math functions, the ``lgamma()`` function pays an inordinately large penalty for converting inputs from int to float.  Presumably the timing difference should be about the same for all the functions.

For the ``fabs()`` function, the conversion only adds 8ns while the ``lgamma() `` adds an enormous 40ns which is more time than ``sqrt()`` and ``exp()`` with integer arguments take in total.  Something is amiss.

```
       float   int
       -----  ----
log     42.3  41.1
exp     18.1  30.7
fabs    16.6  22.7
sin     21.8  37.1
sqrt    16.7  22.4
gamma   16.4  22.4
lgamma  49.1  90.3

```

Timing Detail
------------

$ python3.11 -m timeit -r 11 -s 'from math import log as f' 'f(5.0)'
5000000 loops, best of 11: 42.3 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import exp as f' 'f(5.0)'
20000000 loops, best of 11: 18.1 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import fabs as f' 'f(5.0)'
20000000 loops, best of 11: 16.6 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import sin as f' 'f(5.0)'
10000000 loops, best of 11: 21.8 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import sqrt as f' 'f(5.0)'
20000000 loops, best of 11: 16.7 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import gamma as f' 'f(5.0)'
20000000 loops, best of 11: 16.4 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import lgamma as f' 'f(5.0)'
5000000 loops, best of 11: 49.1 nsec per loop

$ python3.11 -m timeit -r 11 -s 'from math import log as f' 'f(5)'
5000000 loops, best of 11: 41.1 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import exp as f' 'f(5)'
10000000 loops, best of 11: 30.7 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import fabs as f' 'f(5)'
10000000 loops, best of 11: 22.7 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import sin as f' 'f(5)'
10000000 loops, best of 11: 37.1 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import sqrt as f' 'f(5)'
10000000 loops, best of 11: 22.4 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import gamma as f' 'f(5)'
10000000 loops, best of 11: 22.4 nsec per loop
$ python3.11 -m timeit -r 11 -s 'from math import lgamma as f' 'f(5)'
5000000 loops, best of 11: 90.3 nsec per loop

**Comment by mdickinson** [comment] 2022-07-20 07:06
Very odd. I don't see any difference in the way that `gamma` and `lgamma` are implemented here: both use exactly the same `FUNC1A` wrapper around a double-to-double core function. Could this be some weird side-effect of PGO?

Here are timings on my machine (with Python 3.11.0b4 from MacPorts). I don't see the same discrepancy that you see.

For lgamma:
```
mdickinson@mirzakhani ~ % python3.11 -m timeit -r 11 -s "from math import lgamma as f" "f(5)"  
5000000 loops, best of 11: 97.5 nsec per loop
mdickinson@mirzakhani ~ % python3.11 -m timeit -r 11 -s "from math import lgamma as f" "f(5.0)"
5000000 loops, best of 11: 89.6 nsec per loop
```

For gamma:
```
mdickinson@mirzakhani ~ % python3.11 -m timeit -r 11 -s "from math import gamma as f" "f(5)"  
10000000 loops, best of 11: 35.7 nsec per loop
mdickinson@mirzakhani ~ % python3.11 -m timeit -r 11 -s "from math import gamma as f" "f(5.0)"
10000000 loops, best of 11: 27.2 nsec per loop
```

**Comment by mdickinson** [comment] 2022-07-20 07:27
Here are timings for a local build with `./configure --enable-optimizations`, at commit [0f34c7e2d3163525813dbd644f30db58e6d36af2](https://github.com/python/cpython/commit/0f34c7e2d3163525813dbd644f30db58e6d36af2). I still can't reproduce the effect that @rhettinger is seeing.

For lgamma:
```
mdickinson@mirzakhani cpython % ./python.exe -m timeit -r 11 -s "from math import lgamma as f" "f(5)"  
5000000 loops, best of 11: 98.3 nsec per loop
mdickinson@mirzakhani cpython % ./python.exe -m timeit -r 11 -s "from math import lgamma as f" "f(5.0)"
5000000 loops, best of 11: 87.8 nsec per loop
```

For gamma:
```
mdickinson@mirzakhani cpython % ./python.exe -m timeit -r 11 -s "from math import gamma as f" "f(5)"  
10000000 loops, best of 11: 37.9 nsec per loop
mdickinson@mirzakhani cpython % ./python.exe -m timeit -r 11 -s "from math import gamma as f" "f(5.0)"
10000000 loops, best of 11: 25.8 nsec per loop
```

**Comment by rhettinger** [comment] 2022-07-20 14:44
Since you're not seeing the effect, it must be build specific rather that something in the source code.  I'm running the stock Mac build distributed on python.org. It could also be a difference between my running on an Apple M1 instead of an Intel processor.

$ python3.11
Python 3.11.0b4 (v3.11.0b4:5a7e1e0a92, Jul 11 2022, 12:47:14) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by mdickinson** [comment] 2022-07-20 15:11
> I'm running the stock Mac build distributed on python.org.

Thanks. Here are my results on that one:

```
mdickinson@mirzakhani ~ % python3
Python 3.11.0b4 (v3.11.0b4:5a7e1e0a92, Jul 11 2022, 12:47:14) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
```

```
mdickinson@mirzakhani ~ % python3 -m timeit -r 11 -s "from math import lgamma as f" "f(5)"
2000000 loops, best of 11: 98.4 nsec per loop
mdickinson@mirzakhani ~ % python3 -m timeit -r 11 -s "from math import lgamma as f" "f(5.0)"
5000000 loops, best of 11: 87.7 nsec per loop
mdickinson@mirzakhani ~ % python3 -m timeit -r 11 -s "from math import gamma as f" "f(5)"  
10000000 loops, best of 11: 34.5 nsec per loop
mdickinson@mirzakhani ~ % python3 -m timeit -r 11 -s "from math import gamma as f" "f(5.0)"
10000000 loops, best of 11: 26.3 nsec per loop
```

So it looks like it is indeed M1-specific.

**Comment by ned-deily** [comment] 2022-07-21 05:13
I'm looking into it.

**Comment by rhettinger** [comment] 2022-07-23 02:57
Confirmed that this is M1 specific.  I ran the stock python.org macOS installer and observed the timing difference on an M1 Mac but not on my Intel Mac (Haswell processor).

Also, on the M1, I compared the stock python.org build vs a simple local build using only ``./configure && make``.  The timing difference remained but was less pronounced on the local build:

Local Build running on M1
----------

```
raymond@raymonds-mbp cpython % ./python.exe -m timeit -s 'from math import lgamma' 'lgamma(5.0)'
5000000 loops, best of 5: 49 nsec per loop
raymond@raymonds-mbp cpython % ./python.exe -m timeit -s 'from math import lgamma' 'lgamma(5)'
5000000 loops, best of 5: 76.2 nsec per loop
```

Stock Build running on M1
------------------------
```raymond@raymonds-mbp cpython % python3.11 -m timeit -s 'from math import lgamma' 'lgamma(5.0)'
5000000 loops, best of 5: 49 nsec per loop
raymond@raymonds-mbp cpython % python3.11 -m timeit -s 'from math import lgamma' 'lgamma(5)'
5000000 loops, best of 5: 90.3 nsec per loop
```

**Comment by ned-deily** [comment] 2022-07-25 17:55
After looking at the results across a variety of Python builds on more than one version of macOS and on both Intel and Apple Silicon Macs, it is pretty clear that this is just a difference between the two platforms, with or without enabling optimizations. As we have seen before, it is not unusual for differences at the microbenchmark level (10's of nsecs) and I'm sure that, if one were to go looking for them, there are likely many other such differences down at this level. In this case, if anything, I think the numbers tend to indicate that the lgamma(float) case is somewhat faster on Apple Silicon Macs rather than that the lgamma(int) case is slower. Whether the differences are significant in real world applications is not something I have an opinion on but my curiosity is satisfied that there is no build problem here. If someone is curious enough to dig into the generated code to see if there are compiler differences between the two archs or whether the compiler is able to take advantage of the differences in the CPU archs, it might be of some interest but I think we can just close this issue.

**Closed as not planned** 2022-10-09 08:34 UTC
Labels: performance, OS-mac, 3.11, 3.12
