### ISSUE TITLE
Tkinter/IDLE: literal astral char discombobulates text editing

### ISSUE THREAD

**Issue by 1e2b3793-5146-46c5-b55f-27b9e782b291** [python/cpython#88383] opened 2021-05-23 15:36 UTC
BPO | [44217](https://bugs.python.org/issue44217)
--- | :---
Nosy | @terryjreedy, @taleinat, @stevendaprano, @serhiy-storchaka, @erlend-aasland, @shreyanavigyan

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2021-05-23.15:36:23.162>
labels = ['type-bug', 'expert-tkinter', '3.9', '3.10', '3.11', 'expert-IDLE']
title = 'Tkinter/IDLE: literal astral char discombobulates text editing'
updated_at = <Date 2021-05-25.18:53:05.141>
user = 'https://github.com/shreyanavigyan'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-25.18:53:05.141>
actor = 'shreyanavigyan'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE', 'Tkinter']
creation = <Date 2021-05-23.15:36:23.162>
creator = 'shreyanavigyan'
dependencies = []
files = []
hgrepos = []
issue_num = 44217
keywords = []
message_count = 15.0
messages = ['394201', '394206', '394207', '394214', '394215', '394216', '394217', '394230', '394232', '394236', '394238', '394239', '394247', '394387', '394389']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'taleinat', 'steven.daprano', 'serhiy.storchaka', 'erlendaasland', 'shreyanavigyan']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44217'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by terryjreedy** [comment] 2023-06-17 22:00
Closing as a duplicate of previous #83307.

**Closed as completed by terryjreedy** 2023-06-17 22:00 UTC
Labels: type-bug, topic-tkinter, topic-IDLE, 3.11, 3.10, 3.9 (EOL)
