### ISSUE TITLE
tuple default aurguments in function signatures are missing brackets

### ISSUE THREAD

**Issue by verhovsky** [python/cpython#92416] opened 2022-05-07 07:09 UTC
**Documentation**

https://docs.python.org/3/library/logging.handlers.html#logging.handlers.SysLogHandler

says 

> class logging.handlers.SysLogHandler(address='localhost', SYSLOG_UDP_PORT, facility=LOG_USER, socktype=socket.SOCK_DGRAM)

instead of 

> class logging.handlers.SysLogHandler(address=('localhost', SYSLOG_UDP_PORT), facility=LOG_USER, socktype=socket.SOCK_DGRAM)

or https://docs.python.org/3/library/http.cookiejar.html#http.cookiejar.DefaultCookiePolicy

which says

> class http.cookiejar.DefaultCookiePolicy(blocked_domains=None, allowed_domains=None, netscape=True, rfc2965=False, rfc2109_as_netscape=None, hide_cookie2=False, strict_domain=False, strict_rfc2965_unverifiable=True, strict_ns_unverifiable=False, strict_ns_domain=DefaultCookiePolicy.DomainLiberal, strict_ns_set_initial_dollar=False, strict_ns_set_path=False, secure_protocols='https', 'wss')¶

instead of

> class http.cookiejar.DefaultCookiePolicy(blocked_domains=None, allowed_domains=None, netscape=True, rfc2965=False, rfc2109_as_netscape=None, hide_cookie2=False, strict_domain=False, strict_rfc2965_unverifiable=True, strict_ns_unverifiable=False, strict_ns_domain=DefaultCookiePolicy.DomainLiberal, strict_ns_set_initial_dollar=False, strict_ns_set_path=False, secure_protocols=('https', 'wss'))

i.e. `secure_protocols=('https', 'wss')` instead of `secure_protocols='https', 'wss'`.

**Comment by serhiy-storchaka** [comment] 2022-05-07 14:21
This is a duplicate of #89560.

**Closed as completed by serhiy-storchaka** 2022-05-07 14:21 UTC
Labels: docs
