### ISSUE TITLE
test_cppext fails on s390x RHEL7 Refleaks 3.x: option ‘-std=gnu11’ is valid for C/ObjC but not for C++ (GCC 4.8.5)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#107084] opened 2023-07-22 23:47 UTC
s390x RHEL7 Refleaks 3.x: https://buildbot.python.org/all/#/builders/129/builds/828

```
test test_cppext failed -- multiple errors occurred; run in verbose mode for details
(...)
      gcc -std=gnu11 -pthread -fno-strict-overflow -Wsign-compare -g -Og -Wall -fPIC -I/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z.refleak/build/build/test_python_34724æ/test_python_worker_42721æ/tempcwd/env/include -I/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z.refleak/build/Include -I/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z.refleak/build -c /home/dje/cpython-buildarea/3.x.edelsohn-rhel-z.refleak/build/Lib/test/_testcppext.cpp -o build/temp.linux-s390x-cpython-313-pydebug/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z.refleak/build/Lib/test/_testcppext.o -Werror -std=c++03
      cc1plus: error: command line option ‘-std=gnu11’ is valid for C/ObjC but not for C++ [-Werror]
      cc1plus: all warnings being treated as errors
      error: command '/usr/bin/gcc' failed with exit code 1

```

**Comment by vstinner** [comment] 2023-07-22 23:47
test.pythoninfo:

```
CC.version: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
```

**Comment by vstinner** [comment] 2023-07-23 00:26
Maybe I can just skip the test on old GCC versions, like GCC 4.8.

@stratakis: Do we care about testing C++ support of Python 3.13 on RHEL7?

**Comment by dtrodrigues** [comment] 2023-07-23 16:03
This appears to be a dupe of https://github.com/python/cpython/issues/105776 introduced by https://github.com/python/cpython/pull/104925

**Closed as completed** 2023-08-16 13:03 UTC
Labels: type-bug
