### ISSUE TITLE
init_importlib_external  return _PyStatus_ERR("external importer setup failed");

### ISSUE THREAD

**Issue by dshawshank** [python/cpython#120980] opened 2024-06-25 02:00 UTC
# Bug report

### Bug description:

I downloaded the 3.10.0 version of cpython, compiled it on Android Studio, generated libpython.so, and called the initialization interface, 

but it failed. After debugging, I found that the interface **init_importlib_external** returned an error: **external importer setup failed**. 

I don't know what the reason is? Is there any solution to use the Python interpreter in Android JNI development? Thank you.

### CPython versions tested on:

3.10

### Operating systems tested on:

Other

**Comment by sobolevn** [comment] 2024-06-25 18:16
Hi 👋 

Python3.10 is now security only. And the bug description if very vague. I don't think that it can be reproduced in this state.

But!

You can see Python3.13: https://github.com/python/cpython/tree/main/Android
And https://peps.python.org/pep-0738

I hope this helps!

I will close this issue due to the reasons above.
Feel free to reopen with a newer python version and a reproducer :)

**Closed as not planned by sobolevn** 2024-06-25 18:16 UTC
