### ISSUE TITLE
shutil.which() can return non-executable path starting with 3.12 on Windows

### ISSUE THREAD

**Issue by lazka** [python/cpython#127001] opened 2024-11-19 06:52 UTC
# Bug report

### Bug description:

Starting with Python 3.12 if a file is in PATH that does not end with PATHEXT, but happens to be named the same as the searched command it is returned instead of the real command later in PATH which includes PATHEXT.

```python
# Assume:
# PATH=C:\foo;C:\WINDOWS\system32
# "C:\foo\cmd" exists
# "C:\WINDOWS\system32\cmd.exe" exists

import shutil
print(shutil.which('cmd'))
# Actual: C:\foo\cmd
# Expected: C:\WINDOWS\system32\cmd.exe (3.11 result)
```

I have verified that this change was introduced with https://github.com/python/cpython/pull/103179 and reverting it fixes the issue.

@csm10495 ^

Downstream context: https://github.com/mesonbuild/meson/pull/13886

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-127035
* gh-127156
* gh-127158

**Comment by lazka** [comment] 2024-11-19 07:15
Similarly it also returns wrong results for non-executable paths as input:

```python
>>> import shutil
>>> print(shutil.which("C:\\Windows\\system.ini"))
C:\Windows\system.ini
```

**Comment by serhiy-storchaka** [comment] 2024-11-19 19:02
Should not it be fixed by #109590?

**Comment by serhiy-storchaka** [comment] 2024-11-19 19:14
Ah, it still checks for file without extension.

**Comment by lazka** [comment] 2024-11-19 19:21
> Should not it be fixed by #109590?

That only handles the "in the same directory" case, and not in different directories, from what I see.

But, that issue mentioned `Get-Command cmd` in powershell, and that also returns the wrong path as "CommandType=Application" here, even though the docs say that it only returns files ending with PATHEXT (https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-command?view=powershell-7.4#-commandtype) so I don't know what's "right" anymore :)

**Comment by zooba** [comment] 2024-11-19 20:03
The right behaviour ought to be "whatever `CreateProcess("cmd")` would run". Terminals all layer their own logic on top, but Python tries to generally stick to the closest public API that implements the functionality.

(One explicit exception we make to `CreateProcess` behaviour is that we don't search the application directory first with `which`, because if we did, it wouldn't be useful. By skipping that somewhat strange edge case, it is possible to use `which` to _override_ the application directory. This mainly only matters for `python.exe` - `CreateProcess("python")` will always launch `sys._base_executable` due to how the API works, but `CreateProcess(shutil.which("python"))` follows `PATH`, which is likely what was intended if a user provided the command name.)

**Comment by lazka** [comment] 2024-11-19 20:37
> The right behaviour ought to be "whatever `CreateProcess("cmd")` would run". Terminals all layer their own logic on top, but Python tries to generally stick to the closest public API that implements the functionality.

Also CreateProcess prefers "C:\Windows\System32" over PATH, like curl/tar/bash that are in there, which is another can of worms.

Since my initial presented scenario occurs in MSYS2, and it's not quite clear why we have that "cmd" bash script in PATH in the first place, I'm trying to get rid of it instead now :/

**Comment by csm10495** [comment] 2024-11-21 01:07
Ouch. Sorry for the regression folks. I wish this was less complicated than it is. I see @serhiy-storchaka has already started on a fix. Thanks all.

**Comment by serhiy-storchaka** [comment] 2024-11-22 10:22
There was other bug introduced in #109995: full match did not work for files with multcomponent extension in PATHEXT, (e.g. `.foo.bar`).

Other corner case was only discussed in comments: a dot (`.`) in PATHEXT.

**Closed as completed** 2024-11-22 17:32 UTC
Labels: type-bug, OS-windows, stdlib, 3.12, 3.13, 3.14

**Comment by lazka** [comment] 2024-11-22 18:01
I can confirm that this fixes things for my use case. Thanks everyone!

**Comment by eabase** [comment] 2024-12-14 06:04
This got to be the best issue number in all of internet!
`127.0.0.1`
