### ISSUE TITLE
Add busy_configure, busy_config, busy_forget, busy_hold in tkinter.Misc

### ISSUE THREAD

**Issue by Python-ZZY** [python/cpython#107677] opened 2023-08-06 03:08 UTC
Pull requests: https://github.com/python/cpython/pull/107676

Example:
```py
from tkinter import *

root = Tk()
root.busy_hold(cursor='xterm')
# root.busy_config(cursor='xterm')
root.busy_forget()

mainloop()
```

### Linked PRs
* gh-107676

**Comment by serhiy-storchaka** [comment] 2023-08-06 05:48
This is a duplicate of #72684.

**Closed as completed by serhiy-storchaka** 2023-08-06 05:48 UTC
Labels: type-feature, topic-tkinter
