### ISSUE TITLE
test_pickle/test_pickletools fail when running tests sequentially.

### ISSUE THREAD

**Issue by Yhg1s** [python/cpython#103247] opened 2023-04-04 14:49 UTC
When running the test suite sequentially (as is done as part of the release process), an interaction between test_imp, test_importlib and subinterpreters is causing test_pickle and test_pickletools to fail. The easiest reproducer::

```
% ./python -m test test_imp test_importlib test_pickletools
0:00:00 load avg: 0.22 Run tests sequentially
0:00:00 load avg: 0.22 [1/3] test_imp
0:00:00 load avg: 0.22 [2/3] test_importlib
0:00:03 load avg: 0.22 [3/3] test_pickletools
test test_pickletools failed -- Traceback (most recent call last):
  File "Lib/test/pickletester.py", line 1989, in test_builtin_types
    s = self.dumps(t, proto)
        ^^^^^^^^^^^^^^^^^^^^
  File "Lib/test/test_pickletools.py", line 11, in dumps
    return pickletools.optimize(pickle.dumps(arg, proto, **kwargs))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.PicklingError: Can't pickle <class 'importlib._bootstrap.BuiltinImporter'>: it's not the same object as importlib._bootstrap.BuiltinImporter

test_pickletools failed (1 error)

== Tests result: FAILURE ==

2 tests OK.

1 test failed:
    test_pickletools

Total duration: 4.2 sec
Tests result: FAILURE
```
 
The failure happens in both test_pickle and test_pickletools (test_pickletools's traceback is more obvious), after _in the same process_ running both test_imp and either test_import or test_importlib. Disabling `test_imp.ImportTests.test_create_builtin_subinterp()` makes the tests pass. (This was happening before #102982 as well as after it, so I don't think it is involved here.)

I expect this is an unintentional side-effect of the test, but this was _not_ happening in the 3.12.0a6 release, and as far as I can tell the relevant tests haven't changed since before a6. I'm delaying the 3.12.0a7 release until it's clear this isn't a fundamental problem with subinterpreters.

### Linked PRs
* gh-104186
* gh-104226
* gh-104345

**Comment by Yhg1s** [comment] 2023-04-04 15:15
The problem is actually reproducible all the way back to 3.12.0a4, even though it was never caught in the release testing (I don't know why, yet). The problem was exposed by #100142, but that merely adds testing of picklability of builtins, which all things considered is not an unreasonable test.

**Comment by Yhg1s** [comment] 2023-04-04 15:48
As it appears this is merely uncovering a long standing issue with a hole in subinterpreter isolation and importlib (the same test combination fails in 3.10 and 3.11), I'm unblocking a7 for now, but leaving this as a release blocker for beta 1.

**Comment by erlend-aasland** [comment] 2023-04-05 01:36
I did some bisecting in 3.10 and 3.11, and it landed like this:

- In 3.10, first bad commit: 37dbbb208fd9e01890bfb2c741e89359582d5569 (gh-99644)
- In 3.11, first bad commit: 9dda9020abcf0d51d59b283a89c58c8e1fb0f574 (gh-99643)

Strangely, I do not get the same result in `main`; the "parent" commit (cb2ef8b2acbb231c207207d3375b2f8b0077a6ee, gh-99642) that those backports were created from, reproduces the failure, as expected, but `cb2ef8b2acbb231c207207d3375b2f8b0077a6ee~` (1cae31d26ba621f6b1f0656ad3d69a0236338bad) is not a "good" commit; the failure also occurs there.
The first bad commit I get in `main` is:

- 1f369ad07ff44b1fd6db75b33298e20ad604efc8 (gh-98412)

The linked issues for those PRs contain some interesting history and debugging:

- gh-99578
- gh-98354

(It would be nice if someone else could bisect on their machine and verify my findings.)

**Comment by sunmy2019** [comment] 2023-04-05 18:37
> even though it was never caught in the release testing (I don't know why, yet).

Is it because the release testing in running in 4 processes?

**Comment by Yhg1s** [comment] 2023-04-05 20:38
No, the release testing is done sequentially, and that hasn't changed in 2 years: https://github.com/python/release-tools/blame/master/run_release.py#L486

**Comment by FFY00** [comment] 2023-04-06 13:43
Just some research for others also looking into it.

The failure comes from `test_builtin_types`, which is supposed to test pickling the builtins, but to do so it iterates over `builtins.__dict__.values()`, which includes all module attributes, including `__loader__`, which is what ultimately causes the failure here. IMO we should probably be using `dir(builtins)` instead.

https://github.com/python/cpython/blob/fd1947ecfba589feebd48c1ebb60d1c01ee0a89d/Lib/test/pickletester.py#L1985-L1990

I suspect the issue is simply that `test_importlib` leaks some of its monkeypatching, causing modules in other tests to be imported by a copy of the `importlib` module, hence the pickle identity check failure.

https://github.com/python/cpython/blob/52bc2e7b9d451821513a580a9b73c20cfdcf2b21/Lib/test/test_importlib/util.py#L52-L53

The deal with `test_imp` is that both `test_issue98354` and `test_create_builtin_subinterp` import the `builtins` module, causing it to be imported by a copy of the `importlib` module, as explained above. If you disable both of those tests, the failure is gone, but if you keep either, the pickle tests fail.

I think this is simply caused by leakage of the importlib tests, and has nothing to do with subinterpreters.

**Comment by sunmy2019** [comment] 2023-04-06 13:46
I am testing on with macos 13.3 clang 14
```
commit b98d2d31bffcaeb0c4c8848a8d1b35419c70b2da
Author: Serhiy Storchaka <storchaka@gmail.com>
Date:   Wed Dec 21 16:31:22 2022 +0200

    gh-100129: Add tests for pickling all builtin types and functions (GH-100142)

 Lib/test/pickletester.py | 29 +++++++++++++++++++++++++++++
 1 file changed, 29 insertions(+)
```

FWIW, I discovered that, test_importlib has many submodules.

You can invoke test as 
```
./python -m test test_imp {t} test_pickletools
```
with different `t`, such as `t = "test_importlib.builtin.test_finder"`

We got a map from `t` to returncode.

```py
{
    "test_importlib.builtin.test_finder": 2,
    "test_importlib.builtin.test_loader": 2,
    "test_importlib.extension.test_case_sensitivity": 2,
    "test_importlib.extension.test_finder": 2,
    "test_importlib.extension.test_loader": 2,
    "test_importlib.frozen.test_finder": 2,
    "test_importlib.frozen.test_loader": 2,
    "test_importlib.import_.test___loader__": 2,
    "test_importlib.import_.test___package__": 2,
    "test_importlib.import_.test_api": 2,
    "test_importlib.import_.test_caching": 2,
    "test_importlib.import_.test_fromlist": 2,
    "test_importlib.import_.test_helpers": 2,
    "test_importlib.import_.test_meta_path": 2,
    "test_importlib.import_.test_packages": 2,
    "test_importlib.import_.test_path": 2,
    "test_importlib.import_.test_relative_imports": 2,
    "test_importlib.resources.test_compatibilty_files": 0,
    "test_importlib.resources.test_contents": 0,
    "test_importlib.resources.test_files": 0,
    "test_importlib.resources.test_open": 0,
    "test_importlib.resources.test_path": 0,
    "test_importlib.resources.test_read": 0,
    "test_importlib.resources.test_reader": 0,
    "test_importlib.resources.test_resource": 0,
    "test_importlib.source.test_case_sensitivity": 2,
    "test_importlib.source.test_finder": 2,
    "test_importlib.source.test_source_encoding": 2,
    "test_importlib.test_abc": 2,
    "test_importlib.test_api": 2,
    "test_importlib.test_lazy": 2,
    "test_importlib.test_locks": 2,
    "test_importlib.test_main": 0,
    "test_importlib.test_metadata_api": 0,
    "test_importlib.test_namespace_pkgs": 2,
    "test_importlib.test_pkg_import": 0,
    "test_importlib.test_spec": 2,
    "test_importlib.test_threaded_import": 0,
    "test_importlib.test_util": 2,
    "test_importlib.test_zip": 0,
}

```

**Comment by sunmy2019** [comment] 2023-04-06 14:06
Looks like "those files that returned code 2" all include `Lib/test/test_importlib/util.py`?

Hope it is helpful.

**Comment by ericsnowcurrently** [comment] 2023-04-06 14:41
> IMO we should probably be using dir(builtins) instead.

FWIW, at the very least we should skip the module-specific dunder names (`__name__`, `__doc__`, `__spec__`, `__loader__`, `__package__`).

That said, we should also make sure there's a test somewhere that catches the reported failure (which we happened to get lucky catching in the pickle tests).

> I suspect the issue is simply that test_importlib leaks some of its monkeypatching,

+1 (but worth verifying)

> I think this is simply caused by leakage of the importlib tests, and has nothing to do with subinterpreters.

+1 (but worth verifying)

**Comment by JelleZijlstra** [comment] 2023-05-04 22:03
`test_imp` is no more, so the original reproduction steps no longer work. However, I see this failure on current main (no pickle tests necessary):
```
% ./python.exe -m test test_importlib test_import
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 1.91 Run tests sequentially
0:00:00 load avg: 1.91 [1/2] test_importlib
0:00:10 load avg: 2.29 [2/2] test_import
test test_import failed -- Traceback (most recent call last):
  File "/Users/jelle/py/cpython/Lib/test/test_import/__init__.py", line 1815, in test_multi_init_extension_compat
    require_extension(module)
  File "/Users/jelle/py/cpython/Lib/test/test_import/__init__.py", line 90, in require_extension
    _require_loader(module, ExtensionFileLoader, skip)
  File "/Users/jelle/py/cpython/Lib/test/test_import/__init__.py", line 76, in _require_loader
    actual = MODULE_KINDS[actual]
             ~~~~~~~~~~~~^^^^^^^^
KeyError: <class 'importlib._bootstrap_external.ExtensionFileLoader'>

test_import failed (1 error)

== Tests result: FAILURE ==

1 test OK.

1 test failed:
    test_import

Total duration: 13.5 sec
Tests result: FAILURE
```

**Comment by sunmy2019** [comment] 2023-05-05 08:58
> `test_imp` is no more, so the original reproduction steps no longer work. However, I see this failure on current main (no pickle tests necessary):

I looked into it. The failure (changing the env) comes from 
https://github.com/python/cpython/blob/e5b8b19d99861c73ab76ee0175a685acf6082d7e/Lib/test/test_importlib/extension/test_loader.py#L263-L273

Commenting on it solves this issue.

It seems not to follow the `with util.uncache(self.name)` idiom in adjacent tests. (I did not check the code logic, just did A/B test)

**Comment by FFY00** [comment] 2023-05-06 02:37
Good catch! Do you want to open a PR with the fix?

I think it'd make sense to add a teardown method which unloads `self.name` instead of relying on `util.uncache` to be used in all tests.

**Comment by sunmy2019** [comment] 2023-05-06 04:33
> Good catch! Do you want to open a PR with the fix?

#104226

**Closed as completed** 2023-05-12 22:00 UTC
Labels: type-bug, interpreter-core, release-blocker, topic-subinterpreters, topic-importlib
