### ISSUE TITLE
Add sort_list similar to sort_keys to JSONEncoder

### ISSUE THREAD

**Issue by migueltorrescosta** [python/cpython#99738] opened 2022-11-23 23:02 UTC
# Feature or enhancement

Add a `sort_list` boolean Flag to `json.dumps` similar to the `sort_keys` flag.
This would sort any lists in the `json`, similarly to how we sort dictionary keys when passing `sort_keys=True`

# Pitch

We are currently able to do

```python
>>> x = {"b": 1, "a": [3,1,2]}
>>> json.dumps(x)
'{"b": 1, "a": [3, 1, 2]}'
>>> json.dumps(x, sort_keys=True)
'{"a": [3, 1, 2], "b": 1}'
```

This is a brilliant feature, which allows us to ignore the original order of keys in a JSON. It would be equally useful to treat lists similarly:

```python
>>> x = {"b": 1, "a": [3,1,2]}
>>> json.dumps(x)
'{"b": 1, "a": [3, 1, 2]}'
>>> json.dumps(x, sort_list=True)
'{"b": 1, "a": [1, 2, 3]}'
>>> json.dumps(x, sort_keys=True, sort_list=True)
'{"a": [1, 2, 3], "b": 1}'
```

This would have no impact on existing code as the default behaviour is to pass `sort_list=False`. Unless there are reasons to not do this / work that needs to be done to design this feature before this merge, I would like to get started on the PR.

After a brief look at the code my current understanding is that we need to update the `encode` method of the `JSONEncoder` to make use of this flag, and ensure that it is passed properly in the same places that `sort_keys` is passed along.

# Previous discussion

No previous discussion found.

**Comment by ronaldoussoren** [comment] 2022-11-24 09:06
What is the use-case for the proposed new feature? 

Note that there is a fairly significant difference between ``sort_keys`` and the proposed ``sort_list`` argument: ``sort_keys`` doesn't change the value, that is reading back a JSON document created with ``sort_keys`` set to true gives the same value as reading back a document created with ``sort_keys`` set to false.  ``Sort_keys`` set to true just helps in creating cleaner, and reproducible, output.

**Comment by migueltorrescosta** [comment] 2022-11-24 22:12
Comparing JSONs where the various lists order are irrelevant. The use case where I feel this more often is HTTP / API testing ( maybe GraphQL ), where a list is returned with no commitments in terms of the list order returned. For this use case and similar ones where we need to ensure that an admittedly overly nested group of dicts and lists are the same, I end up manually writing out the structure of this nesting and sorting all founded lists based on some custom sorting key.

The particular order chosen for sorting the lists is somewhat irrelevant, as long as it is the same. This parameter `sort_lists=True` sounds like the best approach to ensure such behavior, and I'd be happy to take on this task. Would a different approach be better?

**Comment by 6t8k** [comment] 2022-11-25 00:19
To add, the keys in JSON dicts (objects in JSON parlance) are specified to be orderless, whereas elements within lists (arrays in JSON parlance) are specified to have an order. Like Ronald wrote, sorting them would actually change the output value as compared to the input. I'm not sure if it should be `json.dumps`' responsibility to do that (not that I'd have a say on this, I'm just a bystander who took the liberty of throwing in an opinion). For sorting I'd usually resort to the DB front, which may also result in better performance.

If elements' particular chosen order is not relevant in the output (and needn't be compared based on order, but may be based on contents, similar to sets), one could consider outputting them as dicts with simple counters as keys. Using these you could also transport optional/alternative order information if need be.

**Comment by migueltorrescosta** [comment] 2022-11-25 00:46
> Like Ronald wrote, sorting them would actually change the output value as compared to the input.

True, but is fine since by default it is `False`: A user would have to actively have to decide to activate the flag `sort_lists=True` 

> If elements' particular chosen order is not relevant in the output (and needn't be compared based on order, but may be based on contents, similar to sets), one could consider outputting them as dicts with simple counters as keys. Using these you could also transport optional/alternative order information if need be.

@6t8k Love the idea. How does the particular point about using counters as keys work though? I'm thinking that `["a", "a", "b", "c"]` would become `{2:"a", 1:"b", "c":1}`, but now we have duplicated keys. We could do `{2:["a"], 1:["b", "c"]}`, but this too would require sorting the lists for the comparison to work.

> For sorting I'd usually resort to the DB front, which may also result in better performance.

The core problem I am solving when this specific solution was suggested is 

### Problem Z: How to AssertEqual 2 JSONs when I don't care about list orders inside of it.

If I am doing integration tests with a non-mocked external API ( to check whether one of my 3rd party dependencies is providing the expected data ), I have no control over the specs of their API, namely ordering the list at the DB level. This is just the first example that comes to mind of where solving `Problem Z` is useful: Many others exist

**Comment by 6t8k** [comment] 2022-11-25 01:17
> True, but is fine since by default it is `False`: A user would have to actively have to decide to activate the flag `sort_lists=True`

Sure. I just doubted whether it'd be good to overload `json.dumps` with that functionality.

> @6t8k Love the idea. How does the particular point about using counters as keys work though? I'm thinking that `["a", "a", "b", "c"]` would become `{2:"a", 1:"b", "c":1}`, but now we have duplicated keys. We could do `{2:["a"], 1:["b", "c"]}`, but this too would require sorting the lists for the comparison to work.

I was thinking of e.g. `["a", "a", "b", "c"]` -> `{"0": "a", "1": "a", "2": "b", "3": "c"}` (JSON object keys must be strings).  The values would not be deduplicated automatically (you didn't write that you also need this), but if you do, you could use Python's `set` data type and write a short custom JSON en/decoder between it and the above, if you cannot deduplicate in the DB.

**Comment by pochmann** [comment] 2022-11-25 02:33
> The core problem I am solving when this specific solution was suggested is
> 
> ### Problem Z: How to AssertEqual 2 JSONs when I don't care about list orders inside of it.

How would the `sort_lists` flag help with that? I'd say the proper solution for that would be to `json.load` the two JSONs so you have Python data structures, and then (recursively) compare those.

**Comment by ronaldoussoren** [comment] 2022-11-25 09:33
> > The core problem I am solving when this specific solution was suggested is
> > ### Problem Z: How to AssertEqual 2 JSONs when I don't care about list orders inside of it.
> 
> How would the `sort_lists` flag help with that? I'd say the proper solution for that would be to `json.load` the two JSONs so you have Python data structures, and then (recursively) compare those.

I agree, converting two data structures to an encoded JSON document to compare them feels wrong.  Recursively walking a Python data structure for comparison isn't too hard, and in this particular case you could even write a function that normalises a datastructure, e.g. something like this (completely untested) function:

```python3

def normalize_data(data):
     if isinstance(data, dict):
         for v in data.values():
             normalize_data(v)
     elif isinstance(data, list):
             data.sort()
```

**Comment by migueltorrescosta** [comment] 2022-11-25 16:52
> sounds like you could just convert the lists to sets on both sides and compare your reference Python object with the API side (which you are converting to Python objects via e.g. json.loads, I assume) directly (with regards to `dicts`, also note that while they preserve insertion order since CPython 3.6/Python 3.7, that order is immaterial for equality comparisons - order comparisons don't work)

The conversion from `list` to `set` has been complaining that the content of the list is usually un-hashable. I take this would be a problem for sorting as well, though?

> How would the `sort_lists` flag help with that? I'd say the proper solution for that would be to json.load the two JSONs so you have Python data structures, and then (recursively) compare those.

This does sound appealing. I couldn't find any flags in the json docs for any of the methods `loads` / `equality` / `scanner` / `decode` methods that would take care of this, would this be useful to add?

@ronaldoussoren Agree that the recursive normalization works. I mentioned adding it to stdlib because comparing structures after doing `json.loads` felt like a common enough use-case that it could be a good small task for me to add to `python`. Happy to not do it if this assumption was wrong. I have a small sample based on what is actually common or not, I just assume it based on what I face and what I see popping up on StackOverflow / pyslackers.com .

Would it make sense to allow dict comparison to take a parameter? ( i.e. `dict_a == dict_b` runs `dict_a.equals(dict_b)`, but I could directly call `dict_a.equals(dict_b, ignore_list_order=True)`


_PS: I'll go for @ronaldoussoren suggestion as it is my best approach in the short term. I believe this functionality would be useful generally but if you believe otherwise I am happy to close this now: There's enough work needed to be done elsewhere that I wouldn't want to take your time unnecessarily. Thank you for entertaining this Idea!_

**Comment by 6t8k** [comment] 2022-11-25 17:52
> The conversion from list to set has been complaining that the content of the list is usually un-hashable.

Oh, right -- if you have sublists or subdicts in the lists in question, then those can't be part of sets as all set elements need to be hashable data types. The approach you now opted for should be adequate then.

**Comment by pochmann** [comment] 2022-11-25 18:03
> Would it make sense to allow dict comparison to take a parameter? ( i.e. `dict_a == dict_b` runs `dict_a.equals(dict_b)`, but I could directly call `dict_a.equals(dict_b, ignore_list_order=True)`

That seems even far worse. Why should dictionaries know about lists? You're trying to squeeze functionality into something where it doesn't belong. Same with JSON - its job is to offer data interchange, not sorting/comparing data. About `sort_keys`, its documentation [says](https://docs.python.org/3/library/json.html#json.JSONEncoder):

> this is useful for regression tests to ensure that JSON serializations can be compared on a day-to-day basis.

Lists never had that issue. Python dicts now somewhat also don't have it anymore, since they're now somewhat ordered as well. But not as fundamentally ordered as lists. And I said "Python dicts" to distinguish them from JSON. In [JSON](https://www.json.org/), they (called "objects"there) are explicitly unordered:

> An object is an unordered set of name/value pairs.

> An array is an ordered collection of values.

**Comment by pochmann** [comment] 2022-11-25 18:46
Also, a global `sort_list` flag seems too simplistic even for your use case. Consider this data of five people naming their favorite and second-favorite TV show character:
```
[
  ["Sam", "Diane"],
  ["Sam", "Woody"],
  ["Woody", "Sam"],
  ["Sam", "Carla"],
  ["Norm", "Cliff"],
]
```
Here I'd consider the outer array unordered but the inner arrays ordered. It doesn't matter whether `["Sam", "Woody"]` comes before or after `["Woody", "Sam"]`, but they're *not* equal.

With (JSON) objects, that's not a problem: they're unordered, so `json` is free to order any and all of them in any way - it remains the same data. But with arrays, re-ordering them *changes* the data. That's not for `json` to do. That's for your code to do. Especially if you want unordered at some levels and ordered at others, as in my above example.

**Comment by ronaldoussoren** [comment] 2022-11-25 19:06
I'm closing this issue. 

There is no strong argument for adding this to the json library. Feel free to continue discussion about this idea on the ideas category of discuss.python.org.  That might lead to a better solution for the problem you're trying to solve.

**Closed as not planned by ronaldoussoren** 2022-11-25 19:06 UTC
Labels: type-feature, stdlib, pending
