### ISSUE TITLE
`StopIteration` in a generator in a thread hanging on asyncio

### ISSUE THREAD

**Issue by NewUserHa** [python/cpython#112182] opened 2023-11-16 22:48 UTC
# Bug report

### Bug description:

```python
import asyncio

def a():
    raise StopIteration

try:
    await asyncio.to_thread(a)
except:
    print(3.12.0)

```

other cases: https://github.com/agronholm/anyio/pull/477

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-113220
* gh-123033

**Comment by terryjreedy** [comment] 2023-11-17 02:24
Please post working code.
 `print(3.12.0)` is a SyntaxError.
 With that fixed, 'await' outside an async function is also a syntax error.
 With that fixed I still get an error.
```python
import asyncio

def a():
    raise StopIteration

async def f():
    try:
        await ayncio.to_thread(a)
    except:
        print('done')

f()
```
results in `RuntimeWarning: coroutine 'f' was never awaited`.
(Afaik, without `yield`, `a` is not a generator function.)

**Comment by NewUserHa** [comment] 2023-11-17 12:04
That is the working code in notebook, except the `3.12.0` was trying to match the version number of the used python.
Using `StopIteration` instead of yield is for simplifying the code, and also report that this exception can also cause the issue.

Anyway, here are the working codes without notebook:
* you will see it never exits.
```py
import asyncio


def a():
    raise StopIteration


async def main():
    try:
        await asyncio.to_thread(a)
    except:
        print(3.12)

asyncio.run(main())
```
* the yeild one
```py
import asyncio


def a():
    for _ in [1, 2]:
        yield _


async def main():
    gen = a()
    while True:
        try:
            await asyncio.to_thread(next, gen)
        except:
            print(3.12)
            break

asyncio.run(main())
```

Also, in the related link, it has more example cases

**Comment by terryjreedy** [comment] 2023-11-17 14:49
I just noticed that my code had a spelling error masked by the overly broad except.
With the spelling and the call to f (or main), the following (in IDLE with Win 10)
```python
Exception in callback _chain_future.<locals>._set_state(<Future pendi...ask_wakeup()]>, <Future at 0x...StopIteration>) at C:\Programs\Python313\Lib\asyncio\futures.py:381
handle: <Handle _chain_future.<locals>._set_state(<Future pendi...ask_wakeup()]>, <Future at 0x...StopIteration>) at C:\Programs\Python313\Lib\asyncio\futures.py:381>
Traceback (most recent call last):
  File "C:\Programs\Python313\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Programs\Python313\Lib\asyncio\futures.py", line 383, in _set_state
    _copy_future_state(other, future)
  File "C:\Programs\Python313\Lib\asyncio\futures.py", line 359, in _copy_future_state
    dest.set_exception(_convert_future_exc(exception))
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```
and does indeed 'hang' (no >>> prompt appears).  Hit ^C and
```
Traceback (most recent call last):
  File "C:\Programs\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Programs\Python313\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
  File "F:\dev\tem\tem2.py", line 8, in main
    await asyncio.to_thread(a)
  File "C:\Programs\Python313\Lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\dev\tem\tem2.py", line 12, in <module>
    asyncio.run(main())
  File "C:\Programs\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Programs\Python313\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
```
and a prompt appears.  I don't know enough about asyncio to say more, but I add the label to ping people who do.

**Comment by gvanrossum** [comment] 2023-11-17 17:03
My first response is "don't do that". That's why it prints such an elaborate warning.

Looking into the machinery involved, maybe there could be a `try`/`except` around the `else` block in `_copy_future_state()` (in asyncio/futures.py) that if the whole thing fails just calls `dest.cancel()`. That way the caller at least won't hang.

**Comment by gvanrossum** [comment] 2023-11-17 17:05
The failure should also be logged. Perhaps you can find the loop where to log it via `dest._loop`. Make sure that a failure to log doesn't crash.

**Comment by NewUserHa** [comment] 2023-11-17 19:48
So the PR should look like:
```py
from .log import logger
def _copy_future_state(source, dest):
    """Internal helper to copy state from another Future.

    The other Future may be a concurrent.futures.Future.
    """
    assert source.done()
    if dest.cancelled():
        return
    assert not dest.done()
    if source.cancelled():
        dest.cancel()
    else:
        try:
            exception = source.exception()
            if exception is not None:
                dest.set_exception(_convert_future_exc(exception))
            else:
                result = source.result()
                dest.set_result(result)
        except:
            dest.cancel()
            # dest._loop.
            logger.error('Exception in default exception handler',
                        exc_info=True)
```
?

it seems that it's `dest.set_exception(_convert_future_exc(exception))` raised error, and which is at 
```py
    def set_exception(self, exception):
        """Mark the future done and set an exception.

        If the future is already done when this method is called, raises
        InvalidStateError.
        """
        if self._state != _PENDING:
            raise exceptions.InvalidStateError(f'{self._state}: {self!r}')
        if isinstance(exception, type):
            exception = exception()
        if type(exception) is StopIteration:
            raise TypeError("StopIteration interacts badly with generators "
                            "and cannot be raised into a Future")
        self._exception = exception
        self._exception_tb = exception.__traceback__
        self._state = _FINISHED
        self.__schedule_callbacks()
        self.__log_traceback = True
```
why would `set_exception()` raise the error because of 'stopiteration' in python?

and what about changing the exception to `runtimeerror` like how the anyio does in its issue at the above first comment

**Comment by gvanrossum** [comment] 2023-11-17 23:03
This surprised me too. Maybe the guy history of those lines has a clue.

**Comment by NewUserHa** [comment] 2023-11-17 23:19
It seems that this line exists after 3.5.2rc1 (not in 3..5.1), 
and its commit is https://github.com/python/cpython/commit/1bd030788d1092ba5d5d8b4e2fd75346ded69b3b and it referred to an invalid issue

**Comment by gvanrossum** [comment] 2023-11-18 00:43
That is a bpo issue: https://bugs.python.org/issue26221

**Comment by NewUserHa** [comment] 2023-11-18 01:17
> [msg260584](https://bugs.python.org/issue26221#msg260584) - [(view)](https://bugs.python.org/msg260584)	Author: Guido van Rossum (gvanrossum) * (Python committer)	Date: 2016-02-21 00:20
OK, since eventually there won't be a way to inject StopIteration into
a Future anyway (it'll always raise RuntimeError once [PEP 479](https://www.python.org/dev/peps/pep-0479/) is the
default behavior) we should just reject this in set_exception().

it said "PEP 479 – Change StopIteration handling inside generators"

But what to do to handle the current issue?
since the async is not based on generator anymore, and the current asyncio doesn't obey "This PEP proposes a change to generators: when StopIteration is raised inside a generator, it is replaced with RuntimeError." from PEP 479 neither.

**Comment by gvanrossum** [comment] 2023-11-18 02:08
Unfortunately, the implementation of `async def` and `await` is internally very much still based on generators -- they use the same machinery (notably `yield from`, there's just a bit on the code object that is used to avoid mixing them up.

Please trust me that `StopIteration` is special (PEP 479 is just the tip of the iceberg) and the real bug here is that, after reporting that you can't set a future's exception to `StopIteration` the future should probably be cancelled. Possibly this could be added just before the `raise TypeError(...)` in `set_exception()`. (But note it also needs to be added to the C accelerator module `_asynciomodule.c`).

**Comment by NewUserHa** [comment] 2023-11-18 19:11
What about replacing `StopIteration` with `RuntimeError` as the first paragraph of PEP 479 said

**Comment by gvanrossum** [comment] 2023-11-18 20:24
That’s a good idea. Can you try a PR?

**Comment by NewUserHa** [comment] 2023-11-19 00:39
I tried to replace `StopIteration` in `_copy_future_state()` and it works fine.

However the `set_exception()` in `futures.py` is actually a stub, while the real code is at: https://github.com/python/cpython/blob/1a969b4f55f92a17bec82ce0366021a53afdb2c3/Modules/_asynciomodule.c#L600-L606
Therefore, should remove the `_asynciomodule.c` file and the stub method, or if it's ok just simply remove the test code at: ?https://github.com/python/cpython/blob/1a969b4f55f92a17bec82ce0366021a53afdb2c3/Lib/test/test_asyncio/test_futures.py#L273-L276

**Comment by gvanrossum** [comment] 2023-11-19 01:35
Yeah, you have to make the same change to both futures.py and _asynciomodule.c. These two should always correspond in semantics.

I guess that if we are changing the semantics so that calling `f.set_exception(StopIteration(...))` actually sets the exception to be `RuntimeError`, the test has to be adjusted.

I'd like to ping PEP 479 author @Rosuav to see if he thinks this is a good idea. (Chris, I believe you claim you don't understand or use asyncio -- but it should be straightforward for you to weigh in on the question here -- when some code calls `f.set_exception(StopIteration())` on an asyncio future `f`, is it better to silently transform this into a `RuntimeError()` (so that whoever waits for the future's result sees that), rather than the current approach where the `set_exception()` call itself fails? The problem with the current approach is that if this happens in another task, that task dies (after logging a message), and the task waiting for the future will never wake up. Tasks dying after logging a message happens all the time in large apps, but tasks hanging are really annoying (apparently).

**Comment by Rosuav** [comment] 2023-11-19 01:56
> I'd like to ping PEP 479 author @Rosuav to see if he thinks this is a good idea. (Chris, I believe you claim you don't understand or use asyncio -- but it should be straightforward for you to weigh in on the question here

That was true back when PEP 479 was written, but since then, I have made much more use of asyncio, so I'm in a somewhat better position to discuss this. (I still wouldn't consider myself an *expert* on it, but I've definitely used it.)

Is `to_thread` significant to this, or is it simply a case of a coro raising StopIteration?

I believe that this would be a good idea, and would be consistent with other transformations of StopIteration. Generators and async functions are both situations where StopIteration is not obviously a significant part of the API (in contrast to `__next__` methods), so if raising it causes problems, transforming it into RuntimeError is IMO the correct solution.

> is it better to silently transform this into a `RuntimeError()` (so that whoever waits for the future's result sees that), rather than the current approach where the `set_exception()` call itself fails?

Yep. That definitely sounds like the better option. The docs for set_exception say:

https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.set_exception

that it will raise if the future's already done, which is correct, but it doesn't say that it'll choke on a specific type of error. It definitely seems more fitting for, regardless of the specific exception type, the Future's state to be set to "has an exception", but with StopIteration being transformed into RuntimeError (can we set the original StopIteration as the cause?).

**Comment by gvanrossum** [comment] 2023-11-19 02:28
That's great feedback. I think `to_thread()` is not important -- that's just where the OP ran into the problem. (And alas, their problem won't be fixed by this, but I think it's just not fixable given how async functions use `StopIteration`.)

**Comment by gvanrossum** [comment] 2023-11-19 02:58
FYI, I experimented with simply taking the checks for `StopIteration` out of the code. When using the pure Python version, this produces, surprise, surprise, a `RuntimeError` from the PEP 479 infrastructure. When using the C accelerator, this produces, even more surprising, a valid return value equal to the argument to `StopIteration`. In both cases, the exception stored in the future is the `StopIteration` instance passed to `set_exception()` -- but the attempt to re-raise it in the awaiting task fails, in different ways.

So I think we can't fix this by arranging for the `StopIteration` to pass through. Instead, we have to replace it with `RuntimeError`.

The simplest approach is probably what we were contemplating here: instead of raising `TypeError`, replace the exception with a `RuntimeError` (whose `__cause__` is set to the original `StopIteration` instance).

Another approach would be to do the replacement on the receiving end: this would move the check for `StopIteration` to the `result()` method (raising `RuntimeError` there). That way a caller in the know could reconstruct the original `StopIteration` using `fut.exception()`.

(Note that the original code, both in C and in Python, somehow doesn't intercept exceptions whose type is a *subclass* of `StopIteration`. Not sure if that was meant as a backdoor or not important enough to slow down the check (`type(x) is StopIteration` is way faster than `isinstance(x, StopIteration)`.

**Comment by NewUserHa** [comment] 2023-11-19 19:50
> FYI, I experimented with simply taking the checks for StopIteration out of the code. When using the pure Python version, this produces, surprise, surprise, a RuntimeError from the PEP 479 infrastructure. When using the C accelerator, this produces, even more surprising, a valid return value equal to the argument to StopIteration.

In `futures.py`, no code to replace `StopIteration` with `RuntimeError` exists, where does it produce a `RuntimeError`?

> The simplest approach is probably what we were contemplating here: instead of raising TypeError, replace the exception with a RuntimeError (whose __cause__ is set to the original StopIteration instance).

So replacing `StopIteration` with `RuntimeError` in both .py and .c is the way to fix? What does the msg should be? Does `PyErr_SetString()` need to set __cause__?

> Another approach would be to do the replacement on the receiving end: this would move the check for StopIteration to the result() method (raising RuntimeError there). That way a caller in the know could reconstruct the original StopIteration using fut.exception().

Is this approach to set the dest done in `_copy_future_state()` and had a `RuntimeError` exception?

**Comment by gvanrossum** [comment] 2023-11-19 23:45
> In `futures.py`, no code to replace `StopIteration` with `RuntimeError` exists, where does it produce a `RuntimeError`?

That's the power of PEP 479. When a generator or `async` function raises `StopIteration` and the exception is about to bubble out of there, it is replaced by `RuntimeError`. The C code that does this lives [here in intrinsics.c](https://github.com/python/cpython/blob/ce1096f974d3158a92e050f9226700775b8db398/Python/intrinsics.c#L145). (In older Python versions it was in genobject.c, but it's basically the same code.)

> So replacing `StopIteration` with `RuntimeError` in both .py and .c is the way to fix? What does the msg should be? Does PyErr_SetString() need to set `__cause__`?

If we're replacing it in `set_exception()` I'd use the message that's used there currently for the `TypeError`. If we're doing it on the receiving end (in `result()`) I'd use the message from intrinsics.c above.

> Is this approach to set the dest done in `_copy_future_state()` and had a `RuntimeError` exception?

I think you don't have to do anything in that function, regardless whether you replace it at the sending or the receiving end.

I think for the C code you can probably crib the code from intrinsics.c. For the Python code it's just `err = RuntimeError(message); err.__cause__ = original_exception`.

**Comment by ordinary-jamie** [comment] 2023-12-16 23:24
Hi! Saw that this issue seemed a stale so thought I take a jab at it for my own learning, hope that's OK.

@NewUserHa let me know if you have something already in progress and I can close this PR.

**Comment by NewUserHa** [comment] 2023-12-17 00:17
@ordinary-jamie You should ask before you open your PR.

**Comment by ordinary-jamie** [comment] 2023-12-17 02:06
Ah sorry @NewUserHa; did you want me to close my PR then?

**Closed as completed** 2024-01-10 05:21 UTC
Labels: type-bug, topic-asyncio, 3.12, 3.13
