### ISSUE TITLE
Anomalous behaviour with nan values in min/max functions

### ISSUE THREAD

**Issue by yukta-grofers** [python/cpython#120205] opened 2024-06-07 09:32 UTC
# Bug report

### Bug description:

```python
import numpy as np
print(min([3, np.nan]))
print(min[np.nan, 3])
```
Ideally both of these print values should be same, but in the first case, 3 is returned from the min function while in the other case, nan is returned. Why should that happen? 

### CPython versions tested on:

3.9

### Operating systems tested on:

macOS

**Comment by Eclips4** [comment] 2024-06-07 09:51
Hello, thanks for the report!
First of all, your issue is reproduces without ``numpy`` (which is actually a 3rd-party package):
```python
>>> min([1, float('nan')])
1
>>> min([float('nan'), 1])
nan
>>> 
```
Secondly, it's a duplicate of #88536.

**Closed as not planned by Eclips4** 2024-06-07 09:51 UTC
Labels: type-bug
