### ISSUE TITLE
Pickle `INT`/`LONG` base discrepancy

### ISSUE THREAD

**Issue by Legoclones** [python/cpython#126992] opened 2024-11-19 01:46 UTC
# Bug report

### Bug description:

The `INT` opcode in pickle is the `I` character followed by an ASCII number and a newline. There are multiple comments asking if the base should be explicitly set to 10, or kept as 0. However, a discrepancy exists between pickle implementations:
* [`_pickle.c`](https://github.com/python/cpython/blob/main/Modules/_pickle.c#L5216) uses `strtol(s, &endptr, 0);` with a base of 0, meaning `0xf` would succeed
* [`pickle.py`](https://github.com/python/cpython/blob/main/Lib/pickle.py#L1390) uses `int(data, 0)` with a base of 0, meaning `0xf` would succeed
* [`pickletools.py`](https://github.com/python/cpython/blob/main/Lib/pickletools.py#L750) uses `read_decimalnl_short()`, which calls `int(s)`, meaning any non-decimal base would fail

This same inconsistency exists with the `LONG` opcode:
* [`_pickle.c`](https://github.com/python/cpython/blob/main/Modules/_pickle.c#L5374)
* [`pickle.py`](https://github.com/python/cpython/blob/main/Lib/pickle.py#L1410)
* [`pickletools.py`](https://github.com/Legoclones/cpython/blob/main/Lib/pickletools.py#L786)

This means an attempt to disassemble a pickle bytestream using `pickletools` would fail here, while the actual unpickling process would proceed undisputed.

Personally, I don't really care whether all implementations are changed to base 10 or base 0 (`save_long()` only puts it in decimal form), but I think it should be consistent across all implementations. I'd submit a pull request for one way or the other, but I'm not sure which way you'd prefer it. 

Also as a note, the pickle bytestream `b'I0001\n.'` (`INT` with the argument `0001`) fails in `pickle.py` because having leading 0s in a number with base 0 causes an error. Note that no errors are thrown in `_pickle.c` because it uses `strtol` or `pickletools.py` because it doesn't have base 0 specified. If we keep the implementation as base 0, that discrepancy between `pickle.py` and other pickle implementations would stay, whereas if we change it to base 10 (aka remove base 0), that inconsistency would also go away. For `LONG`, both `pickle.py` and `_pickle.c` fail with `b'L0001L\n.'`, but `pickletools.py` has no problem displaying that number (since it has no base specified).

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-127042

**Comment by vstinner** [comment] 2024-11-19 11:09
I think that using base 10 would be reasonable here.

**Comment by skirpichev** [comment] 2024-11-20 03:36
> I think that using base 10 would be reasonable here.

I think it's an incompatible change.  Why not adjust pickletools instead?

BTW, I see no failing tests in #127042.  Probably we should add some regression tests.

**Comment by Legoclones** [comment] 2024-11-20 03:48
No pickles produced by `pickle.dumps()` would use any base other than 10, so only custom-made pickles would be broken by this change (which is also why it wouldn't break any tests).

**Comment by skirpichev** [comment] 2024-11-20 05:34
Yes, this compatibility break doesn't look too severe.  After all, I'm not sure that many projects use the version 0 protocol.

On another hand, it's *really easy* to not introduce backward-incompatible changes.

**Comment by vstinner** [comment] 2024-11-20 08:35
> I think it's an incompatible change.

Yes, and IMO it's a good change.

In practice, no one should be impacted since everybody should use the Python module to serialize to pickle, and in this case, you cannot get a base different than 10 in the serialized files.

**Comment by serhiy-storchaka** [comment] 2024-11-25 10:21
@tim-one, this may be interesting to you, as it relates to both `pickletools` and the problems with decimal representation of long integers.

Using hexadecimal representation for long integers would be more efficient in terms of time and size. But it is less efficient than using pickle protocol 1 or higher. And not all third-party implementations (for different programming languages) support hexadecimals.

**Comment by serhiy-storchaka** [comment] 2024-12-05 11:31
It is more complicated for other prefixes. `strtol()` parses numbers starting with 0 as octals, but it is an error for `int()`.

```pycon
>>> import pickle, pickletools, io
>>> pickletools.dis(b'I010\n.')
    0: I    INT        10
    5: .    STOP
highest protocol among opcodes = 0
>>> pickle.Unpickler(io.BytesIO(b'I010\n.')).load()
8
>>> pickle._Unpickler(io.BytesIO(b'I010\n.')).load()
Traceback (most recent call last):
  File "<python-input-19>", line 1, in <module>
    pickle._Unpickler(io.BytesIO(b'I010\n.')).load()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/serhiy/py/cpython/Lib/pickle.py", line 1327, in load
    dispatch[key[0]](self)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "/home/serhiy/py/cpython/Lib/pickle.py", line 1390, in load_int
    val = int(data, 0)
ValueError: invalid literal for int() with base 0: b'010\n'
```

@tim-one, will we support non-decimal bases for pickle protocol 0 in future? If no, we should close this door in pickle. If yes, we should fix support of octals in pickle and make pickletools consisting with pickle.

**Comment by vstinner** [comment] 2024-12-05 11:47
> @tim-one, will we support non-decimal bases for pickle protocol 0 in future?

I don't think that protocol 0 should change. It uses base 10 and this property has to stay. Otherwise, we introduce a backward incompatibility, no? Like loading new serialized data with old Python may no longer work.

**Comment by serhiy-storchaka** [comment] 2024-12-05 12:03
> Like loading new serialized data with old Python may no longer work.

It works with all old CPython versions (except if there were releases in short period from 12 April to 15 May in 1996). It may not work with implementations of pickle format in other programming languages.

**Comment by tim-one** [comment] 2024-12-05 19:14
> @tim-one, will we support non-decimal bases for pickle protocol 0 in future?

The only reason we have still have "protocol 0" _at all_ is "backward compatibility". That's the original protocol, and, at the start, the only protocol. The only sane use for it now would be if someone needs to write a pickle readable by an ancient version of Python. The ancient version can no longer be changed in any way, so there is no sane reason to add "new features" to protocol 0 now. So, "no" is my answer to the question.

A semi-sane reason to use protocol 0 _was_ to get a human-readable text file for learning something about how pickles work, but that purpose is far better served now by `pickletools.dis()`, which gives a human-readable display of pickles using all protocols.

**Comment by vstinner** [comment] 2024-12-11 12:39
Fixed by change https://github.com/python/cpython/commit/ce76b547f94de6b1c9c74657b4e8f150365ad76f. Thanks @Legoclones.

**Closed as completed by vstinner** 2024-12-11 12:39 UTC
Labels: type-bug, stdlib, extension-modules
