### ISSUE TITLE
installation denied based on system policy

### ISSUE THREAD

**Issue by ZfiXxtyN** [python/cpython#106806] opened 2023-07-16 10:10 UTC
# installation denied based on system policy.

Tell us what happened, ideally including a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example).

When installing python 3.10, I got an error installation denied based on system policy. The error logs showed 0x80070659: failed to install msi package. error 0x80070659: failed to configure per-user msi package. python

Enter any relevant error message caused by the crash, including a core dump if there is one.

# Your environment

- CPython versions tested on: 3.10
-Windows 10 pro 22H2

**Comment by ronaldoussoren** [comment] 2023-07-16 10:35
This is likely a duplicate of https://github.com/python/cpython/issues/87293.

**Comment by terryjreedy** [comment] 2023-07-16 14:52
@ZfiXxtyN As far as our installer is concerned, this is a repeat issue.  Windows rejected the install with the same Windows error number.  You could repeat the web search done on the previous issue and see if there is any new information, or try the current Windows store python.  As before, this is not a Python issue.  Sorry.

**Closed as not planned** 2023-07-16 19:21 UTC
Labels: OS-windows, topic-installation, pending

**Comment by ZfiXxtyN** [comment] 2023-07-21 00:03
I was able to fix this using the system policy section

**Comment by ZfiXxtyN** [comment] 2023-07-21 00:04
> @ZfiXxtyN As far as our installer is concerned, this is a repeat issue. Windows rejected the install with the same Windows error number. You could repeat the web search done on the previous issue and see if there is any new information, or try the current Windows store python. As before, this is not a Python issue. Sorry.

I was able to fix this using the system policy section

**Comment by San27052** [comment] 2024-07-23 06:34
> > @ZfiXxtyN Что касается нашего установщика, это повторяющаяся проблема. Windows отклонила установку с тем же номером ошибки Windows. Вы могли бы повторить поиск в Интернете, выполненный в предыдущем выпуске, и посмотреть, есть ли какая-либо новая информация, или попробовать текущий python из магазина Windows. Как и прежде, это не проблема с Python. Извините.
> 
> Я смог исправить это, используя раздел системной политики
I have the same problem, tell me how you solved it
