### ISSUE TITLE
Endless recursion in repr of asyncio.Future if a callback uses the Future itself as argument

### ISSUE THREAD

**Issue by usiems** [python/cpython#93837] opened 2022-06-15 09:28 UTC
**Bug report**

I encountered an endless recursion when doing a repr of a asyncio.Future where a callback, which references the Future itself through functools.partial, is added. This crashes when doing this in a Debug version of Python, but somehow recovers on the Release version.

Try this to reproduce:

```
import asyncio
import functools

def test():
  fut = asyncio.Future()
  def done_cb(arg):
    pass
  fut.add_done_callback(functools.partial(done_cb, fut))

  print(repr(fut))

test()
```

The output in the Release version is
> <Future pending cb=[test.<locals>.done_cb(<Future pendi...ion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>

where you can see at least part of the recursion.

An incomplete fix for the recursion problem has already been done for [bpo-42183](https://bugs.python.org/issue?@action=redirect&bpo=42183), but this didn't cover the callbacks.

**Your environment**

- CPython versions tested on: Python 3.9.12, 3.9.11 (self-compiled)
- Operating system and architecture: Windows, Intel

**Propose patch**

I have a patch that fixes the problem for me by including all of the Future's state in the recursion guard:

```
diff --git i/Lib/asyncio/base_futures.py w/Lib/asyncio/base_futures.py
index 2c01ac9..ee60e93 100644
--- i/Lib/asyncio/base_futures.py
+++ w/Lib/asyncio/base_futures.py
@@ -55,26 +55,24 @@ _repr_running = set()
 def _future_repr_info(future):
     # (Future) -> str
     """helper function for Future.__repr__"""
-    info = [future._state.lower()]
-    if future._state == _FINISHED:
-        if future._exception is not None:
-            info.append(f'exception={future._exception!r}')
-        else:
-            key = id(future), get_ident()
-            if key in _repr_running:
-                result = '...'
-            else:
-                _repr_running.add(key)
-                try:
-                    # use reprlib to limit the length of the output, especially
-                    # for very long strings
-                    result = reprlib.repr(future._result)
-                finally:
-                    _repr_running.discard(key)
-            info.append(f'result={result}')
-    if future._callbacks:
-        info.append(_format_callbacks(future._callbacks))
-    if future._source_traceback:
-        frame = future._source_traceback[-1]
-        info.append(f'created at {frame[0]}:{frame[1]}')
-    return info
+
+    key = id(future), get_ident()
+    if key in _repr_running:
+        return ['... [recursion]']
+    else:
+        _repr_running.add(key)
+        try:
+            info = [future._state.lower()]
+            if future._state == _FINISHED:
+                # use reprlib to limit the length of the output, especially
+                # for very long strings
+                result = reprlib.repr(future._result)
+                info.append(f'result={result}')
+            if future._callbacks:
+                info.append(_format_callbacks(future._callbacks))
+            if future._source_traceback:
+                frame = future._source_traceback[-1]
+                info.append(f'created at {frame[0]}:{frame[1]}')
+            return info
+        finally:
+            _repr_running.discard(key)
```

**Comment by kumaraditya303** [comment] 2022-06-15 11:09
Can you specify what should be the intended behavior?  From the title it seems that you are getting a recursion error which isn't the case.

**Comment by usiems** [comment] 2022-06-15 12:37
This is just a thing we stumbled over in [MeVisLab](https://www.mevislab.de/) 3.5, where we currently use Python 3.9.11. I believe the recursion error is caught internally by reprlib, but it crashes in the Debug mode of MeVisLab, possibly because the stack segment isn't big enough then.

Anyway, I believe this should be caught early. I had a look at the code and it doesn't seem this is caught other than by running into the recursion limit, which seems to be risky.

You can make the recursion visible by setting self.maxother = 10000 in reprlib.py, then you get

`<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future pending cb=[test.<locals>.done_cb(<Future instance at 0x1f405c14cc0>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>)() at C:\Users\usiems\Documents\MeVisLab\future_repr_recursion_bug.py:6]>`

The `<Future instance at 0x1f405c14cc0>` in the middle is where Repr.repr_instance catches the recursion error. The string is normally shortened afterwards.

I also checked with Python 3.10.5, the behavior hasn't changed.

**Comment by usiems** [comment] 2022-06-15 12:44
I was also able to provoke a crash by adding
`sys.setrecursionlimit(3000)`
to the test

**Comment by kumaraditya303** [comment] 2022-07-12 09:26
I am unable to reproduce the crash with this:
```py
import sys
sys.setrecursionlimit(3000)
import asyncio
import functools

def test():
  fut = asyncio.Future()
  def done_cb(arg):
    pass
  fut.add_done_callback(functools.partial(done_cb, fut))

  print(repr(fut))

test()
```

It would be better if you can provide a complete script to reproduce it.

**Comment by usiems** [comment] 2022-07-13 16:30
Hi!
This is a modified full script:
```
import asyncio
import functools
import sys

sys.setrecursionlimit(3000)

def test():
  fut = asyncio.Future()
  def done_cb(arg):
    pass
  fut.add_done_callback(functools.partial(done_cb, fut))

  print(repr(fut))

try:
  test()
except:
  print("Done")
```
I noticed that if I run this on Windows from a GIT bash, it isn't apparent that the script crashed, one is just missing some output after the DeprecationWarning (obviously you should at least see "Done"). If you run this from a CMD shell, you get a crash dialog.
(Tested with Python 3.10.5 on Windows, installer downloaded from www.python.org).

**Comment by usiems** [comment] 2022-08-05 12:24
I just want to repeat my point, that an (potential) endless recursion in this method should be avoided.

The recursion isn't visible because the RecursionError is caught in the code and I proposed to increase the recursion limit to prove that there indeed is a problem, even if it normally isn't visible.

At minimum this is a potential performance issue (because a lot of code is executed pointlessly to produce a string which is dropped for the most part)

**Comment by asvetlov** [comment] 2024-11-12 11:41
I think it is fixed by https://github.com/python/cpython/issues/91195 for Python 3.11+

**Closed as completed by asvetlov** 2024-11-12 11:41 UTC
Labels: type-bug, topic-asyncio, stdlib

**Comment by freakboy3742** [comment] 2024-11-13 03:29
@asvetlov Was the added `OS-ios` tag intentional? I can't see an obvious connection to iOS here...

**Comment by asvetlov** [comment] 2024-11-13 04:17
@freakboy3742 sorry, `OS-ios` tag was added by an accident.
