### ISSUE TITLE
asyncio.Semaphore waiters deque doesn't work

### ISSUE THREAD

**Issue by a6a4079d-283a-40a6-851f-b800ae8d5f31** [python/cpython#90155] opened 2021-12-06 14:04 UTC
BPO | [45997](https://bugs.python.org/issue45997)
--- | :---
Nosy | @asvetlov, @1st1, @miss-islington, @hyzyla
PRs | <li>python/cpython#30052</li><li>python/cpython#31910</li><li>python/cpython#32047</li><li>python/cpython#32049</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/asvetlov'
closed_at = None
created_at = <Date 2021-12-06.14:04:23.913>
labels = ['3.11', 'expert-asyncio']
title = "asyncio.Semaphore waiters deque doesn't work"
updated_at = <Date 2022-03-22.15:16:39.410>
user = 'https://github.com/hyzyla'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-22.15:16:39.410>
actor = 'asvetlov'
assignee = 'asvetlov'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-12-06.14:04:23.913>
creator = 'hyzyla'
dependencies = []
files = []
hgrepos = []
issue_num = 45997
keywords = ['patch']
message_count = 9.0
messages = ['407809', '407836', '407841', '407843', '415276', '415286', '415772', '415786', '415787']
nosy_count = 5.0
nosy_names = ['asvetlov', 'python-dev', 'yselivanov', 'miss-islington', 'hyzyla']
pr_nums = ['30052', '31910', '32047', '32049']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45997'
versions = ['Python 3.11']
```

</p></details>

**Comment by cykerway** [comment] 2022-05-25 10:08
Maybe not the end of story.

This shows how to create a broken semaphore (on commit 19710145b496b5e5341630d80be9c400aa792bd1):

```python
from asyncio import CancelledError
from asyncio import Semaphore
from asyncio import create_task
from asyncio import gather
from asyncio import run
from asyncio import sleep

async def process(idx, sem, tasks):
    await sleep(idx)
    async with sem:
        await sleep(2)
    tasks[1].cancel()

async def main():
    print('let me run for 3 seconds')
    sem = Semaphore(1)
    tasks = []
    for idx in range(2):
        tasks.append(create_task(process(idx, sem, tasks)))
    await sleep(3)
    await gather(*tasks, return_exceptions=True)

    print(f'sem._value == {sem._value}')
    print('sem is still...', end='', flush=True)
    async with sem:
        print('working!')

run(main())
```

Expected output:

```
let me run for 3 seconds
sem._value == 1
sem is still...working!
```

Actual output:

```
let me run for 3 seconds
sem._value == 1
sem is still...
```

**Comment by danpascu** [comment] 2022-06-09 23:38
I was going through the changes trying to understand how all this works in various cases and I noticed that the locked method was not adjusted.

It currently reads:

    def locked(self):
        """Returns True if semaphore can not be acquired immediately."""
        return self._value == 0

but after the latest changes that added the ```_wakeup_scheduled``` flag should't it actually read:

    def locked(self):
        """Returns True if semaphore can not be acquired immediately."""
        return self._wakeup_scheduled or self._value == 0

?

Since the comment indicates that this method returns ```True``` if the semaphore cannot be acquired immediately and considering that the condition in the acquire method that prevents an immediate acquiring of the semaphore is:

        while self._wakeup_scheduled or self._value <= 0: ...

it leads me to think that locked method needs to be adjusted to have the same condition.

Someone with a better understanding of how this is supposed to work, please weigh in.

**Comment by alittlesir** [comment] 2022-09-11 05:45
any question about this issue? if not, i think it is better to close it

**Comment by alittlesir** [comment] 2022-09-11 05:51
@asvetlov what about you think?

**Comment by gvanrossum** [comment] 2022-09-11 14:30
He is not active ATM. We need someone to review the issue and PR mentioned in or after the comment by @cykerway

**Comment by gvanrossum** [comment] 2022-09-11 21:13
Definitely should not be closed, the same issue exists for Lock (see https://github.com/python/cpython/issues/90155#issuecomment-1093939560), and also for Queue (see https://github.com/python/cpython/issues/90155#issuecomment-1093939562). Plus there's the issue brought up by @cykerway (see https://github.com/python/cpython/issues/90155#issuecomment-1137052110), which I don't understand yet.

**Comment by cykerway** [comment] 2022-09-15 08:29
The issue is semaphores are *currently broken* in 3.10.7 and other versions. A timeline is given in the PR link.

To understand the issue, just look at the `gather` in it. When `gather` returns, all tasks are done. All tasks interact with semaphore using `async with` which guarantees its release. So the semaphore has value 1 right after `gather` returns. But the last `async with` is not able to acquire this semaphore. This suggets its internal state is corrupted.

**Comment by gvanrossum** [comment] 2022-09-15 22:10
When people state "X is broken" it gets my hackles up a bit. Can you explain in words what's broken? How badly is it broken? When does user code experience it?

I see the code you [showed](https://github.com/python/cpython/issues/90155#issuecomment-1137052110) but I need an explanation.

**Comment by cykerway** [comment] 2022-09-16 12:23
> Can you explain in words what's broken?

The semaphore is broken. It gets corrupted and no longer usable.

> How badly is it broken?

The broken semaphore blocks a task when the task should be allowed to proceed. In this sense it is completely unusable. How bad is the result depends on what the task is doing. The symptom could be no terminal output, network connection timeout, or other bad things you can expect when a task cannot proceed.

> When does user code experience it?

What I found was when a task cancels another task at certain time. This is a race condition so I can't give exact description of the condition that triggers the problem. Someone has documented his own experience [here](https://github.com/mguentner/async_semaphore_race_condition_poc).

----

And to add a bit explanation about the code itself, this is the story in plain words: Player Zero and One share a hotel room whose door is locked and there is only one key. They arrive at the door at about the same time. Zero sleeps 0 seconds then grabs the key (at time 0). He goes into the room and sleeps for another 2 seconds. During his sleep One wakes up from his first sleep (at time 1). One tries to grab the key but he can't, because there is only one key currently held by Zero. So One waits outside on the lock. Zero wakes up (at time 2). He gets out of the room, returns the key, then murders One at the door. Now One has died and he has never got the key. A moment later Police Main comes to the door (at time 3) to investigate. He is the only one here, and there is a key, but he just cannot open the door with the key. Why? Because the lock is damaged. Now Main waits forever on the damaged lock. 

Cast:

- Player Zero: Task `process(0, ...)`
- Player One: Task `process(1, ...)`
- Police Main: Task `main()`
- Lock: `Semaphore(1)`

**Comment by gvanrossum** [comment] 2022-09-16 14:56
Presumably the problem is that some code gets interrupted by the cancellation and exits without restoring an invariant. Not surprising given the complexity of the code. But cancellation only happens in await (there is no pre-emption in asyncio) so it should not be hard to find, right?

**Comment by cykerway** [comment] 2022-09-16 15:39
https://github.com/python/cpython/commit/9d59381a5d20157930bae34e5f5a7bc5ef09fa89#diff-0fee1befb15023abc0dad2623effa93a304946796929f6cb445d11a57821e737R368

Roughly speaking it's `_wakeup_scheduled` set to `True` when Zero releases the lock, then the cancelled One simply exits without touching it. So when Main comes it sees `_wakeup_scheduled == True` and sleeps forever. But this alone doesn't suggest an easy fix to the existing code. The code in PR has gone some trial and error. I don't know if it's optimal but it doesn't seem to suffer either problem (OP's and mine) or introduce new regressions. You are right that these tasks are non-preemptive.

**Comment by gvanrossum** [comment] 2022-09-17 15:29
I'm beginning to wonder of the root of the problem isn't that the Semaphore implementation decided to remove the completed Future in release() instead of in acquire(). If we compare to Lock, it removes the future in acquire():
```py
        try:
            try:
                await fut
            finally:
                self._waiters.remove(fut)
        except exceptions.CancelledError:
            if not self._locked:
                self._wake_up_first()
            raise
```
In its `_wake_up_first()` it just makes the first future in the queue done. Also, at the top of acquire(), it has a thorough check to see if it can immediately grab the lock:
```py
        if (not self._locked and (self._waiters is None or
                all(w.cancelled() for w in self._waiters))):
            self._locked = True
            return True
```
IOW it only grabs it when nobody else is waiting.

Adapting this approach for Semaphore would probably improve the code -- no more `_wakeup_scheduled` counter, no more 'first' flag.

@kumaraditya303 What do you think? And @cykerway?

Looking at things from this perspective, I think the Lock class is fair and does not break the lock when acquire() is cancelled.

I'm less sure about Queue -- like Semaphore, it removes the waiter from the queue of waiters when waking up, but it has much more thorough handling of cancellation (using in `except:` / ... / `raise`). Its docs don't make a promise of fairness when multiple tasks are each blocked in `get()` (or in `put()`, for that matter -- it's completely symmetrical). So in the end I think we don't have to worry about it.

**Comment by cykerway** [comment] 2022-09-17 20:31
That's a great observation. I didn't really pay attention to `Lock` before. A `Lock` can be implemented with `Semaphore(1)`. So if we have a good `Semaphore` then we have a good `Lock`. The other direction is not true: A good `Lock` doesn't automatically give a good `Semaphore`. But in this case, I copied `Lock` to `Semaphore` and tried to patch it. I found the patch didn't seem a lot of work.

The result has been pushed to https://github.com/python/cpython/pull/93222. It can almost pass all the tests, except that I have to change some `asyncio.sleep(0)` into `asyncio.sleep(0.01)`. This irks me. I have had this issue several times before. Could anyone here please explain what is the exact difference between using `0` and `0.01` in `asyncio.sleep()`? And why it matters in tests? I think this implies timing is playing a role in determining test results which doesn't look good to me.

**Comment by gvanrossum** [comment] 2022-09-17 21:52
> The result has been pushed to #93222. It can almost pass all the tests, except that I have to change some `asyncio.sleep(0)` into `asyncio.sleep(0.01)`. This irks me. I have had this issue several times before. Could anyone here please explain what is the exact difference between using `0` and `0.01` in `asyncio.sleep()`? And why it matters in tests? I think this implies timing is playing a role in determining test results which doesn't look good to me. I understand that `sleep(0)` gives control to the event loop. But is there a guarantee that Python asyncio strictly follows the asymmetric stackless coroutine model, with the event loop sitting at the root of all coroutines?

I hadn't seen this before I reviewed your new version; I'll look at those tests and see if I can understand why sleep(0.01) is now needed. It definitely irks me too. I think the idea is that `sleep(0)` allows everything that's runnable _now_ to run, whereas `sleep(tiny_amount)` will effectively also run things that become runnable as a result of the first wave. I'm not sure what _asymmetric stackless coroutine model_ refers to -- is that a textbook concept or something named in the Python docs or just a term you invented on the spot?

**Comment by cykerway** [comment] 2022-09-17 22:08
Hope you can post something here once you completely figure out sleep(0) vs sleep(0.01).

The coroutine model is a categorization of coroutines across two dimensions: asymmetric/symmetric and stackful/stackless. Asymmetric means the callee coroutine always passes control to its caller on yield. Symmetric means the callee coroutine passes control to anyone it likes. Stackful means coroutine preserves its entire stack on yield (like fiber). Stackless means coroutine is implemented as a state machine. It seems Python generators, async functions, etc. fall into the asymmetric+stackless category. I believe knowing this helps understand how coroutines are scheduled in Python, which in turn helps answer the sleep(0) vs sleep(0.01) question.

**Comment by gvanrossum** [comment] 2022-09-18 00:27
I think I've figured out why some tests appeared to need `sleep(0.01)`. The wakeup code was still broken if there were multiple waiters: if the first waiter is already awoken, it should just wake up the second one. This is a subtle difference with Lock, where it is an error to release more than once.

Thanks for the clarification of your coroutine classification scheme -- I'm so used to Python's particular brand of coroutines that I forget the other quadrants of the design space. :-) And yes, once the event loop passes control to a particular coroutine, that coroutine runs without intervention until it next yields -- `await` is implemented using `yield from` (PEP 380) which passes control up and down a stack of coroutines (not sure if that makes it stackful).

**Comment by kumaraditya303** [comment] 2022-09-20 11:45
Okay so I finally got time to look into this:

Currently, the semaphore does not provide FIFO ordering. The was supposed to be fixed by https://github.com/python/cpython/pull/31910 but it didn't. The correct fix for semaphore should have the following semantics:

- Immediately acquire the semaphore if it is not locked and there are no waiters. `not self.locked() and not self._waiters` 
- If there are waiters, it must switch task to allow waking up the task instead of returning and not cause starvation on the next iteration of loop.

Here's my simplified implementation which maintains the FIFO ordering:
```py
import asyncio
import collections


class Semaphore:
    def __init__(self, value: int) -> None:
        self.value = value
        self.waiters = collections.deque()

    async def __aenter__(self):
        await self.acquire()

    async def __aexit__(self, exc_type, exc, tb):
        self.release()

    def locked(self) -> bool:
        return self.value == 0

    async def acquire(self) -> None:
        if not self.locked() and not self.waiters:
            # No need to wait as the semaphore is not locked
            # and no one is waiting
            self.value -= 1
            return

        # if there are waiters or the semaphore is locked
        fut = asyncio.Future()
        self.waiters.append(fut)
        try:
            await fut
        finally:
            self.waiters.remove(fut)

        self.value -= 1
        if not self.locked():
            # The next loop iteration will wake up the waiter
            self._wakeup_next()
        return

    def _wakeup_next(self) -> None:
        if self.waiters:
            # Wake up the first waiter
            # It is removed by the waiting task
            waiter = self.waiters[0]
            if not waiter.done():
                # This schedules the task to be woken up on next loop iteration 
                # It requires exactly one iteration of loop
                # per callback
                waiter.set_result(None)


    def release(self) -> None:
        self.value += 1
        self._wakeup_next()


async def process(idx: int, semaphore: Semaphore) -> None:
    while True:
        async with semaphore:
            print(f'ACQUIRE {idx}')
            await asyncio.sleep(1)


async def main() -> None:
    semaphore = Semaphore(5)
    await asyncio.gather(*[process(idx, semaphore) for idx in range(20)])

asyncio.run(main())

```

**Comment by cykerway** [comment] 2022-09-20 16:08
You didn't handle cancelled tasks. This program would hang.

~~~python
sem = Semaphore(1)
async def c1(): await sem.acquire()
async def c2(): await sem.acquire()
async def c3(): await sem.acquire()
t1 = create_task(c1())
t2 = create_task(c2())
t3 = create_task(c3())
await sleep(0)
sem.release()
sem.release()
t2.cancel()
await gather(t1, t2, t3, return_exceptions=True)
~~~

**Comment by kumaraditya303** [comment] 2022-09-20 16:34
Right, but I did say "simplified implementation" and I avoided cancellation handling to make understanding of waking of task easier which is the main point of confusion.

**Comment by gvanrossum** [comment] 2022-09-21 23:37
But the cancellation is what makes it so challenging. :-(

For example, the acquiring task can go through the following states (not counting the "trivial success" at the top):

- Blocked
- Cancelled, but task not yet running
- Result set, but task not yet running
- Result set, then task cancelled, but not yet running

That last state is surprising -- after the future's result is set the future cannot be cancelled, but the task can -- and CancelledError will be thrown into the task in that case. (You can only get there by calling sem.release() and task.cancel() without sleeping in between.)

I have been trying to come up with a different version that passes all tests, but so far without success. If nothing else, this would give me more confidence that the tests are correct.

**Closed as completed** 2022-09-22 18:19 UTC
Labels: topic-asyncio, 3.11, 3.10, 3.12

**Comment by gvanrossum** [comment] 2022-10-05 06:40
I blogged a bit about this: https://neopythonic.blogspot.com/2022/10/reasoning-about-asynciosemaphore.html
