### ISSUE TITLE
max(a,b) sometimes depends on order of args

### ISSUE THREAD

**Issue by alex77g2** [python/cpython#117200] opened 2024-03-24 19:03 UTC
# Bug report

### Bug description:

```python
# Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] on win32
>>> max(3.5, float('nan'))
3.5
>>> max(float('nan'), 3.5)
nan
>>> f = float('nan')
>>> f == f
False # NAN per definition does equal itself, so this is the test for nan without functions. Same for other compares.
```
As this is not obvious behaviour (and python wants to be easy to understand), I suggest to mention this here:
https://docs.python.org/3/library/functions.html#max
I'm not sure about considering this a bug, but is is on the edge between bug and confusing behaviour.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux, Windows

**Comment by Eclips4** [comment] 2024-03-24 19:17
> NAN per definition does equal itself, so this is the test for nan without functions. Same for other compares.

[IEEE-754](https://en.wikipedia.org/wiki/IEEE_754#Comparison_predicates) says the opposite:
> Any comparison with a NaN is treated as unordered

**Comment by hugovk** [comment] 2024-03-24 19:19
Looks like a duplicate of https://github.com/python/cpython/issues/88536.

> If `math.nan` is the first argument for either max() or min(), the result is always `nan`, regardless of the other values in the results. However, if `nan` is in any other position in the arguments list, the result is always what you would expect if `nan` was not in the arguments list.
> ...

**Comment by alex77g2** [comment] 2024-03-24 19:20
yes, but this is not obvious to each python user. and python is intended to be as friendly or comfortable or easy to understand as possible. No hint in documentation?

**Closed as not planned by hugovk** 2024-03-24 19:19 UTC
Labels: type-bug

**Comment by Eclips4** [comment] 2024-03-24 19:21
> yes, but this is not obvious to each python user. and python is intended to be as friendly or comfortable or easy to understand as possible. No hint in documentation?

There's already a hint in documentation: https://docs.python.org/3/library/math.html#math.nan

**Comment by alex77g2** [comment] 2024-03-24 19:23
I mean a hint in max(), min() docu. As not everybody ready everything. I assume many users dont even know about NAN.

**Comment by Eclips4** [comment] 2024-03-24 19:36
> I mean a hint in max(), min() docu. As not everybody ready everything. I assume many users dont even know about NAN.

This behaviour currently is under discussion, please read the [issue](#88536) found by Hugo.
