### ISSUE TITLE
Heap Segmentation Fault

### ISSUE THREAD

**Issue by 46004174-1dad-4fc4-87fd-b8a2ad055f84** [python/cpython#89983] opened 2021-11-17 01:55 UTC
BPO | [45825](https://bugs.python.org/issue45825)
--- | :---
Nosy | @zware, @thewb
Files | <li>[debug.txt](https://bugs.python.org/file50444/debug.txt "Uploaded as text/plain at 2021-11-17.01:55:44 by @thewb")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-17.01:55:46.340>
labels = ['ctypes', 'invalid', '3.9', 'type-crash']
title = 'Heap Segmentation Fault'
updated_at = <Date 2021-11-17.15:11:42.596>
user = 'https://github.com/thewb'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-17.15:11:42.596>
actor = 'thewb'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2021-11-17.01:55:46.340>
creator = 'thewb'
dependencies = []
files = ['50444']
hgrepos = []
issue_num = 45825
keywords = []
message_count = 3.0
messages = ['406443', '406470', '406472']
nosy_count = 2.0
nosy_names = ['zach.ware', 'thewb']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue45825'
versions = ['Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment] 2022-04-18 19:15
Closed as it was not a bug.

**Closed as completed** 2022-04-18 19:14 UTC
Labels: topic-ctypes, 3.9 (EOL), type-crash
