### ISSUE TITLE
test_mmap: test_access_parameter() failed on ARM64 macOS 3.x with macOS 14 Sonoma

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109916] opened 2023-09-26 19:12 UTC
ARM64 macOS 3.x:

```
ERROR: test_access_parameter (test.test_mmap.MmapTests.test_access_parameter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.x.pablogsal-macos-m1.macos-with-brew/build/Lib/test/test_mmap.py", line 258, in test_access_parameter
    m = mmap.mmap(f.fileno(), mapsize, prot=prot)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted
```

build: https://buildbot.python.org/all/#/builders/725/builds/5749

**Comment by ned-deily** [comment] 2023-09-26 21:04
Duplicate of #107888

**Closed as completed** 2023-09-26 21:04 UTC
Labels: tests

**Comment by smontanaro** [comment] 2023-09-27 18:24
I see this was applied to main and the 3.11 branch, but not the 3.12 branch. Is that just a matter of a tight bottleneck in the run-up to the 3.12 release? I think it would be a shame to exclude this fix to a test case.

**Comment by ned-deily** [comment] 2023-09-28 04:18
> I see this was applied to main and the 3.11 branch, but not the 3.12 branch. Is that just a matter of a tight bottleneck in the run-up to the 3.12 release? I think it would be a shame to exclude this fix to a test case.

@Yhg1s
