### ISSUE TITLE
Performance regression 3.10b1: inlining issue in the big _PyEval_EvalFrameDefault() function with Visual Studio (MSC)

### ISSUE THREAD

**Issue by 23c8a93b-de57-46a3-b68d-6c6a493f0c9f** [python/cpython#89279] opened 2021-09-06 15:27 UTC
BPO | [45116](https://bugs.python.org/issue45116)
--- | :---
Nosy | @malemburg, @gvanrossum, @rhettinger, @pfmoore, @vstinner, @tjguk, @markshannon, @zware, @zooba, @animalize, @pablogsal, @brandtbucher, @neonene, @erlend-aasland, @Fidget-Spinner
PRs | <li>python/cpython#28390</li><li>python/cpython#28419</li><li>python/cpython#28427</li><li>python/cpython#28475</li><li>python/cpython#28630</li><li>python/cpython#28631</li><li>python/cpython#31436</li><li>python/cpython#31459</li><li>python/cpython#32387</li>
Files | <li>[310rc1_confirm_overhead.patch](https://bugs.python.org/file50263/310rc1_confirm_overhead.patch "Uploaded as text/plain at 2021-09-06.15:27:17 by @neonene")</li><li>[ceval_310rc1_patched.c](https://bugs.python.org/file50264/ceval_310rc1_patched.c "Uploaded as text/plain at 2021-09-06.15:29:00 by @neonene")</li><li>[b98e-no-inline-in-all.diff](https://bugs.python.org/file50271/b98e-no-inline-in-all.diff "Uploaded as text/plain at 2021-09-11.02:15:35 by @neonene")</li><li>[b98e-no-inline-in-eval.diff](https://bugs.python.org/file50272/b98e-no-inline-in-eval.diff "Uploaded as text/plain at 2021-09-11.02:15:51 by @neonene")</li><li>[b98e-no-inline-in-the-others.diff](https://bugs.python.org/file50273/b98e-no-inline-in-the-others.diff "Uploaded as text/plain at 2021-09-11.02:16:06 by @neonene")</li><li>[pyproject_inlinestat.patch](https://bugs.python.org/file50274/pyproject_inlinestat.patch "Uploaded as text/plain at 2021-09-11.02:17:00 by @neonene")</li><li>[x64_28d2.log](https://bugs.python.org/file50275/x64_28d2.log "Uploaded as text/plain at 2021-09-11.02:17:39 by @neonene")</li><li>[x64_b98e.log](https://bugs.python.org/file50276/x64_b98e.log "Uploaded as text/plain at 2021-09-11.02:17:56 by @neonene")</li><li>[310rc2_benchmarks.txt](https://bugs.python.org/file50280/310rc2_benchmarks.txt "Uploaded as text/plain at 2021-09-13.23:37:47 by @neonene")</li><li>[310a7_vs_310rc2_bench.txt](https://bugs.python.org/file50286/310a7_vs_310rc2_bench.txt "Uploaded as text/plain at 2021-09-18.16:26:54 by @Fidget-Spinner")</li><li>[PR28475_inline.log](https://bugs.python.org/file50291/PR28475_inline.log "Uploaded as text/plain at 2021-09-21.06:01:53 by @neonene")</li><li>[PR28475_vs_310rc2_vs_310a7.txt](https://bugs.python.org/file50293/PR28475_vs_310rc2_vs_310a7.txt "Uploaded as text/plain at 2021-09-21.09:10:53 by @Fidget-Spinner")</li><li>[PR28475_skip1test_bench.txt](https://bugs.python.org/file50296/PR28475_skip1test_bench.txt "Uploaded as text/plain at 2021-09-23.07:35:56 by @neonene")</li><li>[310rc2patched_vs_310rc2notrace.txt](https://bugs.python.org/file50315/310rc2patched_vs_310rc2notrace.txt "Uploaded as text/plain at 2021-09-29.14:25:54 by @Fidget-Spinner")</li><li>[switch-case_unarranged_bench.txt](https://bugs.python.org/file50363/switch-case_unarranged_bench.txt "Uploaded as text/plain at 2021-10-16.15:26:05 by @neonene")</li><li>[ceval_PR29565_split_func.c](https://bugs.python.org/file50452/ceval_PR29565_split_func.c "Uploaded as text/plain at 2021-11-19.18:54:48 by @neonene")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-06.15:27:18.216>
labels = ['interpreter-core', '3.10', 'performance', 'expert-C-API', '3.11', 'OS-windows']
title = 'Performance regression 3.10b1: inlining issue in the big _PyEval_EvalFrameDefault() function with Visual Studio (MSC)'
updated_at = <Date 2022-04-08.11:04:12.476>
user = 'https://github.com/neonene'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.11:04:12.476>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'Windows', 'C API']
creation = <Date 2021-09-06.15:27:18.216>
creator = 'neonene'
dependencies = []
files = ['50263', '50264', '50271', '50272', '50273', '50274', '50275', '50276', '50280', '50286', '50291', '50293', '50296', '50315', '50363', '50452']
hgrepos = []
issue_num = 45116
keywords = ['patch']
message_count = 82.0
messages = ['401143', '401152', '401154', '401182', '401183', '401319', '401329', '401346', '401364', '401623', '401624', '401628', '401743', '401964', '401970', '401972', '402025', '402040', '402043', '402044', '402063', '402064', '402065', '402067', '402068', '402071', '402090', '402091', '402092', '402098', '402099', '402117', '402135', '402143', '402189', '402190', '402217', '402229', '402230', '402287', '402289', '402296', '402307', '402308', '402320', '402480', '402856', '402857', '402858', '402864', '402867', '402871', '402878', '402886', '402891', '402893', '402928', '402930', '402954', '403403', '403409', '403430', '403432', '403464', '403559', '403587', '403609', '404089', '406354', '406386', '406407', '406416', '406471', '406474', '406479', '406487', '406613', '407188', '415378', '416911', '416950', '416977']
nosy_count = 15.0
nosy_names = ['lemburg', 'gvanrossum', 'rhettinger', 'paul.moore', 'vstinner', 'tim.golden', 'Mark.Shannon', 'zach.ware', 'steve.dower', 'malin', 'pablogsal', 'brandtbucher', 'neonene', 'erlendaasland', 'kj']
pr_nums = ['28390', '28419', '28427', '28475', '28630', '28631', '31436', '31459', '32387']
priority = None
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue45116'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by neonene** [comment] 2022-04-10 23:59
>have you done other experiments confirming this?

My benchmark results are left in https://github.com/faster-cpython/ideas/issues/321#issuecomment-1094129130.

__assume(0) is problematic only where the substitute function is inlined.

**Comment by gvanrossum** [comment] 2022-04-11 19:26
For Py_UNREACHABLE() then maybe we should just remove these two lines from, pymacro.h?
```
#elif defined(_MSC_VER)
#  define Py_UNREACHABLE() __assume(0)
```
Then the code will fall back to
```
#else
#  define Py_UNREACHABLE() \
    Py_FatalError("Unreachable C code path reached")
#endif
```

**Comment by gvanrossum** [comment] 2022-04-12 01:31
> __assume(0) is problematic only where the substitute function is inlined.

Can you elaborate? What is the "substitute function"? The macro definition is
```
#  define Py_UNREACHABLE() __assume(0)
```
so there is no inlined function. Are you referring to the code *containing* the call to `Py_UNREACHABLE()`? That wouldn't affect the ceval.c main loop in `_PyEval_EvalFrameDefault ` because that function is definitely to large to be inlined. :-)

What am I missing?

**Comment by neonene** [comment] 2022-04-13 00:13
Sorry for the lack of explanation.

I encountered a measurable slowdown several months ago when `Py_RETURN_RICHCOMPARE` macro is inlined in the eval-loop.
However, that may be x86 only.

If I understand correctly, x86 official binaries are non-PGO builds. Then, a `Py_FatalError()` only for `TARGET(CACHE)` branch would be enough for now.

<br>

When I change the current version as below:

  1. Substitute `void Py_UNREACHABLE(void) {}` or `Py_FatalError()` for `__assume(0)` in pymacro.h

  2. Make `PyObject_RichCompare()` called through a function pointer, adding
this above `_PyEval_EvalFrameDefault()`.
```
static const richcmpfunc PyObject_RichCompare_PTR = PyObject_RichCompare;
#define PyObject_RichCompare PyObject_RichCompare_PTR
```

Then, PGO decides to inline `PyObject_RichCompare()`, based on its profile.
This seems to affect "Function Layout optimization" even if it is not inlined. (under verification)
```
    PyObject_RichCompare (pgu decision)
      _PyThreadState_GET (pgu decision)
        _PyRuntimeState_GetThreadState (pgu decision)
      _PyErr_Occurred (pgu decision)
      -_PyErr_BadInternalCall (pgo hard reject)
      _Py_EnterRecursiveCall (pgu decision)
        _Py_MakeRecCheck (pgu decision)
        -_Py_CheckRecursiveCall (pgo hard reject)
      do_richcompare (pgu decision)
        PyType_IsSubtype (pgu decision)
          -type_is_subtype_base_chain (pgo hard reject)
        Py_DECREF (pgu decision)
          _Py_Dealloc (pgu decision)
        long_richcompare (pgu decision)
          ...
>>>>>     Py_UNREACHABLE (pgu decision)  // or _Py_FatalErrorFunc (pgo hard reject)
```

As for other place (`_Py_FatalErrorFunc()` never gets inlined anywhere):
```
    dict_get (pgu decision)
      -_PyArg_CheckPositional (pgo hard reject)
      dict_get_impl (pgu decision)
        unicode_get_hash (pgu decision)
        PyObject_Hash (pgu decision)
          _Py_HashPointer (pgu decision)
            _Py_HashPointerRaw (pgu decision)
          -PyType_Ready (pgo hard reject)
          -PyObject_HashNotImplemented (pgo hard reject)
        _Py_dict_lookup (pgu decision)
          -unicodekeys_lookup_unicode (pgo hard reject)
          -unicodekeys_lookup_generic (pgo hard reject)
          dictkeys_generic_lookup (pgu decision)
            dictkeys_get_index (pgu decision)
            Py_INCREF (pgu decision)
            -PyObject_RichCompareBool (pgo hard reject)
            Py_DECREF (pgu decision)
              _Py_Dealloc (pgu decision)
>>>>>       -Py_UNREACHABLE (pgo hard reject)  // (no harm)
```
```
    Py_DECREF (force inline)
      -_Py_Dealloc (initial scan: soft depth exceeded)
    -_Py_Specialize_BinaryOp (pgo hard reject)
>>>  Py_UNREACHABLE (pgu decision)            // @TARGET(CACHE) inlined
    _PyFrame_SetStackPointer (pgu decision)
    -trace_function_entry (pgo hard reject)
    _PyFrame_GetStackPointer (pgu decision)
    PyDTrace_FUNCTION_ENTRY_ENABLED (pgu decision)
    -dtrace_function_entry (pgo hard reject)
    PyDTrace_LINE_ENABLED (pgu decision)
    -maybe_dtrace_line (pgo hard reject)
    _PyFrame_SetStackPointer (pgu decision)
    -maybe_call_line_trace (pgo hard reject)
    _PyFrame_GetStackPointer (pgu decision)
    -_PyInterpreterFrame_GetLine (pgo hard reject)
    -fprintf (initial scan: parameter mismatch, varargs, not eligible)
    -_PyErr_SetString (pgo hard reject)
>>> -Py_UNREACHABLE (pgo hard reject)         // out of switch (no harm)
```

Benchmark after removal of `TARGET(CACHE)` branch:

|Py_UNREACHABLE at<br>long_richcompare()|x64 PGO|x86 PGO|
|:---:|:---:|:---:|
|__assume(0)|1.00|1.00|
|Py_FatalError|1.02x **_slower_**|1.03x faster|
|void foo(void) {}|1.02x **_slower_**|1.04x faster|

`__assume(0)` works well in the hot section on x64.
<details>

```
>pyperf compare_to  assume64  fatalerr64

Slower (25):
- dulwich_log: 195 ms +- 3 ms -> 231 ms +- 50 ms: 1.19x slower
- xml_etree_process: 98.3 ms +- 1.7 ms -> 109 ms +- 1 ms: 1.11x slower
- pickle_pure_python: 540 us +- 7 us -> 592 us +- 41 us: 1.10x slower
- logging_silent: 163 ns +- 1 ns -> 177 ns +- 3 ns: 1.09x slower
- xml_etree_generate: 138 ms +- 4 ms -> 148 ms +- 3 ms: 1.07x slower
- unpickle_pure_python: 348 us +- 9 us -> 371 us +- 5 us: 1.07x slower
- meteor_contest: 152 ms +- 1 ms -> 162 ms +- 2 ms: 1.06x slower
- hexiom: 10.8 ms +- 0.1 ms -> 11.4 ms +- 0.2 ms: 1.06x slower
- deltablue: 6.78 ms +- 0.23 ms -> 7.14 ms +- 0.09 ms: 1.05x slower
- scimark_fft: 491 ms +- 13 ms -> 517 ms +- 12 ms: 1.05x slower
- fannkuch: 627 ms +- 14 ms -> 660 ms +- 20 ms: 1.05x slower
- crypto_pyaes: 127 ms +- 3 ms -> 134 ms +- 4 ms: 1.05x slower
- sqlalchemy_imperative: 44.8 ms +- 2.3 ms -> 47.1 ms +- 5.3 ms: 1.05x slower
- nqueens: 164 ms +- 1 ms -> 172 ms +- 3 ms: 1.05x slower
- float: 138 ms +- 2 ms -> 144 ms +- 3 ms: 1.05x slower
- logging_format: 20.4 us +- 0.4 us -> 21.3 us +- 0.9 us: 1.04x slower
- nbody: 179 ms +- 6 ms -> 185 ms +- 7 ms: 1.04x slower
- django_template: 85.4 ms +- 1.1 ms -> 88.6 ms +- 2.3 ms: 1.04x slower
- go: 240 ms +- 4 ms -> 249 ms +- 7 ms: 1.03x slower
- regex_compile: 231 ms +- 2 ms -> 238 ms +- 3 ms: 1.03x slower
- json_dumps: 21.1 ms +- 0.2 ms -> 21.6 ms +- 0.2 ms: 1.02x slower
- logging_simple: 18.9 us +- 0.3 us -> 19.3 us +- 0.4 us: 1.02x slower
- sqlalchemy_declarative: 277 ms +- 8 ms -> 283 ms +- 8 ms: 1.02x slower
- scimark_monte_carlo: 104 ms +- 2 ms -> 106 ms +- 2 ms: 1.02x slower
- pathlib: 183 ms +- 12 ms -> 187 ms +- 7 ms: 1.02x slower

Faster (6):
- pickle_dict: 44.7 us +- 0.5 us -> 41.9 us +- 0.9 us: 1.07x faster
- scimark_sor: 215 ms +- 4 ms -> 203 ms +- 3 ms: 1.06x faster
- telco: 11.3 ms +- 0.1 ms -> 10.8 ms +- 0.1 ms: 1.04x faster
- unpickle: 23.0 us +- 0.3 us -> 22.2 us +- 0.2 us: 1.04x faster
- pickle_list: 6.75 us +- 0.17 us -> 6.60 us +- 0.19 us: 1.02x faster
- python_startup: 13.8 ms +- 1.2 ms -> 13.5 ms +- 0.1 ms: 1.02x faster

Benchmark hidden because not significant (27): 2to3, chameleon, chaos, json_loads, mako, pickle, pid
igits, pyflate, python_startup_no_site, raytrace, regex_dna, regex_effbot, regex_v8, richards, scima
rk_lu, scimark_sparse_mat_mult, spectral_norm, sqlite_synth, sympy_expand, sympy_integrate, sympy_su
m, sympy_str, tornado_http, unpack_sequence, unpickle_list, xml_etree_parse, xml_etree_iterparse

Geometric mean: 1.02x slower
```
```
>pyperf compare_to  assume64  emptyfunc64

Slower (23):
- nbody: 179 ms +- 6 ms -> 191 ms +- 4 ms: 1.07x slower
- xml_etree_process: 98.3 ms +- 1.7 ms -> 105 ms +- 1 ms: 1.07x slower
- meteor_contest: 152 ms +- 1 ms -> 163 ms +- 7 ms: 1.07x slower
- scimark_fft: 491 ms +- 13 ms -> 523 ms +- 11 ms: 1.07x slower
- xml_etree_generate: 138 ms +- 4 ms -> 146 ms +- 3 ms: 1.06x slower
- fannkuch: 627 ms +- 14 ms -> 662 ms +- 15 ms: 1.06x slower
- spectral_norm: 179 ms +- 2 ms -> 189 ms +- 3 ms: 1.05x slower
- unpickle_pure_python: 348 us +- 9 us -> 366 us +- 5 us: 1.05x slower
- telco: 11.3 ms +- 0.1 ms -> 11.8 ms +- 0.2 ms: 1.05x slower
- scimark_lu: 153 ms +- 3 ms -> 160 ms +- 2 ms: 1.04x slower
- django_template: 85.4 ms +- 1.1 ms -> 89.0 ms +- 1.2 ms: 1.04x slower
- python_startup: 13.8 ms +- 1.2 ms -> 14.3 ms +- 1.8 ms: 1.04x slower
- nqueens: 164 ms +- 1 ms -> 170 ms +- 4 ms: 1.04x slower
- json_dumps: 21.1 ms +- 0.2 ms -> 21.9 ms +- 0.2 ms: 1.04x slower
- deltablue: 6.78 ms +- 0.23 ms -> 7.01 ms +- 0.10 ms: 1.03x slower
- crypto_pyaes: 127 ms +- 3 ms -> 131 ms +- 3 ms: 1.03x slower
- unpack_sequence: 69.1 ns +- 3.0 ns -> 71.3 ns +- 6.4 ns: 1.03x slower
- hexiom: 10.8 ms +- 0.1 ms -> 11.1 ms +- 0.2 ms: 1.03x slower
- sympy_sum: 299 ms +- 4 ms -> 308 ms +- 6 ms: 1.03x slower
- chameleon: 14.7 ms +- 0.2 ms -> 15.1 ms +- 0.8 ms: 1.03x slower
- sqlalchemy_declarative: 277 ms +- 8 ms -> 284 ms +- 12 ms: 1.02x slower
- raytrace: 543 ms +- 6 ms -> 556 ms +- 8 ms: 1.02x slower
- scimark_sparse_mat_mult: 6.86 ms +- 0.35 ms -> 7.00 ms +- 0.30 ms: 1.02x slower

Faster (4):
- scimark_sor: 215 ms +- 4 ms -> 202 ms +- 2 ms: 1.06x faster
- sqlite_synth: 5.44 us +- 0.13 us -> 5.21 us +- 0.02 us: 1.05x faster
- pickle_list: 6.75 us +- 0.17 us -> 6.53 us +- 0.05 us: 1.03x faster
- pickle_dict: 44.7 us +- 0.5 us -> 43.7 us +- 1.5 us: 1.02x faster

Benchmark hidden because not significant (31): 2to3, chaos, dulwich_log, float, go, json_loads, logg
ing_format, logging_silent, logging_simple, mako, pathlib, pickle, pickle_pure_python, pidigits, pyf
late, python_startup_no_site, regex_compile, regex_dna, regex_effbot, regex_v8, richards, scimark_mo
nte_carlo, sqlalchemy_imperative, sympy_expand, sympy_integrate, sympy_str, tornado_http, unpickle,
unpickle_list, xml_etree_parse, xml_etree_iterparse

Geometric mean: 1.02x slower
```


```
>pyperf compare_to  assume86  fatalerr86

Slower (6):
- sqlalchemy_imperative: 40.2 ms +- 2.2 ms -> 42.6 ms +- 2.9 ms: 1.06x slower
- unpickle_list: 8.10 us +- 0.10 us -> 8.47 us +- 0.18 us: 1.05x slower
- pickle: 21.1 us +- 0.6 us -> 21.8 us +- 0.2 us: 1.04x slower
- scimark_monte_carlo: 148 ms +- 5 ms -> 153 ms +- 5 ms: 1.03x slower
- sqlalchemy_declarative: 261 ms +- 5 ms -> 269 ms +- 14 ms: 1.03x slower
- sqlite_synth: 5.57 us +- 0.03 us -> 5.71 us +- 0.03 us: 1.03x slower

Faster (28):
- unpack_sequence: 126 ns +- 11 ns -> 95.3 ns +- 5.7 ns: 1.32x faster
- logging_silent: 225 ns +- 5 ns -> 191 ns +- 10 ns: 1.18x faster
- spectral_norm: 279 ms +- 6 ms -> 244 ms +- 4 ms: 1.14x faster
- hexiom: 14.3 ms +- 0.1 ms -> 12.6 ms +- 0.1 ms: 1.14x faster
- scimark_lu: 230 ms +- 6 ms -> 205 ms +- 5 ms: 1.12x faster
- richards: 101 ms +- 1 ms -> 90.4 ms +- 4.0 ms: 1.12x faster
- scimark_sparse_mat_mult: 10.7 ms +- 0.3 ms -> 9.64 ms +- 0.27 ms: 1.11x faster
- deltablue: 8.37 ms +- 0.10 ms -> 7.65 ms +- 0.31 ms: 1.09x faster
- xml_etree_process: 129 ms +- 1 ms -> 120 ms +- 2 ms: 1.07x faster
- scimark_sor: 275 ms +- 6 ms -> 257 ms +- 11 ms: 1.07x faster
- float: 175 ms +- 2 ms -> 164 ms +- 2 ms: 1.07x faster
- go: 308 ms +- 7 ms -> 288 ms +- 9 ms: 1.07x faster
- xml_etree_generate: 176 ms +- 2 ms -> 165 ms +- 4 ms: 1.06x faster
- pickle_pure_python: 652 us +- 11 us -> 621 us +- 16 us: 1.05x faster
- raytrace: 695 ms +- 5 ms -> 663 ms +- 6 ms: 1.05x faster
- pathlib: 189 ms +- 6 ms -> 180 ms +- 5 ms: 1.04x faster
- pyflate: 963 ms +- 21 ms -> 923 ms +- 27 ms: 1.04x faster
- nbody: 247 ms +- 8 ms -> 237 ms +- 7 ms: 1.04x faster
- xml_etree_parse: 272 ms +- 4 ms -> 264 ms +- 7 ms: 1.03x faster
- regex_compile: 272 ms +- 3 ms -> 263 ms +- 2 ms: 1.03x faster
- mako: 22.0 ms +- 0.3 ms -> 21.3 ms +- 0.1 ms: 1.03x faster
- chameleon: 19.9 ms +- 0.2 ms -> 19.4 ms +- 0.4 ms: 1.03x faster
- chaos: 174 ms +- 2 ms -> 170 ms +- 2 ms: 1.03x faster
- xml_etree_iterparse: 175 ms +- 3 ms -> 170 ms +- 4 ms: 1.03x faster
- nqueens: 203 ms +- 1 ms -> 198 ms +- 2 ms: 1.03x faster
- unpickle_pure_python: 456 us +- 6 us -> 445 us +- 16 us: 1.02x faster
- unpickle: 25.9 us +- 0.4 us -> 25.3 us +- 0.4 us: 1.02x faster
- json_loads: 47.1 us +- 0.4 us -> 46.2 us +- 0.5 us: 1.02x faster

Benchmark hidden because not significant (24): 2to3, crypto_pyaes, django_template, dulwich_log, fan
nkuch, json_dumps, logging_format, logging_simple, meteor_contest, pickle_dict, pickle_list, pidigit
s, python_startup, python_startup_no_site, regex_dna, regex_effbot, regex_v8, scimark_fft, sympy_exp
and, sympy_integrate, sympy_sum, sympy_str, telco, tornado_http

Geometric mean: 1.03x faster
```
```
>pyperf compare_to  assume86  emptyfunc86

Slower (3):
- pickle: 21.1 us +- 0.6 us -> 22.2 us +- 0.5 us: 1.05x slower
- python_startup: 13.2 ms +- 0.2 ms -> 13.8 ms +- 2.5 ms: 1.04x slower
- regex_dna: 243 ms +- 1 ms -> 250 ms +- 6 ms: 1.03x slower

Faster (38):
- unpack_sequence: 126 ns +- 11 ns -> 94.1 ns +- 5.3 ns: 1.34x faster
- hexiom: 14.3 ms +- 0.1 ms -> 12.5 ms +- 0.2 ms: 1.15x faster
- deltablue: 8.37 ms +- 0.10 ms -> 7.43 ms +- 0.08 ms: 1.13x faster
- spectral_norm: 279 ms +- 6 ms -> 249 ms +- 2 ms: 1.12x faster
- logging_silent: 225 ns +- 5 ns -> 202 ns +- 7 ns: 1.11x faster
- xml_etree_process: 129 ms +- 1 ms -> 118 ms +- 1 ms: 1.09x faster
- unpickle_pure_python: 456 us +- 6 us -> 418 us +- 12 us: 1.09x faster
- nqueens: 203 ms +- 1 ms -> 187 ms +- 2 ms: 1.09x faster
- scimark_sparse_mat_mult: 10.7 ms +- 0.3 ms -> 9.85 ms +- 0.33 ms: 1.09x faster
- scimark_lu: 230 ms +- 6 ms -> 213 ms +- 4 ms: 1.08x faster
- xml_etree_generate: 176 ms +- 2 ms -> 163 ms +- 3 ms: 1.08x faster
- richards: 101 ms +- 1 ms -> 93.7 ms +- 3.9 ms: 1.08x faster
- float: 175 ms +- 2 ms -> 163 ms +- 3 ms: 1.08x faster
- scimark_sor: 275 ms +- 6 ms -> 257 ms +- 6 ms: 1.07x faster
- unpickle_list: 8.10 us +- 0.10 us -> 7.60 us +- 0.23 us: 1.07x faster
- scimark_monte_carlo: 148 ms +- 5 ms -> 139 ms +- 5 ms: 1.06x faster
- go: 308 ms +- 7 ms -> 290 ms +- 8 ms: 1.06x faster
- raytrace: 695 ms +- 5 ms -> 661 ms +- 7 ms: 1.05x faster
- crypto_pyaes: 175 ms +- 1 ms -> 166 ms +- 2 ms: 1.05x faster
- nbody: 247 ms +- 8 ms -> 235 ms +- 8 ms: 1.05x faster
- pyflate: 963 ms +- 21 ms -> 917 ms +- 15 ms: 1.05x faster
- xml_etree_iterparse: 175 ms +- 3 ms -> 167 ms +- 6 ms: 1.04x faster
- meteor_contest: 178 ms +- 2 ms -> 171 ms +- 5 ms: 1.04x faster
- sympy_sum: 298 ms +- 11 ms -> 287 ms +- 2 ms: 1.04x faster
- pickle_pure_python: 652 us +- 11 us -> 628 us +- 16 us: 1.04x faster
- scimark_fft: 724 ms +- 10 ms -> 697 ms +- 15 ms: 1.04x faster
- regex_compile: 272 ms +- 3 ms -> 263 ms +- 7 ms: 1.03x faster
- unpickle: 25.9 us +- 0.4 us -> 25.1 us +- 0.3 us: 1.03x faster
- chameleon: 19.9 ms +- 0.2 ms -> 19.3 ms +- 0.4 ms: 1.03x faster
- sympy_expand: 912 ms +- 21 ms -> 885 ms +- 7 ms: 1.03x faster
- mako: 22.0 ms +- 0.3 ms -> 21.4 ms +- 0.2 ms: 1.03x faster
- chaos: 174 ms +- 2 ms -> 169 ms +- 2 ms: 1.03x faster
- django_template: 93.7 ms +- 1.6 ms -> 91.1 ms +- 1.4 ms: 1.03x faster
- fannkuch: 907 ms +- 19 ms -> 885 ms +- 12 ms: 1.02x faster
- sympy_str: 542 ms +- 4 ms -> 529 ms +- 10 ms: 1.02x faster
- xml_etree_parse: 272 ms +- 4 ms -> 266 ms +- 9 ms: 1.02x faster
- json_dumps: 23.8 ms +- 0.2 ms -> 23.3 ms +- 0.3 ms: 1.02x faster
- regex_v8: 38.7 ms +- 0.4 ms -> 38.0 ms +- 0.4 ms: 1.02x faster

Benchmark hidden because not significant (17): 2to3, dulwich_log, json_loads, logging_format, loggin
g_simple, pathlib, pickle_dict, pickle_list, pidigits, python_startup_no_site, regex_effbot, sqlalch
emy_declarative, sqlalchemy_imperative, sqlite_synth, sympy_integrate, telco, tornado_http

Geometric mean: 1.04x faster
```
</details>

**Comment by neonene** [comment] 2022-04-13 01:53
>Are you referring to the code containing the call to Py_UNREACHABLE()? That wouldn't affect the ceval.c main loop in _PyEval_EvalFrameDefault because that function is definitely to large to be inlined. :-)

Here is current Python3.10's inlining decision of MSVC:
https://bugs.python.org/file50291/PR28475_inline.log

Weird, but faster than when only tiny functions are inlined.
In the log, Py_DECREF(static) is expanded until Py_Dealloc(extern) stops its recursion. That looks to me too expansive.

**Comment by gvanrossum** [comment] 2022-04-13 02:44
It looks like we may be looking at different builds? I'm only looking at x64 builds for 3.11.

> If I understand correctly, x86 official binaries are non-PGO builds.
@zooba Is that so?

**Comment by zooba** [comment] 2022-04-13 12:11
> If I understand correctly, x86 official binaries are non-PGO builds.

Yeah, this is correct. We're more likely to deprecate and drop the 32-bit binaries before we make any major effort to optimise them - they run under an emulation layer in the OS (practically all supported OS installs are 64-bit native), so aren't really going to be recommended for people who care about performance anyway.

**Comment by neonene** [comment] 2022-04-23 06:45
I think this issue can be closed. (I can't after migration)

Almost all my experiences are invalid after #91718 corrected the quirks of MSVC(x64).
Another reasonable fix would be good tests which make specialized sections hotter.

Thanks.

**Comment by Fidget-Spinner** [comment] 2022-04-23 09:09
Closing as requested by OP. Thanks for your investigations @neonene ! Thanks to Guido too for the fix.

**Closed as completed by Fidget-Spinner** 2022-04-23 09:09 UTC
Labels: performance, OS-windows, interpreter-core, 3.11, 3.10, topic-C-API

**Comment by gvanrossum** [comment] 2022-04-23 14:38
Thank you @neonene for your gentle pushes and encouragement and help to get this fixed!

**Comment by vstinner** [comment] 2022-04-25 15:39
@neonene:
> Most of my experiences are invalid after Guido's https://github.com/python/cpython/pull/91718 corrected the quirks of MSVC.

Do you mean that this merged change https://github.com/python/cpython/commit/2f233fceae9a0c5e66e439bc0169b36547ba47c3 is now useless?

**Comment by gvanrossum** [comment] 2022-04-25 16:28
No they are complementary.

**Comment by neonene** [comment] 2022-04-25 20:59
>Do you mean that this merged change 2f233fc is now useless?

No. What I said is about the optimization, not the inlining. And what I suggested before have been already fixed by f8dc618 (and 2f233fc):

* `tp_*` or `cfunc` pointer in the eval-loop can inline multiple callees without conflict.

* Moving `LOAD_FAST` out of switch according to the scores below has no speed-up now.
```
TOP3 entries with current 44 tests
case 124  132522464  // LOAD_FAST
case 100   48956231  // LOAD_CONST
case  45   48318813  // LOAD_FAST__LOAD_FAST
```

**Comment by vstinner** [comment] 2022-04-25 22:03
What I understand is that PGO build of Python 3.11 on Windows will be faster thanks to these changes, and the Windows python.org binaries only use PGO for 64-bit, not for 32-bit.

**Comment by neonene** [comment] 2022-04-25 22:33
You can read a bit more posts and links because you have changed this thread's title several times.

**Comment by vstinner** [comment] 2022-04-26 08:02
Can someone please try to write a summary of this long and complex issue? It seems like *different* but *related* topics have been discussed and it's hard to get an overview. I'm confused between sometimes someone said that a change fixed the fix and then wrote that no, it's not really fixing the issue.

**Comment by gvanrossum** [comment] 2022-04-28 04:18
Let me give it a quick try.

- Originally, @neonene observed a Windows-specific performance regression in 3.10 between the a7 and b1 release. This was eventually shown to be caused by the function `_PyEval_EvalFrameDefault` getting so long that the MSVC LTO gave up on inlining many things there. IIUC in 3.10 this was eventually fixed by making the function a bit smaller (https://github.com/python/cpython/pull/28475).

- Of course, the same issue was then observed in the main branch (3.11). We then went back and forth trying various approaches to fix it. This wasn't easy because (a) the code kept changing (because the "Faster CPython" team was very active -- mostly growing the function), and (b) we had no good hardware or strategy to run reliable benchmarks. The latter problem spawned https://github.com/faster-cpython/ideas/issues/321.

- Eventually I settled on a fix which consisted of turning a few inline functions back into macros, but only in ceval.c, and not in debug mode (and one only for MSVC). This was PR https://github.com/python/cpython/issues/89279, commit https://github.com/python/cpython/commit/2f233fceae9a0c5e66e439bc0169b36547ba47c3.

- Somewhat relatedly, I also figured out how to get MSVC to generate slightly faster switch code: if you switch on a one-byte value and all 256 cases exist, it skips a memory load. This was PR https://github.com/python/cpython/issues/91719, commit https://github.com/python/cpython/commit/f8dc6186d1857a19edd182277a9d78e6d6cc3787.

- Finally, I figured out how to get stable benchmark numbers (see https://github.com/faster-cpython/ideas/issues/321#issuecomment-1107072776 and following comments) and showed that the macrofied inline functions gave us 10% performance back and the improved switch code gave 3%.

That's it.

**Comment by vstinner** [comment] 2022-04-28 07:00
Thanks for the summary. I would add that marking performance critical function with ``__forceinline`` (Py_ALWAYS_INLINE) was tested, but it didn't work.
