### ISSUE TITLE
For Loop Index not Incrementing

### ISSUE THREAD

**Issue by jelloramus** [python/cpython#103677] opened 2023-04-22 09:27 UTC
# Bug report

I am using a complex program with a for loop in it, the index is not incrementing although the loop is iterating. I suspect it is a defect of my computer. Here is the code repository with a full description in the read me file. (https://github.com/jelloramus/Calculator_from_string)

# Your environment

- Python 3.10.11
- macOS Catalina 10.15.7
- Processor: 3.2 GHz 6-Core Intel Core i7
- Memory: 64GB 2667 MHz DDR4
- Graphics Intel UHD Graphics 630 1536 MB

**Comment by ericvsmith** [comment] 2023-04-22 09:39
You need to provide a minimal example, and you need to tell us what behavior you observed, and how it differed from what is expected. Please post your small example here, not in another repository. 

That said, this is almost certainly not a bug in Python, but rather in your code. Please ask your question in https://discuss.python.org/c/users/7

I’m going to close this. If you still think it’s a big, then follow my advice above and we’ll look at the example code you paste here. 

See also https://stackoverflow.com/help/minimal-reproducible-example for how to make a small reproducible example.

**Closed as not planned by ericvsmith** 2023-04-22 09:39 UTC
Labels: type-bug

**Comment by jelloramus** [comment] 2023-04-22 10:16
even by changing the for loop statement to:

for index_1, token in enumerate(tokenised_prompt[:]):

the issue persists

**Comment by ericvsmith** [comment] 2023-04-22 11:24
You have not said what you see, and what you expect to see, so we cannot help you.
