### ISSUE TITLE
asserting that the tstate pointer is non-NULL using assert

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#122928] opened 2024-08-12 01:59 UTC
# Bug report

### Bug description:

https://github.com/python/cpython/blob/main/Python/pystate.c#L3016

To prevent dangling pointer issues, adding a check for NULL ensures that invalid pointers are not dereferenced

### Linked PRs
* gh-122929

**Comment by ZeroIntensity** [comment] 2024-08-12 09:03
As mentioned in the PR, a `NULL` check doesn't fix dangling pointers.

With that being said, calling `_PyThreadState_MustExit` with an invalid thread state sounds like a bug, is there a specific case of this happening?

**Comment by neonene** [comment] 2024-08-13 17:02
My understanding is that a dangling pointer could possibly be caused by the legacy non-isolated subinterpreter created with [`Py_NewInterpreter()`](https://docs.python.org/3.14/c-api/init.html#c.Py_NewInterpreter), _allowing daemon threads_.  Now that Python uses and recommends the new isolated subinterpreter, I do not think the concern is worth much consideration.

See also https://github.com/python/cpython/pull/109794#issuecomment-1740129317, https://github.com/python/cpython/issues/104341#issuecomment-1571130439.

**Comment by picnixz** [comment] 2024-08-14 06:49
I'm wondering whether the issue should still mention *dangling pointer* since a dangling pointer is a valid pointer (hence non-null) pointing to invalid memory. It's more about asserting that the pointer is non-NULL using `assert` (namely, enforcing pre-conditions).

**Comment by neonene** [comment] 2024-08-15 00:36
Please change the title, or make the PR belong to gh-109793.  The current title is not good for closing here as "completed".

**Comment by vstinner** [comment] 2024-09-18 17:17
The change is not needed: https://github.com/python/cpython/pull/122929#pullrequestreview-2313315890

**Closed as not planned by vstinner** 2024-09-18 17:17 UTC
Labels: type-bug
