### ISSUE TITLE
`get_origin(str|None) != get_origin(Union[str,None])`

### ISSUE THREAD

**Issue by moi90** [python/cpython#119302] opened 2024-05-21 11:48 UTC
# Bug report

### Bug description:

There seems to be a bug with `str|None` vs `Union[str,None]` / `Optional[str]`:

```python
from typing import Union, get_origin

assert get_origin(str|None) == get_origin(Union[str,None])

get_origin(str|None)
# <class 'types.UnionType'>

get_origin(Union[str,None])
Union
```

This is unexpected to me and I think this is an error.

I verified this behavior on 3.10, 3.11 and 3.12.

### CPython versions tested on:

3.10, 3.11, 3.12

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment] 2024-05-21 11:50
Hello!
There's no bug since it's really different types, although semantically it's the same.
After merge of #105511 this problem will gone.
cc @JelleZijlstra

**Comment by JelleZijlstra** [comment] 2024-05-21 11:51
Duplicate of #105499.

**Closed as not planned by JelleZijlstra** 2024-05-21 11:51 UTC
Labels: type-bug, topic-typing

**Comment by moi90** [comment] 2024-05-22 08:47
Thanks for the info! So currently, one needs to do `get_origin(...) in (Union, UnionType)` to check whether an annotation is any kind of union?

**Comment by Eclips4** [comment] 2024-05-22 10:12
> Thanks for the info! So currently, one needs to do `get_origin(...) in (Union, UnionType)` to check whether an annotation is any kind of union?

Yes.
