### ISSUE TITLE
importlib.metadata.distribution fails to find entry points

### ISSUE THREAD

**Issue by yurivict** [python/cpython#101608] opened 2023-02-06 17:24 UTC
# Bug report

Many Python packages install executables. Under some conditions, when some other python packages installed, such executables fail. For example, pip installs this executable:
```
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'pip==22.3.1'

try:
    from importlib.metadata import distribution
except ImportError: 
    try:
        from importlib_metadata import distribution
    except ImportError: 
        from pkg_resources import load_entry_point
    

def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('pip==22.3.1', 'console_scripts', 'pip')())
```

It fails to find any entry points, and it returns the empty list as ```importlib.metadata.distribution('pip').entry_points```.

As a result pip fails:
```
$ pip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==22.3.1', 'console_scripts', 'pip')())
  File "/usr/local/bin/pip", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

# Your environment

- CPython versions tested on: 3.9
- Operating system and architecture: FreeBSD 13.1

**Comment by jaraco** [comment] 2023-04-16 23:20
Thanks for the report. The conditions described here require more detail. The `entry_points` mechanism works in the general case, so there's some other factor that's affecting the discoverability of the entry points (the metadata). Probably the metadata is missing or is being masked by something else on `sys.path`.

I'll need either a way to replicate the conditions that lead to the behavior or I'll need you to investigate more deeply in the environment where the issue occurs.

Since it's FreeBSD, that will hamper my ability to replicate any environment. I'd prefer something that I can replicate in a lightweight virtualization system.

To investigate more deeply, consider inspecting the distributions returned by `importlib.metadata.distributions(name='pip')`. Presumably there is 0 or > 1. Take a look at the `_path` attributes of each and see if that gives any clues about where the improper metadata is coming from.

**Comment by jaraco** [comment] 2024-03-21 02:44
I'm closing this issue as it requires more information to reproduce the issue. Feel free to follow-up and I can re-open it.

**Closed as completed** 2024-03-21 02:44 UTC
Labels: type-bug, topic-importlib
