### ISSUE TITLE
`make regen-all` fails on conflict markers in argument clinic code

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#126207] opened 2024-10-30 20:42 UTC
# Bug report

### Bug description:

Output:

```none
gcc  -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall    -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal -I./Include/internal/mimalloc  -I. -I./Include    -DPy_BUILD_CORE_BUILTIN -c ./Modules/posixmodule.c -o Modules/posixmodule.o
In file included from ./Modules/posixmodule.c:15944:
./Modules/clinic/posixmodule.c.h:13087:1: error: version control conflict marker in file
<<<<<<< HEAD
^
1 error generated.
make: *** [Modules/posixmodule.o] Error 1
```

This makes it harder to fix merge conflicts, see: https://discuss.python.org/t/reducing-merge-conflicts-in-generated-code/68537/8

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by rruuaanng** [comment] 2024-10-31 01:41
Can you give a minimum trigger? I can't reproduce the issue (I'll try to fix it later, but that doesn't affect anyone else from being able to complete the issue)

**Comment by nineteendo** [comment] 2024-10-31 06:50
You can just insert a conflict marker in `Modules/posixmodule.c.h`:

```c
<<<<<<< HEAD
/*[clinic end generated code: output=1da32369b7d9fd4b input=a9049054013a1b77]*/
=======
/*[clinic end generated code: output=1da32369b7d9fd4b input=a9049054013a1b77]*/
>>>>>>> main
```

**Comment by erlend-aasland** [comment] 2024-10-31 10:16
Please do not create multiple issues for the same problems. Please both of you, see the devguide for how to use the bug tracker.

Duplicate of #126206.

**Closed as not planned by erlend-aasland** 2024-10-31 10:16 UTC
Labels: type-bug, build, topic-argument-clinic

**Comment by nineteendo** [comment] 2024-10-31 12:54
While this is related, this wouldn't necessary be fixed if the other "bug" was fixed. You could have just said that your comment on the other thread also applies here.
