### ISSUE TITLE
Secure coding is not enabled for restorable state! WARNING on Mac OS Sonoma 14.0

### ISSUE THREAD

**Issue by eamarten** [python/cpython#110950] opened 2023-10-16 21:29 UTC
# Bug report

### Bug description:

With turtle_test.py containing

```
from turtle import home
home()
```
running
```
python turtle_test.py
```
outputs:

2023-10-17 08:21:27.948 Python[19831:20908209] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-111041
* gh-112293
* gh-112294

**Comment by terryjreedy** [comment] 2023-10-17 04:31
For anyone's information, `turtle.home` should turtle screen to appear with the turtle at the home (origin) position and orientation.

**Comment by ronaldoussoren** [comment] 2023-10-17 06:38
Minimal reproducer: ``import tkinter; tkinter.Tk()``.

This is a problem in Tk, not in Tkinter as we don't use Cocoa in the Tkinter source code.

**Comment by ugandhar84** [comment] 2023-10-18 02:38
i'm also facing same error - do we have nay resolution for this?

**Comment by aivarannamaa** [comment] 2023-10-18 07:53
I just created a ticket in Tcl/Tk project: https://core.tcl-lang.org/tk/tktview/10b38a7a7c13235296cb0fbc6205f591d5ed15a4

**Comment by SimpungaElias** [comment] 2023-10-18 10:28
what to do with this error?

**Comment by aivarannamaa** [comment] 2023-10-18 12:15
It looks just a warning to me. I haven't seen any misbehaviour in my app after upgrading to Sonoma. So I guess for now you can just ignore it.

**Comment by SimpungaElias** [comment] 2023-10-18 12:57
I am using PyCharm, so the problem is that the UI is not working, all parameters are set well, but all I am seeing is white color background

**Comment by BenjaminIsMyName** [comment] 2023-10-18 14:44
Minimal reproducer with pygame:

```py
import pygame

pygame.init()
screen = pygame.display.set_mode((800, 600))
```

**Comment by chrstphrchvz** [comment] 2023-10-18 17:42
> I am using PyCharm, so the problem is that the UI is not working, all parameters are set well, but all I am seeing is white color background

@SimpungaElias, that issue sounds unrelated to the `Secure coding is not enabled for restorable state!` warning.

**Comment by chrstphrchvz** [comment] 2023-10-18 18:03
Upstream Tcl/Tk has implemented the method suggested by the warning. I have verified that doing so prevents the warning in Tcl/Tk. However, I currently do not have a Python framework build which I can both observe the warning from Tkinter and see whether the upstream fix makes a difference.

I have opened #111041 in case Python is interested in backporting the upstream fix to the macOS installers, and assuming it works for Tkinter.

**Comment by Pablosarti7** [comment] 2023-10-23 16:17
Did anyone find a solution to this problem?

**Comment by pauldebeurs** [comment] 2023-10-26 12:14
I work with Python 3.11.1 and I use matplotlib.pyplot.
Since Sonoma 14.0 I get a warning:  Secure coding is not enabled for restorable state!
When I don't plot there is no warning.
Can Apple resolve this for us?

**Comment by Heilige-49** [comment] 2023-11-10 01:53
> I work with Python 3.11.1 and I use matplotlib.pyplot. Since Sonoma 14.0 I get a warning: Secure coding is not enabled for restorable state! When I don't plot there is no warning. Can Apple resolve this for us?

I am facing the same issue and don't really know how to fix it

**Comment by ronaldoussoren** [comment] 2023-11-13 08:53
> > I work with Python 3.11.1 and I use matplotlib.pyplot. Since Sonoma 14.0 I get a warning: Secure coding is not enabled for restorable state! When I don't plot there is no warning. Can Apple resolve this for us?
> 
> I am facing the same issue and don't really know how to fix it

This is warning, not an error and therefore you don't _have_ to do anything.  The cause for the warning is fixed in the codebase of Tcl/Tk and will be included in a future release of Tcl/Tk and then in a future release of Python.

**Comment by ericsuchagenius** [comment] 2023-11-15 00:45
wait guys i also have this problem, when i implement tkinter even though it pops up a showing window, there is nothing on it even though i followed the steps, but it is just not printing, in the console, there is this line of warning which is simular to the description above. 

from tkinter import *
root = Tk()
myLabel = Label(root,text="helloworld")
myLabel.pack()
root.mainloop()

**Comment by benjiprores** [comment] 2023-11-17 05:52
> wait guys i also have this problem, when i implement tkinter even though it pops up a showing window, there is nothing on it even though i followed the steps, but it is just not printing, in the console, there is this line of warning which is simular to the description above.
> 
> from tkinter import * root = Tk() myLabel = Label(root,text="helloworld") myLabel.pack() root.mainloop()

Yes also having the same problem here…
When are they going to fix this!!

**Comment by Heilige-49** [comment] 2023-11-18 23:49
> > wait guys i also have this problem, when i implement tkinter even though it pops up a showing window, there is nothing on it even though i followed the steps, but it is just not printing, in the console, there is this line of warning which is simular to the description above.
> > from tkinter import * root = Tk() myLabel = Label(root,text="helloworld") myLabel.pack() root.mainloop()
> 
> Yes also having the same problem here… When are they going to fix this!!

I am facing the same issue and I am fed up. I decided to use Pycharm and it works swiftly.

**Comment by ned-deily** [comment] 2023-11-21 09:05
Thanks for the PR. The fix for Tk in the macOS installer has now been merged for release in 3.13.0a2, 3.12.1, and 3.11.7.

**Closed as completed by ned-deily** 2023-11-21 09:05 UTC
Labels: type-bug, OS-mac, topic-tkinter, pending

**Comment by Heilige-49** [comment] 2023-12-04 11:18
Presently I am using Pycharm and it's not having any issue somehow and
works pretty well to date.

**Comment by u-aida** [comment] 2023-12-13 10:48
I got same error pysimplegui with matplotlib.

My environment configuration is
Python:  3.12 (Because of pysimplegui do not work with SONOMA)
Mac OS: 14.2 (Preview version of Sonoma had same issue)

Python problem is happened after I update to Sonoma.

**Comment by ned-deily** [comment] 2023-12-18 06:04
@u-aida: Note above: "The fix for Tk in the macOS installer has now been merged for release in 3.13.0a2, 3.12.1, and 3.11.7." And this only applies to those Pythons for macOS downloadable from the python.org website. If you are using a Python from another source, contact its distributor and ask them to update their version of Tk.

**Comment by Wangsd823** [comment] 2023-12-18 06:28
> wait guys i also have this problem, when i implement tkinter even though it pops up a showing window, there is nothing on it even though i followed the steps, but it is just not printing, in the console, there is this line of warning which is simular to the description above.
> 
> from tkinter import * root = Tk() myLabel = Label(root,text="helloworld") myLabel.pack() root.mainloop()

I had the same problem.
Python:  3.9.6
Tkinter: 8.5
Mac OS: 14.2

**Comment by ned-deily** [comment] 2023-12-18 23:15
> I had the same problem.
> 
> Python: 3.9.6 Tkinter: 8.5 Mac OS: 14.2

There seems to be a lot of confusion and conflation of issues here. This issue is closed and was about the `secure coding` warning that may be seen when using currently released versions of Tk, which is what Python's `tkinter` uses as a GUI library, on macOS 14 Sonoma. This message is only a **warning** and can be **ignored**. As noted above, a patch to eliminate the warning has been applied to the Tk released with the most recent `python.org` macOS installers (for 3.13.0a2, 3.12.1, and 3.11.7). If you use Python on macOS from another source, the Tk versions used by them would need to be patched to eliminate the warning.

Any other behavior you may be seeing is a **different** problem, unrelated to this issue. It might be a Tk problem or it might be a Python problem or it might be a usage problem, but it is not **this** problem. Anyone wanting to pursue another problem should follow the usual procedures, like looking for [help in one of the many forums](https://www.python.org/about/help/) and checking the Python and Tk issue trackers for similar reports.

In this particular case, be aware that Tk 8.5 is extremely old and unsupported and likely has many problems on more recent macOS releases. Python 3.9.6 is also very old and 3.9 is now in the security-fix-only phase of its life cycle: the [most recent release of Python 3.9](https://peps.python.org/pep-0596/) is 3.9.18 and the last full bugfix release with binary installers was 3.9.13. Python 3.11.x and 3.12.x are [the current fully-supported release versions](https://www.python.org/downloads/).

**Comment by ronaldoussoren** [comment] 2023-12-19 19:12
Note that `/usr/bin/python3` also loudly complains about the usage of tkinter:

```
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
```

It is highly unlikely that Apple will ever fix issues like this with Tk or upgrade Tk to a newer version. If you want to use Tkinter with Python you need to install a newer version.
