### ISSUE TITLE
https://docs.python.org/3.11/whatsnew/3.11.html has not updated since 25 Apr

### ISSUE THREAD

**Issue by corona10** [python/cpython#92532] opened 2022-05-09 06:27 UTC
The title is the description :)
cc @Fidget-Spinner

**Comment by hugovk** [comment] 2022-05-09 06:37
cc also @JulienPalard

**Comment by JulienPalard** [comment] 2022-05-09 10:05
Ohhh that's why the number of build errors suspiciously went to 0 on Sentry... it raised a flag in my mind to check it (but I was on holidays...).

I see it now! There's a `sphinx-build` process stuck since the 26 Apr:

    docsbui+ 18192  0.0  1.3 170376 111780 ?       S    Apr26   0:16                                  \_ /srv/docsbuild/venv-with-sphinx-3.2.1/bin/python /srv/docsbuild/venv-with-sphinx-3.2.1/bin/sphinx-build -b html -d build/doctrees -D latex_engine=xelatex -D latex_elements.inputenc= -D latex_elements.fontenc=\usepackage{xeCJK} -j4 -q -D locale_dirs=/srv/docsbuild/3.10/locale -D language=zh_TW -D gettext_compact=0 -Ea -A daily=1 . build/html

 Killing it and keeping an eye on it... I'll try to diagnose if it happen again. It looks related to Sphinx parallelisation (main process were waiting for the child while the child was trying to write on a pipe, maybe to the main process).

**Comment by JulienPalard** [comment] 2022-05-09 10:49
Closing it, as I don't feel the need to investigate as long as it does not reproduce, feel free to reopen if it happen agian.

I'll monitor the builds closely today and tomorrow as [we've added Python 3.12](https://github.com/python/docsbuild-scripts/commit/30b98030d78db56b28f8590b877f3c33f79b913d) yesterday.

**Closed as completed by JulienPalard** 2022-05-09 10:49 UTC
Labels: docs

**Comment by vstinner** [comment] 2022-05-09 11:51
Thank you for fixing the job.
