### ISSUE TITLE
test_tomllib.test_inline_array_recursion_limit() failed on wasm32-wasi 3.11 buildbot

### ISSUE THREAD

**Issue by vstinner** [python/cpython#108851] opened 2023-09-03 19:01 UTC
test_tomllib.test_inline_array_recursion_limit() failed on wasm32-wasi 3.11 buildbot:

```
ERROR: test_inline_array_recursion_limit (test.test_tomllib.test_misc.TestMiscellaneous.test_inline_array_recursion_limit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Lib/test/test_tomllib/test_misc.py", line 98, in test_inline_array_recursion_limit
    tomllib.loads(recursive_array_toml)
  File "/Lib/tomllib/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/tomllib/_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/tomllib/_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/tomllib/_parser.py", line 616, in parse_value
    return parse_array(src, pos, parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/tomllib/_parser.py", line 420, in parse_array
    pos, val = parse_value(src, pos, parse_float)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  (...)
  File "/Lib/tomllib/_parser.py", line 416, in parse_array
    pos = skip_comments_and_array_ws(src, pos)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/tomllib/_parser.py", line 278, in skip_comments_and_array_ws
    pos = skip_chars(src, pos, TOML_WS_AND_NEWLINE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```

link: https://buildbot.python.org/all/#/builders/1047/builds/908

### Linked PRs
* gh-108853
* gh-109012
* gh-109013
* gh-110127

**Comment by markshannon** [comment] 2023-11-18 12:18
I don't understand what's going on here.
Why does the test fail?
Hacking the tests does not seem to be the right solution. Why not fix the underlying problem, or at least triage it first?

**Comment by markshannon** [comment] 2023-11-18 12:19
My mistake. I didn't see the all important `3.11` part.
Still, we ought to record what the problem is on the issue, before fixing it.

**Comment by vstinner** [comment] 2023-11-27 11:13
> So, why change 3.13 and 3.12, if this is a 3.11 issue?

First I saw the issue on 3.11, but in fact the 3 branches were affectected: 3.11, 3.12 and main.

@markshannon: Did you reopen the issue because you want to make changes?

**Comment by brettcannon** [comment] 2023-12-14 23:06
Since all the buildbots are passing, I'm closing the issue as fixed.

**Closed as completed by brettcannon** 2023-12-14 23:06 UTC
Labels: tests, 3.11, OS-wasi
