### ISSUE TITLE
Abstract class validation exception contains misleading text

### ISSUE THREAD

**Issue by foxx** [python/cpython#100714] opened 2023-01-03 14:31 UTC
# Bug report

When subclassing from an ABC, if the child does not implement a required `abstractmethod` of the parent, the raised error message is potentially misleading.

For example

```
class Parent(ABC):
    """."""
    
    @abstractmethod
    def required_method(self):
        pass

class Child(Parent):
    """."""

>>> Child()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't instantiate abstract class Child with abstract method required_method
```

The message says `with abstract method`, but I think this is supposed to say `without abstract method`? E.g. "Child cannot be instanciated _without_ implementing required_method".

I scoured Google and other bug reports but I haven't found anyone complaining about this, which makes me think either I'm being pedantic or I've misunderstood the nature of this error message.

/cc @rhettinger (ps. thanks for your talk on ABCs, very useful!)

# Your environment

- CPython versions tested on: 3.10.8
- Operating system and architecture: Debian 11 (64-bit)

**Comment by FrozenBob** [comment] 2023-01-03 15:46
It says "with abstract method" because the problem is that the class *does* have an abstract method. If you override `abstract_method`, then the class will no longer have an abstract method.

The message could be more explicit, but it doesn't sound like it's a common source of confusion.

**Comment by bswck** [comment] 2023-01-03 15:54
I believe that the message should be comprehended in a different way. Abstract method is a method of an abstract class (has no implementation). Unless there is a subclass that actually implements the method, every subclass of the abstract class inherit a yet-abstract method and they remain abstract. Thus, every subclass that contain abstract methods, even for the reason of inheritance, are still abstract classes. And as we know, in order to be able to instantiate a class that inherits from an abstract class, it must implement all abstract methods, that - if not overridden - still remain abstract. Consequently, the `Child` example you've shown above has an abstract method `Parent.required_method`, because it was not overridden with a non-abstract method (in other words, the implementation). Since the mentioned class `Child` contains an abstract method, it remains abstract, so you **can't instantiate abstract class Child with abstract method required_method**.

**Comment by bswck** [comment] 2023-01-03 16:05
> It says "with abstract method" because the problem is that the class _does_ have an abstract method. If you override `abstract_method`, then the class will no longer have an abstract method.
> 
> The message could be more explicit, but it doesn't sound like it's a common source of confusion.

My linter always warns me that if my class inherits from an abstract class and not all methods were overridden with implementation, I should add either `abc.ABC` as another base class or add the `abc.ABCMeta` metaclass.

When it comes to "unconfusing" the message, my suggestion would be:
`TypeError: Can't instantiate abstract class Child (method required_method is abstract)`
as an example that can be applied to its other variants. I guess.

Maybe this one seems hard to implement from the linguistic viewpoint (`method/methods`, is/are`), but judging by the verbosity of new exception message style that came in 3.10, it would be perfect.

**Comment by carljm** [comment] 2023-01-03 18:06
I think, given that this doesn't seem to be a common misunderstanding of the error message, we can close this.

**Closed as not planned by carljm** 2023-01-03 18:06 UTC
Labels: type-bug
