### ISSUE TITLE
argparse: a bool indicating if arg was encountered

### ISSUE THREAD

**Issue by 8f7af792-b253-47a0-a819-5d9d43b69770** [python/cpython#88911] opened 2021-07-27 09:26 UTC
BPO | [44748](https://bugs.python.org/issue44748)
--- | :---
Nosy | @rhettinger, @terryjreedy, @Thermi, @🖤Black Joker🖤, @wodny

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-27.09:26:32.507>
labels = ['type-feature', 'library', '3.11']
title = 'argparse: a bool indicating if arg was encountered'
updated_at = <Date 2021-09-03.07:39:47.645>
user = 'https://github.com/Thermi'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-03.07:39:47.645>
actor = 'wodny85'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-07-27.09:26:32.507>
creator = 'Thermi'
dependencies = []
files = []
hgrepos = []
issue_num = 44748
keywords = []
message_count = 14.0
messages = ['398288', '398351', '398358', '398416', '398417', '398456', '398608', '400957', '400958', '400968', '400969', '400971', '400973', '400986']
nosy_count = 6.0
nosy_names = ['rhettinger', 'terry.reedy', 'paul.j3', 'Thermi', 'joker', 'wodny85']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44748'
versions = ['Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment] 2024-09-28 15:06
It look that the desired behavior can be achieved by implemented the feature discussed in #70582.

Until it is implemented, you have other options: set special default values which would allow you to determine if arguments were specified, define and use custom actions that set special boolean attributes for every specified argument or collect them in a special list. It can take a lot of work, but it's not a common request.

Closing as a duplicate of #70582.

**Closed as not planned by serhiy-storchaka** 2024-09-28 15:06 UTC
Labels: type-feature, stdlib, 3.11
