### ISSUE TITLE
Tutorial- The warning box is overextended

### ISSUE THREAD

**Issue by Majdoddin** [python/cpython#95759] opened 2022-08-07 09:27 UTC
# Documentation

https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

The redbox of the Warning is extended to the end of page.

**Comment by AlexWaygood** [comment] 2022-08-07 09:37
Duplicate of #91483

**Comment by AlexWaygood** [comment] 2022-08-07 09:37
But thanks for the report!

**Closed as not planned by AlexWaygood** 2022-08-07 09:37 UTC
Labels: docs
