### ISSUE TITLE
Revisit: start_tls() difficult when using asyncio.start_server()

### ISSUE THREAD

**Issue by 33261372-b612-453a-9fa0-b941410d4a01** [python/cpython#90046] opened 2021-11-24 07:37 UTC
BPO | [45888](https://bugs.python.org/issue45888)
--- | :---
Nosy | @tiran, @rob-blackbourn

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2021-11-24.07:37:09.328>
labels = ['expert-SSL', '3.8', '3.9', '3.10', '3.11', 'type-feature', 'library']
title = 'Revisit: start_tls() difficult when using asyncio.start_server()'
updated_at = <Date 2021-11-24.07:37:09.328>
user = 'https://github.com/rob-blackbourn'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-24.07:37:09.328>
actor = 'rob-blackbourn'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'SSL']
creation = <Date 2021-11-24.07:37:09.328>
creator = 'rob-blackbourn'
dependencies = []
files = []
hgrepos = []
issue_num = 45888
keywords = []
message_count = 1.0
messages = ['406906']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'rob-blackbourn']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45888'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by rob-blackbourn** [comment] 2022-04-15 08:56
I notice the original issue has been reopened. Should we close this?

**Comment by kumaraditya303** [comment] 2022-04-16 12:16
Duplicate of https://github.com/python/cpython/issues/79156

**Closed as completed by kumaraditya303** 2022-04-16 12:16 UTC
Labels: type-feature, stdlib, 3.11, 3.10, 3.9 (EOL), 3.8 (EOL), topic-SSL
