### ISSUE TITLE
abc submodule not an attribute of collections on Python 3.10.0 on Windows

### ISSUE THREAD

**Issue by 6e0f1165-6736-4a0b-8d45-05b6e218dc97** [python/cpython#89934] opened 2021-11-10 06:54 UTC
BPO | [45776](https://bugs.python.org/issue45776)
--- | :---
Nosy | @rhettinger, @pfmoore, @mdickinson, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-10.06:54:36.514>
labels = ['type-bug', '3.10', 'OS-windows']
title = 'abc submodule not an attribute of collections on Python 3.10.0 on Windows'
updated_at = <Date 2021-11-10.17:46:37.244>
user = 'https://bugs.python.org/stcanny'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-10.17:46:37.244>
actor = 'stcanny'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2021-11-10.06:54:36.514>
creator = 'stcanny'
dependencies = []
files = []
hgrepos = []
issue_num = 45776
keywords = []
message_count = 7.0
messages = ['406074', '406093', '406103', '406105', '406110', '406113', '406119']
nosy_count = 7.0
nosy_names = ['rhettinger', 'paul.moore', 'mark.dickinson', 'tim.golden', 'zach.ware', 'steve.dower', 'stcanny']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45776'
versions = ['Python 3.10']
```

</p></details>

**Comment by ronaldoussoren** [comment] 2022-08-27 09:37
IMHO there is no bug here. The ``abc`` will be an attribute of ``collections`` when something has imported ``collections.abc`` and won't be an attribute otherwise. That's normal Python import behaviour. 

The deprecated (and later removed) feature w.r.t. ABCs and the collections module is to import an ABC directly from the the collections module, e.g. ``from collections import Sequence``. The correct code is ``from collections.abc import Sequence``. That's unrelated to ``abc`` being available as an attribute on ``collections``.

**Comment by iritkatriel** [comment] 2022-09-07 10:50
I removed the bug label, because I agree this is not a bug. (In any case, we will not change 3.10 now to import collections.abc when you import collection).

Is it worth optimising the import from inspect on Mac?

**Comment by ronaldoussoren** [comment] 2022-09-12 12:41
> I removed the bug label, because I agree this is not a bug. (In any case, we will not change 3.10 now to import collections.abc when you import collection).
> 
> Is it worth optimising the import from inspect on Mac?

Probably not... As @mdickinson noticed this would affect more than just macOS, but any platform using readline/editline.  The import of ``collections.abc`` only happens during interactive sessions, not when running scripts.

**Comment by mdickinson** [comment] 2022-09-12 14:48
+1 for closing

**Closed as not planned** 2022-09-12 14:58 UTC
Labels: performance, OS-mac, pending, 3.12
