### ISSUE TITLE
Problems encountered when using asyncio

### ISSUE THREAD

**Issue by yanwenb** [python/cpython#98955] opened 2022-11-01 11:06 UTC
when i use the aysncio and the event in a Thread, it may have some problems. 
I've run it many times and most of it works, and the error happens occasionally.
It seems only to happen in windows.
in py3.7  ,error is got Future <Future pending> attached to a different loop.
in py3.10 ,it freezes

The code is as follows,  Did I do something wrong?

```python
async def a(event):
    await event.wait()
    print('event is set')
    return 'A'

def start_loop(loop):
    asyncio.set_event_loop(loop)
    loop.run_forever()


def shutdown(loop):
    loop.stop()


def set(event):
    event.set()


if __name__ == "__main__":
    event = asyncio.Event()
    new_loop = asyncio.new_event_loop()
    t = Thread(target=start_loop, args=(new_loop,))
    t.start()

    future = asyncio.run_coroutine_threadsafe(a(
        event=event,
    ), new_loop)
    set(event)

    print(future)
    print(f'Result: {future.result()}')
    new_loop.call_soon_threadsafe(functools.partial(shutdown, new_loop))
```

**Comment by kumaraditya303** [comment] 2022-11-01 12:53
@yanwenb Can you fix the formatting of the code snippet?

**Comment by AlexWaygood** [comment] 2022-11-01 12:54
> @yanwenb Can you fix the formatting of the code snippet?

I edited the message to fix it.

**Comment by kumaraditya303** [comment] 2022-11-15 16:46
I am unable to reproduce this on Windows 11, looking at the code you are creating a global event object which is a bad idea in general and `asyncio` APIs are not thread safe so this is most likely a race condition.

**Comment by yanwenb** [comment] 2022-11-16 01:38
My os is Windows 10.Maybe I have a problem with how I use the asyncio.  Is there any way to use asyncio in thread safety?

**Comment by kumaraditya303** [comment] 2022-11-22 06:15
```py
import asyncio
from threading import Thread
import functools
async def a(event):
    await event.wait()
    print('event is set')
    return 'A'

def start_loop(loop):
    asyncio.set_event_loop(loop)
    loop.run_forever()


def shutdown(loop):
    loop.stop()


def set(event):
    event.set()


if __name__ == "__main__":
    async def main():
        event = asyncio.Event()
        new_loop = asyncio.new_event_loop()
        t = Thread(target=start_loop, args=(new_loop,))
        t.start()

        future = asyncio.run_coroutine_threadsafe(a(
            event=event,
        ), new_loop)
        new_loop.call_soon_threadsafe(set, event)

        print(future)
        print(f'Result: {future.result()}')
        new_loop.call_soon_threadsafe(functools.partial(shutdown, new_loop))
    asyncio.run(main())
```

You should use `call_soon_threadsafe` to make it thread-safe. Thanks for the bug report but I am closing this as it is not a bug.

**Closed as not planned by kumaraditya303** 2022-11-22 06:15 UTC
Labels: type-bug, topic-asyncio, pending
