### ISSUE TITLE
3.8 Documentation code blocks show as all white

### ISSUE THREAD

**Issue by alvaradoo** [python/cpython#115523] opened 2024-02-15 14:45 UTC
When viewing the Python 3.8 documentation on Mozilla Firefox version 122.0.1 and Microsoft Edge version 121.0.2277.12 all code blocks are displayed with a white background where some of the text is impossible to read. Image attached. 

![Capture](https://github.com/python/cpython/assets/41132909/face3a77-4082-4a27-b2e0-f92ce5123ab3)

**Comment by hugovk** [comment] 2024-02-15 14:48
Thanks for the report.

This is a duplicate of https://github.com/python/cpython/issues/115349 which has been fixed, and will be deployed when the next 3.8 and 3.9 releases go out, which I think should be this week.

In the meantime, you can visit the docs for 3.10 or later.

**Closed as not planned by hugovk** 2024-02-15 14:48 UTC
Labels: docs
