### ISSUE TITLE
[Direction of a symbolic link in error messages]

### ISSUE THREAD

**Issue by jaeminSon** [python/cpython#93348] opened 2022-05-30 08:40 UTC
**Bug report**
Direction of a symbolic link is reversed compared to the convention in linux.

>>> import os
>>> src = '/usr/bin/python'
>>> dst = '/tmp/python' # this file already exists in my setting
>>> os.symlink(src, dst)
>>> FileExistsError: [Errno 17] File exists: '/usr/bin/python'-> '/tmp/python'  # '/tmp/python'-> '/usr/bin/python' in a linux terminal

Same for PermissionError.

Environment: 
- CPython versions tested on: python3.7
- Operating system and architecture: Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-47-generic x86_64)

**Comment by eryksun** [comment] 2022-05-30 09:01
Duplicate of #73843

The order shown makes sense from the perspective of the `symlink()` operation's source and destination paths. However, it can be superficially confusing based on the common use of "->" to show the target of a symlink.

**Closed as not planned by eryksun** 2022-05-30 09:01 UTC
Labels: type-bug
