### ISSUE TITLE
Bad indentation after pasting code in interactive interpreter 

### ISSUE THREAD

**Issue by rudyment** [python/cpython#121400] opened 2024-07-05 11:39 UTC
# Bug report

### Bug description:

In the interactive interpreter it is not possible to simply insert function definitions from the clipboard, because each line of the function body is indented compared to the previous one. 

If I copy the function definition:

`def f():`
`   x = 1`
`   x = 2`

to the clipboard and paste it into the interactive interpreter, I get

`>>> def f():`
`...        x = 1`
`...           x = 2`
`  File "<unknown>", line 3`
`    x = 2`
`IndentationError: unexpected indent`
`>>> `

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by JamesParrott** [comment] 2024-07-05 12:01
I've not been able to reproduce this, in 3.13.0a5 from Bash, CMD or Powershell, on Windows 11.

Please could you supply more details, including the exact contents to copy from, e.g. in a Markdown literal code block (enclosed in a pair of triple back-ticks)?

**Comment by Eclips4** [comment] 2024-07-05 13:05
I've able to reproduce it on current main (Windows 10).

**Comment by pablogsal** [comment] 2024-07-13 08:34
Maybe your terminal doesn't have bracketed paste mode (which activates this feature by default). Can you try with normal paste mode (F2)?

**Comment by JamesParrott** [comment] 2024-07-13 09:24
Certainly.  I've updated Windows since I last tried, if that matters.  I've not used F2 paste mode before.  Somehow the first character in the clipboard is deleted (a bug, but Windows does this when I paste into cmd too, so it's nothing to do with Python), so I get a syntax error, and then a different indentation error on the first line.  The second line looks to me like it has the same indent.
![image](https://github.com/user-attachments/assets/8a23bdff-9e0e-499d-95bc-754b38d9b3ca)

![image](https://github.com/user-attachments/assets/34167512-c40e-4819-ae14-362d637575e8)

![image](https://github.com/user-attachments/assets/dcfa58f4-9d2f-4cec-ac09-3ce82d63edad)

![image](https://github.com/user-attachments/assets/87b3bd2e-2a4e-4583-8eca-bc292d952212)

**Comment by JamesParrott** [comment] 2024-07-13 09:51
Right so after your edit I should've been pressing F3 not F2?  OK then, I'll give that a go.

**Comment by pablogsal** [comment] 2024-07-13 13:35
> Right so after your edit I should've been pressing F3 not F2? OK then, I'll give that a go.....
> 
> ....F3 just pastes the last line. This is an indentation error (as it starts with white space), but not the bug.

Ok, that confirms that somehow you don't have bracketed paste mode in the terminal you are using if F3-paste mode works. What terminal are you using?

**Comment by pablogsal** [comment] 2024-07-13 13:36
> F3 just pastes the last line.

What do you mean the last line? Only the last line or the entire text correctly indented?

**Comment by JamesParrott** [comment] 2024-07-13 14:23
It's just called "Terminal" in the start bar and start menu, or in the settings: Windows Terminal (Microsoft Corporation) 1.20.11781.0.  There's another option in there that I'll try now: Windows Console Host  (Microsoft Corporation).  That has a lot of options of its own.

For me, F3 pastes the last line of the multiline text in the clipboard.

Which terminal application do you recommend, that has bracketed paste mode or is it a Windows setting?

**Comment by JamesParrott** [comment] 2024-07-13 14:55
In "Command Prompt" (Windows Console Host) there are these settings.

![image](https://github.com/user-attachments/assets/d2e79c37-5abd-4066-aa21-188e8aaba717)

Toggling "filter clipboard contents", "Enable line wrapping", "Extended text selection" and "Legacy mode" (and restarting the terminal) did not reproduce the bug.  I could paste multiline indented code into Python 3.13 just fine.

Thanks very much for your assitance Pablo.  I didn't know the F keys could  be used for that in a terminal.  But you know I'm not the one inconvenienced by the bug, right?

**Comment by lysnikolaou** [comment] 2024-09-23 20:58
I think we can close this. @pablogsal What do you think?

**Comment by pablogsal** [comment] 2024-09-29 11:11
I agree 👍

**Closed as not planned** 2024-09-29 11:12 UTC
Labels: type-bug, topic-repl

**Comment by rudyment** [comment] 2024-09-29 20:08
The problems caused by the system's wrong response to pressing the F3
key are gone, but I'm afraid the solution is still not optimal. 

For a reason I don't understand, when pressing F3 to switch back from
insert mode to standard mode, the prompt changes not only on the line
where the cursor is currently on, but also on the line before. I don't
know if this is really necessary. 

 Therefore, if the user doesn't want to crash the visual indentation of
the text being pasted from the clipboard, he must type Enter twice
before exiting paste mode to ensure that the appearance of the pasted
code on the last line is not messed up. 

For further clarification, I am ruling PDF-file with a snippet of text
from my last guide where I explained this to readers. 

I apologize, but due to my weaker English, the text is translated by
DeepL program without further editing. 

Rudolf Pecinovsky

Dne 2024-09-23 22:58, Lysandros Nikolaou napsal:

> I think we can close this. @pablogsal [1] What do you think? 
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1] https://github.com/pablogsal
[2]
https://github.com/python/cpython/issues/121400#issuecomment-2369369725
[3]
