### ISSUE TITLE
Trace reports wrong executed line inside case block

### ISSUE THREAD

**Issue by DavideCanton** [python/cpython#105163] opened 2023-05-31 18:30 UTC
# Bug report

When executing a script that has an if inside a case block, if the condition in the if block is false, the `trace` module reports that the last line of the if block is executed, even it is false.

This causes problems with debuggers and code coverage tools.

An example of the problem:

```py
# script bug.py

def foo(n, m):
    match n:
        case 1:
            if m > 0:
                return 1 / 0     
    return -42

foo(1, -1)
```

The output is:
```shell
$ python -m trace -t bug.py
 --- modulename: bug, funcname: <module>
bug.py(3): def foo(n, m):
bug.py(10): foo(1, -1)
 --- modulename: bug, funcname: foo
bug.py(4):     match n:
bug.py(5):         case 1:
bug.py(6):             if m > 0:
bug.py(7):                 return 1 / 0
bug.py(8):     return -42
```

I can't understand why the row 7 (the line with the `return 1 / 0`) is reported as executed in the trace.

The line is not executed, as the program doesn't raise a ZeroDivisionError.

I've tried searching in the issue tracker but didn't find anything, sorry if I missed some already existing issue.

# Your environment

- CPython versions tested on:
  - 3.10.9
  - 3.11.0
- Operating system and architecture:
  - windows 64 bit

**Comment by brandtbucher** [comment] 2023-05-31 21:03
Might be a duplicate of #99474 and #103971.

**Comment by brandtbucher** [comment] 2023-05-31 21:14
Thanks for the report! I've confirmed that this doesn't reproduce on a more recent 3.11.

`3.11.4`, which will does include the fix, is scheduled to be released on Monday.

**Closed as not planned** 2023-05-31 21:14 UTC
Labels: type-bug

**Comment by DavideCanton** [comment] 2023-06-01 07:27
Thanks for the response 👍🏻  !
