### ISSUE TITLE
Add `gc.collect()` at the end of `BaseEventLoop.close()`

### ISSUE THREAD

**Issue by dpr-0** [python/cpython#112280] opened 2023-11-20 09:46 UTC
> Sure, let’s give that a try as a PR. 
Maybe separately it would be nice to gc.collect() in loop.close(). That’s a larger discussion though.

_Originally posted by @gvanrossum in https://github.com/python/cpython/issues/109538#issuecomment-1806842815_

**Comment by dpr-0** [comment] 2023-11-20 09:54
It did not solve RuntimeError, gc.collect() won't collect `writer`.
Here is reference count show at the end of program
```py
import asyncio
import sys
async def main():
    global writer
    reader, writer = await asyncio.open_connection("127.0.0.1", 8000)

asyncio.run(main())
print(sys.getrefcount(writer))

```
```sh
2
Exception ignored in: <function StreamWriter.__del__ at 0x101329300>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 390, in __del__
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 338, in close
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 860, in close
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
RuntimeError: Event loop is closed
```
The ref count is two. If it shows one (referenced by `sys.getrefcount`), I guess `gc.collect()` will work at the `loop.close()`.

**Comment by dpr-0** [comment] 2023-11-20 16:50
Adding `gc.collect()` at loop.close() might not solve every leak problem after reading #106684.

**Comment by gvanrossum** [comment] 2023-11-20 21:55
In general I think relying on `gc.collect()` for anything but memory reclamation is the wrong way to go.

E.g. If you have a server created with `loop.create_server()`, the way to stop is to call `svr.close()` and then `await svr.wait_closed()`. If you are creating streams, you should similarly keep track of which streams are still open, explicitly close the writer and call `writer.wait_close()`.

I don't think there's an action item for asyncio here. If you have an existing application that is too complex to implement such guidelines and you're trying to limit the damage to your production, just call `gc.collect()` in your own code before closing the loop.

If I'm missing something, please write up a proper summary of the problem and how you think it should be fixed, rather than just posting random buggy example code.

**Comment by dpr-0** [comment] 2023-11-21 13:14
I traced my code and the call stack shows `__del__` always occurs after asyncpg package code, but I can not find where the stream writer is created and where make the stream writer unreachable. It might be related to its own Cython implementation.

```sh
_check_closed (.../3.11/lib/python3.11/asyncio/base_events.py:562)
call_soon (.../3.11/lib/python3.11/asyncio/base_events.py:810)
close (.../3.11/lib/python3.11/asyncio/selector_events.py:860)
close (.../3.11/lib/python3.11/asyncio/streams.py:343)
__del__ (.../3.11/lib/python3.11/asyncio/streams.py:395) <--- suddenly happened here
_check_closed (.../3.11/lib/python3.11/asyncio/base_events.py:560)
call_soon (.../3.11/lib/python3.11/asyncio/base_events.py:810)
create_task (.../3.11/lib/python3.11/asyncio/base_events.py:462)
_ensure_future (.../3.11/lib/python3.11/asyncio/tasks.py:676)
gather (.../3.11/lib/python3.11/asyncio/tasks.py:823)
_initialize (.../pypoetry/virtualenvs/xxx/lib/python3.11/site-packages/asyncpg/pool.py:447)
_async__init__ (.../pypoetry/virtualenvs/xxx/lib/python3.11/site-packages/asyncpg/pool.py:409)
__aenter__ (.../pypoetry/virtualenvs/xxx/lib/python3.11/site-packages/asyncpg/pool.py:985)
```
> E.g. If you have a server created with loop.create_server(), the way to stop is to call svr.close() and then await svr.wait_closed(). If you are creating streams, you should similarly keep track of which streams are still open, explicitly close the writer and call writer.wait_close().
> 
> I don't think there's an action item for asyncio here. 

After reading asyncio source code, I agree.

> If I'm missing something, please write up a proper summary of the problem and how you think it should be fixed, rather than just posting random buggy example code.

Sorry for the unclear problem description.

**Comment by kumaraditya303** [comment] 2024-06-23 13:50
The problem is unclear to me, please post a new issue with details and a reproducer without third party dependencies. Also relying on gc is a bad idea in general.

**Closed as not planned by kumaraditya303** 2024-06-23 13:50 UTC
Labels: topic-asyncio
