### ISSUE TITLE
Extra space in Py_BuildValue("( )") leads to SystemError: Unmatched paren in format

### ISSUE THREAD

**Issue by dmitry-kabanov** [python/cpython#110032] opened 2023-09-28 16:03 UTC
# Bug report

### Bug description:

I am using Python C API to embed Python.
I need to instantiate an object of a class without a constructor.

I used this code:
```c
pClass = PyObject_GetAttrString(pModule, class);
pInitArgs = Py_BuildValue("( )");
pInstance = PyEval_CallObject(pClass, pInitArgs);
```
(there is a space between parentheses in `Py_BuildValue`, and received `SystemError: Unmatched paren in format`. When I remove the space character, it works.

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment] 2023-09-28 18:02
Hi, thanks for the report!

This is handeled by:

```c
static Py_ssize_t
countformat(const char *format, char endchar)
{
    Py_ssize_t count = 0;
    int level = 0;
    while (level > 0 || *format != endchar) {
        switch (*format) {
        case '\0':
            /* Premature end */
            PyErr_SetString(PyExc_SystemError,
                            "unmatched paren in format");
            return -1;
        case '(':
        case '[':
        case '{':
            if (level == 0) {
                count++;
            }
            level++;
            break;
        case ')':
        case ']':
        case '}':
            level--;
            break;
        case '#':
        case '&':
        case ',':
        case ':':
        case ' ':
        case '\t':
            break;
        default:
            if (level == 0) {
                count++;
            }
        }
        format++;
    }
    return count;
}
```

The docs never mention `"( )"` case, only:

```
Py_BuildValue("()")                      ()
```

What did you expect to happen? The same as `()`, better error message, or something else?

**Comment by ronaldoussoren** [comment] 2023-09-28 18:19
[The documentation](https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue) mentions that spaces are ignored in the format strings, but not within format units.  Given the explanation of the list of units this means that spaces within a tuple (or list) definition are not ignored.

If my interpretation is correct this is not a bug.

**Comment by serhiy-storchaka** [comment] 2023-09-28 20:06
@sobolevn, no, it is raised by
```c
     if (**p_format != endchar) {
        Py_DECREF(v);
        PyErr_SetString(PyExc_SystemError,
                        "Unmatched paren in format");
        return NULL;
    }
```
in `do_mktuple`.

Whitespaces are usually ignored inside parentheses, except whitespaces before a closing parenthesis.

**Comment by serhiy-storchaka** [comment] 2023-09-29 07:31
It is a duplicate of #84489.

**Closed as not planned by serhiy-storchaka** 2023-09-29 07:31 UTC
Labels: type-bug, topic-C-API
