### ISSUE TITLE
Intermittent regression in test_asyncio .. test_subprocess_shell since Python 3.11

### ISSUE THREAD

**Issue by fancidev** [python/cpython#101922] opened 2023-02-14 23:14 UTC
### Background

I run a daily continuous integration test of `python -m test.test_asyncio` for Python 3.7 through 3.11 on Linux, MacOS, and Windows on GitHub Actions.

### Issue

Since Python 3.11, the following test intermittently fails on MacOS: (see, for example, [Python-3.11-PySide6-macos-latest](https://github.com/fancidev/qtinter/actions/runs/4164520715/jobs/7238079801#step:4:27))

```
python -m test.test_asyncio
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.11.1/x64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.11.1/x64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.1/x64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.1/x64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.1/x64

...

======================================================================
FAIL: test_subprocess_shell (test.test_asyncio.test_events.SelectEventLoopTests.test_subprocess_shell)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_asyncio/test_events.py", line 1814, in test_subprocess_shell
    self.assertEqual(proto.data[1].rstrip(b'\r\n'), b'Python')
AssertionError: b'' != b'Python'

----------------------------------------------------------------------
Ran 2339 tests in 75.968s

FAILED (failures=1, skipped=80)
```

### Observations

I note that:
- This error *only* occurs on MacOS and *only* occurs with Python 3.11. That is, it never happened on Python 3.7 through 3.10 (regardless of OS), and it never happened on Linux or Windows (regardless of Python version).
- This error can happen with `SelectEventLoopTests`, `KqueueEventLoopTests`, and `PollEventLoopTests`. This indicates the error is not related to the specific polling mechanism, which makes sense because it tests subprocess shell.

### Analysis

I see asyncio's subprocess related code is modified in Python 3.11. But I'm unable to tell whether/how those modifications may cause the observed regression.

### Impact

I don't use asyncio's subprocess functionality myself. So I report this error just for good order.

I wonder if you have observed similar error in your Continuous Integration tests?

**Comment by kumaraditya303** [comment] 2023-02-15 10:20
Duplicate of https://github.com/python/cpython/issues/100133

The fix is present in 3.11.2. @fancidev You need to upgrade to 3.11.2.

**Closed as not planned** 2023-02-19 23:34 UTC
Labels: type-bug, topic-asyncio, OS-mac, stdlib, pending
