### ISSUE TITLE
Frozen re.compile behaves differently from re imported from PATH, build error when re is included

### ISSUE THREAD

**Issue by brandonkimdh** [python/cpython#101312] opened 2023-01-25 05:37 UTC
# Bug report

Summary:
With stdlib `re` included in Tools/scripts/freeze_modules.py as in the following snippet
```
    ('stdlib - startup, with site', [
        '_collections_abc',
        '_sitebuiltins',
        'genericpath',
        'ntpath',
        'posixpath',
        # We must explicitly mark os.path as a frozen module
        # even though it will never be imported.
        f'{OS_PATH} : os.path',
        'os',
        'site',
        'stat',
        '<re.*>',
        ]),
```
 the following build error occurs
```
./python.exe -E -S -m sysconfig --generate-posix-vars ;\
	if test $? -ne 0 ; then \
		echo "generate-posix-vars failed" ; \
		rm -f ./pybuilddir.txt ; \
		exit 1 ; \
	fi
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dhk/Desktop/cpython/Lib/sysconfig.py", line 851, in <module>
    _main()
  File "/Users/dhk/Desktop/cpython/Lib/sysconfig.py", line 839, in _main
    _generate_posix_vars()
  File "/Users/dhk/Desktop/cpython/Lib/sysconfig.py", line 466, in _generate_posix_vars
    import pprint
  File "/Users/dhk/Desktop/cpython/Lib/pprint.py", line 38, in <module>
    import dataclasses as _dataclasses
  File "/Users/dhk/Desktop/cpython/Lib/dataclasses.py", line 5, in <module>
    import inspect
  File "/Users/dhk/Desktop/cpython/Lib/inspect.py", line 143, in <module>
    import linecache
  File "/Users/dhk/Desktop/cpython/Lib/linecache.py", line 11, in <module>
    import tokenize
  File "/Users/dhk/Desktop/cpython/Lib/tokenize.py", line 39, in <module>
    blank_re = re.compile(br'^[ \t\f]*(?:[#\r\n]|$)', re.ASCII)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen re>", line 227, in compile
  File "<frozen re>", line 294, in _compile
  File "<frozen re._compiler>", line 743, in compile
  File "<frozen re._parser>", line 980, in parse
  File "<frozen re._parser>", line 455, in _parse_sub
  File "<frozen re._parser>", line 863, in _parse
  File "<frozen re._parser>", line 455, in _parse_sub
  File "<frozen re._parser>", line 568, in _parse
  File "<frozen re._parser>", line 361, in _class_escape
re.error: bad escape \n at position 16
generate-posix-vars failed
make: *** [pybuilddir.txt] Error 1
```

`Python.exe` manages to build even with the error and I was able to reproduce the `re.error` multiple times when trying to run the following snippet:
`blank_re = re.compile(br'^[ \t\f]*(?:[#\r\n]|$)', re.ASCII)`

This error only occurs when the `re` module is frozen and does not occur when `re` is imported normally from Lib PATH.

# Your environment

- CPython versions tested on: 3.11.1
- Operating system and architecture: Apple M1 MBP, macOS 13.0 (22A380)

**Comment by FFY00** [comment] 2023-04-03 15:09
@kumaraditya303 would be interested in looking at this?

**Comment by kumaraditya303** [comment] 2023-04-03 17:33
It works without any error on current main on Linux. This might be macos specific so out of my reach.

**Comment by erlend-aasland** [comment] 2023-04-28 09:02
I'm unable to reproduce on `main` (M1 MBP, macOS 13.3).

**Comment by erlend-aasland** [comment] 2023-04-28 09:15
Also unable to reproduce on `3.11`. Suggesting closing as outdated.

**Closed as not planned** 2023-04-28 10:27 UTC
Labels: type-bug, OS-mac, build

**Comment by conradjones** [comment] 2024-01-01 04:31
I can reproduce on "v3.12.1" on both linux and Mac,  it does not occur on master branch.
