### ISSUE TITLE
subprocess makes environment blocks with duplicate keys on Windows

### ISSUE THREAD

**Issue by c6a16194-fbe2-452d-ab7b-5a02c5e92e91** [python/cpython#91018] opened 2022-02-26 04:19 UTC
BPO | [46862](https://bugs.python.org/issue46862)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-26.04:19:39.329>
labels = ['type-bug', '3.9', '3.10', '3.11', 'library', 'OS-windows']
title = 'subprocess makes environment blocks with duplicate keys on Windows'
updated_at = <Date 2022-02-26.06:07:22.207>
user = 'https://bugs.python.org/benrg'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-26.06:07:22.207>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2022-02-26.04:19:39.329>
creator = 'benrg'
dependencies = []
files = []
hgrepos = []
issue_num = 46862
keywords = []
message_count = 3.0
messages = ['414068', '414074', '414075']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'benrg', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46862'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by zooba** [comment] 2022-08-25 19:03
Duplicate of #87868

**Closed as not planned by zooba** 2022-08-25 19:03 UTC
Labels: type-bug, OS-windows, stdlib, 3.11, 3.10, 3.9 (EOL)
