### ISSUE TITLE
Avoid temporary `varargs` tuple creation in argument passing

### ISSUE THREAD

**Issue by accec968-4cc5-4665-bf48-0da6b8042d0e** [python/cpython#90370] opened 2021-12-31 10:05 UTC
BPO | [46212](https://bugs.python.org/issue46212)
--- | :---
Nosy | @larryhastings, @pablogsal, @isidentical, @erlend-aasland, @colorfulappl
PRs | <li>python/cpython#30312</li>
Files | <li>[bench-print.py](https://bugs.python.org/file50533/bench-print.py "Uploaded as text/plain at 2021-12-31.10:18:07 by @colorfulappl")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-31.10:05:47.113>
labels = ['3.11', 'expert-argument-clinic', 'performance']
title = 'Avoid temporary `varargs` tuple creation in argument passing'
updated_at = <Date 2022-01-21.14:06:02.177>
user = 'https://github.com/colorfulappl'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-21.14:06:02.177>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Argument Clinic']
creation = <Date 2021-12-31.10:05:47.113>
creator = 'colorfulappl'
dependencies = []
files = ['50533']
hgrepos = []
issue_num = 46212
keywords = ['patch']
message_count = 6.0
messages = ['409412', '409413', '409414', '409659', '411129', '411130']
nosy_count = 5.0
nosy_names = ['larry', 'pablogsal', 'BTaskaya', 'erlendaasland', 'colorfulappl']
pr_nums = ['30312']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue46212'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-126064

**Comment by skirpichev** [comment] 2024-10-26 05:19
It seems #30312 was abandoned by author.  I'll continue this work.

**Comment by skirpichev** [comment] 2024-10-28 08:14
#126064 is ready for review (partially address issue)

**Comment by skirpichev** [comment] 2024-10-31 11:29
@erlend-aasland, I'm not sure we can mark this a fixed issue.

The merged pr covers only part of the original proposal (e.g. it doesn't work for the OP example with print()).

**Comment by serhiy-storchaka** [comment] 2024-11-06 08:36
I planned to came to this issue in few steps:

1. Current #122945.
2. Move the code for var-positional parameter to a separate converter (this is not easy, because it needs more parameters).
3. Split that converter into two converters -- 'tuple' and 'array' to support different representations.

There may be other intermediate steps. I tried to do this in one step, but it was too complicated.

Now, #126064 created conflicts with #122945. I spent a day for this, and see a light at the end of tunnel, but the simplest way to resolve conflict is to revert #126064. Then merge #122945, then continue the initial plan. This will take a time.

Alternatively, I can fuse all these steps in #122945, but the result will be larger and _very dirty_, because I would need to use dirty tricks like using globals to pass values of local variables between function calls in three or four different modules.

**Comment by erlend-aasland** [comment] 2024-11-06 08:41
Reverting #126064 will also mean reverting #126235. Are there any others that would need reverting, @skirpichev?

**Comment by skirpichev** [comment] 2024-11-06 08:53
> Reverting https://github.com/python/cpython/pull/126064 will also mean reverting https://github.com/python/cpython/pull/126235.

Not necessary.  Reverting https://github.com/python/cpython/pull/126064 will just introduce some performance regression for converted functions.  But as @serhiy-storchaka planned to address this issue In The Right Way - this will be eventually fixed.

> Are there any others that would need reverting

None, as far as I know.

**Comment by erlend-aasland** [comment] 2024-11-06 09:09
Sounds good. Serhiy, please go ahead.

**Comment by skirpichev** [comment] 2024-11-06 09:24
(Given the size (few lines) of https://github.com/python/cpython/pull/126064, I don't see big problem to resolve merge conflicts.  I'll try to do this.  Serhiy, feel free to ignore these efforts.)

**Comment by erlend-aasland** [comment] 2024-11-06 09:27
> (Given the size (few lines) of #126064, I don't see big problem to resolve merge conflicts. I'll try to do this. Serhiy, feel free to ignore these efforts.)

IMO, this would be the best option; if we can avoid the revert churn that would be great.

**Comment by skirpichev** [comment] 2024-11-06 09:31
So, if this is not urgent, give me a day.

**Closed as completed** 2024-11-08 06:24 UTC
Labels: performance, topic-argument-clinic, 3.14

**Comment by erlend-aasland** [comment] 2024-11-08 11:38
Thanks, @colorfulappl, for the proposal and initial work; thanks Serhiy and Sergey for the PRs 🍰 👏 🥳
