### ISSUE TITLE
Thread Naming Issue in Python 3.11 with format() Function

### ISSUE THREAD

**Issue by IamGroot1234567** [python/cpython#109643] opened 2023-09-21 09:58 UTC
# Bug report

### Bug description:

```import threading

def hello():
    # The use of format() function in Python 3.11 leads to thread naming issues
    print("hello() -- executed by: {}".format(threading.Thread().name))

def hi(val):
    print("Hi(),{} -- executed by: {}".format(val, threading.current_thread().name))

print("Program execution started:", threading.current_thread().name)

t1 = threading.Thread(target=hello)
t2 = threading.Thread(target=hi, args=("TR",))

t1.start()
t2.start()

print("\nProgram execution Ended:", threading.current_thread().name)

```
Expected Output (Python 3.11):

Program execution started: MainThread
hello() -- executed by: Thread-1
Hi(),TR -- executed by: Thread-2
Program execution Ended: MainThread

Actual Output (Python 3.11):

Program execution started: MainThread
hello() -- executed by: Thread-3
Hi(),TR -- executed by: Thread-2 (hi)

Program execution Ended: MainThread

Note: If I remove the format function from hello() then will get expected output.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment] 2023-09-21 18:02
I'm going to close this as not a bug. @IamGroot1234567 : If you have additional usage questions, please ask them on https://discuss.python.org/c/users/7

**Closed as not planned by ericvsmith** 2023-09-21 18:02 UTC
Labels: type-bug
