### ISSUE TITLE
TK askopenfilenames, SVGs, Windows 10 Explorer Issue

### ISSUE THREAD

**Issue by lewi0622** [python/cpython#107869] opened 2023-08-11 15:46 UTC
# Bug report

## Checklist
- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [ ] I have searched the CPython issue tracker, and am confident this bug has not been reported before

## A clear and concise description of the bug
Selecting an SVG file using askopenfilenames, in Windows 10, with explorer dialog box options set to show "Icons", results in the selected file being locked inside a COM Surrogate process. This does not happen when the explorer dialog box is set to show only "Details" (the same problem occurs if the "Preview Pane" is used.) Simply rendering the SVG in the TK explorer window locks it away.

  ```py
  from tkinter.filedialog import askopenfilenames

input_files = askopenfilenames()
  ```
This issue occurs even when just viewing the files, a file need not be selected. If the SVG files render as icons or in the preview pane in the TK explorer window, they will be locked even if you cancel or X out of the window.
This issue does not occur when viewing the file in a standard Windows explorer window, without using TK.
Default application to open SVG on Windows 10 was verified to make no difference (Edge, Chrome, Affinity Designer were set as default.)

# Your environment
- CPython versions tested on: 3.10.4
- Operating system and architecture: Windows 10 Version 22H2 (OS Build 19045.3208)
- When TK dialog opens, make sure that the explorer dialog box is set to one of the "Icons" options so that the file is being rendered in the window.

**Comment by chrstphrchvz** [comment] 2023-08-20 20:45
More information might be needed to reproduce this. To my knowledge, Windows 10 itself does not provide SVG thumbnails/previews. Are you using PowerToys or similar extension which provides that functionality?

Currently, I am inclined to think this is not specifically a Tkinter issue, since `askopenfilenames()` relies on the Tcl/Tk command `tk_getOpenFile` to actually display a file dialog.

**Comment by serhiy-storchaka** [comment] 2024-06-24 18:03
Closed as not a Tkinter issue.

**Closed as not planned by serhiy-storchaka** 2024-06-24 18:03 UTC
Labels: type-bug, topic-tkinter
