### ISSUE TITLE
datetime_strptime is 'NoneType' when restart cpython

### ISSUE THREAD

**Issue by marin-man** [python/cpython#117914] opened 2024-04-16 02:58 UTC
# Bug report

### Bug description:

When executing the following code, it will appear `TypeError: 'NoneType' object is not callable`
```c++
#include "Python.h"
#include <iostream>

void py_test() {
    Py_Initialize();
    auto pName = PyUnicode_DecodeFSDefault("datetime");
    auto pModule = PyImport_Import(pName);
    auto datetime = PyObject_GetAttrString(pModule, "datetime");
    auto strptime = PyObject_GetAttrString(datetime, "strptime");
    auto args = PyTuple_New(2);
    PyTuple_SetItem(args, 0, PyUnicode_FromString("2000-01"));
    PyTuple_SetItem(args, 1, PyUnicode_FromString("%Y-%m"));
    auto res = PyObject_CallObject(strptime, args);
    PyObject_Print(res, stdout, 0);
    Py_Finalize();
}

int main() {
    py_test();
    std::cout << "========" << std::endl;
    py_test();
    return 0;
}
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

### Linked PRs
* gh-117915

**Comment by serhiy-storchaka** [comment] 2024-04-16 09:04
Is it Python 3.11 only issue? Is it reproduced in 3.12 or in the main branch?

**Comment by marin-man** [comment] 2024-04-16 10:16
> Is it Python 3.11 only issue? Is it reproduced in 3.12 or in the main branch?

Python 3.12 and main branch seems to be worse, it crashes on import after reboot.
```c++
#include "Python.h"
#include <iostream>

void py_test() {
  Py_Initialize();
  auto pName = PyUnicode_DecodeFSDefault("datetime");
  auto pModule = PyImport_Import(pName);
  Py_Finalize();
}

int main() {
  py_test();
  std::cout << "========" << std::endl;
  py_test();
  return 0;
}
```
```bash
========
a.out(39618,0x7ff8589827c0) malloc: *** error for object 0x10bffedc0: pointer being freed was not allocated
a.out(39618,0x7ff8589827c0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    39618 abort      ./a.out
```

**Comment by serhiy-storchaka** [comment] 2024-04-16 11:21
If the bug is not 3.11 specific, the PR should be created for the `main` branch.

**Comment by ericsnowcurrently** [comment] 2024-06-12 17:00
This appears to be a duplicate of gh-71587.  If I'm mistaken, please re-open.

**Closed as completed by ericsnowcurrently** 2024-06-12 17:00 UTC
Labels: type-bug
