### ISSUE TITLE
Date formats in help messages of argparse

### ISSUE THREAD

**Issue by d5ac8472-f570-47ad-aab3-d5b909053746** [python/cpython#89149] opened 2021-08-23 23:22 UTC
BPO | [44986](https://bugs.python.org/issue44986)
--- | :---
Nosy | @rhettinger, @Julian, @SengerM
PRs | <li>python/cpython#27923</li>
Files | <li>[deleteme.py](https://bugs.python.org/file50232/deleteme.py "Uploaded as text/plain at 2021-08-23.23:22:20 by @SengerM")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-08-23.23:22:20.648>
labels = ['type-feature', 'library', '3.11']
title = 'Date formats in help messages of argparse'
updated_at = <Date 2021-09-03.00:59:17.771>
user = 'https://github.com/SengerM'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-03.00:59:17.771>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-08-23.23:22:20.648>
creator = 'mail.de.senger'
dependencies = []
files = ['50232']
hgrepos = []
issue_num = 44986
keywords = ['patch']
message_count = 3.0
messages = ['400183', '400246', '400327']
nosy_count = 5.0
nosy_names = ['rhettinger', 'Julian', 'python-dev', 'paul.j3', 'mail.de.senger']
pr_nums = ['27923']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44986'
versions = ['Python 3.11']
```

</p></details>

**Comment by encukou** [comment] 2024-04-15 15:26
The proposed change is not backwards-compatible. You can currently do something like this:
```
import argparse

parser = argparse.ArgumentParser(prog='foo')
parser.add_argument('--arg', help='Some argument to %(prog)r (note the quotes)')
parser.add_argument('--debug', help='For the record, the available params are %s')

print(parser.format_help())
```
(These particular examples may not be useful, but we can't simply assume that no one found anything useful along these lines.)

Rather than guess what the programmer meant, it would be better to tell them more clearly what is wrong: catch the `(TypeError, ValueError)` and add a [note](https://docs.python.org/3/library/exceptions.html#BaseException.add_note) saying `Hint: escape % as %% in help text`.
I'll add that to my TODO list :)

**Comment by serhiy-storchaka** [comment] 2024-09-28 16:09
This is a duplicate of #65865.

**Comment by serhiy-storchaka** [comment] 2024-10-02 13:43
#124899 adds checks for invalid help arguments to `add_argument()`, `add_subparsers()` and `add_parser()`.

**Closed as not planned** 2024-10-12 10:22 UTC
Labels: type-feature, stdlib, 3.11
