### ISSUE TITLE
Not obvious that locale.LC_MESSAGES may not exist sometimes (e.g. on Windows)

### ISSUE THREAD

**Issue by 8946e915-3f93-4dfb-9e92-3cdc1156e045** [python/cpython#88553] opened 2021-06-10 23:27 UTC
BPO | [44387](https://bugs.python.org/issue44387)
--- | :---
Nosy | @jdevries3133
Files | <li>[lc_messages_not_exist.png](https://bugs.python.org/file50102/lc_messages_not_exist.png "Uploaded as image/png at 2021-06-11.07:21:26 by richardmines91"): Proof that locale.LC_MESSAGES may not exist in Python</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-10.23:27:24.102>
labels = ['3.7', '3.8', '3.9', '3.10', '3.11', 'type-feature', 'docs']
title = 'Not obvious that locale.LC_MESSAGES may not exist sometimes (e.g. on Windows)'
updated_at = <Date 2021-06-11.07:21:26.140>
user = 'https://bugs.python.org/richardmines91'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-11.07:21:26.140>
actor = 'richardmines91'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-06-10.23:27:24.102>
creator = 'richardmines91'
dependencies = []
files = ['50102']
hgrepos = []
issue_num = 44387
keywords = []
message_count = 4.0
messages = ['395588', '395590', '395591', '395607']
nosy_count = 3.0
nosy_names = ['docs@python', 'jack__d', 'richardmines91']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44387'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by cdfarrow** [comment] 2024-04-24 07:23
Duplicate of gh-100766, which was fixed on Jan 5, 2023.
I'm suggesting formatting the information as a note in this [PR](https://github.com/python/cpython/pull/118217)

**Closed as not planned** 2024-04-24 08:52 UTC
Labels: type-feature, docs, 3.11, 3.10, 3.9 (EOL), 3.8 (EOL), 3.7 (EOL)
