### ISSUE TITLE
PyEval_SetTrace not set frame->f_trace to true

### ISSUE THREAD

**Issue by leandrogmuller** [python/cpython#106483] opened 2023-07-06 15:14 UTC
Hello.
I'm trying to change f_lineno to jump on debug by Cpython.
But frame->f_trace isn't true value, 
I started the trace by PyEval_SetTrace, but the when I try to change return is not possible.

PyObject_SetAttrString((PyObject*)frame, "f_lineno", line);
f_lineno can only be set by a trace function

Python 3.11.4

**Comment by gaogaotiantian** [comment] 2023-07-06 17:11
Could you show the code you are using? Are you in your tracing function already?

Setting trace function with `PyEval_SetTrace` will not trigger the tracing function(the callback you assigned) immediately. You need to assign the callback to `frame.f_trace` to trigger tracing function in current frame.

Could you put together a minimum reproducible example? Are you able to reproduce it with `sys.settrace`?

**Comment by iritkatriel** [comment] 2023-11-26 11:44
As @gaogaotiantian , we need full instructions on how to reproduce the problem you are seeing. I am marking this as pending, which means we will close it soon unless you can follow up with more information.

**Comment by gaogaotiantian** [comment] 2024-02-04 23:59
Close due to no further information.

**Closed as not planned by gaogaotiantian** 2024-02-04 23:59 UTC
Labels: type-bug, interpreter-core, pending
