### ISSUE TITLE
Cannot pause asyncio transport immediately

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [python/cpython#103607] opened 2023-04-18 10:38 UTC
# Bug report

When creating a asyncio transport/protocol pair, one might want to call `transport.pause_reading()` immediately when `protocol.connection_made()` is called. This is currently not possible. The call to `pause_reading()` is ignored, and reading commences nonetheless.

This is problematic, because there is no other place where the transport can be immediately paused, especially when the protocol is created through `loop.create_server`.

As a remedy, I would suggest guarding
https://github.com/python/cpython/blob/ece20dba120a1a4745721c49f8d7389d4b1ee2a7/Lib/asyncio/selector_events.py#L931-L932
with `if not self._paused:`. There might be other places where this is needed, for other event loops.

### Linked PRs
* gh-17425
* gh-103918

**Comment by gvanrossum** [comment] 2023-04-20 03:40
@LasseBlaauwbroek This makes sense, could you make a PR (with tests, please)?

**Comment by arhadthedev** [comment] 2023-04-20 10:10
gh-17425 is a PR from gh-76002 closed as a duplicate of this issue.

**Closed as completed** 2023-04-27 10:32 UTC
Labels: type-bug, topic-asyncio, stdlib
