### ISSUE TITLE
 Opening pickled files saved in Google Drive occasionally causes jupyter notebook to hang

### ISSUE THREAD

**Issue by davidshumway** [python/cpython#98185] opened 2022-10-11 16:06 UTC
# Bug report

Cross-posted on Google Colab tools issue tracker but not getting any response there: (https://github.com/googlecolab/colabtools/issues/3136).

Is this a pickle or Google Colab or jupyter issue?

Occasionally, opening pickled files saved in Google Drive causes the jupyter notebook to hang. The issue is sporadic. Sometimes the issue happens, other times it does not. Opening 10 pickled files, 1/10 may cause the loading process to hang (and it's not always the first pickled file that causes the issue). But then the same file causes the issue over and over again, even after restarting the kernel. The pickled files were saved at different times but were all saved from within the Colab environment and all saved to Google Drive. None of the files were saved when using the GPU in Colab. The issue happens both when running with and without the GPU. The pickled files are typically less than 2MB. When the issue occurs, the RAM usage always spikes up to nearly 100% as depicted by the Colab RAM usage chart. The notebook is then unresponsive and either times out and the kernel dies or hangs indefinitely. The only solution then is to restart the kernel and try again. Reloading the page doesn't help. Using `touch` on the pickled files does not help. Loading the pickled files in a loop with a sleep doesn't help (e.g. `time.sleep(2)`). Using various parameters within `pickle.load` and `open(...)` also does not seem to help, e.g. opening with `buffering=0` or using `encoding='bytes'` in `pickle.load()`. I haven't tried using a kill command to kill the process after a certain number of seconds of trying to open the pickled file. Any use in going down that path?

# Your environment

- CPython versions tested on: Google Colab
- Operating system and architecture: Google Colab

**Comment by zware** [comment] 2022-10-11 16:23
You'll need to reproduce the issue without any third-party addons before anything can be done here.  It sounds to me like you're probably pickling something that doesn't actually support pickling, and the default attempt causes the issues you're seeing, or that there's a bug in the pickling support for something you're pickling.  There's nothing here to indicate an issue in `pickle` itself, so I'm going to go ahead and close the issue.  If you can provide a reproducer later on, we can reopen the issue.

**Closed as not planned by zware** 2022-10-11 16:23 UTC
Labels: type-bug

**Comment by davidshumway** [comment] 2022-10-11 16:26
> It sounds to me like you're probably pickling something that doesn't actually support pickling

The pickled files are just pandas dataframes with m-by-n rows of some test results.

**Comment by davidshumway** [comment] 2022-10-11 17:00
Is there any way to troubleshoot this issue from the pickle side? I think I've tried all of the parameters for `pickle.load` and nothing helped so far.

**Comment by JelleZijlstra** [comment] 2022-10-11 17:10
Since you're seeing a hang, I would try some tool to hook into the running process while it's "hanging" to see what it's doing. For example, on Linux you can do `gdb -p` or use `strace`.

**Comment by davidshumway** [comment] 2022-10-11 19:11
Unfortunately since this is running within the Google Colab notebook environment, I'm not sure if it would be possible to use `gdb` or `strace`. As I do not have a "Colab Pro" account, I thus don't have access to (much of) a shell. I say much of because some "magic" commands are available such as `!` and `%` (e.g. `!ls` and `%cd`, respectively).

**Comment by pochmann** [comment] 2022-10-11 20:26
You say "strings and ints" and "default types", but your list shows `object`. I'm not familiar with Pandas, but doesn't that mean they can be *anything*?

Maybe try logging the progress by adding a column of  objects that print their value during pickling/unpickling?
```
import pickle

class Log:
    def __init__(self, value):
        self.value = value
    def __getstate__(self):
        print('pickling', self.value)
        return self.value
    def __setstate__(self, value):
        print('unpickling', value)

b = pickle.dumps(list(map(Log, range(5))))
pickle.loads(b)
```
Output ([Try it online!](https://tio.run/##ZU9LCsMgEN17CndRCNmUQin0Br2DmGRipUZFx0JPb00ixdK3nDfv59/4cPZ08SFnvXoXkHo9PQ0QMhkZI707dSW0YIaFCqGtRiFYBLP09CVNAn7QG7brsB/p7SAbpQKMKBGqupH5oC2ybs/VVnV9Y8S/XwEwBdtQjXf89f5vViOSbUKqPxlL2WPzMKfVR2Z0RLZKz8r2ngZpFbAzLyD1zTg5RzbynD8 "Python 3.8 (pre-release) – Try It Online")):
```
pickling 0
pickling 1
pickling 2
pickling 3
pickling 4
unpickling 0
unpickling 1
unpickling 2
unpickling 3
unpickling 4
```

**Comment by davidshumway** [comment] 2022-10-11 20:55
> You say "strings and ints" and "default types", but your list shows object. I'm not familiar with Pandas, but doesn't that mean they can be anything?

I'm not too familiar with Pandas but the objects in this case are all strings or in one case np.nan. What's odd is that the same pickled files will 1/5 times have issues unpickling whereas 4/5 there's no issue. And there's no change to the files in the meantime. The only thing changing is presumably the Google Colab and Drive environment which is I assume is based on some random containers which Google provisions for each "session".

> Maybe try logging the progress by adding a column of objects that print their value during pickling/unpickling?

Thanks for this suggestion. The next session where this error occurs I will give it a try. (Lately it's been happening once or twice per day).

To give a better example of what's contained in the pickled files, here's a description of the unpickled dataframe.

Numeric values:

|index|src tr \#|tgt tr \#|tgt frac|tgt test \#|rmse|r2|pr0|pr1|rec0|rec1|acc|mse|rrmse|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|count|4500\.0|4500\.0|4500\.0|4500\.0|4500\.0|4500\.0|4500\.0|4500\.0|4500\.0|4500\.0|4500\.0|4500\.0|4500\.0|
|mean|119\.90444444444445|119\.90444444444445|0\.51|178\.11111111111111|0\.8305272161311917|-0\.225988469609766|0\.8438324444444445|0\.2614306666666667|0\.8489577777777777|0\.23656822222222224|0\.8158064444444444|0\.7241024444444445|0\.394435725679965|
|std|72\.90292441550757|72\.90292441550757|0\.2886494677383031|35\.50807503727473|0\.2685029317448674|2\.141283931578567|0\.1767210494866244|0\.2733626157028889|0\.2729436988100488|0\.3188832689924921|0\.1392757745182627|0\.6915008265707696|0\.11114676994912934|
|min|4\.0|4\.0|0\.02|97\.0|0\.4333018010682446|-109\.1014468111513|0\.0|0\.0|0\.0|0\.0|0\.219|0\.188|0\.1743719807456052|
|25%|59\.0|59\.0|0\.26|162\.0|0\.7020728659363487|-0\.42286096675315765|0\.857|0\.0|0\.872|0\.0|0\.784|0\.493|0\.3391333471533349|
|50%|116\.0|116\.0|0\.51|185\.0|0\.7849742676134606|0\.055979222387662564|0\.909|0\.2|0\.981|0\.1|0\.875|0\.616|0\.4099757514428908|
|75%|173\.0|173\.0|0\.76|208\.0|0\.9384241125082199|0\.23502212030028619|0\.922|0\.5|1\.0|0\.31|0\.914|0\.88025|0\.4594277661999485|
|max|334\.0|334\.0|1\.0|220\.0|8\.041035350428713|0\.4696006442373817|1\.0|1\.0|1\.0|1\.0|0\.929|35\.874|1\.4052912144077954|

And string-like values (noting that `model-est` is a column filled with np.nan):

|index|src|tgt|model|model-est|train\_years|test\_years|cm|
|---|---|---|---|---|---|---|---|
|count|4500|4500|4500|0|4500|4500|4500|
|unique|3|3|2|0|3|3|870|
|top|BW|BW|RF|NaN|0-1997|1998-2001|\[142   0\]
\[13  0\]|
|freq|1500|1500|2250|NaN|1500|1500|405|

**Comment by davidshumway** [comment] 2022-10-14 01:51
Just want to follow up here to note that the issue is not pickle. 

Simple copying the pickled files to /tmp or /content is also causing the notebook to become unresponsive. E.g.,

```python
!cp "/content/gdrive/MyDrive/1.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/2.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/3.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/4.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/5.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/6.pkl" /tmp # notebook hangs
```
So please go ahead and close this issue. Thanks!
