### ISSUE TITLE
bidir normalization ?

### ISSUE THREAD

**Issue by jul** [python/cpython#117960] opened 2024-04-17 06:48 UTC
# Bug report

### Bug description:

Expected : 
Given a string  in the form ">> A B A << fin" I expect normalized grapheme to be ">> A B A << fin" whatever bidir "A" "B" "fin" supports
I also expect > to NEVER look like <   p == (202E,2066,2069) (addendum : imagine I print an SQL formula on screen which is not the same one as executed ?)
I also expect a bidir ended string to not mess up with the reminder of the flow
I also expect latin alphabet to never appear RL in at least one normalized form (ex : it's a file name I must write to disk)

I don't know what I see, I don't know if it is due to my terminal (gnome-terminal) but I'm pretty sure it smells in the danish kingdom (Othello, Sheakspear)
```python
#!/usr/bin/env python3
# -*- coding: utf8 -*-

from itertools import combinations_with_replacement as cbr
from unicodedata import normalize

for p in cbr([0x200e, 0x200f, 0x061c, 0x202a, 0x202b, 0x202e, 0x202d, 0x202c, 0x2066, 0x2068, 0x2067, 0x2069], 3):
    print(",".join(map(lambda s : f"%2X" % s, p)))
    print(">>%sKenavo/*ﻢﻋ ﺎﻠﺳﻼﻣﺓ*%sKenavo%s <<fin ?==" % tuple(map(chr,p)), end="")
    s=">>%sKenavo/*ﻢﻋ ﺎﻠﺳﻼﻣﺓ*%sKenavo%s <<fin" % tuple(map(chr,p))
    print(s)
    for n in ("NFD", "NFC", "NFKD", "NFKC"):
        print(normalize(n,s))

```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by terryjreedy** [comment] 2024-04-17 07:18
Bidi text is a difficult issue.   It generally works fine on Windows, less so, I believe on Linux.  I see no obvious issues on Windows.

Questions about bugs generally should be posted first on https://discuss.python.org/c/users/7 to clarify the claims.  I do not understand most of your 'expectations' and not at all what specific errors you think you see.   Are you claiming that '>' is misprinted as '>'?  I don't see that.  I see no 'messed up' flow.  I don't know what RL is.

Each specific error claim should have a specific line of code, a copy of the output line *you* see, with a claimed error, and a proposed line that you claim is (at least more) correct.  Nearly 2200 lines of output with no annotation is not very useful.

**Comment by jul** [comment] 2024-04-17 07:33
I can isolate at least ">" shifted to "<" in ALL normalized version with 
\u202b (RLE) (RIGHT-TO-LEFT-EMBEDDING)
```
#!/usr/bin/env python3
# -*- coding: utf8 -*-

from unicodedata import normalize
print("expected output : >")
s = "\u202b>\u202b"
for n in ("NFD", "NFC", "NFKD", "NFKC"):
    print(normalize(n,s))

```

I expect a linux bug, but I will make a fast POC with simplehttpserver to check if it impacts a web server.

**Comment by jul** [comment] 2024-04-17 07:52
```
from wsgiref.util import setup_testing_defaults
from unicodedata import normalize
from wsgiref.simple_server import make_server

# A relatively simple WSGI application. It's going to print out the
# environment dictionary after being updated by setup_testing_defaults
def simple_app(environ, start_response):
    setup_testing_defaults(environ)

    status = '200 OK'
    headers = [('Content-type', 'text/plain; charset=utf-8')]

    start_response(status, headers)

    ret = [("%s > =? %s" % (n, normalize(n,"\u202b>\u202b\n"))).encode("utf-8")
           for n in ("NFD", "NFC", "NFKD", "NFKC")]
    return ret

with make_server('', 8000, simple_app) as httpd:
    print("Serving on port 8000...")
    httpd.serve_forever()

```
I don't know if it matters that it's a linux bug because on firefox my output is definitely NOT what you want (especially if you render an SQL formula)
![image](https://github.com/python/cpython/assets/130171/40c123e0-5c6d-46a0-90e1-52c8eb8e39ef)

**Comment by ronaldoussoren** [comment] 2024-04-17 09:54
See also http://unicode.org/faq/bidi.html, in particular the last part of the page:

> Q: What is Mirroring?
> Many characters have an alternate form that is a mirror image around the vertical axis. For some of these, the [direction](https://www.unicode.org/glossary/#direction) of the shape should match the [writing direction](https://www.unicode.org/glossary/#writing_direction) of the run. In a RTL run, the open parenthesis should not look like '(', but rather like ')'. In some cases, this can be achieved by character substitution on the fly. These cases are listed in the [Unicode Character Database](https://www.unicode.org/glossary/#unicode_character_database) so that layout systems can use this information.
> 
> Note that arrows, although they exist in forward and backward forms, are not included in the set of characters that should be mirrored automatically. The reason is that arrows can be used both to point to the start or end of text, but also to point to other elements on the page (for example a picture that sits in the margin). It is impossible to predict which sense was intended.

According to `unicodedata` the ">" character is mirrored. Thus showing ">" as "<" in a RTL run is IMHO not a bug.

**Comment by jul** [comment] 2024-04-17 10:28
Practicality beats purity. 
I understand norm has got a « rationality » that conflicts with mine. 

I understand this is probably not in « Cpython » backyard. I just beg for a little bit of pity in the dedals of the norms a modern web dev must know (unicode, SIP (dont ask), oauth, JWT and diameter being some of the worst I can think of) to have tools to help us protect our users from « pretty insane defaults ».

Python is my first line of defense, firefox my second and in case of attacks by homeographies (misleading representations due to unicode smartness) I would like to have a « normalization » that helps. Maybe it does not make sense, so I added a question mark in the issue.

I could write a python lib for it, but unicode scope and treacherous caveats are way beyond the scope of a single man army to make it right.

I would gladly contribute in doc (unicode howto, test cases ...) but as I said the scope of knowledge is so large I don't know where to begin and how and plead for a discussion.

**Comment by ronaldoussoren** [comment] 2024-04-17 14:51
Unicode is large and complex indeed, but that's in a large part due to the complexities of human language and scripts. It is also a lot better than what we had before (having lived through confusion caused by files with accented latin characters encoded in an unexpected single byte encoding).  Deviating from the standard will just increase the complexity (e.g. you'd have to learn slightly different rules for Python, Javascript and HTML). 

I'm closing this issue, this is not something we can change on the Python end.

**Closed as not planned by ronaldoussoren** 2024-04-17 14:51 UTC
Labels: type-bug
