### ISSUE TITLE
Path(rootdir).glob('**/*') aborts without reason. 

### ISSUE THREAD

**Issue by ntosis** [python/cpython#93286] opened 2022-05-27 12:31 UTC
**Bug report**

When I use the command Path(rootdir).glob('**/*') to find all files in a directory recursive the glob command aborts 

**Your environment**

windows 10

This is the error message, when I navigate with explorer into this directory I can see a file. 
I think glob cannot handle a very large path. 

for i in Path(rootdir).glob('**/*'):
  File "C:\Tools\Python\Python37-64\lib\pathlib.py", line 1093, in glob
    for p in selector.select_from(self):
  File "C:\Tools\Python\Python37-64\lib\pathlib.py", line 553, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "C:\Tools\Python\Python37-64\lib\pathlib.py", line 510, in _select_from
    entries = list(scandir(parent_path))
FileNotFoundError: [WinError 3] the system cannot find the path: '\\\\dek-scf35\\build_data\\sandboxes\\ntosis\\300BM\\MICROSAR\\ThirdParty\\Mcal_Tc3xx\\Supply\\MC-ISAR_AS42x_AURIX2G_TC38xA_TC39xB_BASIC_1.0.0-beta\\DemoWorkspace\\McalDemo\\TC38A\\1_ToolEnv\\2_Tresos\\.metadata\\.plugins\\org.eclipse.core.resources\\.projects\\DemoApp\\.indexes'

**Comment by eryksun** [comment] 2022-05-27 13:00
To support long normalized paths, set the registry value "LongPathsEnabled" to 1 in the key "HKLM\\System\\CurrentControlSet\\Control\\FileSystem".

**Comment by barneygale** [comment] 2022-05-27 17:43
See also: https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation

**Comment by AA-Turner** [comment] 2022-05-27 18:53
Closing as not a bug.

A

**Closed as not planned by AA-Turner** 2022-05-27 18:53 UTC
Labels: type-bug, OS-windows, stdlib

**Comment by ntosis** [comment] 2022-05-27 19:59
I think this is an issue because the software crashes and there is not a safe method to catch this error and handle it correctly. Also from PC to Pc according to administrator‘s settings a python script could have different behavior and does not have a deterministic behavior.

**Comment by eryksun** [comment] 2022-05-27 22:49
You can use an extended path to support long paths prior to Windows 10, or regardless of the "LongPathsEnabled" setting. An extended path is a type of device path that bypasses normalization when opened by Windows API functions that create and open files and directories. For an absolute drive path, prefix the path with "\\\\?\\", e.g. `pathlib.Path('//?/C:/some/long/path')`. For a UNC path, use the "\\\\?\\UNC" device, e.g. `pathlib.Path('//?/UNC/server/share/some/long/path')`. Note that pathlib's support for extended paths and device paths does have known bugs, which are already tracked and have proposed solutions.

Another workaround for long paths is to create a symlink, junction, or substitute drive that targets the directory. This is useful when you need to traverse a shallow branch (less than 260 characters) that has a deeply nested base directory. Substitute drives can be created via "subst.exe" or WinAPI [`DefineDosDeviceW()`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-definedosdevicew). Junctions can be created using CMD's `mklink` command. Symlinks can be created using `os.symlink()`, `pathlib.Path.symlink_to()`, or CMD's `mklink` command.
