### ISSUE TITLE
Cross Compile for Android and issues with PyExc_OSError

### ISSUE THREAD

**Issue by GRRedWings** [python/cpython#111225] opened 2023-10-23 18:36 UTC
# Bug report

### Bug description:

In trying to run Python 3.12 on Android. I have been cross-compiling Python for a number of years. Having built a 64bit version I am getting the following error when I try to run

I get the following error at runtime.
ImportError('dlopen failed: cannot locate symbol "PyExc_OSError" referenced by "/data/data/com.myapp/files/Python64/lib-dynload/_socket.cpython-312.so"...')

I have verified that the _socket.cpython-3.12.so exists.  I'm not really sure what other info would be beneficial for people to help me understand this error so I will start with this and happily add more details if requested.

### CPython versions tested on:

3.12

### Operating systems tested on:

Other

### Linked PRs
* gh-115780

**Comment by GRRedWings** [comment] 2023-10-27 18:37
I'm not sure if this is useful, but I did find this in the Android NDK 26 notes

[Issue 360](https://github.com/android/ndk/issues/360): thread_local variables with non-trivial destructors will cause segfaults if the containing library is dlcloseed. This was fixed in API 28, but code running on devices older than API 28 will need a workaround. The simplest fix is to stop calling dlclose. If you absolutely must continue calling dlclose, see the following table:

**Comment by mhsmith** [comment] 2024-01-16 07:49
> [Issue 360](https://github.com/android/ndk/issues/360): thread_local variables with non-trivial destructors will cause segfaults if the containing library is dlcloseed

That doesn't seem relevant, because you're not seeing a segfault.

More likely, _socket.cpython-3.12.so has not been linked against libpython3.12.so. You can check this using `readelf -d`.

**Comment by erlend-aasland** [comment] 2024-01-16 08:41
@mhsmith, based on [your comment](https://github.com/python/cpython/issues/111225#issuecomment-1893219315), can we close this issue as not-planned?

**Comment by GRRedWings** [comment] 2024-01-18 13:17
Here is the output I got from the readelf command. I'm not exactly sure how to read it, I do not see libpython3.12.so in there though, is this something I can change to link against it?


<img width="277" alt="image" src="https://github.com/python/cpython/assets/4451799/341fead9-63ea-47e5-a141-7e9bdc2f2b87">

**Comment by mhsmith** [comment] 2024-01-18 14:12
I've just remembered, I also encountered this problem when building Python 3.12 for Chaquopy. I was able to fix it with [this patch](https://github.com/chaquo/chaquopy/blob/15.0.1/target/python/patches/bldlibrary.patch), which I'll turn into a pull request in the near future.

**Comment by GRRedWings** [comment] 2024-01-18 16:19
@mhsmith  - Thanks for the update. I have tried your patch as is.  Something is still different because it's looking for python3.12.so instead of libpython3.12.so.  

I'm playing with your patch file, I'm not an expert but looking at it and trying to figure out what my build needs for some of your changes.

**Comment by mhsmith** [comment] 2024-01-19 08:13
It doesn't say it's looking for python3.12.so, it says it's looking for `-lpython3.12`, which on Android, just like Linux, should be transformed into libpython3.12.so. 

The issue is probably that this file doesn't exist in any of the `-L` directories on your command line. In particular, I see that the command line doesn't contain  `-L.`, even though that should have been assigned to BLDLIBRARY here when `ac_sys_system=Linux-android`:

https://github.com/python/cpython/blob/2305ca51448552542b2414186252123a8dc87db7/configure#L7500-L7502

**Comment by mhsmith** [comment] 2024-01-19 08:14
Are you sure you applied the whole patch?

**Comment by GRRedWings** [comment] 2024-01-19 13:12
I am pretty confident that I applied the entire patch. What I'm not sure is how I can tell if ac_sys_system is being set right.  Is there a log or anything I could put into the configure? I tried using an echo and a printf, but not having any luck.

**Comment by GRRedWings** [comment] 2024-01-19 15:27
In looking at this more, and doing a before and after, I can see that it is trying to apply the patch, I don't see errors, but the configure patch is not being applied. I will look into this and make sure the patch is being applied.  Sorry about that.

**Comment by GRRedWings** [comment] 2024-01-19 18:40
Is there anything with the patch file that you provided that would make the libpython3.12.so output file only be a link to libpython3.12.so.1.0? In 3.11 the output was a valid libpython3.12.so file which I could copy into may app  build, but this build I can not as it is only a link.

**Comment by mhsmith** [comment] 2024-01-21 11:38
I haven't looked at your build process, but maybe you're regenerating the configure script from the configure.ac file after applying the patch.

**Comment by GRRedWings** [comment] 2024-01-21 14:01
You are correct. I didn't realize the script I was using was doing an auto reconfigure, and I was applying the patch before this. Once I applied the patch in the proper place, things worked as expected.

I truly appreciate your help and time looking into this with me.

**Comment by mhsmith** [comment] 2024-01-21 14:25
That's great, but please reopen the issue, because the original bug still exists in an unpatched version of Python.

**Closed as completed** 2024-02-21 23:18 UTC
Labels: type-bug, build, OS-android

**Comment by GRRedWings** [comment] 2024-07-09 12:01
It's been a while, trying to build against 3.12.4, is this patch still needed?

**Comment by mhsmith** [comment] 2024-07-09 13:03
It's still needed on Python 3.12 and older, but it won't be needed in Python 3.13.

**Comment by GRRedWings** [comment] 2024-07-09 19:03
Perfect, I figured as much but wanted to be sure. I appreciate it.
