### ISSUE TITLE
Python 3.11 Build errors when using -j flag 

### ISSUE THREAD

**Issue by GlennButera** [python/cpython#108439] opened 2023-08-24 17:25 UTC
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

### Output from running 'python -VV' on the command line:

Python 3.11.4 (main, Aug 24 2023, 13:06:33) [Clang 14.0.0 (clang-1400.0.29.202)]

### A clear and concise description of the bug:

When building Python 3.11 on macOS Ventura 13.1 with the following command:
```
make altinstall -s -j10
```
it always fails to build with errors similar to the following (the file name can change):
```
LLVM Profile Error: Failed to write file "code-52940.profclangr": No such file or directory
```
This appears to be a parallelization error, as running the command without the `-j` option results in a successful build

**Comment by ned-deily** [comment] 2023-08-24 17:51
Please also indicate the exact `configure` command you are using and, preferably, attach a listing of the complete `configure` and `make` sequence showing the error, Thanks!

**Comment by GlennButera** [comment] 2023-08-24 18:24
The configure command that I am using is as follows:
```
./configure --prefix={{build_directory}} --enable-optimizations
```
I left out the specific build directory as I'm not sure that effects the issue

**Comment by GlennButera** [comment] 2023-08-24 18:33
As a side note, the following versions build properly using the `-j` option in the same environment:
Python 3.8.17
Python 3.9.17
Python 3.10.12

But Python 3.11.4 does not work

**Comment by ned-deily** [comment] 2023-09-04 17:40
Thanks for the additional information. This appears to be a duplicate of #101295 and is also an issue for Python 3.12. As a workaround until fixed, the error can be avoided by performing the build in two make steps, i.e. `make -s -j10 && make altinstall`, which is probably a much more common practice and might explain why this problem hasn't been reported more frequently.

**Closed as completed** 2023-09-04 17:41 UTC
Labels: type-bug, build
