### ISSUE TITLE
Create `test_termios.py`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#110380] opened 2023-10-05 08:34 UTC
# Feature or enhancement

In https://github.com/python/cpython/pull/110366 we found several bugs in `termios.c` module.
But, right now they are not tested.

I propose to add a new test file that can at least cover some regressions that are easy to do.
For example, checking error overwrite or crash from https://github.com/python/cpython/pull/110366

It is better than nothing, later people more familiar with `termios` can add more tests and infrastructure to test more advanced things.

I am working on the PR. Expect it tomorrow or something.

**Comment by AlexWaygood** [comment] 2023-10-05 08:35
Duplicate of #81002

**Closed as not planned by AlexWaygood** 2023-10-05 08:35 UTC
Labels: type-feature, tests
