### ISSUE TITLE
[3.13] Can't use `GzipFile` with previous created `fileobj`

### ISSUE THREAD

**Issue by Kludex** [python/cpython#122727] opened 2024-08-06 08:22 UTC
# Bug report

### Bug description:

This errors in 3.13 beta 4, but not on previous Python versions.

```python
import gzip
import io

with io.BytesIO() as buffer:
    gzip_file = gzip.GzipFile(mode="wb", fileobj=buffer, compresslevel=9)

    gzip_file.write(b"Hello, world!")
```

Ref.: https://github.com/encode/starlette/issues/2615

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by graingert** [comment] 2024-08-06 10:16
bisected to 58a2e0981642dcddf49daa776ff68a43d3498cee so I suspect this issue was always happening, it just wasn't logged as an unraisable exception

**Comment by graingert** [comment] 2024-08-06 10:21
I think this is working as designed because in the code you wrote the BytesIO 'buffer' is closed by the 'with' statement, and then later the GzipFIle is closed by the garbage collector the correct code is:

```python
import gzip
import io

with io.BytesIO() as buffer:
    with gzip.GzipFile(mode="wb", fileobj=buffer, compresslevel=9) as gzip_file:

        gzip_file.write(b"Hello, world!")
```

**Comment by graingert** [comment] 2024-08-07 10:41
I'm going to close this as working as designed. The downstream project has been fixed to use a `with` statement around both the BytesIO and GzipFile for deterministic cleanup

**Closed as not planned by graingert** 2024-08-07 10:41 UTC
Labels: type-bug

**Comment by Kludex** [comment] 2024-08-07 10:44
Thanks Thomas 🙏
