### ISSUE TITLE
seealso is corrupted in 3.9 or later documentation (since Apr 12th?)

### ISSUE THREAD

**Issue by e-kwsm** [python/cpython#91496] opened 2022-04-13 05:33 UTC
For example, see [subprocess](https://docs.python.org/3/library/subprocess.html):

![Screenshot from 2022-04-13 14-22-48](https://user-images.githubusercontent.com/11627708/163106360-cc4b7971-3f0d-4fd6-938d-a3e78b1d37af.png)

The both are created by sphinx 2.4.4; the former and latter are updated on Mar 17 and Apr 12, respectively.

**Comment by arhadthedev** [comment] 2022-04-13 05:49
A duplicate of gh-91483. The issue affects all pages with colored notes and seealsos.

**Closed as completed** 2022-04-13 07:37 UTC
Labels: type-bug, docs

**Comment by JulienPalard** [comment] 2022-04-13 14:57
Hi @e-kwsm it should be fixed now, thanks for the heads up!

**Comment by e-kwsm** [comment] 2022-04-14 05:53
Sorry for noise.
