### ISSUE TITLE
Remove new pyrepl "warning" on Windows

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#118628] opened 2024-05-06 05:33 UTC
# Bug report

Whenever I start the REPL on Windows, it now prints a new statement: "warning: can't use pyrepl: No module named 'readline'" and as things now, it will continue to do so indefinitely.  This is obnoxious.  This is not a warning, not something I can or should do anything about (other than switch to Linux), but a statement of fact.  Please kill it at least on Windows.  And Mac if the situation is the same (never available).  It seems useless on *nix too, though I don't care.  Just document its availability in appropriate places like we do with other things that are not available everythere.

If desired to make its use obvious, color the splash message in places.

### Linked PRs
* gh-118665

**Comment by sobolevn** [comment] 2024-05-06 07:37
I agree, this will cause a lot of confusion among devs.

**Comment by eryksun** [comment] 2024-05-06 15:10
Could someone point me to the PEP or discussion for this change?

`_pyrepl.simple_interact` tries to import `_pyrepl.readline` and `_pyrepl.unix_console`, which depend on POSIX-only `readline`, `curses`, `termios`, and `fcntl`. I see no reason that it should even be distributed in the standard library on Windows. It just ends up calling `sys._baserepl()`. Currently, the only reason I can see to include the `_pyrepl` package on Windows is that all of the pager functions were moved there, but they could be moved to a top-level `_pager` module.

Attempts to use `_pyrepl` in "Modules/main.c" and "Lib/site.py" should gracefully handle its absence. `site` can continue to try to import `_pyrepl.readline`. Maybe `_pyrepl` could be available on Windows one day. But trying to import `_pyrepl.unix_console` seems like something that should be encapsulated in the implementation. In "Modules/main.c", it can try `pymain_run_module(L"_pyrepl", 0)`, and fall back on calling `sys._baserepl()`.

**Comment by ambv** [comment] 2024-05-06 20:12
Sorry for the rough initial experience, y'all!

> Could someone point me to the PEP or discussion for this change?

The issue is https://github.com/python/cpython/issues/111201, it's still open.

As for "a PEP", this is not an API nor a language feature. This needs a PEP in the same sense that rewriting output of `python --help` did or changing the output of tracebacks did. The main visible change is multiline editing and a color prompt, and we're not removing the previous REPL at all.

The Steering Council was aware this change was coming and didn’t suggest a PEP before. Of course, if they change their mind, we’ll provide one.

> I see no reason that it should even be distributed in the standard library on Windows.

@eryksun, there's plenty of other libraries distributed on Windows that are specific to another platform like asyncio.unix_events, pty, posixpath, shutil.chown, tty, and so on.

Here, we want to remove our reliance on readline and curses during the sprints in Pittsburgh, possibly unblocking Windows support in beta 2. If that won't work, we will make sure the Windows experience is no worse than it was on Python 3.12.

In any case, this is now solved with GH-118665 landed so we can close this.

**Closed as completed by ambv** 2024-05-06 20:12 UTC
Labels: type-bug, release-blocker

**Comment by eryksun** [comment] 2024-05-06 21:00
> Sorry for the rough initial experience, y'all!
> 
> > Could someone point me to the PEP or discussion for this change?
> 
> The issue is #111201, it's still open.
> 
> As for "a PEP", this is not an API nor a language feature. This needs a PEP in the same sense that rewriting output of `python --help` did or changing the output of tracebacks did. The main visible change is multiline editing and a color prompt, and we're not removing the previous REPL at all.

I never said it needed a PEP. I was just looking for the discussion about this change, so I could understand the rational for implementing this in a way that requires distributing and attempting to use the `_pyrepl` package on Windows, why the pager functions were moved there when paging text in general isn't intrinsically related to a REPL, and what if any development plans there were for Windows in the long-term roadmap.

> @there's plenty of other libraries distributed on Windows that are specific to another platform like asyncio.unix_events, pty, posixpath, shutil.chown, tty, and so on.

I've never understood why tty and pty are distributed on Windows since trying to import them immediately fails for lack of termios, and there's pretty much no chance that anyone will ever step up to support the termios module in the standard library on Windows, though I'd love to be proven wrong there. `shutil.chown()` should only defined if `os.chown()` exists. Its existence on Windows is a mistake. The asyncio package and posixpath are different. They're both meant to be used on Windows. Trying to import unix_events deliberately fails with a clear message that it's not supported on Windows. This is all a moot point if there's a long-term roadmap to support `_pyrepl` on Windows.

**Comment by hongkilldong** [comment] 2024-11-23 15:06
This problem is still there if you run python via Py_Main on windows platfrom.
![pyrepl_warning](https://github.com/user-attachments/assets/d373b0bc-0bb5-4db7-bd24-740483869177)

**Comment by terryjreedy** [comment] 2024-11-23 17:24
"Windows 10 TH2 or later required" is a different message message from the one I reported.  I have no idea of what win10 TH2 is, but if it is an early version, and the repl requires a feature added later (to color without readline, for instance), the statement would be true and unavoidable.

**Comment by hongkilldong** [comment] 2024-11-25 15:03
It' interesting that sys.getwindowsversion() call made in embedded python reported invalid window version.

![embed_py_winver](https://github.com/user-attachments/assets/5d7de59a-8a66-40ea-bee3-9da5ff05aa24)

At the same time "normal" python correctly reported window version it's running on

![normal_py_winver](https://github.com/user-attachments/assets/54e6f8a6-4917-49c3-9c87-b5876712cb60)

That is the main cause why warning mentioned above are reported.
Reading CPython sources didn't give a answer.

**Comment by AraHaan** [comment] 2024-11-30 08:51
> It' interesting that sys.getwindowsversion() call made in embedded python reported invalid Windows version.
> 
> ![embed_py_winver](https://private-user-images.githubusercontent.com/12894312/389582937-5d7de59a-8a66-40ea-bee3-9da5ff05aa24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NTY3NDksIm5iZiI6MTczMjk1NjQ0OSwicGF0aCI6Ii8xMjg5NDMxMi8zODk1ODI5MzctNWQ3ZGU1OWEtOGE2Ni00MGVhLWJlZTMtOWRhNWZmMDVhYTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDA4NDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MDUzYjJjZDM0OWU2Y2U2ZmM3NDM0YjdhODRiNzQ3ZTg2OWVjMzdhYjhjMDY4YWY5YTUxODM4ZGEwMjg3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NbJ1WjDd-MzQjdcPOjVrNWw4QcLipJ_aZT17K9wbeYw)
> 
> At the same time "normal" python correctly reported Windows version it's running on
> 
> ![normal_py_winver](https://private-user-images.githubusercontent.com/12894312/389582289-54e6f8a6-4917-49c3-9c87-b5876712cb60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NTY3NDksIm5iZiI6MTczMjk1NjQ0OSwicGF0aCI6Ii8xMjg5NDMxMi8zODk1ODIyODktNTRlNmY4YTYtNDkxNy00OWMzLTljODctYjU4NzY3MTJjYjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDA4NDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YTNjYjM5YjAyMzc0YTgxNzMyMDc5MmMyZmE2M2IyMjk2MzM0NzExNjY1OGU4MWJiMDRhODBiZmNhZWZhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jE-12Ihw0TCUpzBNbrqiGVR6nGCuBnTO7-cl4QkIDJk)
> 
> That is the main cause why warning mentioned above is reported. Reading CPython sources didn't give a answer.

This is because the assemblies need a value for Windows 10 in the ``supportedOS`` section of the Manifest resource in the Resource Sections of the python assemblies including the c extensions to not run in ``compatibility`` mode on Windows itself under an older version of Windows. The Windows API in this case will lie to python because of this.
