### ISSUE TITLE
[TraceRefs] test_import fails with: _PyRefchain_Remove: Assertion `value == REFCHAIN_VALUE' failed.

### ISSUE THREAD

**Issue by vstinner** [python/cpython#121198] opened 2024-07-01 07:38 UTC
# Bug report

AMD64 Arch Linux TraceRefs PR build: https://buildbot.python.org/all/#/builders/82/builds/1378

```
test_basic_multiple_interpreters_reset_each (test.test_import.SinglephaseInitTests.test_basic_multiple_interpreters_reset_each) ...

python: Objects/object.c:195: _PyRefchain_Remove: Assertion `value == REFCHAIN_VALUE' failed.
Fatal Python error: Aborted

Current thread 0x00007f26bc0c0740 (most recent call first):
  File "<string>", line 54 in <module>

Extension modules: _testinternalcapi, _testmultiphase, _testcapi (total: 3)
```

**Comment by vstinner** [comment] 2024-07-01 07:42
Regression introduced by: commit b2cd54a4fb2ecdb7b1d30bda8af3314d3a32031e

```
commit b2cd54a4fb2ecdb7b1d30bda8af3314d3a32031e
Author: Eric Snow <ericsnowcurrently@gmail.com>
Date:   Mon May 6 22:21:51 2024 -0600

    gh-117953: Always Run Extension Init Func in Main Interpreter First (gh-118157)
    
    This change makes sure all extension/builtin modules have their init function run first by the main interpreter before proceeding with import in the original interpreter (main or otherwise).  This means when the import of a single-phase init module fails in an isolated subinterpreter, it won't tie any global state/callbacks to the subinterpreter.
```

cc @ericsnowcurrently @pablogsal

**Comment by ericsnowcurrently** [comment] 2024-07-01 17:04
Duplicate of gh-121110.

**Closed as completed by ericsnowcurrently** 2024-07-01 17:04 UTC
Labels: type-bug, tests, topic-subinterpreters
