### ISSUE TITLE
Better tp_version_tag overflow checks in specializer

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#89811] opened 2021-10-28 14:53 UTC
BPO | [45648](https://bugs.python.org/issue45648)
--- | :---
Nosy | @markshannon, @Fidget-Spinner
PRs | <li>python/cpython#29272</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-28.14:53:27.764>
labels = ['3.11']
title = 'Better tp_version_tag overflow checks in specializer'
updated_at = <Date 2021-10-28.14:53:42.278>
user = 'https://github.com/Fidget-Spinner'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-28.14:53:42.278>
actor = 'kj'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-10-28.14:53:27.764>
creator = 'kj'
dependencies = []
files = []
hgrepos = []
issue_num = 45648
keywords = ['patch']
message_count = 1.0
messages = ['405190']
nosy_count = 2.0
nosy_names = ['Mark.Shannon', 'kj']
pr_nums = ['29272']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45648'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-113558
* gh-114216
* gh-115045

**Comment by lazorchakp** [comment] 2023-12-12 17:13
Just want to report that I accidentally ran into this in the wild. I work on an instrumentation library that modifies builtin types like `str` and `bytes`, which involves a few calls to PyType_Modified. My tests call this function hundreds of thousands of times when enabling and disabling machinery.

Repeated calls to PyType_Modified eventually caused tp_version_tag for modified builtin types to reach `_Py_MAX_GLOBAL_TYPE_VERSION_TAG`, which in turn led to tp_version_tag == 0 on these types. Some of the recent LOAD_ATTR_* bytecode specializations rely on tp_version_tag to determine whether to continue with the specialization or fall back to the generic operation. However, with multiple types having tp_version_tag == 0, python was no longer able to correctly distinguish between different types, leading to a variety of strange (oddly hilarious) errors.

Here's a reproduction script:

```python
import ctypes

PyType_Modified = ctypes.pythonapi.PyType_Modified
PyType_Modified.argtypes = [ctypes.py_object]

# reach _Py_MAX_GLOBAL_TYPE_VERSION_TAG
for i in range(2**17):
    PyType_Modified(list)
    [].__add__  # any attribute lookup forces a new tp_version_tag

# newly modified types will be assigned tp_version_tag 0
PyType_Modified(str)
PyType_Modified(bytes)


def get_capitalize(type_):
    return type_.capitalize


# multiple calls with `str` leads to LOAD_ATTR specialization
get_capitalize(str)
get_capitalize(str)

# specialized bytecode fails to differentiate `bytes` from `str`
# TypeError: descriptor 'capitalize' for 'str' objects doesn't apply to a 'bytes' object
get_capitalize(bytes)(b"boom")
```

I verified that this fails in 3.12.1 and 3.13.0a2 and does not fail in 3.11.7 (source builds using pyenv on an M1 mac). I'll be able to work around my particular issue, but I felt responsible to report this as a data point. It's possible that other instrumentation tools will eventually encounter similar issues.

Thanks for all of the recent interpreter improvements - it's been exciting to see these changes. If you'd like me to try refreshing the stale PR here or help out in any other way, I'd be happy to give it a shot.

**Comment by Fidget-Spinner** [comment] 2023-12-12 20:18
@lazorchakp thanks for the reproducer! I can help guide you on making a PR towards fixing this if you're interested. Honestly I did not expect this to appear in the wild, so I forgot about it.

The fix would still be the same - to check `tp_version_tag == 0` after `analyze_descriptor` calls in `specialize.c`.

**Comment by lazorchakp** [comment] 2023-12-12 21:02
@Fidget-Spinner thanks for the quick response! I can definitely throw something together. This will be my first contribution to the project, so I'd really appreciate any guidance. I have a few conflicting priorities at the moment, but I'll work on getting a PR out and then hopefully you can catch anything I may have missed.

**Comment by Fidget-Spinner** [comment] 2023-12-20 17:29
Sorry for the late reply. Do you need help or any guidance on this? If you need help I'll be happy to set up something (you can email me at my GH profile's email).

**Comment by lazorchakp** [comment] 2023-12-21 17:09
That would be great. I think I have a reasonable solution, but I'm unsure how to test it thoroughly - I'll reach out directly

**Comment by Fidget-Spinner** [comment] 2023-12-27 13:28
Another reproducer is at https://github.com/python/cpython/issues/113462.

I'm marking this as a release blocker for 3.12 and 3.13. We should still backport this to 3.11, but the chances of this occuring in that version seems to be lower.

Peter, please don't feel rushed to do this and have a good holiday! If it helps, I think you can submit a draft PR first and we can try to help you from there.

**Comment by lazorchakp** [comment] 2023-12-28 15:31
The new reproducer makes sense to me and shouldn't change how I'm implementing the fix. I can get a draft up a little later today!

**Comment by pablogsal** [comment] 2024-02-05 22:41
This is marked as a release-blocker with the 3.11 tag. The issue is still open but I am not sure if this was expected to be backported to 3.11. It's there anything left for us to do here or can I proceed with the release?

**Comment by lazorchakp** [comment] 2024-02-05 23:24
@pablogsal This does need a backport to 3.11, but I'm currently working on it. Sorry for the delay - I'll have a PR up as soon as possible

**Closed as completed** 2024-02-06 14:00 UTC
Labels: interpreter-core, 3.11, 3.12, 3.13
