### ISSUE TITLE
Default value to dataclass field is ignored if setting up getter/setter

### ISSUE THREAD

**Issue by subercui** [python/cpython#94067] opened 2022-06-21 15:22 UTC
**Bug report**

As the title describes, for example, if I run the following,
```python
from dataclasses import dataclass, InitVar


@dataclass
class Test:
    b: int = 6
    id: InitVar[int]=1

    def __post_init__(self, id=0):
        print(f"the value of id is {id} in the post_init")
        print(f"is id a property: {isinstance(id, property)}")
        self._id = id

    @property
    def id(self):
        print("using the getter")
        return self._id

    @id.setter
    def id(self, to):
        print("using the setter")
        self._id = to


print("\nInit with position argument")
a = Test(1)
print("a is", a)
print("a.id is", a.id)

print("\nInit with explicit key")
a4 = Test(id=4)
print("a4.id is", a4.id)
```

In the position argument initialization case, I expect to have a.id been initialized as either 1 or 0 (I think either behavior is acceptable). However, turns out the value is never set. The actual print-out is as follows:

> Init with position argument
> the value of id is <property object at 0x7f03526be450> in the post_init
> is id a property: True
> a is Test(b=1)
> using the getter
> a.id is <property object at 0x7f03526be450>
> 
> Init with explicit key
> the value of id is 4 in the post_init
> is id a property: False
> using the getter
> a4.id is 4

I've also tested setting `id` as an actual `field(init=True/False)`, and the same issue occurs.

**Your environment**

- CPython versions tested on: 3.9.5
- Operating system and architecture: Ubuntu 18.04.6 LTS, x86_64

**Comment by subercui** [comment] 2022-06-21 20:13
Here is the case for `id` as an actual `Field`

```python
from dataclasses import dataclass, InitVar


@dataclass
class Test:
    b: int = 6
    id: int = 1

    def __post_init__(self):
        print(f"the value of id is {self.id} in the post_init")
        print(f"is id a property: {isinstance(self.id, property)}")
        self._id = self.id

    @property
    def id(self):
        print("using the getter")
        return self._id

    @id.setter
    def id(self, to):
        print("using the setter")
        self._id = to


print("\nInit with position argument")
a = Test(1)
print("a is", a)
print("a.id is", a.id)

print("\nInit with explicit key")
a4 = Test(id=4)
print("a4.id is", a4.id)
```

Output:

> Init with position argument
> using the setter
> using the getter
> the value of id is <property object at 0x7f03526c55e0> in the post_init
> using the getter
> is id a property: True
> using the getter
> a is using the getter
> Test(b=1, id=<property object at 0x7f03526c55e0>)
> using the getter
> a.id is <property object at 0x7f03526c55e0>
> 
> Init with explicit key
> using the setter
> using the getter
> the value of id is 4 in the post_init
> using the getter
> is id a property: False
> using the getter
> using the getter
> a4.id is 4

**Comment by ericvsmith** [comment] 2022-06-22 01:47
This is essentially what's happening:
```python
from dataclasses import dataclass, InitVar


class Test:
    b: int = 6
    id: int = 1

    def __post_init__(self):
        print(f"the value of id is {self.id} in the post_init")
        print(f"is id a property: {isinstance(self.id, property)}")
        self._id = self.id

    @property
    def id(self):
        print("using the getter")
        return self._id

    @id.setter
    def id(self, to):
        print("using the setter")
        self._id = to


def init(self, b=6, id=Test.id):
    self.b = b
    self.id = id
    self.__post_init__()


Test.__init__ = init
Test = dataclass(Test)


print("\nInit with position argument")
a = Test(1)
print("a is", a)
print("a.id is", a.id)

print("\nInit with explicit key")
a4 = Test(id=4)
print("a4.id is", a4.id)
```

**Comment by ericvsmith** [comment] 2022-06-22 01:58
There's nothing that can be done about this. After the class is created, and before `@dataclass()` runs. the value of `Test.id` is the property, and the value originally assigned to `id` is overwritten and lost. Consider:
```python
class Test1:
    id: int = 1
print(Test1.__dict__)
```
Which prints `{'__module__': '__main__', '__annotations__': {'id': <class 'int'>}, 'id': 1, '__dict__': <attribute '__dict__' of 'Test1' objects>, '__weakref__': <attribute '__weakref__' of 'Test1' objects>, '__doc__': None}`
and
```python
class Test2:
    id: int = 1
    @property
    def id(self): pass
print(Test2.__dict__)
```
which prints `{'__module__': '__main__', '__annotations__': {'id': <class 'int'>}, 'id': <property object at 0x000001B58BE13EE0>, '__dict__': <attribute '__dict__' of 'Test2' objects>, '__weakref__': <attribute '__weakref__' of 'Test2' objects>, '__doc__': None}`

Note that in the Test2 case, the default value of `1` has been overwritten, and is not available to `@dataclass()`.

**Comment by subercui** [comment] 2022-06-22 02:00
Thanks for the clarification!
I guess for the `InitVar` case, is it like:
```python
def init(self, b=6, id=Test.id):
    self.b = b
    self.__post_init__(id)
```

So if I understand correctly, using a default value is kind of difficult when working with getter/setter. A workaround can be, in the `__post_init__` have
```python
if isinstance(self.id, property):
    self._id = put_default_value_here
```

**Comment by subercui** [comment] 2022-06-22 02:01
So generally speaking, is there an easier way to use property within `dataclass`?

**Comment by ericvsmith** [comment] 2022-06-22 02:01
Sure, you can do anything you want in `__post_init__`.

**Comment by ericvsmith** [comment] 2022-06-22 02:05
> So generally speaking, is there an easier way to use property within `dataclass`?

Somewhere there's an issue about changing the name of a field (maybe by using a `field` parameter?), but I can't find it and I don't recall if it was intended to solve this case.

**Closed as not planned** 2022-06-24 13:11 UTC
Labels: stdlib
