### ISSUE TITLE
typing.NamedTupleMeta should allow subclassing alongside classes other than NamedTuple and Generic

### ISSUE THREAD

**Issue by CoolCat467** [python/cpython#125167] opened 2024-10-09 02:27 UTC
# Feature or enhancement

### Proposal:

I propose that `typing.NamedTupleMeta` should allow creation of NamedTuples that inherit from things other than NamedTuple or Generic.

For example,
```python
from typing import NamedTuple

class BaseVector:
    """Shared functionality between all vectors."""
    ...

class Vector2(NamedTuple, BaseVector):
    """Vector2 Object. Takes an x and a y coordinate."""

    x: float
    y: float

class Vector3(NamedTuple, BaseVector):
    """Vector3 Object. Takes an x, y, and z coordinate."""

    x: float
    y: float
    z: float
```

Currently, if you try to do this, you get `TypeError: can only inherit from a NamedTuple type and Generic` being raised at runtime.

In particular, in `typing`, instead of this:
```python
class NamedTupleMeta(type):
    def __new__(cls, typename, bases, ns):
        assert _NamedTuple in bases
        for base in bases:
            if base is not _NamedTuple and base is not Generic:
                raise TypeError(
                    'can only inherit from a NamedTuple type and Generic')
        ...
```
it would be changed to this:
```python
class NamedTupleMeta(type):
    def __new__(cls, typename, bases, ns):
        if _NamedTuple not in bases:
             raise TypeError(
                 'must inherit from a NamedTuple type')
        ...
```

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

Kind of related but not really: https://github.com/python/cpython/issues/77258

**Comment by AlexWaygood** [comment] 2024-10-09 08:52
Duplicate of #116241

**Closed as not planned by AlexWaygood** 2024-10-09 08:52 UTC
Labels: type-feature, topic-typing
