### ISSUE TITLE
`dis` module documentation is missing `END_SEND`

### ISSUE THREAD

**Issue by P403n1x87** [python/cpython#109805] opened 2023-09-24 15:17 UTC
# Documentation

The disassembly of some code object obtained with Python 3.12.0rc1 shows a new `END_SEND` opcode

```
Disassembly of <code object coro at 0x104617430, file "/tmp/agen.py", line 20>:
 20           0 RETURN_GENERATOR
              2 POP_TOP
              4 RESUME                   0

 21           6 PUSH_NULL
              8 LOAD_FAST                0 (wrapper)
             10 LOAD_FAST                1 (wrapped)
             12 LOAD_FAST                2 (args)
             14 LOAD_FAST                3 (kwargs)
             16 CALL                     3
             24 GET_AWAITABLE            0
             26 LOAD_CONST               0 (None)
        >>   28 SEND                     3 (to 38)
             32 YIELD_VALUE              2
             34 RESUME                   3
             36 JUMP_BACKWARD_NO_INTERRUPT     5 (to 28)
        >>   38 END_SEND
             40 RETURN_VALUE
        >>   42 CLEANUP_THROW
             44 JUMP_BACKWARD            4 (to 38)
        >>   46 CALL_INTRINSIC_1         3 (INTRINSIC_STOPITERATION_ERROR)
             48 RERAISE                  1
```

However, there doesn't seem to be an entry in the documentation for the `dis` module describing this new opcode.

**Comment by AA-Turner** [comment] 2023-09-25 05:27
Duplicate of #107457; closing.

A

**Closed as not planned by AA-Turner** 2023-09-25 05:28 UTC
Labels: docs, 3.12, 3.13
