### ISSUE TITLE
Python fails to build on x86 Debian Non-Debug with X 3.x: error on Hacl_Hash_Blake2s_Simd128.c

### ISSUE THREAD

**Issue by vstinner** [python/cpython#125535] opened 2024-10-15 15:33 UTC
Build: https://buildbot.python.org/#/builders/1245/builds/3269

```
gcc -c -I./Modules/_hacl -I./Modules/_hacl/include -D_BSD_SOURCE -D_DEFAULT_SOURCE -fno-strict-overflow -Wsign-compare
 -DNDEBUG -g -O3 -Wall -UNDEBUG   -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes
 -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal -I./Include/internal/mimalloc  -I. -I./Include
 -fPIC -msse -msse2 -msse3 -msse4.1 -msse4.2 -DHACL_CAN_COMPILE_VEC128
 -o Modules/_hacl/Hacl_Hash_Blake2s_Simd128.o ./Modules/_hacl/Hacl_Hash_Blake2s_Simd128.c

In file included from ./Modules/_hacl/internal/Hacl_Hash_Blake2s_Simd128.h:40,
                 from ./Modules/_hacl/Hacl_Hash_Blake2s_Simd128.c:26:
./Modules/_hacl/internal/../Hacl_Hash_Blake2s_Simd128.h:55:3: error: unknown type name ‘Lib_IntVector_Intrinsics_vec128’
   55 |   Lib_IntVector_Intrinsics_vec128 *fst;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

cc @gpshead

**Comment by vstinner** [comment] 2024-10-15 15:34
cc @zware, owner of the buildbot worker.

**Comment by vstinner** [comment] 2024-10-15 15:34
Same error on x86 Debian Installed with X 3.x: https://buildbot.python.org/#/builders/1244/builds/3253

**Comment by vstinner** [comment] 2024-10-15 15:39
"x86 Debian Non-Debug with X 3.x" and "x86 Debian Installed with X 3.x" workers are 32-bit machines, whereas `Hacl_Hash_Blake2s_Simd128.c` requires `Lib_IntVector_Intrinsics_vec128` and `Lib_IntVector_Intrinsics_vec128` is only defined on 64-bit architectures (`#if defined(__x86_64__) || defined(_M_X64)`).

**Comment by zware** [comment] 2024-10-15 15:42
Duplicate of gh-125244, but this will make searching for it a bit easier :)

**Comment by zware** [comment] 2024-10-15 15:44
Oh, I didn't realize that's a PR, not an issue.  So this might as well stay open.

**Comment by vstinner** [comment] 2024-10-15 15:44
Good that a PR was proposed to fix the issue!

**Comment by zware** [comment] 2024-10-17 15:21
This is now resolved with the merge of GH-125244.

**Closed as completed by zware** 2024-10-17 15:21 UTC
Labels: build
