### ISSUE TITLE
Inconsistent results for matching with `re.IGNORECASE` if the character's casefold is of length > 1

### ISSUE THREAD

**Issue by HarryLHW** [python/cpython#121678] opened 2024-07-13 10:36 UTC
# Bug report

### Bug description:

The character `İ` (`\u0130`, LATIN CAPITAL LETTER I WITH DOT ABOVE) can (full)match `i` or `I` with `re.IGNORECASE`, while its lowercase is `i̇`, NOT a single `i`.
```python
>>> '\u0130'
'İ'
>>> '\u0130'.casefold()
'i̇'
>>> '\u0130'.lower()
'i̇'
>>> list(map(ord, '\u0130'.lower()))
[105, 775]
>>> re.fullmatch('\u0130', chr(105), re.IGNORECASE)
<re.Match object; span=(0, 1), match='i'>
>>> re.fullmatch('\u0130', 'I', re.IGNORECASE)
<re.Match object; span=(0, 1), match='I'>
>>>
```

The character `ß` (`\u00df`, LATIN SMALL LETTER SHARP S) cannot match `ss`, `SS`, `s`, or `S` with `re.IGNORECASE`. This behavior is different from the one for `İ`.
```python
>>> '\u00df'
'ß'
>>> '\u00df'.casefold()
'ss'
>>> '\u00df'.upper()
'SS'
>>> list(map(ord, '\u00df'.upper()))
[83, 83]
>>> re.search('\u00df', chr(83), re.IGNORECASE)
>>> re.search('\u00df', 'ss', re.IGNORECASE)
>>> re.search('\u00df', 'SS', re.IGNORECASE)
>>> re.search('\u00df', 's', re.IGNORECASE)
>>> re.search('\u00df', 'S', re.IGNORECASE)
>>> 
```
There are many other characters (such as `ß`) whose `.upper()` contains 2 or more characters, and none of them can make a successful match or search with `re.IGNORECASE`. However, `İ` is the only character whose `.lower()` contains 2 or more characters.

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

macOS

**Comment by serhiy-storchaka** [comment] 2024-07-13 10:46
This is a known limitation of the `re` module. Use the third-party `regex` module which has better support of Unicode.

Closing as a duplicate of #75376.

**Closed as not planned** 2024-07-13 10:46 UTC
Labels: type-bug

**Comment by HarryLHW** [comment] 2024-07-13 10:58
> This is a known limitation of the `re` module. Use the third-party `regex` module which has better support of Unicode.
> 
> Closing as a duplicate of #75376.

Thank you for your reply. I understand this is a limitation. But `İ` and `ß` give different results. I am wondering if this would be a problem or not.
