### ISSUE TITLE
Python github installation issue

### ISSUE THREAD

**Issue by f8d0428e-8765-46cf-aaee-ab40e5abefe6** [python/cpython#90064] opened 2021-11-26 20:07 UTC
BPO | [45906](https://bugs.python.org/issue45906)
--- | :---
Nosy | @tiran

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-26.20:07:38.250>
labels = ['build', 'expert-installation', '3.9']
title = 'Python github installation issue'
updated_at = <Date 2021-12-04.22:18:45.672>
user = 'https://bugs.python.org/mazen001ahmed001'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-04.22:18:45.672>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation']
creation = <Date 2021-11-26.20:07:38.250>
creator = 'mazen001.ahmed001'
dependencies = []
files = []
hgrepos = []
issue_num = 45906
keywords = []
message_count = 2.0
messages = ['407089', '407689']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'mazen001.ahmed001']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue45906'
versions = ['Python 3.9']
```

</p></details>

**Comment by hauntsaninja** [comment] 2022-05-14 03:37
Closing, since this isn't currently reproducible

**Closed as completed by hauntsaninja** 2022-05-14 03:37 UTC
Labels: build, topic-installation, 3.9 (EOL)
