### ISSUE TITLE
Python 3.13 interactive console - CTRL-C does not give control back to gdb

### ISSUE THREAD

**Issue by bstaletic** [python/cpython#120721] opened 2024-06-19 03:46 UTC
# Bug report

### Bug description:

Sometimes I debug my C extensions by starting `gdb python` and messing around in the interactive console.
Today I have tried that with python 3.13.0b2.
Normally, ctrl-c should give control back to gdb, so I can set a breakpoint.
With python 3.13, python itself handles ctrl-c and just says `KeyboardInterrupt`.

Python 3.12 recording:

https://asciinema.org/a/jplPQN7lqzKjXu3oRPlAf3GEf

Python 3.13 recording:

https://asciinema.org/a/DThG2xPnh4WIF9TVG1AsJngBd

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by eryksun** [comment] 2024-06-19 09:06
This is a duplicate of #120221, which has already been resolved.

**Closed as not planned** 2024-06-19 12:58 UTC
Labels: type-bug, 3.13, 3.14, topic-repl
