### ISSUE TITLE
The new repl sometimes does not show the error location when `SyntaxError` is raised

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#121804] opened 2024-07-15 18:17 UTC
# Bug report

### Bug description:

When I run `def f[Foo, Foo](): ...` from a file, I get a nice error message including the location of the error:

```python
  File ".../test.py", line 1
    def f[Foo, Foo](): ...
               ^^^
SyntaxError: duplicate type parameter 'Foo'
```
However, when I run this in the new repl, the error location is not shown:

```python
>>> def f[Foo, Foo](): ...
  File "<python-input-0>", line 1
SyntaxError: duplicate type parameter 'Foo'
```
The same thing happens with this error as well:

```python
>>> def f(x, x): ...
  File "<python-input-0>", line 1
SyntaxError: duplicate argument 'x' in function definition
```
The missing location seems to be the case for these two errors only as other errors do show it:

```python
>>> def f(42): ...
  File "<unknown>", line 1
    def f(42): ...
          ^^
SyntaxError: invalid syntax
```
What's interesting is that for the first two errors the file shows up as `<python-input-0>` while for the last one it's `<unknown>`. This could be related to the last error coming from the parser while the previous errors come from symtable:

https://github.com/python/cpython/blob/6522f0e438a8c56a8f3cce2095b193ea6e3f5016/Python/symtable.c#L1421-L1435

Though it looks like that the error location is being set with `SET_ERROR_LOCATION`..

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121886
* gh-123148
* gh-123202
* gh-123366
* gh-123631

**Comment by skirpichev** [comment] 2024-07-16 07:28
This issue is valid for basic repl as well:
```
$ PYTHON_BASIC_REPL=1 ./python
Python 3.14.0a0 (heads/main:bf74db731b, Jul 15 2024, 11:06:00) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def f[Foo, Foo](): ...
...
  File "<stdin>-0", line 1
SyntaxError: duplicate type parameter 'Foo'
>>> def f(x, x): ...
... 
  File "<stdin>-1", line 1
SyntaxError: duplicate argument 'x' in function definition
```

**Comment by skirpichev** [comment] 2024-07-16 11:05
Exceptions metadata differ when compile() has valid filename argument wrt fake filename like ``<input>``.  It seems, the only way to workaround this is using a temporary file to dump code:
```pycon
>>> def f(x, x): ...
  File "/tmp/tmpuygzaco0", line 1
    def f(x, x): ...
             ^
SyntaxError: duplicate argument 'x' in function definition
```

<details>

<summary>POC diff</summary>

```diff
diff --git a/Lib/_pyrepl/console.py b/Lib/_pyrepl/console.py
index a8d3f52034..0df16c2b3d 100644
--- a/Lib/_pyrepl/console.py
+++ b/Lib/_pyrepl/console.py
@@ -168,6 +168,12 @@ def showtraceback(self):
         super().showtraceback(colorize=self.can_colorize)
 
     def runsource(self, source, filename="<input>", symbol="single"):
+        import tempfile
+        import os
+        file = tempfile.NamedTemporaryFile('w+', delete=False)
+        file.write(source)
+        file.close()
+        filename = file.name
         try:
             tree = ast.parse(source)
         except (SyntaxError, OverflowError, ValueError):
@@ -189,11 +195,15 @@ def runsource(self, source, filename="<input>", symbol="single"):
                         f" top-level 'await' and run background asyncio tasks."
                     )
                 self.showsyntaxerror(filename)
+                os.unlink(filename)
                 return False
             except (OverflowError, ValueError):
                 self.showsyntaxerror(filename)
+                os.unlink(filename)
                 return False
 
+            os.unlink(filename)
+
             if code is None:
                 return True
 
```
</details>

**Comment by sobolevn** [comment] 2024-07-16 11:21
There are multiple systems / setups where temporary files could not be created: 
- readonly mounts
- permissions
- etc

Plus, I am not sure that users expect to see `File "/tmp/tmpuygzaco0", line 1`, I think that it should be a bit more complicated:
- We can try to create and open this temp file, if not - fallback to default behaviour
- If it is opened, then still show an old `<input>` tag as a visible filename

There's also a question about how to append / rewrite / recreate this file on new statements.

State is hard :(

**Comment by tomasr8** [comment] 2024-07-16 11:32
imo fixing the core issue with the metadata is probably better than using a temp file for the reasons @sobolevn mentioned, but I don't know enough about the code to tell how hard that would be..

**Comment by skirpichev** [comment] 2024-07-16 14:12
> There are multiple systems / setups where temporary files could not be created

Yes, this is not easy:)

> Plus, I am not sure that users expect to see File "/tmp/tmpuygzaco0", line 1

I think this can be fixed.

On another hand, we have almost all required metadata for exception in it's attributes:
```pycon
>>> try:
...     compile("def f(x,x): ...\n", "spam.py", "single")
... except Exception as e:
...     print(e.lineno, e.offset)
...     
1 9
```
The ``text`` attribute is empty.

So, we can provide ``source`` as an optional kwarg for showsyntaxerror() method.  Given this, we can "fix" empty ``text`` attribute of the exception.  With this patch (see details below):
```pycon
>>> def f(x, x): ...
  File "<python-input-0>", line 1
    def f(x, x): ...
             ^
SyntaxError: duplicate argument 'x' in function definition
>>> def f[Foo, Foo](): ...
  File "<python-input-1>", line 1
    def f[Foo, Foo](): ...
               ^^^
SyntaxError: duplicate type parameter 'Foo'
```

<details>

<summary>POC patch</summary>

```diff
diff --git a/Lib/_pyrepl/console.py b/Lib/_pyrepl/console.py
index a8d3f52034..1eda92d49c 100644
--- a/Lib/_pyrepl/console.py
+++ b/Lib/_pyrepl/console.py
@@ -161,8 +161,8 @@ def __init__(
         super().__init__(locals=locals, filename=filename, local_exit=local_exit)  # type: ignore[call-arg]
         self.can_colorize = _colorize.can_colorize()
 
-    def showsyntaxerror(self, filename=None):
-        super().showsyntaxerror(colorize=self.can_colorize)
+    def showsyntaxerror(self, filename=None, **kwargs):
+        super().showsyntaxerror(colorize=self.can_colorize, **kwargs)
 
     def showtraceback(self):
         super().showtraceback(colorize=self.can_colorize)
@@ -188,7 +188,7 @@ def runsource(self, source, filename="<input>", symbol="single"):
                         f"Try the asyncio REPL ({python} -m asyncio) to use"
                         f" top-level 'await' and run background asyncio tasks."
                     )
-                self.showsyntaxerror(filename)
+                self.showsyntaxerror(filename, source=source)
                 return False
             except (OverflowError, ValueError):
                 self.showsyntaxerror(filename)
diff --git a/Lib/code.py b/Lib/code.py
index a55fced070..78bcdcdca5 100644
--- a/Lib/code.py
+++ b/Lib/code.py
@@ -64,7 +64,7 @@ def runsource(self, source, filename="<input>", symbol="single"):
             code = self.compile(source, filename, symbol)
         except (OverflowError, SyntaxError, ValueError):
             # Case 1
-            self.showsyntaxerror(filename)
+            self.showsyntaxerror(filename, source=source)
             return False
 
         if code is None:
@@ -107,6 +107,7 @@ def showsyntaxerror(self, filename=None, **kwargs):
 
         """
         colorize = kwargs.pop('colorize', False)
+        source = kwargs.pop('source', "")
         type, value, tb = sys.exc_info()
         sys.last_exc = value
         sys.last_type = type
@@ -124,6 +125,8 @@ def showsyntaxerror(self, filename=None, **kwargs):
                 value = SyntaxError(msg, (filename, lineno, offset, line))
                 sys.last_exc = sys.last_value = value
         if sys.excepthook is sys.__excepthook__:
+            if source:
+                value.text = source.splitlines()[value.lineno-1]
             lines = traceback.format_exception_only(type, value, colorize=colorize)
             self.write(''.join(lines))
         else:
```

</details>

If this is not too hackish way to deal with the issue - I'll make a pr.

**Comment by skirpichev** [comment] 2024-07-17 03:46
pr is ready for review: #121886

**Comment by skirpichev** [comment] 2024-08-18 14:40
cc @pablogsal, maybe you could take look on pr?

**Comment by pablogsal** [comment] 2024-08-18 19:35
Will do today

**Comment by skirpichev** [comment] 2024-08-20 02:13
@pablogsal, this is still valid, in the basic repl.  Does it not worth fixing?

**Comment by pablogsal** [comment] 2024-08-20 10:47
> @pablogsal, this is still valid, in the basic repl. Does it not worth fixing?

Unless the fix is trivial I would prefer not to add extra complexity for just the fallback.

**Comment by skirpichev** [comment] 2024-08-20 10:56
You can see fixes (drafts) few commits above (for basic repl too): https://github.com/python/cpython/issues/121804#issuecomment-2231007082

**Comment by pablogsal** [comment] 2024-08-20 11:33
> You can see fixes (drafts) few commits above (for basic repl too): [#121804 (comment)](https://github.com/python/cpython/issues/121804#issuecomment-2231007082)

Ok, go for it, but that patch needs a bunch of handling for errors in these calls.

**Comment by skirpichev** [comment] 2024-08-21 14:24
@pablogsal, here is a new pr: https://github.com/python/cpython/pull/123202

Still marked as a draft, because it crashes on debug builds.  gdb shows it happens in PyUnicode_Check(interactive_src).

<details>

```
Python 3.14.0a0 (heads/syntaxerr-location-basicrepl-121804-dirty:99f7d742a9, Aug 21 2024, 14:26:0) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def f(x, x): ...
...

Program received signal SIGSEGV, Segmentation fault.
ensure_unicode (obj=obj@entry=<unknown at remote 0x7ffff713f700>) at ./Include/object.h:763
763         return ((flags & feature) != 0);
(gdb) bt
#0  ensure_unicode (obj=obj@entry=<unknown at remote 0x7ffff713f700>) at ./Include/object.h:763
#1  0x0000555555726951 in PyUnicode_Splitlines (string=<unknown at remote 0x7ffff713f700>, keepends=keepends@entry=1)
    at Objects/unicodeobject.c:10193
#2  0x000055555581e4fd in PyRun_InteractiveOneObjectEx (fp=fp@entry=0x7ffff7eb4a80 <_IO_2_1_stdin_>,
    filename=filename@entry='<stdin>', flags=flags@entry=0x7fffffffd580) at Python/pythonrun.c:290
#3  0x000055555581ff97 in _PyRun_InteractiveLoopObject (fp=fp@entry=0x7ffff7eb4a80 <_IO_2_1_stdin_>,
    filename=filename@entry='<stdin>', flags=flags@entry=0x7fffffffd580) at Python/pythonrun.c:131
#4  0x0000555555820430 in _PyRun_AnyFileObject (fp=fp@entry=0x7ffff7eb4a80 <_IO_2_1_stdin_>, filename=filename@entry='<stdin>',
    closeit=closeit@entry=0, flags=flags@entry=0x7fffffffd580) at Python/pythonrun.c:71
#5  0x00005555558204e9 in PyRun_AnyFileExFlags (fp=0x7ffff7eb4a80 <_IO_2_1_stdin_>, filename=filename@entry=0x5555558b3886 "<stdin>",
    closeit=closeit@entry=0, flags=flags@entry=0x7fffffffd580) at Python/pythonrun.c:98
#6  0x0000555555845b36 in pymain_run_stdin (config=config@entry=0x555555b5f358 <_PyRuntime+199800>) at Modules/main.c:571
#7  0x000055555584615e in pymain_run_python (exitcode=exitcode@entry=0x7fffffffd624) at Modules/main.c:699
#8  0x00005555558463f4 in Py_RunMain () at Modules/main.c:775
#9  0x000055555584646b in pymain_main (args=args@entry=0x7fffffffd680) at Modules/main.c:805
#10 0x0000555555846531 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:829
#11 0x00005555555d5842 in main (argc=<optimized out>, argv=<optimized out>) at ./Programs/python.c:15
```

</details>

It could be reproduced on the current master with:
```diff
diff --git a/Python/pythonrun.c b/Python/pythonrun.c
index ce7f194e92..2601c9268c 100644
--- a/Python/pythonrun.c
+++ b/Python/pythonrun.c
@@ -282,6 +282,10 @@ PyRun_InteractiveOneObjectEx(FILE *fp, PyObject *filename,
     PyObject *res = run_mod(mod, filename, main_dict, main_dict, flags, arena, interactive_src, 1);
     _PyArena_Free(arena);
     Py_DECREF(main_module);
+    if (interactive_src) {
+        printf("float? - %d\n", PyFloat_Check(interactive_src));
+        printf("unicode? - %d\n", PyUnicode_Check(interactive_src));
+    }
     if (res == NULL) {
         return -1;
     }
```
Works on non-debug builds (prints 0 and then 1) and crashes on the first check for debug builds.  I think it's a bug, but not with my code: the ``interactive_src`` is a PyObject, type checks on it shouldn't crash interpreter.

Should I report new issue?

**Comment by pablogsal** [comment] 2024-08-21 17:47
> Should I report new issue?

It's not a bug, the `interactive_src` object it's own by the arena and you are freeing the arena two lines before that. If you incref the `interactive_src` object before freeing the arena it won't crash

**Comment by skirpichev** [comment] 2024-08-22 07:47
Thanks for help!  Now pr is ready for review.

**Comment by picnixz** [comment] 2024-08-28 15:08
I'm reopening this issue until we've merged the second PR (just for tracking purposes).

**Closed as completed** 2024-09-03 12:38 UTC
Labels: type-bug, interpreter-core, topic-repl
