### ISSUE TITLE
Slots does not work with typing.Final dataclass attribute

### ISSUE THREAD

**Issue by NicoHood** [python/cpython#115879] opened 2024-02-24 08:56 UTC
# Bug report

### Bug description:

Hi,
I discovered a bug when using the `Final` attribute along with `slots=True` in dataclasses. The bug is more described in this stackoverflow post where someone with more knowledge has explained to me why this happens and which code line causes this issue:
https://stackoverflow.com/questions/78039353/why-does-slots-not-work-with-final-dataclass-attribute

Here is a minimal example:
```python
#!/usr/bin/env python3

from __future__ import annotations
from dataclasses import dataclass
from typing import Final, ClassVar

@dataclass(slots=True)
class Child():
    VERSION: Final[str] = '1.0.0'

    @classmethod
    def check_version(cls, version: str) -> bool:
        return version == cls.VERSION

print(Child.check_version('1.0.0'))
# Returns False

```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment] 2024-02-24 11:13
Interesting -- possibly a duplicate of #89547

**Comment by sobolevn** [comment] 2024-02-25 15:07
I don't think that this is a bug, actually. Let's "compile" what's happening into simplier python code:

```python
@dataclass(slots=True)
class Child:
    VERSION: Final[str] = '1.0.0'
```

Turns into:

```python
class Child:
    __slots__ = ('VERSION',)
    def __init__(self, VERSION) -> None:
         self.VERSION: Final[str] = '1.0.0'
```

Remember that all `field: annotation = default` statements inside a dataclass are translated into instance attributes.

So, when you access `cls.VERSION` you get `<member 'VERSION' of 'Child' objects>`. This is also correct.

If you want to use `Final` with class-level variables right now you have to do something like:

```python
class Base:
    VERSION: Final[str] = '1.0.0'

@dataclass(slots=True)
class Child(Base):
    ...
```

I agree with @AlexWaygood that this is a duplicate of https://github.com/python/cpython/issues/89547 and the proper solution would be to use something like `ClassVar[Final[]]` for this in the future.

I am going to close this issue as a duplicate, but feel free to ask any questions you might have :)

**Closed as not planned by sobolevn** 2024-02-25 15:07 UTC
Labels: type-bug, stdlib, topic-typing

**Comment by NicoHood** [comment] 2024-03-05 06:39
So is `ClassVar[Final[]]` the correct solution or not? You wrote "in the future". So what should I do now?

**Comment by NicoHood** [comment] 2024-09-06 05:53
But what if the version must be in the child, as I have different child implementations?

**Comment by sobolevn** [comment] 2024-09-06 06:27
Use `VERSION: ClassVar[str] = '1.2.3'` then.

**Comment by NicoHood** [comment] 2024-09-20 06:03
But a classvar is not final, isnt it?
