### ISSUE TITLE
``test_builtin.PtyTests.test_input_tty`` hangs on macOS

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#122439] opened 2024-07-30 06:18 UTC
# Bug report

### Bug description:

```python
./python.exe -m test -v test_builtin -m test_input_tty
== CPython 3.14.0a0 (heads/main:11ad731f4fa, Jul 30 2024, 07:55:09) [Clang 15.0.0 (clang-1500.3.9.4)]
== macOS-14.5-arm64-arm-64bit-Mach-O little-endian
== Python build: debug
== cwd: /Users/admin/Projects/cpython/build/test_python_worker_3797æ
== CPU count: 8
== encodings: locale=UTF-8 FS=utf-8
== resources: all test resources are disabled, use -u option to unskip tests

Using random seed: 3279392138
0:00:00 load avg: 2.79 Run 1 test sequentially in a single process
0:00:00 load avg: 2.79 [1/1] test_builtin
test_input_tty (test.test_builtin.PtyTests.test_input_tty) ... ^C

== Tests result: INTERRUPTED ==

1 test omitted:
    test_builtin

Test suite interrupted by signal SIGINT.

Total duration: 16 min 52 sec
Total tests: run=0 (filtered)
Total test files: run=0/1 (filtered)
Result: INTERRUPTED
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by ambv** [comment] 2024-07-30 09:06
This is a duplicate of #116402.

**Closed as not planned by ambv** 2024-07-30 09:06 UTC
Labels: type-bug, tests, OS-mac, 3.13, 3.14
