### ISSUE TITLE
email.message: header value parser get_msg_id throws IndexError on some invalid RFC822 Message-ID

### ISSUE THREAD

**Issue by zougloub** [python/cpython#117849] opened 2024-04-13 15:21 UTC
# Bug report

### Bug description:

I was looping in my inbox and found an e-mail with a Message-ID that causes an unexpected exception to be thrown:
```python
msgid = "<[ABCDEF====@microsoft.com]>"
assert msgid.startswith("<[") and msgid.endswith("]>")
email_message = email.message.EmailMessage()
email_message["Message-ID"] = msgid # Throws IndexError
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment] 2024-04-16 13:57
This is a duplicate of  #86650.

**Closed as not planned by serhiy-storchaka** 2024-04-16 13:57 UTC
Labels: type-bug, topic-email

**Comment by serhiy-storchaka** [comment] 2024-04-16 14:02
Or #105802.

**Comment by zougloub** [comment] 2024-04-16 14:16
Thank you @serhiy-storchaka , sorry for not finding an existing bug.

**Comment by serhiy-storchaka** [comment] 2024-04-16 16:10
Or #94306.

You are not the only one. There are currently three open issues for the same bug.
