### ISSUE TITLE
sqlite3.iterdump() incompatible with binary data

### ISSUE THREAD

**Issue by dotysan** [python/cpython#108590] opened 2023-08-28 21:58 UTC
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.11.5 (main, Aug 25 2023, 13:19:53) [GCC 9.4.0]

### A clear and concise description of the bug:

Apologies if I'm misunderstanding. Please advice if I should post elsewhere. But shouldn't iterdump() properly detect VARCHAR columns with binary data and output X'' strings instead of throwing an error? This is what `sqlite3 .dump` does.

```python
import sqlite3
with sqlite3.connect(db_path) as conn:
    with open(dump_path, 'w') as dump:
        for line in conn.iterdump():
            pass
```

The above will throw an error:
```
  File "foo.py", line 79, in dump_sqlite_db
    for line in conn.iterdump():
  File "/usr/lib/python3.11/sqlite3/dump.py", line 63, in _iterdump
    for row in query_res:
sqlite3.OperationalError: Could not decode to UTF-8 column ''INSERT INTO "sync_entities_metadata" VALUES('||quote("storage_key")||','||quote("metadata")||')'' with text 'INSERT INTO "sync_entities_metadata" VALUES(1,'v10����
```

I tried enabling `conn.text_factory = bytes` as a workaround, but now get a different error.
```
  File "foo.py", line 79, in dump_sqlite_db
    for line in conn.iterdump():
  File "/usr/lib/python3.11/sqlite3/dump.py", line 43, in _iterdump
    elif table_name.startswith('sqlite_'):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

### Linked PRs
* gh-108657
* gh-108673
* gh-108674
* gh-108683
* gh-108686
* gh-108694
* gh-108695
* gh-108699
* gh-111324
* gh-111325

**Comment by CorvinM** [comment] 2023-08-29 00:36
I am not able to reproduce this, could you provide an example database or the script/sql to create one that demonstrates the issue?

**Comment by dotysan** [comment] 2023-08-29 01:36
Hi @CorvinM, thanks for taking the time to attempt to reproduce.

My use case is fiddling around with existing settings in a Google Chrome profile. Your mileage may vary.

But here's a simplified/synthesized test that should be reproducible...

```
$ cat foo.sql
BEGIN TRANSACTION;
CREATE TABLE foo (id INTEGER, data VARCHAR);
INSERT INTO foo VALUES(42,'a�');
COMMIT;
$ hexdump -C foo.sql 
00000000  42 45 47 49 4e 20 54 52  41 4e 53 41 43 54 49 4f  |BEGIN TRANSACTIO|
00000010  4e 3b 0a 43 52 45 41 54  45 20 54 41 42 4c 45 20  |N;.CREATE TABLE |
00000020  66 6f 6f 20 28 69 64 20  49 4e 54 45 47 45 52 2c  |foo (id INTEGER,|
00000030  20 64 61 74 61 20 56 41  52 43 48 41 52 29 3b 0a  | data VARCHAR);.|
00000040  49 4e 53 45 52 54 20 49  4e 54 4f 20 66 6f 6f 20  |INSERT INTO foo |
00000050  56 41 4c 55 45 53 28 34  32 2c 27 61 9f 27 29 3b  |VALUES(42,'a.');|
00000060  0a 43 4f 4d 4d 49 54 3b  0a                       |.COMMIT;.|
00000069
```

Notice a single non-ASCII/UTF byte in the data VARCHAR column.

Then do this to build the database:
`sqlite3 foo.db <foo.sql`
Everything works fine! The sqlite3 database is apparently restored and consistent.

But then in Python...
```python
#! /usr/bin/env python3.11
"""https://github.com/python/cpython/issues/108590"""

import sqlite3

conn = sqlite3.connect('foo.db')
curs = conn.cursor()
curs.execute('SELECT * FROM foo')
for line in conn.iterdump():
    pass
```

It fails thusly:
```
 ./cpython-108590.py 
Traceback (most recent call last):
  File "cpython-108590.py", line 9, in <module>
    for line in conn.iterdump():
  File "/usr/lib/python3.11/sqlite3/dump.py", line 63, in _iterdump
    for row in query_res:
sqlite3.OperationalError: Could not decode to UTF-8 column ''INSERT INTO "foo" VALUES('||quote("id")||','||quote("data")||')'' with text 'INSERT INTO "foo" VALUES(42,'a�')'
```

**Comment by erlend-aasland** [comment] 2023-08-29 08:49
I'm unable to reproduce this using the following:

```
import sqlite3
with sqlite3.connect(":memory:") as cx:
    cx.execute("CREATE TABLE foo (data VARCHAR)")
    cx.execute("INSERT INTO foo VALUES(?)", ["a\x9f"])
for row in cx.iterdump():
    print(row)
cx.close()
```

**Comment by erlend-aasland** [comment] 2023-08-29 09:08
> Apologies if I'm misunderstanding. Please advice if I should post elsewhere. But shouldn't iterdump() properly detect VARCHAR columns with binary data and output X'' strings instead of throwing an error? This is what `sqlite3 .dump` does.

The SQLite shell does not special case VARCHAR (take a look at `shell.c` in the SQLite sources); it simply ignores the unprintable character. On my computer, that is also the behaviour of `iterdump`.

**Comment by erlend-aasland** [comment] 2023-08-29 11:21
Unable to reproduce on Debian as well.

**Comment by erlend-aasland** [comment] 2023-08-29 12:57
BTW, @dotysan, I see you are using the connection context manager. Note that the connection context manager does not close the database, it only makes sure that the transaction in the `with` body is committed; `__exit__` implicitly executes `COMMIT` or `ROLLBACK`, depending on if an exception happened. So, from your use case, it seems to me you would be better off by using `itertools.closing`.

**Comment by CorvinM** [comment] 2023-08-29 17:01
I am able to reproduce using @dotysan's foo.sql (recreated from hex dump, my terminal/editor is giving similar problems trying to "fix" the invalid encoding). The sqlite3 CLI both accepts it and reproduces it in a dump so I do believe its a python sqlite bug (rather than a corrupt db). Usually there is not supposed to be invalid encoded characters in a VARCHAR/TEXT field but it seems sqlite takes the garbage in -> garbage out policy. Working on a patch for this.

Heres an alternative hexdump of foo.sql that can be imported a bit easier (with `xxd -r`):
```
00000000: 4245 4749 4e20 5452 414e 5341 4354 494f  BEGIN TRANSACTIO
00000010: 4e3b 0a43 5245 4154 4520 5441 424c 4520  N;.CREATE TABLE 
00000020: 666f 6f20 2869 6420 494e 5445 4745 522c  foo (id INTEGER,
00000030: 2064 6174 6120 5641 5243 4841 5229 3b0a   data VARCHAR);.
00000040: 494e 5345 5254 2049 4e54 4f20 666f 6f20  INSERT INTO foo 
00000050: 5641 4c55 4553 2834 322c 2761 9f27 293b  VALUES(42,'a.');
00000060: 0a43 4f4d 4d49 543b 0a                   .COMMIT;.
```

**Comment by erlend-aasland** [comment] 2023-08-29 17:12
We can't use a hexdump for a regression test; please provide a Python only reproducer.

**Comment by erlend-aasland** [comment] 2023-08-29 17:17
@CorvinM, something like this should suffice:

``python
import sqlite3
SCRIPT = """
    CREATE TABLE foo (data VARCHAR);
    INSERT INTO foo VALUES('a\x9f');
"""
with sqlite3.connect(":memory:") as cx:
    cx.executescript(SCRIPT)
for row in cx.iterdump():
    print(row)
cx.close()
```

**Comment by erlend-aasland** [comment] 2023-08-29 18:54
Hm, yes I noticed this, @CorvinM. I can reproduce using the hexdump.

**Comment by erlend-aasland** [comment] 2023-08-29 19:00
It does not matter if the repro is ugly; we cannot rely on the SQLite shell in the CI. Having a zipped database and loading it with deserialize is a better option (however, that won't work in 3.11, since deserialize isn't implemented there).

**Comment by dotysan** [comment] 2023-08-29 19:32
For context, I stumbled across this while attempting to dump my Google Chrome profile settings using Python. They are the source of the binary data read/written into VARCHAR columns. I.e. not written from Python.

In particular `%LocalAppData%/Google/Chrome/User Data/Login Data` is the db and the offending column is `metadata` in table `sync_entities_metadata`.

The workaround in my case is to bypass the Python module with...
```py
    with open(dump_path, 'w') as dump:
        subprocess.run(['sqlite3', db_path, '.dump'], stdout=dump)
```

**Comment by CorvinM** [comment] 2023-08-29 19:34
Found a much better way to get around the encoding issue.
```python
import sqlite3
import gzip

SCRIPT = """
    CREATE TABLE foo (data VARCHAR);
    INSERT INTO foo VALUES (CAST(X'619f' AS VARCHAR));
"""

with sqlite3.connect(":memory:") as cx:
    cx.executescript(SCRIPT)
    for line in cx.iterdump():
        print(line)
cx.close()
```

**Comment by erlend-aasland** [comment] 2023-08-29 19:37
You can drop `import gzip`, now ;)

**Comment by erlend-aasland** [comment] 2023-08-29 19:44
BTW: Note that SQLite has the concept of type _affinity_. VARCHAR has the TEXT affinity. You can get the same result casting to TEXT. Also, the data type is optional in the table creation.

**Comment by erlend-aasland** [comment] 2023-08-29 19:47
> ...So I assume the rational for storing binary data in a sqlite3 VARCHAR is somewhere in the Chromium source..?

SQLite will let you put pretty much any data type into any column. See SQLite quirks: https://sqlite.org/quirks.html.

**Comment by erlend-aasland** [comment] 2023-08-29 20:06
@CorvinM wrote:

> Working on a patch for this.

Thanks; I'm curious how you indent to solve it :)

**Comment by CorvinM** [comment] 2023-08-29 21:10
> @CorvinM wrote:
> 
> > Working on a patch for this.
> 
> Thanks; I'm curious how you intend to solve it :)

I opened a draft PR #108657 for now. Would love to hear your thoughts if you want to take a peek.

**Comment by erlend-aasland** [comment] 2023-08-30 08:29
Thanks for the report, @dotysan, and thanks for the quick fix, @CorvinM!

**Comment by serhiy-storchaka** [comment] 2023-08-30 12:04
Is it a correct fix? When you execute commands from the result of `iterdump()`, will you get a DB with the same content? Note that Unicode string `\x9f` is equivalent to bytes sequence `\xc2\x9f`.

Did you try to use `conn.text_factory = lambda x: str(x, errors='surrogateescape')` or `conn.text_factory = lambda x: str(x, 'latin1')` as a workaround?

**Comment by erlend-aasland** [comment] 2023-08-30 12:13
> will you get a DB with the same content?

The SQLite shell will _not_ give you the same content, but it will not fail either; it gives you a complete dump, wrapped in a transaction. Using the example in this issue:

```
$ sqlite3 foo.db
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE foo (id INTEGER, data VARCHAR);
INSERT INTO foo VALUES(42,'a?');
COMMIT;
sqlite> ^D
```

I did not think of `surrogateescape`; it is indeed a more correct solution, as it does not translate `\x9f` to `\xc2\x9f`.

**Comment by erlend-aasland** [comment] 2023-08-30 12:18
Turns out the easiest fix was this one-liner, suggested by Serhiy:

```diff
diff --git a/Lib/sqlite3/dump.py b/Lib/sqlite3/dump.py
index ead3360ce6..55379c0349 100644
--- a/Lib/sqlite3/dump.py
+++ b/Lib/sqlite3/dump.py
@@ -25,6 +25,7 @@ def _iterdump(connection):
     """
 
     writeable_schema = False
+    connection.text_factory = lambda x: str(x, errors='surrogateescape')
     cu = connection.cursor()
     yield('BEGIN TRANSACTION;')
 
```

**Comment by CorvinM** [comment] 2023-08-30 19:43
> Is it a correct fix? When you execute commands from the result of `iterdump()`, will you get a DB with the same content? Note that Unicode string `\x9f` is equivalent to bytes sequence `\xc2\x9f`.
> 
> Did you try to use `conn.text_factory = lambda x: str(x, errors='surrogateescape')` or `conn.text_factory = lambda x: str(x, 'latin1')` as a workaround?

Surrogate-escape is actually different, I cannot get the same DB from iterdump when using it (its turing the \x9f into \udc9f) but can with the original chr() version. Adding a test to #108695 for dump reproducibility to check this.

**Comment by erlend-aasland** [comment] 2023-08-30 21:59
@serhiy-storchaka, @CorvinM: As an alternative, I created #108699 in order to try to solve this in documentation only.

**Comment by serhiy-storchaka** [comment] 2023-08-31 07:15
Let see. It is a complex issue, like every encoding issue.

The SQLite database can contain non UTF-8 sequences of bytes as a text. To work it around, there is a special mechanism: you can set `text_factory` to `bytes`, `bytearray` or custom factory which calls `str()` with other encoding or errors handler. What do you do with the result -- is your problem. If you get `bytes` or `bytearray`, you are responsible of decoding it. If you have a non-standard decoded string, you should use corresponding encoding when write it to a file or handle special characters in some way.

`iterdump()` has its own issues. It is not compatible with `bytes` and `bytearray`. When you use non-standard string decoding method, you can write it to file (using the correct encoding method) and feed to `sqlite3` command, but you cannot feed it to `execute()`.

So what can we do?

1. First of all, document the limitation of `iterdump()`, the workaround (seems, it is not well known) and the limitation of the workaround.
2. We can make `execute()` accepting non-UTF-8-encodable SQL statement and values. It should not be enabled by default, because it is easy to produce by accident a DB which breaks other programs. We can even use the same option to use surrogateescapes in results, it is more efficient than `text_factory = lambda x: str(x, errors='surrogateescape')`.
3. We can make `iterdump()` converting all surrogateescapes into `CAST(X'...' AS TEXT)`. Additional checks and transformations have a cost, so perhaps it should not be enabled by default. We can make `iterdump()` compatible with `text_factory = bytes`, but it will convert all TEXTs into BLOBs.

(2) and (3) are complex tasks and may require separate discussions about details. For example, should `text_factory` and new options be `Connection` or `Cursor` attributes, or parameters of `execute()`?

**Comment by erlend-aasland** [comment] 2023-08-31 07:32
> Let see. It is a complex issue, like every encoding issue.

+1

> So what can we do?
> 
> 1. First of all, document the limitation of `iterdump()`, the workaround (seems, it is not well known) and the limitation of the workaround.

IMO, this is the preferred solution. See #108699 for a draft docs update.

> 2. We can make `execute()` accepting non-UTF-8-encodable SQL statement and values. It should not be enabled by default, because it is easy to produce by accident a DB which breaks other programs. We can even use the same option to use surrogateescapes in results, it is more efficient than `text_factory = lambda x: str(x, errors='surrogateescape')`.

I'm not sure this is a good idea. The sqlite3 module is a DB API (PEP-249) implementation, and the DB API dictates the param spec of `execute()`. If we change that, we'd be drifting further away from the DB API, which IMO is not desirable.

> 3. We can make `iterdump()` converting all surrogateescapes into `CAST(X'...' AS TEXT)`. Additional checks and transformations have a cost, so perhaps it should not be enabled by default. We can make `iterdump()` compatible with `text_factory = bytes`, but it will convert all TEXTs into BLOBs.

Using `CAST(X'...' AS TEXT)` in the dump is a possibility. I'm not sure it is worth the added complexity, though.

**Comment by erlend-aasland** [comment] 2023-08-31 08:20
I suggest we focus on 1. for now, the docs update. Well, in my opinion, docs are as hard to get right as encoding issues, so feel free to chime in 😄

**Comment by serhiy-storchaka** [comment] 2023-08-31 09:53
> I suggest we focus on 1. for now, the docs update. Well, in my opinion, docs are as hard to get right as encoding issues, so feel free to chime in 😄

At least it works with older versions of Python.

**Comment by hugovk** [comment] 2023-11-09 22:03
I see lots of merged PRs for this issue. Can it be closed or is there more to be done?

**Comment by erlend-aasland** [comment] 2023-11-10 19:05
The sqlite3 docs now includes a section about encoding issues, so it should hopefully be easier to avoid issues like this. However, @serhiy-storchaka is not satisfied with how the docs turned out and has flagged that he wants to improve them further. Perhaps those improvements should be done in a separate issue, though.

I'm fine with closing this.

**Closed as completed by erlend-aasland** 2023-11-10 19:05 UTC
Labels: type-bug, 3.11, 3.12, topic-sqlite3, 3.13
