### ISSUE TITLE
TypeError in bisect when called with key argument

### ISSUE THREAD

**Issue by c-m-m-kobayashi** [python/cpython#117848] opened 2024-04-13 14:50 UTC
# Bug report

### Bug description:

bisect functions raise TypeError when called with _key_ argument.
Here is a minimum code to reproduce the issue:
```python
import bisect
import operator

a = [('one', 1), ('two', 2)]
print(bisect.bisect(a, ('one', 1), key=operator.itemgetter(0)))
```
This results in the following error:
```shell
Traceback (most recent call last):
  File "/path/to/bisect_test.py", line 5, in <module>
    print(bisect.bisect(a, ('one', 1), key=operator.itemgetter(0)))
          ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'tuple' and 'str'
```
It seems that picking an item in a tuple has a problem.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by nineteendo** [comment] 2024-04-13 15:09
I think you need to apply `key()` to `x`:

```diff
+x=key(x)
 while lo < hi:
     mid = (lo + hi) // 2
     if x < key(a[mid]):
         hi = mid
     else:
         lo = mid + 1
```

**Comment by nineteendo** [comment] 2024-04-13 15:30
See https://github.com/python/cpython/pull/20556#discussion_r432997024

**Comment by nineteendo** [comment] 2024-04-13 15:34
@AlexWaygood, could you close this? This works as intended.

**Comment by michikoba** [comment] 2024-04-13 15:47
@nineteendo Thank you for your comment.
Now I understand that giving the field to be compared is better than the entire record in bisect search.

**Closed as completed by michikoba** 2024-04-13 15:47 UTC
Labels: type-bug
