### ISSUE TITLE
The default unraisablehook implementation does not print chained exceptions or recurse into exception groups

### ISSUE THREAD

**Issue by graingert** [python/cpython#95572] opened 2022-08-02 13:46 UTC
here's a demo in the repl

```
>>> class Foo:
...     def __del__(self):
...         raise BaseExceptionGroup("the bad", [Exception("critical debug advice here")])
... 
>>> f = Foo()
>>> del f
Exception ignored in: <function Foo.__del__ at 0x7f2f59df2200>
Traceback (most recent call last):
  File "<stdin>", line 3, in __del__
ExceptionGroup: the bad (1 sub-exception)
>>> 
```

@vstinner @iritkatriel I'm not sure if this is an omission or by design, but if an exception with critical debug advice is raised in an exceptiongroup during `__del__` I can't see the type or error message

I expected the output to include:

```
  + Exception Group Traceback (most recent call last):
  |   File "<stdin>", line 1, in <module>
  | ExceptionGroup: the bad (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception: critical debug advice here
    +------------------------------------
```

**Comment by iritkatriel** [comment] 2022-08-02 14:22
Looks like the default unraisable hook has its own implementation of exception printing. Why isn't it just calling ``_PyErr_Display``?

**Comment by graingert** [comment] 2022-08-02 14:32
looks like the threading.excepthook does the right thing:

```
>>> t = threading.Thread(target=raise_, args=(BaseExceptionGroup("the bad", [Exception("critical debug advice here")]),))
>>> t.start()
Exception in thread Thread-4 (raise_):
  + Exception Group Traceback (most recent call last):
  |   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
  |     self.run()
  |   File "/usr/lib/python3.11/threading.py", line 975, in run
  |     self._target(*self._args, **self._kwargs)
  |   File "<stdin>", line 1, in raise_
  | ExceptionGroup: the bad (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception: critical debug advice here
    +------------------------------------
>>> t.join()
>>> 
```

**Comment by graingert** [comment] 2022-08-02 16:57
> Looks like the default unraisable hook has its own implementation of exception printing. Why isn't it just calling `_PyErr_Display`?

if this is a bug in unraisable hook can we get the fix backported to 3.10 so the exceptiongroup backport can use it?

**Comment by iritkatriel** [comment] 2022-08-02 17:00
I don't know if this is a bug or an enhancement. In any case it's hookable, right?

**Comment by iritkatriel** [comment] 2022-08-03 05:44
> > Looks like the default unraisable hook has its own implementation of exception printing. Why isn't it just calling `_PyErr_Display`?
> 
> if this is a bug in unraisable hook can we get the fix backported to 3.10 so the exceptiongroup backport can use it?

I don't think back porting this even could affect the exception group backport - in 3.10 ``_PyErr_Display()`` doesn't know anything about exception groups.

**Comment by iritkatriel** [comment] 2022-08-03 06:07
The default unraisablehook doesn't print chained exceptions either. 

I think this may be deliberate to avoid recursion when the interpreter could be in a delicate state (e.g. under memory pressure).  This is definitely not a bugfix. I'm removing 3.11.

**Comment by graingert** [comment] 2022-08-03 07:49
in the backport if I delete the custom `__str__` on BaseExceptionGroup, I get closer to the desired behavior:

```
>>> del exceptiongroup.BaseExceptionGroup.__str__
>>> class Foo:
...     def __del__(self):
...         raise exceptiongroup.BaseExceptionGroup("the bad", [Exception("critical debug information")])
... 
>>> f = Foo()
>>> del f
Exception ignored in: <function Foo.__del__ at 0x7f65d65ade10>
Traceback (most recent call last):
  File "<stdin>", line 3, in __del__
exceptiongroup.ExceptionGroup: ('the bad', [Exception('critical debug information')])
>>> 
```

**Comment by iritkatriel** [comment] 2022-08-03 08:53
Yes, but then the normal tracebacks will probably have the strs of the nested exceptions twice.

**Comment by graingert** [comment] 2022-08-03 12:02
I've seen a fair bit of code that does "print(type(e)), print(e)" for "logging" and results in output like "<class 'ExceptionGroup'>: exception in task group (1 sub-exception)"

I think the normal tracebacks should change how ExceptionGroup is printed and the `ExceptionGroup.__str__` should keep the default `__str__`

**Comment by iritkatriel** [comment] 2022-08-03 12:10
> I think the normal tracebacks should change how ExceptionGroup is printed and the `ExceptionGroup.__str__` should keep the default `__str__`

I don't understand the suggestion.

**Comment by iritkatriel** [comment] 2022-08-03 12:18
We can't keep the default ``__str__`` because the list of nested exceptions can be very large and we would need to limit the number of exceptions we include in the output. We could implement ``str`` that prints a few of the nested exceptions, but I'm not sure that's better (how do you know which ones have critical info on them?).

How are you proposing to change the normal tracebacks?

**Comment by graingert** [comment] 2022-08-11 07:34
> We could implement str that prints a few of the nested exceptions, but I'm not sure that's better (how do you know which ones have critical info on them?).

> How are you proposing to change the normal tracebacks?
The normal tracebacks wouldn't change in appearance, I'm suggesting they special case ExceptionGroup outright

Specifically they would not call `ExceptionGroup.__str__` and would print `ExceptionGroup: {message} ({n} sub-exception{plural})`

**Comment by iritkatriel** [comment] 2022-08-11 07:42
What if you subclasses ExceptionGroup and redefined str?

**Comment by gvanrossum** [comment] 2024-01-05 21:40
I would honestly close this as "won't fix". I don't see the point of spending the resources on trying to improve this corner case without making things more fragile.

**Comment by iritkatriel** [comment] 2024-01-05 22:26
I agree, this is hookable so anyone can implement what they need anyway.

**Closed as not planned by iritkatriel** 2024-01-05 22:26 UTC
Labels: type-feature, interpreter-core, 3.13
