### ISSUE TITLE
Using multiprocessing and Kivy at the same time causes error on Windows

### ISSUE THREAD

**Issue by emoto-yasushi** [python/cpython#112056] opened 2023-11-14 13:11 UTC
# Bug report

### Bug description:

I used to use threading.thread when doing other processing in parallel with Kivy, but I have found that threading.thread is chopy when I want to run a program with a large processing load on the CPU. Checking the task manager, it seems that it may become chopy even though the CPU usage is not high.

This is why I am looking into the multiprocessing spec in Python, but it is not working with an error. As shown below, I use a UI library called Kivy and when I press the button that comes up, the program runs, but I get an error.

```python
#-*- coding: utf-8 -*-

from kivy.lang import Builder
Builder.load_string("""
<TextWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        Button:
            id: button1
            text: "start"
            font_size: 48
            on_press: root.buttonClicked()
""")

from kivy.app import App
from kivy.uix.widget import Widget

from kivy.properties import StringProperty 
import threading
import time
from multiprocessing import Process

class TextWidget(Widget):

    def __init__(self, **kwargs):
        super(TextWidget, self).__init__(**kwargs)
        self.process_test = None
        
    def p_test(self):
        print("Hello")
        print("Sleeping... 3s")
        time.sleep(3)
        print("Good morning")

    def buttonClicked(self):
        if self.ids.button1.text == "start":
            self.process_test = Process(target=self.p_test, args=())
            self.process_test.start()
            self.ids.button1.text = "stop"
        else:
            self.process_test.join()
            self.ids.button1.text = "start"
            

class TestApp(App):
    def __init__(self, **kwargs):
        super(TestApp, self).__init__(**kwargs)
        self.title = 'testApp'

    def build(self):
        return TextWidget()

if __name__ == '__main__':
    TestApp().run()
```

The error message is as follows
```
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "C:\Users\taichi\Documents\Winpython64-3.11.5.0\WPy64-31150\python-3.11.5.amd64\Lib\multiprocessing\spawn.py", line 122, in spawn_main
     exitcode = _main(fd, parent_sentinel)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\taichi\Documents\Winpython64-3.11.5.0\WPy64-31150\python-3.11.5.amd64\Lib\multiprocessing\spawn.py", line 132, in _main
     self = reduction.pickle.load(from_parent)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 EOFError: Ran out of input
```

I have also [posted this issue on StackOverflow](https://stackoverflow.com/questions/77471934/how-to-get-multiprocessing-working-in-python-with-kivy). According to other Python users, this code seems to work fine on Ubuntu; it seems to be a bug that only happens on Windows.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by zooba** [comment] 2023-11-14 13:24
Calling a function with multiprocessing requires launching a new copy of Python, importing your module, and passing across referenced values. In this case, you are referencing `self`, which is a Kivy widget that represents a GUI control.

It is incredibly unlikely that this can be pickled and transferred to another process. Windows does not support multiple processes owning the same GUI element - they are inherently per-process.

What you'll need to do is to move your multiprocessing state to its own object, making sure it can be pickled (if it only contains basic Python types it should be fine), and referencing that instead of the GUI. This roughly equates to using an MVC design pattern, which I'd strongly suggest researching if you are going to build complex GUI apps (I wouldn't worry about strictly adhering to the pattern at all times, but simply being aware of it will help you implement better separation between your app's components).

You may also need to move all your Kivy related imports and definitions under `if __name__ == '__main__'` so that they aren't defined in every single new process you launch. At the very least, it will make things run faster, but it might also be necessary depending on how Kivy implements things.

I'd suggest asking in the Help section at https://discuss.python.org. This is not a bug in CPython, but you should get some good advice and feedback from the people in that community.

**Closed as not planned by zooba** 2023-11-14 13:24 UTC
Labels: type-bug, OS-windows, topic-multiprocessing

**Comment by emoto-yasushi** [comment] 2023-11-15 01:09
Following your advice, I tried posting on that page.
[https://discuss.python.org/t/using-multiprocessing-issue-with-kivy/38716](https://discuss.python.org/t/using-multiprocessing-issue-with-kivy/38716)
