### ISSUE TITLE
Error while installing the library

### ISSUE THREAD

**Issue by saiveeranki** [python/cpython#101929] opened 2023-02-15 08:28 UTC
library multiprocessing

ERROR: Command errored out with exit status 1:

print 'Macros:'
            ^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Macros:')?

**Comment by thiyagarajan17** [comment] 2023-02-15 08:29
assign issue to me. would love to take a look into it

**Comment by thiyagarajan17** [comment] 2023-02-15 08:32
Go with the syntax error suggestions. exit status 1 takes the same cue

**Comment by saiveeranki** [comment] 2023-02-15 08:45
@thiyagarajan17 can i assign the issue to you?

**Comment by arhadthedev** [comment] 2023-02-15 08:51
> print 'Macros:'

Use `print('Macros:')` as the error message suggests.

**Comment by ericvsmith** [comment] 2023-02-15 08:52
It looks like you're trying to run python2 code with python3.

This is not a bug in python. I suggest you ask a question on https://discuss.python.org/c/users/7. When you do that, you'll need to provide more information, like what code you were running which caused this problem.

**Comment by arhadthedev** [comment] 2023-02-15 08:52
Closing as an issue not caused by the interpreter.

**Closed as not planned** 2023-02-15 08:52 UTC

**Comment by saiveeranki** [comment] 2023-02-15 09:22
Thank you, sorry for causing any unnecessary trouble. 
I was trying to install multiprocessing using pip3 install multiprocessing like i do for any other library.

**Comment by stevendaprano** [comment] 2023-02-15 09:50
> I was trying to install multiprocessing using pip3 install multiprocessing like i do for any other library.

You don't have to install multiprocessing, it is [a standard Python module](https://docs.python.org/3/library/multiprocessing.html). You only need to [install it with pip](https://pypi.org/project/multiprocessing/) if you are running Python 2.6 or 3.0, both of which are so many years out of date that you should not use them.
