### ISSUE TITLE
re.findall: '\Z' must consume end of string if it matched

### ISSUE THREAD

**Issue by 84cae046-a27b-4ad9-bf51-e627d9912443** [python/cpython#87880] opened 2021-04-03 13:03 UTC
BPO | [43714](https://bugs.python.org/issue43714)
--- | :---
Nosy | @terryjreedy, @ezio-melotti, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-03.13:03:13.339>
labels = ['type-bug', 'library', '3.9', '3.10']
title = "re.findall: '\\Z' must consume end of string if it matched"
updated_at = <Date 2021-04-10.07:33:07.809>
user = 'https://bugs.python.org/alegrigoriev'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-10.07:33:07.809>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-04-03.13:03:13.339>
creator = 'alegrigoriev'
dependencies = []
files = []
hgrepos = []
issue_num = 43714
keywords = []
message_count = 5.0
messages = ['390124', '390127', '390169', '390686', '390699']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'alegrigoriev']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43714'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by serhiy-storchaka** [comment] 2022-04-22 17:42
Closed as "not a bug".

**Closed as completed by serhiy-storchaka** 2022-04-22 17:42 UTC
Labels: type-bug, stdlib, topic-regex, 3.10, 3.9 (EOL)
