### ISSUE TITLE
`os.path.isabs` change in behavior in Python 3.13 on MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [python/cpython#125283] opened 2024-10-10 21:40 UTC
# Bug report

### Bug description:

I'm not sure if this is a fix or a regression issue?

`os.path.isabs` use to return True when a windows path started with `/`.

In python 3.13
```python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os.path
>>> os.path.isabs("/c:")
False
```
In python 3.12
```python
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os.path
>>> os.path.isabs("/c:")
True
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by nineteendo** [comment] 2024-10-11 06:06
Works as intended: #113829, maybe a new function could be considered to check if a path is rooted?

**Comment by ikappaki** [comment] 2024-10-11 06:59
> Works as intended: #113829, maybe a new function could be considered to check if a path is rooted?

This behavior changes how `os.path.isabs` interacts with `urllib.parse.urlparse` when dealing with absolute paths in Windows URIs. In Python 3.12, paths parsed from local file URIs (drive and network paths) were recognized as absolute, but in Python 3.13, they no longer are
```python
import os.path
import pathlib
import urllib.parse

>>> urllib.parse.urlparse(pathlib.Path('c:\\xyz').as_uri())
ParseResult(scheme='file', netloc='', path='/c:/xyz', params='', query='', fragment='')
>>> urllib.parse.urlparse(pathlib.Path('\\\\machine\\xyz').as_uri())
ParseResult(scheme='file', netloc='machine', path='/xyz/', params='', query='', fragment='')
```

In Python 3.12, `os.path.isabs` would correctly identify these paths as absolute, including network paths:
```python
>>> os.path.isabs(urllib.parse.urlparse(pathlib.Path('c:\\xyz').as_uri()).path)
True
>>> os.path.isabs(urllib.parse.urlparse(pathlib.Path('\\\\machine\\xyz').as_uri()).path)
True
```

but not any more in 3.13

```python
>>> os.path.isabs(urllib.parse.urlparse(pathlib.Path('c:\\xyz').as_uri()).path)
False
>>> os.path.isabs(urllib.parse.urlparse(pathlib.Path('\\\\machine\\xyz').as_uri()).path)
False
```

It seems as if `os.path.isabs` was never intended to be used with ParseResult `path`s. I suppose a more appropriate solution would be to directly check if the `path` starts with '/', which would indicate that it's absolute.

**Comment by marc-hb** [comment] 2024-10-11 15:22
> Also, aren't uri's always absolute?

Relative URLs work perfectly fine.

**Comment by nineteendo** [comment] 2024-10-11 15:33
Well, at least `pathlib` doesn't allow creating them.

**Comment by barneygale** [comment] 2024-10-11 18:26
> It seems as if `os.path.isabs` was never intended to be used with ParseResult `path`s. I suppose a more appropriate solution would be to directly check if the `path` starts with '/', which would indicate that it's absolute.

Checking whether it starts with a `/` makes most sense to me. Another option is `posixpath.isabs()`.

**Comment by nineteendo** [comment] 2024-10-11 18:50
Use `p.scheme and p.netloc and p.path.startswith("/")` to check if a uri is absolute, an absolute path doesn't change when joined with another path:

```python
>>> import urllib.parse
>>> urllib.parse.urljoin("file://netloc/foo/", "bar")
'file://netloc/foo/bar'
>>> urllib.parse.urljoin("file://netloc/foo/", "/bar")
'file://netloc/bar'
>>> urllib.parse.urljoin("file://netloc/foo/", "//netloc2/bar")
'file://netloc2/bar'
>>> urllib.parse.urljoin("file://netloc/foo/", "file://netloc2/bar")
'file://netloc2/bar'
```

That's also why we changed the behaviour of `os.path.isabs()`:

```python
>>> import os.path
>>> os.path.join(r"c:\foo", "bar")
'c:\\foo\\bar'
>>> os.path.join(r"c:\foo", r"\bar")
'c:\\bar'
>>> os.path.join(r"c:\foo", r"d:\bar")
'd:\\bar'
```

**Comment by nineteendo** [comment] 2024-10-11 18:53
I think this can be closed.

**Comment by barneygale** [comment] 2024-10-11 18:54
Thanks @nineteendo! Closing.

**Closed as not planned by barneygale** 2024-10-11 18:54 UTC
Labels: type-bug, OS-windows, stdlib, 3.13

**Comment by barneygale** [comment] 2024-12-03 21:09
Hey @kayychou - `"\\foo\\bar"` expresses a string that begins with a _single_ backslash. If you want two backslashes, you could use a raw string (`r"\\foo\bar"`) or double the backslashes (`"\\\\foo\\bar"`)
