### ISSUE TITLE
signal.signal, et al, doesn't support [SIGRTMIN,SIGRTMAX] on FreeBSD (not included in NSIG)

### ISSUE THREAD

**Issue by cd099432-c439-4196-9816-d22314ec360c** [python/cpython#91145] opened 2022-03-11 19:12 UTC
BPO | [46989](https://bugs.python.org/issue46989)
--- | :---
Nosy | @ngie-eign, @koobs

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-11.19:12:02.712>
labels = ['3.7', '3.8', '3.9', '3.10', '3.11']
title = "signal.signal, et al, doesn't support [SIGRTMIN,SIGRTMAX] on FreeBSD (not included in NSIG)"
updated_at = <Date 2022-03-11.19:12:02.712>
user = 'https://github.com/ngie-eign'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-11.19:12:02.712>
actor = 'ngie'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['FreeBSD']
creation = <Date 2022-03-11.19:12:02.712>
creator = 'ngie'
dependencies = []
files = []
hgrepos = []
issue_num = 46989
keywords = []
message_count = 1.0
messages = ['414932']
nosy_count = 2.0
nosy_names = ['ngie', 'koobs']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46989'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by vstinner** [comment] 2022-04-25 21:57
This issue is a duplicate of #64783.

**Comment by tiran** [comment] 2022-05-05 21:19
The test is incorrect and breaks Emscripten because it also checks the value of ``SIG_IGN`` and ``SIG_DFL``. Both constants are not values but actually pointers we just happen to be ``0`` and ``1`` on most POSIX-like OS.

**Comment by vstinner** [comment] 2022-05-05 23:19
It seems like it has been fixed by https://github.com/python/cpython/pull/92350

**Closed as completed by vstinner** 2022-05-05 23:19 UTC
Labels: 3.11, 3.10, 3.9 (EOL), 3.8 (EOL), 3.7 (EOL), OS-freebsd
