### ISSUE TITLE
Python turtledemo clock stop does not clear time

### ISSUE THREAD

**Issue by DannyWuzhiheng** [python/cpython#125187] opened 2024-10-09 12:49 UTC
# Bug report

### Bug description:

`clock`turtle demo's time can't be cleared
![pic](https://s3.bmp.ovh/imgs/2024/10/09/e78139abbf3ce2b7.png)

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment] 2024-10-09 14:45
Duplicate of #123370, which has a fix nearly done.

**Comment by Wulian233** [comment] 2024-10-17 22:27
Fixed we can close this
https://github.com/python/cpython/pull/123457

**Closed as not planned** 2024-10-18 04:45 UTC
Labels: type-bug, stdlib

**Comment by terryjreedy** [comment] 2024-10-18 06:32
I meant to close this as a duplicate last week, as is our usual policy for such cases.
