### ISSUE TITLE
Allow to set non-UTF8 exception messages

### ISSUE THREAD

**Issue by picnixz** [python/cpython#126742] opened 2024-11-12 13:50 UTC
# Feature or enhancement

### Proposal:

This is a follow-up to the discussion in https://github.com/python/cpython/pull/126555#discussion_r1837812348. 

`dlerror()` may return non-UTF-8 messages, possibly translated. We should be able to set exception messages according to the current locale. To that end, we'll expose some internal helper:

```C
extern void 
_PyErr_SetLocaleStringTstate(PyThreadState *tstate, PyObject *exception, const char *string);

extern void
_PyErr_SetLocaleString(PyObject *exception, const char *string);
```

cc @ZeroIntensity @encukou 

For now, both functions would be only declared as `extern` and not part of the public C API.

### Linked PRs
* gh-126746
* gh-128023
* gh-128027

* gh-128034
* gh-128056
* gh-128057
* gh-128025
* gh-128059
* gh-128060

**Comment by picnixz** [comment] 2024-11-12 13:52
Let's actually mark it as a bugfix since we'll need to backport it in order to use it later.

**Comment by ZeroIntensity** [comment] 2024-11-12 13:55
Hmm, so is `PyErr_SetLocaleString` supposed to be implicitly private? I'm not the biggest fan of that--if something is supposed to be private, then we need to prefix it with `_`, not only so users don't touch, but so people reading the source don't mistake it as public. If we want a variation of it that takes a thread state, we could have something like `_PyErr_SetLocaleStringTstate`.

**Comment by picnixz** [comment] 2024-11-12 13:57
> Hmm, so is PyErr_SetLocaleString supposed to be implicitly private

For now, but maybe we can directly expose to the C API? I want to be consistent with the naming of each function.

**Comment by encukou** [comment] 2024-11-12 14:47
How many places in the code would use this helper? I don't see the advantage over calling `PyUnicode_DecodeLocale` and `PyErr_SetObject`.

**Comment by picnixz** [comment] 2024-11-12 14:51
There are a few occurrences of `dlerror()` in `_ctypes.c` and `callproc.c` and `dynload_shlib` as well.

**Comment by encukou** [comment] 2024-11-12 15:14
`errors.c` uses `PyUnicode_DecodeLocale` (with `surrogateescape`) on `strerror()`'s result. That looks like a good precedent.

I don't think it's worth it to add a project-wide helper here. Calling the 2 functions should be fine.

**Comment by ZeroIntensity** [comment] 2024-11-12 15:19
My main arguments for adding a new internal function would be that a) it helps remove the risk of reference leaks (which in my experience, are all too common when dealing with string mutations) and b) makes it easier to deal with locale in the future (we have incorrect uses of `dlerror()` internally that skip the locale check).

**Comment by encukou** [comment] 2024-11-13 09:43
As far as I know, this is not a bug on any supported/known platforms, and so can't be tested in our CI. It's also not been reported/patched on any other platform I know of.

I don't know if it should be called a “bug” (that's more a question about the definition of the term), but I don't think a fix for this issue should be backported. Let's just improve `main`.

As for the helper: IMO, it's better to *first* fix the code, and *then*, if it makes sense, refactor to add a helper. In clear-cut cases you'd combine the steps in one commit, but let's not do that here.

**Comment by serhiy-storchaka** [comment] 2024-11-29 13:31
I do not mind to add a private helper if it can be used in multiple files, but I am not sure about a public API. It is just a combination of two functions, and this pattern may be not so common.

Some examples in the PR looks wrong. Set an error with locale-decoded error message, then clear it and set an error with utf8-decoded error message -- this pattern looks very wrong.

**Comment by picnixz** [comment] 2024-11-29 13:34
> Set an error with locale-decoded error message, then clear it and set an error with utf8-decoded error message -- this pattern looks very wrong

This pattern is actually a way to fallback to a generic message. Otherwise, there will be no error message at all, which can be more confusing IMO. We only clear the error if the decoding fails (for whatever reason). Such pattern already existed when handling `dlerror()`.

**Comment by picnixz** [comment] 2024-12-17 11:15
A `_PyErr_SetLocaleString` has

**Closed as completed** 2024-12-17 11:16 UTC
Labels: type-bug, interpreter-core, topic-C-API, 3.12, 3.13, 3.14

**Comment by picnixz** [comment] 2024-12-17 12:57
I changed the labels since we decideed to eventually treat this as a bug fix.
