### ISSUE TITLE
Error in Documentation Style

### ISSUE THREAD

**Issue by utkonos** [python/cpython#95725] opened 2022-08-05 20:48 UTC
# Documentation

The documentation pages appear to have a style problem. Pages with a note of some type at the top now have the note's background color bleeding down the whole page. If this was an intentional change, no problem, it just looks strange now. You can see the old vs new on archive.org.

Here is the old `csv` documentation:
https://web.archive.org/web/20220712195820/https://docs.python.org/3/library/csv.html

<img width="839" alt="image" src="https://user-images.githubusercontent.com/2775739/183159513-452635c8-15a4-4a49-89e3-db309b0d0bc1.png">

Here is the current:
https://web.archive.org/web/20220805204234/https://docs.python.org/3/library/csv.html

<img width="829" alt="image" src="https://user-images.githubusercontent.com/2775739/183159842-cb6d265f-08ce-4871-b06e-85bd807f326a.png">

Here is `json`:
https://web.archive.org/web/20220722160241/https://docs.python.org/3/library/json.html

<img width="831" alt="image" src="https://user-images.githubusercontent.com/2775739/183160031-74006fc7-5c1e-4df1-af33-65972db11fc5.png">

Here is the current:
https://web.archive.org/web/20220805204612/https://docs.python.org/3/library/json.html

<img width="832" alt="image" src="https://user-images.githubusercontent.com/2775739/183160175-2d216264-3e4f-4b46-8d55-8d679917324b.png">

If this was intentional, it might be a good idea to revert it. The old style was cleaner and easier to read.

**Comment by zware** [comment] 2022-08-05 20:50
Duplicate of #91483.

**Closed as not planned by zware** 2022-08-05 20:50 UTC
Labels: docs
