### ISSUE TITLE
Disassembly of Lambdas in 3.11.1 missing stack values and args

### ISSUE THREAD

**Issue by jrmccluskey** [python/cpython#102403] opened 2023-03-03 19:50 UTC
# Bug report

I'm working on updating a [type hinting and inference module in Apache Beam](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/typehints/trivial_inference.py) to support CPython 3.11 opcodes and have hit a snag working with test cases involving lambdas. The line `dis.dis(lambda: {x for x in ()}, show_caches=True, adaptive=False)` return the following in 3.10:

```
1          0 LOAD_CONST               1   (<code object <setcomp> at 0x7fd2f2b1f5d0, file "<stdin>", line 1>)
              2 LOAD_CONST               2 ('TrivialInferenceTest.testSet.<locals>.<lambda>.<locals>.<setcomp>')
              4 MAKE_FUNCTION            0
              6 LOAD_CONST               3 (())
              8 GET_ITER
             10 CALL_FUNCTION            1
             12 RETURN_VALUE

Disassembly of <code object <setcomp> at 0x7fd2f2b1f5d0, file "<stdin>", line 1>:
346           0 BUILD_SET                0
              2 LOAD_FAST                0 (.0)
        >>    4 FOR_ITER                 4 (to 14)
              6 STORE_FAST               1 (x)
              8 LOAD_FAST                1 (x)
             10 SET_ADD                  2
             12 JUMP_ABSOLUTE            2 (to 4)
        >>   14 RETURN_VALUE
```

But in 3.11 we get:
```
  1           0 RESUME                   0
              2 LOAD_CONST               1 (<code object <setcomp> at 0x7fd2f2b1f5d0, file "<stdin>", line 1>)
              4 MAKE_FUNCTION            0
              6 LOAD_CONST               2 (())
              8 GET_ITER
             10 PRECALL                  0
             12 CACHE                    0
             14 CALL                     0
             16 CACHE                    0
             18 CACHE                    0
             20 CACHE                    0
             22 CACHE                    0
             24 RETURN_VALUE

Disassembly of <code object <setcomp> at 0x7fd2f2b1f5d0, file "<stdin>", line 1>:
  1           0 RESUME                   0
              2 BUILD_SET                0
              4 LOAD_FAST                0 (.0)
        >>    6 FOR_ITER                 4 (to 16)
              8 STORE_FAST               1 (x)
             10 LOAD_FAST                1 (x)
             12 SET_ADD                  2
             14 JUMP_BACKWARD            5 (to 6)
        >>   16 RETURN_VALUE
```

The 3.11 output has two distinct difference: it isn't pushing a qualified name for the lambda onto the stack for `MAKE_FUNCTION`, and the `PRECALL` and `CALL` opcodes have args of 0 indicating that there are no args to be passed to the function despite there being a constant on the top of the stack when `CALL` is executed. Is this expected behavior? I haven't been able to find any documentation around lambda handling being changed, and the existing documentation for the opcodes leads me to believe this is unintended.

# Your environment

- CPython versions tested on: 3.10, 3.11
- Operating system and architecture: Linux, x86

**Comment by iritkatriel** [comment] 2023-04-25 14:51
Closing as the issue is unclear and there has been for response to followup questions.

**Closed as not planned by iritkatriel** 2023-04-25 14:51 UTC
Labels: type-bug

**Comment by robertwb** [comment] 2023-09-12 15:41
I ran into this as well. 

At instruction 14 there are two elements on the stack (the iterable on top of the anonymous comprehension lambda) which should both be consumed, and indeed the called function expects an argument and pulls it off the stack (instruction 4), yet the CALL (and preceding PRECALL) have an argument of 0.
