### ISSUE TITLE
configure script cannot detect float word ordering on linux

### ISSUE THREAD

**Issue by 066556ba-7af7-46d2-9c9a-2c6e63902e21** [python/cpython#89640] opened 2021-10-14 21:19 UTC
BPO | [45477](https://bugs.python.org/issue45477)
--- | :---
Nosy | @tiran
Files | <li>[config.log](https://bugs.python.org/file50364/config.log "Uploaded as text/plain at 2021-10-16.16:27:29 by sourish.basu")</li><li>[conftest.o](https://bugs.python.org/file50374/conftest.o "Uploaded as application/octet-stream at 2021-10-20.13:23:38 by sourish.basu")</li><li>[conftest.c](https://bugs.python.org/file50375/conftest.c "Uploaded as text/plain at 2021-10-20.13:23:53 by sourish.basu")</li><li>[conftest_unoptimized.o](https://bugs.python.org/file50376/conftest_unoptimized.o "Uploaded as application/octet-stream at 2021-10-20.14:08:43 by sourish.basu")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-14.21:19:53.235>
labels = ['build', 'expert-installation', '3.10']
title = 'configure script cannot detect float word ordering on linux'
updated_at = <Date 2021-10-22.22:49:31.555>
user = 'https://bugs.python.org/sourishbasu'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-22.22:49:31.555>
actor = 'sourish.basu'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation']
creation = <Date 2021-10-14.21:19:53.235>
creator = 'sourish.basu'
dependencies = []
files = ['50364', '50374', '50375', '50376']
hgrepos = []
issue_num = 45477
keywords = []
message_count = 12.0
messages = ['403951', '403978', '404096', '404135', '404138', '404447', '404448', '404449', '404450', '404459', '404463', '404836']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'sourish.basu']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue45477'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-125571
* gh-126387
* gh-126429
* gh-126430
* gh-126569
* gh-126747

**Comment by kumaraditya303** [comment] 2022-07-23 11:33
Closing as this is not a CPython issue but rather a compiler bug and icc is not supported as per PEP 11.

**Comment by damelang** [comment] 2023-06-07 20:28
Author of the AX_C_FLOAT_WORDS_BIGENDIAN macro here. I committed a permanent fix to this issue in 
Autoconf Archive (see above, commit 23be7cc). Update to latest and you should be able to close this issue once and for all.

**Comment by mikoxyz** [comment] 2023-12-31 07:52
Pinging @tiran; without the updated macro, float word ordering won't be detected if e.g. -flto is present in one's CFLAGS.

**Comment by yan12125** [comment] 2024-02-13 16:42
There is a CI job that verifies generated files (autoconf-related and some others) match those found on ubuntu 22.04:
https://github.com/python/cpython/blob/681778c56a9204d65b8857e7ceba57f2c638671d/.github/workflows/build.yml#L121
As a result, CPython may need to wait for a new autoconf-archive Ubuntu package that includes the fix (https://github.com/autoconf-archive/autoconf-archive/pull/279)

**Comment by erlend-aasland** [comment] 2024-02-21 09:04
> Author of the AX_C_FLOAT_WORDS_BIGENDIAN macro here. I committed a permanent fix to this issue in Autoconf Archive (see above, commit 23be7cc). Update to latest and you should be able to close this issue once and for all.

Was this included in Autoconf 2.71, or must we upgrade to Autoconf 2.72?

**Comment by erlend-aasland** [comment] 2024-02-21 09:56
> It's in autoconf-archive, which is a separate collection of autoconf macros, namespaced `AX_*`.

Ah, yes of course. Unless Ubuntu 22.04 upgrades autoconf-archive, we'd have to explicitly force `Tools/build/regen-configure.sh` to use the new version. Our CI check is currently (and surprisingly) a lot more forgiving than it used to be, so I don't think we'd have to do anything with that.

**Comment by yan12125** [comment] 2024-02-24 04:54
> Unless Ubuntu 22.04 upgrades autoconf-archive, we'd have to explicitly force `Tools/build/regen-configure.sh` to use the new version

It may take months or even years to get fixed autoconf-archive into a Ubuntu LTS version. How about vendoring the latest `ax_c_float_words_bigendian.m4` for now? For example: https://github.com/python/cpython/compare/main...yan12125:cpython:issue89640

**Comment by damelang** [comment] 2024-02-25 06:06
> > Unless Ubuntu 22.04 upgrades autoconf-archive, we'd have to explicitly force `Tools/build/regen-configure.sh` to use the new version
> 
> How about vendoring the latest `ax_c_float_words_bigendian.m4` for now?
(followed by copy, paste, and renaming of code)

Although the license on my code permits this, I would really prefer you all take the force-to-newer-version approach. (If those are the only two options.)

The copy-paste-rename approach severs the link between the codebases. People have done copy-paste-rename with this very same code before, and it ends up causing headaches for maintainers and myself. I still get emails from people about some out-of-date / hacked up version of this code (often they don't even know where the code came from).

So, please, not the copy-paste-rename route?

**Comment by erlend-aasland** [comment] 2024-02-25 22:42
> So, please, not the copy-paste-rename route?

I agree, let's not take that route. Forcing the regen script to use the an updated version of autoconf-archive sounds like the best option so far. I'll see if I can find time for this the coming week.

**Comment by erlend-aasland** [comment] 2024-02-26 23:30
FTR, Ubuntu 24.04 ships with autoconf-archive 20220903.

**Comment by erlend-aasland** [comment] 2024-02-26 23:56
> I committed a permanent fix to this issue in Autoconf Archive (see above, commit 23be7cc). Update to latest and you should be able to close this issue once and for all.

@damelang, ISTM there is no official autoconf-archive release containing this commit. Do you know when the next release is scheduled?

**Comment by damelang** [comment] 2024-02-27 18:58
> @damelang, ISTM there is no official autoconf-archive release containing this commit. Do you know when the next release is scheduled?

I don't. I think it's an "as needed" kind of thing. I'll ping the owner to let him know that there is need. Will report back.

**Comment by yan12125** [comment] 2024-03-02 11:24
> So, please, not the copy-paste-rename route?

Sorry for the bad example, I removed it

> FTR, Ubuntu 24.04 ships with autoconf-archive 20220903.

That seems inherited from Debian, which is also on 20220903 https://tracker.debian.org/pkg/autoconf-archive

**Comment by erlend-aasland** [comment] 2024-03-02 12:01
Yes, Donghee and I are working on a container (like we had until recently). This way, we can explicitly control the autoconf and autoconf-archive version.

**Comment by damelang** [comment] 2024-03-04 20:17
> > @damelang, ISTM there is no official autoconf-archive release containing this commit. Do you know when the next release is scheduled?
> 
> I don't. I think it's an "as needed" kind of thing. I'll ping the owner to let him know that there is need. Will report back.

The owner (@peti) hasn't responded to my email from last week. Maybe he'll see this?

**Comment by erlend-aasland** [comment] 2024-10-15 21:35
There's been no release of autoconf-archive so far. As a workaround, until a new version is released, we can apply @damelang's https://github.com/autoconf-archive/autoconf-archive/pull/279 to our autoconf container.

**Comment by erlend-aasland** [comment] 2024-10-31 10:29
#125571 broke Emscripten; see https://github.com/python/cpython/pull/125571#issuecomment-2447535342 for a reproducer.

**Comment by hoodmane** [comment] 2024-10-31 16:21
I made a PR to autotools-archive to fix this:
https://github.com/autoconf-archive/autoconf-archive/pull/316/
I've locally confirmed the fix.

**Comment by erlend-aasland** [comment] 2024-11-01 22:58
@hoodmane, how about this:

<details>

```diff
diff --git a/configure.ac b/configure.ac
index 6a98cc5e2a0..60ffe6a67c4 100644
--- a/configure.ac
+++ b/configure.ac
@@ -5946,28 +5946,26 @@ AS_VAR_IF([ac_cv_gcc_asm_for_x64], [yes], [
 # * Check for various properties of floating point *
 # **************************************************
 
-AX_C_FLOAT_WORDS_BIGENDIAN
-if test "$ax_cv_c_float_words_bigendian" = "yes"
-then
-  AC_DEFINE([DOUBLE_IS_BIG_ENDIAN_IEEE754], [1],
-  [Define if C doubles are 64-bit IEEE 754 binary format, stored
-   with the most significant byte first])
-elif test "$ax_cv_c_float_words_bigendian" = "no"
-then
-  AC_DEFINE([DOUBLE_IS_LITTLE_ENDIAN_IEEE754], [1],
-  [Define if C doubles are 64-bit IEEE 754 binary format, stored
-   with the least significant byte first])
-else
-  # Some ARM platforms use a mixed-endian representation for doubles.
-  # While Python doesn't currently have full support for these platforms
-  # (see e.g., issue 1762561), we can at least make sure that float <-> string
-  # conversions work.
-  # FLOAT_WORDS_BIGENDIAN doesn't actually detect this case, but if it's not big
-  # or little, then it must be this?
-  AC_DEFINE([DOUBLE_IS_ARM_MIXED_ENDIAN_IEEE754], [1],
-  [Define if C doubles are 64-bit IEEE 754 binary format, stored
-   in ARM mixed-endian order (byte order 45670123)])
-fi
+AX_C_FLOAT_WORDS_BIGENDIAN(
+  [AC_DEFINE([DOUBLE_IS_BIG_ENDIAN_IEEE754], [1],
+             [Define if C doubles are 64-bit IEEE 754 binary format,
+              stored with the most significant byte first])],
+  [AC_DEFINE([DOUBLE_IS_LITTLE_ENDIAN_IEEE754], [1],
+             [Define if C doubles are 64-bit IEEE 754 binary format,
+              stored with the least significant byte first])],
+  [AS_CASE([$host_cpu],
+           [*arm*], [# Some ARM platforms use a mixed-endian representation for
+                     # doubles. While Python doesn't currently have full support
+                     # for these platforms (see e.g., issue 1762561), we can at
+                     # least make sure that float <-> string conversions work.
+                     # FLOAT_WORDS_BIGENDIAN doesn't actually detect this case,
+                     # but if it's not big or little, then it must be this?
+                     AC_DEFINE([DOUBLE_IS_ARM_MIXED_ENDIAN_IEEE754], [1],
+                               [Define if C doubles are 64-bit IEEE 754 binary format,
+                                stored in ARM mixed-endian order (byte order 45670123)])],
+           [wasm*], [AC_DEFINE([DOUBLE_IS_LITTLE_ENDIAN_IEEE754], [1],
+                               [Define if C doubles are 64-bit IEEE 754 binary format,
+                                stored with the least significant byte first])])])
 
 # The short float repr introduced in Python 3.1 requires the
 # correctly-rounded string <-> double conversion functions from
```

</details>

**Comment by hoodmane** [comment] 2024-11-04 08:28
Looks good to me and it has the advantage of not involving autotools-archive. Though it would be nice to eventually land a fix upstream too, in case other projects also use this project with Emscripten. They haven't responded to my PR though so it might take a while.

**Comment by erlend-aasland** [comment] 2024-11-05 08:00
@hoodmane, I'd like to backport #125571, since it's an improvement on Linux; what's the status of WASM in the 3.13 and 3.12 branches? Would a backport break those platforms?

**Comment by hoodmane** [comment] 2024-11-05 08:19
Could you also backport the fix? It would be helpful for me.

**Comment by erlend-aasland** [comment] 2024-11-05 08:51
> Could you also backport the fix for emscripten? It would be helpful for me.

I created the following backports:

- #126429
- #126430

These include both the autoconf-archive patch and the Emscripten workaround

**Comment by hoodmane** [comment] 2024-11-05 09:00
Thanks!

**Closed as completed** 2024-11-13 20:57 UTC
Labels: build, topic-installation, 3.10
