### ISSUE TITLE
Code blocks have white text agaisnt white background in dark mode in documentation for 3.9

### ISSUE THREAD

**Issue by ghost** [python/cpython#116481] opened 2024-03-07 23:03 UTC
# Documentation

## Version: 3.9.18

As an example, on page https://docs.python.org/3.9/library/xml.etree.elementtree.html, some of the words contained within the code blocks are invisible because they are white text against white background.

![image](https://github.com/python/cpython/assets/116753126/9b03f82c-b7bf-490a-b1c3-409bca4a783f)

Switching to the light theme, this same block appears like so in 3.9.18

![image](https://github.com/python/cpython/assets/116753126/45bba706-c68d-4ae2-a4cf-7db5495080bb)

## Version: 3.10.13 onwards

This error is not present in versions after and including 3.10 which appears like so:

![image](https://github.com/python/cpython/assets/116753126/ff641dd9-ea5a-43a5-8663-014db74d9304)

**Comment by terryjreedy** [comment] 2024-03-08 04:48
This is a duplicate of https://github.com/python/cpython/issues/115349 which has been fixed, and will be deployed when the next 3.8 and 3.9 releases go out, which I think should be quite soon.

In the meantime, you can switch to the light theme, or visit the docs for 3.10 or later.

**Closed as not planned** 2024-03-08 06:00 UTC
Labels: docs
