### ISSUE TITLE
Significant performance degradation in the macOS build

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#122832] opened 2024-08-08 17:35 UTC
# Bug report

### Bug description:

The benchmark at `Tools/scripts/var_access_benchmark.py` indicates that something is wrong with the latest build.

The versions compared are `3.12.4` versus `Python 3.13.0rc1` using the stock `macOS 64-bit universal2 installer` builds published on `python.org`.

<img width="1353" alt="Screenshot 2024-08-08 at 12 28 26 PM" src="https://github.com/user-attachments/assets/27dbc04d-43d7-4e6a-a7e6-40619012eb95">

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by hugovk** [comment] 2024-08-08 17:38
Sound like a duplicate of https://github.com/python/cpython/issues/122580.

**Comment by rhettinger** [comment] 2024-08-08 18:28
> Sound like a duplicate of https://github.com/python/cpython/issues/122580.

There are key differences.  

The other report shows a specific piece of code that runs a little slower and could reasonably be attributed to a skipped PGO path or build noise.  This report shows degradation across the board. Local variable reads are 4x slower.  This isn't minor.

The other report used a local build which would be affected by many factors.  This report uses the official `python.org` builds.

The other report used an alpha version.  This report focuses on a release-candidate which means that this is what we're about to ship.  That makes the level of severity more important.

Rather than thinking about dismissing this as a duplicate, a better question is whether it should be marked as a release-blocker.

**Comment by ned-deily** [comment] 2024-08-08 18:42
Thanks for the additional data points. I think we were considering the other issue to be a release blocker and should have been labeled it as such.

**Comment by hugovk** [comment] 2024-08-08 18:43
The full pyperformance suite has been run in the other issue, comparing 3.13.0rc1 and 3.12.4 and showed the RC is some 9% slower. See https://github.com/python/cpython/issues/122580#issuecomment-2265345358

Yes, I think it's a release blocker. There's a possible solution in the other issue, building with different flags.

**Comment by ned-deily** [comment] 2024-08-08 19:01
BTW, thanks again, @rhettinger, for implementing that useful benchmark. I had been using it already in investigating the other report which was also against the python.org builds, later diverging into local test builds.

**Comment by hg0428** [comment] 2024-08-09 22:28
> > Sound like a duplicate of #122580.
> 
> There are key differences.
> 
> The other report shows a specific piece of code that runs a little slower and could reasonably be attributed to a skipped PGO path or build noise. This report shows degradation across the board. Local variable reads are 4x slower. This isn't minor.
> 
> The other report used a local build which would be affected by many factors. This report uses the official `python.org` builds.
> 
> The other report used an alpha version. This report focuses on a release-candidate which means that this is what we're about to ship. That makes the level of severity more important.
> 
> Rather than thinking about dismissing this as a duplicate, a better question is whether it should be marked as a release-blocker.



> > Sound like a duplicate of #122580.
> 
> There are key differences.
> 
> The other report shows a specific piece of code that runs a little slower and could reasonably be attributed to a skipped PGO path or build noise. This report shows degradation across the board. Local variable reads are 4x slower. This isn't minor.
> 
> The other report used a local build which would be affected by many factors. This report uses the official `python.org` builds.
> 
> The other report used an alpha version. This report focuses on a release-candidate which means that this is what we're about to ship. That makes the level of severity more important.
> 
> Rather than thinking about dismissing this as a duplicate, a better question is whether it should be marked as a release-blocker.

Actually, my report used the official installers from Python.org, and focused on the release candidate as well. So, they can be seen as the same overall issue. Thanks for the benchmark to help this out.

**Comment by ned-deily** [comment] 2024-09-03 06:58
Thanks again for the extremely useful data and the heads-up. Since the performance degradation here appears to the same root cause and solution (which will be available in 3.13.0rc2) as that noted in #122580, I am going to close this as a duplicate and consolidate the discussion there.

**Closed as not planned by ned-deily** 2024-09-03 06:58 UTC
Labels: performance, OS-mac

**Comment by rhettinger** [comment] 2024-09-07 02:39
Just tested 3.13rc2 and everything is fixed.  Thank you.
