### ISSUE TITLE
_ProactorBasePipeTransport.abort() after _ProactorBasePipeTransport.close() does not cancel writes

### ISSUE THREAD

**Issue by f82f2f79-bfff-44c7-86e7-c93f7a9fd1fe** [python/cpython#88594] opened 2021-06-15 21:00 UTC
BPO | [44428](https://bugs.python.org/issue44428)
--- | :---
Nosy | @gvanrossum, @asvetlov, @ambv, @1st1, @graingert

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-15.21:00:19.644>
labels = ['3.8', '3.9', '3.10', 'expert-asyncio']
title = '_ProactorBasePipeTransport.abort() after _ProactorBasePipeTransport.close() does not cancel writes'
updated_at = <Date 2021-07-12.16:40:18.078>
user = 'https://github.com/graingert'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-12.16:40:18.078>
actor = 'graingert'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-06-15.21:00:19.644>
creator = 'graingert'
dependencies = []
files = []
hgrepos = []
issue_num = 44428
keywords = []
message_count = 2.0
messages = ['395896', '396558']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'asvetlov', 'lukasz.langa', 'yselivanov', 'graingert']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44428'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment] 2022-07-09 16:13
@gvanrossum Do you recall the details as you fixed the selector event loop race ?

**Comment by gvanrossum** [comment] 2022-07-10 00:09
Sorry, you're on your own here. I have no recollection of this fix.

**Comment by kumaraditya303** [comment] 2022-10-23 18:32
Duplicate of https://github.com/python/cpython/issues/89237

**Comment by kumaraditya303** [comment] 2022-10-23 18:32
https://github.com/python/cpython/pull/98572 fixes this

**Closed as not planned by kumaraditya303** 2022-10-23 18:32 UTC
Labels: topic-asyncio, 3.11, 3.10, 3.12
