### ISSUE TITLE
Use a more principled approach to freelists

### ISSUE THREAD

**Issue by markshannon** [python/cpython#89738] opened 2021-10-22 16:20 UTC
BPO | [45575](https://bugs.python.org/issue45575)
--- | :---
Nosy | @markshannon
PRs | <li>python/cpython#29165</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/markshannon'
closed_at = None
created_at = <Date 2021-10-22.16:20:28.637>
labels = ['interpreter-core', '3.11', 'performance']
title = 'Use a more principled approach to freelists'
updated_at = <Date 2021-10-22.16:21:16.097>
user = 'https://github.com/markshannon'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-22.16:21:16.097>
actor = 'Mark.Shannon'
assignee = 'Mark.Shannon'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-10-22.16:20:28.637>
creator = 'Mark.Shannon'
dependencies = []
files = []
hgrepos = []
issue_num = 45575
keywords = ['patch']
message_count = 1.0
messages = ['404788']
nosy_count = 1.0
nosy_names = ['Mark.Shannon']
pr_nums = ['29165']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue45575'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment] 2022-09-10 17:50
@markshannon you closed the PR. Did you intend to leave this issue open?

**Comment by iritkatriel** [comment] 2023-01-31 16:34
Duplicate of https://github.com/python/cpython/issues/100240.

**Closed as not planned by iritkatriel** 2023-01-31 16:34 UTC
Labels: performance, interpreter-core, 3.11, pending
