### ISSUE TITLE
Should comparison with lambda be allowed

### ISSUE THREAD

**Issue by pomponchik** [python/cpython#99822] opened 2022-11-27 18:58 UTC
# Bug report

This expression is not available for Python:

`variable == lambda: 'kek'`

I know that in most cases such comparisons do not make sense. However, I am talking more about the syntactic side of the question than about the practical application. From the point of view of syntax, such comparisons should not be prohibited.

Now I have to wrap such expressions in brackets:

`variable == (lambda: 'kek')`

It works, however I don't find it beautiful. I don't see any ambiguities in the syntax that would occur when lambda is used without parentheses.

# My environment

- CPython versions tested on: Python 3.10.7
- Operating system and architecture: MacOS Monterey (12.5), ARM m1

### Linked PRs
* gh-99861

**Comment by sobolevn** [comment] 2022-11-27 20:04
3.12 still has this:

```python
>>> class StrangeDSL:
...    def __mul__(self, other):
...        return other()
... 
>>> s = StrangeDSL()
>>> s * lambda: 123
  File "<stdin>", line 1
    s * lambda: 123
        ^^^^^^
SyntaxError: invalid syntax
>>> s * (lambda: 123)
123
```

This might affect some DSLs 🤔

**Comment by ericvsmith** [comment] 2022-11-27 20:26
https://docs.python.org/2/reference/expressions.html#operator-precedence

lambda has lower precedence than other operators.

**Comment by pomponchik** [comment] 2022-11-27 22:05
@ericvsmith I think the essence of the error is not in the order of operations, but in the incorrect splitting of the string into sub-operations at the parsing stage.

I expect such work of the a parser:

`[variable == [lambda: 'kek']]`

And what i think i have:

`[[variable == lambda]: 'kek']`

In this case, an expression without parentheses looks syntactically valid, but it's not valid by the parsers's opinion.

**Comment by pomponchik** [comment] 2022-11-27 22:07
@sobolevn 
> This might affect some DSLs 🤔

Yes, I encountered this problem in the process of creating a DSL.

**Comment by ericvsmith** [comment] 2022-11-27 22:38
> @ericvsmith I think the essence of the error is not in the order of operations, but in the incorrect splitting of the string into sub-operations at the parsing stage.

I'm not sure of your terminology, but it sounds like you're defining operator precedence. It's documented that `==` binds tighter than `lambda`. So no parens is the same as parens around `variable==lambda`.

```python
>>> variable = 0
>>> variable == lambda: 'kek'
  File "<stdin>", line 1
    variable == lambda: 'kek'
                ^
SyntaxError: invalid syntax
>>> (variable == lambda): 'kek'
  File "<stdin>", line 1
    (variable == lambda): 'kek'
                 ^
SyntaxError: invalid syntax
>>> variable == (lambda: 'kek')
False
```

Adding parens in the last example changes the order of bindings.

**Comment by pomponchik** [comment] 2022-11-28 20:06
@ericvsmith no, I'm talking about something else.

A lambda expression is primarily an expression, it consists of 2 parts: before the colon and after. The word "lambda" is not an expression. This priority table refers to the fact that the lambda _expression_ is executed after the others, but this does not apply to the order in which we separate the expressions in this case.

I understand that this is a rather subtle difference, but it is important, the parser does not work correctly.

**Comment by pablogsal** [comment] 2022-11-28 21:44
To clarify for future readers: this behaviour is not new and has been like this since the old parser:

```

❯ python3.8 -c "variable == lambda: 'kek'"
  File "<string>", line 1
    variable == lambda: 'kek'
                ^
SyntaxError: invalid syntax

 python3.9 -Xoldparser -c "variable == lambda: 'kek'"
  File "<string>", line 1
    variable == lambda: 'kek'
                ^
SyntaxError: invalid syntax

 python3.9 -c "variable == lambda: 'kek'"
  File "<string>", line 1
    variable == lambda: 'kek'
                ^
SyntaxError: invalid syntax
```

The behaviour was preserved with the new PEG parser as that was our target. What we are trying to understand here is whether this is an intended behaviour. 


> This priority table refers to the fact that the lambda expression is executed after the others, but this does not apply to the order in which we separate the expressions in this case.

It really depends on how you look at it because it also specifies how they are parsed. Operator priority **is** a parser feature and is encoded in the grammar (normally, is possible to do it later) and is independent on the VM. This is because 3 + 4 * 5 creates an AST that binds it as 3+ (4 * 5) and not as (3 + 4) * 5. This is important because is defined in the parser stage and has consequences. There are subtle differences between the preference of "operators" and how the parser binds.

> It works, however I don't find it beautiful. I don't see any ambiguities in the syntax that would occur when lambda is used without parentheses.

There are, for instance, in f-strings:

```
>>> f"{lambda: x}"
  File "<fstring>", line 1
    (lambda)
           ^
SyntaxError: unexpected EOF while parsing
>>> f"{(lambda: x)}"
'<function <lambda> at 0x1015529d0>'
```

I will try to understand if this is something that can be easily fixed in the parser. If this is quite intrusive to improve I am afraid that is very unlikely that this will ever be fixed, specifically given that the balance of complexity to benefit is quite low.

@gvanrossum Do you have any opinions on this?

**Comment by gvanrossum** [comment] 2022-11-28 23:33
I see this as a consistency issue in the grammar. If we interpret `x == lambda: y` as `x == (lambda: y)` then that might lead users to assume that it also works the other way, and write `lambda: y == x` expecting it to be grouped as `(lambda: x) == y`. However, `lambda: x == y` is grouped as `lambda: (x == y)`, and we want it that way. So to not betray users' expectations, we require explicit grouping even in `x == (lambda: y)`.

A counter-argument could be made, since we already violate this expectation for unary `-` when combined with `**`: `x**-y` is valid, meaning `x**(-y)`, while `-y**x` is parsed as `-(y**x)`. I think the reasoning here is that `**` is right-associative. We could argue that `lambda` is also right-associative.

I agree with Pablo that if this is easy to do in the grammar it's fine to do, otherwise we shouldn't bother.

**Comment by pomponchik** [comment] 2022-11-29 01:11
@pablogsal thank you very much for the detailed analysis! I was interested to find out how it works in different versions of Python.

In general, I agree that this does not look like a very important matter (it just surprised me in the process of creating a small DSL) and I think it is logical that it should be fixed only if it is not too expensive, however, I would like to mention a couple of points. 

1. This code example demonstrates that the lambda comparison operation is commutative by default:

```python
class KekComparable:
    def __eq__(self, other):
        return True

assert KekComparable() == (lambda x: x)  # True
assert (lambda x: x) == KekComparable()  #True
```

2. If you still think that the lambda comparison operation is not commutative (and you assume that this is bad) - you should prohibit this operation in principle. Now it is allowed, but only if you are willing to pay for it by introducing a small ugliness in the form of brackets.

**Comment by gvanrossum** [comment] 2022-11-29 07:00
> If you still think that the lambda comparison operation is not commutative (and you assume that this is bad) - you should prohibit this operation in principle. Now it is allowed, but only if you are willing to pay for it by introducing a small ugliness in the form of brackets.

There seem to be two separate concerns here. Confusing these is confusing.
- Syntactically, we could have `x == lambda: y` and `lambda: y == x` with very different meanings.
- Semantically, if `x` and `y` are both lambdas (or most other things that don't have a perverse definition of `__eq__`), `x == y` and `y == x` mean the same thing.

IMO the term "commutative" refers to the _semantics_ of `x == y` vs. `y == x`. For example, string concatenation is not commutative (`'a' + 'b' != 'b' + 'a'`).

FWIW, I prefer the relatively straightforward definition of expression grammar using operator priorities, where `lambda` is seen as an "operator" with a very low priority. This would be the status quo.

**Comment by pomponchik** [comment] 2022-11-29 14:48
@gvanrossum yes, this is a very sensible remark. We really should separate these two kinds of things when we talk about "commutativity".

I would also like to note this aspect of the problem. I would introduce such a rule: if we decide on some property of the language, it is best for us to be guided by the widest rule available. If a certain property of a language follows exactly the same from several rules we have adopted, we should justify it with the widest possible of them.

I think that the rule "lambda is a right-associative operation" has a broader analogue, leading to the same consequence in this case. The bottom line is how many language-valid ways we have to read something. Additional restrictions (for example, the need to frame the expression with brackets) are needed only to eliminate ambiguity of interpretations. The expression `x == lambda: y` has only one valid interpretation, so the interpreter at this point should not doubt what is meant. For the expression `lambda: y == x` there are 2 possible interpretations: `[[lambda: y] == x]` and `[lambda: [y == x]]`. In this case, the interpreter cannot determine which option the user had in mind, so it needs clarification. A situation with several possible interpretations is fundamentally different from a situation where only one is possible (unless we discard all options where cats walk on keyboards and sometimes stuff valid Python code), only in such situations should the interpreter request clarifications.

**Comment by gvanrossum** [comment] 2022-11-29 21:41
Thank you for thinking about this. At this point I prefer to close the issue without action.

**Closed as not planned by gvanrossum** 2022-11-29 21:41 UTC
Labels: interpreter-core
