### ISSUE TITLE
The Python library first imports files in its working folder rather than the libraries it actually depends on

### ISSUE THREAD

**Issue by Alpha-Qian** [python/cpython#122673] opened 2024-08-04 23:10 UTC
# Bug report

### Bug description:

This took me at least at least three hours only because I created a new file called signal.py in my work folder and then asyncio imported it. Under what circumstances would a python library load a module outside of the library folder? This is also disguised as static creation of a py file with the same name as the module. This behavior should be fixed or a reason given for the error.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows, Other

**Comment by terryjreedy** [comment] 2024-08-05 03:12
This a a documented feature.  Changing is a feature (change) request.  As such, this should likely be posted on discuss.python.org first.

**Comment by ZeroIntensity** [comment] 2024-08-05 07:50
I'm with @terryjreedy, this would be a breaking change (someone might *intentionally* be shadowing an import, for whatever monkeypatching purposes).

**Comment by Alpha-Qian** [comment] 2024-08-05 08:16
> 这是一个记录在案的功能。更改是一种功能（更改）请求。因此，这可能应该首先发布在 discuss.python.org 上。

That's just bizarre. Someone else's published library will take my own script as a dependency? Is there a need for this mechanism to exist? I originally thought this was a bug.

**Comment by vstinner** [comment] 2024-08-05 18:04
You can run "python -P" to avoid this issue: https://docs.python.org/dev/using/cmdline.html#cmdoption-P

**Comment by vstinner** [comment] 2024-08-05 18:05
This issue is the expected behavior and not a bug, I suggest to close it.

**Closed as not planned** 2024-08-06 12:55 UTC
Labels: type-feature
