### ISSUE TITLE
Python3.12 regression - really slow loop with strings

### ISSUE THREAD

**Issue by gitzdnex** [python/cpython#115645] opened 2024-02-19 06:54 UTC
# Bug report

### While trying Python3.12
- it seems that some operations are quite slow (I mean a lot more 10x times slower, I did not let it finish) 
- on python3.10 it is okay
- testing code is just simple loop test
- it looks like it is spending time 
- **when I have put code to function it went much faster**
- originaly from https://gitlab.com/gambas/gambas/-/raw/master/benchmark/string2.py?ref_type=heads
```python
#!/usr/bin/python

str = ''
i = 0

for i in range(0, 1000000):
    for j in range(65, 91):
        c = chr(j)
        str += '.(' + c + ')'

print(len(str))

```
### Python3.12 - I let it run 1:30 and it still did not finish...
```console
$time python3.12 /tmp/test.py
^CTraceback (most recent call last):
  File "/tmp/test.py", line 9, in <module>
    str += '.(' + c + ')'
    ^^^
KeyboardInterrupt


real	1m31.003s
user	0m36.380s
sys	0m54.605s
$python3.12
Python 3.12.2 (main, Feb 13 2024, 09:17:46) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

### Python3.10 - 5sec to finish
```console
$time python3 /tmp/test.py 
104000000

real	0m4,562s
user	0m4,497s
sys	0m0,064s

$python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by MechanicPig** [comment] 2024-02-19 07:29
The output format for the running time of your python 3.10 is a bit confusing. If I'm not mistaken, the displayed time actually exceeds an hour, so it's normal for python 3.12 to run for 1min30s without ending.

**Comment by hugovk** [comment] 2024-02-19 07:41
I think it says 3.10 took about 5 seconds.

---

Also quick with 3.8 - 3.10 for me (on macOS):

```console
❯ time python3.8 test.py
104000000
python3.8 test.py  5.69s user 0.03s system 98% cpu 5.818 total

❯ time python3.9 test.py
104000000
python3.9 test.py  5.33s user 0.04s system 98% cpu 5.469 total

❯ time python3.10 test.py
104000000
python3.10 test.py  4.49s user 0.03s system 98% cpu 4.574 total
```

Slowness started in 3.11, I stopped this after 16 minutes:

```console
❯ time python3.11 test.py
^CTraceback (most recent call last):
  File "/private/tmp/test.py", line 9, in <module>
    str += '.(' + c + ')'
    ^^^
KeyboardInterrupt

python3.11 test.py  605.63s user 359.96s system 98% cpu 16:17.49 total
```

**Comment by gitzdnex** [comment] 2024-02-19 07:48
Yes it takes about 5 sec on 3.10. But it is slow on Python3.12.

**Comment by gitzdnex** [comment] 2024-02-19 07:57
But that is on windows and here it looks like speed regression is at least 200% and we already see it in some scripts which were before really quick, now takes a lot of time.
Is this really okay to leave? Previus issue was closed.

**Comment by terryjreedy** [comment] 2024-02-19 08:37
I am closing this as a duplicate of #99862 and adding a note there.  Any further discussion should continue there.

**Closed as not planned by terryjreedy** 2024-02-19 08:37 UTC
Labels: type-bug, performance
