### ISSUE TITLE
cv2 result in python crashing due to typehints

### ISSUE THREAD

**Issue by ahmedhishamradwan** [python/cpython#103757] opened 2023-04-24 14:01 UTC
# Crash report
Calling:

`cv2.VideoCapture(false_rtmp_stream_url*) 
`
causes python to crash in a very specific setting:

1. This happened after updating the docker image where the code run on, from debian 10 slim-buster to debina 11 slim-bullseye.
2. Local package init.py need to be like shown below, GstDecoderPipeline is a class object
```
from .gst_decoder import GstDecoderPipeline

__all__ = [
    "GstDecoderPipeline",
]
```
 3. The GstDecoderPipeline include a "call back function" methods .
 4. The methods arguments include type hints i.e: `on_new_frame_sample(self, sink: Gst.Element)`

Any of those scenarios will avoid the crushing situation for example: 

1. Using debian 10 slim-buster
2. Deleting the init.py and importing the class using `from .gst_decoder import GstDecoderPipeline` whenever it's needed or even emptying the init.py file.
3. The best way just deleting the type hints from the "call back function" methods arguments

*false_rtmp_stream_url is a non existing rtmp stream url and usually it fail gracefully with those errors:
[ERROR:0] global /tmp/pip-req-build-5x6cvtvt/opencv/modules/videoio/src/cap.cpp (164) open VIDEOIO(CV_IMAGES): raised OpenCV exception:
OpenCV(4.5.4-dev) /tmp/pip-req-build-5x6cvtvt/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtmp://source-node-testing-rmtp-server:1935/false/stream in function 'icvExtractPattern'

# Error messages

In case of crush:
**Fatal Python error: Segmentation fault** 

In case everything working fine(intended behaviour):
**[ERROR:0] global /tmp/pip-req-build-5x6cvtvt/opencv/modules/videoio/src/cap.cpp (164) open VIDEOIO(CV_IMAGES): raised OpenCV exception:
OpenCV(4.5.4-dev) /tmp/pip-req-build-5x6cvtvt/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtmp://source-node-testing-rmtp-server:1935/false/stream in function 'icvExtractPattern'**

# Your environment

- CPython versions tested on: 3.9 (The highest by slim-bullseye-3.9 is 3.9.16)
- Operating system and architecture: Docker image python:3.9-slim-bullseye
- packages installed OS:
```
libglib2.0-0
libsm6 libxext6 libxrender-dev
libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl
gstreamer-1.0
gstreamer1.0-dev
python3-gst-1.0
libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
python3-gi
python3-gi-cairo
gir1.2-gtk-3.0
libcairo2-dev
libjpeg-dev
libgif-dev
```
- pip packages:
```
boto3==1.24.66
confluent_kafka==1.9.2
kubernetes==12.0.1
numpy==1.23.2
opencv-python==4.5.4.58
prometheus-client==0.8.0
pyarrow==11.0.0
pygobject==3.42.2
pylertalertmanager==0.1.1
PyMySQL[rsa]==1.0.2
python-json-logger==0.1.11
requests==2.26.0
SQLAlchemy==1.4.4
zstandard==0.19.0 
```

**Comment by JelleZijlstra** [comment] 2023-04-24 14:07
Do you have a stack trace for the segfault?

It is quite likely that the bug is in cv2's C++ code, not in CPython.

**Comment by ahmedhishamradwan** [comment] 2023-04-24 14:12
File "/builds/computer_vision/engineering/source_node/source_node/sources/video.py", line 264 in run
  File "/usr/local/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 937 in _bootstrap
Thread 0x00007f77937fe700 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 316 in wait
  File "/usr/local/lib/python3.9/queue.py", line 180 in get
  File "/builds/computer_vision/engineering/source_node/source_node/cache.py", line 93 in _message_loop
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80 in _run
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905 in _run_once
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601 in run_forever
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634 in run_until_complete
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44 in run
  File "/builds/computer_vision/engineering/source_node/source_node/cache.py", line 102 in run
  File "/usr/local/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 937 in _bootstrap
Thread 0x00007f7738bfe700 (most recent call first):
  File "/builds/computer_vision/engineering/source_node/source_node/kafka_internal.py", line 306 in run
  File "/usr/local/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 937 in _bootstrap
Thread 0x00007f7791ffb700 (most recent call first):
  File "/usr/local/lib/python3.9/queue.py", line 175 in get
  File "/builds/computer_vision/engineering/source_node/source_node/cache.py", line 93 in _message_loop
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80 in _run
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905 in _run_once
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601 in run_forever
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634 in run_until_complete
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44 in run
  File "/builds/computer_vision/engineering/source_node/source_node/cache.py", line 102 in run
  File "/usr/local/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 937 in _bootstrap
Thread 0x00007f77bb89c700 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 316 in wait
  File "/usr/local/lib/python3.9/queue.py", line 180 in get
  File "/builds/computer_vision/engineering/source_node/source_node/cache.py", line 93 in _message_loop
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80 in _run
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905 in _run_once
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601 in run_forever
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634 in run_until_complete
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44 in run
  File "/builds/computer_vision/engineering/source_node/source_node/cache.py", line 102 in run
  File "/usr/local/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 937 in _bootstrap
Thread 0x00007f77e1821740 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 1080 in _wait_for_tstate_lock
  File "/usr/local/lib/python3.9/threading.py", line 1064 in join
  File "/builds/computer_vision/engineering/source_node/source_node/sources/video.py", line 295 in collect
  File "/builds/computer_vision/engineering/source_node/source_node/sources/video.py", line 143 in prepare
  File "/builds/computer_vision/engineering/source_node/source_node/sources/video.py", line 169 in prepare
  File "/builds/computer_vision/engineering/source_node/source_node/stream.py", line 81 in propose_start
  File "/builds/computer_vision/engineering/source_node/source_node/scheduler.py", line 619 in start_stream
  File "/builds/computer_vision/engineering/source_node/source_node/scheduler.py", line 742 in process
  File "/builds/computer_vision/engineering/source_node/tests/helpers.py", line 20 in wait_for_scheduler_state
  File "/builds/computer_vision/engineering/source_node/tests/test_gst_pipeline.py", line 833 in test_end_to_end_online_video_gst_false_stream_with_retry
  File "/usr/local/lib/python3.9/site-packages/_pytest/python.py", line 184 in pytest_pyfunc_call
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/local/lib/python3.9/site-packages/_pytest/python.py", line 1479 in runtest
  File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 135 in pytest_runtest_call
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 217 in <lambda>
  File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 244 in from_call
  File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 216 in call_runtest_hook
  File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 186 in call_and_report
  File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 100 in runtestprotocol
  File "/usr/local/lib/python3.9/site-packages/_pytest/runner.py", line 85 in pytest_runtest_protocol
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 272 in pytest_runtestloop
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 247 in _main
  File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 191 in wrap_session
  File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 240 in pytest_cmdline_main
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 124 in main
  File "/usr/local/lib/python3.9/site-packages/pytest/__main__.py", line 7 in <module>
  File "/usr/local/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/local/lib/python3.9/runpy.py", line 197 in _run_module_as_main

**Comment by ahmedhishamradwan** [comment] 2023-04-24 14:12
line 264 calls
 `cv2.VideoCapture(false_rtmp_stream_url)`

**Comment by ahmedhishamradwan** [comment] 2023-04-24 14:13
The reason I believe its python (I can be wrong) is removing type hints in the local module just avoid the situation

**Comment by JelleZijlstra** [comment] 2023-04-24 14:14
Since you're getting a segfault, a C backtrace (e.g. from gdb) is more helpful. How are you getting the Python stack trace for the segfault?

**Comment by ahmedhishamradwan** [comment] 2023-04-24 14:16
I am not sure since this is not running locally I can just get the log. This is automatic testing for ci

**Comment by JelleZijlstra** [comment] 2024-05-01 16:10
Closing since there are no clear reproduction steps.

**Closed as not planned by JelleZijlstra** 2024-05-01 16:10 UTC
Labels: type-crash
