### ISSUE TITLE
PicklingError on multiprocessing for windows

### ISSUE THREAD

**Issue by pjn2work** [python/cpython#105982] opened 2023-06-22 08:47 UTC
# Bug report

I have this code giving me a PicklingError but only on a Windows machine. It works fine in Linux.
I’m running a function as a process by annotation. Could this be a bug?

# Your environment

Windows 10 Enterprise
Dell Latitude 7420 - x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   1.80 GHz
Tested with python 3.9.13, 3.10.11 and 3.11.3

# Code

```
import multiprocessing
from types import MethodType


DEFAULT_POOL = []


def run_as_process(_func=None, *, name: str = None, context_pool: list[multiprocessing.Process] = DEFAULT_POOL):

    class RunParallel:
        def __init__(self, func):
            self.func = func

        def __call__(self, *args, **kwargs):
            process = multiprocessing.Process(target=self.func, name=name, args=args, kwargs=kwargs)
            context_pool.append(process)
            process.start()

        def __get__(self, instance, owner):
            return self if instance is None else MethodType(self, instance)

    if _func is None:
        return RunParallel
    else:
        return RunParallel(_func)


def process_wait_context(context_pool: list[multiprocessing.Process] = DEFAULT_POOL, kill_others_if_one_fails: bool = False, clear_pool: bool = False) -> list[tuple[int, str, int]]:
    finished = []
    for process in context_pool:
        process.join()
        finished.append(process)

        if kill_others_if_one_fails and process.exitcode != 0:
            break

    if kill_others_if_one_fails:
        # kill unfinished processes
        for process in context_pool:
            if process not in finished:
                process.kill()

        # wait for every process to be dead
        for process in context_pool:
            process.join()

    result = [(i, process.name, process.exitcode) for i, process in enumerate(context_pool)]

    if clear_pool:
        process_clear_context_pool(context_pool)

    return result


def process_clear_context_pool(context_pool: list[multiprocessing.Process] = DEFAULT_POOL):
    context_pool.clear()


@run_as_process
def m1(a, b="b"):
    print(f"proc m1 -- {a=} {b=}")


if __name__ == "__main__":
    m1(11)  # fails here, but only in windows - tested with 3.9.13 3.10.11 3.11.3. Linux ok
    process_wait_context()

```

# Error

```
Traceback (most recent call last):
  File "C:\Users\Pedro.Nunes\BJSS\code\python\pyutils\src\d.py", line 65, in <module>
    m1(11)  # fails here, but only in windows - tested with 3.9.13 3.10.11 3.11.3. Linux ok
    ^^^^^^
  File "C:\Users\Pedro.Nunes\BJSS\code\python\pyutils\src\d.py", line 17, in __call__
    process.start()
  File "C:\Users\Pedro.Nunes\.pyenv\pyenv-win\versions\3.11.3\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro.Nunes\.pyenv\pyenv-win\versions\3.11.3\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro.Nunes\.pyenv\pyenv-win\versions\3.11.3\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro.Nunes\.pyenv\pyenv-win\versions\3.11.3\Lib\multiprocessing\popen_spawn_win32.py", line 94, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Pedro.Nunes\.pyenv\pyenv-win\versions\3.11.3\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function m1 at 0x00000208100FA0C0>: it's not the same object as __main__.m1

C:\Users\Pedro.Nunes\BJSS\code\python\pyutils\src>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Pedro.Nunes\.pyenv\pyenv-win\versions\3.11.3\Lib\multiprocessing\spawn.py", line 106, in spawn_main
    source_process = _winapi.OpenProcess(
                     ^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect
```

**Comment by sunmy2019** [comment] 2023-06-22 12:05
```py
@run_as_process
def m1: ...
```

`m1` after decoration is now a local object which cannot be pickled as indicated in the doc.

---

Windows uses `spawn` as the default open method. Linux uses `fork` as default.

`fork` does not require pickling.

**Comment by sunmy2019** [comment] 2023-06-22 12:06
It will be closed as invalid.

**Comment by ronaldoussoren** [comment] 2023-06-22 12:09
The code will also fail on unix-y platforms if you pick the "spawn" start method (which the start method on Windows). 

The code sends the ``m1`` function to a child process. With the "spawn" method this is done by pickling the callable (and its arguments) and sending that to the child, while with the "fork" method there is no explicit copying.  The pickling of fails because it tries to pickle the function before decorating while its ``__name__`` is bound to the decorated/wrapped function.

**Comment by sunmy2019** [comment] 2023-06-22 12:09
See also #91027

**Comment by ronaldoussoren** [comment] 2023-06-22 12:23
@sunmy2019 : I agree with your conclusion.   This is not a bug, but a side effect of the "spawn" start method of multiprocessing that cannot be avoided on the CPython end.

**Closed as not planned by ronaldoussoren** 2023-06-22 12:23 UTC

**Comment by terryjreedy** [comment] 2023-06-22 19:50
@pjn2work Questions about 'is my problem due to a CPython bug' should first be asked elsewhere, such as https://discuss.python.org/c/users/7.  The Bug Report template said a bit more.
