### ISSUE TITLE
create_datagram_endpoint() no longer compatible with CAN bus raw sockets 

### ISSUE THREAD

**Issue by tjhowse** [python/cpython#114887] opened 2024-02-02 04:02 UTC
# Bug report

### Bug description:

# Problem description

We are using `create_datagram_endpoint()` to set up an asyncio-managed connection to a native hardware CAN bus interface at `can0` under debian linux. We are using the `sock` named argument to pass in a pre-built raw socket to the FD.

This works in Python 3.5.3 but broke following a migration to 3.11.4. We found that the datagram endpoint would fail to be brought up, and the `connection_made(transport)` method on the `protocol_factory` would never be called. When I rejigged our code to await the coroutine I got:

```
    ValueError: A UDP Socket was expected, got <socket.socket fd=7, family=29, type=3, proto=1, laddr=('can0',)
```

I believe this has gone unnoticed due to hardware CAN bus interfaces being rare.

# Relevant history

https://github.com/python/cpython/pull/4231
https://github.com/python/cpython/pull/4898
https://github.com/python/cpython/pull/4922

Discussion of underlying issues: https://bugs.python.org/issue32331

# Core issue

A socket connected to a CAN bus has `sock.type` `socket.SOCK_RAW`, I.E. `0b11`. This fails the comparison to `socket.SOCK_DGRAM` (`0b01`) so `create_datagram_endpoint()` raises an exception because the socket's type fails the "is a datagram" check, even though it is. In 3.5.3 the check was:

```python
    (sock.type & socket.SOCK_DGRAM) == socket.SOCK_DGRAM
```
This worked because it was treating SOCK_DGRAM as a bitwise mask, which it kinda is, but kinda isn't.

x86_64-linux-gnu/bits/socket_type.h:
```c
    ...
    /* Types of sockets.  */
    enum __socket_type
    {
    SOCK_STREAM = 1,		/* Sequenced, reliable, connection-based
                    byte streams.  */
    #define SOCK_STREAM SOCK_STREAM
    SOCK_DGRAM = 2,		/* Connectionless, unreliable datagrams
                    of fixed maximum length.  */
    #define SOCK_DGRAM SOCK_DGRAM
    SOCK_RAW = 3,			/* Raw protocol interface.  */
    #define SOCK_RAW SOCK_RAW
    SOCK_RDM = 4,			/* Reliably-delivered messages.  */
    ...
```

I am torn on the best way to approach a fix here. I have written a PR that replaces

```python
    if sock.type != socket.SOCK_DGRAM:
```

comparisons with

```python
    if not sock.type & socket.SOCK_DGRAM:
```
however this perpetuates the enum-vs-bitmask confusion. A more constrained change might be to change

```python
    if sock.type != socket.SOCK_DGRAM:
```

to

```python
    if not (sock.type == socket.SOCK_DGRAM || sock.type == socket.SOCK_RAW):
```

but that may not catch every instance of the problem. I'd appreciate some guidance on this.

Cheers,
Travis.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-114888
* gh-114893
* gh-114977
* gh-114978
* gh-114979
* gh-114980

**Comment by ncoghlan** [comment] 2024-02-02 05:04
Looking at the origin of the underlying regression in #4922 & #76512, it's clear that the intent was to eliminate the bit flag behaviour from the handling of the Python-level socket type information.

Looking at the glibc source code for the [declarations of the socket types](https://sourceware.org/git/?p=glibc.git;a=blob;f=bits/socket.h;h=13de124bac67c21769026d62091154c292360dea;hb=HEAD), and Linux socket [man page](https://man7.org/linux/man-pages/man2/socket.2.html) strongly suggests that bringing back the bitwise checks is NOT the right answer:

* `SOCK_RAW` is `SOCK_DGRAM | SOCK_STREAM`, but from a syscall point of view, it works like `SOCK_DGRAM`
* from the description of `SOCK_RDM` in the man page, it should also be handled like `SOCK_DGRAM` but doesn't set that bit
* `SOCK_SEQPACKET` is `SOCK_RDM | SOCK_DGRAM | SOCK_STREAM`, but from a syscall point of view, the man page states it works like `SOCK_STREAM`

Actually handling `SOCK_RDM` and `SOCK_SEQPACKET` is well out of scope (since there aren't any standardised Internet protocols that use them), but their existence can still be used to inform the design of an appropriate solution.

For a pure `SOCK_RAW` bug fix, that sounds to me like leaving checks against `SOCK_STREAM` alone (since `SOCK_RAW` failing them is correct, and we're not trying to fix `SOCK_SEQPACKET` here, but any checks for `s.type == SOCK_DGRAM` need to change to instead be `(s.type == SOCK_DGRAM or s.type == SOCK_RAW)`)

Regardless of the solution chosen, it would be very helpful if a basic vcan based compatibility test could be added to the test suite to ensure the standard lib continues to support CAN in addition to TCP and UDP.

(Full disclosure for other core devs: I used to work with @tjhowse and am hence familiar with the application(s) that are affected here)

**Comment by tjhowse** [comment] 2024-02-02 06:48
That makes sense to me. This also fixes the problem in our use-case.

**Comment by ncoghlan** [comment] 2024-02-08 08:23
Commit was missing the magic comment to auto-close the issue. Closing since the regression is fixed.

I'll file a new issue for the gap in the test suite (access restrictions on raw sockets make routine testing a bit awkward).

**Closed as completed by ncoghlan** 2024-02-08 08:23 UTC
Labels: type-bug, topic-asyncio, 3.11, 3.12, 3.13
