### ISSUE TITLE
re.sub()  doesn't substitute for all words with the replacement in the string when re.IGNORECASE is used and counter not specified

### ISSUE THREAD

**Issue by abhii2003** [python/cpython#99918] opened 2022-12-01 06:42 UTC
**# Bug report**

re.sub()  doesn't substitute for all words with the replacement in the string when re.IGNORECASE is used.

**# Your environment**
This bug was experienced on IDLE and VS code 

**#Problem**
Whenever re.sub() is used with the flag re.IGNORECASE or re.I and, the counter is not specified all of the occurrences of the word were not replaced instead only the first 2 occurrences were replaced. 

For example if the replacement is a string "cat" which should replace the word dog,
_The code_ :
**import re
print(re.sub("dog","cat","dog and cat and dog and dog and dog",re.I))**
_or_ 
**import re
print(re.sub("dog","cat","dog and cat and dog and dog and dog",re.IGNORECASE))**

_the  expected output was :_
**cat and cat and cat and cat and cat**

_the actual output is:_
**cat and cat and cat and dog and dog**

below is the image of the editor depicting the problem 

![image](https://user-images.githubusercontent.com/103648054/204983092-d483b592-8983-4a3f-b7b7-f0e7f907da63.png)

**Comment by abhii2003** [comment] 2022-12-01 06:46
Can someone please help and guide me to contribute to solving the issue?

**Comment by hauntsaninja** [comment] 2022-12-01 08:14
Duplicate of https://github.com/python/cpython/issues/85830

I recommend using keyword args: `print(re.sub("dog","cat","dog and cat and dog and dog and dog", flags=re.I))`

I'm leaving open in case anyone is interested in deprecating passing `count` by position — this is a little bit of a footgun

**Comment by hauntsaninja** [comment] 2022-12-01 08:18
Okay, looks like this is a super common point of confusion, so we should do something. Time to go through the following issues and figure out what Serhiy's opinion on this: https://github.com/python/cpython/issues/89621, https://github.com/python/cpython/issues/86639, https://github.com/python/cpython/issues/85930, https://github.com/python/cpython/issues/85830, https://github.com/python/cpython/issues/79724, https://github.com/python/cpython/issues/75110, https://github.com/python/cpython/issues/73091, https://github.com/python/cpython/issues/72038, https://github.com/python/cpython/issues/70542, https://github.com/python/cpython/issues/66949, https://github.com/python/cpython/issues/61863, https://github.com/python/cpython/issues/59972, https://github.com/python/cpython/issues/56287, https://github.com/python/cpython/issues/56166, https://github.com/python/cpython/issues/56156, https://github.com/python/cpython/issues/55471

**Comment by hauntsaninja** [comment] 2022-12-01 08:26
Okay, closing and will discuss on #56166

**Closed as not planned by hauntsaninja** 2022-12-01 08:26 UTC
Labels: type-bug, topic-regex

**Comment by abhii2003** [comment] 2022-12-01 11:47
okay that is good
