### ISSUE TITLE
Speedup `os.path`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117609] opened 2024-04-07 18:58 UTC
# Feature or enhancement

### Proposal:

There are (still) some minor optimisations possible in `os.path`, including some fast returns.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-117610

**Comment by barneygale** [comment] 2024-04-08 09:44
Duplicate of #117349, please don't do this. The bug tracker is not your personal to-do list.

**Closed as not planned by barneygale** 2024-04-08 09:44 UTC
Labels: type-feature, performance, stdlib

**Comment by nineteendo** [comment] 2024-04-08 09:56
> Most PRs will require an issue number. Trivial changes, like fixing a typo, do not need an issue.

Must I link to the closed issue then? This PR is about further changes.

**Comment by barneygale** [comment] 2024-04-08 09:59
If you think the previous issue was closed prematurely then you can leave a comment there asking for it to be re-opened.
