### ISSUE TITLE
Force UUIDv1 to use a clock sequence storage (RFC 4122)

### ISSUE THREAD

**Issue by 2d5c8f4d-4163-4998-af6c-b4c706ec080e** [python/cpython#88786] opened 2021-07-13 11:15 UTC
BPO | [44620](https://bugs.python.org/issue44620)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-13.11:15:00.340>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'UUIDv1 is not RFC 4122 compliant'
updated_at = <Date 2022-01-15.17:12:15.334>
user = 'https://bugs.python.org/contact2'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-15.17:12:15.334>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-07-13.11:15:00.340>
creator = 'contact2'
dependencies = []
files = []
hgrepos = []
issue_num = 44620
keywords = []
message_count = 1.0
messages = ['397392']
nosy_count = 1.0
nosy_names = ['contact2']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44620'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-124571

**Comment by picnixz** [comment] 2024-09-27 09:58
As discussed on the (now) closed PR, I do not think that this is an issue for UUIDv1. While the probability for having a collision is not that low when using the same timestamp, it is not worth changing a historical version (maybe still used though) that could (probably in a near future) be replaced by UUIDv6.

As such, I'm closing this one as `wont fix` (it would anyway be a feature and not a bug fix by the way).

**Closed as not planned by picnixz** 2024-09-27 09:58 UTC
Labels: type-feature, stdlib
