### ISSUE TITLE
Misleading error message when pathlib.Path.symlink_to() fails with permissions error

### ISSUE THREAD

**Issue by edc4926a-f180-4aad-b15c-88a5b2550682** [python/cpython#89389] opened 2021-09-17 01:06 UTC
BPO | [45226](https://bugs.python.org/issue45226)
--- | :---
Nosy | @barneygale, @dfntlymaybe

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-17.01:06:01.972>
labels = ['3.8', 'type-bug', 'library']
title = 'Misleading error message when pathlib.Path.symlink_to() fails with permissions error'
updated_at = <Date 2021-09-21.16:53:29.671>
user = 'https://github.com/dfntlymaybe'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-21.16:53:29.671>
actor = 'dfntlymaybe'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-09-17.01:06:01.972>
creator = 'dfntlymaybe'
dependencies = []
files = []
hgrepos = []
issue_num = 45226
keywords = []
message_count = 3.0
messages = ['401996', '402277', '402327']
nosy_count = 2.0
nosy_names = ['barneygale', 'dfntlymaybe']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45226'
versions = ['Python 3.8']
```

</p></details>

**Comment by barneygale** [comment] 2022-07-23 19:57
I believe this is a duplicate of #73843.

**Comment by barneygale** [comment] 2024-01-26 03:06
Closing - duplicate of #73843.

**Closed as not planned by barneygale** 2024-01-26 03:06 UTC
Labels: type-bug, stdlib, 3.8 (EOL), topic-pathlib
