### ISSUE TITLE
Admonition "spill" over the whole document in some cases in 3.10 docs only

### ISSUE THREAD

**Issue by Jackenmen** [python/cpython#95629] opened 2022-08-03 22:43 UTC
# Documentation

So, this happens:
![image](https://user-images.githubusercontent.com/6032823/182724559-edab9e29-f4c5-4eae-a491-bef02a331483.png)
https://docs.python.org/3.10/library/subprocess.html
![image](https://user-images.githubusercontent.com/6032823/182724520-9a8b3a73-bf65-4d80-9cd0-416058591036.png)
https://docs.python.org/3.10/library/socket.html

This could be an issue with the theme but it doesn't appear in 3.9, 3.11, and 3.12 docs which makes me think that this is more likely related to the Sphinx version as those seem to be using the same doc theme version.

**Comment by AlexWaygood** [comment] 2022-08-03 22:45
Duplicate of #95585

**Closed as not planned by AlexWaygood** 2022-08-03 22:45 UTC
Labels: docs
