### ISSUE TITLE
Add timestamp method to datetime.date object

### ISSUE THREAD

**Issue by hnewey7** [python/cpython#122700] opened 2024-08-05 18:39 UTC
# Feature or enhancement

### Proposal:

Add a timestamp method to the datetime.date object which calculates the epoch time similar to the datetime.datetime object.

```python
from datetime import date

current_date = date.today() # e.g 2024-08-05
current_date_timestamp = current_date.timestamp() # Epoch time of 2024-08-05
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by aisk** [comment] 2024-08-06 04:55
The minimum part in `datetime.date` is day, and the basic unit of a timestamp is second (or millisecond), so what's the timestamp of the current day (for example, 2024/9/6 in UTC)?

**Comment by hnewey7** [comment] 2024-08-06 07:44
It would be the equivalent of `datetime.datetime(year=2024,month=8,day=6).timestamp()`. So you would be getting the timestamp when it's just turned that day, no additional hours, minutes or seconds.

**Comment by serhiy-storchaka** [comment] 2024-08-06 16:42
This is a duplicate of #103072.

**Closed as not planned by serhiy-storchaka** 2024-08-06 16:42 UTC
Labels: type-feature, stdlib
