### ISSUE TITLE
python version 3.10.4 installation fails

### ISSUE THREAD

**Issue by shukyp** [python/cpython#92310] opened 2022-05-04 15:30 UTC
Hi,

I can't install Python version 3.10.4

I've been searching the internet for the last past two weeks… I've tried every (relevant) idea 

As it takes place in Windows 10 Home (version 21H2, build 19044.1682), I turned to Microsoft's support.
they pretty much-repeated ideas I had already tried while others were found to be useless

It seems that either a late update caused the problem or an uninstall caused it and there is an issue 
of missing or inconsistent settings in the registry (but this is just a guess)

The log file says:
[5BB0:48E4][2022-05-04T17:56:15]e000: Error 0x80070659: Failed to install MSI package.
[5BB0:48E4][2022-05-04T17:56:15]e000: Error 0x80070659: Failed to execute MSI package.
[3594:5524][2022-05-04T17:56:15]e000: Error 0x80070659: Failed to configure per-machine MSI package.

Can anyone provide support on the above?

**Thanks,** Shuky

**Comment by shukyp** [comment] 2022-05-06 23:39
Needs to be added:
1. I tried installing an earlier Python version and it failed for same reason
2. I tried installing Python 3.10.4 on a different machine running Windows 10 home (same version) and installation was successful

So it seems that the problem is with my windows environment

**Comment by kumaraditya303** [comment] 2022-06-19 09:38
Closing as per OP comment `So it seems that the problem is with my windows environment`

**Closed as not planned by kumaraditya303** 2022-06-19 09:38 UTC
Labels: type-bug, OS-windows
