### ISSUE TITLE
http.client leaks from self.fp.read()

### ISSUE THREAD

**Issue by e98dba01-5fe6-4717-99f5-55e6de791f17** [python/cpython#87907] opened 2021-04-06 07:43 UTC
BPO | [43741](https://bugs.python.org/issue43741)
--- | :---
Nosy | @ukarroum, @HynekPetrak

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-06.07:43:38.231>
labels = ['3.9', 'performance']
title = 'http.client leaks from self.fp.read()'
updated_at = <Date 2022-01-15.09:50:34.279>
user = 'https://github.com/HynekPetrak'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-15.09:50:34.279>
actor = 'ukarroum'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-04-06.07:43:38.231>
creator = 'HynekPetrak'
dependencies = []
files = []
hgrepos = []
issue_num = 43741
keywords = []
message_count = 4.0
messages = ['390287', '390290', '390403', '410634']
nosy_count = 2.0
nosy_names = ['ukarroum', 'HynekPetrak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue43741'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment] 2022-08-10 22:25
@HynekPetrak How did you determine that this is a leak (in the sense that the memory is allocated and then never released) rather than just a memory spike due to multiple threads reading large files at the same time (with the unbounded reads)?

**Comment by HynekPetrak** [comment] 2022-08-10 22:34
I was running a large scan of web servers, say several thousands, in threadpoolexecutor with some 50 threads at max. I tested it with requests but also with urllib / stdlib itself. With session per each thread. 
Each thread just retrieved the html and saved it to the file. 
When I retrieved and saved full response I run always out of memory (4GB 64Bit system). 
I could work around that by retrieving just a chunk of 10kB, then it runs low on memory.
I tried garbage collect offer each save, did not helped.

**Comment by iritkatriel** [comment] 2022-08-10 22:48
What if you reduce the number of threads to, say, 2?

**Comment by iritkatriel** [comment] 2022-08-10 22:52
If it works with 2 threads, what happens if you gradually increase the read size from 10000 to larger numbers - how does that change the number of threads you can have without running out of memory?

(Since you didn't give us your complete script, it's hard to investigate your problem properly. But answers to these questions could, maybe, help clarify what's going on).

**Comment by HynekPetrak** [comment] 2022-08-10 22:54
Those are three implementations, that run out of memory. Note the below is the body of a function, that is being run by ThreadPoolExecutor for many thousands of URLs.

with urllib3:
``` python
session = urllib3.PoolManager(cert_reqs='CERT_NONE', headers=headers)
r = session.request('GET', url, timeout=timeout)
data = r.data
save_to_file(url, data)
```

with requests:
``` python
session = requests.Session()
session.max_redirects = 3

with session.get(url, timeout=timeout, headers=headers, verify=False) as r:
        data = r.text
        save_to_file(url, data)
        r.close()
```

with http.client:
``` python
o = urlparse(url)
if o.scheme == 'http':
    cn = http.client.HTTPConnection(o.netloc, timeout=timeout)
else:
    cn = http.client.HTTPSConnection(o.netloc, context=ctx, timeout=timeout)
cn.request('GET', o.path, headers=headers)
data = cn.getresponse()
save_to_file(url, data)
```

This is the workaround that finally does not run out of memory - with requests:
``` python
session = requests.Session()
session.max_redirects = 3

with session.get(url, timeout=timeout, headers=headers, verify=False) as r:
        data = next(r.iter_content(chunk_size=10000), b"").decode("utf-8", errors="ignore")
        save_to_file(url, data)
        r.close()
```

**Comment by HynekPetrak** [comment] 2022-08-10 22:59
> What if you reduce the number of threads to, say, 2?

Not sure how that would be related to the memory consumption. It only depended on number of URLs scanned, what I remember.

**Comment by HynekPetrak** [comment] 2022-08-10 23:02
> If it works with 2 threads, what happens if you gradually increase the read size from 10000 to larger numbers - how does that change the number of threads you can have without running out of memory?
> 
> (Since you didn't give us your complete script, it's hard to investigate your problem properly. But answers to these questions could, maybe, help clarify what's going on).

Let me do some more experiments. For that I need to build a test environment, so it might take me some days.

**Comment by iritkatriel** [comment] 2022-08-10 23:21
> > What if you reduce the number of threads to, say, 2?
> 
> Not sure how that would be related to the memory consumption. It only depended on number of URLs scanned, what I remember.

The question I am trying to answer is - does it depend on the number of urls, or on the number of urls accessed simultaneously?

In your experiments, can you also keep track of the sizes of the urls (or just the sizes of the large ones)?

**Comment by HynekPetrak** [comment] 2022-08-11 00:55
Let's close this "bug". I cannot reproduce it with a clean code written from a scratch. And I don't have the exact code where I observed it.
It might have happened, that I made some stupid mistake, which prevented garbage collection of data from http response.

**Comment by iritkatriel** [comment] 2022-08-11 05:33
Ok. Thank you.

**Closed as not planned by iritkatriel** 2022-08-11 05:33 UTC
Labels: performance, 3.9 (EOL), pending
