### ISSUE TITLE
NameError: name '_check_date_fields' is not defined

### ISSUE THREAD

**Issue by FANGOD** [python/cpython#110676] opened 2023-10-11 02:50 UTC
# Bug report

### Bug description:

```python
    import bs4
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/site-packages/bs4/__init__.py", line 37, in <module>
    from .builder import (
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/site-packages/bs4/builder/__init__.py", line 621, in <module>
    from . import _html5lib
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/site-packages/bs4/builder/_html5lib.py", line 21, in <module>
    import html5lib
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/site-packages/html5lib/__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/site-packages/html5lib/html5parser.py", line 6, in <module>
    from . import _inputstream
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/site-packages/html5lib/_inputstream.py", line 4, in <module>
    from six.moves import http_client, urllib
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/site-packages/six.py", line 97, in __get__
    result = self._resolve()
             ^^^^^^^^^^^^^^^
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/site-packages/six.py", line 120, in _resolve
    return _import_module(self.mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/site-packages/six.py", line 87, in _import_module
    __import__(name)
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/http/client.py", line 71, in <module>
    import email.parser
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/calendar.py", line 52, in <module>
    class _localized_month:
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/calendar.py", line 54, in _localized_month
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/calendar.py", line 54, in <listcomp>
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lian/.pyenv/versions/3.11.4/lib/python3.11/datetime.py", line 948, in __new__
    year, month, day = _check_date_fields(year, month, day)
                       ^^^^^^^^^^^^^^^^^^
NameError: name '_check_date_fields' is not defined
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by CharlieZhao95** [comment] 2023-10-11 03:36
It seems that you got an error when `import bs4`, right?

`_check_date_fields` in `datetime.py` exists and works well. This is not a bug in CPython, please check your environment. 
```python
Python 3.11.4 (heads/3.11.4:6109e45273, Oct  9 2023, 19:59:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bs4  # success
```

**Comment by FANGOD** [comment] 2023-10-11 03:39
> It seems that you got an error when `import bs4`, right?
> 
> `_check_date_fields` in `datetime.py` exists and works well. This is not a bug in CPython, please check your environment.
> 
> ```python
> Python 3.11.4 (heads/3.11.4:6109e45273, Oct  9 2023, 19:59:14) [GCC 11.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import bs4  # success
> ```

Yes, that's right. Maybe it was an error caused by some imports, but the information displayed by the traceback confused me.

**Comment by FANGOD** [comment] 2023-10-11 03:50
```
# ls utils -l
__init__.py  # from ._datetime import simple_datetime
_play.py  # main file
_datetime.py  # This filename caused the problem above, even though I wasn't using it
```

**Comment by AndresProgramerCOP** [comment] 2023-10-11 06:37
You solve your issue ? https://github.com/python/cpython/issues/110676#issuecomment-1756723107 with this comment ?

**Comment by FANGOD** [comment] 2023-10-11 07:28
> Are You solve your issue ? [#110676 (comment)](https://github.com/python/cpython/issues/110676#issuecomment-1756723107) with this comment ?

Yes, but I don’t understand what caused it. This code has always worked before.

**Comment by AndresProgramerCOP** [comment] 2023-10-24 06:48
Would you consider closing this issue? It's just so you don't have open issues, because clearly you already solved it @FANGOD

**Closed as not planned** 2023-11-26 20:08 UTC
Labels: type-bug
