### ISSUE TITLE
logging.Logger methods exhibit confusing behavior when called before logging.basicConfig()

### ISSUE THREAD

**Issue by mikolysz** [python/cpython#107749] opened 2023-08-07 21:09 UTC
The behavior of methods such as `logging.Logger.debug`, `logging.Logger.info`, `logging.Logger.warning` etc, when called before `logging.basicConfig()`, is confusing and not well-documented.

In such a case, the logged message is sent to the handler of last resort, which outputs it to STDERR without any formatting. However, this only happens when the message's level is WARNING or above, regardless of the level of the logger in question.

Consider the following code snippet:

```python
import logging

logger = logging.getLogger("foo")
logger.setLevel(logging.INFO)
logger.debug("not printed, and for good reason")
logger.info("not printed, even though level is INFO") # 1
logger.warning("printed without logger name and level") # 2
logging.basicConfig()
logger.debug("still not printed, which makes sense")
logger.info("basicConfig called, info printed properly") # 3
logger.warning("warnings now have a level and logger name attached")
```

This behavior is deeply confusing to users. One would intuitively expect that either both `1` and `2` are printed, or, in the worst case scenario, that nothing is printed before `3`. The current behavior is hinted at in the [Advanced logging tutorial](https://docs.python.org/3/howto/logging.html#what-happens-if-no-configuration-is-provided), but it is not mentioned at all in the [documentation for logging.Logger.debug](https://docs.python.org/3/library/logging.html#logging.Logger.debug).

Essentially, we have three kinds of messages here, messages below the logger's level, which are never printed, messages at the logger's level and below the `WARNING` level, which are only printed after `logging.basicConfig()`, and messages at `WARNING` and above, which are always printed, although their format changes. The behavior users expect is to either have the second kind always behave like the third, or to have the third kind always behave like the second.

## Proposed ways to fix this (from least to most invasive):

- Document the current behavior for `logging.Logger.debug` and expand the [relevant section in the advanced logging tutorial](https://docs.python.org/3/howto/logging.html#what-happens-if-no-configuration-is-provided) to mention this case specifically. Maybe we should also point this issue out in the [section on loggers](https://docs.python.org/3/howto/logging.html#loggers).
- Make the handler of last resort print messages at all levels, ensuring that messages are never passed to it if they're above the effective level of their logger. This is still somewhat confusing to users, as messages would still be printed unformatted, but it's less confusing than the "triple standard" we have now.
- Make methods on `logging.Logger` call `logging.basicConfig()` when needed, just like the functions in package `logging` itself. This completely eliminates the confusion and makes loggers always respect the level they have set. As far as I understand, this would eliminate the need for the handler of last resort completely, although I'm not completely sure of this.

I'm willing to make a PR for this issue if it's is deemed worth fixing and once a consensus is reached on how.

**Comment by vsajip** [comment] 2023-08-08 05:53
I'll look at suggested improvements to the documentation, but I wouldn't want to make changes along the last two approaches suggested.

**Comment by mohd-akram** [comment] 2023-10-12 20:34
Ran into this as well. The problem is even worse because `basicConfig()` is called implicitly. The formatting changes based on what is called first:

```python
import logging
logger = logging.getLogger('custom')
logging.error('root error')
logger.error('custom error')
```

prints

```
ERROR:root:root error
ERROR:custom:custom error
```

while

```python
import logging
logger = logging.getLogger('custom')
logger.error('custom error')
logging.error('root error')
```

prints:


```
custom error
ERROR:root:root error
```

I agree on the second point with OP, there is no reason for a level on the handler since by default the root logger has level `WARNING` already. The following patch results in consistent behavior:

```diff
--- logging/__init__.py.orig	2023-10-02 22:41:20
+++ logging/__init__.py	2023-10-13 00:26:06
@@ -1301,7 +1301,10 @@
         return sys.stderr
 
 
-_defaultLastResort = _StderrHandler(WARNING)
+# Use the same format as basicConfig()
+_defaultLastResort = _StderrHandler()
+_defaultLastResort.setFormatter(Formatter(_STYLES['%'][1], None, '%'))
+
 lastResort = _defaultLastResort
 
 #---------------------------------------------------------------------------
```

**Comment by vsajip** [comment] 2023-10-13 03:58
This is a;so a change in behaviour, which I was suggesting was unacceptable.

**Comment by mohd-akram** [comment] 2023-10-13 08:52
I see. It seems in this case it's best for applications to set `lastResort` to `None` to maintain predictable behavior.

**Comment by vsajip** [comment] 2023-10-13 09:53
Or, perhaps, don't mix usage of `logger.XXX` method calls with `logging.XXX` module-level functions (meant for simple standalone scripts, where no logging hierarchy is needed and so the root logger suffices). Or, call `basicConfig()` (or `dictConfig()`, etc.) first in the `if __name__ == '__main__':` clause, before logging anything.

**Comment by vsajip** [comment] 2023-10-13 09:56
@mikolysz offered to make a PR, but perhaps hasn't found the time. I'll mark this issue as pending and close it soon, but I remain willing to look at a documentation PR for this area, even after closing the issue.

**Comment by mikolysz** [comment] 2023-10-13 09:58
If a documentation PR is acceptable, I can make one for sure.

**Comment by mohd-akram** [comment] 2023-10-13 10:20
> Or, perhaps, don't mix usage of `logger.XXX` method calls with `logging.XXX` module-level functions (meant for simple standalone scripts, where no logging hierarchy is needed and so the root logger suffices). Or, call `basicConfig()` (or `dictConfig()`, etc.) first in the `if __name__ == '__main__':` clause, before logging anything.

I think all this can be done in addition to setting `lastResort` to `None`. Thinking about this more, there's no guarantee that `stderr` is looked at in the first place, so it really should just throw an exception rather than mask the problem. This can be done like so:

```python
logging.lastResort = logging.Handler()
```

**Comment by vsajip** [comment] 2023-10-15 20:58
> So the list of recommendations

No, I don't recommend these for the general case, though they might work for you.

**Comment by vsajip** [comment] 2023-10-23 16:25
Closing now; you can reopen when a documentation PR is available.

**Closed as completed by vsajip** 2023-10-23 16:25 UTC
Labels: docs, pending
