### ISSUE TITLE
doctest.testmod() fails for a file called tokenize.py

### ISSUE THREAD

**Issue by baoilleach** [python/cpython#113488] opened 2023-12-26 13:44 UTC
# Bug report

### Bug description:

If the following file is saved as `tokenize.py` or `linecache.py`, then it fails with an error when run:
```python
if __name__ == "__main__":
    import doctest
    doctest.testmod()
```
For `tokenize.py`:
```
Traceback (most recent call last):
  File "/home/noel/Work/20231226-doctest-bug/tokenize.py", line 3, in <module>
    doctest.testmod()
  File "/usr/lib/python3.10/doctest.py", line 1969, in testmod
    for test in finder.find(m, name, globs=globs, extraglobs=extraglobs):
  File "/usr/lib/python3.10/doctest.py", line 917, in find
    source_lines = linecache.getlines(file, module.__dict__)
  File "/usr/lib/python3.10/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python3.10/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
AttributeError: module 'tokenize' has no attribute 'open'
```

### CPython versions tested on:

3.10, 3.12

### Operating systems tested on:

Linux

**Comment by carljm** [comment] 2023-12-26 13:52
Hi, thanks for the report!

This is expected behavior, not a bug. Your modules take precedence over the standard library, so if you shadow a standard library module name, your module will be imported in place of the standard library one, and won't have the contents expected by other standard library modules using it. The solution is not to shadow standard library module names with your modules.

In https://github.com/python/cpython/issues/95754 we recently merged a change to help clarify the error messages in this situation.

**Closed as not planned by carljm** 2023-12-26 13:52 UTC
Labels: type-bug

**Comment by baoilleach** [comment] 2023-12-26 13:56
Thanks @carljm. I wasn't sure if expected or not in this case.

**Comment by terryjreedy** [comment] 2023-12-26 14:37
https://discuss.python.org/c/users/7 is a good place to ask "Is this a bug?"
