### ISSUE TITLE
unzip test_zipfile.cpython-310.pyc need passwd?

### ISSUE THREAD

**Issue by alittlesir** [python/cpython#103081] opened 2023-03-28 13:00 UTC
# Bug report

If we think of `test_zipfile.cpython-310.pyc` as a compressed file and unzip, but it need passwd? why need passwd?

```
[root@localhost tools]# unzip test_zipfile.cpython-310.pyc
Archive:  test_zipfile.cpython-310.pyc
warning [test_zipfile.cpython-310.pyc]:  73625 extra bytes at beginning or within zipfile
  (attempting to process anyway)
[test_zipfile.cpython-310.pyc] zero password:
```
In normal cases, the file is not a compressed file. like this.
```
[root@localhost tools]# unzip test_zipfile64.cpython-310.pyc 
Archive:  test_zipfile64.cpython-310.pyc
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of test_zipfile64.cpython-310.pyc or
        test_zipfile64.cpython-310.pyc.zip, and cannot find test_zipfile64.cpython-310.pyc.ZIP, period.
```

# Your environment

- CPython versions tested on: 3.10.9
- Operating system and architecture: openeuler x86

**Comment by ronaldoussoren** [comment] 2023-03-28 14:18
This could be a duplicate of #103051

**Comment by krchlry** [comment] 2023-04-01 06:15
> If we think of `test_zipfile.cpython-310.pyc` as a compressed file and unzip, but it need passwd? why need passwd?

why do you want to do this?

**Comment by alittlesir** [comment] 2023-04-01 11:19
> Why are you trying to unzip `test_zipfile.cpython-310.pyc`?

Our company has a scanning system, which can scan cpython source. 


I don't know why this file is considered a compressed file in the system.It was found that extracting this file actually prompted that a password was required. That's amazing.

**Comment by krchlry** [comment] 2023-04-01 11:19
您好，您发的邮件已收到，我会尽快处理！

**Comment by alittlesir** [comment] 2023-04-01 11:20
Normally to extract this file, it should prompt that it is not a compressed file.

**Comment by ronaldoussoren** [comment] 2023-04-02 09:52
The test_zipfile.cpython-310.pyc file is not a zipfile, but contains some data that can cause zipfile tooling to interpreted the file as a zipfile.

An easy way to reproduce is to create a file named "repro.py" with the following contents (extracted from test_zipfile.py):

```
data2 = (       
        b'PK\x03\x04\x14\x00\t\x00\x08\x00\xcf}38xu\xaa\xb2\x14\x00\x00\x00\x00\x02'
        b'\x00\x00\x04\x00\x15\x00zeroUT\t\x00\x03\xd6\x8b\x92G\xda\x8b\x92GUx\x04'
        b'\x00\xe8\x03\xe8\x03\xc7<M\xb5a\xceX\xa3Y&\x8b{oE\xd7\x9d\x8c\x98\x02\xc0'
        b'PK\x07\x08xu\xaa\xb2\x14\x00\x00\x00\x00\x02\x00\x00PK\x01\x02\x17\x03'
        b'\x14\x00\t\x00\x08\x00\xcf}38xu\xaa\xb2\x14\x00\x00\x00\x00\x02\x00\x00'
        b'\x04\x00\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa4\x81\x00\x00\x00\x00ze'
        b'roUT\x05\x00\x03\xd6\x8b\x92GUx\x00\x00PK\x05\x06\x00\x00\x00\x00\x01'
        b'\x00\x01\x00?\x00\x00\x00[\x00\x00\x00\x00\x00' )
```

The run ``python3 -c 'import repro'`` and finally try to unzip the PYC file in ``__pycache__`` to get the same error as the OP.

This is happens because the PYC file happens to have the representation of the ``data2`` value at the end of the file and that representation contains a valid zipfile directory at the end.

There is no bug here.

**Closed as not planned by ronaldoussoren** 2023-04-02 09:52 UTC
Labels: type-bug

**Comment by disconnect3d** [comment] 2023-04-02 12:50
> This is happens because the PYC file happens to have the representation of the data2 value at the end of the file and that representation contains a valid zipfile directory at the end.

This is nitpicky, but the data2 is not at the end of file. It is somewhere in the middle of the file, where the pyc file contains the module code object's constant values. But yeah, that still allows for zip tools to read the file as a zip file. The problem happens if such a file, which should be treated/imported as .pyc would be imported via a zipimport, as shown in #103051. But yeah, it is not the case this issue is describing.

```
➜  ~ python3 -c 'import x'
➜  ~ ll __pycache__/x.cpython-38.pyc
-rw-r--r--  1 dc  staff   296B Apr  2 14:22 __pycache__/x.cpython-38.pyc
➜  ~ xxd __pycache__/x.cpython-38.pyc
00000000: 550d 0d0a 0000 0000 9173 2964 9602 0000  U........s)d....
00000010: e300 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0001 0000 0040 0000 0073 0800 0000 6400  .....@...s....d.
00000030: 5a00 6401 5300 2902 73b0 0000 0050 4b03  Z.d.S.).s....PK.
00000040: 0414 0009 0008 00cf 7d33 3878 75aa b214  ........}38xu...
00000050: 0000 0000 0200 0004 0015 007a 6572 6f55  ...........zeroU
00000060: 5409 0003 d68b 9247 da8b 9247 5578 0400  T......G...GUx..
00000070: e803 e803 c73c 4db5 61ce 58a3 5926 8b7b  .....<M.a.X.Y&.{
00000080: 6f45 d79d 8c98 02c0 504b 0708 7875 aab2  oE......PK..xu..
00000090: 1400 0000 0002 0000 504b 0102 1703 1400  ........PK......
000000a0: 0900 0800 cf7d 3338 7875 aab2 1400 0000  .....}38xu......
000000b0: 0002 0000 0400 0d00 0000 0000 0000 0000  ................
000000c0: a481 0000 0000 7a65 726f 5554 0500 03d6  ......zeroUT....
000000d0: 8b92 4755 7800 0050 4b05 0600 0000 0001  ..GUx..PK.......
000000e0: 0001 003f 0000 005b 0000 0000 004e 2901  ...?...[.....N).
000000f0: 5a05 6461 7461 32a9 0072 0100 0000 7201  Z.data2..r....r.
00000100: 0000 00fa 0e2f 5573 6572 732f 6463 2f78  ...../Users/dc/x
00000110: 2e70 79da 083c 6d6f 6475 6c65 3e02 0000  .py..<module>...
00000120: 0073 0200 0000 02ff                      .s......
```
