### ISSUE TITLE
[feature request] Method to refresh os.environ

### ISSUE THREAD

**Issue by yurivict** [python/cpython#119737] opened 2024-05-29 17:23 UTC
# Bug report

### Bug description:

```os.environ``` doesn't reflect environment changes that are made outside of Python.

For example, this code adds the environment XXX but os.environ doesn't see this change.

This program:
```python
import os

import ctypes
import ctypes.util

clib = ctypes.util.find_library("c")
dll = ctypes.CDLL(clib)

setenv = dll.setenv
setenv.argtypes = [ctypes.POINTER(ctypes.c_char), ctypes.POINTER(ctypes.c_char), ctypes.c_int]

getenv = dll.getenv
getenv.argtypes = [ctypes.POINTER(ctypes.c_char)]
getenv.restype=ctypes.c_char_p

# set XXX outside of Python's os.environ
setenv(b"XXX", b"Hello", 2)

print(f'real XXX value: {str(getenv(b"XXX"))}')
print(f'XXX is in os.getenv: {os.getenv("XXX")}')
print(f'XXX is in os.environ: {"YES" if "XXX" in os.environ else "NO"}')
```

prints:
```
real XXX value: b'Hello'
XXX is in os.getenv: None
XXX is in os.environ: NO
```

There should be a method, for example ```os.environ_refresh```, that would re-read environment into os.environ.

I've hit this on the real-world case when Python didn't see environment set by TCL script executed in the same process.

### CPython versions tested on:

3.9

### Operating systems tested on:

Other

**Comment by itamaro** [comment] 2024-06-01 17:35
the behavior matches the [documented behavior](https://docs.python.org/3/library/os.html#os.environ):

> This mapping is captured the first time the [os](https://docs.python.org/3/library/os.html#module-os) module is imported, typically during Python startup as part of processing site.py. Changes to the environment made after this time are not reflected in [os.environ](https://docs.python.org/3/library/os.html#os.environ), except for changes made by modifying [os.environ](https://docs.python.org/3/library/os.html#os.environ) directly.

so this is not a bug, but a feature request.
please propose this on the [Python discuss ideas category](https://discuss.python.org/c/ideas/6) first!

**Comment by eryksun** [comment] 2024-06-01 23:59
This new feature would have to be implemented in C in "Modules/posixmodule.c". That's why I added the "extension-modules" label.

**Comment by yurivict** [comment] 2024-06-02 01:44
https://discuss.python.org/t/feature-request-method-to-refresh-os-environ/54774

**Comment by vstinner** [comment] 2024-06-05 10:26
I close this issue as a duplicate of https://github.com/python/cpython/issues/120057

**Closed as not planned by vstinner** 2024-06-05 10:26 UTC
Labels: type-feature, stdlib, extension-modules

**Comment by WolfDWyc** [comment] 2024-06-11 22:24
@vstinner 

As I noted in the discourse thread, and was mentioned in the comment on the PR, I still feel like this name will be confusing for new users, even with docs clarifying it. Can we maybe re-discuss this? Or at least choose another name?

Should we continue here or in the discourse thread?
