### ISSUE TITLE
Pathlib.rename isn't robust

### ISSUE THREAD

**Issue by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [python/cpython#90475] opened 2022-01-09 14:52 UTC
BPO | [46317](https://bugs.python.org/issue46317)
--- | :---
Nosy | @oz123, @barneygale
PRs | <li>python/cpython#30650</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-09.14:52:56.361>
labels = ['library', '3.9', '3.10', '3.11']
title = "Pathlib.rename isn't robust"
updated_at = <Date 2022-01-17.19:38:48.397>
user = 'https://github.com/oz123'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-17.19:38:48.397>
actor = 'Oz.Tiram'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-09.14:52:56.361>
creator = 'Oz.Tiram'
dependencies = []
files = []
hgrepos = []
issue_num = 46317
keywords = ['patch']
message_count = 6.0
messages = ['410155', '410590', '410593', '410595', '410648', '410649']
nosy_count = 2.0
nosy_names = ['Oz.Tiram', 'barneygale']
pr_nums = ['30650']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46317'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by barneygale** [comment] 2023-04-14 21:23
Hey @oz123, I've just spotted that this issue is a duplicate of #73991. There's some more discussion there. I'll resolve this issue as a duplicate, and re-title your PR. Hope that's alright, thanks!

**Closed as not planned by barneygale** 2023-04-14 21:23 UTC
Labels: stdlib, 3.11, 3.10, 3.9 (EOL), topic-pathlib
