### ISSUE TITLE
contextlib.redirect_stdout doesn't catch stream handlers that point directly to stdout

### ISSUE THREAD

**Issue by scarere** [python/cpython#123481] opened 2024-08-29 20:35 UTC
# Bug report

### Bug description:

loggers with stream handlers are able to bypass redirect stdout: https://stackoverflow.com/questions/70957676/python-redirect-stdout-doesnt-catch-logger

Ideally redirect_stdout would catch logs as well. Sometimes methods from dependencies have lots of unecessary logs that I'd like to silence or redirect to the DEBUG level of my own logger.

```python
import logging.handlers
import sys
import logging
from contextlib import redirect_stdout

logger = logging.getLogger()
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)

with redirect_stdout(None):
    print("STDOUT")
    logger.warning("LOGGER")
```

Output:
```bash
LOGGER
```

Expected:
```bash
```

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by rhettinger** [comment] 2024-08-30 00:25
Your report is well titled.  In fact, the redirection does only apply to new references to `sys.stdout` inside the with-statement.  

That was the intended behavior, so this isn't a bug and is more just a fact of life.  

And at the moment, I can't think of any way to write a new context manager that would change all direct references to `sys.stdout`.

That said, you could write a context manager that temporarily replaces one logging handler with another.  That would likely satisfy this use case.

**Comment by blhsing** [comment] 2024-08-30 05:52
> And at the moment, I can't think of any way to write a new context manager that would change all direct references to `sys.stdout`.

There's a good [answer](https://stackoverflow.com/a/22434262/6890912) on StackOverflow that demonstrates how stdout can be universally redirected at the file descriptor level using `os.dup` and `os.dup2`.

**Comment by picnixz** [comment] 2024-08-30 12:38
Following Raymond's analysis, I'll close the issue as `wontfix`.

**Closed as not planned by picnixz** 2024-08-30 12:38 UTC
