### ISSUE TITLE
Pickling of enum with functional API throws error

### ISSUE THREAD

**Issue by fnobis** [python/cpython#106959] opened 2023-07-21 10:35 UTC
# Bug report

I want to create a enum from a list of variables and then pickle it. I use the functional constructor. When I try to pickle it, an error is thrown:

`_pickle.PicklingError: Can't pickle <enum 'classes_enum_name'>: attribute lookup classes_enum_name on __main__ failed`

If I create the class explicitly the pickling works. 

See the following example to reproduce the error:

```py
import pickle
import enum


class ClassEnum(enum.Enum):
    dog = 1
    cat = 2
    cow = 3


if __name__ == "__main__":
    # **************************************************************************
    # Enum variant 1 - works
    # **************************************************************************

    class_enum = ClassEnum
    print(class_enum["cow"])
    with open("test.pkl", "wb") as f:
        pickle.dump(class_enum, f)  # works

    # **************************************************************************
    # Enum variant 2 - error
    # **************************************************************************
    classes = ["dog", "cat", "cow"]
    list_enum = enum.Enum("classes_enum_name", classes, start=0)
    print(list_enum["cow"])
    with open("test.pkl", "wb") as f:
        pickle.dump(list_enum, f)  # throws error
```

**Comment by TeamSpen210** [comment] 2023-07-21 10:52
The problem is that pickling for things like classes, functions and enums doesn't encode how to create a new version. It just stores the module and name, so that it can be re-imported when unpickled. That works fine as a class, but if you create it dynamically you have to ensure you assign it to that global name so it can be unpickled. The dumping process checks it's available under the name to verify the unpickling works.

**Comment by AlexWaygood** [comment] 2023-07-21 11:06
Yes, @TeamSpen210 is correct. The issue is that you've assigned `list_enum` to a different name in the global namespace than the `__name__` attribute of the enum class. If you don't do that, it works fine:

```pycon
>>> import enum, pickle
>>> classes = ["dog", "cat", "cow"]
>>> list_enum = enum.Enum("classes_enum_name", classes, start=0)
>>> x = pickle.dumps(list_enum)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <enum 'classes_enum_name'>: attribute lookup classes_enum_name on __main__ failed
>>> list_enum = enum.Enum("list_enum", classes, start=0)
>>> x = pickle.dumps(list_enum)
>>>
```

This is sort-of called out in the docs, but perhaps it could be clearer:
- https://docs.python.org/3/howto/enum.html#pickling
- https://docs.python.org/3/howto/enum.html#functional-api

**Comment by fnobis** [comment] 2023-07-21 11:43
Thanks for the input! I am starting to understand a bit better and got the toy example to work. 
In the real code the enum is nested in another Class which is only instantiated in other modules in another package.

I put a similar structure in a one file example to test how to pickle the same enum in different objects. In reality  `outer_class_enum1`   and `outer_class_enum2` would also be in different modules in a different package. I got it to work for the first specific object with the `qualname`, but did not find a generalizable solution. From your comments, I am wondering if this is possible?


```
import pickle
import enum


class ClassEnum(enum.Enum):
    dog = 1
    cat = 2
    cow = 3


class InnerClass:
    def __init__(self):
        classes = ["dog", "cat", "cow"]
        self.list_enum = enum.Enum(
            "list_enum",
            classes,
            start=0,
            module=__name__,
            qualname="outer_class_enum1.inner_class.list_enum",  # works with specific object
            # qualname="self.inner_class.list_enum",   # does not work
            # qualname="InnerClass.list_enum",   # does not work
        )


class OuterClass:
    def __init__(self):
        self.inner_class = InnerClass()


# **************************************************************************
# Enum variant 1 - works
# **************************************************************************
outer_class_enum1 = OuterClass()
with open("test.pkl", "wb") as f:
    pickle.dump(outer_class_enum1, f)  # works

# **************************************************************************
# Enum variant 2 - error
# **************************************************************************
outer_class_enum2 = OuterClass()
with open("test.pkl", "wb") as f:
    pickle.dump(outer_class_enum2, f)  # throws error
```

**Closed as not planned** 2023-07-26 16:08 UTC
Labels: docs
