### ISSUE TITLE
Stdlib packages import local packages from working dir instead of other stdlib packages

### ISSUE THREAD

**Issue by krfricke** [python/cpython#101210] opened 2023-01-21 01:26 UTC
# Bug report

Global packages (e.g. `enum`) try to import from local packages in the current working dir, even if a same-named stdlib package exists.

For instance, if a `types.py` exists in the local directory, `import enum` will fail:

```
> touch types.py
> python
Python 3.10.9 (main, Jan 20 2023, 17:02:49) [Clang 13.0.0 (clang-1300.0.27.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import enum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kai/.pyenv/versions/3.10.9/lib/python3.10/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' (/home/kai/sandbox/types.py)
```

The correct package to import should be the stdlib `types.py` package, not the local `types.py`.

# Your environment

- CPython versions tested on: Python 3.10.4, 3.10.9, 3.8.6
- Bug does **not** come up in 3.8.7
- Operating system and architecture: Mac x86_64

**Comment by hauntsaninja** [comment] 2023-01-21 02:08
Duplicate of https://github.com/python/cpython/issues/95893, https://github.com/python/cpython/issues/90482, https://github.com/python/cpython/issues/42852, https://github.com/python/cpython/issues/73790, https://github.com/python/cpython/issues/66368, https://github.com/python/cpython/issues/65577, https://github.com/python/cpython/issues/65401

See https://ncoghlan-devs-python-notes.readthedocs.io/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap

**Closed as not planned by hauntsaninja** 2023-01-21 02:08 UTC
Labels: type-bug

**Comment by eryksun** [comment] 2023-01-21 02:21
When running interactively, the current working directory is prepended to `sys.path` as an empty string. This gets evaluated to whatever the working directory is at the time of each import. When running a script, the directory of the script gets prepended to `sys.path`. Usually the script directory is not the same as the current working directory. 

You can run in isolated mode (i.e. `-I` command-line option) to avoid prepending either the working directory or the script directory. However, this is an extreme measure that also disables reading `PYTHON*` environment variables and the user site packages. Starting with Python 3.11, there's a [`-P` command-line option](https://docs.python.org/3/using/cmdline.html#cmdoption-P) to get a safe `sys.path` that doesn't prepend these directories.

**Comment by krfricke** [comment] 2023-01-21 04:21
Thanks for the explanation and sorry for the duplicate (I tried searching but didn't find the other issues).

Looking forward to the `-P` option - for our case we found another workaround.

Thanks!
