### ISSUE TITLE
Substitution of ParamSpec in Concatenate

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#88954] opened 2021-07-31 10:25 UTC
BPO | [44791](https://bugs.python.org/issue44791)
--- | :---
Nosy | @gvanrossum, @serhiy-storchaka, @JelleZijlstra, @miss-islington, @sobolevn, @Fidget-Spinner, @AlexWaygood, @cdce8p
PRs | <li>python/cpython#27518</li><li>python/cpython#30959</li><li>python/cpython#30969</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-31.10:25:13.991>
labels = ['library', '3.10', '3.11']
title = 'Substitution of ParamSpec in Concatenate'
updated_at = <Date 2022-02-20.09:11:54.505>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-20.09:11:54.505>
actor = 'med2277'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-07-31.10:25:13.991>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 44791
keywords = ['patch']
message_count = 9.0
messages = ['398632', '398645', '398661', '411862', '411863', '411926', '411933', '413534', '413573']
nosy_count = 9.0
nosy_names = ['gvanrossum', 'serhiy.storchaka', 'JelleZijlstra', 'miss-islington', 'sobolevn', 'kj', 'AlexWaygood', 'cdce8p', 'med2277']
pr_nums = ['27518', '30959', '30969']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44791'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by JelleZijlstra** [comment] 2022-04-29 18:37
I still haven't seen a compelling reason to allow substituting `...` in Concatenate, so I think we should leave things unchanged here and close #30969.

**Comment by JelleZijlstra** [comment] 2022-04-29 21:00
I just talked to @pradeep90 and he is actually on board with allowing this; it seems like a reasonable generalization, and we can allow it at runtime already pending type checker support.

**Comment by gvanrossum** [comment] 2022-04-29 22:57
Mind summarizing the use case here? Maybe give a simple example?

**Comment by JelleZijlstra** [comment] 2022-04-29 23:03
Pradeep showed me an email thread from a few months ago (I think you were also on it) that showed a use case. I don't recall the exact code, but basically it would allow pyre to infer `Callable[Concatenate[T1, ...], T2]` instead of `Callable[..., T2]` in some cases.

**Comment by gvanrossum** [comment] 2022-04-29 23:12
Sure. I wish we had allowed spelling that as `Callable[[T1, ...], T2]` -- the `Concatenate` seems to do nothing except make everything longer and less readable. :-(

**Comment by pradeep90** [comment] 2022-05-01 19:45
> Pradeep showed me an email thread from a few months ago (I think you were also on it) that showed a use case. I don't recall the exact code, but basically it would allow pyre to infer `Callable[Concatenate[T1, ...], T2]` instead of `Callable[..., T2]` in some cases.

@JelleZijlstra  Reproducing the email thread (from August 2021)… for future reference:

Mark Mendoza said: 
> Guido is correct in that I've moved on from working on Python typing in my day-to-day work.
> Overall, this plan sounds totally reasonable.  Serhiy, your proposals for substitution rules line up with my intentions/intuitions, save for the `Callable[Concatenate[int, P], str][...]` substitution, which I think I originally implemented as resolving to `Callable[..., str]`.  However, your proposal seems totally reasonable!  In any case, I think augmenting the PEP with more precision as to the solution rules is a good idea.
> As for the details of the generic alias question, and any other ongoing work in this area, I'd refer you to Pradeep, who is on the Pyre team today, and implemented our support for generic aliases.

My reply to Serhiy's question:


###  Concatenate and `...` and other edge cases

As Mark mentioned, Pyre's current behavior is to convert `Callable[Concatenate[int, P], str][...]` to `Callable[..., str]`.

If we want to allow `Callable[Concatenate[int, ...], str]`, then we'd probably have to extend the grammar in PEP 612 to allow any `parameters_expression` as the second argument to `Concatenate` instead of just `parameter_specification_variable`. That will make the following cleanly interchangeable in the syntax: `P`, `[int, str]`, `...`, and `Concatenate[int, P]`.

before:

```
callable ::= Callable "[" parameters_expression, type_expression "]"

parameters_expression ::=
  | "..."
  | "[" [ type_expression ("," type_expression)* ] "]"
  | parameter_specification_variable
  | concatenate "["
                   type_expression ("," type_expression)* ","
                   parameter_specification_variable
                "]"
```

after:

```
callable ::= Callable "[" parameters_expression, type_expression "]"

parameters_expression ::=
  | "..."
  | "[" [ type_expression ("," type_expression)* ] "]"
  | parameter_specification_variable
  | concatenate "["
                   type_expression ("," type_expression)* ","
                   parameters_expression                                          # <--- change
                "]"
```

This would allow things like

1. `Concatenate[int, str, P]`
2. `Concatenate[int, str, ...]`
3. `Concatenate[int, str, [str, bool]]`
4. `Concatenate[int, str, Concatenate[str, bool, P]]`

(3) should be equivalent to `[int, str, str, bool]` and (4) should be equivalent to `Concatenate[int, str, str, bool, P]`.

This would be more flexible than the previous behavior. It would handle different edge cases equivalently regardless of whether they came from alias substitution or from direct user-written types. But it would also require more parsing work from typecheckers. Pyre's current behavior is simpler but less flexible. This might be worth checking on in typing-sig since people from other typecheckers may have opinions.

I'm ok with adding these items to the PEP since they're not explicitly stated. Happy to extend the reference implementation in Pyre if we reach a consensus on the `...` case.

**Comment by serhiy-storchaka** [comment] 2022-05-02 05:45
> 3. `Concatenate[int, str, [str, bool]]`
> 4. `Concatenate[int, str, Concatenate[str, bool, P]]`

I do not think we need this.

We need a way to express the result of `parameter_specification_variable` substitution with `parameters_expression`, that's all. It is not necessary that substitution gives the same type. For example, `Union[T, int][int]` is just `int`, not `Union[int]`.

The only problem was with ellipsis. There is no valid syntax to express the result. The specification should be extended to allow either `Concatenate[int, str, ...]`, or `[int, str, ...]`, or some other syntax.

**Comment by AlexWaygood** [comment] 2023-03-15 10:57
I believe that we eventually arrived on consensus here that the changes made were acceptable. (Apologies if this summary is inaccurate.) Is there anything left to do here from a CPython/runtime perspective, or can this now be closed?

Discussions about whether the PEP should be updated should probably continue over at `python/typing`, if there are still unresolved questions.

**Comment by AlexWaygood** [comment] 2023-03-23 11:27
Closing for now. Feel free to reopen (or open a new issue at python/typing) if there's still more to discuss :)

**Closed as completed by AlexWaygood** 2023-03-23 11:27 UTC
Labels: stdlib, 3.11, 3.10, topic-typing
