### ISSUE TITLE
Python 3.12.2 headers contain non-C90-compliant code

### ISSUE THREAD

**Issue by jayaddison** [python/cpython#116869] opened 2024-03-15 15:37 UTC
# Bug report

### Bug description:

When compiling a program that links against the Python libraries (and uses their headerfiles) with the `-Werror=declaration-after-statement` compiler flag enabled, the following error occurs:

```
/usr/include/python3.12/object.h:233:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  233 |     PyVarObject *var_ob = _PyVarObject_CAST(ob);
```

This is fairly similar to previous issue #92781.

Although the C90 style may be archaic and perhaps not worth supporting at some point, maintaining support could be helpful for some downstream platforms (I encountered this in Debian bug [#1057442](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057442)).

<details>
<summary>Minimal test cases to show that the problem did not occur with Python 3.11.8 and that it does occur on Python 3.12.2 and to help verify any fixes.</summary>

```c
#include "/usr/include/python3.11/Python.h"
#include "/usr/include/python3.11/object.h"

int main() {}
```

```c
#include "/usr/include/python3.12/Python.h"
#include "/usr/include/python3.12/object.h"

int main() {}
```

Compiled in either case using:

```
$ gcc bugreport.c -Werror=declaration-after-statement
```

or equivalently, using `llvm` v17:

```
$ clang-17 bugreport.c -Werror=declaration-after-statement
```
</details>

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-116950
* gh-116954
* gh-116963
* gh-116973
* gh-116990
* gh-116995
* gh-117010
* gh-117011
* gh-117043
* gh-117106

**Comment by hugovk** [comment] 2024-03-15 15:41
The build requirements for 3.12 include:

> * A [C11](https://en.cppreference.com/w/c/11) compiler. [Optional C11 features](https://en.wikipedia.org/wiki/C11_(C_standard_revision)#Optional_features) are not required.

This is since 3.11:

> _Changed in version 3.11:_ C11 compiler, IEEE 754 and NaN support are now required. On Windows, Visual Studio 2017 or later is required.

https://docs.python.org/3/using/configure.html

**Comment by vstinner** [comment] 2024-03-18 09:00
I wrote PR gh-116950 to fix the issue.

While C11 is needed to build Python itself, the C API *should be* usable with ISO C90.

**Comment by colesbury** [comment] 2024-03-18 13:23
> While C11 is needed to build Python itself, the C API should be usable with ISO C90.

Where do we document that? PEP 7 says "The public C API should be compatible with C++.", not ISO C90. ISO C90 doesn't even support the `inline` keyword.

**Comment by vstinner** [comment] 2024-03-18 13:31
> Where do we document that?

I don't think that it's documented. It's just convenient since a few projects still use `-Werror=declaration-after-statement`. IMO these projects added this option when Visual Studio didn't support C99, it does now, but these projects were never updated.

In 2024, I don't see the point to support ISO C90. But the way, Python doesn't: it uses C99 "// comment" which fails with a build error with `-std=c90`.

But if the limited C API only exposes opaque functions, in fact, it's cheap to support `-Werror=declaration-after-statement`.

If tomorrow, we have a better reason to break that unwritten rule, we can revisit it.

**Comment by vstinner** [comment] 2024-03-18 13:53
I agree on writing down the rule. Also, I'm working on an unit test (starting with PR gh-116954) to avoid future regression.

**Comment by vstinner** [comment] 2024-03-19 10:46
I created https://github.com/python/peps/pull/3728 to write down the rule in PEP 7.

I created https://github.com/python/cpython/pull/116990 to build test_cext with `-Werror=declaration-after-statement` to check for regressions.

**Comment by vstinner** [comment] 2024-03-19 11:06
Ok, the initial issue has been fixed by https://github.com/python/cpython/commit/a9c304cf020e2fa3ae78fd88359dfc808c9dd639. I also added a non-regression test (test_cext).

Thanks for the report @jayaddison.

**Closed as completed by vstinner** 2024-03-19 11:06 UTC
Labels: type-bug, topic-C-API

**Comment by jayaddison** [comment] 2024-03-19 19:45
Thank you @vstinner!  It may take me a while but I will confirm that this is working when I can (particularly on 3.12; thank you for backporting the fix).

**Comment by vstinner** [comment] 2024-03-19 22:03
> Thank you @vstinner! It may take me a while but I will confirm that this is working when I can (particularly on 3.12; thank you for backporting the fix).

Do you have an idea on how many projects were affected by this issue? The Debian bug was reported on the `onboard` issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057442

**Comment by jayaddison** [comment] 2024-03-20 19:06
> > Thank you @vstinner! It may take me a while but I will confirm that this is working when I can (particularly on 3.12; thank you for backporting the fix).
> 
> Do you have an idea on how many projects were affected by this issue? The Debian bug was reported on the `onboard` issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057442

Not many that I'm aware of.  So far, Debian has rebuilt `614` packages with Python3.12 (while retaining support for Python3.11 as the default), and `onboard` is the only one to have failed with this particular error.  Another `162` packages do not have build results -- and I can't say that I know why that is -- but this doesn't appear to be a widespread problem.

Ref: https://release.debian.org/transitions/html/python3.12-add.html (tick/untick the good/partial/bad/unknown checkboxes to navigate the results)
