### ISSUE TITLE
`__annotations__` are not inherited in 3.10 while they are in 3.8

### ISSUE THREAD

**Issue by henrifroese** [python/cpython#99535] opened 2022-11-16 14:30 UTC
# Bug report

Python 3.8.13 inherits annotations from a subclass:

```bash
Python 3.8.13 (default, Oct 19 2022, 17:54:22) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class A:
...     x: int
... 
>>> class B(A):
...     pass
... 
>>> print(A.__annotations__)
{'x': <class 'int'>}
>>> print(B.__annotations__)
{'x': <class 'int'>}
>>> print(B.__dict__)
{'__module__': '__main__', '__doc__': None}
```

Python 3.10.8 does not:

```bash
Python 3.10.8 (main, Nov  4 2022, 08:45:18) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class A:
...     x: int
... 
>>> class B(A):
...     pass
... 
>>> print(A.__annotations__)
{'x': <class 'int'>}
>>> print(B.__annotations__)
{}
>>> print(B.__dict__)
{'__module__': '__main__', '__doc__': None, '__annotations__': {}}
```

Can't find anything related to this in the changelogs, release notes, stackoverflow etc. Is this known/expected behaviour?

### Linked PRs
* gh-99990
* gh-100507
* gh-100509

**Comment by sobolevn** [comment] 2022-11-16 20:32
3.12 `main` branch:

```
>>> class A:
...   x: int
... 
>>> class B(A):
...    ...
... 
>>> A.__annotations__
{'x': <class 'int'>}
>>> B.__annotations__
{}
```

3.11 is the same.
3.10 is the same
3.9.9 is different:

```
>>> class A:
...   x: int
... 
>>> class B(A): ...
... 
>>> A.__annotations__
{'x': <class 'int'>}
>>> B.__annotations__
{'x': <class 'int'>}
```

So, yes. I think it is a bug. And should be fixed / backported to 3.10 and 3.11

**Comment by JelleZijlstra** [comment] 2022-11-16 20:38
I haven't checked the logs, but I suspect this is an intentional change made by @larryhastings as part of his efforts to improve `__annotations__` handling. The 3.10+ behavior makes more sense to me: you `Cls.__annotations__` should give you the annotations for the current class, not a base class.

**Comment by JelleZijlstra** [comment] 2022-11-16 20:44
2f2b69855d6524e15d12c15ddc0adce629e7de84 and  #88067

**Comment by sobolevn** [comment] 2022-11-16 20:55
Yes, you are right. The change is intentional: https://github.com/python/cpython/issues/88067#issuecomment-1093911703

**Comment by sobolevn** [comment] 2022-11-16 20:55
So, adding tests and docs about it should be the way to go? 🤔

**Comment by MonadChains** [comment] 2022-12-04 14:03
@sobolevn I've added a small test to check the behavior of annotations w.r.t. inheritance. I've also updated the docs by adding a line to remark that annotations are not inherited anymore, but I'm not sure it is the right place for it.

**Comment by carljm** [comment] 2022-12-16 21:10
One additional note:

> Right now TypedDicts and NamedTuples inherit all annotations from parents. Classes are inconsistent to them.

I don't think this is quite accurate. NamedTuples behave the same as normal classes as far as the `__annotations__` attribute is concerned:

```
>>> from typing import NamedTuple
>>> class A(NamedTuple):
...     x: int
...
>>> A.__annotations__
{'x': <class 'int'>}
>>> class B(A):
...     pass
...
>>> B.__annotations__
{}
>>> class C(A):
...     y: str
...
>>> C.__annotations__
{'y': <class 'str'>}
```

i.e. `__annotations__` are not inherited, the same as for normal classes. Annotations from base classes are still considered when deciding what fields the subclass should have, though, which is something specific to the _use_ of annotations by `NamedTuple`. (The same is true for dataclasses.)

TypedDicts do indeed "inherit" `__annotations__`, but this is a special case because of TypedDicts having very unusual inheritance behavior. When you inherit a TypedDict, _all_ you get is its `__annotations__`; the base class itself does not even appear in your MRO! Anything subclassing `TypedDict` or any subclass of `TypedDict` ends up simply inheriting `dict`:

```
>>> from typing import TypedDict
>>> class A(TypedDict):
...     x: int
...
>>> A.__annotations__
{'x': <class 'int'>}
>>> class B(A):
...     pass
...
>>> B.__annotations__
{'x': <class 'int'>}
>>> B.mro()
[<class '__main__.B'>, <class 'dict'>, <class 'object'>]
>>> A.mro()
[<class '__main__.A'>, <class 'dict'>, <class 'object'>]
```

So in this special case "inheritance" of the `__annotations__` attribute is necessary because the inheritance hierarchy itself is not preserved.

**Closed as completed** 2022-12-24 20:07 UTC
Labels: type-bug, topic-typing

**Comment by FrozenBob** [comment] 2023-01-01 02:34
The pull request introduced a documentation error for `typing.get_type_hints`. `typing.get_type_hints` recursively merges annotations from parent classes, which has always been intended behavior. The pull request mixed up this behavior with the `__annotations__` inheritance change, and added an incorrect note to the `typing.get_type_hints` documentation claiming that `typing.get_type_hints` no longer does this.
