### ISSUE TITLE
isinstance(x, typing.Protocol-class) unexpectedly evaluates properties

### ISSUE THREAD

**Issue by b7e43491-e3cb-4e96-af27-0b032370507f** [python/cpython#89445] opened 2021-09-24 13:25 UTC
BPO | [45282](https://bugs.python.org/issue45282)
--- | :---
Nosy | @AlexWaygood, @daitakahashi
Files | <li>[test_protocol_property.py](https://bugs.python.org/file50303/test_protocol_property.py "Uploaded as text/plain at 2021-09-24.13:25:14 by @daitakahashi"): testcases</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-24.13:25:14.862>
labels = ['type-bug', '3.8', '3.9']
title = 'isinstance(x, typing.Protocol-class) unexpectedly evaluates properties'
updated_at = <Date 2021-09-24.14:52:18.540>
user = 'https://github.com/daitakahashi'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-24.14:52:18.540>
actor = 'AlexWaygood'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-09-24.13:25:14.862>
creator = 'daitakahashi'
dependencies = []
files = ['50303']
hgrepos = []
issue_num = 45282
keywords = []
message_count = 2.0
messages = ['402562', '402567']
nosy_count = 2.0
nosy_names = ['AlexWaygood', 'daitakahashi']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45282'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by AlexWaygood** [comment] 2023-03-05 14:36
Duplicate of #102433, which is a newer issue but has more discussion

**Closed as not planned by AlexWaygood** 2023-03-05 14:36 UTC
Labels: type-bug, 3.9 (EOL), 3.8 (EOL), topic-typing
