### ISSUE TITLE
new-bugs-announce notifier workflow fails on large bug reports

### ISSUE THREAD

**Issue by andersk** [python/cpython#106217] opened 2023-06-28 21:51 UTC
When I opened #106092, I got an email notification “new-bugs-announce notifier: All jobs have failed”, linking to https://github.com/python/cpython/actions/runs/5371513882. The error is

```
[Error: Bad Request] {
  status: 400,
  details: 'Send options (parameters starting with o:, h:, or v:) are limited to 16 kB total',
  type: 'MailgunAPIError'
}
Error: Unhandled error: Error: Bad Request
```

I guess the stack traces I included bumped the report size to more than 16 kB. It seems that this is not an uncommon problem: https://github.com/python/cpython/actions/workflows/new-bugs-announce-notifier.yml?query=is%3Afailure.

Perhaps the notifier should truncate or omit the body if the payload would be too long.

### Linked PRs
* gh-106329
* gh-106423

**Comment by hugovk** [comment] 2023-07-02 11:05
Thanks for the report! Let's close it as a duplicate of https://github.com/python/core-workflow/issues/456 and try the fix at https://github.com/python/cpython/pull/106329.

**Closed as not planned by hugovk** 2023-07-02 11:05 UTC
Labels: type-bug
