### ISSUE TITLE
Create modular packages for zipfile and test_zipfile

### ISSUE THREAD

**Issue by jaraco** [python/cpython#98098] opened 2022-10-08 18:45 UTC
I'm about to embark on once again syncing changes from [zipp](/jaraco/zipp) to `zipfile`.

Historically, I've manually copied the contents of the [cpython branch](/jaraco/zipp/tree/cpython) to the relevant files in this repository, but that process is error prone (because it involves syncing a whole file to a portion of another file).

I'd like to instead create packages for `zipfile` and `test_zipfile`, such that the functionality that's synced with `zipp` can be kept separate from other zipfile functionality. Moreover, late versions of `zipp` bring in extra dependencies so a package can also serve as a home to vendor such functionality.

I'm not suggesting to change the user's signature at all. The names will still be presented through the `zipfile` module unchanged.

### Linked PRs
* gh-98103

**Comment by jaraco** [comment] 2022-10-08 19:21
I tried moving most of `zipfile.py` to `zipfile/_core.py` but that caused problems with all of the global constants in that file, many of which are treated as mutable (at least for tests).

**Comment by hauntsaninja** [comment] 2022-11-29 06:12
Looks like this can be closed, but not touching it since I see it was assigned to Yhg1s and I don't know what that means

**Closed as completed** 2023-02-19 19:01 UTC
Labels: type-feature

**Comment by ilia1243** [comment] 2023-12-01 07:05
Hello, looks like this issue has lead to warning `<frozen runpy>:128: RuntimeWarning: 'zipfile.__main__' found in sys.modules after import of package 'zipfile', but prior to execution of 'zipfile.__main__'; this may result in unpredictable behaviour` when using https://docs.python.org/3/library/zipfile.html#command-line-interface

**Comment by gpshead** [comment] 2023-12-01 07:48
please file a new issue if you believe there is a bug with instructions for how to reproduce it.
