### ISSUE TITLE
`Import __hello__` no longer working

### ISSUE THREAD

**Issue by nhumrich** [python/cpython#115174] opened 2024-02-08 17:58 UTC
# Bug report

### Bug description:

```python
import __hello__
```

is no longer working as intended. I have tested on linux on 3.11.6 as well as in a docker container on 3.12.2.

```bash
$ docker run -it python
Unable to find image 'python:latest' locally
latest: Pulling from library/python
6a299ae9cfd9: Pull complete 
e08e8703b2fb: Pull complete 
68e92d11b04e: Pull complete 
5b9fe7fef9be: Pull complete 
09864a904dd0: Pull complete 
a21b4eeffed1: Pull complete 
14fa1d442750: Pull complete 
4c1733c93f94: Pull complete 
Digest: sha256:5eda1a3e78a90e7542c221cf525233f4b958a5778e61bcc350cc1e0d2bcf7ecf
Status: Downloaded newer image for python:latest
Python 3.12.2 (main, Feb  7 2024, 21:28:35) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import __hello__
>>> import __hello__
>>> print('Hello world...')
Hello world...
>>> 
```

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment] 2024-02-08 18:04
Duplicate of #100136

**Closed as not planned by AlexWaygood** 2024-02-08 18:04 UTC
Labels: type-bug
