### ISSUE TITLE
csv library does not correctly interpret some files

### ISSUE THREAD

**Issue by dbc649fd-0cc8-43ea-86a8-9554a66a2fa1** [python/cpython#88751] opened 2021-07-08 13:13 UTC
BPO | [44585](https://bugs.python.org/issue44585)
--- | :---
Nosy | @voidloop

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-08.13:13:28.860>
labels = ['library', '3.9']
title = 'csv library does not correctly interpret some files'
updated_at = <Date 2021-07-08.13:13:28.860>
user = 'https://github.com/voidloop'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-08.13:13:28.860>
actor = 'voidloop'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-07-08.13:13:28.860>
creator = 'voidloop'
dependencies = []
files = []
hgrepos = []
issue_num = 44585
keywords = []
message_count = 1.0
messages = ['397139']
nosy_count = 1.0
nosy_names = ['voidloop']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44585'
versions = ['Python 3.9']
```

</p></details>

**Comment by kwsp** [comment] 2023-03-20 00:39
Looks like what's happening is that in the given "test.csv" (which I put in the fenced code block below), there are sometimes spaces after the closing `quotechar` (`"` in this case).

```
"A" ,"B" ,"C"
"aaaaaa","bbbbbbb","cccc"
"aaaaa" ,"bbbbbb" ,"ccc"
"aaaa" ,"bbbbb" ,"cc"
```

This happens because currently when the CSV parser encounters the closing `quotechar`, it falls through to parsing the rest of the field as "unquoted field" until it encounters the "delimiter".

https://github.com/python/cpython/blob/main/Modules/_csv.c#L781

---

Now in the program you submitted to reproduce this issue, if you pass `strict=True` to `csv.register_dialect`, the program will throw a `_csv.Error`, since the input CSV data shouldn't have those spaces between the closing "quotechar" and the "delimiter".

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/tnie/code/cpython/Lib/csv.py", line 113, in __next__
    self.fieldnames
  File "/Users/tnie/code/cpython/Lib/csv.py", line 100, in fieldnames
    self._fieldnames = next(self.reader)
                       ^^^^^^^^^^^^^^^^^
_csv.Error: ',' expected after '"'
```

**Comment by kwsp** [comment] 2023-03-20 18:14
Sorry I was mistaken. I traced the execution and the "problem" is actually here. In quoted mode, after finding the closing quote, we get to the `QUOTE_IN_QUOTED_FIELD` branch, and if `strict=False`, it just keeps parsing (hence recording the white space between the closing quote and the delimiter).

https://github.com/python/cpython/blob/main/Modules/_csv.c#L820

**Comment by serhiy-storchaka** [comment] 2024-01-06 22:40
RFC 4180 does not say anything about ignoring spaces. Ignoring them will be violation of RFC 4180.

There is a special option `skipinitialspace` to skip initial spaces. We could add also `skiptrailingspace` if there is a number of CSV files that need it. What is the source of your example, @voidloop? If it is just manually created by human, it can be considered as error.

**Comment by voidloop** [comment] 2024-03-06 21:45
Right, it can be considered an error. I generated several manually and, driven by my need, I wrote impulsively. I apologize.

**Comment by serhiy-storchaka** [comment] 2024-03-06 22:12
No need to apologize. You did the right thing by reporting behavior that could have been a bug. Thank you for your report. But it turned out that it was not a bug, and this case is not sufficiently justified to add a new option.

**Closed as not planned by serhiy-storchaka** 2024-03-06 22:12 UTC
Labels: stdlib, 3.9 (EOL), pending
