### ISSUE TITLE
asyncio.get_event_loop() fails if there is no current event loop

### ISSUE THREAD

**Issue by vstinner** [python/cpython#94174] opened 2022-06-23 14:10 UTC
In Python 3.10, asyncio.get_event_loop() was modified to emit a DeprecationWarning if there is no current event loop. I propose to convert this deprecation into an exception. This change is part of issue #83710 plan.

What's New In Python 3.10:

> asyncio.get_event_loop() now emits a deprecation warning if there is no running event loop. In the future it will be an alias of get_running_loop(). asyncio functions which implicitly create Future or Task objects now emit a deprecation warning if there is no running event loop and no explicit loop argument is passed: ensure_future(), wrap_future(), gather(), shield(), as_completed() and constructors of Future, Task, StreamReader, StreamReaderProtocol. (Contributed by Serhiy Storchaka in bpo-39529.)

I'm working on a PR to implement this change.

**Comment by serhiy-storchaka** [comment] 2022-07-04 19:19
Isn't it a duplicate of #93453?

**Comment by kumaraditya303** [comment] 2022-10-16 16:53
Duplicate of https://github.com/python/cpython/issues/93453

**Comment by kumaraditya303** [comment] 2022-10-16 16:53
See discussion on https://github.com/python/cpython/issues/93453

**Closed as not planned by kumaraditya303** 2022-10-16 16:53 UTC
Labels: type-bug, topic-asyncio

**Comment by vstinner** [comment] 2022-11-04 13:50
> Isn't it a duplicate of https://github.com/python/cpython/issues/93453?

Right. I close my issue and my PR: https://github.com/python/cpython/pull/94175#issuecomment-1303571464
