### ISSUE TITLE
Problems about shift operator in Python

### ISSUE THREAD

**Issue by emreke6** [python/cpython#122714] opened 2024-08-06 01:31 UTC
# Bug report

### Bug description:

Dear,

I have a very simple python codes with addition multiplication and bit operations.

```python
# op: 10 + 5*8 = 50
res1 = 10 + 5 * 8

# op: 10 + 5<<3 = 120 ?
res2 = 10 + 5<<3

print(res1, res2)
```

In the above example, first operation (res1) results as 50 as expected. However, second operation (res) results as 120 instead of 50.

I know the reason which is that bitwise operators have same priority with addition but this seems wrong. Normally, bitwise operators are basicallay multipliers and dividers. They should be treated such that they have higher priority than addition or subtraction.

Thanks in advance,
Emre

### CPython versions tested on:

3.10

### Operating systems tested on:

macOS

**Comment by Octopus136** [comment] 2024-08-06 03:26
Hi, @emreke6 

In fact addition and subtraction always have a higher priority than left and right shifts in most languages.

You get the same result if you calculate `10 + 5 << 1 + 2` .

**Comment by skirpichev** [comment] 2024-08-06 03:29
> I know the reason which is that bitwise operators have same priority with addition but this seems wrong.

I not just "wrong".  It's not true.  In fact, bitwise shifts have lower priority wrt addition or subtraction.  The Python language here follows C, I guess:
https://en.cppreference.com/w/c/language/operator_precedence
vs
https://docs.python.org/3/reference/expressions.html#operator-precedence

> They should be treated such that they have higher priority than addition or subtraction.

This will be a huge compatibility break.

So, this is not a bug - it's a feature request.  If you are interested in pushing this - please open first a thread on discuss.python.org.

**Comment by tim-one** [comment] 2024-08-06 03:35
This is working as designed and documented, so closing this. The language has worked this way for decades, and there's no chance it will change.

**Closed as not planned by tim-one** 2024-08-06 03:35 UTC

**Comment by emreke6** [comment] 2024-08-06 12:48
> In fact addition and subtraction always have a higher priority than left and right shifts in most languages.



> This is working as designed and documented, so closing this. The language has worked this way for decades, and there's no chance it will change.

I am very aware of this situation but it just seems weird to me. Thank you for the discussion.

Regards,
Emre
