### ISSUE TITLE
Regression in threading support when running on older Docker

### ISSUE THREAD

**Issue by ddrinka** [python/cpython#106038] opened 2023-06-23 17:08 UTC
# Bug report

The Python 3.10.12 release repeatably throws `RuntimeError: can't start new thread` when run on an older version of Docker.  Reverting to Python 3.10.11 resolved the issue.  Running on Docker 20.10.24 does not exhibit the issue.

# Your environment

Docker 19.03.6-ce, build 369ce74
Paramiko 3.0.0

# Additional details

I'm utilizing the `paramiko` SSH client which uses basic threading.  Call stack included below though it appears the issue is with Python itself.

```
File "/app/./clone.py", line 51, in connect_to_ssh
  ssh_client.connect(hostname=hostname, port=port, username=username, password=password, look_for_keys=False, allow_agent=False, timeout=10, auth_timeout=60, banner_timeout=30)
File "/usr/local/lib/python3.10/site-packages/paramiko/client.py", line 420, in connect
  t.start_client(timeout=timeout)
File "/usr/local/lib/python3.10/site-packages/paramiko/transport.py", line 695, in start_client
  self.start()
File "/usr/local/lib/python3.10/threading.py", line 935, in start
  _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by sunmy2019** [comment] 2023-06-23 17:55
0.

Python3.10 is not accepting bug fixes.

1.

> Running on Docker 20.10.24 does not exhibit the issue.

Does this mean it is also possible that it's a bug in the docker?

2.

> Call stack included below though it appears the issue is with Python itself.

Then can you provide an example without using `paramiko`?

Also, you did not provide the base OS and the docker image you are using.

3.

> RuntimeError: can't start new thread

Python on Linux will set this on the failure of several pthread calls. So it is more likely the errors are inside the pthread library/OS syscalls, which in this case may blame on the docker.

4.

Python 3.10.12 is only a few more commits than Python 3.10.11. You can easily bisect (if it's really its problem).

https://github.com/python/cpython/commits/3.10

**Comment by sunmy2019** [comment] 2023-06-23 18:00
If you can build your own Python, you can print logs in this function:
https://github.com/python/cpython/blob/45de31db9cc9be945702f3a7ca35bbb9f98476af/Python/thread_pthread.h#L252-L320

**Comment by ddrinka** [comment] 2023-06-23 19:05
I won't be able to do a bunch to help diagnose the cause of the issue.  Just thought the team would like to know that something was introduced that might cause problems for others.

The base OS is Amazon Linux, and the docker image is python:3.10.12

**Comment by ethanhs** [comment] 2023-06-24 04:02
I am unable to reproduce this error using Docker 19.03 with Python 3.10.12 nor 3.11.4 (the latest stable image). Tested on Ubuntu 20.04.

**Comment by tkyanko** [comment] 2023-08-25 02:11
This seems like it might be an issue with the newer OS trying to call syscalls that aren't in the older Docker versions' [seccomp](https://docs.docker.com/engine/security/seccomp/) allowlists.  It may be related to a call in glibc or some other library as well.

**Comment by picnixz** [comment] 2024-09-07 12:34
Is this issue still relevant?

**Comment by ddrinka** [comment] 2024-09-10 23:10
Not for me.  I updated the version of Docker and moved on.

**Comment by picnixz** [comment] 2024-09-11 09:13
I'm closing this issue as being fixed (although I don't know when it was). For those this issue persists on the **latest stable** Python version (as of this time of writing, this would be 3.12.x), first **upgrade** Docker before opening an issue.

**Closed as completed by picnixz** 2024-09-11 09:13 UTC
Labels: type-bug, stdlib
