### ISSUE TITLE
Representation of Regular Expression Truncated

### ISSUE THREAD

**Issue by Blastus** [python/cpython#94059] opened 2022-06-21 13:30 UTC
**Bug report**

It appears that regular expression representations are sometimes truncated. This behavior shows up in the following example:

```
>>> import re
>>> # Reference: https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch07s13.html
>>> LOGGING_FORMAT = r'''^(?P<client>\S+)●\S+●(?P<userid>\S+)●\[(?P<datetime>[^\]]+)\]↵
... ●"(?P<method>[A-Z]+)●(?P<request>[^●"]+)?●HTTP/[0-9.]+"↵
... ●(?P<status>[0-9]{3})●(?P<size>[0-9]+|-)●"(?P<referrer>[^"]*)"↵
... ●"(?P<useragent>[^"]*)"'''
>>> RE_TABLE = str.maketrans('●', ' ', '↵\n')
>>> RE_LOGGING_FORMAT = LOGGING_FORMAT.translate(RE_TABLE)
>>> RE_LOGGING_PATTERN = re.compile(RE_LOGGING_FORMAT)
>>> print(repr(RE_LOGGING_FORMAT))
'^(?P<client>\\S+) \\S+ (?P<userid>\\S+) \\[(?P<datetime>[^\\]]+)\\] "(?P<method>[A-Z]+) (?P<request>[^ "]+)? HTTP/[0-9.]+" (?P<status>[0-9]{3}) (?P<size>[0-9]+|-) "(?P<referrer>[^"]*)" "(?P<useragent>[^"]*)"'
>>> print(RE_LOGGING_PATTERN)
re.compile('^(?P<client>\\S+) \\S+ (?P<userid>\\S+) \\[(?P<datetime>[^\\]]+)\\] "(?P<method>[A-Z]+) (?P<request>[^ "]+)? HTTP/[0-9.]+" (?P<status>[0-9]{3}) (?P<size>[0-9]+|-) "(?P<referrer>[^"]*)" "(?P<useragent)
```

The validity of the built Pattern object can be considered using the following line:

`>>> re.compile(RE_LOGGING_FORMAT, re.DEBUG)`

**Your environment**

- CPython versions tested on: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
- Operating system and architecture: Windows-10-10.0.22000-SP0 64bit WindowsPE

**Comment by AlexWaygood** [comment] 2022-06-21 14:55
Duplicate of #70256

**Closed as not planned by AlexWaygood** 2022-06-21 14:55 UTC
Labels: type-bug, topic-regex
