### ISSUE TITLE
IDLE File saving bug seemingly new on macOS Ventura

### ISSUE THREAD

**Issue by YourUsualFenderStrat** [python/cpython#99565] opened 2022-11-17 14:32 UTC
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by YourUsualFenderStrat** [comment] 2022-11-17 14:33
Every time I try and save a python file to run it python freezes, I get the spinning rainbow thingy, basically it stops responding and then crashes

**Comment by YourUsualFenderStrat** [comment] 2022-11-17 14:58
I don't know but I use the python IDLE quite often, and since upgrading to Ventura I have been unable to save and run files using the IDLE,

**Comment by ronaldoussoren** [comment] 2022-11-17 15:57
My initial message and your first update crossed paths, that's exactly what I was looking for: IDLE is hanging when you try to save or run files. 

I have a lot of  questions that might help pinpoint the problem. 

1. Which version of Python to you use?
2. How did you install Python? Did you use the installer on www.python.org or some other method?
3. How did you start IDLE, using the application in /Applications/Python X.Y or from the command line?
4. Looking at the "Privacy & Security" pane in System Settings, is there an entry for Python or IDLE in the "Files and Folders" section? And if so, is that for the "Documents Folder" and is that enabled?

And finally an experiment, assuming you normally start IDLE in the Finder. Can you run "/Applications/Python X.Y/IDLE.app/Contents/MacOS/IDLE" in a terminal window (replace "X.Y" by the version of Python you are using, and include the quotation marks (needed due to the space in the path).  Can you save files when you start IDLE like this? And if not, does IDLE print error messages?

**Comment by ronaldoussoren** [comment] 2022-11-17 15:59
Possibly related: https://github.com/python/cpython/issues/84108 (although the error is different in that issue)

**Comment by terryjreedy** [comment] 2022-11-29 04:12
Ronald, thank you for attending to current macOS issues.  My MacBook Air from about 2012 cannot update past Catalina.

**Comment by ronaldoussoren** [comment] 2022-12-09 09:04
I cannot reproduce this issue locally and there is too little information in the issue to troubleshoot. I'm therefore closing this issue.

The issue can be reopened when there is more information (see my previous message).

**Closed as not planned by ronaldoussoren** 2022-12-09 09:04 UTC
Labels: type-bug, OS-mac, topic-IDLE
