### ISSUE TITLE
Repeated string concatenation much slower starting with Python 3.11

### ISSUE THREAD

**Issue by dadap** [python/cpython#122203] opened 2024-07-23 21:35 UTC
# Bug report

### Bug description:

Trivial reproducer; concatenates a million spaces and prints time since start every fifty thousand iterations:

```python
#!/usr/bin/env python3

import time

start=time.time()
concat=''
count=0

while count < 1000000:
    concat += ' '
    count += 1
    if (count % 50000 == 0):
        print(f'{count}: {time.time() - start}')
```

With cpython 3.10, this runs to completion nearly instantly:

```
$ python3.10 concat.py 
50000: 0.012315034866333008
100000: 0.01887059211730957
150000: 0.025367021560668945
200000: 0.03182864189147949
250000: 0.038453102111816406
300000: 0.04492950439453125
350000: 0.05142927169799805
400000: 0.058084726333618164
450000: 0.06461119651794434
500000: 0.0711672306060791
550000: 0.07768106460571289
600000: 0.08418941497802734
650000: 0.09066891670227051
700000: 0.09713101387023926
750000: 0.10375785827636719
800000: 0.1103205680847168
850000: 0.11682963371276855
900000: 0.12338542938232422
950000: 0.12988734245300293
1000000: 0.13641619682312012
```

But with cpython 3.11 (and later, also tested with cpython built from top of tree main branch), the concatention operations become progressively slower:

```
$ python3.11 concat.py 
50000: 0.03374743461608887
100000: 0.14004302024841309
150000: 0.36527204513549805
200000: 0.7147610187530518
250000: 1.186763048171997
300000: 1.7870004177093506
350000: 2.520460367202759
400000: 3.3907878398895264
450000: 4.411084890365601
500000: 5.588932514190674
550000: 6.927828311920166
600000: 8.437948942184448
650000: 10.136655569076538
700000: 12.02797794342041
750000: 14.119840860366821
800000: 16.427090406417847
850000: 18.95009994506836
900000: 21.679301738739014
950000: 24.6390597820282
1000000: 27.896022081375122
```

A bisection identifies commit 9178f533ff5ea7462a2ca22cfa67afd78dad433b as the first commit with the slower behavior. From a quick skim, it seems there was some specialized code for concatenating Unicode strings which is no longer used, but I didn't look into it any further than identifying the regression point. Credit to @clsn for noticing the issue in a script that took approximately a second to concatenate "only" about 300K lines of text, a line at a time, in cpython 3.10, and approximately two hours in cpython 3.11.

### CPython versions tested on:

3.10, 3.11, 3.12, CPython main branch

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment] 2024-07-23 21:36
Duplicate of #99862

**Closed as not planned by JelleZijlstra** 2024-07-23 21:36 UTC
Labels: type-bug

**Comment by dadap** [comment] 2024-07-23 21:43
Thanks for quickly identifying this as a duplicate. I would have been surprised if it hadn't been noticed already. :) Looking at #99862 it seems that the optimization is still available for local variables if one *truly* needs to do repeated string concatenation. (The code where this was noticed didn't actually need to do this and has already been changed, but it seemed like the sort of thing that might be useful elsewhere.)
