### ISSUE TITLE
Code blocks in some older versions of Python docs do not respect dark mode properly

### ISSUE THREAD

**Issue by EnronEvolved** [python/cpython#116140] opened 2024-02-29 19:14 UTC
# Documentation

I was looking through the Python documentation today, for my system's installed version of Python, and found an eye-searing issue with the documentation on the latest version of Firefox:

When viewing the latest version, everything's fine:
![noeyepain](https://github.com/python/cpython/assets/29132145/0acaf2cc-9d06-46df-bf4d-b44b6fa4535e)

However, viewing a previous version, the colours used in code blocks seem to be a strange hybrid of light and dark theming that is unreadable without highlighting the code:
![eyepain](https://github.com/python/cpython/assets/29132145/c25ff9db-fb81-4fc8-8b79-3bf1404c35de)

Doing a little investigation, the error seems to be present on versions 3.8 and 3.9.

**Comment by hugovk** [comment] 2024-02-29 19:40
Thanks for the report.

This is a duplicate of https://github.com/python/cpython/issues/115349 which has been fixed, and will be deployed when the next 3.8 and 3.9 releases go out, which I think should be quite soon.

In the meantime, you can switch to the light theme, or visit the docs for 3.10 or later.

**Closed as not planned by hugovk** 2024-02-29 19:40 UTC
Labels: docs, 3.9 (EOL), 3.8 (EOL)
