### ISSUE TITLE
multiprocessing pool skips some jobs when the number of processes is set too large

### ISSUE THREAD

**Issue by jingyangcarl** [python/cpython#113305] opened 2023-12-20 05:21 UTC
# Bug report

### Bug description:

I'm using a multiprocessing Pool to process json blocks in a parallel way and store the resutls in a Manager().dict(). However, when the number of processes is set too large, there will be some jobs been skipped. 
```python
import multiprocessing as mp
mp.cpu_count() # 32
pool = mp.Pool(processes=64) # this skips no jobs
pool = mp.Pool(processes=128) # this will skip around 4 jobs
pool = mp.Pool(processes=512) # this will skip around 12 jobs
```

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux
```[tasklist]
### Tasks
```

**Comment by gaogaotiantian** [comment] 2023-12-20 06:27
Can you give us a reproducible example? The code you gave won't have any issue as there will be no job. Can you put together a full example that can show "missing jobs"?

**Comment by jingyangcarl** [comment] 2023-12-20 21:15
`
def parse_pdf(url_pdf):
    #parsing pdf files here and returning some metadata via pypdf
    return {'title': title}

pool = mp.Pool(processes=64) # larger number of processes will cause job skipping
pool_ret = mp.Manager().dict()
pbar = tqdm(total=len(e_pdfs)')
def mpupdate(x):
    pool_ret[x['title']] = x
    pbar.update(1)
for i in range(pbar.total):
    title = e_pdfs[i].text_content().strip()
    url_paper = os.path.dirname(args[year][conf]['url_open']) + e_pdfs[i].attrib['href']
    pool.apply_async(parse_paper_url, (title, url_paper,), callback=mpupdate)
pool.close()
pool.join()
`
Please check this out. The returned length in pool_ret is smaller than that in len(e_pdfs) when the processes setting is large.

**Comment by gaogaotiantian** [comment] 2023-12-20 21:38
Sorry but this is still not a full example. A full example is a piece of code that we can simply copy and run, then reproduce the issue you mentioned.

We don't know what is `args` or `e_pdfs`, we don't know if they are related to the issue. For example, if your `url_paper` is duplicated (because of the data in `e_pdfs`), your `pool_ret` could be smaller than you expect.

If it is an issue with `multiprocessing.Pool`, then you should be able to reproduce it without the external dependencies, like `args` or `e_pdfs`. You should not need `tqdm` either. A simple mock work plus the assertion of the list(dict?) should do.

**Comment by encukou** [comment] 2024-02-13 14:35
I could not reproduce.
Without more information -- preferably a full example that can run by itself -- we can't fix the issue.
I'll close the issue; if you have more info please add it and we can reopen.

**Closed as not planned by encukou** 2024-02-13 14:35 UTC
Labels: type-bug, topic-multiprocessing
