### ISSUE TITLE
importlib.import_module() doesn't raise ModuleNotFoundError for non-existent modules in Python 3.11.4+.

### ISSUE THREAD

**Issue by felixxm** [python/cpython#108078] opened 2023-08-17 09:48 UTC
### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.11.4 (main, Jul 19 2023, 08:05:31) [GCC 11.3.0]

### A clear and concise description of the bug:

```python
# Python 3.11.4
# importlib.import_module() doesn't raise ModuleNotFoundError for non-existent modules.
>>> from importlib import import_module
>>> import_module("django.contrib.contenttypes.templatetags")
<module 'django.contrib.contenttypes.templatetags' from '/django/django/templatetags/__init__.py'>
```

```python
# Python 3.10.9
>>> from importlib import import_module
>>> import_module("django.contrib.contenttypes.templatetags")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.contrib.contenttypes.templatetags'
```

**Comment by Eclips4** [comment] 2023-08-17 09:54
Hello!
I don't see any non-existent modules in the first example. 
You try to import django module (or package, it doesn't matter) and its imported. Maybe you have installed django in your virtual environment?

Please, explain why do you think this is a bug.

**Comment by felixxm** [comment] 2023-08-17 09:57
> Please, explain why do you think this is a bug.

`templatetags` module [doesn't exist](https://github.com/django/django/tree/main/django/contrib/contenttypes) in `django.contrib.contenttypes`.

**Comment by felixxm** [comment] 2023-08-17 10:00
Many of our tests stopped working after bumping to Python 3.11.4, check out CI [logs](https://djangoci.com/job/main-no-requirements/).

**Comment by Eclips4** [comment] 2023-08-17 10:02
> > Please, explain why do you think this is a bug.
> 
> `templatetags` module [doesn't exist](https://github.com/django/django/tree/main/django/contrib/contenttypes) in `django.contrib.contenttypes`.

Interesting. I cannot reproduce it local. I've tried it on python `3.11.4` and django `4.2.4`:
```python
Python 3.11.4 (main, Jul 25 2023, 17:36:13) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib import import_module
>>> import_module("django.contrib.contenttypes.templatetags")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.contrib.contenttypes.templatetags'
```

**Comment by felixxm** [comment] 2023-08-17 10:08
> Did I miss something?

:thinking: Maybe it's an issue in "editable" mode: `pip install -e <django_main_directory>`.

**Comment by Eclips4** [comment] 2023-08-17 10:13
> > Did I miss something?
> 
> 🤔 Maybe it's an issue in "editable" mode: `pip install -e <django_main_directory>`.

Oh, you're right. With editable mode I can reproduce it:
```python
Python 3.11.4 (main, Jul 25 2023, 17:36:13) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib import import_module
>>> import_module("django.contrib.contenttypes.templatetags")
<module 'django.contrib.contenttypes.templatetags' from '/Users/admin/PycharmProjects/django/django/templatetags/__init__.py'>
>>> 
```

**Comment by Eclips4** [comment] 2023-08-17 10:15
I'm not expert in this area, but it's looks like a problem with pip editable mode.

**Comment by wd0517** [comment] 2023-08-17 10:17
not only `3.11.4`, but `3.10.12` and `3.8.10` on my machine also have this strange behavior with editable mode

**Comment by felixxm** [comment] 2023-08-17 17:12
I checked and 3.11.3 is also affected (we've bumped 3.11.1 to 3.11.4 on our CI). I will try to bisect this regression.

**Comment by erlend-aasland** [comment] 2023-08-17 17:32
Thanks, @felixxm

**Comment by felixxm** [comment] 2023-08-18 16:03
I'm extremely puzzled :detective: . Yesterday I was able to reproduce this issue on different Python versions (build from source, build directly from branches, packed, etc.) on new and existing virtual environments. Today everything works fine :exploding_head:

**Comment by brettcannon** [comment] 2023-08-18 19:51
I'm going to close this as I assume this is an issue with how some build tool is doing editable installs since it would make it very easy to "succeed" in finding any and all module names you want. Plus Python has not changed anything around this in years, so since this is a new issue I'm going to guess it's a 3rd-party issue.

**Closed as not planned by brettcannon** 2023-08-18 19:51 UTC
Labels: type-bug, topic-importlib

**Comment by felixxm** [comment] 2023-08-19 08:32
Thanks for closing, and sorry for the false report.

**Comment by brettcannon** [comment] 2023-08-21 22:13
> Thanks for closing, and sorry for the false report.

No need to apologize! It's an honest mistake we have all made on _some_ project at some point.
