### ISSUE TITLE
Setting a `int` type value to `message` argument of `warnings.warn()` gets a wrong or abstract error message

### ISSUE THREAD

**Issue by hyperkai** [python/cpython#125827] opened 2024-10-22 05:27 UTC
# Bug report

### Bug description:

Setting the `int` type value `100` to `message` argument of [warnings.warn()](https://docs.python.org/3/library/warnings.html#warnings.warn) gets the 1st error message as shown below:

```python
import warnings
#             ↓ ↓ ↓ ↓ ↓ ↓
warnings.warn(message=100) # Error
```

> TypeError: expected string or bytes-like object, got 'int'

But, setting a bytes-like object to `message` argument of `warnings.warn()` gets the 2nd error message as shown below:

```python
import warnings

warnings.warn(message=b"Hello World") # Error
warnings.warn(message=bytes(source="Hello World", encoding="utf-8")) # Error

print(type(b"Hello World"))  # <class 'bytes'>
print(type(bytes(source="Hello World", encoding="utf-8"))) # <class 'bytes'>
```

> TypeError: cannot use a string pattern on a bytes-like object

So, I set a `str` type value using [decode()](https://docs.python.org/3/library/stdtypes.html#bytes.decode) to `message` argument of `warnings.warn()`, then it works as shown below:

```python
import warnings

warnings.warn(message=b"Hello World".decode(encoding="utf-8")) # Works
warnings.warn(message=bytes(source="Hello World", encoding="utf-8").decode(encoding="utf-8")) # Works

print(type(b"Hello World".decode(encoding="utf-8"))) # <class 'str'>
print(type(bytes(source="Hello World", encoding="utf-8").decode(encoding="utf-8"))) # <class 'str'>
```

So, the 1st error message should be something like below:

> TypeError: expected string, got 'int'

Or, It's better to say `str` which is more exact(precise) than `string`:

> TypeError: expected `str`, got 'int'

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by picnixz** [comment] 2024-10-22 08:34
Related: https://github.com/python/cpython/issues/47889

**Comment by picnixz** [comment] 2024-10-22 08:40
Actually, after some investigation, it appears that I cannot reproduce the issue again:

```pycon
>>> import warnings
>>> warnings.warn(5)
<python-input-1>:1: UserWarning: 5
  warnings.warn(5)
```

**Comment by picnixz** [comment] 2024-12-01 18:03
Closing since I couldn't reproduce the issue and the OP did not reply for a while.

**Closed as not planned by picnixz** 2024-12-01 18:03 UTC
Labels: type-bug
