### ISSUE TITLE
Pdb crashes after jump with `Fatal Python error: _PyMem_DebugRawFree: bad trailing pad byte`

### ISSUE THREAD

**Issue by komoto48g** [python/cpython#91742] opened 2022-04-20 13:29 UTC
**Crash report**

Access violation occurs when using `pdb` in the following procedure:
1. step in a function
2. step next a few lines inside `print` function
3. before exiting `print` function, jump to the beginning of the code 
4. continue

<details>
  <summary>Code Example [test_pdb.py] (click to expand)</summary>

```python
__author__ = "pi"
__version__ = "3.14"

def about():
    """About"""
    print(f"Module: {__file__!r}",
          f"Author: {__author__!r}",
          f"Version: {__version__!r}",
          sep='\n')

breakpoint()
about()
```
</details>

**Error messages**

$ python -Wd -Xdev -Xtracemalloc test_pdb.py
```
> test_pdb.py(12)<module>()
-> about()
(Pdb) s
--Call--
> test_pdb.py(4)about()
-> def about():
(Pdb) n
> test_pdb.py(6)about()
-> print(f"Module: {__file__!r}",
(Pdb) n
> test_pdb.py(7)about()
-> f"Author: {__author__!r}",
(Pdb) j 4
> test_pdb.py(4)about()
-> def about():
(Pdb) c
Module: 'test_pdb.py'
Author: 'pi'
Version: '3.14'
Debug memory block at address p=0000021D17AD8CF0: API 'o'
    432 bytes originally requested
    The 7 pad bytes at p-7 are FORBIDDENBYTE, as expected.
    The 8 pad bytes at tail=0000021D17AD8EA0 are not all FORBIDDENBYTE (0xfd):
        at tail+0: 0x90 *** OUCH
        at tail+1: 0x46 *** OUCH
        at tail+2: 0x05 *** OUCH
        at tail+3: 0x17 *** OUCH
        at tail+4: 0x1d *** OUCH
        at tail+5: 0x02 *** OUCH
        at tail+6: 0x00 *** OUCH
        at tail+7: 0x00 *** OUCH
    Data at p: 00 00 00 00 00 00 00 00 ... f0 b4 b5 16 1d 02 00 00

Memory block allocated at (most recent call first):
  File "test_pdb.py", line 12

Fatal Python error: _PyMem_DebugRawFree: bad trailing pad byte
Python runtime state: finalizing (tstate=0000021D169BEA10)

Current thread 0x000033f0 (most recent call first):
<no Python frame>
```

**Your environment**

- CPython versions tested on: 3.10.4
- Operating system and architecture: Windows10 64bit

**Comment by dignissimus** [comment] 2022-06-21 20:13
Commit cf345e945f48f54785799390c2e92c5310847bd4 introduced this issue.
Running the following minimal example with the below input reproduces the crash.
```python
def function():
    print(  
      3       
    )
    
breakpoint()
function()
```
```s
n
n
j 1
c

```

**Comment by dignissimus** [comment] 2022-06-21 21:29
PDB attempts to access `f_lineno` but in doing so it dereferences a null pointer as `self.curframe` is NULL.
https://github.com/python/cpython/blob/4abab6b603dd38bec1168e9a37c40a48ec89508e/Lib/pdb.py#L1172

**Comment by kumaraditya303** [comment] 2022-06-22 10:16
Changing `Py_DECREF` to `Py_XDECREF` fixes the issue but I'll let @markshannon decide if it is the correct fix.

cc @markshannon

**Comment by markshannon** [comment] 2022-06-22 11:07
This looks like an old bug, probably dating back to the introduction of `LOAD_METHOD`.
`LOAD_METHOD` pushes a `NULL` to stack, which could cause this crash. `LOAD_GLOBAL` can also push a `NULL`, making this bug much easier to trigger.

@kumaraditya303 your fix looks correct.

**Comment by kumaraditya303** [comment] 2022-06-24 11:44
Python 3.11 and 3.12 (main) both are fixed now.

---
However Python 3.10 is also affected but it crashes on different assertion.

```console
python: Python/ceval.c:3040: _PyEval_EvalFrameDefault: Assertion `STACK_LEVEL() <= co->co_stacksize' failed.
```
cc @markshannon

**Comment by pablogsal** [comment] 2022-06-27 17:55
Removing the 3.11 and 3.12 tags so these are fixed in 3.11 and 3.12.

**Comment by pablogsal** [comment] 2022-08-02 17:57
I'm removing the release blocker flag because 3.10 was already crashing with this. This will be treated as a regular bugfix.

**Comment by sunmy2019** [comment] 2023-06-17 03:28
Closed as 3.10 is no longer available for bug fixes

**Closed as completed by sunmy2019** 2023-06-17 03:28 UTC
Labels: 3.10, type-crash
