### ISSUE TITLE
[C API] Add PySet_NextEntry() function

### ISSUE THREAD

**Issue by vstinner** [python/cpython#121125] opened 2024-06-28 11:19 UTC
# Feature or enhancement

The `_PySet_NextEntry()` function was removed in Python 3.13 alpha 1, but it's used by the Blender project: https://projects.blender.org/blender/blender/search?q=_PySet_NextEntry

I propose adding a new function to replace it:

```
int PySet_NextEntry(PyObject *set, Py_ssize_t *pos, PyObject **key)
```

* Set `*key` to a strong reference, and return 1 on success.
* Return 0 if there is no more item.
* Set an exception and return -1 on error.

Differences with `_PySet_NextEntry()`:

* *key* is set to a **strong** reference, rather than a borrowed reference.
* Remove the *hash* parameter.

**Comment by vstinner** [comment] 2024-06-28 11:22
cc @AdamWill

**Comment by erlend-aasland** [comment] 2024-06-28 11:26
Meta: why the `pending` label? Are you considering immediately closing your newly opened issue? :)

**Comment by vstinner** [comment] 2024-06-28 11:29
I added "pending" label by mistake, I don't know how. Removed.

**Comment by encukou** [comment] 2024-06-28 13:33
Why is this better than `PyObject_GetIter` & `PyIter_Next`?

**Comment by AdamWill** [comment] 2024-06-28 15:29
Poking around, it's also used in [Numba](https://github.com/search?q=repo%3Araybellwaves%2Fnumba%20_PySet_NextEntry&type=code). PyO3 (Rust bindings for Python) used to use it but changed that recently in https://github.com/PyO3/pyo3/pull/3849 . [llvm-opt-benchmark](https://github.com/search?q=repo%3Adtcxzyw%2Fllvm-opt-benchmark%20_PySet_NextEntry&type=code) seems to use it, but I think that's just benchmarking how fast it is when you build CPython with LLVM or something; presumably they could just...stop benchmarking that specific function. Everything else I can find at least in github universal search is some kind of fork or copy of CPython or one of the other users, or an alternative C interpreter providing its own version.

**Comment by serhiy-storchaka** [comment] 2024-06-28 16:53
Do you want to add only `PySet_NextEntry()`, or also `PyFrozenSet_NextEntry()` and `PyAnySet_NextEntry()`?

See #43090 for discussion about `PySet_Next()`.

cc @rhettinger

**Comment by vstinner** [comment] 2024-06-29 11:13
I expect the function to work on set, frozenset and subclasses.

**Comment by rhettinger** [comment] 2024-06-30 15:46
I prefer people to just use `__iter__` and `__next__`.  Those are reasonably fast, are standard, are well-understood, and have strong guarantees around them (something that will become even more important in free-threaded code).

The `_PySet_NextEntry` API is fragile, hard to use correctly, and too tightly coupled to implementation details. It was intended solely an internal optimization hack.  The warning comment for `set_next` is dead serious. Even for internal calls, we've had bugs related to its use.

**Comment by rhettinger** [comment] 2024-06-30 16:03
FWIW, it was an intentional decision to not make this a public API.

The API was carefully thought out to provide what most people need from a set object.  Implementation details, optimization hacks, and fragile interfaces were avoided.  For the most part, this has served us well.

**Closed as not planned** 2024-07-05 19:34 UTC
Labels: type-feature, topic-C-API

**Comment by vstinner** [comment] 2024-07-08 08:56
@AdamWill: Well, it seems like Blender, other mentioned projects, have to be updated to PyObject_GetIter() and PyIter_Next().
