### ISSUE TITLE
'inspect.getmembers()' delivers attribute '__annotations__' for class 'module' that does not exist

### ISSUE THREAD

**Issue by siegbert7** [python/cpython#123506] opened 2024-08-30 13:20 UTC
# Bug report

### Bug description:

```python
# Add a code block here, if required

# Demonstrate AttributeError: type object 'module' has no attribute '__annotations__'
# Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32

import sys, inspect

pObj = type(sys)
print(pObj)             # <class 'module'>

for name, value in iter(inspect.getmembers(pObj)):                                # Delivers member '__annotations__'
    print(name)
    try                     :   obj = eval('pObj.'+name)                                      # Works fine, except for '__annotations__'
    except AttributeError   :   print('***********************************')    # AttributeError: type object 'module' has no attribute '__annotations__'
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment] 2024-08-30 13:21
Duplicate of #123242

**Closed as not planned by Eclips4** 2024-08-30 13:21 UTC
Labels: type-bug
