### ISSUE TITLE
refleak test for test_socket on macOS is failed.

### ISSUE THREAD

**Issue by corona10** [python/cpython#114049] opened 2024-01-14 07:00 UTC
# Bug report

```
➜  cpython git:(main) ✗ ./python.exe -m test test_socket -R 3:3
Using random seed: 2290437226
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 2.83 Run 1 test sequentially
0:00:00 load avg: 2.83 [1/1] test_socket
beginning 6 repetitions
123456
/Users/user/oss/cpython/Lib/test/test_socket.py:2934: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg_into([buf], *args)
/Users/user/oss/cpython/Lib/test/test_socket.py:2843: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg(bufsize, *args)
./Users/user/oss/cpython/Lib/test/test_socket.py:2934: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg_into([buf], *args)
/Users/user/oss/cpython/Lib/test/test_socket.py:2843: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg(bufsize, *args)
./Users/user/oss/cpython/Lib/test/test_socket.py:2934: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg_into([buf], *args)
/Users/user/oss/cpython/Lib/test/test_socket.py:2843: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg(bufsize, *args)
./Users/user/oss/cpython/Lib/test/test_socket.py:2934: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg_into([buf], *args)
/Users/user/oss/cpython/Lib/test/test_socket.py:2843: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg(bufsize, *args)
./Users/user/oss/cpython/Lib/test/test_socket.py:2934: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg_into([buf], *args)
/Users/user/oss/cpython/Lib/test/test_socket.py:2843: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg(bufsize, *args)
./Users/user/oss/cpython/Lib/test/test_socket.py:2934: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg_into([buf], *args)
/Users/user/oss/cpython/Lib/test/test_socket.py:2843: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg(bufsize, *args)
.
test_socket leaked [20, 20, 20] file descriptors, sum=60
test_socket failed (reference leak) in 3 min 8 sec

== Tests result: FAILURE ==

1 test failed:
    test_socket

Total duration: 3 min 8 sec
Total tests: run=483 skipped=245
Total test files: run=1/1 failed=1
Result: FAILURE
```

This happens in both the default build and the free-threaded build.
It looks like we have not detected this issue for a long time.
According to @itamaro there is not refleak builder for macOS at all.
https://github.com/python/buildmaster-config/pull/444#discussion_r1398317056

**Comment by Eclips4** [comment] 2024-01-14 07:58
I doesn't sure, but it's probably a duplicate of #80931

**Closed as not planned** 2024-01-14 07:59 UTC
Labels: type-bug, OS-mac
