### ISSUE TITLE
How to enable Secure Coding on mac sonoma?

### ISSUE THREAD

**Issue by Bilalxan** [python/cpython#111082] opened 2023-10-19 15:38 UTC
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
import turtle

timmy = turtle.Turtle()

print(timmy)

This is terminal:
2023-10-19 20:37:44.070 Python[13669:791789] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by ned-deily** [comment] 2023-10-19 16:29
Thanks for the report. This is a duplicate of #110950.

**Closed as not planned** 2023-10-19 16:30 UTC
Labels: type-bug, OS-mac
