### ISSUE TITLE
sysconfig.get_config_var("LDLIBRARY") returns non-existent libname

### ISSUE THREAD

**Issue by ze897c** [python/cpython#111268] opened 2023-10-24 15:02 UTC
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
HI folks, this is almost certainly not a bug with `sysconfig`, but I am not sure. While debugging issue "installing" USD, I ran into a dead end trying to hack build script. `sysconfig.get_config_var("LDLIBRARY")` returns `libpython3.11.a`, which is not present. Further digging, the auto-gen Makefile (<path-to-conda-env>/lib/python3.11/config-3.11-x86_64-linux-gnu/Makefile) reads

```
LDLIBRARY= libpython$(VERSION)$(ABIFLAGS).a
```

Again, sorry if this is the wrong place, but my hope is that folks here can help me correctly direct it ...perhaps a `miniconda` bug?

```bash
$ uname -a                                                                                                                                                                       exit 2
Linux baikal 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 3.11.5
```
```python
>>> sys.implementation
namespace(name='cpython', cache_tag='cpython-311', version=sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0), hexversion=51054064, _multiarch='x86_64-linux-gnu')
```
Thanks for any direction.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by FFY00** [comment] 2023-10-24 20:24
Could you give me instructions to set up an environment able to reproduce this?

**Comment by FFY00** [comment] 2023-12-19 18:29
@ze897c friendly ping.

**Comment by picnixz** [comment] 2024-12-02 12:39
Closing since the OP did not reply for a year.

**Closed as not planned by picnixz** 2024-12-02 12:39 UTC
Labels: type-bug, topic-sysconfig
