### ISSUE TITLE
Ref leaks in `test_peg_generator`

### ISSUE THREAD

**Issue by sunmy2019** [python/cpython#105087] opened 2023-05-30 11:14 UTC
# Bug report

Previously, `test_peg_generator` is skipped -- distutils has been removed in Python 3.12

Now it's added back in #104798 and is leaking references.

Recent builtbot results:
https://buildbot.python.org/all/#/builders/259/builds/775
```
test_peg_generator leaked [68, 68, 68] references, sum=204
test_peg_generator leaked [52, 52, 52] memory blocks, sum=156

**Comment by AlexWaygood** [comment] 2023-05-30 11:17
Duplicate of #105063

**Closed as not planned by AlexWaygood** 2023-05-30 11:17 UTC
Labels: type-bug
