### ISSUE TITLE
problem with using a keyword with non-ASCII chars

### ISSUE THREAD

**Issue by metebalci** [python/cpython#105898] opened 2023-06-18 21:23 UTC
I believe that it is not written anywhere that a keyword can contain non-ASCII characters. However, if it is supposed to work (like identifiers), it is not working. Because, I think, `reserved_keywords` in auto-generated `parser.c` contains the keywords grouped by their actual string/code-point length (because `c_generator.py` calls `len()` for the keywords), but `_get_keyword_or_name_type` in `pegen.c` is called with a byte length. For example, a new keyword called `eğer` is kept together with `else` in `reserved_keywords`, but the function `_get_keyword_or_name_type` would be called with 5 instead of 4; hence, the keyword `eğer` cannot be found and token type is not correctly set but left as `NAME`. It seems there are a few different ways to fix this, I am trying the alternatives. If this is considered a bug, I can submit a pr.

I tested this on 3.11.4.

**Comment by pochmann** [comment] 2023-06-19 00:04
What do you mean with using a keyword with non-ASCII chars? There are only a few dozen [keywords](https://docs.python.org/3/reference/lexical_analysis.html#keywords) and all of them are ASCII.

**Comment by ericvsmith** [comment] 2023-06-19 00:51
Please show your test: including what you tried, what you expected, and what actually happened.

That said, I don't think we plan on adding any non-ascii keywords.

**Comment by terryjreedy** [comment] 2023-06-19 01:19
It was GvR's policy and remains our group policy that programming Python and using the stdlib should not require the ability to enter non-ascii characters.  Numerous proposals to use non-ascii characters in names and syntax have been rejected.  So it is not a bug that the CPython implementation assumes this.

Add a feature would require a test.  This would be much easier if and when we had such a keyword.

**Comment by metebalci** [comment] 2023-06-19 07:23
@ericvsmith not entirely clear to me what kind of test I can provide, a modified `python.gram` and a failing test in `test_grammar.py`?

@terryjreedy Yes, I understand. It might be expected a bit naturally because identifiers can contain such characters. However, I cannot think of a reason that this could be requested as a feature for keywords until someone wants to have an alternative Python language with keywords in another human language, which I was just trying out of curiosity. So, this issue can be closed or I can write to python-ideas maybe, not sure how it should proceed.

On the other hand, leaving the support for non-ASCII keywords aside, I think it makes sense for the `peg_generator` to give an error and fail if such a keyword is encountered. That might be a reasonable bug or feature request.

**Comment by ericvsmith** [comment] 2023-06-19 15:11
@metebalci: without some details, your error report is basically "I changed something and something bad happened". We can't guess what you did. I was trying to get some details so we could see if what you tried was reasonable or not. You did provide some more details: you were changing `python.gram` and running unit tests, so I assume the build didn't fail.

But as @terryjreedy says, using non-ascii keywords is a deliberate decision, and we won't be spending effort supporting it. I'm going to close this. If you want to discuss it and try to get that decision changed, I suggest posting to https://discuss.python.org/c/ideas/6.

Another option would be to produce a patch that adds non-ascii keyword support, then we could evaluate if it's worth the support cost to add this feature. But unless the changes were very small, the answer is probably going to be "no, thank you".

**Closed as not planned by ericvsmith** 2023-06-19 15:11 UTC
Labels: type-feature, interpreter-core

**Comment by metebalci** [comment] 2023-06-19 15:57
@ericvsmith I thought my explanation was clear enough, sorry for that. It is just adding a non-ASCII keyword to `python.gram`, running `make regen-all` and `make`, and then this new keyword is not working, interpreter gives a parsing error due to the reasons I mentioned.

OK, thanks for the information and the clarification.
