### ISSUE TITLE
tkinter filedialog keeps outputing info message(CATransaction synchronize) on macOS 13 Ventura

### ISSUE THREAD

**Issue by 1155159410** [python/cpython#101895] opened 2023-02-14 08:50 UTC
# Bug report

When calling the `tkinter.filedialog` module for a file dialog, below's info message keeps printing in the console:
> 2023-02-14 17:33:27.943 python[8474:96190] +[CATransaction synchronize] called within transaction

Especially when I drag and move the dialog window, it keeps spamming the above message in the console.
The same report on this issue can also be found on Stackoverflow: [How can I stop tkinter from outputting "[CATransaction synchronize] called within transaction" on Mac?](https://stackoverflow.com/questions/74437765/how-can-i-stop-tkinter-from-outputting-catransaction-synchronize-called-withi)

Here is a code to reproduce the problem:
```
from tkinter import filedialog
print(filedialog.askdirectory())
```

This issue can be reproduced in both IDE and executable(i.e. pyinstaller) environments. And it only occurs on macOS, Windows does not have such a problem. (Probably starting from macOS 13.0)

# Your environment

- CPython versions tested on: Python 3.10
- Operating system and architecture: macOS 13.2 (ARM)

**Comment by ned-deily** [comment] 2023-02-14 18:35
Thanks for the report. For what it's worth, a quick test shows that the issue is reproducible with various versions of Python tkinter (i.e. 3.9.13, 3.11.2) linked with various versions of Tk on macOS 13.2 (i.e. Tk 8.6.8, 8.6.12, 8.6.13). And it does seem to be a new problem with macOS 13, i.e. it doesn't appear to show up when running the same python.org 3.11.2 on macOS 12.6.3. A web search shows reports of similar messages showing up with other windowing systems, like Qt, on recent macOS versions. A quick search of the Tk issue tracker didn't turn up anything obvious. So it could be an issue in either Tk itself or how Python uses Tk. Or just an incompatible change by Apple in macOS. Perhaps Marc Culler (@culler) has run into this?

**Comment by culler** [comment] 2023-02-14 19:09
I have seen this, starting with the beta release of Ventura, and I see it in the Tk widget demo.  The bad news is that I don't think there is anything that we (meaning people who do not work for Apple) can do about it.  All that Tk is doing is to call [NSOpenPanel openPanel].  That method does not return until the user interaction with the file dialog ends.  All events are handled by Apple during that interaction - Tk does not see them.  As far as I can tell these log messages are being generated by Apple code.

I suppose someone could try filing a bug report with Apple.  Good luck with that.

**Comment by ned-deily** [comment] 2023-02-14 20:07
Sigh, thanks for the info, Marc. I was afraid of that. So, to summarize, the behavior seen here appears to be a change in macOS 13 Ventura that impacts Tk, the GUI library that tkinter uses (and possibly other windowing systems). Since there doesn't seem to be anything obvious that Python could do to work around the problem, I'm going to close this issue. If someone does have any further info from Apple, feel free to comment here.

**Closed as not planned by ned-deily** 2023-02-14 20:07 UTC
Labels: type-bug, OS-mac, topic-tkinter

**Comment by culler** [comment] 2023-02-14 20:23
[This report](https://developer.apple.com/forums/thread/722889) on the Apple Developer site gives a short Objective C program which exhibits the same behavior.  The conclusion there is also that this is an Apple bug.

**Comment by terryjreedy** [comment] 2023-02-14 20:49
I'd like to know the extent of the 'damage'.  IDLE uses filedialog.Open and filedialog.SaveAs, which invoke system dialogs.  Filedialog.askdirectory (line 440) appears to be a generic alternative.  It displays a filedialog.Directory (line 359), which uses command "tk_chooseDirectory" rather than "tk_getOpenFile" or "tk_getSaveFile"

**Comment by culler** [comment] 2023-02-14 21:25
As far as I know, there is no 'damage'.  But there is some annoyance.  These messages are just being sent to a log file.  The file dialog itself works fine.  The catch is that Apple sends log messages to stderr when the process has a stderr.  This means that the messages would not interfere with a macOS app.  You could see them in the console.app (which is full of junk like that, but invisible to most users).  However, when you are running python from a Terminal window and using a tkinter filedialog you will see the messages on your screen unless you have redirected stderr.  (This is much like what happens when you run a standard Ubuntu app from your terminal.)

**Comment by ned-deily** [comment] 2023-02-14 21:34
As Marc says this appears to be just a nuisance and really only if you are running IDLE from a macOS terminal window via a shell and then do some sort of IDLE file operation. IF you launch IDLE via IDLE.app (for example, double-clicking on the IDLE icon in the /Applications/Python 3.x folder as provided by the python.org macOS installers, you don't see the messages, because of there being no display of stderr as Marc explains. It seems like there is nothing Python or IDLE should change at the moment; it's really up to Apple to change or provide guidance.

**Comment by culler** [comment] 2023-02-14 22:02
If you don't like clicking you could also run `open /Applications/Python\ 3.11/IDLE.app` in your Terminal.

**Comment by terryjreedy** [comment] 2023-02-14 23:54
Thank you both.  Now I know what to ask or say in response to a report on GH, Stackoverflow, or discuss.

**Comment by ronaldoussoren** [comment] 2023-02-19 12:55
I've filed FB11997307 with Apple about this issue based on the code in the developer forum post.

**Comment by culler** [comment] 2023-02-19 19:11
Thanks Ronald!  Please let us know if you get a response.

**Comment by culler** [comment] 2023-09-19 16:24
This problem does not seem to occur in the macOS Sonoma beta release.

@ronaldoussoren, just out of curiosity, did Apple ever respond to you about FB11997307?

**Comment by ronaldoussoren** [comment] 2023-09-22 11:22
> 
> @ronaldoussoren, just out of curiosity, did Apple ever respond to you about FB11997307?

The haven't :-(
