### ISSUE TITLE
Allow the JSON encoder to optionally support decimal.Decimal objects

### ISSUE THREAD

**Issue by chris-ashford** [python/cpython#118810] opened 2024-05-09 00:02 UTC
# Feature or enhancement

### Proposal:

JSON files allow real numbers of infinite size and precision.
By default, the json module parses real numbers to floats, which have limited precision.
Python already has a built-in solution for this in the form of decimal.Decimal objects.
However, while it is easy to use these with the decoder, Python's JSON encoder does not allow you to encode decimal.Decimal objects, and producing JSON with infinite precision reals requires a custom encoder at this time.
I propose that the json module have an optional flag, which when toggled allows the it to encode decimal.Decimal objects.

Example usage:
```python
>>> import json
>>> import decimal
>>> json.dumps(decimal.Decimal("1.2345"), support_decimal=True)
'1.2345'
>>> json.dumps({decimal.Decimal("1.2345"): [decimal.Decimal("6.7890"), decimal.Decimal("3.14159265"), "some other data", decimal.Decimal("0")]}, support_decimal=True)
'{"1.2345": [6.7890, 3.14159265, "some other data", 0]}'
>>> from math import pi
>>> json.loads(json.dumps(decimal.Decimal(pi), support_decimal=True), parse_float=decimal.Decimal)
Decimal('3.141592653589793115997963468544185161590576171875')
```

This is my first attempt at contributing to open source, so any feedback is greatly appreciated :)

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-118811

**Comment by serhiy-storchaka** [comment] 2024-05-10 07:22
It is a duplicate of #60739.

**Closed as not planned by serhiy-storchaka** 2024-05-10 07:22 UTC
Labels: type-feature

**Comment by Kris-0605** [comment] 2024-05-12 13:58
Sorry for not finding that before.
In case anyone stumbles upon this issue in the future, I've made the code from this PR into [its own module](https://github.com/Kris-0605/json_with_decimals), and [uploaded it to PyPI](https://pypi.org/project/json-with-decimals/). It can function as a drop-in replacement for `json` (`support_decimal` is true by default in this version):
```py
import json_with_decimals as json
from decimal import Decimal
# In this version, real numbers are automatically made into Decimals
json.loads(json.dumps(Decimal("1.2345")))
# Returns the same Decimal you passed in
```
