### ISSUE TITLE
glob.glob outputs the base path in recursive mode even when it does not exist

### ISSUE THREAD

**Issue by blhsing** [python/cpython#115131] opened 2024-02-07 09:15 UTC
# Bug report

### Bug description:

As reported in the StackOverflow question:
https://stackoverflow.com/questions/72366844/unexpected-result-with-recursive-glob-glob-using-pattern

`glob.glob` on a non-existing directory:
```
>>> import os, glob
>>> os.path.exists('dir')
False
>>> glob.glob('dir/*', recursive=True)
[]
>>> glob.glob('dir/**', recursive=True)
['dir/']
```
`glob.glob` on an existing file/non-directory:

```python
>>> os.path.exists('file')
True
>>> glob.glob('file/*', recursive=True)
[]
>>> glob.glob('file/**', recursive=True)
['file/']
```
The same issue is observed with `glob.iglob` as well.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux, Windows

**Comment by serhiy-storchaka** [comment] 2024-02-07 09:44
It is a duplicate of #79382.

**Closed as not planned by serhiy-storchaka** 2024-02-07 09:44 UTC
Labels: type-bug, 3.11, 3.12, 3.13
