### ISSUE TITLE
pyrepl doesn't print result if any part came from paste

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#119076] opened 2024-05-15 18:22 UTC
# Bug report

### Bug description:

Below, the *first* occurrence of `"copyright"` was pasted in. The second occurrence was pulled from history using up-arrow. Note that the former doesn't print the result.
```
~/cpython$ ./python.exe 
Python 3.14.0a0 (heads/main:7e894c2f38f, May 11 2024, 14:54:01) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "copyright"
>>> "copyright"
'copyright'
>>> 
```
Worse, even if *any* part of a line was pasted in, it seems the result isn't printed.

It's the same in 3.13b1.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by hugovk** [comment] 2024-05-15 18:23
This is a duplicate of https://github.com/python/cpython/issues/118893.

**Closed as not planned by hugovk** 2024-05-15 18:23 UTC
Labels: type-bug, topic-repl

**Comment by gvanrossum** [comment] 2024-05-15 18:33
> This is a duplicate of #118893.

Sorry about that. I searched but didn't find that issue somehow.
