### ISSUE TITLE
Totally black dialog box when running on mac

### ISSUE THREAD

**Issue by jerrikf** [python/cpython#111608] opened 2023-11-01 15:39 UTC
# Bug report

### Bug description:

In my project we work with a lot of people. some of them have a MacBook.

When using simpledialog.askstring and simpledialog.askfloat it appears to only show a fully black box as a pop-up.

It does work, meaning you can type something in the box, but you can't really see anything you are typing. This can be really inconvenient at times. Is there some way to fix this?

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by ericvsmith** [comment] 2023-11-01 16:24
Please provide a small, complete, and working code example that demonstrates the problem. Also, how did you install Python3.11? And what version of macOS are you on?

**Comment by ned-deily** [comment] 2023-11-01 16:43
These kinds of issues are usually related to what version of Tk is being used by the Python in use. Please include the output of:

`python3.11 -m test.pythoninfo
`

substituting for `python3.11` whatever is used to invoke the failing code.

Another factor can be what system appearance is in use, i.e. `light` or `dark`. Does the behavior change if you change the appearance in the macOS System Settings?

**Comment by ronaldoussoren** [comment] 2023-11-04 15:42
@jerrikf, please add the requested information otherwise we cannot reproduce the issue (fwiw, the code works just fine on my machine running macOS Sonoma with Python 3.11 installed using the python.org installer)

To summarise the information requests:
- Which version of macOS?
- How did you install Python (Python.org installer, Homebrew, ...)? If using /usr/bin/python3: which version of Xcode or the Command Line Tools package is installed?
- Output of ``python3.11 -m test.pythoninfo``

**Comment by ronaldoussoren** [comment] 2023-11-10 15:37
I'm closing this issue because there's not enough information to reproduce the issue, let alone find the underlying problem.

**Closed as not planned by ronaldoussoren** 2023-11-10 15:37 UTC
Labels: type-bug, OS-mac, topic-tkinter
