### ISSUE TITLE
Invalid  datetime.time.fromisoformat

### ISSUE THREAD

**Issue by random1st** [python/cpython#124257] opened 2024-09-19 19:09 UTC
# Bug report

### Bug description:

According to the standard ISO 8601 `Thus the value ‘24:00:00’ is chosen to represent the final
instant of the day in order to distinguish the expression of this instant from an expression of a time scale
unit.` 

```python
>>> datetime.time.fromisoformat("24:00")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: hour must be in 0..23

```
[Link to standard pdf](https://cdn.standards.iteh.ai/samples/81801/f527872a9fe34281ae3a4af8e730f3f8/ISO-8601-1-2019-Amd-1-2022.pdf)

### CPython versions tested on:

3.10, 3.12

### Operating systems tested on:

Linux, macOS

**Comment by eendebakpt** [comment] 2024-09-19 19:48
Some other discussions on supporting this: https://github.com/dotnet/runtime/issues/12197, https://github.com/astropy/astropy/issues/9837

Also note the documentation of `datetime.datetime.fromisoformat`:

> Return a [date](https://docs.python.org/3/library/datetime.html#datetime.date) corresponding to a date_string given in any valid ISO 8601 format, with the following

The part "in any valid ISO 8601" suggest that `fromisodate` should support `24:00`

**Comment by tomasr8** [comment] 2024-09-19 20:47
> The part "in any valid ISO 8601" suggest that fromisodate should support 24:00

On one hand it says `any valid ISO 8601 format` (which with the latest amendement to the spec `24:00` is). On the other hand, it also lists exceptions to the spec. Even though I think it would make sense to support `24:00`, if it's decided against it, I think we should at least document this discrepancy in the docs

**Comment by hugovk** [comment] 2024-09-19 20:55
Is this a duplicate of https://github.com/python/cpython/issues/102450 (or https://github.com/python/cpython/issues/54636)?

**Comment by eendebakpt** [comment] 2024-09-19 21:41
There is an open PR to allow `24:00`: https://github.com/python/cpython/pull/105856. I can review it (but it would be nice to know beforehand whether we actually want to allow `24:00`).

@pganssle @abalkin as code owners

**Closed as completed** 2024-09-25 21:32 UTC
Labels: type-bug, stdlib
