### ISSUE TITLE
``test_importlib`` leaks references

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#116777] opened 2024-03-14 06:19 UTC
# Bug report

### Bug description:

```python
./python.exe -m test -R 3:3 test_importlib
Using random seed: 3606634477
0:00:00 load avg: 2.94 Run 1 test sequentially
0:00:00 load avg: 2.94 [1/1] test_importlib
beginning 6 repetitions. Showing number of leaks (. for 0 or less, X for 10 or more)
123:456
XXX 511
test_importlib leaked [5, 1, 1] references, sum=7
test_importlib leaked [2, 1, 1] memory blocks, sum=4
test_importlib failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_importlib

Total duration: 18.8 sec
Total tests: run=1,274 skipped=6
Total test files: run=1/1 failed=1
Result: FAILURE
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by sobolevn** [comment] 2024-03-14 07:19
Duplicate of https://github.com/python/cpython/issues/116731

**Closed as not planned by sobolevn** 2024-03-14 07:19 UTC
Labels: type-bug, tests
