### ISSUE TITLE
Problem in Turkish Documentation (Interpreter Section)

### ISSUE THREAD

**Issue by T-Z-N** [python/cpython#123119] opened 2024-08-18 08:38 UTC
[# Documentation

The problem occurs in: (https://docs.python.org/tr/3/tutorial/interpreter.html)

The first Paragraph and Third paragraphs are in English instead of Turkish Language.

E.g

>The Python interpreter is usually installed as /usr/local/bin/python3.12 on those machines where it is available; putting /usr/local/bin in your Unix shell’s search path makes it possible to start it by typing the command:

>On Windows machines where you have installed Python from the [Microsoft Store](https://docs.python.org/tr/3/using/windows.html#windows-store), the python3.12 command will be available. If you have the [py.exe launcher](https://docs.python.org/tr/3/using/windows.html#launcher) installed, you can use the py command. See [Excursus: Setting environment variables](https://docs.python.org/tr/3/using/windows.html#setting-envvars) for other ways to launch Python.

**Comment by picnixz** [comment] 2024-08-18 08:42
Localization issues should be reported to their corresponding repositories. In your case this would be https://github.com/python/python-docs-tr.

Closing as `not a CPython issue`.

**Comment by picnixz** [comment] 2024-08-18 08:44
Ok, actually it's not just a Turkish issue. It *might* be a Sphinx issue. Re-opening.

**Comment by picnixz** [comment] 2024-08-18 09:07
I'm not sure whether the issue is with Sphinx or if the translation repositories are not using the latest Sphinx version for extracting their messages catalogs.

Example: https://docs.python.org/fr/3.14/using/mac.html#getting-and-installing-python

> A Python 3.14 folder in your Applications folder. In here you find IDLE, the development environment that is a standard part of official Python distributions; and Python Launcher, which handles double-clicking Python scripts from the Finder.

The RST:

```rst
* A |python_version_literal| folder in your :file:`Applications` folder. In here
  you find IDLE, the development environment that is a standard part of official
  Python distributions; and :program:`Python Launcher`, which handles double-clicking Python
  scripts from the Finder.
```

Now, the [simplified Chinese translation](https://github.com/python/python-docs-zh-tw/blob/485c468c462a20f598aae0ea1fa7a802c67237b4/using/mac.po#L72C1-L82C1) has:

```po
#: ../../using/mac.rst:32
msgid ""
"A |python_version_literal| folder in your :file:`Applications` folder. In "
"here you find IDLE, the development environment that is a standard part of "
"official Python distributions; and :program:`Python Launcher`, which handles "
"double-clicking Python scripts from the Finder."
msgstr ""
"會有一個 |python_version_literal| 資料夾在你的 :file:`Applications` 資料夾"
"中。在這裡你可以找到 IDLE，它是作為官方 Python 發行版標準組成的開發環境；以"
"及 :program:`Python Launcher`，它負責處理在 Finder 中雙擊 Python 腳本的操作。"
```

On the other hand, the [French translation](https://git.afpy.org/AFPy/python-docs-fr/src/commit/ceaeb373626e282ba17220752aa2c522fd046891/using/mac.po#L66-L76) (but only for the Python 3.11 branch and not 3.12) has:

```po
#: using/mac.rst:29
	msgid ""
	"A :file:`Python 3.12` folder in your :file:`Applications` folder. In here "
	"you find IDLE, the development environment that is a standard part of "
	"official Python distributions; and PythonLauncher, which handles double-"
	"clicking Python scripts from the Finder."
	msgstr ""
	"Un dossier :file:`Python 3.12` dans votre dossier :file:`Applications`. "
	"Dedans vous trouverez **IDLE**, l'environnement de développement qui fait "
"partie des distributions Python officielles ; **PythonLauncher**, qui gère "
	"le lancement de scripts Python depuis le ``Finder``."
```

In particular, the translation being extracted is different. Maybe it's because of the Sphinx version. 

@AA-Turner What do you think the issue is? is it a Sphinx (version) issue where the projects are not using the latest Sphinx for correctly extracting the text to translate or do you think it's a Sphinx issue itself?

**Comment by AA-Turner** [comment] 2024-08-18 10:21
I'm travelling today, but this might be related?: https://github.com/sphinx-doc/sphinx/issues/4293

A

**Comment by picnixz** [comment] 2024-08-18 16:01
I'll check more in detail tomorrow and see what I can do out there. I want to know why some translations are ok and why some are not... (maybe they have an additional processing step but I didn't check).

**Comment by picnixz** [comment] 2024-08-19 11:52
I digged in a bit in Sphinx and it appears that the messages should be extracted normally, namely the substitution string should be correctly set. I think I understand what happens:

- In your example, the Turkish localization has

```po
#: tutorial/interpreter.rst:13
#, fuzzy
msgid ""
"The Python interpreter is usually installed as :file:`/usr/local/bin/"
"python3.12` on those machines where it is available; putting :file:`/usr/"
"local/bin` in your Unix shell's search path makes it possible to start it by "
"typing the command:"
msgstr ""
"Python yorumlayıcısı genellikle mevcut olduğu makinelerde :file:`/usr/local/"
"bin/python3.10` 'a yüklenir; Unix kabuğunuzun arama yoluna (path) :file:`/"
"usr/local/bin` yazmak, komutu yazarak başlatmayı mümkün kılar:"
```

Now, the CPython 3.12 branch has

https://github.com/python/cpython/blob/8edfa0b0b4ae4235bb3262d952c23e7581516d4f/Doc/tutorial/interpreter.rst?plain=1#L13-L15

but the CPython **main** branch has

https://github.com/python/cpython/blob/e077b201f49a6007ddad7c1b6e3069a037b6d952/Doc/tutorial/interpreter.rst?plain=1#L13-L15

So I'm not really sure what happens. What's funny is that the 3.10 docs seem to be correct: https://docs.python.org/tr/3.10/tutorial/interpreter.html, but there is *one* thing that changes between the two .po files, namely the presence of `fuzzy`:

```po
#: tutorial/interpreter.rst:13
msgid ""
"The Python interpreter is usually installed as :file:`/usr/local/bin/"
"python3.10` on those machines where it is available; putting :file:`/usr/"
"local/bin` in your Unix shell's search path makes it possible to start it by "
"typing the command:"]
```
https://github.com/python/python-docs-tr/blob/7c7c3b0349a1238a8c72da8f0f5de7cf68527833/tutorial/interpreter.po#L28-L33

```po
#: tutorial/interpreter.rst:13
#, fuzzy
msgid ""
"The Python interpreter is usually installed as :file:`/usr/local/bin/"
"python3.12` on those machines where it is available; putting :file:`/usr/"
"local/bin` in your Unix shell's search path makes it possible to start it by "
"typing the command:"
```

https://github.com/python/python-docs-tr/blob/3a1f460265b904e8eb994522a51337afce9d5de2/tutorial/interpreter.po#L28-L38

I don't know whether `fuzzy` is added by Sphinx or not, but I'm not sure it's the case. It appears that it's added by `potodo`. In particular, I think this issue should be reported to the dedicated localization docs (it's neither a CPython issue nor a Sphinx issue as far as I can tell).

**Comment by picnixz** [comment] 2024-08-19 12:11
In conclusion, either we set `gettext_allow_fuzzy_translations=True` in this repo, or "fuzzy" should be removed on in TR localization for the 3.12 branch. By default, Sphinx skips fuzzy translations, hence the lack of translation but I'm not sure we want to use fuzzy translation in production. So, I'd suggest removing the `fuzzy` attribute in the corresponding .po files (I don't think it's the `gettext` builder that adds the `fuzzy` flag, it should be the `make fuzzy` rule of the TR repository that is responsible for that).

**Closed as not planned** 2024-08-19 12:12 UTC

**Comment by hugovk** [comment] 2024-08-19 13:23
Will you report it to https://github.com/python/python-docs-tr?

**Comment by picnixz** [comment] 2024-08-19 15:17
I think so. Though I'm not sure which direction is the best. @AA-Turner should we enable fuzzy translations on CPython or not?
