### ISSUE TITLE
DeepChainMap

### ISSUE THREAD

**Issue by uemit61** [python/cpython#113074] opened 2023-12-13 21:54 UTC
# collections

class DeepChainMap(ChainMap)...

the code of this class is not korrect.
In the Example the passed Objects are Dictionarys and not a ChainMap, if you pass
a ChainMap you will get a KeyError.

I have changed it like this...:
```python

class DeepChainMap(ChainMap):
    def __setitem__(self,key,value):
        for m in self.maps:
            if key in m:
                m[key] = value 
                return 
        self.maps[0][key]=value
          
    def __delitem__(self,key):
        
        if type(self.maps[0]) is ChainMap: # other ways like in the Example it is a Dictonary
            for m in self.maps[0].maps:
                if key in m:
                    del m[key]
                    return
        else:
            for m in self.maps:
                if key in m:
                    del m[key]
                    return 
                
        raise KeyError(key) 
```

**Comment by gaogaotiantian** [comment] 2023-12-13 23:10
You are right about the code, but I'm not sure of this is a docs issue. `ChainMap` itself does not work when you try to delete a key in deeper layer which is documented. `DeepChainMap` solves it - so if you want that feature to work, you need to use `DeepChainMap` for all the maps. That means, you probably should not put a `ChainMap` in a `DeepChainMap`. Instead, put a `DeepChainMap` in the `DeepChainMap`, and the code will work.

**Comment by terryjreedy** [comment] 2023-12-13 23:37
A [ChainMap](https://docs.python.org/3/library/collections.html#chainmap-objects) is "a single, updatable view" of "multiple maps".  Unless a ChainMap is also a map in itself (by the collections.abc definition), which I expect not, neither ChainMap nor a subclass, like DeepChainMap, should be initialized with a ChainMap.  If so, I think this should be closed.

If a ChainMap can be initialized with ChainMap, but the DeepChainMap subclass cannot be, then the revised condition should be mentioned.

**Comment by rhettinger** [comment] 2023-12-14 00:39
>  Instead, put a DeepChainMap in the DeepChainMap, and the code will work.

@gaogaotiantian is correct here.  DeepChainMap can only promise to search all the mappings in its chain.  It cannot and should not make any promises about what the constituent mappings do.  If you want the inner mappings to be DeepChainMaps as well, that is allowed. It is also allowed to use a regular ChainMap which only sets and deletes at its top level.  Likewise, it is allowed to use any `MutableMapping`, each of which can decide on their own semantics.

Marking as closed.  The recipe is behaving as intended.  The chain recipes create a view of the underlying mappings but does not alter the characteristics of those mappings.

**Closed as not planned by rhettinger** 2023-12-14 00:39 UTC
Labels: docs

**Comment by uemit61** [comment] 2023-12-14 05:48
@gaogaotiantian "That means, you probably should not put a ChainMap in a DeepChainMap. Instead, put a DeepChainMap in the DeepChainMap, and the code will work."  
 ------ Can you give me an Example please, because I get every time same KeyError

**Comment by gaogaotiantian** [comment] 2023-12-14 07:00
> @gaogaotiantian "That means, you probably should not put a ChainMap in a DeepChainMap. Instead, put a DeepChainMap in the DeepChainMap, and the code will work." ------ Can you give me an Example please, because I get every time same KeyError

```python
from collections import ChainMap

class DeepChainMap(ChainMap):
    'Variant of ChainMap that allows direct updates to inner scopes'

    def __setitem__(self, key, value):
        for mapping in self.maps:
            if key in mapping:
                mapping[key] = value
                return
        self.maps[0][key] = value

    def __delitem__(self, key):
        for mapping in self.maps:
            if key in mapping:
                del mapping[key]
                return
        raise KeyError(key)

inner = DeepChainMap({'zebra': 'black'}, {'elephant': 'blue'}, {'lion': 'yellow'})
outer = DeepChainMap({'zebra': 'white'}, inner)

print(outer)
del outer['elephant']
print(outer)
```

**Comment by uemit61** [comment] 2023-12-14 07:20
@gaogaotiantian you only passed dict's as Objects that are not ChainMaps.... the inner and the outer

class DeepChainMap(ChainMap):
    def __setitem__(self,key,value):
        for m in self.maps:
            if key in m:
                m[key] = value 
                return 
        self.maps[0][key]=value
          
    def __delitem__(self,key):
        
        if type(self.maps[0]) is ChainMap: # other ways like in the Example it is a Dictonary
            for m in self.maps[0].maps:
                if key in m:
                    del m[key]
                    return
        else:
            for m in self.maps:
                if key in m:
                    del m[key]
                    return 
      
c={'z':'a'}
b={'y':'b'}
a={'x':'c'}

lod =[c,b,a] # I have a list of dict's
d =ChainMap()
d.maps =lod # can work deep too without DeepChainMap

# or 
e=ChainMap(c,b,a)

f = DeepChainMap(d)
g= DeepChainMap(e)

# this don not work with the Code in the documentation

print(f)
del f['x']
print(f)

print(g)
del  g['x']
print(g)

**Comment by gaogaotiantian** [comment] 2023-12-14 07:53
> @gaogaotiantian you only passed dict's as Objects that are not ChainMaps.... the inner and the outer

I passed `DeepChainMap` (`inner`) to `DeepChainMap` (`outer`). Yes, `ChainMap` won't work, but `DeepChainMap` will. Change all your `ChainMap`s to `DeepChainMap` and it would work.

You can't delete a key in `ChainMap` even if it's "in" it - that's not the issue with `DeepChainMap`, that's just a fact with `ChainMap`.

This is an expected behavior (yes, `KeyError` is expected). You can't really "solve" it - you can design another data structure that behaves just like `ChainMap`, but has a different name - it will still fail with your check.

**Comment by uemit61** [comment] 2023-12-14 09:16
# collections 

ChainMap(*maps)

DeepChainMaps(ChainMap) an not DeepChainMap(*maps)
