### ISSUE TITLE
uuid1 generates identical UUIDs after a fork, even though it returns SafeUUID.safe

### ISSUE THREAD

**Issue by guillaumematheron** [python/cpython#105337] opened 2023-06-05 20:55 UTC
# Bug report

Minimal reproductible example:

```python
import os
from uuid import uuid1

print(uuid1(), flush=True)
os.fork()
u = uuid1()
print(u, u.is_safe)
```

Expected output: Either all UUIDs are different, or u.is_safe is not `safe`

Actual output:
```
774c65f2-03e1-11ee-a9b2-134f3c9f0156
774c65f3-03e1-11ee-a9b2-134f3c9f0156 SafeUUID.safe
774c65f3-03e1-11ee-a9b2-134f3c9f0156 SafeUUID.safe
```

If the initial call to uuid1() is omitted, or if using spawn instead of fork, then the bug is not triggered.

By following the code, the underlying function called seems to be [uuid_generate_time_safe](https://github.com/util-linux/util-linux/blob/master/libuuid/src/gen_uuid.c). I was not able to reproduce the bug outside of python by calling the C method directly, so I assume python sets a global state the first time `uuid1()` is called, and this state is copied when the fork occurs.

This issue was originally discovered in [clickhouse-connect](https://github.com/ClickHouse/clickhouse-connect/issues/194) then discussed in the context of [multiprocessing](https://github.com/python/cpython/issues/84559).

# Documentation issue

This may require a separate issue, but the documentation of `uuid1()` states:

```
uuid.uuid1(node=None, clock_seq=None)

Generate a UUID from a host ID, sequence number, and the current time. If node is not given, getnode() is used to obtain the hardware address. If clock_seq is given, it is used as the sequence number; otherwise a random 14-bit sequence number is chosen.
```

This seems to be false on my platform since only a counter seems to be incremented between two calls to `uuid1()`.

# Environment

- Python 3.10.6
- Ubuntu 22.04 LTS 5.15.0-58-generic x86_64

**Comment by cfrademan** [comment] 2024-04-24 19:06
I have shared this report to more accurately define what could be the cause.

https://github.com/python/cpython/issues/118241

**Comment by lyc8503** [comment] 2024-05-02 15:36
I can reproduce this behavior on the latest python version(`Python 3.13.0a6+ (heads/main:9789440de3, May  2 2024, 23:01:27) [GCC 11.4.0] on linux`).

The problem is that the `uuid` module uses `global _last_timestamp`, `_last_timestamp` which is a variable that is shared between two processes at fork time. According to the [documentation](https://docs.python.org/3/library/uuid.html), `A safe UUID is one which is generated using synchronization methods that ensure no two processes can obtain the same UUID`, so I think this behavior should be a bug in the `uuid` library implementation.

I'm drafting a PR that fixes this by using the `register_at_fork` method to clear this global variable at fork time.

**Comment by lyc8503** [comment] 2024-05-03 16:15
I debugged the code and found that my analysis above was incorrect, and in fact the return value of `safely_generated` only comes from `uuid_generate_time_safe` provided by `uuid.h` in the C module `_uuid`. Nevertheless, according to the documentation of [UUID_GENERATE(3)](https://man.archlinux.org/man/uuid_generate_time_safe.3.en), we should not get duplicate safe uuid either.

**Comment by lyc8503** [comment] 2024-05-04 12:25
I wrote the following code to test the behavior of `uuid.h`, and it seems that this problem with python comes from upstream use  `uuid/uuid.h`.

```c
#include <uuid/uuid.h>
#include <unistd.h>
#include <stdio.h>

int main()
{
    uuid_t uuid;
    printf("before fork: %d ", uuid_generate_time_safe(uuid));
    for (int i = 0; i < 16; i++)
        printf("%02x", uuid[i]);
    printf("\n");

    int ret = fork();
    printf("after fork: %d %d\n", ret, uuid_generate_time_safe(uuid));
    for (int i = 0; i < 16; i++)
        printf("%02x", uuid[i]);
    printf("\n");

    return 0;
}
```

**Comment by erlend-aasland** [comment] 2024-05-07 07:47
Unable to reproduce on Ubuntu 22.04 using Python 3.10, nor can I reproduce on macOS with Python 3.8 through 3.13.

**Comment by lyc8503** [comment] 2024-05-07 08:01
> Unable to reproduce on Ubuntu 22.04 using Python 3.10, nor can I reproduce on macOS with Python 3.8 through 3.13.

Based on the discussion in https://github.com/util-linux/util-linux/issues/3009, you may need to enable uuidd to reproduce the problem. I happen to have uuidd enabled in my test environment.

**Comment by lyc8503** [comment] 2024-05-27 00:38
This issue has already been resolved in the upstream repository, and theoretically, we just have to wait for the upstream changes to propagate. I'm not sure we need to do more on the python side though?

**Comment by erlend-aasland** [comment] 2024-05-27 13:26
Thanks. Sounds like we can close this.

**Closed as not planned by erlend-aasland** 2024-05-27 13:26 UTC
Labels: type-bug, stdlib
