### ISSUE TITLE
Isnt __init__ kinda annoying

### ISSUE THREAD

**Issue by inikishev** [python/cpython#96355] opened 2022-08-28 08:35 UTC
When I create a class and it has a bunch of properties, have to write this def` __init__(self, stuff)` and then copy all properties into stuff, and then make this giant list of self.property1=property1. Isnt that annoying and makes code giant with useless repeating? Or is there a better way to do this

**Comment by sobolevn** [comment] 2022-08-28 08:52
You can use `@dataclass`: https://docs.python.org/3/library/dataclasses.html

I am going to close this as a solved question, but if you still have anything to ask: please, consider using a helping forum https://www.python.org/community/forums. Not a bugtracker :)

**Closed as completed by sobolevn** 2022-08-28 08:52 UTC
