### ISSUE TITLE
A new Python REPL

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#111201] opened 2023-10-23 06:52 UTC
This issue will track all the different steps to bootstrap a new Python REPL with many new features. The target of this issue is that we can reach a point where new contributions can be made easily to the REPL once is written in pure Python. This issue only coveres the initial ground work to reach this status.

Tasks to be done:

- [x] Redirect the parser and the main module to a new Python module.
- [x] Fallback to the previous tokenizer-based REPL if the terminal is not a tty (and for backwards compat reasons)
- [x] Bootstrap a new REPL module (based on a trimmed version pypy's pyrepl module).
- [x] Ensure that the basic features work:
    - [x] History
    - [x] Completions
    - [x] Ctrl-r and Ctrl-s

### Linked PRs
* gh-111567
* gh-118616
* gh-118635
* gh-118638
* gh-118653
* gh-118700
* gh-118705
* gh-118712
* gh-119262
* gh-119274
* gh-119341
* gh-119348
* gh-119403
* gh-119405
* gh-119427
* gh-119432
* gh-119439
* gh-119559
* gh-119606
* gh-119833
* gh-119834
* gh-119848
* gh-119850
* gh-119924
* gh-123196
* gh-123764

**Comment by pablogsal** [comment] 2023-10-23 06:52
If you want to help with this endeavour, please mention it here so we can coordinate everyone!

**Comment by pablogsal** [comment] 2023-10-23 06:53
I have a initial version that we can start building upon, I will create a PR shortly.

**Comment by tomasr8** [comment] 2023-10-23 22:09
I learned about this from the "core.py" podcast and it sounds like a great idea! I'd be happy help with this effort :)

**Comment by vstinner** [comment] 2023-11-01 20:03
> Fallback to the previous tokenizer-based REPL if the terminal is not a tty (and for backwards compat reasons)

Do you mean not using _pyrepl? Can _pyrepl be used without readline nor tty?

**Comment by pablogsal** [comment] 2023-11-01 22:13
> Can _pyrepl be used without readline nor tty?

It needs at least a tty yes. Readline can be lifted but I am not sure yet

**Comment by novaTopFlex** [comment] 2024-04-28 16:24
I would like to see a new REPL (read, evaluate, print, loop) for the Python interpreter if the interpreter goes by a different name. Two other major Python interpreters also exist, and they already use other names ("bpython" and "ipython"). I would recommend forking the current REPL and renaming the interpreter with the new REPL to "zpython" instead. Also, I would like to see a built-in "clear()" function in the REPL as I already encounter with the "exit()" function and other REPL-specific functions.

**Comment by theLastOfCats** [comment] 2024-05-05 22:02
Big feature without PEP?

**Comment by pablogsal** [comment] 2024-05-06 08:32
Checking, will make a PR this morning

**Comment by lysnikolaou** [comment] 2024-05-06 08:36
I already have something, will push in a bit.

**Comment by kulikjak** [comment] 2024-05-06 08:52
Hi, I am seeing the following error:
```python-traceback
======================================================================
FAIL: test_completion_with_many_options (test.test_pyrepl.TestPyReplCompleter.test_completion_with_many_options)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/..../cpython-main/Lib/test/test_pyrepl.py", line 586, in test_completion_with_many_options
    self.assertEqual(output, "os.O_ASYNC")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'os.O_AS' != 'os.O_ASYNC'
- os.O_AS
+ os.O_ASYNC
?        +++
```
The reason is most likely that `os.O_ASYNC` is not necessarily available on all platforms (I am seeing this on Solaris where it's missing). I tried replacing it with `O_AP` and `O_APPEND` and then it works as expected.

**Comment by hauntsaninja** [comment] 2024-05-06 09:05
(hmm there is only one constant starting with `os.O_AS`, so not sure where the "with_many_options" comes in. should it just be testing `os.O_`?)

**Comment by pablogsal** [comment] 2024-05-06 10:33
> (hmm there is only one constant starting with `os.O_AS`, so not sure where the "with_many_options" comes in. should it just be testing `os.O_`? if anything `test_simple_completion` tests multiple options because of getenv and getenvb)

Yes, but the "multiple options" comes from the fact that the test first checks what happens if you type `os.` and you press tab twice (which displays all options) and **then** you complete from one.

**Comment by hauntsaninja** [comment] 2024-05-06 23:24
- I think history is only separate when using `help` statement, not when calling `help()`
- When you use the help statement (but not when calling `help()`), there is an extra `>>>` when you exit
- Previously it was common for users to encounter "Type help(object) for help about object" message. I wonder if we should now mention this in the main `help` help
- Paste mode is awesome. I wonder if we can have it mostly work always, like IPython

**Comment by treyhunner** [comment] 2024-05-06 23:47
> * When you use the `help` statement (but not when calling `help()`), there is an extra `>>>` when you exit

Exiting history mode (hitting `F2` and then `q`) also shows an extra `>>>`.

> * Paste mode is awesome. Would be even more awesome if we can have it mostly work all the time, like IPython

IPython relies on [prompt toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit?tab=readme-ov-file) which relies on [bracketed paste mode](https://cirw.in/blog/bracketed-paste). Issue #84001 is about that.

Bracketed paste mode and Windows support (which is a much bigger ask than bracket paste mode I assume) would likely fully replace my tendency to explain pip and venv early for the sake of nudging brand new Python programmers toward IPython.

I am *so* excited to use this new REPL while teaching after 3.13's release. 👏

**Comment by cfbolz** [comment] 2024-05-07 06:03
One behaviour I was pretty confused by right now is the "recursive" help mode. If you press F1 a bunch of times, it will start nested helps and each of them needs an exit/ctrl-d to leave. Is that intentional?

**Comment by ambv** [comment] 2024-05-07 11:39
Keep the feedback coming, we'll be fixing those things for beta 2!

**Comment by pablogsal** [comment] 2024-05-07 12:20
Bracketed paste coming right up: https://github.com/python/cpython/pull/118700

**Comment by treyhunner** [comment] 2024-05-07 21:04
Another issue, unfortunately caused by bracketed paste mode: pasting text is now about 1,000 times slower (by my estimate). Pasting [the 441,033 character text of Frankenstein](https://github.com/asweigart/codebreaker/blob/master/frankenstein.txt) takes a couple seconds in the old REPL, but pasting just the first 7,628 characters took 39 seconds in the new REPL.

Hitting Ctrl+C while pasting also doesn't stop the pasting, so accidentally pasting a very large block is an unfortunate mistake to make currently.

**Comment by hugovk** [comment] 2024-05-08 06:49
With the old REPL on macOS, `sys.prefix.replace("\\", "\\\\")` prints out a string. But the new one doesn't:

```pycon
❯ PYTHON_BASIC_REPL=1 ./python.exe
Python 3.13.0a6+ (heads/main:fcf52d7cee, May  8 2024, 09:40:54) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.prefix
'/usr/local'
>>> sys.prefix.replace("\\", "\\\\")
'/usr/local'
>>> 
```
```pycon
main on  main [$?⇡] via C v15.0.0-clang via 🐍 v3.12.3 via 💎 v3.1.3 took 36s
❯ ./python.exe
Python 3.13.0a6+ (heads/main:fcf52d7cee, May  8 2024, 09:40:54) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.prefix
'/usr/local'
>>> sys.prefix.replace("\\", "\\\\")
>>> 
```

**Comment by pablogsal** [comment] 2024-05-08 09:03
> With the old REPL on macOS, `sys.prefix.replace("\\", "\\\\")` prints out a string. But the new one doesn't:
> 
> ```
> ❯ PYTHON_BASIC_REPL=1 ./python.exe
> Python 3.13.0a6+ (heads/main:fcf52d7cee, May  8 2024, 09:40:54) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import sys
> >>> sys.prefix
> '/usr/local'
> >>> sys.prefix.replace("\\", "\\\\")
> '/usr/local'
> >>> 
> ```
> 
> ```
> main on  main [$?⇡] via C v15.0.0-clang via 🐍 v3.12.3 via 💎 v3.1.3 took 36s
> ❯ ./python.exe
> Python 3.13.0a6+ (heads/main:fcf52d7cee, May  8 2024, 09:40:54) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import sys
> >>> sys.prefix
> '/usr/local'
> >>> sys.prefix.replace("\\", "\\\\")
> >>> 
> ```

Hummm, are you using the latest main? It works for me:

```
main on  main [$?⇕] took 49s
❯ ./python.exe
Python 3.13.0a6+ (heads/main:c4f9823be27, May  8 2024, 10:02:25) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.prefix
'/usr/local'
>>> sys.prefix.replace("\\", "\\\\")
'/usr/local'
```

**Comment by pablogsal** [comment] 2024-05-08 09:04
Oh, by any chance have you pasted the code into the REPL? Paste mode uses `exec` in some occasions so it may have a bug when it does not print the result

**Comment by hugovk** [comment] 2024-05-08 09:09
Yes, I was on latest `main` and I did paste it in.

Yep, confirmed it reproduces when pasting, and works fine when typing or selecting from history.

**Comment by chgnrdv** [comment] 2024-05-08 20:17
Since `_pyrepl.__main__` is top-level now, its imports/definitions are exposed to user. Should we hide them?
```
Python 3.13.0a6+ (heads/main:c4f9823be2, May  8 2024, 21:42:56) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> dir()
['CAN_USE_PYREPL', '__annotations__', '__builtins__', '__cached__', '__doc__', '__file__',
'__loader__', '__name__', '__package__', '__spec__', 'interactive_console', 'os', 'sys']
>>>
```

**Comment by treyhunner** [comment] 2024-05-09 03:32
When editing the last line in a function in the new REPL, hitting Enter doesn't end the block if the last line has indentation on it.

![658451](https://github.com/python/cpython/assets/285352/04d90d25-ede8-43cf-9c96-f242b99e2127)

[Demo of the bug](https://asciinema.org/a/658451), [demo of what IPython does](https://asciinema.org/a/658452)

**Comment by pablogsal** [comment] 2024-05-09 09:19
> When editing the last line in a function in the new REPL, hitting Enter doesn't end the block if the last line has indentation on it.
> 
> 
> 
> ![658451](https://github.com/python/cpython/assets/285352/04d90d25-ede8-43cf-9c96-f242b99e2127)
> 
> 
> 
> [Demo of the bug](https://asciinema.org/a/658451), [demo of what IPython does](https://asciinema.org/a/658452)

We will look into it but that's by design I think. The block won't end unless you are in the last line at the start and you press enter. Otherwise it will think you are editing the block adding new lines

**Comment by sobolevn** [comment] 2024-05-09 10:23
Now `python` and `python -m asyncio` works differently.
<img width="788" alt="Снимок экрана 2024-05-09 в 11 55 50" src="https://github.com/python/cpython/assets/4660275/ce98ba85-7272-4e70-8819-82acc1c2ebed">

I want to give it a shot and fix it :)

**Comment by sobolevn** [comment] 2024-05-09 10:56
Hm, right now I don't see any simple way of mergin these two together:
https://github.com/python/cpython/blob/c68acb1384a51eb745f572687eaf677371b9e765/Lib/asyncio/__main__.py#L15-L21

and 

https://github.com/python/cpython/blob/c68acb1384a51eb745f572687eaf677371b9e765/Lib/_pyrepl/simple_interact.py#L81-L83

I think that this would require some API change. Not sure which one, though :(
I would like pass it to someone else.

**Comment by AlexWaygood** [comment] 2024-05-09 12:09
We've discovered that if you manually type out a condition that evaluates to `False` in the new REPL, `False` is printed as the result, as expected...

```pycon
>>> (3, 13, 0, "final") < (3, 13, 0, "beta")
False
```

...but that if you copy and paste this condition into the REPL, nothing is printed (implying that the condition evaluates to `None`:

```pycon
>>> (3, 13, 0, "final") < (3, 13, 0, "beta")
>>> 
```

Thanks @Eclips4 for realising that the difference in behaviour here was due to copying-and-pasting the condition rather than typing it out!

**Comment by Eclips4** [comment] 2024-05-09 12:19
Additionally to Alex's message:
There's another problem that probably has the same root cause:
```python
>>> async with a: pass
  File "<python-input-2>", line 1
    async with a: pass
SyntaxError: invalid syntax
```
This was typed manually and raised an incorrect "version" of ``SyntaxError``.

If I paste this (i.e `async with a: pass`) instead of typing it manually, the correct ``SyntaxError`` will be raised:
```python
>>> async with a: pass
  File "<python-input-3>", line 1
SyntaxError: 'async with' outside async function
>>> 
```

**Comment by pablogsal** [comment] 2024-05-09 12:23
> We've discovered that if you manually type out a condition that evaluates to `False` in the new REPL, `False` is printed as the result, as expected...
> 
> ```
> >>> (3, 13, 0, "final") < (3, 13, 0, "beta")
> False
> ```
> 
> ...but that if you copy and paste this condition into the REPL, nothing is printed (implying that the condition evaluates to `None`:
> 
> ```
> >>> (3, 13, 0, "final") < (3, 13, 0, "beta")
> >>> 
> ```
> 
> Thanks @Eclips4 for realising that the difference in behaviour here was due to copying-and-pasting the condition rather than typing it out!

This was already noted in https://github.com/python/cpython/issues/111201#issuecomment-2100108867

**Comment by pablogsal** [comment] 2024-05-09 12:25
Maybe it's time to start opening individual issues for these things. @ambv @lysnikolaou thoughts?

**Comment by AlexWaygood** [comment] 2024-05-09 12:25
> This was already noted in [#111201 (comment)](https://github.com/python/cpython/issues/111201#issuecomment-2100108867)

Ah, sorry for the noise :(

**Comment by pablogsal** [comment] 2024-05-09 12:26
> > This was already noted in [#111201 (comment)](https://github.com/python/cpython/issues/111201#issuecomment-2100108867)
> 
> Ah, sorry for the noise :(

No problem, but as we are only using one issue I am afraid that problems will be lost in the discussion ;)

**Comment by lysnikolaou** [comment] 2024-05-09 12:59
> Maybe it's time to start opening individual issues for these things. @ambv @lysnikolaou thoughts?

I agree. Opening new issues sounds better, but it'd be great if we could create a `topic-repl` label for easier grouping.

**Comment by cfbolz** [comment] 2024-05-09 13:02
> I agree. Opening new issues sounds better, but it'd be great if we could create a `topic-repl` label for easier grouping.

yes please, I'd like that too.

**Comment by hugovk** [comment] 2024-05-09 13:09
Label requested at https://github.com/python/core-workflow/issues/536

**Comment by erlend-aasland** [comment] 2024-05-10 08:56
> > Maybe it's time to start opening individual issues for these things. @ambv @lysnikolaou thoughts?
> 
> I agree. Opening new issues sounds better, but it'd be great if we could create a `topic-repl` label for easier grouping.

Consider also to use a GitHub Project.

**Comment by pablogsal** [comment] 2024-05-10 09:38
> > > Maybe it's time to start opening individual issues for these things. @ambv @lysnikolaou thoughts?
> 
> > 
> 
> > I agree. Opening new issues sounds better, but it'd be great if we could create a `topic-repl` label for easier grouping.
> 
> 
> 
> Consider also to use a GitHub Project.

What would be the advantage over a label?

**Comment by pablogsal** [comment] 2024-05-10 11:42
Label created: https://github.com/python/cpython/labels/topic-repl

**Comment by pablogsal** [comment] 2024-05-10 11:43
@treyhunner @AlexWaygood @chgnrdv @hugovk Do you mind creating individual issues and label them with the new label?

**Comment by pablogsal** [comment] 2024-05-10 11:44
I'm closing this one for now, please lets continue with individual ones

**Comment by pablogsal** [comment] 2024-05-10 11:50
Actually I am reopening until we land the tests PRs that we have pending

**Comment by erlend-aasland** [comment] 2024-05-10 11:52
> What would be the advantage over a label?

- you don't have to create an issue over at the core-workflow repo, you can just create the project
- you can add custom metadata (text fields, numeric fields, etc.) to further split the issues into groups

But a label is also fine.

**Comment by AlexWaygood** [comment] 2024-05-10 11:54
> * you don't have to create an issue over at the core-workflow repo, you can just create the project

Well, this is just our convention -- any core dev or triager can actually create a label by themselves at any time. We just choose to have a slightly more elaborate process around it :P

**Comment by AlexWaygood** [comment] 2024-05-10 11:55
> @treyhunner @AlexWaygood @chgnrdv @hugovk Do you mind creating individual issues and label them with the new label?

I created https://github.com/python/cpython/issues/118893

**Comment by treyhunner** [comment] 2024-05-10 14:50
> @treyhunner @AlexWaygood @chgnrdv @hugovk Do you mind creating individual issues and label them with the new label?

I created #118911

**Comment by lysnikolaou** [comment] 2024-09-23 20:50
I think we can close this and handle the rest of the bugs in individual issues. Feel free to re-open if you feel otherwise.

**Closed as completed by lysnikolaou** 2024-09-23 20:50 UTC
Labels: topic-repl

**Comment by 0dminnimda** [comment] 2024-10-15 19:59
Thanks to all the participants, this is amazing! I really enjoy its increased portability!

**Comment by HarbingerOfFire** [comment] 2025-05-24 03:53
I absolutely love this change! I was using 3.12 and was thinking about making the change myself when I found this. Thank you all for your dedication!
