### ISSUE TITLE
Fix types for dev_t processing in posix module: use uint64_t (unsigned) instead of int64_t (signed)

### ISSUE THREAD

**Issue by 2720531d-0155-4bdd-b7ec-4d2ad838e11d** [python/cpython#89928] opened 2021-11-09 17:13 UTC
BPO | [45767](https://bugs.python.org/issue45767)
--- | :---
Nosy | @serhiy-storchaka, @koobs, @AMDmi3
PRs | <li>python/cpython#29494</li><li>python/cpython#31794</li>
Files | <li>[posixmodule.c.patch](https://bugs.python.org/file50433/posixmodule.c.patch "Uploaded as text/plain at 2021-11-09.17:13:08 by @AMDmi3"): Patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-09.17:13:09.157>
labels = ['extension-modules', 'type-bug', '3.9', '3.10', '3.11']
title = 'Fix types for dev_t processing in posix module'
updated_at = <Date 2022-03-10.14:54:37.748>
user = 'https://github.com/AMDmi3'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-10.14:54:37.748>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'FreeBSD']
creation = <Date 2021-11-09.17:13:09.157>
creator = 'AMDmi3'
dependencies = []
files = ['50433']
hgrepos = []
issue_num = 45767
keywords = ['patch']
message_count = 5.0
messages = ['406030', '406051', '411022', '411036', '414851']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'koobs', 'AMDmi3']
pr_nums = ['29494', '31794']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45767'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-120053
* gh-120054

**Comment by vstinner** [comment] 2024-05-24 09:06
I closed the FreeBSD issue https://github.com/python/cpython/issues/113078 as a duplicate of this issue.

**Closed as completed** 2024-06-04 16:42 UTC
Labels: type-bug, extension-modules, 3.11, OS-freebsd, 3.12

**Comment by vstinner** [comment] 2024-06-04 17:10
Thanks for the fix @serhiy-storchaka!
