### ISSUE TITLE
Signaling an asyncio subprocess might raise ProcessLookupError, even if you haven't called .wait() yet

### ISSUE THREAD

**Issue by 7fe0d667-dd94-466c-94e5-7b898206163a** [python/cpython#88319] opened 2021-05-16 22:24 UTC
BPO | [44153](https://bugs.python.org/issue44153)
--- | :---
Nosy | @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-16.22:24:45.281>
labels = ['type-bug', '3.7', '3.10', 'expert-asyncio']
title = "Signaling an asyncio subprocess might raise ProcessLookupError, even if you haven't called .wait() yet"
updated_at = <Date 2021-05-16.22:28:20.661>
user = 'https://bugs.python.org/syntaxcoloring'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-16.22:28:20.661>
actor = 'syntaxcoloring'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-05-16.22:24:45.281>
creator = 'syntaxcoloring'
dependencies = []
files = []
hgrepos = []
issue_num = 44153
keywords = []
message_count = 1.0
messages = ['393764']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'syntaxcoloring']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44153'
versions = ['Python 3.7', 'Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment] 2022-10-23 17:40
Duplicate of https://github.com/python/cpython/issues/87744

**Closed as not planned by kumaraditya303** 2022-10-23 17:40 UTC
Labels: type-bug, topic-asyncio
