### ISSUE TITLE
Memory leak when asyncio.open_connection raise

### ISSUE THREAD

**Issue by 57ae018f-5644-47db-ae3a-de866162d8b4** [python/cpython#88863] opened 2021-07-21 13:46 UTC
BPO | [44697](https://bugs.python.org/issue44697)
--- | :---
Nosy | @brianquinlan, @asvetlov, @1st1, @aeros, @jdevries3133

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-21.13:46:19.757>
labels = ['expert-asyncio', '3.9', 'performance']
title = 'Memory leak when asyncio.open_connection raise'
updated_at = <Date 2021-08-05.20:05:54.604>
user = 'https://bugs.python.org/seer'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-05.20:05:54.604>
actor = 'jack__d'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-07-21.13:46:19.757>
creator = 'seer'
dependencies = []
files = []
hgrepos = []
issue_num = 44697
keywords = ['patch']
message_count = 4.0
messages = ['397945', '397982', '398219', '398234']
nosy_count = 7.0
nosy_names = ['bquinlan', 'asvetlov', 'yselivanov', 'aeros', 'jack__d', 'seer', 'whoKilledLora']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue44697'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-95739
* gh-99721
* gh-99722

**Comment by kumaraditya303** [comment] 2022-05-28 15:24
This seems more like a gc issue as adding `gc.collect()` calls after each iteration fixes the leak.

```py
import resource
import asyncio
import gc


class B:
    def __init__(self, loop):
        self.loop = loop
        self.some_big_data = bytearray(1024 * 1024)  # 1Mb for memory bloating

    async def doStuff(self):
        if not await self.connect():
            return
        print('Stuff done')

    async def connect(self) -> bool:
        try:
            _, writer = await asyncio.open_connection('127.0.0.1', 12345)
            writer.close()
            return True
        except OSError as e:
            pass
        return False


class A:
    def __init__(self, loop):
        self.loop = loop

    async def doBStuff(self):
        b = B(self.loop)
        await b.doStuff()

    async def work(self):
        print('Working...')
        for i in range(1000):
            await self.loop.create_task(self.doBStuff())
            gc.collect()
            if i % 100 == 0:
                print('Memory usage {}kb {}'.format(resource.getrusage(
                    resource.RUSAGE_SELF).ru_maxrss, i))
        print('Memory usage {}kb '.format(resource.getrusage(
            resource.RUSAGE_SELF).ru_maxrss, ))
        print('Done.')


async def amain(loop):
    a = A(loop)
    await a.work()


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(amain(loop))

```

cc @pablogsal

**Comment by pablogsal** [comment] 2022-05-28 21:13
> This seems more like a gc issue as adding gc.collect() calls after each iteration fixes the leak.

That doesn't mean it is a GC issue. That means the GC is doing its work and the problem is that there are reference cycles to clean that until the GC runs they won't go away on their own.

It may be something to help here, but the GC is working as expected from this description.

**Comment by kumaraditya303** [comment] 2022-07-11 06:47
This might be related to https://github.com/python/cpython/issues/81001

**Comment by kumaraditya303** [comment] 2022-07-11 07:02
After some investigation, the issue is that the raised exception's traceback forms ref cycles are eventually cleared by gc but causes increased memory usage. The following example does not form ref cycles and hence memory usage is constant.

```py
import resource
import asyncio


class B:
    def __init__(self, loop):
        self.loop = loop
        self.some_big_data = bytearray(1024 * 1024)  # 1Mb for memory bloating

    async def doStuff(self):
        if not await self.connect():
            return
        print('Stuff done')

    async def connect(self) -> bool:
        try:
            _, writer = await asyncio.open_connection('127.0.0.1', 12345)
            writer.close()
            return True
        except OSError as e:
            e.__traceback__ = None # Clear ref cycle manually
        return False


class A:
    def __init__(self, loop):
        self.loop = loop

    async def doBStuff(self):
        b = B(self.loop)
        await b.doStuff()

    async def work(self):
        print('Working...')
        for i in range(1000):
            await self.loop.create_task(self.doBStuff())
            if i % 100 == 0:
                print('Memory usage {}kb {}'.format(resource.getrusage(
                    resource.RUSAGE_SELF).ru_maxrss, i))
        print('Memory usage {}kb '.format(resource.getrusage(
            resource.RUSAGE_SELF).ru_maxrss, ))
        print('Done.')


async def amain(loop):
    a = A(loop)
    await a.work()


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(amain(loop))

```

**Comment by frostbyte134** [comment] 2022-08-06 10:52
It seems like there are some local variables (exception and future instances) which makes reference cycles in asyncio library.
I uploaded a [PR](https://github.com/python/cpython/pull/95739) which breaks those cycles explicitly. 

After the fix numbers from [get_traced_memory](https://docs.python.org/3/library/tracemalloc.html#tracemalloc.get_traced_memory) does not grow linearly with the loop count anymore. 

```
MacBookPro cpython % ./python.exe ~/dev/leak.py --loop_count 10  
Working...
Done.
cur = 1311527, peak = 2365922 from tracemalloc.get_traced_memory()
------------------------------
MacBookPro cpython % ./python.exe ~/dev/leak.py --loop_count 100
Working...
Done.
cur = 1317149, peak = 2371520 from tracemalloc.get_traced_memory()
------------------------------
MacBookPro cpython % ./python.exe ~/dev/leak.py --loop_count 1000
Working...
Done.
cur = 1317050, peak = 2371421 from tracemalloc.get_traced_memory()
```

Checked in Windows 10/Mac Monterey/Centos 7.9

**Closed as completed** 2022-11-22 15:06 UTC
Labels: performance, topic-asyncio, 3.11, 3.12
