### ISSUE TITLE
Cannot perform frame jump after handled exception

### ISSUE THREAD

**Issue by dkrystki** [python/cpython#92228] opened 2022-05-03 12:39 UTC
For given code:
```
def fun():
    a = 1  # <---- jump location

    try:
        b = 1 / 0
    except ZeroDivisionError as e:
        pass

    c = 3  # current location


if __name__ == "__main__":
    fun()
```
Jumping from `current location` to `jump location` yields `ValueError: can't jump from within an exception handler`

**Your environment**

- CPython versions tested on: 3.11.0a7
- Operating system and architecture:  Linux q 5.4.0-42-generic x64

Works as expected for python < 3.11

**Comment by serhiy-storchaka** [comment] 2022-05-04 05:52
@markshannon

**Comment by markshannon** [comment] 2022-05-04 15:19
@dkrystki Do you have a full reproducer?
You haven't said how you are performing the jump.

**Comment by dkrystki** [comment] 2022-05-04 15:29
For the presented example I performed jump using PyCharm.
Not sure if I know how to reproduce it using settrace (I can try) but under the hood PyCharm is simply setting f_lineno to perform a jump.

**Comment by sweeneyde** [comment] 2022-05-14 07:21
For what it's worth, this is the problematic result from the reproducer.

Bytecode:
<details>

```
3           0 RESUME                   0

4           2 LOAD_CONST               1 (1)
            4 STORE_FAST               0 (a)

6           6 NOP

7           8 LOAD_CONST               1 (1)
           10 LOAD_CONST               2 (0)
           12 BINARY_OP               11 (/)
           16 STORE_FAST               1 (b)

11          18 LOAD_CONST               3 (3)
           20 STORE_FAST               3 (c)
           22 LOAD_CONST               0 (None)
           24 RETURN_VALUE
      >>   26 PUSH_EXC_INFO

8          28 LOAD_GLOBAL              0 (ZeroDivisionError)
           40 CHECK_EXC_MATCH
           42 POP_JUMP_FORWARD_IF_FALSE    13 (to 70)
           44 STORE_FAST               2 (e)

9          46 POP_EXCEPT
           48 LOAD_CONST               0 (None)
           50 STORE_FAST               2 (e)
           52 DELETE_FAST              2 (e)

11          54 LOAD_CONST               3 (3)
           56 STORE_FAST               3 (c)
           58 LOAD_CONST               0 (None)
           60 RETURN_VALUE
           62 LOAD_CONST               0 (None)
           64 STORE_FAST               2 (e)
           66 DELETE_FAST              2 (e)
           68 RERAISE                  1

8     >>   70 RERAISE                  0
      >>   72 COPY                     3
           74 POP_EXCEPT
           76 RERAISE                  1
ExceptionTable:
8 to 16 -> 26 [0]
26 to 44 -> 72 [1] lasti
62 to 70 -> 72 [1] lasti
```
</details>

Result from `mark_stacks()`:
```
int64_t *stacks = {
     [0] =  0,  [1] =  0,  [2] =  3,  [3] =  0,  [4] =  0,
     [5] =  3,  [6] = 15,  [7] =  3,  [8] =  3,  [9] =  0,
    [10] =  3, [11] =  0, [12] =  3, [13] = -2, [14] = -2,
    [15] = -2, [16] = -2, [17] = -2, [18] = -2, [19] = -2,
    [20] = -2, [21] = -2, [22] = -2, [23] = -2, [24] = -2,
    [25] = -2, [26] = -2, [27] = -2, [28] = -2, [29] = -2,
    [30] = -2, [31] = -2, [32] = -2, [33] = -2, [34] = -2,
    [35] = -2, [36] = -2, [37] = -2, [38] = -2, [39] = -2,
};
```

Here, `-2` means `UNINITIALIZED`. This is a result of the following code in `mark_stacks`:

```c
        for (i = 0; i < len; i++) {
            int64_t next_stack = stacks[i];
            if (next_stack == UNINITIALIZED) {
                continue;
            }
            // ...
        }
```

After `RETURN_VALUE`, the rest of the stacks are `UNINITIALIZED` and remain `UNINITIALIZED` as they're skipped over. I don't know the correct solution.

BTW, bisected to adcd2205565f91c6719f4141ab4e1da6d7086126

**Comment by markshannon** [comment] 2022-06-16 09:30
I'm making this a deferred blocker.
I don't think it needs to block the next beta, but I definitely want to fix it before release

**Comment by markshannon** [comment] 2022-06-16 16:20
We need to use the exception handling table to fill in the stacks for exception handlers. 
Fiddly, but not too difficult.

**Comment by pablogsal** [comment] 2022-07-05 20:46
Bumping this to release-blocker

**Comment by iritkatriel** [comment] 2022-07-05 21:18
> We need to use the exception handling table to fill in the stacks for exception handlers.
> Fiddly, but not too difficult.

The issue here is actually not jumping from within an exception handler to code outside of the handler (I'm not sure we want to allow that). Rather, it's jumping between two points that are outside of the handler. 

If it wasn't for the inline-small-exit-blocks optimisation, there would be a jump over the except block that ``mark_stacks`` follows. But the ``c = 3`` line is duplicated, so the except case has its own copy, which is unreachable in normal control flow:

```
  1           0 RESUME                   0

  2           2 LOAD_CONST               1 (1)
              4 STORE_FAST               0 (a)

  3           6 NOP

  4           8 LOAD_CONST               1 (1)
             10 LOAD_CONST               2 (0)
             12 BINARY_OP               11 (/)
             16 STORE_FAST               1 (b)

  7          18 LOAD_CONST               3 (3)
             20 STORE_FAST               3 (c)
             22 LOAD_CONST               0 (None)
             24 RETURN_VALUE
        >>   26 PUSH_EXC_INFO

  5          28 LOAD_GLOBAL              0 (ZeroDivisionError)
             40 CHECK_EXC_MATCH
             42 POP_JUMP_FORWARD_IF_FALSE    13 (to 70)
             44 STORE_FAST               2 (e)

  6          46 POP_EXCEPT
             48 LOAD_CONST               0 (None)
             50 STORE_FAST               2 (e)
             52 DELETE_FAST              2 (e)

  7          54 LOAD_CONST               3 (3)
             56 STORE_FAST               3 (c)
             58 LOAD_CONST               0 (None)
             60 RETURN_VALUE
             62 LOAD_CONST               0 (None)
             64 STORE_FAST               2 (e)
             66 DELETE_FAST              2 (e)
             68 RERAISE                  1

  5     >>   70 RERAISE                  0
        >>   72 COPY                     3
             74 POP_EXCEPT
             76 RERAISE                  1
```


Thinking..

**Comment by iritkatriel** [comment] 2022-07-05 21:23
This confirms what I wrote above - the problem goes away if we make this change:

```
diff --git a/Python/compile.c b/Python/compile.c
index 5ae1e34520..5e56d4eb22 100644
--- a/Python/compile.c
+++ b/Python/compile.c
@@ -8978,7 +8978,7 @@ jump_thread(struct instr *inst, struct instr *target, int opcode)
 }
 
 /* Maximum size of basic block that should be copied in optimizer */
-#define MAX_COPY_SIZE 4
+#define MAX_COPY_SIZE 0
 
 /* Optimization */
 static int

```

**Comment by tiran** [comment] 2022-07-06 12:18
Since the optimization does not have a noticeable negative impact and in fact improves performance on your system, then it is reasonable to remove it and get rid of one more release blocker. In worst case we can reconsider the optimization for next beta or 3.12.

**Comment by esc** [comment] 2022-07-06 15:06
> This optimisation is very old, and I wanted to check that it is still worth having.

@iritkatriel  : Just to double check, is this the optimization introduced in:

https://bugs.python.org/issue44626

From what I can tell this came with Python 3.10, or am I mistaken?

**Comment by esc** [comment] 2022-07-07 13:34
> > > This optimisation is very old, and I wanted to check that it is still worth having.
> > 
> > 
> > @iritkatriel : Just to double check, is this the optimization introduced in:
> > https://bugs.python.org/issue44626
> > From what I can tell this came with Python 3.10, or am I mistaken?
> 
> No that PR just moved it around.

@iritkatriel : Thank you for answering my question. I have a followup questions about this. I will post the question here, but do let me know if this is not the appropriate place. I am asking, because I only discovered this bytecode optimization being triggered on Python 3.10. Maybe you can shed some light as to why I hadn't seen this before, e.g. on 3.9. Allow me to illustrate:

Using the following example:

```
def test(a):
    b = 0
    if a == 1:
        b = 3
    elif a == 2:
        b = 4
    else:
        b = 5
    return b
```

Using https://godbolt.org/ I get the following for 3.9

```
  2           0 LOAD_CONST               1 (0)
              2 STORE_FAST               1 (b)

  3           4 LOAD_FAST                0 (a)
              6 LOAD_CONST               2 (1)
              8 COMPARE_OP               2 (==)
             10 POP_JUMP_IF_FALSE       18

  4          12 LOAD_CONST               3 (3)
             14 STORE_FAST               1 (b)
             16 JUMP_FORWARD            18 (to 36)

  5     >>   18 LOAD_FAST                0 (a)
             20 LOAD_CONST               4 (2)
             22 COMPARE_OP               2 (==)
             24 POP_JUMP_IF_FALSE       32

  6          26 LOAD_CONST               5 (4)
             28 STORE_FAST               1 (b)
             30 JUMP_FORWARD             4 (to 36)

  8     >>   32 LOAD_CONST               6 (5)
             34 STORE_FAST               1 (b)

  9     >>   36 LOAD_FAST                1 (b)
             38 RETURN_VALUE
```

and then for 3.10:

```
  2           0 LOAD_CONST               1 (0)
              2 STORE_FAST               1 (b)

  3           4 LOAD_FAST                0 (a)
              6 LOAD_CONST               2 (1)
              8 COMPARE_OP               2 (==)
             10 POP_JUMP_IF_FALSE       10 (to 20)

  4          12 LOAD_CONST               3 (3)
             14 STORE_FAST               1 (b)

  9          16 LOAD_FAST                1 (b)
             18 RETURN_VALUE

  5     >>   20 LOAD_FAST                0 (a)
             22 LOAD_CONST               4 (2)
             24 COMPARE_OP               2 (==)
             26 POP_JUMP_IF_FALSE       18 (to 36)

  6          28 LOAD_CONST               5 (4)
             30 STORE_FAST               1 (b)

  9          32 LOAD_FAST                1 (b)
             34 RETURN_VALUE

  8     >>   36 LOAD_CONST               6 (5)
             38 STORE_FAST               1 (b)

  9          40 LOAD_FAST                1 (b)
             42 RETURN_VALUE
```

From what I can tell, the `return` block is only being inlined on Python 3.10 only?

**Comment by iritkatriel** [comment] 2022-07-07 13:39
Possibly it was added in 3.10. You can dig in the code if you want. The compiler has changed quite a lot between 3.9 and now.

**Comment by esc** [comment] 2022-07-07 13:48
> Possibly it was added in 3.10. You can dig in the code if you want. The compiler has changed quite a lot between 3.9 and now.

Yes, I am aware of the changes to the compiler in 3.10. Thank you for your answer, my guess is that the code has been there for some time, but due to the refactoring in 3.10 it actually started triggering.

**Comment by markshannon** [comment] 2022-07-11 10:24
Unfortunately https://github.com/python/cpython/pull/94592 doesn't fix this.
The problem applies to jumping from any block that is only reachable through an exception handler.
For example, this test fails.
```Python
    @jump_test(7, 1, [1, 6, 1, 6])
    def test_jump_over_try_except_early_return(output):
        output.append(1)
        try:
            1 / 0
            return
        except ZeroDivisionError as e:
            output.append(6)
        pass # This block is dominated by the except handler
```
Code like this is much less likely than the original example, but I think we should fix this properly by marking the stacks for exception handlers in `mark_stacks`

**Comment by markshannon** [comment] 2022-07-11 10:52
The jump from the example I give is from the `pass`, which is outside of the except handler.

**Comment by iritkatriel** [comment] 2022-07-11 11:00
I see, will check.

**Comment by iritkatriel** [comment] 2022-07-11 12:09
This fails too:

```
    @jump_test(1, 3, [1, 3])
    def test_jump_over_return(output):
        output.append(1)
        return 12
        output.append(3)

```

**Comment by markshannon** [comment] 2022-07-11 12:46
That should fail. `output.append(3)` is unreachable

**Comment by iritkatriel** [comment] 2022-07-11 13:39
You mean, the compiler can tell that it's unreachable.

If you allow the debugger to jump around you can do all kinds of impossible things (like get to the pass in your example without an exception being raised). I'm not sure what the semantics of these debugger jumps are, really.

**Comment by markshannon** [comment] 2022-07-11 13:49
> I'm not sure what the semantics of these debugger jumps are, really.

No one is.

In my mind, they are:
* Never crash the interpreter.
* If it is possible to make the jump, then do so. 
* Present a meaningful error message if the jump is impossible.

**Comment by iritkatriel** [comment] 2022-07-11 14:20
We understand the issue, and it's the subject of https://github.com/python/cpython/issues/94739 so I'll close this again (the original problem reported here was resolved).

**Closed as completed by iritkatriel** 2022-07-11 14:20 UTC
Labels: type-bug, release-blocker, 3.11, 3.12
