### ISSUE TITLE
Possible slowdown of regex searching in 3.11

### ISSUE THREAD

**Issue by markshannon** [python/cpython#91404] opened 2022-04-07 11:30 UTC
BPO | [47248](https://bugs.python.org/issue47248)
--- | :---
Nosy | @markshannon, @serhiy-storchaka, @animalize, @sweeneyde

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-04-07.11:30:33.473>
labels = ['3.11', 'performance']
title = 'Possible slowdown of regex searching in 3.11'
updated_at = <Date 2022-04-08.07:22:53.130>
user = 'https://github.com/markshannon'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.07:22:53.130>
actor = 'malin'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2022-04-07.11:30:33.473>
creator = 'Mark.Shannon'
dependencies = []
files = []
hgrepos = []
issue_num = 47248
keywords = ['3.11regression']
message_count = 4.0
messages = ['416923', '416928', '416959', '416961']
nosy_count = 4.0
nosy_names = ['Mark.Shannon', 'serhiy.storchaka', 'malin', 'Dennis Sweeney']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue47248'
versions = ['Python 3.11']
```

</p></details>

**Comment by animalize** [comment] 2022-04-11 05:05
I wrote a script to automatically benchmark some commits about re module in recent months.

Platform: Windows 10, WSL2, Ubuntu 20.04, gcc-9.4.0.
Configure: `--with-lto`. PGO is not enabled.

The results are in attached file `results.txt`. There is no 10% performance regression, my_re_benchmark is 1.10x faster.

Compare from 08eb754d8~1 (2022-03-21) to b09184bf0 (2022-04-07):
```
  regex_compile:   110 ms +- 1 ms      -> 110 ms +- 1 ms
  regex_dna:       149 ms +- 1 ms      -> 143 ms +- 1 ms
  regex_effbot:    2.23 ms +- 0.03 ms  -> 1.98 ms +- 0.01 ms
  regex_v8:        16.5 ms +- 0.1 ms   -> 16.9 ms +- 0.1 ms
  my_re_benchmark: 13.0 sec +- 0.0 sec -> 11.8 sec +- 0.0 sec
```
my_re_benchmark [1] is a benchmark made by myself, it uses 16 patterns to process 100 MiB real text data.
my_re_benchmark tested each commit 30 times, then save/compare with `pyperf`.

[1] https://github.com/animalize/re_benchmarks
[results.txt](https://github.com/python/cpython/files/8461170/results.txt)

**Comment by brandtbucher** [comment] 2022-04-13 04:01
Not sure how we're supposed to be linking issues to PRs yet, but check out #91495.

**Comment by brandtbucher** [comment] 2022-04-15 16:27
Leaving this open, since it may still be worth exploring where the prior 3.10-to-3.11 slowdown came from.

**Comment by Hello71** [comment] 2022-06-06 20:17
Chromium build effectively hangs with Python 3.11 due to re slowdown. `generate_about_tracing_contents` takes 6 seconds on Python 3.10, and I killed it after 1 hour on Python 3.11.

Reduced example:

```
re.findall(r'(?:(?:/[^\n]*)?\n)*/', '../utils/common":3}],15:[function(t,e,a){"use strict";e.exports=function(){this.input=null,this.next_in=0,this.avail_in=0,this.total_in=0,this.output=null,this.next_out=0,this.avail_out=0,this.total_out=0,this.msg="",this.state=null,this.data_type=2,this.adler=0}},{}],"/":[function(t,e,a){"use strict";var i={};(0,t("./lib/utils/common").assign)(i,t("./lib/deflate"),t("./lib/inflate"),t("./lib/zlib/constants")),e.exports=i},{"./lib/deflate":1,"./lib/inflate":2,"./lib/utils/common":3,"./lib/zlib/constants":6}]},{},[])("/")});\n')
```

takes about 0.02 seconds on Python 3.10, and 8.6 seconds on Python 3.11.

Full example: [slow.tar.gz](https://github.com/python/cpython/files/8847584/slow.tar.gz)

**Comment by sweeneyde** [comment] 2022-06-06 22:47
I git-bisected @Hello71's slowdown to commit 6e3eee5c11b539e9aab39cff783acf57838c355a
```
Author: Ma Lin <animalize@users.noreply.github.com>
Date:   Mon Apr 4 00:16:20 2022 +0800

    bpo-23689: re module, fix memory leak when a match is terminated by a signal or memory allocation failure (GH-32283)
```

**Comment by animalize** [comment] 2022-06-07 02:08
In nesting repeats, a repeat context may have multiple active existences. For example:
```python
# Multiple repeat context of (a)? will exist at the same time
re.match(r'((a)?)*', 'aaaaa')
```
This is a serious bug, it can cause wrong result.
To fix, either revert 6e3eee5c11b539e9aab39cff783acf57838c355a or use this patch:
```diff
--- a/Modules/sre_lib.h
+++ b/Modules/sre_lib.h
@@ -1037,6 +1037,10 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
             TRACE(("|%p|%p|REPEAT %d %d %d\n", ctx->pattern, ctx->ptr,
                    ctx->pattern[1], ctx->pattern[2], ctx->pattern[3]));
 
+            
+            /* repeat context may be reused in nesting repeats, save the
+               wanted repeat context to stack. */
+            DATA_PUSH(&state->repeats_array[ctx->pattern[3]]);
             /* install repeat context */
             ctx->u.rep = &state->repeats_array[ctx->pattern[3]];
 
@@ -1049,6 +1053,8 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
             state->ptr = ctx->ptr;
             DO_JUMP(JUMP_REPEAT, jump_repeat, ctx->pattern+ctx->pattern[0]);
             state->repeat = ctx->u.rep->prev;
+            /* restore repeat context from stack */
+            DATA_POP(&state->repeats_array[ctx->pattern[3]]);
 
             if (ret) {
                 RETURN_ON_ERROR(ret);
```

**Comment by animalize** [comment] 2022-06-07 03:21
The patch also has bug, and it's difficult to understand the nesting levels.
I'm reverting it.

**Comment by gpshead** [comment] 2022-06-15 21:25
https://github.com/python/cpython/pull/93882 proposed to rollback 
https://github.com/python/cpython/commit/6e3eee5c11b539e9aab39cff783acf57838c355a

there were a few other changes to `re` after that landed so the rollback required some hand edits.

**Closed as completed** 2022-06-17 08:45 UTC
Labels: performance, release-blocker, topic-regex, 3.11
