### ISSUE TITLE
Hypothesis tests on Ubuntu fails in the main

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#122686] opened 2024-08-05 09:32 UTC
# Bug report

### Bug description:

See e.g.:
https://github.com/python/cpython/actions/runs/10240047164/job/28326351304

It seems, pinning attrs deps helps.  I'll provide patch.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-122687
* gh-122729

**Comment by hugovk** [comment] 2024-08-05 09:36
Please could you also report this upstream at Hypothesis or attrs?

**Comment by skirpichev** [comment] 2024-08-05 09:51
https://github.com/python-attrs/attrs/issues/1326

**Comment by hynek** [comment] 2024-08-05 12:51
is this 3.14-only, or does Hypothesis only run on 3.14?

**Comment by skirpichev** [comment] 2024-08-06 04:57
@hugovk, is this intentionally left open?

**Comment by hynek** [comment] 2024-08-06 05:05
A pin is a stopgap, not a fix. I’m still waiting for feedback from the Hypothesis team on https://github.com/HypothesisWorks/hypothesis/issues/4067 how to actually fix it.

The problem is not solved until the pin is removed again.

**Comment by skirpichev** [comment] 2024-08-06 10:58
Then https://github.com/python/cpython/pull/122729 should address this.

**Comment by vstinner** [comment] 2024-08-06 11:47
> Then https://github.com/python/cpython/pull/122729 should address this.

Do you have more context? Is there a new Hypothesis release? Does it fix the issue?

**Comment by skirpichev** [comment] 2024-08-06 11:51
> Is there a new Hypothesis release? Does it fix the issue?

Yes.  Yes.  See https://github.com/HypothesisWorks/hypothesis/releases/tag/hypothesis-python-6.108.10

**Comment by vstinner** [comment] 2024-08-06 12:39
Fixed by updating Hypothesis to 6.108.10 ([changelog](https://hypothesis.readthedocs.io/en/latest/changes.html)) which fix compatibility with attrs 24.1.0: [commit](https://github.com/python/cpython/commit/6ff82fdb56fa0381f94c7a45aa67ab4c4aa71930).

**Closed as completed by vstinner** 2024-08-06 12:39 UTC
Labels: type-bug
