### ISSUE TITLE
pathlib.Path methods can raise NotImplementedError

### ISSUE THREAD

**Issue by 4b0c5ead-8181-475a-af87-9342ce46c4e3** [python/cpython#90889] opened 2022-02-12 19:35 UTC
BPO | [46733](https://bugs.python.org/issue46733)
--- | :---
Nosy | @terryjreedy, @pitrou, @merwok, @serhiy-storchaka, @eryksun, @barneygale, @AlexWaygood
PRs | <li>python/cpython#31338</li><li>python/cpython#31339</li><li>python/cpython#31340</li><li>python/cpython#31341</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-12.19:35:13.033>
labels = ['type-bug', 'library', '3.11']
title = 'pathlib.Path methods can raise NotImplementedError'
updated_at = <Date 2022-02-21.11:42:45.391>
user = 'https://github.com/barneygale'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-21.11:42:45.391>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-02-12.19:35:13.033>
creator = 'barneygale'
dependencies = []
files = []
hgrepos = []
issue_num = 46733
keywords = ['patch']
message_count = 11.0
messages = ['413142', '413143', '413144', '413263', '413276', '413298', '413308', '413506', '413627', '413644', '413647']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'pitrou', 'eric.araujo', 'serhiy.storchaka', 'eryksun', 'barneygale', 'AlexWaygood']
pr_nums = ['31338', '31339', '31340', '31341']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46733'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-101505

**Comment by barneygale** [comment] 2023-03-10 21:56
Closing this ticket - the issue is too minor, and the compatibility problems of a fix too major, for it to be worth addressing.

**Closed as completed by barneygale** 2023-03-10 21:56 UTC
Labels: type-bug, stdlib, 3.11, topic-pathlib
