### ISSUE TITLE
Memory leak in garbage collector, not running generation collection

### ISSUE THREAD

**Issue by voegtlel** [python/cpython#98801] opened 2022-10-28 09:46 UTC
# Bug report

We're encountering memory growth in a pytorch training application (which we cannot share). The observation: Although the number of live objects does not increase (verified by running `gc.collect()`, `print(len(gc.get_objects()))`), and also the number of torch objects and their total size remain constant, the memory increases every iteration, from 2GB initially to 60GB after a few iterations. Nevertheless, `tracemalloc` was reporting increasing number of objects. Finally, we found that `gc.get_count()` is increasing in generation 2: `gc.get_count() -> (347, 2, 247)` (third number slowly increasing). Although, after running `gc.collect()`, a lot of memory was actually freed. By adding a print hook to the gc `gc.callbacks.append(lambda phase, info: info["generation"] >= 2 and print(f"GC: {phase} {info}, {gc.get_count()}"))`, we found that gen2 is actually never being called.

## Good Example (shows the problem)
See this post: https://github.com/python/cpython/issues/98801#issuecomment-1299971988

## Original Example (better ignore this, it's not really showing the problem)
Trying to reproduce this as a minimal example proves hard, there is a lot of interaction happening with pytorch and dataloading, etc. Nevertheless, here is a small example which reproduces something similar: It might not be "minimal", but at least it's small:
```python
import gc


class Island:
    def __init__(self):
        # Important, this causes the object to create a gc island.
        self.self = self
        # To show the memory increase stronger, allocate something large
        self.memory = b'0' * 1024 * 1024


def gc_island():
    # Prevent the large object "gc island" from being collected (store it in x)
    x = Island()
    # This is key to reproducing the error. It does not clean up anything. Probably, in the full
    # training code this must somehow be triggered implicitly by some random situation?
    gc.collect(1)


# Hook for the gc, which logs when generation 2 gc is triggered
def gc_cb(phase, info):
    if info["generation"] >= 2:  # set to the gen you want to log
        print(f"GC: {phase} {info}, {gc.get_count()}")


def main():
    # initial cleanup. Just to be sure
    gc.collect()
    # Logging the gc gen2 collection
    gc.callbacks.append(gc_cb)

    # Iterate the gc_island() to create the leak.
    # Increase this to any number, memory will increase 500 * iteration until gc.collect(2) is
    # called (then it is reset to initial usage).
    for i in range(500):
        gc_island()
        if i % 100 == 0:
            print(f"{i}: GC: {gc.get_count()}")

    # Print current counter.
    print(f"GC: {gc.get_count()}")
    # Run collect(2) to actually free the memory
    print("gc.collect()")
    print(f"-> {gc.collect()}")
    # Now, memory is freed. But why was gc.collect(2) never called automatically?
    print(f"GC: {gc.get_count()}")

    print("exit")


if __name__ == "__main__":
    main()

```

Output:
```
0: GC: (0, 0, 1)
100: GC: (0, 0, 101)
200: GC: (0, 0, 201)
300: GC: (0, 0, 301)
400: GC: (0, 0, 401)
GC: (0, 0, 500)
gc.collect()
GC: start {'generation': 2, 'collected': 0, 'uncollectable': 0}, (0, 0, 500)
GC: stop {'generation': 2, 'collected': 1000, 'uncollectable': 0}, (1, 0, 0)
-> 1000
GC: (2, 0, 0)
exit
GC: start {'generation': 2, 'collected': 0, 'uncollectable': 0}, (0, 0, 0)
GC: stop {'generation': 2, 'collected': 0, 'uncollectable': 0}, (1, 0, 0)
```

# Your environment

- CPython versions tested on: 3.8.10, 3.10.7
- Operating system and architecture: Windows 8, Ubuntu on WSL, Ubuntu (bare metal) with Docker

**Comment by Jason-Y-Z** [comment] 2022-10-28 14:06
Thanks for the report. 

To make sure we are on the same page, here is the [doc for generational garbage collection](https://devguide.python.org/internals/garbage-collector/#optimization-generations).
Sorry if you already know this, but as explained in the doc, when running `gc.collect(i)`, all the generations **_below or equal to_** `i` will be merged and collected. Therefore, running `gc.collect(1)`, in the example above, will **_not_** collect generation `2`. 

As a more general comment, [`gc.set_debug()`](https://docs.python.org/3/library/gc.html#gc.set_debug) might help you with debugging relevant issues.

**Comment by voegtlel** [comment] 2022-10-28 15:33
Hi Jason-Y-Z,

thanks for your reply. Yes, of course, I'm running `gc.collect(1)` only to ensure that generation 1 has been collected, and thus everything has been merged with generation 2. Still, shouldn't generation 2 run automatically as soon as a new object is allocated and `long_lived_pending > long_lived_total / 4` (which should happen here)? We're not actually running `gc.collect()` in our code, it's only in the minimal example to trigger the leak. Probably you could somehow make the code run `gc.collect(1)`, but it's a brainer :D Before mid next weekend I'll not be able to respond here, but then I'll also try `gc.set_debug()`, maybe it reveals something.

What I'd expect is the gc calling `gc.collect(2)` by itself in regular intervals (even when I run `gc.collect(1)` manual), without the need to run it manually (as in the end of the example). This is imho a leak of the gc?

Thanks and best,
Lukas

**Comment by Jason-Y-Z** [comment] 2022-10-28 17:14
Thanks Lukas for the clarification.

To make sure I understand the problem, I modified your example slightly to the following

```python
import gc

class Island:
    def __init__(self):
        # Important, this causes the object to create a gc island.
        self.self = self
        # To show the memory increase stronger, allocate something large
        self.memory = b'0' * 1024 * 1024

def main():
    # initial cleanup. Just to be sure
    gc.collect()
    gc.set_threshold(100, 3, 3)
    print(f"Thresholds: {gc.get_threshold()}")

    for j in range(18):
        # Iterate the Island creation to create the leak.
        # Increase this to any number, memory will increase 500 * iteration until gc.collect(2) is
        # called (then it is reset to initial usage).
        for _ in range(500):
            x = Island()

        # Print current counter.
        if j % 3 == 0:
            print(f"{j}: GC: {gc.get_count()}")

if __name__ == "__main__":
    main()
```

And the output I get is the following

```
Thresholds: (100, 3, 3)
0: GC: (20, 1, 1)
3: GC: (72, 2, 4)
6: GC: (34, 4, 7)
9: GC: (92, 0, 11)
12: GC: (47, 2, 14)
15: GC: (9, 4, 17)
```

The results indeed show that generation 2 doesn't seem to get collected even when the threshold is exceeded.

**Comment by nascheme** [comment] 2022-10-31 21:38
This is a guess, but I think the reason you see the behaviour is as follows: higher generation collected is triggered off of the collection of the first generation.  Since you are manually calling `gc.collect()`, you are never letting that auto collection trigger.  You would have to take over manually running a full collection yourself as well.

**Comment by philipp-fischer** [comment] 2022-11-01 08:53
@nascheme: Note that `gc.collect()` is not called in the loop in @Jason-Y-Z's example and still the memory usage increases.

**Comment by nascheme** [comment] 2022-11-01 16:57
The second example doesn't have much to do with with the first (doesn't call `gc.collect()`) and I don't think it shows a leak.  If you run `gc.set_debug(gc.DEBUG_STATS)` you can see that collections are happening.

**Comment by voegtlel** [comment] 2022-11-02 10:02
Hi @nascheme, thanks for your response. The following condensed version clearly shows that there is a bug:

* Object with index 845 is still alive after 200k intermediate object instantiations (actually objects in regular intervals are still alive)
* gen2 collection was never triggered automatically, although the threshold is "3" for gen2
* I'd expect gc to run gen2 after the count reaches 3, but somehow it doesn't?


## Code
```python
import gc
import time

class Island:
    def __init__(self, idx: int):
        # Important, this causes the object to create a gc island.
        self.self = self
        # To show the memory increase stronger, allocate something large
        self.memory = b"0" * 1024 * 1024
        # Store index to show that first objects are not collected
        self.idx = idx

    def __del__(self):
        print("deleted", self.idx)


def main():
    gc.set_threshold(100, 3, 3)
    print(f"Thresholds: {gc.get_threshold()}")
    gc.collect()
    gc.set_debug(1)

    # Just a loop of 200k object instantiations
    for j in range(200000):
        # The effect gets stronger if you add `x = Island(j)`. But it's visible even without.
        Island(j)

    # (sleeps to ensure stderr was flushed properly)
    time.sleep(0.1)
    print(f"count: {gc.get_count()}")
    print("collect()")
    time.sleep(0.1)
    gc.collect()
    time.sleep(0.1)
    print("exit")
    time.sleep(0.1)


if __name__ == "__main__":
    main()

```

## Stdout
```
Thresholds: (100, 3, 3)
gc: collecting generation 0...
gc: objects in each generation: 99 0 6474
gc: objects in permanent generation: 0
gc: done, 98 unreachable, 0 uncollectable, 0.0000s elapsed
[...]
```
First gen1 collection:
```
gc: collecting generation 1...
gc: objects in each generation: 182 1 6474
gc: objects in permanent generation: 0
gc: done, 182 unreachable, 0 uncollectable, 0.0150s elapsed
[...]
```
Somewhere in the middle:
```
gc: collecting generation 0...
gc: objects in each generation: 182 3 6705
gc: objects in permanent generation: 0
gc: done, 180 unreachable, 0 uncollectable, 0.0000s elapsed
gc: collecting generation 1...
gc: objects in each generation: 182 4 6705
gc: objects in permanent generation: 0
gc: done, 184 unreachable, 0 uncollectable, 0.0000s elapsed
gc: collecting generation 0...
gc: objects in each generation: 182 0 6706
gc: objects in permanent generation: 0
gc: done, 180 unreachable, 0 uncollectable, 0.0000s elapsed
[...]
```
There is no "collecting generation 2" in between, now the end of the loop:
```
gc: collecting generation 0...
gc: objects in each generation: 182 3 6914
gc: objects in permanent generation: 0
gc: done, 180 unreachable, 0 uncollectable, 0.0160s elapsed
gc: collecting generation 1...
gc: objects in each generation: 182 4 6914
gc: objects in permanent generation: 0
gc: done, 184 unreachable, 0 uncollectable, 0.0150s elapsed
count: (54, 0, 442)
collect()
gc: collecting generation 2...
gc: objects in each generation: 109 0 6915
gc: objects in permanent generation: 0
deleted 845
deleted 1750
deleted 2655
deleted 3560
deleted 4465
[...]
```
Lots of objects, total of 274 "deleted" lines
```
deleted 199995
deleted 199996
deleted 199997
deleted 199998
deleted 199999
gc: done, 550 unreachable, 0 uncollectable, 0.0150s elapsed
exit
gc: collecting generation 2...
gc: objects in each generation: 0 0 6473
gc: objects in permanent generation: 0
gc: done, 0 unreachable, 0 uncollectable, 0.0160s elapsed
gc: collecting generation 0...
gc: objects in each generation: 117 0 6446
gc: objects in permanent generation: 0
gc: done, 0 unreachable, 0 uncollectable, 0.0000s elapsed
gc: collecting generation 2...
gc: objects in each generation: 3 117 6431
gc: objects in permanent generation: 0
gc: done, 1476 unreachable, 0 uncollectable, 0.0000s elapsed
gc: collecting generation 2...
gc: objects in each generation: 0 0 4292
gc: objects in permanent generation: 0
gc: done, 1122 unreachable, 0 uncollectable, 0.0000s elapsed
gc: collecting generation 2...
gc: objects in each generation: 0 0 3014
gc: objects in permanent generation: 0
gc: done, 218 unreachable, 0 uncollectable, 0.0000s elapsed
```
(Skipped some output with [...])

**Comment by nascheme** [comment] 2022-11-02 17:50
I don't see that behaviour (Python 3.11.0 on Linux):
```
[...]
deleted 199976                                                                  
deleted 199977                                                                  
count: (21, 0, 396)                                                             
collect()                                                                       
deleted 199978                                                                  
[...]                                                                 
deleted 199999                                                                  
exit  
```
What Python version and what platform are you seeing this?

**Comment by philipp-fischer** [comment] 2022-11-02 18:04
Running @voegtlel 's Example with Python 3.10.6 on Windows (64bit) I can reproduce it:

```collect()
gc: collecting generation 2...
gc: objects in each generation: 109 0 5229
gc: objects in permanent generation: 0
deleted 845
deleted 1750
deleted 2655
[...]
```

Memory use is constantly growing

**Comment by nascheme** [comment] 2022-11-02 18:10
I see the with Python 3.10.6 on Ubuntu.  I'll need to investigate more to figure out why this is happening.

**Comment by tim-one** [comment] 2022-11-02 18:26
> * I'd expect gc to run gen2 after the count reaches 3, but somehow it doesn't?

The last generation is [treated specially ](https://devguide.python.org/internals/garbage-collector/index.html#collecting-the-oldest-generation), and, as that implies, it's quite possible it will never be collected automatically. So that's a red herring.

In this particular program, it shouldn't matter anyway. The cyclic objects you're creating become trash the instant after they're created, so should never survive to make it into the oldest generation anyway (they should be reclaimed the first time a gen0 or gen1 collection occurs after they're created).

**Comment by pablogsal** [comment] 2022-11-02 18:29
I will give this a go this night or tomorrow

**Comment by philipp-fischer** [comment] 2022-11-02 19:07
> The last generation is [treated specially ](https://devguide.python.org/internals/garbage-collector/index.html#collecting-the-oldest-generation), and, as that implies, it's quite possible it will never be collected automatically. So that's a red herring.

Yes we have seen the code in https://github.com/python/cpython/blob/main/Modules/gcmodule.c#L1455 but didn't see how this would impact collection in our case.

**Comment by pablogsal** [comment] 2022-11-02 19:31
I made a simple check, added:

```
print(sum(1 for x in gc.get_objects() if type(x) == Island))
```

after the last `gc.collect()` shows that no `Island` objects remain alive at the end of the program.

**Comment by pablogsal** [comment] 2022-11-02 19:43
Also, between collections, seems that the only objects that survive the island object on the stack and the index tuple:

```
...
gc: done, 180 unreachable, 0 uncollectable, 0.0008s elapsed
gc: collecting generation 0...
gc: objects in each generation: 182 2 4625
gc: objects in permanent generation: 0
tuple
object address  : 0x1049e4550
object refcount : 1
object type     : 0x10461ac40
object type name: tuple
object repr     : (1115,)
Island
object address  : 0x104b132a0
object refcount : 4
object type     : 0x13e71b510
object type name: Island
object repr     : <__main__.Island object at 0x104b132a0>
...
```

and that immediately goes away in the next gc run.

**Comment by nascheme** [comment] 2022-11-02 19:44
For the second demo problem, it looks to me like the problem is that collection of generation 2 (i.e. full collection) is never triggered until the end of the program.  Occasionally an `Island` instance survives a non-full collection, kept alive somehow.  Probably referenced by a local variable or function parameter.  E.g. if collection happens while `Island.__init__` is running.  

I don't yet see a bug here.  The original issue is that you call `gc.collect(1)` which results in a full collection never getting triggered.

**Comment by pablogsal** [comment] 2022-11-02 19:45
> Occasionally an `Island` instance survives a non-full collection, kept alive somehow.

That's the reference on the ceval stack, is the one that I see surviving the collection on every generation.

**Comment by Jason-Y-Z** [comment] 2022-11-02 19:46
Thanks Pablo and @nascheme , (sorry if I misunderstood you but) as Lukas @voegtlel mentioned - 

> Nevertheless, gen2 seems to be triggered in your example when the gen2 counter reaches ~400. Maybe it's not a real leak to infinity. Nevertheless, memory should be freed much earlier? In our own code, we see it grow to >500, but also thresholds are at defaults (=10 in gen2), thus it might be that at some point memory would actually be freed again, but we never reach it because we run oom before?

I think the main concern here was the intermediate gen2 objects alive before the final `gc.collect()` gets run.

**Comment by pablogsal** [comment] 2022-11-02 19:47
I can always account for all objects as well:

```
./python.exe repro.py |& grep '^deleted' | wc -l
  200000
```

**Comment by pablogsal** [comment] 2022-11-02 19:50
> or the second demo problem, it looks to me like the problem is that collection of generation 2 (i.e. full collection) is never triggered until the end of the program.

I am seeing full collections before the end of the program:


```
import gc
import time

class Island:
    def __init__(self, idx: int):
        self.self = self
        self.idx = idx

def main():
    gc.set_threshold(100, 3, 3)
    print(f"Thresholds: {gc.get_threshold()}")
    gc.collect()
    gc.set_debug(1)

    # Just a loop of 200k object instantiations
    print("======")
    for j in range(200000):
        # The effect gets stronger if you add `x = Island(j)`. But it's visible even without.
        Island(j)
    print("======")

if __name__ == "__main__":
    main()

```

I get this:

```
./python.exe repro.py |& grep 'collecting generation' | sort | uniq -c
1768 gc: collecting generation 0...
 442 gc: collecting generation 1...
   4 gc: collecting generation 2...
```

**Comment by pablogsal** [comment] 2022-11-02 19:52
Ah, but those happen on teardown.

**Comment by pablogsal** [comment] 2022-11-02 19:58
The reason is that every time the last generation is considered the counts are:

* long_lived_pending 440 
* long_lived_total 4620 

So the condition `ling_lived_pending >= long_lived_total / 4` is never true.

**Comment by pablogsal** [comment] 2022-11-02 20:02
Notice that the threshold of the last generation is just a first-measure pass, if you make it too small you still need to manage to get the `ling_lived_pending >= long_lived_total / 4` to be true.

**Comment by nascheme** [comment] 2022-11-02 20:03
The GC collection threshold mechanism is based on the assumption that used memory is proportional to the number of Python objects allocated.  CPython doesn't track bytes allocated, for example.  I suspect that assumption is not a good one for your pytorch application.  Probably large chunks of memory are consumed by things other than Python objects.

Adding explicit calls to `gc.collect()` (full collection) might fix it.  I'd suggest a better fix is to not create the reference cycles in the first place (maybe hard to do) or to manually tear them down, maybe with a context handler or something similar.  If you are going to manually call `gc.collect()` or lower the thresholds, it would be a good idea to look into `gc.freeze()`.  That could make full collection a lot cheaper.

If you want to avoid the reference cycles, using `gc.DEBUG_LEAK` and `gc.get_referrers()` could be helpful.  If the object reference graph is complex, it can be really hard to debug though.  Perhaps you have only a few things that are consuming most of the memory and then you can track down what is keeping those alive.

**Comment by pablogsal** [comment] 2022-11-02 20:11
Indeed, to complete @nascheme's words, here is the rough summary of what's going on with this reproducer:

* Cycle objects are created at a rate of 1 at a time.
* When the first gen threshold is reached, mostly all survive except for 1 if the ceval stack still has a reference to it.
* When enough of these ceval survivors make the second gen reach the threshold, it collects it deleting everything there. As in the 2nd gen there are no ceval-owned objects because those are always on first gen, the second gen never promotes anything so the last gen never gets bigger so it never triggers a full collection.

**Comment by pablogsal** [comment] 2022-11-02 20:15
@tim-one @nascheme I think there is something interesting here, correct me if I am missing something.

Imagine a process that basically promotes a single object every time from the second to the last generation. In this case the number of objects in the last generation will increase by definition while `ling_lived_pending` is always `. This means that the last generation will never get collected but memory will increase forever.

**Comment by pablogsal** [comment] 2022-11-02 20:18
Indeed, consider this:

```
import gc
import time
import sys

class Island:
    def __init__(self, idx: int):
        self.self = self
        self.idx = idx

def main():
    gc.collect()
    gc.set_debug(1)
    for j in range(200000):
        x = Island(j)
        gc.collect(1)
        del x

if __name__ == "__main__":
    main()
```

This prints:


```
...

gc: objects in each generation: 2 0 13325
gc: objects in each generation: 2 0 13327
gc: objects in each generation: 2 0 13329
gc: objects in each generation: 2 0 13331
gc: objects in each generation: 2 0 13333
gc: objects in each generation: 2 0 13335
gc: objects in each generation: 2 0 13337
gc: objects in each generation: 2 0 13339
gc: objects in each generation: 2 0 13341
....

```

**Comment by philipp-fischer** [comment] 2022-11-02 20:18
> Adding explicit calls to `gc.collect()` (full collection) might fix it. I'd suggest a better fix is to not create the reference cycles in the first place (maybe hard to do) or to manually tear them down, maybe with a context handler or something similar. If you are going to manually call `gc.collect()` or lower the thresholds, it would be a good idea to look into `gc.freeze()`. That could make full collection a lot cheaper.
> 
> If you want to avoid the reference cycles, using `gc.DEBUG_LEAK` and `gc.get_referrers()` could be helpful. If the object reference graph is complex, it can be really hard to debug though. Perhaps you have only a few things that are consuming most of the memory and then you can track down what is keeping those alive.

We are not looking for a workaround or fix for our program (we already have `gc.collect` in place for that) but we are looking to fix cpython itself. Our application is by no means special and the cyclic reference is indeed a useful one and it's needed.
So memory should not explode if cpython works as expdcted

**Comment by pablogsal** [comment] 2022-11-02 20:19
> We are not looking for a workaround or fix for our program (we already have `gc.collect` in place for that) but we are looking to fix cpython itself. Our application is by no means special and the cyclic reference is indeed a useful one and it's needed.
> So memory should not explode if cpython works as expected

Don't worry, if this is something worth fixing in CPython we will get it fixed 👍

**Comment by philipp-fischer** [comment] 2022-11-02 20:29
Just wanted to add that our original full pytorch code which shows the indefinite memory growth does not mess with the GC in any way (no `gc.collect` or `gc.set_threshold` or anything from `import gc`)

**Comment by pablogsal** [comment] 2022-11-02 20:29
Ok, I am quite sure this is the problem. I think this is indeed a "bug" (depending on your definition of "bug"). I assume this is more common if your thresholds are very small or you create objects very slowly that mostly are cycles. Here is a plot of how the following code grows the last generation:


```
import gc
import time
import sys

class Island:
    def __init__(self, idx: int):
        self.self = self
        self.idx = idx

def main():
    gc.collect()
    while True:
        x = Island(None)
if __name__ == "__main__":
    main()
```

![Figure_1](https://user-images.githubusercontent.com/11718525/199595617-5fc1bddd-0986-464b-bb6f-8a9115e38b6e.png)

But this is how the following program grows:

```
import gc
import time
import sys

class Island:
    def __init__(self, idx: int):
        self.self = self
        self.idx = idx

def main():
    gc.collect()
    while True:
        x = Island(None)
        gc.collect(1)

if __name__ == "__main__":
    main()
```
![Figure_1](https://user-images.githubusercontent.com/11718525/199596113-4327b67d-20ca-42e9-bfac-f6d62f59f11c.png)

Is unclear to me if there is a way to get this behaviour with some weird allocation patterns without using `gc.collect(1)` but I think is possible to get promotions to the last gen one at a time through some similar process.

**Comment by pablogsal** [comment] 2022-11-02 20:31
> Just wanted to add that our original full pytorch code which shows the indefinite memory growth does not mess with the GC in any way (no `gc.collect` or `gc.set_threshold` or anything from `import gc`).

Yeah, see this part of my latest comment:

> Is unclear to me if there is a way to get this behaviour with some weird allocation patterns without using gc.collect(1) but I think is possible to get promotions to the last gen one at a time through some similar process.

I think a variation of this reproducer can be made without explicitly calling `gc.collect()` but it will require some more involved patterns.

**Comment by philipp-fischer** [comment] 2022-11-02 20:33
Did you try the example from https://github.com/python/cpython/issues/98801#issuecomment-1299971988 ?
This one does not have `gc.collect()` in the loop and still keeps growing.

**Comment by pablogsal** [comment] 2022-11-02 20:35
> Did you try the example from [#98801 (comment)](https://github.com/python/cpython/issues/98801#issuecomment-1299971988) ?
> This one does not have `gc.collect()` in the loop and still keeps growing.

Yeah, I did and is not enough. This is the grow pattern of that example:
![Figure_1](https://user-images.githubusercontent.com/11718525/199597210-0b76d46f-a1aa-48cb-af4b-148a960bd113.png)

**Comment by pablogsal** [comment] 2022-11-02 20:35
These plots show the size of the last generation

**Comment by pablogsal** [comment] 2022-11-02 20:37
@tim-one @nascheme I think we should have another limit here: the maximum numbers in the last gen that if surpassed, will trigger a collection. This number is like the threshold of the last gen except is dynamic: when a collection of the last gen finishes, is updated to `new_number = max(HARDCODED_MAYBE_TUNABLE_BIG_NUMBER, last_gen_survivors)`

**Comment by philipp-fischer** [comment] 2022-11-02 20:41
How do pick the `HARDCODED_MAYBE_TUNABLE_BIG_NUMBER`?

**Comment by pablogsal** [comment] 2022-11-02 20:43
Default will be some number obtained by the use of very complicated arcane rituals but the important part is that it will be tunable, so if you don't like the default, you can chose your own.

**Comment by philipp-fischer** [comment] 2022-11-02 20:46
> by the use of very complicated arcane rituals

:D

**Comment by philipp-fischer** [comment] 2022-11-02 20:46
> Yeah, I did and is not enough. This is the grow pattern of that example

Interestingly, for me the example works and gen2 objects increase steadily

**Comment by pablogsal** [comment] 2022-11-02 20:47
> Interestingly, for me the example works and gen2 objects increase steadily

What Python are you using? I am using 3.10.8

**Comment by philipp-fischer** [comment] 2022-11-02 20:49
Earlier I had run this with 3.10.6, now I'm on a different machine and with Python 3.9.0

**Comment by pablogsal** [comment] 2022-11-02 20:49
> Earlier I had run this with 3.10.6, now I'm on a different machine and with Python 3.9.0

Ah, I noticed I commented out the big string because that's not doing anything in the cycle. Can you check what happens if you comment out this line:

```
        self.memory = b'0' * 1024 * 1024
```

**Comment by philipp-fischer** [comment] 2022-11-02 20:51
Runs much quicker and still shows object count growth

**Comment by pablogsal** [comment] 2022-11-02 20:53
I'm trying 3.10.6 (on macOS) and I cannot reproduce it. It doesn't grow as you say. I suppose something else is at play here in your case because I am compiling these versions from the source every time so they are as vanilla as it gets. I cannot what difference different OSes can make here.

**Comment by pablogsal** [comment] 2022-11-02 20:55
Are you using vanilla CPython or this is something you are getting from vendors (i.e. conda provided Python or similar).

**Comment by philipp-fischer** [comment] 2022-11-02 20:57
We really have tried many different version and OSes. This is nothing special.
Right now it's this one: `3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]`

**Comment by pablogsal** [comment] 2022-11-02 20:58
Then I am afraid you are going to try to explain to me why if I execute that same code I don't get what you say :S

**Comment by pablogsal** [comment] 2022-11-02 21:03
> The original report seemed to be about "memory" use,

Yeah, but that sentence was about the discussion regarding the fact that this reproducer:

https://github.com/python/cpython/issues/98801#issuecomment-1299971988

for me doesn't grow the last generation over time but for @philipp-fischer apparently does.

**Comment by philipp-fischer** [comment] 2022-11-02 21:05
Ok I ran the exact code from the above example with `3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]`
and see output like
```
gc: objects in each generation: 182 4 5097
gc: objects in each generation: 182 0 5098

[...]
gc: objects in each generation: 182 4 5175
gc: objects in each generation: 182 1 5176
```

**Comment by pablogsal** [comment] 2022-11-02 21:08
> and see output like

Yeah, but doesn't it work arbitrarily or not? I can see that output but never grows above ~6k

**Comment by philipp-fischer** [comment] 2022-11-02 21:09
> > I cannot what difference different OSes can make here.
> 
> The original report seemed to be about "memory" use, but didn't say precisely how that was measured. There's no guarantee that CPython _can_ return dynamic memory to C (at the CPython level this is at "arena" granularity, and a single live object in an arena keeps the entire arena alive),, and even when we do return memory to C, there's no guarantee that the platform C will in turn return it to "the system" in a way that shows up in whatever system tool(s) are used to measure.

We understand that. We noticed the issue by growing memory (up too hundreds of GB and operating killing the process due to out of memory).
But the issue in cpython should be measured in object count not gigabytes.

**Comment by pablogsal** [comment] 2022-11-02 21:09
@philipp-fischer Can you try to run with `python -I`?

**Comment by philipp-fischer** [comment] 2022-11-02 21:12
Still the same in isolated mode

**Comment by pablogsal** [comment] 2022-11-02 21:15
Yep. I have tried using Arch Linux current python (3.10.8) with the same behaviour.

 I suppose the only thing left is for you to give me a docker container that reproduces this.

**Comment by pablogsal** [comment] 2022-11-02 21:17
Also, please check this comment:

https://github.com/python/cpython/issues/98801#issuecomment-1301263476

To ensure that you are not seeing just a bigger bound, please make the loop much bigger:

```
for j in range(20000000000):
```

and check that indeed it keeps growing.

**Comment by nascheme** [comment] 2022-11-02 21:25
The `gcstate->long_lived_pending` count does not get reset until a full collection happens.  So, I don't see how adding objects slowly to the final generation would prevent a full collection from happening indefinitely.  The comment in the source code is:
```
Avoid quadratic performance degradation in number                
of tracked objects (see also issue #4074):                       
                                                                 
To limit the cost of garbage collection, there are two strategies;
  - make each collection faster, e.g. by scanning fewer objects  
  - do less collections                                          
This heuristic is about the latter strategy.                     
                                                                 
In addition to the various configurable thresholds, we only trigger a
full collection if the ratio                                     
                                                                 
 long_lived_pending / long_lived_total                           
                                                                 
is above a given value (hardwired to 25%).                       
                                                                 
The reason is that, while "non-full" collections (i.e., collections of
the young and middle generations) will always examine roughly the same
number of objects -- determined by the aforementioned thresholds --,
the cost of a full collection is proportional to the total number of
long-lived objects, which is virtually unbounded.                
                                                                 
Indeed, it has been remarked that doing a full collection every  
<constant number> of object creations entails a dramatic performance
degradation in workloads which consist in creating and storing lots of
long-lived objects (e.g. building a large list of GC-tracked objects would
show quadratic performance, instead of linear as expected: see issue #4074).
                                                                 
Using the above ratio, instead, yields amortized linear performance in
the total number of objects (the effect of which can be summarized
thusly: "each full garbage collection is more and more costly as the
number of objects grows, but we do fewer and fewer of them").    
                                                                 
This heuristic was suggested by Martin von Löwis on python-dev in
June 2008. His original analysis and proposal can be found at:   
http://mail.python.org/pipermail/python-dev/2008-June/080579.html
```

My reservation about a PR to change this would be a fear of re-introducing "dramatic performance
degradation in workloads which consist in creating and storing lots of long-lived objects".

**Comment by pablogsal** [comment] 2022-11-02 21:27
> The `gcstate->long_lived_pending` count does not get reset until a full collection happens. So, I don't see how adding objects slowly to the final generation would prevent a full collection from happening indefinitely.

Run this:

```
import gc
import time
import sys

class Island:
    def __init__(self, idx: int):
        self.self = self
        self.idx = idx

def main():
    gc.collect()
    gc.set_debug(1)
    while True:
        x = Island(None)
        gc.collect(1)

if __name__ == "__main__":
    main()
```

**Comment by nascheme** [comment] 2022-11-02 21:36
I believe adding `gc.collect(1)` is what causes that behaviour.  The young generations stay small and a full collection never gets automatically triggered.  For the pytorch program in the original report, they say they don't call gc.collect() or tweak anything using the gc module.

**Comment by pablogsal** [comment] 2022-11-02 21:39
My hypothesis is that it may be possible to get similar behavior without `gc.collect()`, which the OPs claim is what they see with their reprucer, but so far I cannot confirm it on my side.

**Comment by pablogsal** [comment] 2022-11-02 21:51
I'm removing the "bug" label until we can confirm a reproducer.

**Comment by voegtlel** [comment] 2022-11-03 10:20
Hi @pablogsal,

thanks for investigating! I agree with your analysis. I can reproduce with ~750.000 iterations in the loop, that gen2 collection is triggered. Exactly at 8092 objects in gen2 (= 6474 *(initial number of objects in gen2 after first gc.collect())* * 1.25 which is the threshold of gen2 collection -> works as intended).

So, this mechannm hj ,m ism works, but doesn't seem optimal to me, as we obviously actually run out of memory in terms of gigabytes, because our GC islands are quite huge (they are actually deeply nested NamedTuples) and this seems not to be captured? I fear our only solution options are:
* Modify gc behavior, i.e. when gen2 collection runs (this seems pretty complicated, because you cannot run `gc.collect` from `gc.callbacks`)
* Calling `gc.collect()` regularly manually
* Dispose cyclic objects by clearing recursive variables
* Using weakrefs for cyclic objects

All of these options are workarounds, especially because I believe we're not doing something rare? Maybe it is because lots of nested `NamedTuple`s and `list`s instead of actual python objects are being used? If desired, I can try to repro this behavior (without the simple bytes object, but nested objects). I see why you don't want to change behavior of the gc, because it may have wide implications on other application's performance.

**Comment by pablogsal** [comment] 2022-11-03 11:42
Hi @voegtlel and thanks for reporting back.

> thanks for investigating! I agree with your analysis. I can reproduce with ~750.000 iterations in the loop, that gen2 collection is triggered. Exactly at 8092 objects in gen2 (= 6474 (initial number of objects in gen2 after first gc.collect()) * 1.25 which is the threshold of gen2 collection -> works as intended).

Ok, very good to know that this was indeed the case and I was not missing anything here.

> So, this mechanism works, but doesn't seem optimal to me, as we obviously actually run out of memory in terms of gigabytes, because our GC islands are quite huge (they are actually deeply nested NamedTuples) and this seems not to be captured

Well, this has been mentioned several times in this thread so it should not come as news. **The gc deals at the object level and knows nothing about memory**. This has been explained by @nascheme here:

https://github.com/python/cpython/issues/98801#issuecomment-1301165934

and by Tim here:

https://github.com/python/cpython/issues/98801#issuecomment-1301245088

I was under the assumption that this was already a clear fact based on what your colleague acknowledged here:

https://github.com/python/cpython/issues/98801#issuecomment-1301263653

> We understand that. We noticed the issue by growing memory (up to hundreds of GB and operating system killing the process due to out of memory).
But the issue in cpython should be measured in object count not gigabytes.

But it seems that you are talking about memory again because the cycles you create a point to a lot of memory. 

From the point of view of the interpreter, everything is working as expected and this is not pointing to a bug. Unfortunately, there isn't much we can do on our side to improve the automatic management of your use case because the GC is oblivious to the memory content of an object. Notice that is not even as simple as calling `sys.getsizeof` because objects can have arbitrary trees of objects held in strong references and some memory is not even visible to Python.

> I believe we're not doing something rare?

Well, I would not say is rare, but certainly is not common. Having a lot of cycles where every cycle is pointing to a lot of memory is a very uncommon situation. So uncommon that this is the first time I remember someone coming to our bug tracker with this concern in 30 years. 


> So, this mechanism works, but doesn't seem optimal to me

I understand that you feel is not optimal because you are running out of memory, but is optimal given the constraints the GC needs to work on (number of objects and cycles). Discussing this area in this issue is not going to be productive for anyone so I won't elaborate more about this aspect.

> as we obviously actually run out of memory in terms of gigabytes, because our GC islands are quite huge (they are actually deeply nested NamedTuples) and this seems not to be captured? I fear our only solution options are:

The most obvious solution to me is to strategically call `gc.collect()` or (better) use `weakrefs` to break the cycles or self-cycles so they get collected naturally by reference counting. Appart from that check @nascheme's advice here:

https://github.com/python/cpython/issues/98801#issuecomment-1301165934

----------

Thanks again for reaching out to us! I am closing this issue because is not a bug in the interpreter. If you discover new information, please feel free to reopen it, but **you must** attach a reproducer that can be run on any system (so we don't do the debugging dance again just to discover that the memory was not growing arbitrarily).

**Closed as not planned by pablogsal** 2022-11-03 11:42 UTC
