### ISSUE TITLE
New tier 2 counters break some C extensions due to order of field mismatch

### ISSUE THREAD

**Issue by mdboom** [python/cpython#117549] opened 2024-04-04 17:51 UTC
# Bug report

### Bug description:

@tacaswell reported [here](https://github.com/python/cpython/pull/117144#issuecomment-2037824706):

#177144 appears to have broken building scipy

```
FAILED: scipy/special/_specfun.cpython-313-x86_64-linux-gnu.so.p/meson-generated__specfun.cpp.o
ccache c++ -Iscipy/special/_specfun.cpython-313-x86_64-linux-gnu.so.p -Iscipy/special -I../scipy/special -I../../../../home/tcaswell/.virtualenvs/py313/lib/python3.13/site-packages/numpy/_core/include -I/home/tcaswell/.pybuild/py313/include/python3.13 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O3 -fpermissive -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -MD -MQ scipy/special/_specfun.cpython-313-x86_64-linux-gnu.so.p/meson-generated__specfun.cpp.o -MF scipy/special/_specfun.cpython-313-x86_64-linux-gnu.so.p/meson-generated__specfun.cpp.o.d -o scipy/special/_specfun.cpython-313-x86_64-linux-gnu.so.p/meson-generated__specfun.cpp.o -c scipy/special/_specfun.cpython-313-x86_64-linux-gnu.so.p/_specfun.cpp
In file included from /home/tcaswell/.pybuild/py313/include/python3.13/internal/pycore_code.h:461,
                 from /home/tcaswell/.pybuild/py313/include/python3.13/internal/pycore_frame.h:13,
                 from scipy/special/_specfun.cpython-313-x86_64-linux-gnu.so.p/_specfun.cpp:14948:
/home/tcaswell/.pybuild/py313/include/python3.13/internal/pycore_backoff.h: In function ‘_Py_BackoffCounter make_backoff_counter(uint16_t, uint16_t)’:
/home/tcaswell/.pybuild/py313/include/python3.13/internal/pycore_backoff.h:47:67: error: designator order for field ‘_Py_BackoffCounter::<unnamed union>::<unnamed struct>::backoff’ does not match declaration order in ‘_Py_BackoffCounter::<unnamed union>::<unnamed struct>’
   47 |     return (_Py_BackoffCounter){.value = value, .backoff = backoff};
      |   
```    
conformed scipy builds with https://github.com/python/cpython/commit/63bbe77d9bb2be4db83ed09b96dd22f2a44ef55b

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-117551
* gh-118580

**Comment by gvanrossum** [comment] 2024-04-04 18:32
Oh, I think I see what it is. I swapped the order in which the fields `value` and `backoff` are declared, and they have a compiler (flag?) that insists that the initializer lists the fields in the same order. @mdboom are you planning to make a PR to fix this? I can do it too (it's raining here :-).

**Comment by scoder** [comment] 2024-05-04 19:18
Apparently, designated initializers are a C++20 feature, i.e. they require a really recent C++ compiler with appropriate configuration. I see this in MSVC with Py3.13a6, so I don't think it's fixed:
```
C:\...\Python\3.13.0-alpha.6\x64\include\internal\pycore_backoff.h(47): error C7555: use of designated initializers requires at least '/std:c++20'
C:\...\Python\3.13.0-alpha.6\x64\include\internal\pycore_backoff.h(47): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
```

**Comment by scoder** [comment] 2024-05-04 19:29
The reason why this appears on user side is probably that Cython needs to include `pycore_frame.h` in Py3.11+ because some parts of frames that it needs for its coroutine implementation were moved from `frameobject.h` into internal header files at the time.

The discussion that lead to this change is here:
https://github.com/python/cpython/issues/90992

**Comment by gvanrossum** [comment] 2024-05-04 19:36
So if I changed pycore_backoff.h to use something like this, the problem will be solved?
```diff
diff --git a/Include/internal/pycore_backoff.h b/Include/internal/pycore_backoff.h
index decf92bc419..50e88487a52 100644
--- a/Include/internal/pycore_backoff.h
+++ b/Include/internal/pycore_backoff.h
@@ -44,7 +44,10 @@ make_backoff_counter(uint16_t value, uint16_t backoff)
 {
     assert(backoff <= 15);
     assert(value <= 0xFFF);
-    return (_Py_BackoffCounter){.backoff = backoff, .value = value};
+    _Py_BackoffCounter counter;
+    counter.value = value;
+    counter.backoff = backoff;
+    return counter;
 }
 
 static inline _Py_BackoffCounter
```
(I know there's another place this is used in that header, I'll fix that too. I'll whip up a PR.

**Comment by scoder** [comment] 2024-05-04 19:47
> So if I changed pycore_backoff.h to use something like this, the problem will be solved?

Probably, yes. Looks good to me. I'm not sure how to reproduce the issue locally, though, because GCC seems to be fairly relaxed about non-standard features whereas MSVC has the tendency to simply not support them, and I don't have MSVC on my side.

**Comment by gvanrossum** [comment] 2024-05-04 19:54
Okay, I've asked you to review gh-118580 anyways, since we're so close to the beta1 release date. Hopefully it'll go in over the weekend and somebody else reading this can test with a nightly build or something. Otherwise we can of course revise this after beta1.

**Comment by gvanrossum** [comment] 2024-05-05 21:01
The fix has been merged, let's keep this issue open for a bit to wait for confirmation that this fixes things.

**Comment by gvanrossum** [comment] 2024-05-06 23:57
Closing now. If you find a problem with this in beta 1, leave a comment here and I'll reopen.

**Closed as completed by gvanrossum** 2024-05-06 23:57 UTC
Labels: type-bug
