### ISSUE TITLE
Can not communicate with subprocess during interpreter shutdown on windows

### ISSUE THREAD

**Issue by tacaswell** [python/cpython#115219] opened 2024-02-09 14:59 UTC
# Bug report

### Bug description:

In #104826 (backported to 3.12 in #105277) to fix #104690 disallowed creating new threads during interpreter finalization.   This poses a problem on windows because the `Popen._communicate` uses a thread (see https://github.com/matplotlib/matplotlib/issues/27437#issuecomment-1840870442 for discussion).

In Matplotlib we are holding onto a latex process and triggering this via a weakref finalize, but a minimal reproducer is:

```python
from subprocess import Popen, PIPE
import atexit

# anything that holds stdin and stdout should work
proc = Popen(['powershell'], stdin=PIPE, stdout=PIPE)

def cleanup():
    print('hi bob')
    proc.kill()
    proc.communicate()

atexit.register(cleanup)
```

xref https://github.com/matplotlib/matplotlib/issues/27437

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by serhiy-storchaka** [comment] 2024-02-09 16:44
cc @chgnrdv, @gpshead

**Comment by zooba** [comment] 2024-02-12 22:45
(cc @ericsnowcurrently)

One possibility is to transform the Windows code here into a purely native thread, rather than a Python thread, but that is likely to break people who are passing file objects to `stdout=`/`stderr=` besides our constants. That's probably unlikely, but we also shouldn't break it.

What might be better, and why I pinged Eric, is to find a finalization ordering where we can run `atexit` callbacks and then require all threads to be exited. That may not help with the similar GC issues, but it seems like `atexit` ought to be okay with running a bit earlier.

**Comment by ericsnowcurrently** [comment] 2024-03-18 21:47
See gh-116677.

**Comment by gpshead** [comment] 2024-03-19 01:02
This subprocess on Windows atexit or from a non-daemon thread use case is a good one. I'm going to mark this a duplicate of our more general issue #113964 on the topic where we've got a PR and likely a second one in the works to address this.

**Closed as not planned by gpshead** 2024-03-19 01:02 UTC
Labels: type-bug, OS-windows, 3.12, 3.13
