### ISSUE TITLE
mock raises exception when using a spec with an attribute that raises exception on access

### ISSUE THREAD

**Issue by 86da2b18-4a79-4b15-997d-4be64dd0987f** [python/cpython#89917] opened 2021-11-08 19:47 UTC
BPO | [45756](https://bugs.python.org/issue45756)
--- | :---
Nosy | @ambv, @hongweipeng, @tirkarthi, @sobolevn, @jaap3
PRs | <li>python/cpython#29901</li><li>python/cpython#31348</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-08.19:47:53.494>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.11']
title = 'mock raises exception when using a spec with an attribute that raises exception on access'
updated_at = <Date 2022-02-15.06:36:26.841>
user = 'https://bugs.python.org/kjamieson'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-15.06:36:26.841>
actor = 'hongweipeng'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-11-08.19:47:53.494>
creator = 'kjamieson'
dependencies = []
files = []
hgrepos = []
issue_num = 45756
keywords = ['patch']
message_count = 3.0
messages = ['405982', '406284', '406452']
nosy_count = 6.0
nosy_names = ['lukasz.langa', 'hongweipeng', 'xtreak', 'sobolevn', 'kjamieson', 'jaap3']
pr_nums = ['29901', '31348']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45756'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by carljm** [comment] 2023-05-05 19:36
Closing as duplicate of #85934

**Closed as not planned by carljm** 2023-05-05 19:36 UTC
Labels: type-bug, 3.11, 3.10, 3.9 (EOL), 3.8 (EOL)
