### ISSUE TITLE
Python bug in if and else

### ISSUE THREAD

**Issue by Untilsara** [python/cpython#99759] opened 2022-11-24 18:51 UTC
Dear programmers, please pay attention to this code.

 Question: Ask the user to say the three sides of a triangle and Python will answer them, what kind of triangle is this triangle?  (, isosceles, equilateral, or other)

The coding environment is IDLE.

a=int(input("enter the first side"))
b=int(input("enter the second side"))
c=int(input("enter the third side "))
if(a==b or a==c or b==c):
  print("isosceles")
elif(a==b==c):
   print("Equilateral")
else:
       print("invalid input")

If the user enters the value of 5 for all three, contrary to the idea, Python says that the triangle is isosceles, if a triangle with three equal sides is equilateral, and we mentioned this condition in elif, but Python is wrong.  and checks the first if.

Please check this code and I would be grateful if you answer.  Thanks for your hard work.  (an eighteen-year-old programmer).

**Comment by zware** [comment] 2022-11-24 19:18
Duplicate of #99757

**Closed as not planned by zware** 2022-11-24 19:18 UTC
Labels: type-bug

**Comment by stevendaprano** [comment] 2022-11-24 20:59
@Untilsara the bug is in your code, not in Python. Please ask for help at Python's Discuss, Reddit's /learnpython or [the tutor mailing list](https://mail.python.org/mailman/listinfo/tutor).

You are a beginner at programming. Thousands of people with ten, twenty or thirty years of experience use Python every day. Any time you find something where Python does not do what you expect, it is **very** unlikely that you have discovered a bug that nobody else has noticed in thirty years, and more likely that you have made a mistake.
