### ISSUE TITLE
Improve and simplify configure.ac checks

### ISSUE THREAD

**Issue by tiran** [python/cpython#89886] opened 2021-11-05 10:05 UTC
BPO | [45723](https://bugs.python.org/issue45723)
--- | :---
Nosy | @tiran, @erlend-aasland
PRs | <details><li>python/cpython#29429</li><li>python/cpython#29441</li><li>python/cpython#29442</li><li>python/cpython#29466</li><li>python/cpython#29485</li><li>python/cpython#29486</li><li>python/cpython#29500</li><li>python/cpython#29517</li><li>python/cpython#29637</li><li>python/cpython#29701</li><li>python/cpython#29846</li><li>python/cpython#30024</li><li>python/cpython#30026</li><li>python/cpython#30029</li><li>python/cpython#30449</li></details>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2021-11-05.10:05:47.030>
labels = ['type-feature', 'build', '3.11']
title = 'Improve and simplify configure.ac checks'
updated_at = <Date 2022-01-12.04:40:54.295>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-12.04:40:54.295>
actor = 'zach.ware'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2021-11-05.10:05:47.030>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 45723
keywords = ['patch']
message_count = 18.0
messages = ['405780', '405799', '405865', '405896', '405932', '405977', '405978', '406021', '406027', '406054', '406104', '406137', '406745', '407281', '408191', '409946', '409951', '409953']
nosy_count = 3.0
nosy_names = ['christian.heimes', 'erlendaasland', 'byllyfish']
pr_nums = ['29429', '29441', '29442', '29466', '29485', '29486', '29500', '29517', '29637', '29701', '29846', '30024', '30026', '30029', '30449']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45723'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-29429
* gh-29441
* gh-29442
* gh-29466
* gh-29485
* gh-29486
* gh-29500
* gh-29517
* gh-29637
* gh-29701
* gh-29846
* gh-30024
* gh-30026
* gh-30029
* gh-30449
* gh-104925
* gh-105058
* gh-105062
* gh-105118
* gh-105192
* gh-105207
* gh-105226
* gh-105423

**Comment by kulikjak** [comment] 2022-04-22 07:22
One of these changes broke our Solaris build.

The issue is that previously, `hstrerror` presence was tested using `AC_LINK_IFELSE`, but the new `PY_CHECK_FUNC` macro uses `AC_COMPILE_IFELSE` and (at least) on Oracle Solaris, you can compile a program with `hstrerror` but need `-lresolv` for linking.

So now, `hstrerror` is detected as available (previously it was not as the linking failed), but the compilation fails at the end with relocation error "_symbol hstrerror: referenced symbol not found_".


That said, the issue is probably more in the "needs `-lresolv`" detection few lines above:
```
dnl On some systems (e.g. Solaris 9), hstrerror and inet_aton are in -lresolv
dnl On others, they are in the C library, so we to take no action
AC_CHECK_LIB(c, inet_aton, [$ac_cv_prog_TRUE],
  AC_CHECK_LIB(resolv, inet_aton)
)
```
The problem here is that while `hstrerror` still needs `-lresolv`, `inet_aton` does not, and since only the latter is checked here, the system incorrectly determines that it's not necessary.

I am unsure what would be the best fix. I can change the above macro to check for `hstrerror` instead, but this can possibly break systems where `inet_aton` still needs `-lresolv` and `hstrerror` doesn't or where it is not available (the inverse of what is happening now).

Another possibility is to instead use:
```
AC_CHECK_LIB(resolv, hstrerror, [LIBS="-lresolv $LIBS"], [], $LIBS)
```
similarly to how it's being used for `socket` and `nsl`. But this results in `-lresolv` being added whenever libresolv is available (even on systems where it doesn't have to be linked).


I think that both of these should work, but neither of them is a perfect solution. I guess the best one would be to create a list of functions where each might need `-lresolv` and add it if one does, but I am not sure if that is not an overkill.

I am not very familiar with configure scripts and macros, so I might be overlooking better solutions and will be happy for any suggestions.

**Comment by asottile** [comment] 2023-06-02 21:41
autoconf bumping to 2.71+ is a little annoying because LTS ubuntu 20.04 only ships with `2.69`

should this have landed in 3.12 which is already in beta freeze?  I'm building this for deadsnakes and it'd kind of suck to not ship 3.12 for ubuntu 20.04 especially when 3.12b1 built cleanly

**Comment by erlend-aasland** [comment] 2023-06-03 05:03
> autoconf bumping to 2.71+ is a little annoying because LTS ubuntu 20.04 only ships with `2.69`
> 
> 
> 
> should this have landed in 3.12 which is already in beta freeze?  I'm building this for deadsnakes and it'd kind of suck to not ship 3.12 for ubuntu 20.04 especially when 3.12b1 built cleanly

Perhaps you are misunderstanding something. The _generated_ `configure` script is **part of the sources**; a clean build includes the generated configure script (try `git clean -fdx`).

**Comment by asottile** [comment] 2023-06-03 12:37
part of debian packaging is to regenerate configure

**Comment by erlend-aasland** [comment] 2023-06-03 12:54
> part of debian packaging is to regenerate configure

They can still do that with autoconf 2.69. There is no hard requirement to use 2.71. We only require 2.71 for CPython development. Debian should be all ok with 2.69.

**Comment by asottile** [comment] 2023-06-03 13:25
the sources were updated to require 2.71 in #105207

**Comment by erlend-aasland** [comment] 2023-06-03 13:29
> the sources were updated to require 2.71 in #105207 

For CPython development, yes.

**Comment by erlend-aasland** [comment] 2023-06-03 13:33
Ah, there's a requirement check in the configure.ac script. Perhaps we can loosen that.

**Comment by asottile** [comment] 2023-06-03 13:58
> Ah, there's a requirement check in the configure.ac script. Perhaps we can loosen that.

yes that's the one I've been referring to

**Comment by erlend-aasland** [comment] 2023-06-19 08:08
I'll close this issue for now; Christian and I made several improvements to the AC code back in 3.10 and 3.11. IMO, future improvements should get their own targeted issues.

(cc. @tiran, in case you're around)

**Closed as completed by erlend-aasland** 2023-06-19 08:08 UTC
Labels: type-feature, build, 3.13

**Comment by asottile** [comment] 2023-06-19 10:35
@erlend-aasland my fear is that 2.71+ syntax / features will get used -- what should I do then?

**Comment by erlend-aasland** [comment] 2023-06-19 10:43
> @erlend-aasland my fear is that 2.71+ syntax / features will get used -- what should I do then?

I suggest sticking to [the recommendations of the devguide](https://devguide.python.org/getting-started/setup-building/#regenerate-configure):

```console
$ podman run --rm --pull=always -v $(pwd):/src:Z quay.io/tiran/cpython_autoconf:271
# ... or:
$ docker run --rm --pull=always -v $(pwd):/src quay.io/tiran/cpython_autoconf:271
```

Use the `269` tag iso. `271` for GNU Autoconf 2.69. Note also, that the autoconf version we use for 3.11 and older is _not_ the stock GNU Autoconf v2.69; it is a patched version. So, once again, you're better off by using the devguide recommendations (or just use the `configure` script shipped with the source code) :)

**Comment by asottile** [comment] 2023-06-19 10:47
I can't just do that unfortunately. that's outside my control as debian packages both *must* build from source and use the packages of the distribution

when 2.71+ syntax is used I'll basically have no choice but to drop the packages which is unfortunate but understandable

**Comment by erlend-aasland** [comment] 2023-06-19 10:51
Well, on the bright side, no "2.71+ syntax" did sneak in yet, so deadsnakes should be fine for now :)
