### ISSUE TITLE
Consistent use of valid index check

### ISSUE THREAD

**Issue by eendebakpt** [python/cpython#99761] opened 2022-11-24 22:08 UTC
# Feature or enhancement

In `listobject.c` there is an [optimization](https://github.com/python/cpython/blob/main/Objects/listobject.c#L230) to check whether an index is valid (e.g. `0 <= index < N`) using a single comparison. The same optimization is not used in other files such as `tupleobject.c`.

By replacing index checks with a single macro that includes the optimization we have consistency in the code and have the optimized check for all index checks.

# Previous discussion

Idea first mentioned at https://github.com/faster-cpython/ideas/issues/498

### Linked PRs
* gh-99762
* gh-100064

**Comment by serhiy-storchaka** [comment] 2024-06-08 07:58
This is a duplicate of #72583.

**Closed as not planned by serhiy-storchaka** 2024-06-08 07:58 UTC
Labels: type-feature, interpreter-core
