### ISSUE TITLE
`isinstance(..., Optional[Any])` always returns False

### ISSUE THREAD

**Issue by jcal-15** [python/cpython#128232] opened 2024-12-25 00:00 UTC
# Bug report

### Bug description:

`isinstance(..., Optional[Any])` is always returning False. Based off of behavior of other types I am pretty sure that `isinstance` should raise a `TypeError`

```python
# Add a code block here, if required
>>> from typing import Optional, Any

# ✅ `Any` raises a TypeError
>>> isinstance(1, Any)
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    isinstance(1, Any)
    ~~~~~~~~~~^^^^^^^^
  File "C:\Program Files\Python313\Lib\typing.py", line 589, in __instancecheck__
    raise TypeError("typing.Any cannot be used with isinstance()")
TypeError: typing.Any cannot be used with isinstance()

# ✅ Generic types raise type errors
>>> isinstance(1, list[int])
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    isinstance(1, list[int])
    ~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: isinstance() argument 2 cannot be a parameterized generic

# ✅ Optional of Generic types raise type errors
>>> isinstance(1, Optional[list[int]])
Traceback (most recent call last):
  File "<python-input-10>", line 1, in <module>
    isinstance(1, Optional[list[int]])
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\typing.py", line 1786, in __instancecheck__
    return self.__subclasscheck__(type(obj))
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\typing.py", line 1790, in __subclasscheck__
    if issubclass(cls, arg):
       ~~~~~~~~~~^^^^^^^^^^
TypeError: issubclass() argument 2 cannot be a parameterized generic
>>>

# ❌ Optional of `Any` returns false
>>> isinstance(1, Optional[Any])
False
>>> isinstance(Any, Optional[Any])
False
>>> isinstance("Any", Optional[Any])
False
>>>
```

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment] 2024-12-25 07:43
This appears to be because `Optional[Any]` produces a `typing.Union`, and its `__instancecheck__` is implemented by delegating to `__subclasscheck__`, and somehow you can do `issubclass()` on Any:

```
>>> issubclass(int, Any)
False
```

**Comment by serhiy-storchaka** [comment] 2024-12-30 18:59
Closing as a duplicate of #88834.

**Closed as not planned by serhiy-storchaka** 2024-12-30 18:59 UTC
Labels: type-bug, topic-typing
