### ISSUE TITLE
functools.cache vs sys.setrecursionlimit

### ISSUE THREAD

**Issue by gsbrodal** [python/cpython#127346] opened 2024-11-27 20:34 UTC
# Bug report

### Bug description:

When running the below code with Python 3.13.0 on Windows

```python
import functools
import sys

sys.setrecursionlimit(1_000_000)

@functools.cache
def double(n):
    return 2 + double(n - 1) if n > 0 else 0

print(f'{double(2_000) = }')
```
I get the following error

    return 2 + double(n - 1) if n > 0 else 0
               ~~~~~~^^^^^^^
    [Previous line repeated 996 more times]
    RecursionError: maximum recursion depth exceeded"

It appears that the `sys.setrecursionlimit` does not carry over to `functools.cache`. The error does not occur when using Python 3.12.3.


### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment] 2024-11-27 21:16
Duplicate of #112215

**Closed as not planned by Eclips4** 2024-11-27 21:16 UTC
Labels: type-bug

**Comment by gsbrodal** [comment] 2024-11-27 23:56
Sorry for the slightly wrong info - the problem also persisted in Python 3.12 on Windows (I was not running the program with Python 3.12 on my Windows machine). I just downloaded the Windows binaries for Python 3.10.10, 3.11.7, and 3.12.7, and all have problems with increasing the recursionlimit and the `functools.cache`.

I know increasing the recursion limit comes with a risk, so I ask for trouble. I was just hopping that I always could use `functools.cache` instead of writing my own `@cache` decorator, like the below. The below `@cache` decorator handles significantly higher recursion depths with Python 3.13.0 on Windows (and with 3.12 and 3.11, but not with 3.10).

```
import sys
sys.setrecursionlimit(1_000_000)

def cache(f):
    answers = {}
    def wrapper(x):
        if x not in answers:
            answers[x] = f(x)
        return answers[x]
    return wrapper

@cache
def double(n):
    return 2 + double(n - 1) if n > 0 else 0

print(f'{double(400_000) = }')  # prints 800_000
````
