### ISSUE TITLE
Failing test_exceptions and test_threading

### ISSUE THREAD

**Issue by d1a6975d-7e95-4d0f-bcb0-e4856af34156** [python/cpython#89697] opened 2021-10-20 08:57 UTC
BPO | [45534](https://bugs.python.org/issue45534)
--- | :---
Nosy | @pablogsal, @iritkatriel, @aritra1911

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-20.08:57:27.219>
labels = ['type-bug', 'tests', '3.11']
title = 'Failing test_exceptions and test_threading'
updated_at = <Date 2021-10-20.12:16:44.210>
user = 'https://github.com/aritra1911'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-20.12:16:44.210>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2021-10-20.08:57:27.219>
creator = 'aritra1911'
dependencies = []
files = []
hgrepos = []
issue_num = 45534
keywords = []
message_count = 9.0
messages = ['404405', '404407', '404411', '404419', '404428', '404431', '404434', '404435', '404436']
nosy_count = 3.0
nosy_names = ['pablogsal', 'iritkatriel', 'aritra1911']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45534'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment] 2022-04-14 14:37
This is a duplicate of https://bugs.python.org/issue45400. It was fixed there.

**Closed as completed by iritkatriel** 2022-04-14 14:37 UTC
Labels: type-bug, tests, 3.11
