### ISSUE TITLE
posix._fcopyfile adding couple of more flags

### ISSUE THREAD

**Issue by devnexen** [python/cpython#92172] opened 2022-05-02 18:17 UTC
**Feature or enhancement**

Adding `COPYFILE_STAT`, `COPYFILE_ACL` and `COPYFILE_XATTR` flags for fcopyfile in addition of `COPYFILE_DATA`

**Comment by JelleZijlstra** [comment] 2022-05-02 23:12
Duplicate of #90887

**Closed as completed by JelleZijlstra** 2022-05-02 23:12 UTC
Labels: type-feature
