### ISSUE TITLE
spam output printed by test__xxinterpchannels

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#111712] opened 2023-11-03 20:52 UTC
```
0:04:08 load avg: 4.60 [ 60/462] test__xxinterpchannels passed -- running (1): test.test_multiprocessing_spawn.test_processes (1 min 1 sec)
Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 34 is closed
Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 34 is closed
0:04:12 load avg: 4.60 [ 61/462] test__xxsubinterpreters passed -- running (1): test.test_multiprocessing_spawn.test_processes (1 min 5 sec)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemExit: 42
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: spam
  File "<string>", line 1
    print("spam"
         ^
SyntaxError: '(' was never closed
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit: 42

```

**Comment by Eclips4** [comment] 2023-11-03 20:53
Duplicate of #110866

**Closed as not planned** 2023-11-03 20:53 UTC
