### ISSUE TITLE
`asyncio.wait(aws)` require aws is 'iterable', but doesn't accept `generator`

### ISSUE THREAD

**Issue by NewUserHa** [python/cpython#99936] opened 2022-12-01 20:12 UTC
# Bug report
https://github.com/python/cpython/blob/0563be23a557917228a8b48cbb31bda285a3a815/Lib/asyncio/tasks.py#L407-L409
https://docs.python.org/3/library/asyncio-task.html#waiting-primitives
https://docs.python.org/3/glossary.html#term-iterable
`asyncio.wait(aws)` require aws is 'iterable' but doesn't accept `generator` while which is iterable ( has __iter__ and __next__ methods):
```py
await asyncio.wait(asyncfunc(_) for _ in range())
```

**Comment by JelleZijlstra** [comment] 2022-12-01 20:16
This is because generators are in `asyncio.coroutines._COROUTINE_TYPES`: https://github.com/python/cpython/blob/main/Lib/asyncio/coroutines.py#L28. Therefore, `asyncio.coroutines.iscoroutine` thinks every generator is a coroutine.

This is presumably a holdover from generator-based coroutines, which no longer exist in recent versions of asyncio. We should consider removing `GeneratorType` from `_COROUTINE_TYPES`, but we'll have to think about whether there are any backward compatibility implications.

**Comment by NewUserHa** [comment] 2022-12-01 20:28
a more thing:
I also see "DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.".
It didn't say anything, but I guess it's asking users to `.create_task()` outside `.wait()` for comparing if the task is in the returned `done set`. But the [document](https://docs.python.org/3/library/asyncio-task.html#waiting-primitives) of `.wait()` deleted that comparing part from the example code.
It seems to make a little confuse both in DeprecationWarning and the document because they didn't match.

maybe should update the document to match the warning?

**Comment by kumaraditya303** [comment] 2022-12-02 11:49
Duplicate of https://github.com/python/cpython/issues/78530

**Closed as not planned by kumaraditya303** 2022-12-02 11:49 UTC
Labels: type-bug, topic-asyncio

**Comment by NewUserHa** [comment] 2022-12-02 14:04
I have seen https://github.com/python/cpython/issues/78530 when open issue. However, this issue is more about the document.
