### ISSUE TITLE
WeakKeyDictionary iteration not thread-safe

### ISSUE THREAD

**Issue by FrozenBob** [python/cpython#98937] opened 2022-11-01 00:41 UTC
# Bug report

Despite a comment in the _IterationGuard code claiming the iteration guard is thread-safe, iterating over a weakref.WeakKeyDictionary is not thread-safe.

For example, after a thread finishes iterating and starts committing removals, another thread might start iterating while the first thread is still cleaning up. Depending on thread scheduling, the second thread might hit a `RuntimeError: dictionary changed size during iteration` if the first thread removes entries while the second thread is iterating, or the second thread might finish iterating and start trying to commit removals at the same time as the first thread, with consequences like `IndexError: pop from empty list` inside `_commit_removals`. There may be other possible symptoms I haven't seen.

Similar errors also occur with WeakSet and WeakValueDictionary.

# Your environment

- CPython versions tested on: 3.10, 3.7 (I don't have a copy of 3.11 handy.)
- Operating system and architecture: Linux, x86_64

Reproducer:

    import threading
    import weakref
     
    class X: pass
     
    n = 100000
     
    l = [X() for i in range(n)]
    d = weakref.WeakKeyDictionary({x: None for x in l})
     
    event = threading.Event()
     
    def target():
        global l
        for i, k in enumerate(d):
            if i == n-1:
                del l
                event.set()
     
    threading.Thread(target=target).start()
     
    event.wait()
    for k in d:
        pass

You may have to adjust the value of `n`, or run the code a few times, depending on your environment.

One observed stack trace:

```
Traceback (most recent call last):
  File "./prog.py", line 23, in <module>
  File "/usr/lib/python3.7/weakref.py", line 451, in keys
    for wr in self.data:
RuntimeError: dictionary changed size during iteration
```

Another observed stack trace:

```
Traceback (most recent call last):
  File "./prog.py", line 23, in <module>
  File "/usr/lib/python3.7/weakref.py", line 454, in keys
    yield obj
  File "/usr/lib/python3.7/_weakrefset.py", line 32, in __exit__
    w._commit_removals()
  File "/usr/lib/python3.7/weakref.py", line 382, in _commit_removals
    del d[l.pop()]
IndexError: pop from empty list
```

**Comment by FrozenBob** [comment] 2022-11-01 00:44
Similar errors also occur with WeakSet and WeakValueDictionary.

**Comment by kumaraditya303** [comment] 2024-10-16 16:42
Duplicate of https://github.com/python/cpython/issues/89967

**Closed as not planned by kumaraditya303** 2024-10-16 16:42 UTC
Labels: type-bug, stdlib
