### ISSUE TITLE
Deadlock when calling PyGILState_Ensure() from a fresh C thread

### ISSUE THREAD

**Issue by tom-pytel** [python/cpython#96071] opened 2022-08-18 12:29 UTC
# Bug report

This used to work with py 3.8, 3.9 and 3.10 but now fails. The failure is due to a deadlock condition due to the move of an alloc from before a HEAD_LOCK() to after causing a recursive call to PyGILState_Ensure() which eventually deadlocks on the HEAD_LOCK().

The following is a trace of calls from the initial call to PyGILState_Ensure() to the eventual deadlock:

```
pystate:PyGILState_Ensure()
pystate:PyThreadState_New()
pystate:new_threadstate()
  HEAD_LOCK()  <-- Initial head locked, the alloc_threadstate() call below used to happen before this in previous versions of Python.
pystate:alloc_threadstate()
obmalloc:PyMem_RawCalloc()
_tracemalloc:_PyMem_Raw.calloc()
_tracemalloc:tracemalloc_raw_calloc()
  get_reentrant() = 0
  set_reenterant(1)
pystate:PyGILState_Ensure()
pystate:PyThreadState_New()
pystate:new_threadstate()
  HEAD_LOCK()  <--   DEADLOCK HERE!
```

Steps to reproduce: In a Python C extension module, create a C thread then try to call PyGILState_Ensure() in that thread with no previous existing Python threadstate.

# Your environment

Python 3.11.0rc1
Linux tom-VirtualBox 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ronaldoussoren** [comment] 2022-08-18 16:40
Do you have a self-contained example that demonstrates the problem?  I quickly checked using PyObjC on macOS (which basically does this when starting threads using the Cocoa interface), and that code did not deadlock.

**Comment by tom-pytel** [comment] 2022-08-18 19:22
> Do you have a self-contained example that demonstrates the problem? I quickly checked using PyObjC on macOS (which basically does this when starting threads using the Cocoa interface), and that code did not deadlock.

Ok, I investigated a little deeper and admittedly I have a bit more going on in the environment where I found this. Tried duplicating until I found the difference: `tracemalloc`. When `tracemalloc` is imported and started the function flow is as shown in the header of this issue. When it is not, then after `obmalloc:PyMem_RawCalloc()` it goes to `obmalloc:_PyMem_DebugRawCalloc()` instead of `_tracemalloc:_PyMem_Raw.calloc()` which avoids the recursive call to `PyGILState_Ensure()` and works fine. I will see about getting some poc module code here tomorrow or after.

**Comment by ronaldoussoren** [comment] 2022-08-18 19:46
I can reproduce using PyObjC by using ``python3.11 -X tracemalloc script.py`` to start the PyObjC using script I mentioned earlier. 

@pablogsal is this a release blocker?

**Comment by pablogsal** [comment] 2022-08-18 20:08
> @pablogsal is this a release blocker?

Indeed it is. Thanks for pinging me.

**Comment by pablogsal** [comment] 2022-08-18 20:08
@ronaldoussoren Can you share the reproducer?

**Comment by pablogsal** [comment] 2022-08-18 20:09
Or alternatively, could you bisect the issue?

**Comment by tom-pytel** [comment] 2022-08-18 20:41
> Or alternatively, could you bisect the issue?

In previous versions the memory for the new `PyThreadState` was allocated before the `HEAD_LOCK()` in `pystate:new_threadstate()`, if you revert to that behavior the bug is fixed.

**Comment by ronaldoussoren** [comment] 2022-08-18 20:45
The reproducer needs PyObjC (from v8.5-branch in https://github.com/ronaldoussoren/pyobjc because the latest release does not work with Python 3.11 yet). 

The reproducer script:

```
from Cocoa import NSObject, NSThread
import time

class Runner(NSObject):
   def doit_(self, arg):
       print("hello world")
       print(NSThread.currentThread().isMainThread())


runner = Runner.alloc().init()

thread = NSThread.alloc().initWithTarget_selector_object_(runner, b"doit:", None)
thread.start()
print(thread)
time.sleep(1)
while thread.isExecuting():
    time.sleep(1)
```

This script hangs when using "python3.11 -X tracemalloc script.py`` and works fine when using an older version of Python or leaving out ``-X tracemalloc``.

It is probably easier to reproduce this using a small C extension that uses ``pthread_create`` to launch a thread that call ``PyGILState_Ensure``. 

I can look into this during the weekend at the earliest, but also need to get a release of PyObjC out to fix Python 3.11 support (which is needed due to documented API changes, nothing to worry about there).

**Comment by pablogsal** [comment] 2022-08-18 22:45
I will prepare a patch tomorrow

**Comment by kumaraditya303** [comment] 2022-08-19 06:41
Minimal reproducer:

```c
#include "Python.h"
#include "pthread.h"

static struct PyModuleDef deadlockmodule = {
    PyModuleDef_HEAD_INIT,
    "deadlock",
    NULL,
    -1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};

static void *func(void *arg)
{
    printf("in func\n");
    PyGILState_STATE state = PyGILState_Ensure();
    printf("called PyGILState_Ensure\n");
    PyGILState_Release(state);
    printf("called PyGILState_Release\n");
    return NULL;
}

PyMODINIT_FUNC
PyInit_deadlock(void)
{
    Py_BEGIN_ALLOW_THREADS
    pthread_t thread;
    pthread_create(&thread, NULL, func, NULL);
    pthread_join(thread, NULL);
    Py_END_ALLOW_THREADS
    return PyModule_Create(&deadlockmodule);
}

```

**Comment by kumaraditya303** [comment] 2022-08-19 06:44
@pablogsal I have a fix for this https://github.com/python/cpython/issues/96071

**Comment by ericsnowcurrently** [comment] 2022-08-19 18:59
Thanks for the eyes on this, everyone, and for the fixes.

**Comment by ericsnowcurrently** [comment] 2022-08-19 19:46
I've merged the fix into main.  Now I'm wondering if it would make sense to also add a test that would have caught the bug.  That wouldn't be too hard, would it @kumaraditya303?

**Comment by kumaraditya303** [comment] 2022-08-21 08:56
PR https://github.com/python/cpython/pull/96137 adds a test for this.

**Comment by ericsnowcurrently** [comment] 2022-08-22 18:43
We can close this once gh-96184 and gh-96185 are merged.

**Comment by kumaraditya303** [comment] 2022-08-24 09:54
Closing  as I have fixed both the issue and added tests to ensure no further regression. Thanks!

**Closed as completed by kumaraditya303** 2022-08-24 09:54 UTC
Labels: type-bug, interpreter-core, 3.11, 3.12

**Comment by ericsnowcurrently** [comment] 2022-08-24 16:27
Thanks, @kumaraditya303!
