### ISSUE TITLE
import mmap

### ISSUE THREAD

**Issue by Mazogedoo** [python/cpython#110250] opened 2023-10-02 23:58 UTC
import mmap
mem = mmap.mmap(-1, mmap.PAGESIZE)
mem.resize(mmap.PAGESIZE * N)
#                   ^ no error
print(mem[mmap.PAGESIZE-1])
#                  ^ still ok
print(mem[mmap.PAGESIZE])
# Bus error (core dumped)

_Originally posted by @Mazogedoo in https://github.com/python/cpython/issues/110243#issuecomment-1743939070_

**Comment by JelleZijlstra** [comment] 2023-10-03 00:00
Duplicate of #110243

**Closed as not planned by JelleZijlstra** 2023-10-03 00:00 UTC
