### ISSUE TITLE
Incorrect parsing of attribute with type annotation involving |, the attribute name having the same name as a class used in its type, and a default value

### ISSUE THREAD

**Issue by tibbe** [python/cpython#115844] opened 2024-02-23 08:52 UTC
# Bug report

### Bug description:

```python
>>> class A: pass
... 
>>> class B:
...   A: A | None = None
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in B
TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by AlexWaygood** [comment] 2024-02-23 09:06
Thanks for the report! I agree that this can seem unintuitive, but this is actually documented as part of the [language reference](https://docs.python.org/3/reference/simple_stmts.html#annassign), which states that assignments are evaluated first, then annotations. To change this now would be very breaking. (Also note that we discussed this issue before in #108437 -- this issue is a duplicate of that earlier issue.)

See also the feature request #107271, which would also help fix this specific runtime error.

To fix the issue in your code, I would recommend either:
1. Not shadowing the global `A` variable in the class scope, _or_
2. If you _have_ to use shadowing, you could stringify the annotation:
   a. Either manually like this:
      ```py
      class A: pass

      class B:
         A: "A | None" = None
      ```
   b. Or by adding `from __future__ import annotations` to the top of your file

**Closed as not planned by AlexWaygood** 2024-02-23 09:06 UTC
Labels: type-bug, topic-typing
