### ISSUE TITLE
asyncio DatagramProtocol stops calling callbacks after OSError, on Windows

### ISSUE THREAD

**Issue by ecb5d39f-207a-4833-9a8b-971d9e330cb7** [python/cpython#88906] opened 2021-07-26 14:50 UTC
BPO | [44743](https://bugs.python.org/issue44743)
--- | :---
Nosy | @asvetlov, @1st1, @sim1234, @JulianOrteil
Files | <li>[reproducible_datagramprotocol_error.py](https://bugs.python.org/file50183/reproducible_datagramprotocol_error.py "Uploaded as text/plain at 2021-07-26.14:50:57 by @JulianOrteil"): Reproducible code</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-26.14:50:58.620>
labels = ['type-bug', '3.9', 'expert-asyncio']
title = 'asyncio DatagramProtocol stops calling callbacks after OSError'
updated_at = <Date 2021-11-14.20:12:24.291>
user = 'https://github.com/JulianOrteil'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-14.20:12:24.291>
actor = 'sim1234'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-07-26.14:50:58.620>
creator = 'JulianOrteil'
dependencies = []
files = ['50183']
hgrepos = []
issue_num = 44743
keywords = []
message_count = 2.0
messages = ['398229', '406332']
nosy_count = 5.0
nosy_names = ['asvetlov', 'yselivanov', 'sim1234', 'Thomas Trummer', 'JulianOrteil']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44743'
versions = ['Python 3.9']
```

</p></details>

**Comment by AdjWang** [comment] 2022-06-25 09:23
Same issue using python 3.10 on windows 10. The issue can also happen on the client-side.
During the client and server exchanging messages, I restarted the server process. The client raised "OSError: [WinError 1234] No service is operating at the destination network endpoint on the remote system", then it stopped receiving messages even after the server process restarted. 
However the sending on the client-side is still working since the restarted server can receive messages from the client.

**Comment by kumaraditya303** [comment] 2024-11-01 15:04
Duplicate of #91227

**Closed as not planned by kumaraditya303** 2024-11-01 15:04 UTC
Labels: type-bug, topic-asyncio, OS-windows
