### ISSUE TITLE
IDLE macOS shortcut ctrl+S doesn’t work for show completions

### ISSUE THREAD

**Issue by d6cf71fe-527d-437c-983c-852fea3c880a** [python/cpython#90655] opened 2022-01-24 04:33 UTC
BPO | [46497](https://bugs.python.org/issue46497)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @ned-deily, @dvd101x
Files | <li>[IDLE edit menu.jpg](https://bugs.python.org/file50596/IDLE%20edit%20menu.jpg "Uploaded as image/jpeg at 2022-01-29.16:08:17 by @dvd101x")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2022-01-24.04:33:13.540>
labels = ['OS-mac', 'expert-IDLE', 'type-bug', '3.11']
title = 'IDLE macOS shortcut ctrl+S doesn\xe2\x80\x99t work for show completions'
updated_at = <Date 2022-01-29.16:08:17.281>
user = 'https://github.com/dvd101x'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-29.16:08:17.281>
actor = 'dvd101x'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE', 'macOS']
creation = <Date 2022-01-24.04:33:13.540>
creator = 'dvd101x'
dependencies = []
files = ['50596']
hgrepos = []
issue_num = 46497
keywords = []
message_count = 3.0
messages = ['411441', '412037', '412080']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'ned.deily', 'dvd101x']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46497'
versions = ['Python 3.11']
```

</p></details>

**Comment by ronaldoussoren** [comment] 2022-11-22 10:40
This is a duplicate of #88564 (bad label in the menu for show completions), and #88564 has PR that fixes this.

I therefore propose closing this issue.

**Closed as not planned** 2022-11-23 08:01 UTC
Labels: type-bug, OS-mac, topic-IDLE, 3.11
