### ISSUE TITLE
Fix [frozen]set documentation for multiple-set methods

### ISSUE THREAD

**Issue by SimpleArt** [python/cpython#101565] opened 2023-02-04 17:20 UTC
# Documentation

Many methods of `set` and `frozenset` methods take more arguments than what their documentation claims:

```python
{1, 2, 3}.intersection([1, 2], [2, 3])  # {2}

help(set.intersection)
"""
intersection(...)
    Return the intersection of two sets as a new set.

    (i.e. all elements that are in both sets.)

"""
```

There have been a few issues about this such as #51512, but it seems that they have been closed as "fixed" despite not having been fixed?

**Comment by rhettinger** [comment] 2023-02-04 22:19
Closing as a duplicate of https://github.com/python/cpython/issues/99967 .

I'm aware of the issue and am working on it.

**Closed as not planned by rhettinger** 2023-02-04 22:19 UTC
Labels: docs
