### ISSUE TITLE
support for Awaitable objects in `asyncio.wait` removed in 3.11

### ISSUE THREAD

**Issue by graingert** [python/cpython#95601] opened 2022-08-03 16:30 UTC
on `python3.10 -W error`  this passes:

```python
class ExampleAwaitable:
    def __await__(self):
        async def _():
            return await asyncio.sleep(0)

        return _().__await__()


import asyncio

print(f"{asyncio.iscoroutine(ExampleAwaitable())=}")

async def amain():
    await asyncio.wait([ExampleAwaitable()])
    print("waited!")

asyncio.run(amain())
```

and in 3.11 this fails:

```
asyncio.iscoroutine(ExampleAwaitable())=False
Traceback (most recent call last):
  File "/home/graingert/projects/foo.py", line 17, in <module>
    asyncio.run(amain())
  File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/graingert/projects/foo.py", line 14, in amain
    await asyncio.wait([ExampleAwaitable()])
  File "/usr/lib/python3.11/asyncio/tasks.py", line 427, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 531, in _wait
    f.add_done_callback(_on_completion)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ExampleAwaitable' object has no attribute 'add_done_callback'
```

this broke distributed and we missed the DeprecationWarning because ensure_future accepts a wider variety of objects than just futures tasks and coroutines

https://github.com/dask/distributed/issues/6785

the removal happened here https://github.com/python/cpython/commit/903f0a02c16240dc769a08c30e8d072a4fb09154

**Comment by graingert** [comment] 2022-08-03 16:38
I think using something like this might help?

```python
def _insist_future(f, loop):
    f2 = ensure_future(f, loop=loop)
    if f2 is not f:
        warnings.warn("passing non-futures is deprecated")
    return f2


```python
    fs = set(fs)
    loop = events.get_running_loop()
    if any(coroutines.iscoroutine(f) for f in fs):
        raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
    fs = {_insist_future(f, loop=loop) for f in fs}
    return await _wait(fs, timeout, return_when, loop)
```

**Comment by graingert** [comment] 2022-08-09 16:40
This was intended to be deprecated in 3.10 so I'm tentatively adding the 3.10 label

**Comment by gvanrossum** [comment] 2022-08-27 23:47
So what is the bug exactly? Was the deprecation schedule not followed properly? Or do you just disagree with the deprecation and subsequent removal? In that case, tough luck. The release manager isn't going to allow the removal to be reversed.

**Comment by graingert** [comment] 2022-09-12 07:04
> So what is the bug exactly? Was the deprecation schedule not followed properly? Or do you just disagree with the deprecation and subsequent removal? In that case, tough luck. The release manager isn't going to allow the removal to be reversed.

The deprecation schedule was not followed properly. The removal didn't match the deprecation, and support for iterables was removed. There's more discussion on the PR

**Comment by gvanrossum** [comment] 2022-10-27 17:55
Now that the PR is closed, can you come up with a better description? It should describe a desired course of action.

**Comment by sileht** [comment] 2022-11-23 17:19
I upgrade some projects to 3.11 and got the same issue.

We usually fix python deprecation warning the day python released a version, but we missed that one.

The real root cause issue, I guess, is that the deprecation warning of python < 3.11 was not working for this kind of object:

```
class ExampleAwaitable:
    def __await__(self):
          yield from asyncio.sleep(0)
```

**Comment by kumaraditya303** [comment] 2023-04-16 07:25
@graingert are you going to follow up on this? If not I am inclined to just close it, 3.11 is far ahead in release cycle now anyways.

**Comment by kumaraditya303** [comment] 2023-04-23 13:51
Closing because of no response to my and Guido's comment.

**Closed as not planned by kumaraditya303** 2023-04-23 13:51 UTC
Labels: type-bug, topic-asyncio, 3.11, 3.10, 3.12
