### ISSUE TITLE
JIT CI is broken due to `test_traceback` & `test_tracemalloc`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118275] opened 2024-04-25 11:12 UTC
Looks like something broke: https://github.com/python/cpython/actions/runs/8823706356/job/24224733399#step:8:9723

```pytb
======================================================================
FAIL: test_env_var_invalid (test.test_tracemalloc.TestCommandLine.test_env_var_invalid) (nframe=-1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_tracemalloc.py", line 957, in test_env_var_invalid
    self.check_env_var_invalid(nframe)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/test/test_tracemalloc.py", line 951, in check_env_var_invalid
    self.fail(f"unexpected output: {stderr!a}")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: unexpected output: b"aarch64-binfmt-P: Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory\n"

======================================================================
FAIL: test_env_var_invalid (test.test_tracemalloc.TestCommandLine.test_env_var_invalid) (nframe=1073741824)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_tracemalloc.py", line 957, in test_env_var_invalid
    self.check_env_var_invalid(nframe)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/test/test_tracemalloc.py", line 951, in check_env_var_invalid
    self.fail(f"unexpected output: {stderr!a}")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: unexpected output: b"aarch64-binfmt-P: Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory\n"

======================================================================
ERROR: test_encoded_file (test.test_traceback.TracebackCases.test_encoded_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_traceback.py", line 439, in test_encoded_file
    do_test("", "foo", "ascii", 3)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/test/test_traceback.py", line 428, in do_test
    self.assertIn(("line %s" % lineno), stdout[1],
                                        ~~~~~~^^^
IndexError: list index out of range

----------------------------------------------------------------------
```

**Comment by hugovk** [comment] 2024-04-25 11:22
See also https://github.com/python/cpython/pull/117672#issuecomment-2076573618 and https://github.com/python/cpython/issues/112730#issuecomment-2076634389.

**Comment by nineteendo** [comment] 2024-04-25 11:50
Do we disable these tests like #118247?

**Comment by hugovk** [comment] 2024-04-25 11:54
Maybe, let's see if someone can fix the root cause first. The JIT is experimental and the CI is allowed to fail, it's mainly an annoyance when it does.

**Comment by brandtbucher** [comment] 2024-04-25 18:36
> Maybe, let's see if someone can fix the root cause first. The JIT is experimental and the CI is allowed to fail, it's mainly an annoyance when it does.

Agreed. Since it's affecting others (not just the JIT emulation) it is probably worth actually fixing or handling more generally.

**Comment by brandtbucher** [comment] 2024-04-25 18:38
Perhaps the tests could just patch the desired environment variables instead of wiping them out completely?

**Comment by savannahostrowski** [comment] 2024-05-01 02:59
I think that this is now fixed as I don't see the failures anymore on CI runs. I think that https://github.com/python/cpython/pull/118288 fixed things up.

**Closed as completed** 2024-05-01 05:11 UTC
Labels: performance, topic-JIT
