### ISSUE TITLE
Undocumented breaking change to functools.partialmethod

### ISSUE THREAD

**Issue by pgcd** [python/cpython#99559] opened 2022-11-17 05:23 UTC
# Bug report
This code works perfecty fine in CPython up to 3.10;
```
import functools
class A:
    def whoami(self, obj):
        print(self, obj)
class B:
    pass
a = A()
setattr(B, "whoami", functools.partialmethod(a.whoami))
b = B()
b.whoami()
```
And the output is gonna be something like
`<__main__.A object at 0x7f5385e80a60> <__main__.B object at 0x7f538503d0d0>`

If you run it in 3.11.0, though, the output is:
`TypeError: A.whoami() missing 1 required positional argument: 'obj'`

As far as I can tell, this is somehow due to the instance method no longer implementing a descriptor interface that can be used by `partialmethod`, but I haven't been able to find any usable information in the release notes for 3.11.0

# Your environment

I have tested the minimal example in 3.9.2 and 3.11.0, but other people tested it on 3.10.x and it worked as expected.

**Comment by sweeneyde** [comment] 2022-11-17 06:40
This is essentially a duplicate of https://github.com/python/cpython/issues/99152 right?

**Comment by pgcd** [comment] 2022-11-17 06:47
You're completely right, I have no idea why I couldn't find it when I searched. I guess it can be closed in favor of it.

**Closed as not planned** 2022-11-17 08:28 UTC
Labels: type-bug
