### ISSUE TITLE
function__entry dtrace point is mssing in main branch and v3.12.0

### ISSUE THREAD

**Issue by Zheaoli** [python/cpython#110385] opened 2023-10-05 10:04 UTC
# Bug report

### Bug description:

Compile code with `./configure --with-dtrace`

And here's the readelf result

```text
Displaying notes found in: .note.gnu.property
  Owner                Data size        Description
  GNU                  0x00000030       NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA needed: x86-64-baseline
        x86 feature used: x86, x87, XMM
        x86 ISA used: x86-64-baseline

Displaying notes found in: .note.gnu.build-id
  Owner                Data size        Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: cd07ca8c5a0d8d7ac24b99e423d3a351ee48676a

Displaying notes found in: .note.ABI-tag
  Owner                Data size        Description
  GNU                  0x00000010       NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 4.4.0

Displaying notes found in: .note.stapsdt
  Owner                Data size        Description
  stapsdt              0x00000040       NT_STAPSDT (SystemTap probe descriptors)
    Provider: python
    Name: import__find__load__start
    Location: 0x000000000024ba88, Base: 0x0000000000412f1d, Semaphore: 0x000000000059e722
    Arguments: 8@%rax
  stapsdt              0x00000047       NT_STAPSDT (SystemTap probe descriptors)
    Provider: python
    Name: import__find__load__done
    Location: 0x000000000024baa0, Base: 0x0000000000412f1d, Semaphore: 0x000000000059e724
    Arguments: 8@%rax -4@%edx
  stapsdt              0x00000033       NT_STAPSDT (SystemTap probe descriptors)
    Provider: python
    Name: audit
    Location: 0x0000000000282ba5, Base: 0x0000000000412f1d, Semaphore: 0x000000000059e726
    Arguments: 8@%rbp 8@%rbx
  stapsdt              0x00000036       NT_STAPSDT (SystemTap probe descriptors)
    Provider: python
    Name: gc__start
    Location: 0x000000000029e27d, Base: 0x0000000000412f1d, Semaphore: 0x000000000059e71e
    Arguments: -4@120(%rsp)
  stapsdt              0x00000030       NT_STAPSDT (SystemTap probe descriptors)
    Provider: python
    Name: gc__done
    Location: 0x000000000029e8a4, Base: 0x0000000000412f1d, Semaphore: 0x000000000059e720
    Arguments: -8@%rbx
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

Thanks @jschwinger233  for the help

**Comment by markshannon** [comment] 2023-10-05 12:45
Duplicate of https://github.com/python/cpython/issues/104280

**Closed as completed by markshannon** 2023-10-05 12:45 UTC
Labels: type-bug, 3.12, 3.13
