### ISSUE TITLE
Allow `except X | Y:`, catching PEP-604 unions of exceptions

### ISSUE THREAD

**Issue by Zac-HD** [python/cpython#102414] opened 2023-03-04 07:37 UTC
[PEP-604](https://peps.python.org/pep-0604/) added a compact `X | Y` syntax to express unions of types - I've found this makes type-annotated code much nicer.  The PEP left it an open question whether these unions should be supported in `isinstance()` and `issubclass()`; this was resolved in favor and the analogously expected support in `functools.singledispatch()` was added in https://github.com/python/cpython/issues/90172.

However, `except` clauses raise a runtime error: `catching classes that do not inherit from BaseException is not allowed`.  

```python
t = ZeroDivisionError | ValueError         # Python 3.10 syntax for types.UnionType (PEP-604)
assert isinstance(ZeroDivisionError(), t)  # isinstance and issubclass work

try: 
    1/0
except ZeroDivisionError | ValueError:     # but this fails!
    pass
```
```python-traceback
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    1/0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    except ZeroDivisionError | ValueError: 
TypeError: catching classes that do not inherit from BaseException is not allowed
```

I propose that this restriction should be lifted for `UnionType`, as an enhancement in Python 3.12 - and if appropriate as a bugfix included in the next patch releases of Python 3.10 and 3.11.

**Comment by Fidget-Spinner** [comment] 2023-03-04 08:43
If this is added, I don't think it should be backported to 3.10 and 3.11, as it isn't a bugfix but more of an enhancement. It's only a bug if it diverges from PEP 604. However, PEP 604 says nothing about exceptions.

>The PEP left it an open question whether these unions should be supported in isinstance() and issubclass()

Wait, isn't `isinstance` and `issubclass` explicitly part of the spec? https://peps.python.org/pep-0604/#isinstance-and-issubclass

I don't have any strong opinions on whether we should support this. Could you raise it up on typing-sig for discussion please?

**Comment by AlexWaygood** [comment] 2023-03-04 08:45
This issue is a duplicate of #91123, which was rejected.

**Comment by Zac-HD** [comment] 2023-03-04 08:49
Ah, my search for `UnionType` was too precise to find that issue 😓 

Happy for this to be closed if it's already been rejected; it's a smallish footgun but we can lint for it.

**Comment by AlexWaygood** [comment] 2023-03-04 08:56
> Ah, my search for `UnionType` was too precise to find that issue 😓

It took me a while to find it again, don't worry :)

**Closed as not planned by AlexWaygood** 2023-03-04 08:56 UTC
Labels: type-feature, topic-typing

**Comment by terryjreedy** [comment] 2023-03-04 18:23
Thanks for searching.  Not always easy.
