### ISSUE TITLE
Pathlib join pure windows path and pure posix path changes it behaviour on 3.13

### ISSUE THREAD

**Issue by pohmelie** [python/cpython#125069] opened 2024-10-07 21:18 UTC
# Bug report

## 3.12.7
```
Python 3.12.7 (main, Oct  8 2024, 00:39:14) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib; pathlib.PureWindowsPath("C:\\A") / pathlib.PurePosixPath("/foo/C:\\B").relative_to("/")
PureWindowsPath('C:/B')
```

## 3.13.0rc3
```
Python 3.13.0rc3 (main, Oct  7 2024, 23:18:57) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib; pathlib.PureWindowsPath("C:\\A") / pathlib.PurePosixPath("/foo/C:\\B").relative_to("/")
PureWindowsPath('C:/A/foo/C:/B')
```
 Not sure if it is a bug, or a fixed behaviour

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-125156
* gh-125409
* gh-125410

**Comment by AA-Turner** [comment] 2024-10-07 21:28
cc @barneygale, though the reproducer does look a bit off, with multiple drive roots. 

@pohmelie can you reproduce this using only `os.path`?

A

**Comment by pohmelie** [comment] 2024-10-07 21:34
@AA-Turner 
If you provide a code with `os.path` module, then I can test it. But, AFAIK, `os.path` have no ability to manage windows and posix paths.

**Comment by terryjreedy** [comment] 2024-10-07 23:40
Checking 3.13 What's New or the linked log file might reveal if intentional change.

**Comment by ImFeH2** [comment] 2024-10-08 04:09
It happens after this change.
https://github.com/python/cpython/pull/111431

**Comment by hacscred** [comment] 2024-10-08 10:58
Classic that an optimization changes semantics. I'd rip out that optimization or make sure that the new behavior matches the specification.

**Comment by ZeroIntensity** [comment] 2024-10-08 13:56
cc @barneygale, apparently that PR introduced a breaking change.

**Comment by barneygale** [comment] 2024-10-08 19:42
Thanks for reporting this! There's a few things going on here. I think it comes down to pathlib's special handling of `PurePath(PurePath(...))` and our efforts to delay joining of `*pathsegments`. I believe the 3.13 behaviour is correct, and that we should fix 3.12. PR coming up...

**Comment by barneygale** [comment] 2024-10-08 19:52
Another repro, this one works in 3.13 and 3.14:

```python
>>> a = PureWindowsPath('a')
>>> b1 = PurePosixPath('b', 'c:\\d')
>>> b2 = PurePosixPath('b/c:\\d')
>>> b1 == b2
True
>>> a / b1
PureWindowsPath('c:/d')
>>> a / b2
PureWindowsPath('a/b/c:/d')
```

**Comment by barneygale** [comment] 2024-10-13 16:53
PR available, if anyone has a mo to review: https://github.com/python/cpython/pull/125156

**Comment by barneygale** [comment] 2024-10-13 18:19
I've pushed a fix to 3.12, 3.13 and 3.14 (main).

In the original repro case, the 3.12 behaviour was buggy and the 3.13 behaviour was correct. The optimisation in #111431 (3.13+) happened to fix the issue for paths generated by `relative_to()`. The fix I've applied here should fix the problem at its source.

Thanks for reporting :)

**Closed as completed by barneygale** 2024-10-13 18:19 UTC
Labels: type-bug, topic-pathlib, 3.13

**Comment by pohmelie** [comment] 2024-10-13 18:25
@barneygale 
So, what should I do in my library code? Should I dispatch behaviour by python version? Will the fix lands on 3.12.8 and buggy behaviour still presents in 3.12.0 to 3.12.7 inclusive? 🤔 I want equal behaviour of my function on all supported python versions from 3.8 to 3.13.

**Comment by barneygale** [comment] 2024-10-13 18:35
> @barneygale So, what should I do in my library code? Should I dispatch behaviour by python version? Will the fix lands on 3.12.8 and buggy behaviour still presents in 3.12.0 to 3.12.7 inclusive? 🤔 I want equal behaviour of my function on all supported python versions from 3.8 to 3.13.

Untested, but I think this will work in all version:

```diff
diff --git a/src/aioftp/server.py b/src/aioftp/server.py
index 1830d78..d31f40a 100644
--- a/src/aioftp/server.py
+++ b/src/aioftp/server.py
@@ -1031,7 +1031,7 @@ class Server:
             else:
                 resolved_virtual_path /= part
         base_path = connection.user.base_path
-        real_path = base_path / resolved_virtual_path.relative_to("/")
+        real_path = base_path / str(resolved_virtual_path.relative_to("/"))
         # replace with `is_relative_to` check after 3.9+ requirements lands
         try:
             real_path.relative_to(base_path)
```

**Comment by hacscred** [comment] 2024-10-14 15:50
(Pathlib code is atrocious, btw. )

(I think for something as big as Python, getting rid of informal specifications would be a good idea, but I doubt the people in the project could ever accept it. 

The specification of many pathlib functions is completely underspecified.)

**Comment by barneygale** [comment] 2024-10-14 16:41
Please use https://discuss.python.org/ for general discussion. If you're looking to convince other people to do work on your behalf (e.g. improving the pathlib codebase) then I suggest you strike a more constructive note. If you're planning to put in your own issues and PRs I'd be happy to review.

**Comment by pohmelie** [comment] 2024-10-14 18:27
@barneygale yep, looks like this `str(...)` trick works, thank you!

**Comment by hacscred** [comment] 2024-10-14 18:48
> Please use https://discuss.python.org/ for general discussion. If you're looking to convince other people to do work on your behalf (e.g. improving the pathlib codebase) then I suggest you strike a more constructive note. If you're planning to put in your own issues and PRs I'd be happy to review.

I don't particularly care *that* much about Python. I looked at the code for this issue and I just wanted to leave my opinion on the Internet, which could be used by someone as an argument to fix pathlib. 

I was just being nice in sharing my (highly valuable) opinion. 

I don't particularly care if anyone does something with it. I certainly am not forcing anyone to do anything. Not sure where you got that idea. 

I am also not interested in discussion, because that would suggest I care about the opinion of others, which I don't, since I already am an expert. 

So, ignore my advice all you want, but that doesn't change the reality of the quality of that code. The code generator is even worse, for those interested. 

I will say it again: I am not asking for your opinion. I am giving you mine.

**Comment by barneygale** [comment] 2024-10-14 19:31
Wow what valuable feedback, thanks buddy! :P
