### ISSUE TITLE
Possible performance improvement in list repeating

### ISSUE THREAD

**Issue by thatbirdguythatuknownot** [python/cpython#92285] opened 2022-05-04 02:32 UTC
**Bug report**

List repeating can be optimized a bit by using the same algorithm/method as [`_PyBytes_Repeat`](https://github.com/python/cpython/blob/main/Objects/bytesobject.c#L3565-L3587):
```cmd
python_original -m timeit -s "l = [*range(100)]" "l * 100"
5000 loops, best of 5: 31.9 usec per loop

python_modified -m timeit -s "l = [*range(100)]" "l * 100"
5000 loops, best of 5: 25.9 usec per loop
```

**Your environment**

- CPython versions tested on: 3.11.0a7+
- Operating system and architecture: Windows 10 64-bit

**Comment by methane** [comment] 2022-05-04 05:11
Duplicate of #91247

**Closed as completed by methane** 2022-05-04 05:11 UTC
Labels: type-feature, performance
