### ISSUE TITLE
IDLE does not raise SyntaxWarning in 3.11 for BPO 43833

### ISSUE THREAD

**Issue by SectorCorruptor** [python/cpython#99567] opened 2022-11-18 04:22 UTC
This bug report has been added as Serihy asked me to:

> Please open a new issue for IDLE. Perhaps there is already an open issue for SyntaxWarning in IDLE.

The main problem is that as Pablo said:
 
> Unless I am missing something it should be 3.11 non-silent warning and 3.12 syntax error

However, on a Windows 11 device, the IDLE version of Python 3.11 still does not raise a non-silent warning.
When I tried this out:
```python
>>> [0x1for i in range(10)]
[31]
```
it does not raise the warning. This was run in interactive mode. 
Was the bugfix implemented only for shell mode? Or is there something in the interpreter that does not raise the `SyntaxWarning`?

# Environment

- CPython versions tested on: 3.11.0
- Operating system and architecture: Dell Inspiron 15, Windows 11, IDLE interactive

**Comment by rizwan342** [comment] 2022-11-18 05:05
Additional note: This does seem to work after saving it in a file, but not in the interactive mode when you just plain-try `[0x1for i in range(10)]` or assign it to a variable.

**Comment by rizwan342** [comment] 2022-11-18 05:07
And it doesn't seem to work when trying `print([0x1for i in range(10)])` in interactive mode.

**Comment by terryjreedy** [comment] 2022-11-29 04:06
In 3.12.0a2+, as of today, this is still just a warning.  Duplicate of #82005.  Thanks for the current example.

**Closed as completed by terryjreedy** 2022-11-29 04:06 UTC
Labels: type-bug, topic-IDLE

**Comment by rizwan342** [comment] 2022-11-30 03:56
@terryjreedy I think Python implemented this change intentionally as another way of detecting if you're in the interpreter.
