### ISSUE TITLE
basicblock_addop Assertion

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#109627] opened 2023-09-20 19:30 UTC
# Bug report

### Bug description:

I found the following error with the latest cpython 3.12 from git (4a0c118d6a4080efc538802f70ee79ce5c046e72), which I build myself with --with-pydebug enabled.

source:
```python
def get_namespace_uri():
    while element and something:
        try:
            return something
        except:
            pass
```

output (Python 3.12.0rc3+):
```python
python3: Python/flowgraph.c:114: basicblock_addop: Assertion `0 <= oparg && oparg < (1 << 30)' failed.
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-109630
* gh-109632

**Comment by JelleZijlstra** [comment] 2023-09-20 19:59
Confirmed on main, 3.11 is fine. cc @iritkatriel for `flowgraph.c`.

I'll try to bisect but not sure I'll have time to finish the bisect.

**Comment by iritkatriel** [comment] 2023-09-20 21:36
I'm looking. I don't think bisecting will help - the jump targets labels are new so you'll probably get to the large PR that added them.

**Comment by iritkatriel** [comment] 2023-09-20 22:29
In order to ensure that function exits have a line number, the compiler duplicates small exit blocks which (1) do not have a line number in any instruction and (2) have more than one predecessor. Since these blocks are jump targets (at least one predecessor reaches this block via a jump or exception), they need to have labels assigned to them. This was missing, and is added in the attached PR.

This begs the question "how did this ever work?"

The assertion that fails here is in a piece of code that transforms a conditional backwards jump into a conditional forward jump followed by an unconditional backward jump (because all backward jumps are unconditional). It is this code that asserted the label. In general the labels are no that useful this late in the compiler's process, they are mostly used in the code generation phase, before we have the CFG with a direct pointer from a jump to its target block.

The typical case of a small basic block is the "return None" of a function, and it is not a target of a conditional backward branch - this is what made this edge case rare.

**Comment by iritkatriel** [comment] 2023-09-20 22:30
@15r10nk - Thank you for finding this and for the tiny repro.

**Closed as completed** 2023-09-20 23:08 UTC
Labels: type-bug, release-blocker, 3.12, 3.13

**Comment by 15r10nk** [comment] 2023-09-21 18:57
@iritkatriel thank you for fixing this bug.
I would also like to mention that I automatically minimized the example with [pysource-minimize](https://github.com/15r10nk/pysource-minimize). maybe you will find that useful too.
