### ISSUE TITLE
some headers not compatible with C90

### ISSUE THREAD

**Issue by petere** [python/cpython#92889] opened 2022-05-17 18:59 UTC
Similar to [this issue](https://bugs.python.org/issue39615), some header files in v3.11.0b1 contain inline functions that are not compatible with C90 because they contain declarations after statements. This prevents `Python.h` from being usable in projects that use a pre-C99 compiler.

Will submit a pull request to show the details.

**Comment by erlend-aasland** [comment] 2022-05-17 19:24
Closing as duplicate of gh-92781 – please retarget your PR to that issue; also check if gh-92783 fixed the problem

**Closed as completed by erlend-aasland** 2022-05-17 19:24 UTC
Labels: type-bug
