### ISSUE TITLE
About whether to add `arch` attribute in `sys.impelemtation`

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#125639] opened 2024-10-17 08:30 UTC
### Proposal:

```python
# Add a code block here, if required
```

Actually, the discussion in the PR failed because no one decided whether to merge it or not (it seems that the only supporter is @zooba).
The newly added arch is used to get the current build architecture in Windows (it comes from python.props). What do you think?

### Has this already been discussed elsewhere?
https://github.com/python/cpython/pull/124582
https://discuss.python.org/t/regarding-whether-we-should-add-py-currentarch-or-py-archname-function/65191/17

**Comment by vstinner** [comment] 2024-10-17 08:38
This issue is a duplicate of issue gh-102536. Please continue the discussion her.

**Closed as not planned by vstinner** 2024-10-17 08:38 UTC
Labels: type-feature
