### ISSUE TITLE
Decimal(0)**-1 does not throw ZeroDivisionError

### ISSUE THREAD

**Issue by edwhiting** [python/cpython#123031] opened 2024-08-15 02:53 UTC
# Bug report

### Bug description:

When you raise a zero-value `Decimal` to a negative power, the result is `Decimal('Infinity')`.  This is wrong behaviour.
 - It is inconsistent with Python's built-in types, since
   - raising a zero-value `float` to a negative power fails with a `ZeroDivisionError`.
   - raising a zero-value `int` to a negative fails with a `ZeroDivisionError`. 
 - It is inconsistent with the result of the mathematically equivalent `1/Decimal(0)` which fails with a `ZeroDivisionError`.

eg:
```python
>>> from decimal import Decimal
>>> Decimal(0)**-1
Decimal('Infinity')

>>> 0.0**-1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: 0.0 cannot be raised to a negative power

>>> 0**-1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: 0.0 cannot be raised to a negative power

>>> 1/Decimal(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by skirpichev** [comment] 2024-08-15 05:19
Yes, this looks inconsistent, by I don't think it's a bug.

As specified in the [General Decimal Arithmetic Specification](https://speleotrove.com/decimal/decarith.html): ["If the left-hand operand is a zero, the result will be exact and will be infinite if the right-hand side is negative or 0 if the right-hand side is positive."](https://speleotrove.com/decimal/daops.html#refpower)  You should see reference to this specification in the module docs.

**Comment by skirpichev** [comment] 2024-08-15 05:20
Ah, and it's a duplicate of https://github.com/python/cpython/issues/66502.  I think this might be closed on same ground.

**Comment by terryjreedy** [comment] 2024-08-15 06:48
From @rhettinger, https://github.com/python/cpython/issues/66502#issuecomment-1093663514:
 >| the decimal module explicitly references that IBM spec.
   | I imagine that standard python arithmatic doesn't even attempt
   | to conform to this ibm spec.
That is exactly correct.

**Closed as not planned by terryjreedy** 2024-08-15 06:48 UTC
Labels: type-bug

**Comment by edwhiting** [comment] 2024-08-16 06:38
It's not an exact duplicate of [#66502](https://github.com/python/cpython/issues/66502), but if the spec says that the result should be infinity then I won't dispute it.

Nevertheless, there is an inconsistency when `getcontext().traps[DivisionByZero]` is `True` :

```python
>>> getcontext().traps[DivisionByZero] = True

>>> Decimal(1)/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]

>>> Decimal(0)**-1
Decimal('Infinity')
```

**Comment by skirpichev** [comment] 2024-08-16 07:16
Division behaviour is also part of the quoted above spec: ["if the divisor is zero then either the Division undefined condition is raised (if the dividend is zero) and the result is NaN, or the Division by zero condition is raised and the result is an Infinity with a sign which is the exclusive or of the signs of the operands."](https://speleotrove.com/decimal/daops.html#refdivide).  Note the difference wrt power: here exceptional condition is raised (and might be trapped).

That's odd wrt C case (if the implementation supports IEEE floating-point arithmetic).  In C you got 'inf' and FE_DIVBYZERO raised both for ``1./0.`` and ``pow(0., -1)``.
