### ISSUE TITLE
Wrong formatting of url in urlunsplit() function when used with _replace function to change scheme

### ISSUE THREAD

**Issue by MKCompu** [python/cpython#99901] opened 2022-11-30 14:54 UTC
# Bug report

```
from urllib.parse import urlparse
malformed = urlparse("8.8.8.8:1337")._replace(scheme='http').geturl()
print(malformed)
```
This prints ''http:///8.8.8.8:1337", but should have printed "http://8.8.8.8:1337".
Note the three slashes.
The reason is that the urlunsplit function in Lib/urllib/parse.py checks whether the original url contains a slash, which is not the case, adds a slash and then adds two more slashes.

# Your environment
- CPython versions tested on: 3.10.5

### Linked PRs
* gh-99910

**Comment by WolframAlph** [comment] 2022-11-30 15:22
```py
urlparse("8.8.8.8:1337", scheme='http').geturl()
```
will also produce `http:///8.8.8.8:1337`
Can I work on patch?

**Comment by serhiy-storchaka** [comment] 2023-12-28 13:12
I think that the issue is not in `urlunparse()`, but in `urlparse()`.

```
>>> urllib.parse.urlparse('8.8.8.8:1337', scheme='http')
ParseResult(scheme='http', netloc='', path='8.8.8.8:1337', params='', query='', fragment='')
```
'8.8.8.8:1337' is expected to be a netlock, not path.

Or maybe it is incorrectly used.

**Comment by WolframAlph** [comment] 2023-12-28 13:31
Actually, it is explicitly mentioned in the [docs](https://docs.python.org/3.12/library/urllib.parse.html?highlight=urlparse#urllib.parse.urlparse). 
>Following the syntax specifications in [RFC 1808](https://datatracker.ietf.org/doc/html/rfc1808.html), urlparse recognizes a netloc only if it is properly introduced by ‘//’. Otherwise the input is presumed to be a relative URL and thus to start with a path component.

And indeed it works if you prepend `//`
```
>>> urlparse('//8.8.8.8:1337', scheme='http')
ParseResult(scheme='http', netloc='8.8.8.8:1337', path='', params='', query='', fragment='')
```

So the question is if we want to handle cases when netloc is empty when `urlunparse` is used to recostruct URI.

**Comment by serhiy-storchaka** [comment] 2023-12-29 11:16
The question is how to handle URLs with empty netloc and relative path.

1. `scheme:path` -- omit netloc.
2. `scheme:///path` -- make the path absolute.
3. Error.

Option 1 is used for schemes that do not use netloc, option 2 is currently used for schemes that use netloc (e.g. `http`). Error is never produced. In any case `scheme://path` is not correct result.

So I think that this issue should be closed as "not a bug". The question about empty netloc and relative path is discussed in #85110.

**Closed as not planned** 2023-12-29 13:47 UTC
Labels: type-bug, stdlib

**Comment by VrindavanSanap** [comment] 2024-08-20 04:43
When is this going to get fixed?

**Comment by serhiy-storchaka** [comment] 2024-08-20 05:05
See #85110.
