### ISSUE TITLE
time.sleep(100) sometimes doesn't return after 100 seconds on Windows

### ISSUE THREAD

**Issue by yurivict** [python/cpython#106523] opened 2023-07-07 16:36 UTC
# Bug report

This code:
```
import time

time.sleep(100) 
```

returns after 100 seconds in most cases, but every once in a while it doesn't exit and stays blocked forever.
Curiously, hitting "Enter" on that process causes this call to exit.

I came to this point by troubleshooing the problem that the keep-presence program hangs at [this](https://github.com/carrot69/keep-presence/blob/master/src/keep-presence.py#L173) point.

# Your environment

- CPython versions tested on: 3.11
- Operating system and architecture: MS Windows 10 Enterprise

**Comment by eryksun** [comment] 2023-07-07 17:25
Are you running this script via "python.exe", attached to a console session (either "conhost.exe" or "openconsole.exe" under Windows Terminal)? If so, does Task Manager show the Python process is still running?

If Python has actually exited, then it's likely that you've clicked or dragged the mouse in the console window/tab. A console session can have quick-edit mode enabled (i.e. the `ENABLE_QUICK_EDIT_MODE` flag is set in the console mode), in which case clicking or dragging the mouse on the window/tab enables select mode, which pauses all console input/output (e.g. reading keyboard/mouse input or writing a prompt). In a classic console session (conhost.exe), the window title also changes to begin with "Select" (of course, localized to the user's preferred UI language) when select mode is enabled. Pressing enter copies the selection to the clipboard and exits select mode. Then normal console input/output resumes.

**Comment by yurivict** [comment] 2023-07-07 17:29
@eryksun 

No, The Python process itself didn't exit. Only the ```time.sleep(100)``` call didn't  exit on time.
Once Enter is clicked - it exits the above call, and proceeds normally.

**Comment by eryksun** [comment] 2023-07-07 17:45
To be clear, you confirmed that after 100 seconds the "python.exe" process is still listed as running in Task Manager, indefinitely until enter is pressed?

**Comment by yurivict** [comment] 2023-07-07 18:05
Yes, after 100 seconds the python.exe is still listed as running.
Only hitting Enter causes it to proceed, not expiration of the 100 seconds sleep timeout.

**Comment by eryksun** [comment] 2023-07-07 18:32
To rule out interference from `PYTHON*` environment variables, registry settings, and ".pth" files from third-party packages, please run your script with the `-I` and `-S` command line options, e.g. `python.exe -IS "path\to\script.py"`.

**Comment by yurivict** [comment] 2023-07-07 21:25
I confirm:
This script:
```
from datetime import datetime
import time

def get_now_timestamp():
    now = datetime.now()
    return now.strftime("%H:%M:%S")

while (True):
    print(get_now_timestamp(), "time")
    time.sleep(5)
```

stops printing time after a while when run with ```-IS``` flags.

**Comment by yurivict** [comment] 2023-07-07 21:27
This is a very severe problem, because is would undermine functionality of any Python software that uses ```time.sleep()``` on Windows.

**Comment by zware** [comment] 2023-07-07 21:34
Agreed, and as yours is the first report of it I'm inclined to believe it has something to do with your system configuration.  What exact version of Python and Windows are you using?  Can you reproduce it using a different version or different machine?  How long does the process run before it hangs?

**Comment by zware** [comment] 2023-07-07 22:18
FTR, I've been running your test script on a Windows 11 machine since roughly 21:28 UTC (50 minutes ago as of this writing) with no issues other than the printed time drifting forward by two seconds.

**Comment by yurivict** [comment] 2023-07-07 22:20
My machine is Windows 10.

**Comment by yurivict** [comment] 2023-07-07 22:20
Windows version: Windows 10 Enterprise (corporate issued)
Python version: 3.11

There seems to be nothing special about this Windows system - it was imaged by the company.


I don't use Windows at all otherwise, so I don't have any other Windows systems.

**Comment by zware** [comment] 2023-07-07 22:48
What patch version of 3.11?  Can you try another version of Python on the same machine, particularly 3.10?  The implementation of `time.sleep` changed significantly in 3.11.

**Comment by yurivict** [comment] 2023-07-07 22:59
Python 3.11.2

**Comment by yurivict** [comment] 2023-07-07 23:33
[This page](https://www.python.org/downloads/release/python-31012/) says that binary Python-3.10 installer isn't distributed any more, so there is no obvious easy way to install it on Windows any more.

**Comment by eryksun** [comment] 2023-07-08 00:06
Here's a direct link to the x64 installer for 3.10.11: https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe. Run the script using the py launcher with the option `-3.10` in order to ensure that it runs in Python 3.10 -- e.g. `py -3.10 -IS "path\to\script.py"`.

**Comment by SonOfLilit** [comment] 2023-07-08 11:01
Sorry, can't look at it myself as I don't have any Windows boxes around. But.

This feels so suspiciously like a manifestation of this known issue with Windows: https://twitter.com/SwiftOnSecurity/status/1677511371087396867

@eryksun already mentioned it, but I'm not sure a manifestation of this would necessarily include the process already being dead. Maybe add prints right before and after the sleep to make sure it's the sleep that's stuck and not I/O?

Or it could be somehow related to accessibility (weird things happen on Windows if you press Shift many times in a row, as far as I recall).

Also, Imagine how much easier this would be to troubleshoot if we found it happens with sleep(5) and not just sleep(100). What's the minimal sleep where this reproduces? I'd maybe try a binary search to find that.

**Comment by tim-one** [comment] 2023-07-08 18:27
I think this original line has spawned confusion:

> Curiously, hitting "Enter" on that process causes this call to exit.

The OP never said anything about the Python process exiting. "This call to exit" referred to `time.sleep()` waking up.

I have tons of experience using `sleep()` on Windows (including Windows 10), and the only thing like this I've ever experienced is, as already mentioned but not addressed by the OP, the console Window being stuck in "select" mode. It's _very_ easy for that to happen by accident. For example, click anywhere inside a console window to bring it to the foreground, and the slightest finger tremor can get interpreted as an attempt to select text. In fact, that's happened to me twice already today.

To the OP: next time, don't hit ENTER. If this is the problem, it should work just as well to press and release the ESCape key.  It's not your program waiting for input, it's convincing the console window that you don't want select mode. So long as it is in select mode, your program will actually hang not in `time.sleep()`, but in the next attempt to display output to the console window. I figure you're _assuming_ it's hung in `time.sleep()` because the following attempt to `print()` doesn't display output. And it won't/can't until the console window is out of select mode.

One way to confirm that: change your program to append output to a file instead of printing to the console window.  Like

```python
    with open("somefile.txt", "a") as f:
        print(get_now_timestamp(), "time", file=f)
```

My bet it that it will never appear to "hang" then (unless you're still also printing to  a console window and getting that into select mode by mistake).

**Comment by eryksun** [comment] 2023-07-08 19:15
The only way the console's select mode can make a console app hang is by blocking synchronous console API calls such as `ReadConsoleW()` and `WriteConsoleW()`, and only if those calls occur on the UI thread (usually the main thread for a simple console script).  There are no console API calls either during or after `time.sleep(100)` in the example script -- at least there shouldn't be any.

I asked to run with the `-I` and `-S` options to rule out any third-party Python code that might change the runtime environment in a way that ends up calling console API functions unexpectedly. That was ruled out, but some other third-party code could be affecting the process, such as an injected DLL, so to move forward with a diagnosis I'll need a memory dump file for the "python.exe" process when it's stuck in `time.sleep()`. Please do this just for the simple two-line script after the `time.sleep()` call should have returned. Please do not add any `print()` statements or other I/O calls, which would just confuse the issue. Task Manager has an option to create a memory dump file of a process on the right-click properties menu.

---

FYI, the linked twitter thread is technically confused. "cmd.exe" is a CLI shell that uses standard I/O, just like "python.exe" implements a REPL that uses standard I/O. "cmd.exe" is not a terminal. The console's quick-edit mode -- which is what makes it so easy to accidentally enter select mode -- has nothing to do with "cmd.exe". It's a property of the console session to which "cmd.exe" and "python.exe" are attached. Each console session is hosted by an instance of either "conhost.exe" or "openconsole.exe". In classic console mode, the host provides a builtin terminal interface. In pseudoconsole mode, the console host is a headless background process that implements everything about the console API and session (e.g. title, screen buffers, input buffer, active code pages, and events sent to attached process groups such as `CTRL_C_EVENT`), but the user interface itself is implemented by another process. For example, Windows Terminal allocates a pseudoconsole session (i.e. instance of "openconsole.exe") for each tab in its user interface.

**Comment by tim-one** [comment] 2023-07-08 19:30
> There are no console API calls either during or after `time.sleep(100)` in the example script -- at least there shouldn't be any.


@eryksun, what do you think Python's `print()` does? it's trivial to reproduce the OP's complaint by running the sample script in a console window (here `cmd.exe`):

```none
C:\MyPy>type sleeper.py
from datetime import datetime
import time

def get_now_timestamp():
    now = datetime.now()
    return now.strftime("%H:%M:%S")

while (True):
    print(get_now_timestamp(), "time")
    time.sleep(5)

C:\MyPy>py sleeper.py
14:25:28 time
14:25:33 time
14:25:38 time
```

Now just select some text in the window. Output stops. Hit, e.g., ESC, and it resumes:

```
14:25:43 time
14:25:56 time
14:26:01 time
14:26:06 time
...
```

This burns me essentially every day of my life, using no explicit Windows API calls of any kind - just whatever CPython happens to invoke under the covers.

**Comment by eryksun** [comment] 2023-07-08 20:38
I'm only concerned with the original report in which a script that simply calls `time.sleep(100)` hangs while the "python.exe" process is still running. That should not happen with a vanilla "python.exe" process, regardless of the console being in select mode.

> @eryksun, what do you think Python's `print()` does?

By default, if `sys.stdin` is console input, then builtin `print()` writes to the console via `WriteConsoleW()`. This call blocks when the console is in select mode. Specifically, in Windows 8+, `WriteConsoleW()` is implemented as an IOCTL via the system call `NtDeviceIoControlFile()`, which is synchronous because "\\Device\\ConDrv\\Output" is opened in synchronous mode. Thus the system has to wait for the device driver ("condrv.sys") to complete the I/O request. On the other end of the connection, the console host process (i.e. "conhost.exe" or "openconsole.exe") has "\\Device\\ConDrv\\Server" opened for sending and receiving I/O requests to/from its client processes such as "cmd.exe" and "python.exe". It reads the IOCTL via its own `NtDeviceControlFile()` system call, and it carries out the request to write the given text into the active screen buffer. However, if select mode is enabled in the classic console window, it can't actually write to the screen buffer and complete the I/O request until select mode ends. Meanwhile the `NtDeviceIoControlFile()` call in the client is blocked while waiting for the I/O request to complete.

**Comment by tim-one** [comment] 2023-07-08 21:39
> I'm only concerned with the original report in which a script that simply calls `time.sleep(100)` hangs while the "python.exe" process is still running.

The self-contained sample script the OP posted later has its sleep followed by a print, and _so does_ the original report in the Github code it links to:

> I came to this point by troubleshooing the problem that the keep-presence program hangs at [this](https://github.com/carrot69/keep-presence/blob/master/src/keep-presence.py#L173) point.

I've seen nothing to confirm that it's actually the sleep that's hanging rather than the print. Instead, as I said, I figure the OP _assumes_ it's the sleep that's not waking up just because they're not seeing the output they expect to see.

BTW, I know the original report says this code hangs at times:

```python
import time
time.sleep(100) 
```

but I simply don't believe it. There's no evidence that they actually ran that - and only that - exact code.  When they later added an actual script to demonstrate the problem, they added code beyond that.

So that's for the OP to clarify: is it true that code that _only_ calls `time.sleep(100)` (no prints) seemingly hangs forever at times? Specifically, the two-line program just above?

That's what Eryk is digging into. I think it's more likely that you leaped to a conclusion.

**Comment by zware** [comment] 2023-07-11 21:08
I accidentally left the reproduction script from https://github.com/python/cpython/issues/106523#issuecomment-1626150756 running over the weekend in both a Windows Terminal and `cmd.exe` window, and neither one hung.  Given the inability to reproduce (aside from by entering "select mode" in `cmd.exe`, which is unrelated to  Python), the lack of other reports, and no apparent cause for the reported symptom in the code, I'm going to go ahead and close this.  If anyone can reproduce the issue (without "select mode") it can be reopened.

**Closed as not planned by zware** 2023-07-11 21:08 UTC
Labels: type-bug, OS-windows, 3.11

**Comment by eryksun** [comment] 2023-07-11 22:18
You meant "conhost.exe window" and "select mode in conhost.exe". "cmd.exe" is a CLI shell. It creates no window(s), implements no window message loop, and its command-line shell interface just consumes console API functions such as `ReadConsoleW()` and `WriteConsoleW()`, much like Python's own REPL shell.
