### ISSUE TITLE
Undocumented behavior of sleep functions and asyncio delayed execution

### ISSUE THREAD

**Issue by 7d43ca6d-5798-4cf3-b97d-2a9a8e478a07** [python/cpython#87987] opened 2021-04-12 22:11 UTC
BPO | [43821](https://bugs.python.org/issue43821)
--- | :---
Nosy | @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-12.22:11:20.324>
labels = ['type-bug', '3.8', '3.9', '3.10', 'library', 'docs']
title = 'Undocumented behavior of sleep functions and asyncio delayed execution'
updated_at = <Date 2021-04-16.20:27:09.056>
user = 'https://bugs.python.org/JosefHavrnek'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-16.20:27:09.056>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)']
creation = <Date 2021-04-12.22:11:20.324>
creator = 'Josef Havr\xc3\xa1nek'
dependencies = []
files = []
hgrepos = []
issue_num = 43821
keywords = []
message_count = 1.0
messages = ['390914']
nosy_count = 4.0
nosy_names = ['asvetlov', 'docs@python', 'yselivanov', 'Josef Havr\xc3\xa1nek']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43821'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment] 2022-10-02 14:35
First `time.sleep` should not used in asyncio. You should use `asyncio.sleep`. The behavior of `asyncio.sleep` is documented to [suspend the task](https://docs.python.org/3/library/asyncio-task.html?highlight=asyncio%20sleep#asyncio.sleep) not `hibernate` the computer. 

`loop.call_later` is used to execute callback after some time relative to loop time and `loop.call_at` is used to execute a callback at specified absolute time. The thing to remember here is that all of this is relative to `loop.time` which is a monotonic clock not RTC

Closing as it is not a bug. The behavior is documented at https://docs.python.org/3/library/asyncio-eventloop.html?highlight=call_later#scheduling-delayed-callbacks. You ask these questions on https://discuss.python.org/c/users/7

**Closed as not planned by kumaraditya303** 2022-10-02 14:35 UTC
Labels: type-bug, docs, stdlib, 3.10, 3.9 (EOL), 3.8 (EOL)
