### ISSUE TITLE
Class constructor variable define throws an infinit loop 

### ISSUE THREAD

**Issue by SerbanTudor04** [python/cpython#112149] opened 2023-11-16 11:52 UTC
# Bug report

### Bug description:

```python
# basically if i create a class and define a variable in constructor without assigning any value it will stay in a infinit loop
class Foo:
    def __init__(self) -> None:
        self.bar

    def printHello(self):
        print('Hello')


class_var=Foo() # here it will stay forever :)))
class_var.printHello()  

# i encounter this bug when i forget to assign a value in constructor for a variable

```

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment] 2023-11-16 14:32
I cannot reproduce this. On Windows, I get `AttributeError: 'Foo' object has no attribute 'bar'`.

**Comment by Fidget-Spinner** [comment] 2023-11-17 09:30
I can't reproduce it on Ubuntu either.

**Comment by ericvsmith** [comment] 2023-11-17 13:49
@SerbanTudor04 I'm going to close this issue, since it can't be reproduced. If you can give more information, we can reopen it.

**Closed as not planned by ericvsmith** 2023-11-17 13:49 UTC
Labels: type-bug, pending
