### ISSUE TITLE
Incorrect hexadecimal to decimal conversion in enum example

### ISSUE THREAD

**Issue by array93** [python/cpython#118443] opened 2024-04-30 17:25 UTC
# Documentation

Section describing `__new__(cls, *args, **kwds)` [says](https://docs.python.org/3/library/enum.html#enum.Enum.__new__):
> results in the call `int('1a', 16)` and a value of `17` for the member.

While `class int(x, base=10)` [suggests](https://docs.python.org/3/library/functions.html#int) the value would be `26` since `1A` hex is `26` decimal.

Also wouldn't the enum in the example need to inherit from `int` to get its `__new__` implementation? I'm confused about the mixed-in.

**Comment by eendebakpt** [comment] 2024-04-30 23:24
@array93 Thanks for reporting, you are right the documentation was not correct. The issue was recently fixed in https://github.com/python/cpython/pull/118311. That change will take some time though before it ends up in the official documentation.

**Comment by hugovk** [comment] 2024-05-01 06:01
Thanks both, let's mark this as a duplicate of https://github.com/python/cpython/issues/118310.

**Closed as not planned by hugovk** 2024-05-01 06:01 UTC
Labels: docs
