### ISSUE TITLE
ImportError: _ssl.so: undefined symbol: _PyModule_Add

### ISSUE THREAD

**Issue by 0x2b3bfa0** [python/cpython#108525] opened 2023-08-26 23:07 UTC
# Bug report

## Environment

```console
$ uname
Linux
$ python --version{,}
Python 3.11.4 (tags/v3.11.4:d2340ef257, Aug 26 2023, 22:42:28) [GCC 12.2.0]
```

## Description

Importing the `ssl` shared library from a Python 3.11.5 build from a Python 3.11.4 binary produces an `ImportError` due to an undefined symbol. Isn't CPython's ABI supposed to be fully compatible between [patch](https://semver.org/) releases?

> [_CPython’s Application Binary Interface (ABI) is forward- and backwards-compatible across a minor release_](https://docs.python.org/3/c-api/stable.html#stable-abi-platform).

## Example

```dockerfile
FROM debian

RUN apt update\
 && apt install --yes build-essential git libssl-dev zlib1g-dev

RUN git clone --branch v3.11.4 https://github.com/python/cpython 3.11.4\
 && cd 3.11.4 && ./configure && make

RUN git clone --branch v3.11.5 https://github.com/python/cpython 3.11.5\
 && cd 3.11.5 && ./configure && make

RUN mv 3.11.5/build/lib.linux-x86_64-3.11/_ssl.cpython-311-x86_64-linux-gnu.so\
       3.11.4/build/lib.linux-x86_64-3.11/_ssl.cpython-311-x86_64-linux-gnu.so

RUN 3.11.4/python -m ssl
```

## Error

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "//3.11.2/Lib/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: //3.11.2/build/lib.linux-x86_64-3.11/_ssl.cpython-311-x86_64-linux-gnu.so: undefined symbol: _PyModule_Add
```

## Observations

It looks like fced79f91e186dd6a608221ad7cee2eeb443c40d is the breaking commit, as per `git bisect` results.

### Linked PRs
* gh-108582

**Comment by hansegucker** [comment] 2023-08-27 20:24
I also observed the issue on my system.

**Comment by CorvinM** [comment] 2023-08-27 23:53
Also able to reproduce between 3.11 branch and 3.11.4, looks like #106863 broke the ABI

**Comment by sunmy2019** [comment] 2023-08-28 04:02
@serhiy-storchaka as the commit author

**Comment by serhiy-storchaka** [comment] 2023-08-28 05:05
I don't think this warranty extends to the private API.

> Names prefixed by an underscore, such as `_Py_InternalState`, are private API that can change without notice even in patch releases.

If you only use the public C API in your extension, you can expect forward- and backwards-compatibinility.

**Comment by Templarrr** [comment] 2023-08-31 13:06
I see the same error locally in poetry after my Ubuntu upgraded 3.11.4 -> 3.11.5. Any advice how this can be mitigated/fixed? It doesn't look like I can downgrade local python back to 3.11.4 - deadsnakes ppa don't list 3.11.4 anymore

**Comment by LostInDarkMath** [comment] 2023-08-31 13:13
@Templarrr I had the same issue and fixed it by updating poetry to the latest version.

**Comment by erlend-aasland** [comment] 2023-08-31 13:15
cc. RM @pablogsal

**Comment by Templarrr** [comment] 2023-08-31 13:18
@LostInDarkMath thank you! Seems to be the solution

**Comment by CorvinM** [comment] 2023-08-31 16:12
> The reproducer looks contrived. In what situation would pieces of CPython get mixed up like this? Is Ubuntu's `_ssl` module not built together with the interpreter?

A faulty install or packaging script could easily cause this (but wouldn't be noticed in most cases, since they are usually ABI compatible) because the file paths are named identically (I.e., specific to 3.11, not 3.11.5).

**Comment by 0x2b3bfa0** [comment] 2023-09-01 23:35
> _A faulty install or packaging script could easily cause this [...] because the file paths are named identically (i.e., specific to 3.11, not 3.11.5)_

This. ☝🏼 💯

**Comment by zvolsky** [comment] 2023-09-14 13:59
> @LostInDarkMath: I had the same issue and fixed it by updating poetry to the latest version.

My `poetry --version` was 1.6.1.
`poetry self update` exactly as other poetry commands has failed with this issue.
I decided to "update" via `curl -sSL https://install.python-poetry.org | python3 -`, i.e. reinstall,
the `poetry --version` is now again 1.6.1.
And Poetry works again.
(Debian Testing)

**Comment by dusty-phillips** [comment] 2023-10-06 17:56
I encountered this issue in a python3.11-slim Dockerfile even after updating poetry. 

In my case, the issue was that the Dockerfile in question was installing the python3-dev apt package, which was providing 3.11.2 headers. I was able to remove this dependency without any repercussions.

Was devilishly hard to track down so thought I'd share in case it helps someone else.

**Comment by cove9988** [comment] 2023-11-14 10:41
Yes, the old poetry 1.6.1 is not working well with python 3.11
if you `curl -sSL https://install.python-poetry.org | python3 -` upgrade to 1.7.1, It works well.

**Comment by vstinner** [comment] 2023-12-02 00:50
> Importing the ssl shared library from a Python 3.11.5 build from a Python 3.11.4 binary produces an ImportError due to an undefined symbol.

Usually, a Python binary loads its "own" Python stdlib. I don't think that we want to support using a newer/older Python with newer/older stdlib. You should use the exact same version for the Python binary and its stdlib.

What can be done is to enhance error reporting. For example, but storing the version in stdlib C extensions and raise an error if there is version mismatch.

Today, you get an ImportError because of a missing symbol. But tomorrow, you might get a crash because of subtle different behavior :-(

**Comment by vstinner** [comment] 2024-03-18 11:04
I close the issue. I don't think that we want to support this use case.

**Closed as not planned by vstinner** 2024-03-18 11:04 UTC
Labels: type-bug, extension-modules, topic-C-API
