### ISSUE TITLE
Unit tests on Mac should fall back to use X if DISPLAY is set

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#123155] opened 2024-08-19 18:52 UTC
# Bug report

### Bug description:

When running the test suite on my Mac, it always complains I don't have an OS X gui process running. I don't know how to remedy that, but I do know that I have XQuartz running, as the `DISPLAY` environment variable is set. The test suite should fall back to using X for `tkinter` and `ttk` unit tests if available.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-123156

**Comment by smontanaro** [comment] 2024-08-19 19:02
Changed the title. XQuartz isn't really required. Any valid `DISPLAY` setting should be fine.

**Comment by ronaldoussoren** [comment] 2024-08-19 19:40
Some questions:

* What version of macOS do you use?

* How did you install Tcl/Tk?

* How do you run the tests?

**Comment by ronaldoussoren** [comment] 2024-08-21 08:40
This is a duplicate of #61698.

**Closed as not planned** 2024-08-21 08:40 UTC
Labels: type-bug, OS-mac

**Comment by smontanaro** [comment] 2024-08-21 18:32
I'm beginning to think that my superpower is proposing half-baked ideas which motivate other people to actually develop/produce/confirm the correct solution to the problem. ;-)

I trust that fix you had me check will find its way into main and 3.13?
