### ISSUE TITLE
Json encode from __repr__, __str__ or __serialize__ when available

### ISSUE THREAD

**Issue by pmithrandir** [python/cpython#114285] opened 2024-01-19 09:45 UTC
Hello,

When I need to json encode a new object or an Enum , I need to either extend str, or build a json decoder to make it compatible with the default json encoder.

When using third parties lib, it might create some difficulties as implementing string is not an option, and the dumps method is not reachable.

If I wanted to do that in java, I would implement in my class a serialize method that would be called by json serializer.

Would it be possible, in the encoder, to allow the usage of either a __serialize__(self) method, or to directly use __repr__ or __str__ when the object after all other option failed.

https://github.com/python/cpython/blob/a34e4db28a98904f6c9976675ed7121ed61edabe/Lib/json/encoder.py#L192

That will give the final developer a reliable way to explain the json encoder how to interpret the object and serialize it.

**Comment by sobolevn** [comment] 2024-01-19 12:20
Please, start a new discussion on https://discuss.python.org/c/ideas/6
But, I guess this was already discussed.

You can do that if you want:
1. Create your own https://docs.python.org/3/library/json.html#json.JSONEncoder and `Decoder` if you want
2. Make them call `__json_encode__` and `__json_decode__` magic method that you can define on any objects (or even monkey-patch them to existing ones)
3. Done! :)

I will close this for now, you can follow up this issue with the discussion link! 👍

**Closed as not planned by sobolevn** 2024-01-19 12:20 UTC

**Comment by ronaldoussoren** [comment] 2024-01-19 12:22
This is a duplicate of #71549.  That issue proposes a different method (``__json__`` instead of ``__serialize__``). 

The other issue also doesn't propose a fallback to ``__repr__`` or ``__str__``, but IMHO that would be a bug magnet.
