### ISSUE TITLE
No tests for termios module

### ISSUE THREAD

**Issue by ronaldoussoren** [python/cpython#97689] opened 2022-09-30 19:27 UTC
# Feature or enhancement

While working on a PR for #97001 I noticed that there are no tests for the termios extension.  Bits of termios are used in some other tests, but there are no explicit tests of the extension itself.

**Comment by benthorner** [comment] 2022-10-01 07:01
@ronaldoussoren is this a duplicate of https://github.com/python/cpython/issues/81002?

**Comment by ronaldoussoren** [comment] 2022-10-01 07:48
It is a duplicate.  Thanks !

**Closed as not planned** 2022-10-01 07:48 UTC
Labels: type-feature, tests
