### ISSUE TITLE
[macOS] ``test_builtin.PtyTests.test_input_tty`` hangs if ``rlcompleter`` is imported

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#116402] opened 2024-03-06 06:08 UTC
# Bug report

### Bug description:

```python
./python.exe -m test
...many lines
0:05:14 load avg: 4.04 [ 87/472] test_bool
0:05:14 load avg: 4.04 [ 88/472] test_buffer
0:05:15 load avg: 3.80 [ 89/472] test_bufio
0:05:16 load avg: 3.80 [ 90/472] test_builtin
/Users/admin/Projects/cpython/Lib/pty.py:95: DeprecationWarning: This process (pid=47600) is multi-threaded, use of forkpty() may lead to deadlocks in the child.
  pid, fd = os.forkpty()
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-122447
* gh-122472

**Comment by Eclips4** [comment] 2024-03-06 06:23
Reduced amount of tests to trigger the hang:
```python
 ./python.exe -m test test___all__ test_builtin 
Using random seed: 2282378935
0:00:00 load avg: 1.58 Run 2 tests sequentially
0:00:00 load avg: 1.58 [1/2] test___all__
0:00:00 load avg: 1.58 [2/2] test_builtin
^C

== Tests result: INTERRUPTED ==

1 test omitted:
    test_builtin

1 test OK.

Test suite interrupted by signal SIGINT.

Total duration: 18.0 sec
Total tests: run=1
Total test files: run=1/2
Result: INTERRUPTED
```

**Comment by sobolevn** [comment] 2024-03-06 07:50
Minimal number of tests:

```
test.test___all__.AllTest.test_all
test.test_builtin.PtyTests.test_input_tty
```

It gets stuck here: https://github.com/python/cpython/blob/d2f1b0eb4956b4923f111c7c740ba7ab25f3312d/Lib/test/test_builtin.py#L2282

**Comment by sobolevn** [comment] 2024-03-06 07:54
Since `test_all` actually imports all modules and executes them, the problem can be in any module :(

**Comment by sobolevn** [comment] 2024-03-06 08:04
I think that it would be easier to bisect when running only two test cases at least!

**Comment by Eclips4** [comment] 2024-03-06 08:50
Seems like problem in this import:
```python
try:
    import readline
except ImportError:
    _readline_available = False
else:
    readline.set_completer(Completer().complete)
    # Release references early at shutdown (the readline module's
    # contents are quasi-immortal, and the completer function holds a
    # reference to globals).
    atexit.register(lambda: readline.set_completer(None))
    _readline_available = True
```

**Comment by vstinner** [comment] 2024-03-06 08:55
If a test fails with a completer callback is set, you can try to:

```
completer = readline.get_completer()
try:
    readline.set_completer(None)
   ... # run the test
finally:
    readline.set_completer(completer)
```

But only do it if readline is in `sys.modules`.

**Comment by serhiy-storchaka** [comment] 2024-03-06 10:51
`test.test_builtin.PtyTests.test_input_tty` can also be affected by other tests that import `rlcompleter`, and importing `rlcompleter` can also affect other tests. There may be several old issues which will be solved when solve this issue.

I would add a code that restores (or just resets) the completer in `Lib/test/libregrtest/save_env.py`.

**Comment by vstinner** [comment] 2024-03-06 11:08
> readline.set_completer(None)

If you fully want to control the TTY and not be affected by previous tests, another approach is to spawn a new process.

**Comment by ronaldoussoren** [comment] 2024-03-06 15:53
This might be a duplicate of https://github.com/python/cpython/issues/89050

**Comment by JelleZijlstra** [comment] 2024-05-31 16:27
This test hangs for me on a Mac even without running any other test:

```
% ./python.exe -m test test_builtin -m test_input_tty -v
== CPython 3.14.0a0 (heads/pep649-inspect:ad8c51c157, May 31 2024, 08:27:05) [Clang 14.0.0 (clang-1400.0.29.202)]
== macOS-13.4.1-arm64-arm-64bit-Mach-O little-endian
== Python build: debug
== cwd: /Users/jelle/py/cpython/build/test_python_worker_85845æ
== CPU count: 8
== encodings: locale=UTF-8 FS=utf-8
== resources: all test resources are disabled, use -u option to unskip tests

Using random seed: 1737450533
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 1.34 Run 1 test sequentially
0:00:00 load avg: 1.34 [1/1] test_builtin
test_input_tty (test.test_builtin.PtyTests.test_input_tty) ... ^C

== Tests result: INTERRUPTED ==
```

**Comment by JelleZijlstra** [comment] 2024-05-31 16:40
What I'm seeing is related to #112950, which made it so `pdb` unconditionally imports `rlcompleter`; `test_builtin` imports `doctest` which imports `pdb` which now imports `rlcompleter`. However, obviously there are many code paths that could cause `rlcompleter` to be imported when this test runs.

I tried locally to temporarily set the readline completer to None as @vstinner suggests above, but the test still hangs. I haven't looked more deeply to figure out what's going wrong.

**Comment by AlexWaygood** [comment] 2024-05-31 17:03
If I comment out the import of `readline` in `rlcompleter.py`, the test in `test_builtin` no longer hangs. But getting rid of the `readline.set_completer()` call in `rlcompleter.py` is not sufficient.

I see that many similar tests in `test_builtin.py` are simply skipped if `"readline"` is present in `sys.modules`:

https://github.com/python/cpython/blob/64ff1e217d963b48140326e8b63c62f4b306f4a0/Lib/test/test_builtin.py#L2400

https://github.com/python/cpython/blob/64ff1e217d963b48140326e8b63c62f4b306f4a0/Lib/test/test_builtin.py#L2405

https://github.com/python/cpython/blob/64ff1e217d963b48140326e8b63c62f4b306f4a0/Lib/test/test_builtin.py#L2415

We could consider doing something similar here, though obviously it would be nice if the test could still be run even if `readline` is present in `sys.modules`.

**Closed as completed** 2024-07-31 04:37 UTC
Labels: type-bug, tests, 3.13, 3.14
