### ISSUE TITLE
[dataclasses] [typing] Dataclass Protocol

### ISSUE THREAD

**Issue by randolf-scholz** [python/cpython#102395] opened 2023-03-03 11:24 UTC
# Feature or enhancement

Currently, the `dataclasses` module only provides the `dataclasses.is_dataclass` function to check whether a class is in fact a dataclass.

https://github.com/python/cpython/blob/0a7936a38f0bab1619ee9fe257880a51c9d839d5/Lib/dataclasses.py#L1258-L1267

# Pitch

Create a `Dataclass(Protocol)`. Classes satisfying the Protocol should be compatible with dataclass methods such as `dataclasses.astuple`, `dataclasses.asdict`, `dataclasses.fields` and `dataclasses.replace`

It seems that currently the following is possible sufficient:

```python
@runtime_checkable
class Dataclass(Protocol):
    r"""Protocol for dataclasses."""

    @property
    def __dataclass_fields__(self) -> Mapping[str, Field]:
        r"""Return the fields of the dataclass."""
```

Remarks:

- Additionally one might want to add a `MutableDataclass`,  with `__setattr__` and `__delattr__`.
- As a side benefit, the `dataclasses.is_dataclass` can be equipped with a `Typeguard` for `Dataclass`-Protocol (`issubclass(cls, Dataclass)` currently won't work because only methods are checked)

**Comment by AlexWaygood** [comment] 2023-05-10 17:44
Closing as a duplicate of #102699, which is a newer issue but has more discussion attached to it.

**Closed as not planned by AlexWaygood** 2023-05-10 17:44 UTC
Labels: type-feature, stdlib
