### ISSUE TITLE
`datetime.timedelta` returns unexpected value when passed a bool `True` for days arg

### ISSUE THREAD

**Issue by danish-wani** [python/cpython#124852] opened 2024-10-01 15:46 UTC
# Bug report

### Bug description:

Today I stumbled upon a strange issue where I was supposed to pass an integer value to `datetime.timedelta` for days arg but I was passing a boolean `True` value to this function as a positional argument.  Below is what I was doing;

```python
import datetime

datetime.datetime.now() -  datetime.timedelta(True)

# instead of

start_datetimestamp = datetime.datetime.now() -  datetime.timedelta(10)

```

to my surprise, when I checked the value `start_datetimestamp` it was not what I expected. Upon debugging it further I realized I was passing the boolean `True` instead of integer `10` as a positional argument to this function.

Since in my case, the `days` arg was initialized as `True` the below statement evaluated to `True + 0 = 1`, hence assigning `1` to days instead of raising a ValueError.

`days += weeks*7 => True += 0 *7 => 1`

![image](https://github.com/user-attachments/assets/76a16b77-b260-4882-82cd-ce6b00d0b2db)

Proposed better handling of this behaviour:

### Adding a `type` check on all the arguments should possibly avoid this unexpected behaviour;

```python

        d = s = us = 0
        assert isinstance(days, (int, float))
        assert isinstance(seconds, (int, float))
        assert isinstance(microseconds, (int, float))
        assert isinstance(milliseconds, (int, float))
        assert isinstance(minutes, (int, float))
        assert isinstance(hours, (int, float))
        assert isinstance(weeks, (int, float))
```

### When a bool `True` is passed to `datetime.timedelta`

```python
import datetime

datetime.timedelta(True)

# output
# datetime.timedelta(days=1)
```

### CPython versions tested on:

3.10

### Operating systems tested on:

macOS

**Comment by ericvsmith** [comment] 2024-10-01 16:07
As a rule we don't add type checks like this. And in any event, as you discovered `True` is an instance of `int`, so the above test wouldn't work, anyway. You'd need to explicitly exclude `bool` as a valid type.

**Comment by danish-wani** [comment] 2024-10-01 16:57
Fair enough, are you suggesting adding this check before calling `timedelta` in the caller function? Shouldn't this `explicitly exclude bool as a valid type.` be added inside the source code?  @ericvsmith

**Comment by bswck** [comment] 2024-10-01 19:01
I wouldn't consider this a bug, but an example use case of the Liskov substitution principle.

**Comment by bswck** [comment] 2024-10-01 19:12
> Fair enough, are you suggesting adding this check before calling `timedelta` in the caller function? Shouldn't this `explicitly exclude bool as a valid type.` be added inside the source code? @ericvsmith

I'm afraid such a check is shortsighted (despite being breaking).
What about enum int flags? What about Windows-only `subprocess.Handle`? They all also don't fit.
And someone might actually want to use bool there, for instance

```py
duration = timedelta(days=is_one_day_event)  # is_one_day_event=True -> timedelta(days=1), one_day_event=False -> timedelta(0)
```

I've seen a common practice in using `bool` as ints for string multiplication. I guess that you found a feature, not a bug.
I'd consider closing this.

**Comment by JelleZijlstra** [comment] 2024-10-01 19:53
The fact that bools are a subclass of int is arguably a design bug in Python but not one we can fix now.

**Closed as not planned** 2024-10-01 19:52 UTC
Labels: type-bug

**Comment by danish-wani** [comment] 2024-10-03 12:01
Appreciate your response and clarifications. Thank you @bswck @JelleZijlstra
