### ISSUE TITLE
MessageID parser raises IndexError: string index out of range

### ISSUE THREAD

**Issue by 44b4c87c-fe02-447d-bbdd-58861e3ff3f2** [python/cpython#90593] opened 2022-01-19 17:01 UTC
BPO | [46435](https://bugs.python.org/issue46435)
--- | :---
Nosy | @warsaw, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-19.17:01:36.172>
labels = ['type-bug', 'expert-email', '3.11']
title = 'MessageID parser raises IndexError: string index out of range'
updated_at = <Date 2022-01-23.19:28:19.688>
user = 'https://bugs.python.org/bpoaugust'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-23.19:28:19.688>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['email']
creation = <Date 2022-01-19.17:01:36.172>
creator = 'bpoaugust'
dependencies = []
files = []
hgrepos = []
issue_num = 46435
keywords = []
message_count = 1.0
messages = ['410972']
nosy_count = 3.0
nosy_names = ['barry', 'r.david.murray', 'bpoaugust']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46435'
versions = ['Python 3.11']
```

</p></details>

**Comment by PhrozenByte** [comment] 2023-02-18 00:08
Apparently the same happens with an empty message ID like `Message-ID: <>`.

**Comment by serhiy-storchaka** [comment] 2024-04-17 09:45
It is a duplicate of #85116.

**Closed as not planned by serhiy-storchaka** 2024-04-17 09:45 UTC
Labels: type-bug, 3.11, topic-email
