### ISSUE TITLE
add an operator for `not x`

### ISSUE THREAD

**Issue by xSpecialFoodx** [python/cpython#121436] opened 2024-07-06 15:31 UTC
# Feature or enhancement

### Proposal:

Currently there are 2 main ways to check for `not boolean`.
The first is:
```python
x = True
if x is False:
    ...
```
The second is:
```python
x = True
if not x:
    ...
```
`not x` doesn't have a unique dunder, instead it relies on the bool dunder.
I think making a unique dunder for `not x` would make sense, with a unique operator for it.
If the dunder wouldn't be implemented then it'd resort to `bool(x) is False` perhaps.
Now what would that operator be? I think there's already a suitable answer for that, and I'll explain.

When doing `x == y` the `eq` dunder gets called, which goes for "equal"
When doing `x != y` the `ne` dunder gets called, which goes for "not equal"

So perhaps, the most logical operator would be `!x`.
Lucky for us, the `!` operator isn't used.

### Has this already been discussed elsewhere?

No response given

**Comment by Eclips4** [comment] 2024-07-06 15:59
Hello! All major changes should be firstly widely discussed before they're get implemented, so, please create a new topic on https://discuss.python.org/c/ideas/6. 

To be honest, I do not understand what the problem is with `not x`. 
The `not` operator does not have its own dunder, as well as `and` & `or` operators.

Now I'm going to close it; we can re-open it later if needed.

**Closed as not planned by Eclips4** 2024-07-06 15:59 UTC
Labels: type-feature

**Comment by xSpecialFoodx** [comment] 2024-07-06 16:07
> Hello! All major changes should be firstly widely discussed before they're get implemented, so, please create a new topic on https://discuss.python.org/c/ideas/6.
> 
> To be honest, I do not understand what the problem is with `not x`. The `not` operator does not have its own dunder, as well as `and` & `or` operators.
> 
> Now I'm going to close it; we can re-open it later if needed.

Technically, there is no issue with `not`, but having an operator and a dunder for it can be useful, as it is in `!=` and `ne`.
I've listened to your advice, and opened a thread in there.
https://discuss.python.org/t/add-an-operator-for-not-x/57482
