### ISSUE TITLE
sqlite3 seclect with "order" accepts named parameter but don't order

### ISSUE THREAD

**Issue by sh-dvl** [python/cpython#94322] opened 2022-06-27 09:46 UTC
at least with python 3.8.10 following test shows, that "order" with named parameters neither works nor returns an error:
(the data for the table was grabbed from https://www.tutorialspoint.com/python_data_access/python_sqlite_order_by.htm)
```
import sqlite3

conn = sqlite3.connect(':memory:')

cursor = conn.cursor()

sql = '''CREATE TABLE EMPLOYEE(
FIRST_NAME CHAR(20) NOT NULL,
   LAST_NAME CHAR(20),
   AGE INT, SEX CHAR(1),
   INCOME INT,
   CONTACT INT
)'''
cursor.execute(sql)


cursor = conn.cursor()

cursor.execute('''INSERT INTO EMPLOYEE
   (FIRST_NAME, LAST_NAME, AGE, SEX, INCOME) VALUES 
   ('Ramya', 'Rama priya', 27, 'F', 9000),
   ('Vinay', 'Battacharya', 20, 'M', 6000), 
   ('Sharukh', 'Sheik', 25, 'M', 8300), 
   ('Sarmista', 'Sharma', 26, 'F', 10000),
   ('Tripthi', 'Mishra', 24, 'F', 6000)''')

cursor = conn.cursor()

cursor.execute("SELECT * from EMPLOYEE WHERE SEX = :SEX ORDER BY :ORDER", { 'SEX':'F', 'ORDER':'AGE'} )
print('bad:')
for r in cursor.fetchall():
	print(r)

cursor = conn.cursor()

cursor.execute("SELECT * from EMPLOYEE WHERE SEX = :SEX ORDER BY AGE", { 'SEX':'F'} )
print('good:')
for r in cursor.fetchall():
	print(r)

conn.close()
```

results in:
```
bad:
('Ramya', 'Rama priya', 27, 'F', 9000, None)
('Sarmista', 'Sharma', 26, 'F', 10000, None)
('Tripthi', 'Mishra', 24, 'F', 6000, None)
good:
('Tripthi', 'Mishra', 24, 'F', 6000, None)
('Sarmista', 'Sharma', 26, 'F', 10000, None)
('Ramya', 'Rama priya', 27, 'F', 9000, None)
```

**Comment by erlend-aasland** [comment] 2022-06-27 10:31
The SQLite placeholders do not function as direct manipulation of Python strings; SQLite placeholders _bind values to SQLite statements_; that is they bind values to SQLite values (strings, ints, floats, NULLs, or BLOBs). The placeholders do not modify the query itself; you modify _parameters_ in the query.

For your case, you'll have to resort to to different SQL statements, or regular Python string manipulation here. Hope that was clarifying :)

You'll see what happens if you start off your script with a `conn.set_trace_callback(print)`, as soon as the connection is created:

<details>

```
CREATE TABLE EMPLOYEE(
FIRST_NAME CHAR(20) NOT NULL,
LAST_NAME CHAR(20),
AGE INT, SEX CHAR(1),
INCOME INT,
CONTACT INT
)
BEGIN
INSERT INTO EMPLOYEE
(FIRST_NAME, LAST_NAME, AGE, SEX, INCOME) VALUES
('Ramya', 'Rama priya', 27, 'F', 9000),
('Vinay', 'Battacharya', 20, 'M', 6000),
('Sharukh', 'Sheik', 25, 'M', 8300),
('Sarmista', 'Sharma', 26, 'F', 10000),
('Tripthi', 'Mishra', 24, 'F', 6000)
bad:
SELECT * from EMPLOYEE WHERE SEX = 'F' ORDER BY 'AGE'
('Ramya', 'Rama priya', 27, 'F', 9000, None)
('Sarmista', 'Sharma', 26, 'F', 10000, None)
('Tripthi', 'Mishra', 24, 'F', 6000, None)
good:
SELECT * from EMPLOYEE WHERE SEX = 'F' ORDER BY AGE
('Tripthi', 'Mishra', 24, 'F', 6000, None)
('Sarmista', 'Sharma', 26, 'F', 10000, None)
('Ramya', 'Rama priya', 27, 'F', 9000, None
```

Notice the apostrophes around AGE in the "bad" query; you're trying to order by a string literal, which does not make any sense to SQLite. Hence, the result.

</details>

Thanks for the report, but this is not a bug in sqlite3 :) Closing as not-a-bug.

**Closed as not planned by erlend-aasland** 2022-06-27 10:31 UTC
Labels: topic-sqlite3

**Comment by sh-dvl** [comment] 2022-06-27 10:38
oops, yes of course those parameters are intentionally sql-bindings. for security-reasons it's rather a bad idea to use format-strings and as you can see, the bound parameter ':id' works as expected. 

so, if pythons sqlite3 does not support the same for 'order-by'-clause, it should give an error (as already mentioned above)

the current behaviour of handling parameterized order-clause perhaps might not be a bug, but neither show consistent handling of parameters nor give an error is at least bad API-behaviour, which should be fixed

**Comment by erlend-aasland** [comment] 2022-06-27 11:31
> pythons sqlite3 does not support the same for 'order-by'-clause, it should give an error (as already mentioned above)

The sqlite3 modules does not "support" any SQL. It merely passes SQL to SQLite, which then interprets it. The sqlite3 module "supports" whatever the underlying SQLite library supports. If SQLite does not throw an error, neither should sqlite3.

> the current behaviour of handling parameterized order-clause perhaps might not be a bug, but neither show consistent handling of parameters nor give an error is at least bad API-behaviour, which should be fixed

How is it not consistent? You pass a Python string and it ends up as an SQLite string literal. This is expected and consistent behaviour. It is not API misuse. If it was, SQLite would have raised an error, which sqlite3 would have relayed as an exception.

**Comment by sh-dvl** [comment] 2022-06-27 11:44
> How is it not consistent? You pass a Python string and it ends up as an SQLite string literal. 

ok, you're right, I was wrong.
of course the parameter for `:SEX` in the example _is_ a string and is handled as such, but for `:ORDER` there might be a type of sql_statement, which doesn't exist.
sorry, I had to look twice on the trace-output-hint, given by you. thanks for your patience
