### ISSUE TITLE
Subprocess module calling shell commands only using one physical core

### ISSUE THREAD

**Issue by cap-jmk** [python/cpython#103555] opened 2023-04-15 08:22 UTC
# Bug report

When invoking subprocess in either pytest or invoking pytest from a subprocess the command is using only one physical core. 
However invoking the commands myself makes use of all cores. It seems like only heavy loads experience the problem as small loads distribute the calculations across physical cores.

# Your environment

- CPython versions tested on: 3.10
- Operating system and architecture: Ubuntu 22.04, Endeavor OS

I also tried to diagnose the bug a little bit. You can refer to these two issues as a reference 

* [issue1](https://github.com/pallets/click/issues/2474)
* [issue2](https://codeberg.org/cap_jmk/lia/issues/25#issuecomment-873987)

# Summary of debugging done so far

```
* using os -> is also not recognized by the kernel properly
* not invoking a shell
* invoking a shell 
* installing cmake and gcc
* using multithreading 
* using multiprocessing 
* using a bash script with subprocess
```
They all happen to work on one physical core.

Yet, running pytest in the plain shell works! From what I see, the system is ready for high performance but subprocess does not communicate well with the kernel for some reason.

**Comment by sunmy2019** [comment] 2023-04-16 12:13
While I don't think this is the right place to pose the issue, you should know that it's the command
```sh
prettify-py format-dir carate/
```
make you stuck forever. Not what you thought it was.


Please politely close those irrelevant issues.

**Comment by sunmy2019** [comment] 2023-04-16 12:38
Looks like you own the `prettify_py`. Try to debug yourself.

**Comment by cap-jmk** [comment] 2023-04-16 12:48
I am not so sure how you derive that conclusion?  Can you elaborate on that? I would love to debug it, however also invoking the normal carate CLI from a pytest function using subprocess would not use multiple cores.

**Comment by sunmy2019** [comment] 2023-04-16 12:56
`subprocess` opens a new process, which cannot prevent the new process from forking child processes.

> I am not so sure how you derive that conclusion?

I use your reproducing example in the pytest issue `lia heal carate`, but then it stuck at the command `prettify-py format-dir carate/` for very long time. Pytest was never executed.

**Comment by cap-jmk** [comment] 2023-04-16 14:54
Hum, I think your consideration is true to some extent. But one can already see the coverage xmls when invoking the command, such that the tests are actually running. Thus to fix the performance, the answer lies in another direction, too.

**Comment by gpshead** [comment] 2023-04-21 20:17
This issue needs a simple Python snippet that reproduces it (not using other project third party dependencies).

**Comment by hauntsaninja** [comment] 2023-07-05 05:14
Closing as per above

**Closed as not planned by hauntsaninja** 2023-07-05 05:14 UTC
Labels: type-bug, pending
