### ISSUE TITLE
Add API to allow extensions to set callback function on creation and destruction of PyCodeObject

### ISSUE THREAD

**Issue by f820ac6c-889b-43b7-b077-21b10aeb370a** [python/cpython#91054] opened 2022-03-01 22:20 UTC
BPO | [46898](https://bugs.python.org/issue46898)
--- | :---
Nosy | @carljm, @DinoV, @itamaro, @mpage

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-01.22:20:58.520>
labels = ['expert-C-API', 'type-feature', '3.11']
title = 'Add API to allow extensions to set callback function on creation and destruction of PyCodeObject'
updated_at = <Date 2022-03-01.22:20:58.520>
user = 'https://github.com/mpage'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-01.22:20:58.520>
actor = 'mpage'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2022-03-01.22:20:58.520>
creator = 'mpage'
dependencies = []
files = []
hgrepos = []
issue_num = 46898
keywords = []
message_count = 1.0
messages = ['414309']
nosy_count = 4.0
nosy_names = ['carljm', 'dino.viehland', 'itamaro', 'mpage']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46898'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-99859
* gh-99976
* gh-99978
* gh-107821
* gh-107835

**Comment by gvanrossum** [comment] 2022-09-15 03:41
In which header file would you put that? Maybe this is simple enough that you should just submit a PR?

**Comment by itamaro** [comment] 2022-09-15 04:20
> In which header file would you put that?

would `Include/cpython/code.h` make sense for this API?

> Maybe this is simple enough that you should just submit a PR?

hopefully yes, we intend to do that for 3.12.
does the proposed API look reasonable?

**Comment by gvanrossum** [comment] 2022-09-24 03:38
The API looks reasonable -- I'd spell `LifeCycle` with two capital letters (though [Wikipedia seems divided on this](https://en.wikipedia.org/wiki/Life_cycle)), and I'd start the enum values with `PY_CODE`, similar to `_PyCodeLocationInfoKind` in the same file. The implementation would seem straightforward, and code objects aren't created or destroyed at a monstrous rate (it might be worth seeing if this slows down unmarshalling noticeably, but I doubt it). The callback should probably be stored in the per-interpreter state.

**Comment by pablogsal** [comment] 2022-12-03 20:57
Unfotunately, there are many buildbots failing to build this PR. Check [buildbot.python.org/all/#/release_status](https://buildbot.python.org/all/#/release_status) for reference

As per our buildbot policy, this PR will be reverted if the buildbot fleet is not fixed in the next 24h. @markshannon @itamaro can you please take a look?

I have opened https://github.com/python/cpython/pull/99976. I will close it if the issue is fixed before the deadline.

**Comment by itamaro** [comment] 2022-12-04 22:22
this issue can be closed now!

**Closed as completed** 2022-12-04 22:36 UTC
Labels: type-feature, topic-C-API, 3.12
