### ISSUE TITLE
PyObject_GC_Track: Assertion failed: object already tracked by the garbage collector

### ISSUE THREAD

**Issue by vitassuper** [python/cpython#111651] opened 2023-11-02 15:25 UTC
# Crash report

### What happened?

PyObject_GC_Track: Assertion failed: object already tracked by the garbage collector
Current thread 0x00007eff726fc700 (most recent call first):
  Garbage-collecting
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 941 in deep_extend
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 946 in deep_extend
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 946 in deep_extend
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 946 in deep_extend
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 2064 in set_markets
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1445 in load_markets
  File "/app/src/bot/exchange/base.py", line 85 in load_markets
  File "/app/src/bot/exchange/decorators.py", line 13 in wrapper
  File "/app/src/bot/exchange/base.py", line 14 in __init__
  File "/app/src/bot/exchange/okx.py", line 29 in __init__
  File "/app/src/bot/exchange/exchange_manager.py", line 18 in get_exchange
  File "/app/src/bot/exchange/bot.py", line 50 in get_exchange
  File "/app/src/bot/exchange/bot.py", line 33 in process
  File "/app/src/bot/signal_dispatcher.py", line 52 in dispatch
  File "/app/src/bot/singal_dispatcher_spawner.py", line 43 in run
  File "/app/src/bot/singal_dispatcher_spawner.py", line 98 in thread_run
  File "/usr/local/lib/python3.11/threading.py", line 975 in run
  File "/usr/local/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/usr/local/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00007eff72efd700 (most recent call first):
  File "/usr/local/lib/python3.11/ssl.py", line 1134 in read
  File "/usr/local/lib/python3.11/ssl.py", line 1278 in recv_into
  File "/usr/local/lib/python3.11/socket.py", line 706 in readinto
  File "/usr/local/lib/python3.11/http/client.py", line 631 in _safe_read
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 1027 in _handle_chunk
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 1076 in read_chunked
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 933 in stream
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 816 in generate
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 899 in content
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 747 in send
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589 in request
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 584 in fetch
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3048 in fetch2
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3051 in request
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/types.py", line 26 in unbound_method
  File "/usr/local/lib/python3.11/site-packages/ccxt/okx.py", line 1422 in fetch_markets_by_type
  File "/usr/local/lib/python3.11/site-packages/ccxt/okx.py", line 1259 in fetch_markets
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1444 in load_markets
  File "/app/src/bot/exchange/base.py", line 85 in load_markets
  File "/app/src/bot/exchange/decorators.py", line 13 in wrapper
  File "/app/src/bot/exchange/base.py", line 14 in __init__
  File "/app/src/bot/exchange/okx.py", line 29 in __init__
  File "/app/src/bot/exchange/exchange_manager.py", line 18 in get_exchange
  File "/app/src/bot/exchange/bot.py", line 50 in get_exchange
  File "/app/src/bot/exchange/bot.py", line 33 in process
  File "/app/src/bot/signal_dispatcher.py", line 52 in dispatch
  File "/app/src/bot/singal_dispatcher_spawner.py", line 43 in run
  File "/app/src/bot/singal_dispatcher_spawner.py", line 98 in thread_run
  File "/usr/local/lib/python3.11/threading.py", line 975 in run
  File "/usr/local/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/usr/local/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00007eff736fe700 (most recent call first):
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3158 in safe_currency
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3755 in safe_currency_code
  File "/usr/local/lib/python3.11/site-packages/ccxt/okx.py", line 1340 in parse_market
  File "/usr/local/lib/python3.11/site-packages/ccxt/okx.py", line 1269 in parse_markets
  File "/usr/local/lib/python3.11/site-packages/ccxt/okx.py", line 1429 in fetch_markets_by_type
  File "/usr/local/lib/python3.11/site-packages/ccxt/okx.py", line 1259 in fetch_markets
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1444 in load_markets
  File "/app/src/bot/exchange/base.py", line 85 in load_markets
  File "/app/src/bot/exchange/decorators.py", line 13 in wrapper
  File "/app/src/bot/exchange/base.py", line 14 in __init__
  File "/app/src/bot/exchange/okx.py", line 29 in __init__
  File "/app/src/bot/exchange/exchange_manager.py", line 18 in get_exchange
  File "/app/src/bot/exchange/bot.py", line 50 in get_exchange
  File "/app/src/bot/exchange/bot.py", line 33 in process
  File "/app/src/bot/signal_dispatcher.py", line 52 in dispatch
  File "/app/src/bot/singal_dispatcher_spawner.py", line 43 in run
  File "/app/src/bot/singal_dispatcher_spawner.py", line 98 in thread_run
  File "/usr/local/lib/python3.11/threading.py", line 975 in run
  File "/usr/local/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/usr/local/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00007effa51ac740 (most recent call first):
  File "/usr/local/lib/python3.11/site-packages/sanic/server/runners.py", line 145 in _run_server_forever
  File "/usr/local/lib/python3.11/site-packages/sanic/server/runners.py", line 264 in _serve_http_1
  File "/usr/local/lib/python3.11/site-packages/sanic/worker/serve.py", line 117 in worker_serve
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108 in run
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314 in _bootstrap
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 133 in _main
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 120 in spawn_main
  File "<string>", line 1 in <module>

Extension modules: multidict._multidict, uvloop.loop, httptools.parser.parser, httptools.parser.url_parser, ujson, websockets.speedups, _cffi_backend, charset_normalizer.md, sqlalchemy.cyextension.collections, sqlalchemy.cyextension.immutabledict, sqlalchemy.cyextension.processors, sqlalchemy.cyextension.resultproxy, sqlalchemy.cyextension.util, greenlet._greenlet, asyncpg.pgproto.pgproto, asyncpg.protocol.protocol (total: 16)

My code repository: https://github.com/vitassuper/flux-bot

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.11.4 (main, Jul 28 2023, 05:28:12) [GCC 10.2.1 20210110]

**Comment by sunmy2019** [comment] 2023-11-11 12:01
Please report your problem to ccxt, not here. More likely it's their bug.

**Comment by sunmy2019** [comment] 2023-11-11 12:09
Otherwise, you should better provide some reproducible examples with only Python stdlib.

**Comment by terryjreedy** [comment] 2023-12-13 06:12
Closing due to inadequate infor to act on and mo response.

**Closed as not planned by terryjreedy** 2023-12-13 06:12 UTC
Labels: type-crash, pending
