### ISSUE TITLE
[Python 3.12] Removal of `error` and `BadZipfile` aliases of `BadZipFile`

### ISSUE THREAD

**Issue by PedanticHacker** [python/cpython#102622] opened 2023-03-12 13:58 UTC
Please firstly visit this link: https://github.com/python/cpython/blob/main/Lib/zipfile/__init__.py#L49.

Alright, so, this has existed for far too long now. I think it should be removed already. I reported this to be removed on the Python Bug Tracker way back, but was told to wait until Python 3.11 or 3.12. Okay, so, here we are, Python 3.12 Alpha 6.

Can you please remove those two ugly and undeeded aliases of `BadZipFile`? It's time. Thank you.

**Comment by hugovk** [comment] 2023-03-12 16:19
The old BPO issue was transferred over here and is still open, so let's close this as a duplicate and carry on over there: https://github.com/python/cpython/issues/86437

**Closed as not planned by hugovk** 2023-03-12 16:19 UTC
Labels: type-feature

**Comment by PedanticHacker** [comment] 2023-03-12 16:34
Not planned? Seriously? After all these years? You gotta be shitting me.

**Comment by AlexWaygood** [comment] 2023-03-12 16:39
Please re-read Hugo's message, @PedanticHacker. This issue has been closed as "not planned" because it is a duplicate of your previous issue, #86437, which remains open. As such, discussion should continue there rather than on this duplicate issue.

Please also note that if you continue to use language like that when addressing open-source volunteers who are giving up their time for free to help you, you're liable to be banned from the CPython repo. The Python code of conduct is here: https://www.python.org/psf/conduct/
