### ISSUE TITLE
argparse: space in an incorrect argument adds it to `nargs="*"`, instead of raising an error

### ISSUE THREAD

**Issue by abcydybcy** [python/cpython#114429] opened 2024-01-22 14:11 UTC
# Bug report

### Bug description:

Code to recreate:
```python
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("args", nargs="*")
print(parser.parse_args())
```
Current behaviour:
If the wrong argument contains a space, it is added to the catch-all arguments:
```
> python bug.py --wrong-arg="foo bar"
Namespace(args=['--wrong-arg=foo bar'])
```

But if it doesn't contain a space, expected behaviour happens:
```
> python bug.py --wrong-arg="foobar" 
usage: bug.py [-h] [args ...]
bug.py: error: unrecognized arguments: --wrong-arg=foobar
```

Expected behaviour:
Calling this program as `bug.py --wrong-argument="foo bar"` prints an error message:
```
usage: bug.py [-h] [--name NAME] [args ...]
bug.py: error: unrecognized arguments: --wrong-arg=foo bar.
```

### CPython versions tested on:

3.11

**Comment by hugovk** [comment] 2024-01-22 14:16
Thanks for the report, this looks like a duplicate of https://github.com/python/cpython/issues/66623.

**Closed as not planned by hugovk** 2024-01-22 14:16 UTC
Labels: type-bug
