### ISSUE TITLE
Sqlite Prepared statements, Boolean Conversion

### ISSUE THREAD

**Issue by LukasFehring** [python/cpython#113807] opened 2024-01-08 09:37 UTC
# Bug report

### Bug description:

When using the prepared statements of sqlite, the values "TRUE" and "FALSE" are not being converted to 1, and 0. Howerver, according to the sqlite documentation this should happen. Instead one has to use the python types in the prepared values.

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment] 2024-01-08 09:39
cc @erlend-aasland

**Comment by erlend-aasland** [comment] 2024-01-08 12:37
@LukasFehring, can you add some more context? I have a hard time understanding what you are doing here. Are you inserting the Python strings `"TRUE"` and `"FALSE"` into a table? Are you trying to read data from an SQLite database into Python data structure?

As an example, here I'm first reading back the SQLite _strings_ `"TRUE"` and `"FALSE"` to Python; as expected, the _strings_ are returned as Python _strings_. In the latter query, I'm reading back the SQLite _boolean values_[^1] `TRUE` and `FALSE`; as expected, these are returned to Python as _integers_.

```python
Python 3.13.0a2 (v3.13.0a2:9c4347ef8b, Nov 22 2023, 11:02:00) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> cx = sqlite3.connect(":memory:")
>>> for row in cx.execute('SELECT "TRUE"'): print(row)
... 
('TRUE',)
>>> for row in cx.execute('SELECT TRUE'): print(row)
... 
(1,)
>>> 
```

[^1]: SQLite does not have booleans; they are stored internally as integers https://www.sqlite.org/datatype3.html

**Comment by erlend-aasland** [comment] 2024-01-08 12:50
Here's an example where I'm inserting Python values into an SQLite database:

```console
$ sqlite3 test.db
SQLite version 3.43.2 2023-10-10 13:08:14
Enter ".help" for usage hints.
sqlite> CREATE TABLE t(t);
sqlite> ^D
$ python3
Python 3.13.0a2 (v3.13.0a2:9c4347ef8b, Nov 22 2023, 11:02:00) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> cx = sqlite3.connect("test.db")
>>> with cx:
...     cx.executemany("INSERT INTO t VALUES(?)", [("TRUE",), (True,)])
... 
<sqlite3.Cursor object at 0x100d1d940>
>>> cx.close()
>>> ^D
$ sqlite3 test.db "SELECT * FROM t;"
TRUE
1
$
```

**Comment by LukasFehring** [comment] 2024-01-08 12:51
@erlend-aasland Sorry, yes i should have provided more context :)

Here is some example code, where I would have expected the table to contain the value 0


```python
from sqlite3 import connect

connection = connect("example.db")
cursor = connection.cursor()
cursor.execute("CREATE TABLE IF NOT EXISTS example_table (id INTEGER PRIMARY KEY AUTOINCREMENT, value BOOLEAN)")
cursor.execute("INSERT INTO EXAMPLE_TABLE (value) VALUES (?)", ("False",))
connection.commit()

cursor.execute("SELECT * FROM example_table")
values = cursor.fetchall()
values = [value[1] for value in values]
for value in values:
    if value:
        print("True")
```

My confusion stems from the sqlite [documentation](https://www.sqlite.org/quirks.html#no_separate_boolean_datatype):

```
3.1. No Separate BOOLEAN Datatype
Unlike most other SQL implementations, SQLite does not have a separate BOOLEAN data type. Instead, TRUE and FALSE are (normally) represented as integers 1 and 0, respectively. This does not seem to cause many problems, as we seldom get complaints about it. But it is important to recognize.

Beginning with SQLite [version 3.23.0](https://www.sqlite.org/releaselog/3_23_0.html) (2018-04-02), SQLite also recognizes TRUE and FALSE keywords as aliases for integer values 1 and 0, respectively. This provides better compatibility with other SQL implementations. But for backwards compatibility, if there are columns named TRUE or FALSE, then the keywords are treated as identifiers referencing those columns, rather than BOOLEAN literals.
```
in combination with pythons [documentation](https://docs.python.org/3/library/sqlite3.html)
```
execute(sql, parameters=(), /)
Create a new [Cursor](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor) object and call [execute()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.execute) on it with the given sql and parameters. Return the new cursor object.
```

Additionally, this code seems to put the 0 into the database
from sqlite3 import connect

connection = connect("example.db")
cursor = connection.cursor()
cursor.execute("CREATE TABLE IF NOT EXISTS example_table (id INTEGER PRIMARY KEY AUTOINCREMENT, value BOOLEAN)")
cursor.execute("INSERT INTO EXAMPLE_TABLE (value) VALUES (FALSE)")
connection.commit()

cursor.execute("SELECT * FROM example_table")
values = cursor.fetchall()
values = [value[1] for value in values]
for value in values:
    if value:
        print("True")
    else:
        print("False")

**Comment by erlend-aasland** [comment] 2024-01-08 12:53
If the Python sqlite3 docs are unclear, please let us know how we can improve them. Relevant sections:

- https://docs.python.org/3/library/sqlite3.html#tutorial
- https://docs.python.org/3/library/sqlite3.html#sqlite-and-python-types
- https://docs.python.org/3/library/sqlite3.html#how-to-use-placeholders-to-bind-values-in-sql-queries

**Comment by LukasFehring** [comment] 2024-01-08 12:55
I see that https://docs.python.org/3/library/sqlite3.html#how-to-use-placeholders-to-bind-values-in-sql-queries might be an argument against this being a bug, rather it being intended behaviour.

**Comment by erlend-aasland** [comment] 2024-01-08 12:59
> cursor.execute("INSERT INTO EXAMPLE_TABLE (value) VALUES (?)", ("False",))

Here, you are using the **Python** _string_ `"False"`; not the Python boolean `False`. The behaviour you are seeing is the expected behaviour when you supply a string.

> cursor.execute("INSERT INTO EXAMPLE_TABLE (value) VALUES (FALSE)")

Here, you are using the **SQLite** _boolean_ (_integer_) `FALSE`; as opposed to the **SQLite** _string_ `'FALSE'`[^1]. The behaviour you are seeing is the expected behaviour when you are inserting an _integer_.

[^1]: BTW, double quoted string literals are also allowed by default in SQLite: https://www.sqlite.org/quirks.html

**Comment by erlend-aasland** [comment] 2024-01-08 13:00
> I see that https://docs.python.org/3/library/sqlite3.html#how-to-use-placeholders-to-bind-values-in-sql-queries might be an argument against this being a bug, rather it being intended behaviour.

You are seeing expected behaviour; there is no bug here. If there is a "bug", it is unclear documentation; we can improve the docs!

**Comment by LukasFehring** [comment] 2024-01-08 13:08
I agree - it was a misunderstanding of the docs on my part!

Maybe the docs could be improved by explicitly stating how prepared statements work in that context for sqlite. This suggestion is based on the fact that the confusion started with the fact that the call
```python
cursor.execute("INSERT INTO EXAMPLE_TABLE (value) VALUES ({})".format("False"))
```
would work as intended, and the above calls work as well for MySQL-connector-python and pymysql.

**Comment by LukasFehring** [comment] 2024-01-08 13:11
I have a hard time putting into words how this can be added to the docs, without adding more confusion for people who do not fall for the same misconception I did. My only concrete suggestion would be to add it into the docstring of the execute functions clarifying how the parameters are used.

**Comment by erlend-aasland** [comment] 2024-01-08 13:19
> ```python
> cursor.execute("INSERT INTO EXAMPLE_TABLE (value) VALUES ({})".format("False"))
> ```

Here, you are not using placeholders; you are _building a Python string_. Try it in the REPL to see the effect:

```python
Python 3.13.0a2 (v3.13.0a2:9c4347ef8b, Nov 22 2023, 11:02:00) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "INSERT INTO EXAMPLE_TABLE (value) VALUES ({})".format("False")
'INSERT INTO EXAMPLE_TABLE (value) VALUES (False)'
>>> 
```

As you can see, the resulting _Python string_ is an _SQL query_ that inserts a _boolean SQLite value_. Also, this is not a bug; this is expected behaviour.

Have you read through the Python tutorial? If not, I suggest you do that. The sqlite3 library docs expect you to be familiar Python data types.

**Comment by erlend-aasland** [comment] 2024-01-08 13:39
I'm going to close this as not-planned. There is no bug, and it is not obvious to me how we could improve [the sqlite3 docs](https://docs.python.org/3/library/sqlite3.html). The sqlite3 docs can not and should not evolve into a fundamental Python tutorial (we've already got [the Python tutorial](https://docs.python.org/3/tutorial/index.html) for that; no need to duplicate it).

**Closed as not planned by erlend-aasland** 2024-01-08 13:39 UTC
Labels: docs, topic-sqlite3
