### ISSUE TITLE
argparse does not accept negative args w/ exponents as for negative arguments

### ISSUE THREAD

**Issue by mwette** [python/cpython#96994] opened 2022-09-21 15:00 UTC
# Bug report

In the "Arguments Containing -" section of the argparse documentation it says:
>  positional arguments may only begin with - if they look like negative numbers and there are no options in the parser that look like negative numbers

However, negative numbers with exponent notation are rejected.  I feel this is a bug.

With file `apbug.py` containing
```python
#!/usr/bin/env python3.10

import argparse

ap = argparse.ArgumentParser()
ap.add_argument("maybe_neg", default=False)

print("try -3.0"); args = ap.parse_args(args=["-3.0",])
print("try -3.0e0"); args = ap.parse_args(args=["-3.0e0",])
```
execution results in 
```console
$ ./apbug.py 
try -3.0
try -3.0e0
usage: apbug.py [-h] maybe_neg
apbug.py: error: the following arguments are required: maybe_neg

```

# Your environment

- CPython versions tested on: 3.10
- Operating system and architecture: macOS 12.6 x86_64

**Comment by ryuyz** [comment] 2022-10-05 09:28
Yes argparse accepts very limited forms of negative numbers. See also: #53580 (and #66862)

I'm thinking of suggesting a fix for this problem.

**Comment by hugovk** [comment] 2023-01-08 09:13
Hi, thanks for the report. This is a duplicate of https://github.com/python/cpython/issues/53580 (and https://github.com/python/cpython/issues/66862), which was closed after a long discussion and investigation: unfortunately the behaviour is too deeply baked into argparse, and it would be too risky to change without breaking many existing tools. 

See for example https://github.com/python/cpython/issues/53580#issuecomment-1093512317 and https://github.com/python/cpython/issues/53580#issuecomment-1093512320. 

The alternatives are to use the older (deprecated) optparse, or one of many third-party libraries.

**Closed as not planned by hugovk** 2023-01-08 09:13 UTC
Labels: type-bug
