### ISSUE TITLE
Shim frames can be accessed during frame teardown (via `tstate->cframe->current_frame`)

### ISSUE THREAD

**Issue by jaraco** [python/cpython#100126] opened 2022-12-09 01:10 UTC
# Crash report

In jaraco/jaraco.net#5, I've captured a failure that's emerged as Github updated Python 3.12 from a2 to a3 on Linux. The [calling code](https://github.com/jaraco/jaraco.net/blob/e0d1db9d0c8d91579e26f5bcae9c61270d6d6647/jaraco/net/devices/linux.py#L97-L104) is using ctypes to call libc functions.

I don't yet have a minimal reproducer. I'm unable to replicate the issue locally as I don't yet have Linux with a3.

- Operating system and architecture: Ubuntu Linux

### Linked PRs
* gh-100613

**Comment by illia-v** [comment] 2022-12-17 15:16
Tests of urllib3 detected a segmentation fault on 3.12.0a3 too.
https://github.com/urllib3/urllib3/actions/runs/3720502510/jobs/6310016874

`Fatal Python error: Segmentation fault` on Linux and `Windows fatal exception: access violation` on Windows happened in one test function.

The function succeeded on macOS, but `Fatal Python error: Bus error` happened in a different one.

**Comment by illia-v** [comment] 2022-12-22 21:07
b72014c783e5698beb18ee1249597e510b8bcb5a is the first commit where the segfault in urllib3's tests happens.

**Comment by AlexWaygood** [comment] 2022-12-22 21:09
> [b72014c](https://github.com/python/cpython/commit/b72014c783e5698beb18ee1249597e510b8bcb5a) is the first commit where the segfault in urllib3's tests happens.

Cc. @brandtbucher

**Comment by brandtbucher** [comment] 2022-12-22 21:32
I'll look into this too. No promises that I'll have it figured out before the holiday weekend, but it'll be my main priority starting next Tuesday.

Not sure if #99110 is related... hard to tell without a reproducer.

**Comment by illia-v** [comment] 2022-12-26 19:43
> I'll look into this too. No promises that I'll have it figured out before the holiday weekend, but it'll be my main priority starting next Tuesday.

Thanks!

> Not sure if #99110 is related... hard to tell without a reproducer.

It still happens after PR of #99110 is merged.

**Comment by brandtbucher** [comment] 2022-12-28 23:30
Here is a reproducer with only `pytest`:

```py
# pytest crasher.py

import socket

class TestFoo:
    def test_foo(self) -> None:
        _ = socket.socket()
```

Indeed, this looks eerily similar to #99729.

**Comment by brandtbucher** [comment] 2022-12-28 23:52
Found the issue. `PyEval_GetGlobals` returns `tstate->cframe->current_frame->f_globals`. When tearing a frame down, `current_frame` may be a shim frame. Shim frames have no globals, so the code crashes.

**Comment by brandtbucher** [comment] 2022-12-28 23:56
Looks like in general, it is not safe for `current_frame` to be a shim frame. Too many things can break.

**Comment by brandtbucher** [comment] 2022-12-28 23:59
Minimal reproducer, no `pytest`:

# python crasher.py

```py
import operator

class C:
    def __del__(self):
        assert False

def f():
    local = C()

# Call from C, so there is a shim frame above f:
operator.call(f)
```

**Comment by brandtbucher** [comment] 2022-12-29 00:18
I'm honestly not sure what to do here.

Perhaps, before tearing down a frame, if our previous frame is a shim frame, we should set `tstate->cframe` to be `cframe.previous`. But that's adding code to a perf-sensitive path, and it also makes the interaction with `INTERPRETER_EXIT` awkward, since it tries to do the same thing.

The best option is probably just to add more `while (frame && _PyFrame_IsIncomplete(frame)) {frame = frame->previous;}` loops to all of the affected areas. It probably makes sense to just add a helper function for this (`_PyThreadState_GetInterpreterFrame`?), rather than continuing to sprinkle them everywhere.

Thoughts, @markshannon? (I don't think you're out this week... feel free to ignore if so.)

**Comment by brandtbucher** [comment] 2022-12-29 00:19
Also going to tag as `release-blocker` (for now).

**Comment by Yhg1s** [comment] 2023-01-09 12:09
@brandtbucher what's the state of this issue (and the attached fix for it)? Should this hold up 3.12.0a4?

**Comment by brandtbucher** [comment] 2023-01-09 17:24
Sorry, just got back from vacation and thought it was merged while I was gone. I'm in a meeting right now, but I have one small review comment to apply, then I'll merge.

If it's not too much trouble, I'd like this to make it into the next release. It's not too hard to trigger using frameworks like `pytest`, so it would be nice to have non-crashy test coverage of the next alpha out in the wild.

**Comment by brandtbucher** [comment] 2023-01-09 20:21
@yhg1s, this is done!

**Closed as completed by brandtbucher** 2023-01-09 20:21 UTC
Labels: release-blocker, type-crash, 3.12
