### ISSUE TITLE
logging module does not work with non-ascii characters

### ISSUE THREAD

**Issue by RAbhiman2009** [python/cpython#99765] opened 2022-11-25 05:52 UTC
When logging module parse a path where the path contains ascii characters, the module fails to parse tha path and report an issue on windows10

**Comment by RAbhiman2009** [comment] 2022-11-25 06:13
File "C:\Python310\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run
  File "C:\Python310\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "filecreate.py", line 8, in <module>
  File "C:\Python310\lib\logging\config.py", line 72, in fileConfig
  File "C:\Python310\lib\logging\config.py", line 105, in _create_formatters
  File "C:\Python310\lib\configparser.py", line 964, in __getitem__
KeyError: 'formatters'

**Comment by RAbhiman2009** [comment] 2022-11-25 06:14
import io
import logging.config

confpath = "C:/Users/Иван/AppData/Local/MyLog.conf"
try:
	logging.config.fileConfig(confpath)
	_logger = logging.getLogger("root")
	
except IOError as e:
	print(e)

**Comment by ericvsmith** [comment] 2022-11-25 09:32
There's not enough information here to show this is a bug in Python.

Please show a complete example that we can run. We do not have a copy of "C:/Users/Иван/AppData/Local/MyLog.conf" to test with. Also, please show the error you get.

Your traceback shows that you're using cx_Freeze. Please create an example without using cx_Freeze.

For your example, please also include the line `open(confpath)` before you call `logging.config.fileConfig`.

**Comment by rohin-dasari** [comment] 2022-11-26 16:25
I was able to execute this without an error so I don't think it is a Python bug. Here's the gist I used to test: https://gist.github.com/rohin-dasari/c9f76afcfb9fd4e1991ccbb8dea4d028

The gist contains a sample logger config file, which is taken from here: https://docs.python.org/3/library/logging.config.html#logging-config-fileformat

I was able to reproduce the error mentioned above when I used a path to a file that doesn't exist. I would double check the path you are passing to the logger.
```python
import logging.config

confpath = "./thisfiledoesntexist.conf"
logging.config.fileConfig(confpath)
_logger = logging.getLogger("root")
```

Interestingly enough, when executing this, I get this error:
```
Traceback (most recent call last):
  File "/Users/rohin/projects/test.py", line 4, in <module>
    logging.config.fileConfig(confpath)
  File "/Users/rohin/miniconda3/lib/python3.9/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/Users/rohin/miniconda3/lib/python3.9/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/Users/rohin/miniconda3/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```
The traceback is a little confusing. I think it makes more sense for the error that is raised to be a `FileNotFoundError`.

**Comment by PranadeepTalamanchi** [comment] 2022-11-26 19:13
The error raised because of non-ascii characters -"Иван" in your specified path - "C:/Users/Иван/AppData/Local/MyLog.conf"

**Comment by ericvsmith** [comment] 2022-11-26 20:20
> The error raised because of non-ascii characters -"Иван" in your specified path - "C:/Users/Иван/AppData/Local/MyLog.conf"

Have you verified that? I don't think it's true that filenames with non-ASCII characters would cause this failure. It's more likely that the file was not found, or its contents are incorrect. `configparser.ConfigParser.read()` does not error out if the file doesn't exist, it just assumes an empty mapping, which causes the `KeyError: 'formatters'` error seen above.

Unfortunately it wouldn't be easy to turn this error into a `FileNotFoundError`. I'm going to close this. If the OP can produce a failing example (per my message above), we can look into it further.

**Closed as not planned by ericvsmith** 2022-11-26 20:20 UTC
Labels: type-bug

**Comment by RAbhiman2009** [comment] 2022-11-29 07:24
Sorry for couple of days could not able to update.
Yes the issue is due to the non-ascii character "Иван" in the path. I included this in the path since the user name is "Иван" and reading the conf file is failing which is inside the profile path.
The conf file is a valid file which is working if executed on a valid path but failing only when "Иван" is present in the path. I have attached the conf file.

Just ignorethe cx-freez since I am using it to package the same to an executable to run on different machines but the error remains same.
[MyLog.log](https://github.com/python/cpython/files/10110661/MyLog.log)

**Comment by RAbhiman2009** [comment] 2022-11-29 07:35
E:\Bugs>python test.py
Traceback (most recent call last):
  File "E:\Bugs\test.py", line 7, in <module>
    logging.config.fileConfig(confpath)
  File "E:\Python310\lib\logging\config.py", line 72, in fileConfig
    formatters = _create_formatters(cp)
  File "E:\Python310\lib\logging\config.py", line 105, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "E:\Python310\lib\configparser.py", line 964, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

**Comment by RAbhiman2009** [comment] 2022-11-29 07:36
import io
import logging.config

#confpath = "E:/Bugs/MyLog.log"
confpath = "C:/Users/Иван/AppData/Local/Novell/Filr/MyLog.conf"
try:
	logging.config.fileConfig(confpath)
	_logger = logging.getLogger("root")
	
except IOError as e:
	print(e)

**Comment by RAbhiman2009** [comment] 2022-11-29 07:39
I am fine with "FileNotFoundError" since the issue is not because the file is not present instead its due to the path which has non-ascii chars. It is very much required to include "Иван" in the path as stated earlier its a user profile path hence by default the path include "Иван".

**Comment by RAbhiman2009** [comment] 2022-11-29 14:13
For me the issue is consistently reproducible

**Comment by ericvsmith** [comment] 2022-11-30 18:12
From an earlier comment of mine:

> For your example, please also include the line open(confpath) before you call logging.config.fileConfig.

I'm trying to figure out if plain `open()` can read your file. That's all that `logging.config.fileConfig` is doing, via `configparser`.

I'd like to see an example that shows that `open(confpath)` works, but `logging.config.fileConfig(confpath)` does not.

**Comment by PranadeepTalamanchi** [comment] 2022-12-19 17:35
I had this issue because Python couldn't find my config file, though you would never know it by the error message. Apparently it does not look for the config file relative to the file in which the code is running, but rather relative to the current working directory (which you can get from os.getcwd()). I used the following code to initialize the logger. The Mylog.log file is in the same directory as the file running this code:

[Mylog.log](https://github.com/python/cpython/files/10261450/Mylog.log)

**Comment by ericvsmith** [comment] 2022-12-20 14:23
Yes, this is why I asked you to show us what happened when you tried `open(confpath)`.

I agree that there should be a better error message here, but the debugging technique of using `open` would have shown the error.
