### ISSUE TITLE
Should we add "i" as a suffix for imaginary numbers (while keeping "j" also)?

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#92938] opened 2022-05-19 01:26 UTC
See https://stackoverflow.com/questions/24812444/why-are-complex-numbers-in-python-denoted-with-j-instead-of-i

Why couldn't we support both `1j` and `1i` with equivalent meanings?

**Comment by serhiy-storchaka** [comment] 2022-05-19 05:28
Isn't it a duplicate of #54771? :wink:

**Comment by gvanrossum** [comment] 2022-05-19 05:33
10+ years later we can change our mind. Of course we should keep 'j' as well -- no deprecation.

**Comment by serhiy-storchaka** [comment] 2022-05-19 06:16
Agree, things are changing and some arguments against this are not so strong now.

I prefer `i` over `j`, but before reading the StackOverflow answers my thought were:

1. It can be confused with digit `1`. In Python 2 it could also be confused with suffix `l` (which almost nobody used in the lowercase form due to confusion with `1`).
2. The output will be with `j` in any case. This may confuse beginners.
3. We may reserve this suffix for something different in future. Unlikely, but there were talks about the `i` prefix for strings.
4. It will complicate the parser. There are already problems with `else` after decimal integer, `or` after `0`, `for` after hexadecimal integer. It will add problems with `if` and `in` after decimal integer. A warning is emitted now in such potentially confusing cases (#87999), thing may be slightly simpler after making it an error in future versions. There are no current plans to make it an error.

They are not very strong arguments, but on other hand, supporting the `i` suffix will brought not much benefit either.

**Comment by stevendaprano** [comment] 2022-05-19 22:15
Is there a specific reason why you are considering changing your mind now? Has something changed since that SO question was asked seven years ago, or last answered two years ago?

"Python uses the engineering convention for complex numbers rather than the maths convention" is a perfectly valid reason to stick with j. Back in the Python 1,5 days I was annoyed that Python used j rather than i, but I got used to it, and I see no strong benefit to adding a second way to write complex literals.

Although in support of this suggestion [Coconut](http://coconut-lang.org/) allows i as an alternative syntax.

If we allowed i, there will surely be people who write numbers like 1I and that's just going to be awful, so maybe we shouldn't tempt them?

I think that short of setting the ground work to eventually add quaternion literals 1+2i+3j+4k I kinda feel that this is churn for no real benefit. But I don't object to it.

**Comment by gvanrossum** [comment] 2022-05-19 22:54
I was reminded of this by a privat document I read recently and regretted the choice of j. IIUC it’s only a small subcommunity (electrical engineering, where complex numbers represent A/C currents with phase) that really prefers j. In high school and college math(s) they teach i. I read on StackOverflow that C++ will get i. I figured I’d at least test the waters to see if there’s appetite for this now.

**Comment by alxlg** [comment] 2022-05-20 10:33
In my education we have always used i from high school to university (engineering) with the exception of the electronics courses where the teachers preferred j , but I always had the impression that the new generations preferred i , probably because now complex numbers are taught in school and you use i , so it's hard to change.

As an advocate of teaching Python at school to better understand math concepts, using i would be more convenient for me instead of explaining to students that j is used because electronics engineers did not want to confuse imaginary unity with the current (which is usually denoted by i(t) )

**Comment by mdickinson** [comment] 2022-05-20 12:18
I'd definitely prefer a universe in which Python used `i` for imaginary numbers, but I've long since accepted that that's not the universe we're in. And that's okay.

@alxlg 
> using i would be more convenient for me instead of explaining to students that j is used because electronics engineers [...]

I don't think the proposed change would do away with the need for that explanation, since there would still be a `j` on output. That is, a student wanting to work with $3 + 4i$ would see this:

```python
>>> 3 + 4i
(3+4j)
```

I don't see any reasonable path to changing that, so accepting a suffix of `i` feels like only half a solution. If we add optional support for `i` on output in the string-formatting mini-language (which seems as though it ought to be relatively straightforward to do), maybe that bumps us to three-quarters of a solution.

That said, I'm not _opposed_ to allowing an `i` or `I` suffix. It just doesn't solve the problem that I want it to solve.

Parsing seems like a non-argument to me, either way. In many years of scientific programming, I have yet to encounter a case where I've needed to convert "i"'s in incoming strings to "j"'s for parsing purposes.

**Comment by oda-gitso** [comment] 2022-05-20 12:34
I do not see any significant benefits in adding `i`. If one wishes to  use complex numbers in Python, they will learn very quickly that `j` is used.

It is simply notation. 

I will always prefer `i` on paper when doing maths and it did feel strange when I first learned that Python uses `j`, but it never bothered me thereafter.

**Comment by rhettinger** [comment] 2022-05-20 14:45
I've never had student have a slightest difficulty with *j*.  People seem to get it instantly and move on.  So I don't think there is any value in add *i* as an alternate input format, especially if repr(z) continued to display *j*.

**Comment by gvanrossum** [comment] 2022-05-20 15:57
Okay, let’s not waste any more time discussing it then.

**Closed as not planned** 2022-05-20 15:57 UTC
Labels: type-feature

**Comment by stevendaprano** [comment] 2022-05-21 00:52
There is little or no support for this idea on Reddit either.

https://www.reddit.com/r/Python/comments/utqo8q/should_python_support_i_suffix_for_complex/
