### ISSUE TITLE
`StopIteration` Exception is ignored in `map()`

### ISSUE THREAD

**Issue by shner-elmo** [python/cpython#100111] opened 2022-12-08 12:32 UTC
# Bug report
```py
def func(x):
    raise StopIteration

>>> list(map(func, [1, 2, 3]))
```
```
[]
```
As you can see `map()` ignores the Exception and instead stops iterating on the first loop.
It seems like it simply mistakes the Exception raised from the function with the one from the Iterator, so it thinks its supposed to stop iterating, and therefore it quits early.

In fact if we overwrite the `map()` function like so, it will raise it properly:
```py
def map(func, it):
    it = iter(it)
    while True:
        try:
            n = next(it)
        except StopIteration:
            return
        yield func(n)

>>> list(map(func, [1, 2, 3]))
```
```
...
RuntimeError: generator raised StopIteration
```

But when call the function directly on the `next()` element then the same thing happens
```py
def map(func, it):
    it = iter(it)
    while True:
        try:
            yield func(next(it))
        except StopIteration:
            return

>>> list(map(func, [1, 2, 3]))
```
```
[]
```
---
For those wondering how I came across this bug, it happened when I was calling `next()` on a bunch of iterators,
which as you can see, made an infinite loop since `map()` would confuse the Exception raised from `next()` of the function that was passed with `next()` when iterating through the iterable that was passed to `map()`
```py
iterables = [[1, 3, 109, 3], (x for x in range(23)), {'a', '2', 'c', 's'}, (1, 2, 3)]
iterators = [iter(x) for x in iterables]
while True:
    print(tuple(map(next, iterators)))
```
```
(1, 0, 's', 1)
(3, 1, '2', 2)
(109, 2, 'c', 3)
(3, 3, 'a')
()
()
()
()
# and it goes on infinetly...
```

# Your environment

- CPython versions tested on: `3.10.7`
- Operating system and architecture: `Windows-10`, `AMD64`, `64bit`

**Comment by sweeneyde** [comment] 2022-12-08 19:24
This seems mostly like a duplicate of https://github.com/python/cpython/issues/90779

**Comment by rhettinger** [comment] 2022-12-09 18:45
This premise of this bug report is false.  The `StopIteration` exception is not being caught by `map()`.  It is the enclosing `list()` that is catching the exception:

```
>>> def func(x):
        raise StopIteration

>>> it = map(func, [10, 20, 30])
>>> next(it)
Traceback (most recent call last):
  File "<pyshell#33>", line 1, in <module>
    next(it)
  File "<pyshell#31>", line 2, in func
    raise StopIteration
StopIteration
```

**Comment by thatbirdguythatuknownot** [comment] 2022-12-10 03:17
> This premise of this bug report is false. The `StopIteration` exception is not being caught by `map()`. It is the enclosing `list()` that is catching the exception...

If this guy is really the same person I encountered a few days ago in the Python discord server talking about how `map()` is ignoring `StopIteration`s, then they must not be listening. We already told them that.

**Comment by shner-elmo** [comment] 2022-12-10 21:56
> This premise of this bug report is false. The `StopIteration` exception is not being caught by `map()`. It is the enclosing `list()` that is catching the exception

@rhettinger You're right, it is raised in `map()` but `list()` (or any object that takes an iterable for that matter) mistakes the Exception raised from the function for the end of the loop (i.e. no more elements..). And this goes against the zen of Python that no error should pass silently.

Wouldn't it be a better idea to wrap the `StopIteration` raised from the function in a `RuntimeError` so it's not confused with "no more elements", like it was done with [generators in PEP 479](https://peps.python.org/pep-0479/) ?

**Comment by rhettinger** [comment] 2022-12-12 08:09
> Wouldn't it be a better idea to wrap the StopIteration raised from the function in a RuntimeError so it's not confused with "no more elements", like it was done with [generators in PEP 479](https://peps.python.org/pep-0479/) ?

This is a guaranteed behavior and not a bug in Python.   Changing the behavior would break code.

You can take the suggestion back to a forum for discussion but I expect it will be an uphill battle.

**Closed as not planned by rhettinger** 2022-12-12 08:09 UTC
Labels: type-bug, pending

**Comment by kaya3** [comment] 2023-01-07 11:03
If the behaviour is guaranteed, then the issue is one of documentation. The docs for the [`list` type](https://docs.python.org/3/library/stdtypes.html#list) and the [`list` function](https://docs.python.org/3/library/functions.html#func-list) don't mention catching `StopIteration`. Does anyone know where this behaviour is specified?

That said, the `list` function doesn't catch `StopIteration` when called with a generator function instead of `map`:

```python
>>> def raises(i):
...     raise StopIteration()
... 
>>> list(map(raises, range(3)))
[]
>>> list(raises(i) for i in range(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <genexpr>
  File "<stdin>", line 2, in raises
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: generator raised StopIteration
```

So it appears to be specifically the combination of `list` and `map` (or `list` and `filter`) that causes this behaviour, not just `list` by itself - specifically, the generator expression wraps the `StopIteration` in a `RuntimeError`, but `map` doesn't. I note also that [the documentation for `filter`](https://docs.python.org/3/library/functions.html#filter) says that `filter(raises, ...)` should be equivalent to a generator expression, but for the aforementioned reason they are not equivalent. So it seems that two contradictory behaviours are specified in the docs, though I think it is the docs that need fixing, not the behaviour.
