### ISSUE TITLE
Regression in help(sqlite3) between Python 3.10.8 and Python 3.11.0

### ISSUE THREAD

**Issue by tom-kacvinsky** [python/cpython#99003] opened 2022-11-02 11:54 UTC
# Bug report

When running the Python interactive interpreter as follows

```
$ ./python3
Python 3.10.8 (tags/v3.10.8:aaaf517424, Nov  2 2022, 07:29:14) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> help(sqlite3)
```
Python 3.10.8 displays the help for `sqlite3`, but 3.11.0 gives a trackback

```
$ ./python3
Python 3.11.0 (main, Nov  2 2022, 07:13:10) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> help(sqlite3)
Traceback (most recent call last):
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 2219, in wrap_value
    value = eval(s, module_dict)
            ^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'ConnectionType' is not defined. Did you mean: 'Connection'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 2222, in wrap_value
    value = eval(s, sys_module_dict)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'ConnectionType' is not defined. Did you mean: 'ConnectionError'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen _sitebuiltins>", line 103, in __call__
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/pydoc.py", line 2001, in __call__
    self.help(request)
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/pydoc.py", line 2060, in help
    else: doc(request, 'Help on %s:', output=self._output)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/pydoc.py", line 1784, in doc
    pager(render_doc(thing, title, forceload))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/pydoc.py", line 1778, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/pydoc.py", line 479, in document
    if inspect.ismodule(object): return self.docmodule(*args)
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/pydoc.py", line 1275, in docmodule
    contents.append(self.document(value, key, name))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/pydoc.py", line 481, in document
    if inspect.isroutine(object): return self.docroutine(*args)
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/pydoc.py", line 1494, in docroutine
    signature = inspect.signature(object)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 3272, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 3020, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 2512, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 2324, in _signature_from_builtin
    return _signature_fromstr(cls, func, s, skip_bound_arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 2272, in _signature_fromstr
    p(name, default)
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 2254, in p
    default_node = RewriteSymbolics().visit(default_node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/ast.py", line 410, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 2246, in visit_Name
    return wrap_value(node.id)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/LOCAL/tjk/python-3.11.0/lib/python3.11/inspect.py", line 2224, in wrap_value
    raise RuntimeError()
RuntimeError
```

# Your environment

- CPython versions tested on: 3.10.8 and 3.11.0
- Operating system and architecture: CentOS 7, x86_64

Built with GCC 12.1.0 and sqlite3 3.37.2

**Comment by AlexWaygood** [comment] 2022-11-02 12:11
I get a different traceback on my Windows machine on `main` (but still not good):

```pycon
C:\Users\alexw\coding\cpython>python
Running Debug|x64 interpreter...
Python 3.12.0a1+ (main, Oct 26 2022, 12:45:55) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> help(sqlite3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\coding\cpython\Lib\_sitebuiltins.py", line 102, in __call__
    import pydoc
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 70, in <module>
    import sysconfig
  File "C:\Users\alexw\coding\cpython\Lib\sysconfig.py", line 5, in <module>
    import threading
  File "C:\Users\alexw\coding\cpython\Lib\threading.py", line 36, in <module>
    _daemon_threads_allowed = _thread.daemon_threads_allowed
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module '_thread' has no attribute 'daemon_threads_allowed'
```

**Comment by AlexWaygood** [comment] 2022-11-02 13:56
This bisects to a3d4d15f53777662ce0957500e5a538ce7161f5e on `main`, and 5d3f2fbf37cd8faa9830490ac244b051d3879990 on the 3.11 branch. That's these PRs:

- #95146
- #95158

Both PRs are linked to:

- #95132

Cc. @erlend-aasland

**Comment by AlexWaygood** [comment] 2022-11-02 16:12
I was curious, so I ran the following script to see if `help(module)` failed for any other stdlib modules:

<details>
<summary>Click to see the script </summary>

```python
import io
import sys
import warnings
from contextlib import redirect_stdout

warnings.filterwarnings("ignore", category=DeprecationWarning)

bad_modules, unimportable_modules = [], []

for name in sys.stdlib_module_names:
    if name in {"antigravity", "this"}:
        continue  # no
    try:
        mod = __import__(name)
    except:
        unimportable_modules.append(name)
        continue
    with redirect_stdout(io.StringIO()):
        try:
            help(mod)
        except:
            bad_modules.append(name)

print(f"Modules with broken help: {bad_modules}")
print(f"Unimportable modules: {unimportable_modules}")
```

</details>

Results on my Windows machine:

```
Modules with broken help: ['_ssl', 'sqlite3', '_sqlite3']
Unimportable modules: ['resource', 'crypt', 'curses', 'posix', 'grp', '_crypt', '_scproxy', '_posixshmem', 'readline', 'tty', 'pwd', 'nis', '_gdbm', '_dbm', 'termios', 'syslog', '_posixsubprocess', 'pty', 'fcntl', '_curses', 'spwd', '_curses_panel', 'ossaudiodev']
```

`python -c "import _ssl; help(_ssl)"` crashes with a very similar traceback:

<details>
<summary>Click to see the traceback</summary>

```
C:\Users\alexw\coding\cpython>python -c "import _ssl; help(_ssl)"
Running Debug|x64 interpreter...
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 2207, in wrap_value
    value = eval(s, module_dict)
            ^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'Encoding' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 2210, in wrap_value
    value = eval(s, sys_module_dict)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'Encoding' is not defined. Did you mean: 'encodings'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\alexw\coding\cpython\Lib\_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 2001, in __call__
    self.help(request)
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 2062, in help
    else: doc(request, 'Help on %s:', output=self._output)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 1783, in doc
    pager(render_doc(thing, title, forceload))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 1777, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 479, in document
    if inspect.ismodule(object): return self.docmodule(*args)
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 1268, in docmodule
    contents.append(self.document(value, key, name))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 480, in document
    if inspect.isclass(object): return self.docclass(*args)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 1434, in docclass
    attrs = spill("Methods %s:\n" % tag, attrs,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 1383, in spill
    push(self.document(value,
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 481, in document
    if inspect.isroutine(object): return self.docroutine(*args)
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\pydoc.py", line 1493, in docroutine
    signature = inspect.signature(object)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 3264, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 3008, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 2500, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 2312, in _signature_from_builtin
    return _signature_fromstr(cls, func, s, skip_bound_arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 2260, in _signature_fromstr
    p(name, default)
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 2242, in p
    default_node = RewriteSymbolics().visit(default_node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\ast.py", line 413, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 2229, in visit_Attribute
    return wrap_value(value)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\inspect.py", line 2212, in wrap_value
    raise RuntimeError()
RuntimeError
```

**Comment by erlend-aasland** [comment] 2022-11-02 17:18
@AlexWaygood: Nice. A possible enhancement for the check-modules script that's run at the end of the build?

**Comment by erlend-aasland** [comment] 2022-11-13 11:41
Part of the problem is inconsistencies in the docstrings themselves. I've fixed these, but the problems still persist. I suspect a bug in `inspect`.

**Comment by erlend-aasland** [comment] 2022-11-13 11:46
See also gh-83685

**Comment by erlend-aasland** [comment] 2022-11-13 11:58
> See also [gh-83685](https://github.com/python/cpython/issues/83685)

I confirm that the fix for the above issue, gh-98796, resolves the remaining problems reported in this issue.

**Comment by erlend-aasland** [comment] 2022-11-13 12:50
Duplicate of gh-83685

**Closed as not planned by erlend-aasland** 2022-11-13 12:50 UTC
Labels: type-bug, 3.11, 3.12, topic-sqlite3
