### ISSUE TITLE
pathlib behaviour with filenames ending with '.'

### ISSUE THREAD

**Issue by batmanfeynman** [python/cpython#100157] opened 2022-12-10 09:56 UTC
# Bug report

Current pathlib module behaviour:
```pycon
>>> x = pathlib.Path('file/example.test.')
>>> x.suffix
''
>>> x.suffixes
[]
>>> x.stem
'example.test.'
```
Expected behaviour:
```pycon
>>> x = pathlib.Path('file/example.test.')
>>> x.suffix
'.'
>>> x.suffixes
['.test','.']
>>> x.stem
'example.test'
```

I think there should be a discussion around the expected behaviour. But the most important bit is that when there are multiple periods in a file name and the file ends with a period, at least the suffixes before the last empty one should be returned! 

Or at least this behaviour should be explicitly documented!

# My environment

Python 3.10.8 (main, Nov 14 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux

Although, if you look at the source [here](https://github.com/python/cpython/blob/7c0fb71fbfa8682f56c15832e2c793a6180f2ec0/Lib/pathlib.py#L555) you can see that it is present in the latest commit on main!

**Comment by eryksun** [comment] 2022-12-10 18:45
This behavior hasn't changed since pathlib was added in [3.4.0b1](https://github.com/python/cpython/blob/v3.4.0b1/Lib/pathlib.py#L717-L734). The tests haven't changed either between [3.4.0b1](https://github.com/python/cpython/blob/v3.4.0b1/Lib/test/test_pathlib.py#L460-L497) and [main](https://github.com/python/cpython/blob/d5f8a2b6ad408368e728a389da918cead3ef7ee9/Lib/test/test_pathlib.py#L520-L557). 

It's documented that `PurePath.stem` and `PurePath.suffix` are equivalent to [`os.path.splitext()`](https://docs.python.org/3/library/os.path.html#os.path.splitext). That needs clarification in at least the following two cases.

A path that ends with a dot:

```pycon
>>> os.path.splitext('spam.')
('spam', '.')
>>> pathlib.Path('spam.').suffix
''
```

A name that begins with more than one dot:

```pycon
>>> os.path.splitext('..spam')
('..spam', '')
>>> pathlib.Path('..spam').suffix
'.spam'
```

On Windows, note that dots and spaces are stripped from the end of a path when it's opened, unless it's an extended path (i.e. a path that begins with the prefix "\\\\?\\"). Also, dots and spaces are stripped from the end of a path, even an extended path, when it's explicitly resolved and normalized by WinAPI `GetFullPathNameW()`, which `ntpath.abspath()` calls when running on Windows.

**Comment by batmanfeynman** [comment] 2022-12-11 07:34
Since windows treats trailing dots and spaces differently from linux(and i suppose the other unix like OSes are like linux), can we not have different behaviour based on whether it is a PosixPath or a WindowsPath? For example WindowsPath is case insensitive while PosixPath is not as mentioned in the docuemntation!

**Comment by batmanfeynman** [comment] 2022-12-11 07:47
The following behaviour is also undesirable based on @eryksun 's comment on how windows deals with trailing spaces and dots
```
>>> PureWindowsPath('hello/test.txt') == PureWindowsPath('hello/test.txt  ')
False
>>> PureWindowsPath('hello/test.txt') == PureWindowsPath('hello/test.txt...')
False
```

But since I can create files on linux with trailing spaces and dots, the following behaviour is good:
```
>>> PurePosixPath('hello/test.txt') == PurePosixPath('hello/test.txt ')
False
>>> PurePosixPath('hello/test.txt') == PurePosixPath('hello/test.txt...')
False
```

**Comment by batmanfeynman** [comment] 2022-12-11 07:57
Also, I am not sure whether this is the right place to mention it, but I think an `add_suffix` method will complement the current `with_suffix` method. The difference being that `add_suffix` will _always_ add a suffix!

**Comment by batmanfeynman** [comment] 2022-12-11 08:04
I will try to make some changes to the source to see if it can all be resolved!

**Comment by eryksun** [comment] 2022-12-11 09:02
For 3.10 and 3.11, it's just a documentation issue. The `suffix()`, `suffixes()` and `stem()` methods have always behaved this way for a trailing dot, and it's clearly intentional and tested. Changing the behavior in 3.12 to align with `os.path.splitext()` may be possible, but I'd wait for agreement from people who are actively working on pathlib, particularly @barneygale.

**Comment by barneygale** [comment] 2022-12-12 16:10
This has come up before: #82805

I'm weakly in favour of aligning with `splitext()`. Perhaps I'm lacking imagination, but I can't think of a case where someone would rely on the existing `suffix` behaviour in this case.

**Comment by GUNnibal** [comment] 2023-05-06 09:50
I think it's worth mentioning that having a file **without a stem** but with a suffix leads to somewhat unexpected behavior as well, if you use `.suffix` and `.stem` attributes with that file's Path. 
For context: XLSX files consist mostly of xml files, and one of them is named ".rels". The OS itself (Windows 10 in my case) recognizes this file correctly and understands that there is no stem here but a suffix is present. Pathlib, on the other hand, believes the opposite: suffix in considered empty, ".rels" is considered a stem.

While this is a very niche case, I think the bigger issue is, I suspect, Pathlib assumes:
-it's possible for a file to have no suffix and some stem
-it's impossible for a file to have a suffix but no stem
The second assumption is simply false.

**Comment by barneygale** [comment] 2023-05-06 13:06
Filenames that begin with a period but have no extension are commonplace on non-Windows systems, e.g. `.bashrc`, `.ssh`, `.htaccess` etc. I'm not sure how pathlib could distinguish those from your `.rels` files.

**Comment by eryksun** [comment] 2023-05-06 13:41
`os.path.splitext()` also assumes that a file can't have a suffix if it has no stem. This is because of a convention on Unix systems that dot files and dot directories such as ".bashrc" and ".config" are 'hidden'. Windows does not abide this convention at either the API level or the shell level, so this is a case of Python forcing a Unix convention on a non-Unix platform.

The preferred platform behavior on Windows is crystal clear. Windows shells such as Explorer, CMD, and PowerShell do not automatically hide dot files and dot directories from a directory listing. WinAPI `PathCchFindExtension()`, `PathCchRenameExtension()`, and `PathCchRemoveExtension()` operate on a filename that only has an extension. WinAPI `CreateProcessW()` spawns the `%ComSpec%` shell for a file named ".bat" or ".cmd", and `ShellExecuteExW()` (e.g. `os.startfile()`) executes a filename that only has an extension, such as ".txt".

**Comment by Ravencentric** [comment] 2023-10-11 18:39
Dealing with some arbitrary file/folder names, I encountered something similar:
```py
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
>>> from pathlib import Path
>>> path = Path(r"C:\Users\Username\Documents\My.Project.Files") # directory
>>> path.stem
'My.Project'
>>> path.name
'My.Project.Files'
```
Folders with periods throw it off

**Comment by barneygale** [comment] 2024-01-13 20:26
Strictly speaking this issue is a duplicate of #82805, so I'll close it. Thank you for reporting it all the same!

**Closed as not planned by barneygale** 2024-01-13 20:26 UTC
Labels: type-bug, stdlib, topic-pathlib
