### ISSUE TITLE
test.test_decimal is failing when doing a local build on Ubuntu 20.04

### ISSUE THREAD

**Issue by AbhigyanBose** [python/cpython#91839] opened 2022-04-22 20:09 UTC
**Bug report**

Lib.test.test_decimal is failing with the following error when building locally on Ubuntu 20.04:

```
======================================================================
FAIL: test_from_tuple (test.test_decimal.CWhitebox.test_from_tuple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abhigyan/Documents/my-forks/cpython/Lib/test/test_decimal.py", line 5538, in test_from_tuple
    self.assertEqual(str(c.create_decimal(x)), '-0E-1000007')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: '-0E-1000026' != '-0E-1000007'
- -0E-1000026
?          ^^
+ -0E-1000007
?          ^^

```
Steps to recreate: 
1. Use fresh install of Ubuntu 20.04 (64-bit).
2. Install `build-essential` from apt.
3. clone python from github, 
4. execute `./configure --with-pydebug`
5. execute `make -s -j2`
6. execute `./python -m test -v test_decimal -j2`

**Your environment**
Ubuntu 20.04 fresh install followed by installing build-essential.

CPython versions tested on:
lastest version from github

Commit which causes the error:
https://github.com/python/cpython/commit/bcf14ae4336fced718c00edc34b9191c2b48525a

Testing to find commit: 
Used git bisect to test commits using steps 4-6 as mentioned above in Steps to recreate (used make clean before each build).

Above issue does not arise in commit:
https://github.com/python/cpython/commit/5e130a8da4e4f13444ec20dfe88a3e2e070005ca

**Comment by JelleZijlstra** [comment] 2022-04-22 20:10
Duplicate of #91821

**Closed as completed by JelleZijlstra** 2022-04-22 20:10 UTC
Labels: type-bug
