### ISSUE TITLE
Library page for os now seems to have almost the whole module being a "Note"

### ISSUE THREAD

**Issue by juliangilbey** [python/cpython#95659] opened 2022-08-04 16:08 UTC
# Documentation

Something seems to be wrong with the formatting of this page.  There's nothing obvious in the source code, though, which suggests why this might be the case.  Here's a snapshot:

![os-snapshot](https://user-images.githubusercontent.com/1658936/182895029-b5ffdff0-7b86-4550-9acf-4b52cdbd93b8.png)

The greyed Note region should just be one paragraph.

**Comment by juliangilbey** [comment] 2022-08-04 16:10
Oh, I should have looked at the HTML as well.  It's really strange:
```html
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>All functions in this module raise <a class="reference internal" href="[exceptions.html#OSError](view-source:https://docs.python.org/3/library/exceptions.html#OSError)" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a> (or subclasses thereof) in
the case of invalid or inaccessible file names and paths, or other arguments
that have the correct type, but are not accepted by the operating system.</p>
</aside>
```
What is that `</aside>` tag about?  It should be `</div>`.

**Comment by erlend-aasland** [comment] 2022-08-04 16:11
Thanks for the report. This is a duplicate of #91483.

**Closed as not planned by erlend-aasland** 2022-08-04 16:11 UTC
Labels: docs
