### ISSUE TITLE
argparse mis-handles a store_true option in between two nargs="?" positionals

### ISSUE THREAD

**Issue by zackw** [python/cpython#121282] opened 2024-07-02 17:44 UTC
# Bug report

### Bug description:

Consider the following cut-down script:

```python
import argparse
import pprint

ap = argparse.ArgumentParser()
ap.add_argument("p", nargs="?")
ap.add_argument("q", nargs="?")
ap.add_argument("--test", action="store_true")

args = ap.parse_args()
pprint.pprint(args.__dict__)
```

When invoked with two positional arguments and `--test` on either side of them, the behavior is as expected:

```none
$ python3 test.py --test a b
{'p': 'a', 'q': 'b', 'test': True}
$ python3 test.py a b --test
{'p': 'a', 'q': 'b', 'test': True}
```

However, if you put `--test` in between the two positionals, argparse misinterprets the argument list:

```none
$ python3 test.py a --test b
usage: test.py [-h] [--test] [p] [q]
test.py: error: unrecognized arguments: b
```

This argument list should produce the same Namespace object as the first two examples.

### CPython versions tested on:

3.9, 3.11, 3.12

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment] 2024-10-11 10:38
This is a duplicate of #59317 and has already been fixed.

**Closed as not planned by serhiy-storchaka** 2024-10-11 10:38 UTC
Labels: type-bug
