### ISSUE TITLE
URLLIB3 Issue 

### ISSUE THREAD

**Issue by DannyBrock123** [python/cpython#105176] opened 2023-06-01 00:37 UTC
- CPython versions tested on:
- Operating system and architecture: Windows 10 64x Home eddtion 

<!--
You can freely edit this text. Remove any lines you believe are unnecessary.

**Main issue**

So, I was using python like a normal person. And the next day when I turned on my computer, I got this error when I launched my program.

C:\Users\marka\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (2.0.2) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
  
  This never happened before, I deleted and reinstalled URLLIB3 and even uninstalled Python and reinstalled it. But it's still here, and it's really annoying me. 
  
  If someone can help me with this thanks.

**Comment by DannyBrock123** [comment] 2023-06-01 00:38
For some odd reason it wont show my issue report, so I'm gonna send it here 

So, I was using python like a normal person. And the next day when I turned on my computer, I got this error when I launched my program.

C:\Users\marka\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (2.0.2) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
  
  This never happened before, I deleted and reinstalled URLLIB3 and even uninstalled Python and reinstalled it. But it's still here, and it's really annoying me. 
  
  If someone can help me with this thanks.

**Comment by DannyBrock123** [comment] 2023-06-01 00:43
Nevermind, I got it fixed. 

I used these below: 

pip install --upgrade urllib3
pip install --upgrade chardet
pip install --upgrade charset_normalizer

Or for Python3

pip3 install --upgrade urllib3
pip3 install --upgrade chardet
pip3 install --upgrade charset_normalizer

_(Thanks to ChatGPT)_

**Comment by baseplate-admin** [comment] 2023-06-01 02:04
If the issue is resolved, would you mind closing it?

**Closed as not planned** 2023-06-01 02:21 UTC
Labels: type-bug
