### ISSUE TITLE
code.interact() will exit the whole process when given exit() or quit() 

### ISSUE THREAD

**Issue by GauravN123** [python/cpython#102929] opened 2023-03-22 19:05 UTC
When you call code.interact() in Python, you are starting an interactive console that allows you to execute Python code and inspect variables in the current context.

If you call the exit() or quit() functions within the code.interact() console, it will exit not just the interactive console, but the entire Python process that launched it. This is because exit() and quit() are built-in functions that cause the Python interpreter to exit.

If you want to exit just the interactive console and return to the original context, you can use the CTRL+D keyboard shortcut or call raise SystemExit instead.

**Comment by zware** [comment] 2023-03-22 19:45
Duplicate of gh-102895

**Closed as not planned by zware** 2023-03-22 19:45 UTC
Labels: type-feature
