### ISSUE TITLE
pyatomic_gcc.h with GCC discards const qualifier 

### ISSUE THREAD

**Issue by ndparker** [python/cpython#120593] opened 2024-06-16 19:40 UTC
# Bug report

### Bug description:

Hi,

including Python.h with gcc and -Wcast-qual raises the following issue (Regression from 3.12):

```
    /usr/include/python3.13/cpython/pyatomic_gcc.h: In function '_Py_atomic_load_ptr':
    /usr/include/python3.13/cpython/pyatomic_gcc.h:300:34: error: cast discards 'const' qualifier from pointer target type [-Werror=cast-qual]
      300 | { return (void *)__atomic_load_n((void **)obj, __ATOMIC_SEQ_CST); }
          |                                  ^
    /usr/include/python3.13/cpython/pyatomic_gcc.h: In function '_Py_atomic_load_ptr_relaxed':
    /usr/include/python3.13/cpython/pyatomic_gcc.h:359:34: error: cast discards 'const' qualifier from pointer target xt (line 8))
```

```shell
$ python3.13 -V
Python 3.13.0b1
```

This is a follow-up to https://github.com/python/cpython/issues/120293

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-121052
* gh-121053
* gh-121055
* gh-121057
* gh-121081
* gh-122367

**Comment by picnixz** [comment] 2024-06-17 08:55
For the record, this is not the only place where const qualifiers are lost. If you compile cpython with `make CFLAGS=-Wcast-qual -j12` you end up with a lot of warnings. For the line 359, the fix would be:

```diff
// pyatomic_gcc.h
static inline const void *
_Py_atomic_load_ptr_relaxed(const void *obj)
-{ return (void *)__atomic_load_n((void **)obj, __ATOMIC_RELAXED); }
+{ return (const void *)__atomic_load_n((const void * const *)obj, __ATOMIC_RELAXED); }
```

As you can see you lose constness twice, namely when calling `__atomic_load_n` and when returning the type. Note that we have

```C
// pyatomic_std.h
static inline void*
_Py_atomic_load_ptr_relaxed(const void *obj)
{
    _Py_USING_STD;
    return atomic_load_explicit((const _Atomic(void*)*)obj,
                                memory_order_relaxed);
}
```

As you can see, the cast here is essentially using a `const void **`, but still the return type should be a const as well (in the case of `__atomic_load_n`, the signature is `type __atomic_load_n(type *ptr, int memorder);`).

**Comment by ndparker** [comment] 2024-06-17 17:24
Yes, I'd like to clarify that this is specifically not about compiling CPython, it's about including Python.h only.

**Comment by picnixz** [comment] 2024-06-18 09:10
Yes, I understood that from the other issue but since you only mentioned 2 lines, I wanted to 1) give a way to fix it 2) say that it's not just 2 lines that are affected but a lot of calls.

**Comment by vstinner** [comment] 2024-06-27 10:29
The warnings were fixed by https://github.com/python/cpython/commit/9cd2dcbb87fb3c35d8ca3554d9472ac283f62a64 and https://github.com/python/cpython/commit/e51e880e75d79687b54a71351266e29ee349b4b8.

I also added a check in test_cext for check for non-regression: https://github.com/python/cpython/commit/b7a95dfee30aae171de47f98ed3b7d1cc08e5bd4.

Thanks @ndparker for your bug report. It's now fixed, I close the issue.

**Closed as completed** 2024-06-27 10:29 UTC
Labels: type-bug

**Comment by markshannon** [comment] 2024-07-15 08:39
I don't think weakening the type of calls that should be `const` is the correct thing to do here.
Where there is a conflict in types we should be strengthening the type, not weakening it.
Why not strengthen the types in the callees, rather than weakening them in the callers?

**Comment by vstinner** [comment] 2024-07-27 20:24
@markshannon:
> I don't think weakening the type of calls that should be const is the correct thing to do here.

If you're talking about _PyLong_CompactValue(): I wrote PR gh-122367 to restore the const modifier.

If you're talking about something else, please elaborate which function/code you are referring to.
