### ISSUE TITLE
Round Function Issue

### ISSUE THREAD

**Issue by ghost** [python/cpython#125160] opened 2024-10-08 21:44 UTC
# Bug report

### Bug description:

When using the round function, there is an issue when I try to round the floating-point number that has a even number to the left of the decimal, and 5 to right of the decimal. For example 2.5, 4.5, 6.5 etc... Instead of rounding the number up , it rounds the number down. Example: Instead of rounding 2.5 up to 3, it rounds it down to 2. As I mentioned, this only happens to the even number. For odd numbers, it actually rounds the odd number up. Example: 3.5 will be rounded up to 4

```
print(round(2.5))
print(round(3.5))
print(round(4.5))
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by hugovk** [comment] 2024-10-08 21:52
Duplicate of https://github.com/python/cpython/issues/125155:

This is [documented behavior](https://docs.python.org/3/library/functions.html#round):

> if two multiples are equally close, rounding is done toward the even choice (so, for example, both round(0.5) and round(-0.5) are 0, and round(1.5) is 2)

See also [this SO question](https://stackoverflow.com/q/10825926).

**Comment by efimov-mikhail** [comment] 2024-10-08 21:53
It's not a big, round function is designed this way:

"For the built-in types supporting [round()](https://docs.python.org/3/library/functions.html#round), values are rounded to the closest multiple of 10 to the power minus ndigits; if two multiples are equally close, rounding is done toward the even choice (so, for example, both round(0.5) and round(-0.5) are 0, and round(1.5) is 2)."

**Closed as not planned by hugovk** 2024-10-08 21:52 UTC
Labels: type-bug

**Comment by chris-abshire** [comment] 2024-10-08 21:56
Thanks to those who commented on this. It seems weird how the function was programmed to round that way, but I understand it now. Thanks again.

**Comment by skirpichev** [comment] 2024-10-09 02:11
It's not "weird", see https://en.wikipedia.org/wiki/Rounding#Rounding_half_to_even

This is the default rounding mode used in IEEE 754.
