### ISSUE TITLE
bisect.bisect is not cross-referenced properly

### ISSUE THREAD

**Issue by Gobot1234** [python/cpython#104145] opened 2023-05-03 22:49 UTC
# Documentation

The documentation page for bisect includes lots of interlinks to the bisect function but it appears that link isn't being resolved correctly by sphinx, whilst it thinks it is a function, it links to the module header

To reproduce: https://docs.python.org/3/library/bisect.html#searching-sorted-lists, click on `bisect()` and see it take you to the top of the page and not to the function bisect

### Linked PRs
* gh-104172
* gh-104295

**Comment by Lincoln-developer** [comment] 2023-05-04 10:20
Hey @Gobot1234  and @hauntsaninja ,am kindly requesting to work on this if it is possible. Thanks and kind regards.

**Comment by Gobot1234** [comment] 2023-05-04 11:35
I would have done it myself but I'm not even sure where the issue lies as the documentation uses the func role which probably means sphinx is broken

**Comment by Lincoln-developer** [comment] 2023-05-04 11:49
okay then, how can we go about fixing this

**Comment by AA-Turner** [comment] 2023-05-04 12:43
James is right, this is an issue in Sphinx. Removing the 'easy' label.

A

**Comment by AA-Turner** [comment] 2023-05-04 13:01
It just means that it isn't entirely straightforwards; to find other documentation issues labelled as easy you can look here: is:issue is:open label:easy label:docs 

A

**Comment by Lincoln-developer** [comment] 2023-05-04 13:04
thanks @AA-Turner, let me look through and see where to begin from.

**Comment by AA-Turner** [comment] 2023-05-04 14:23
@Gobot1234 -- the issue is the default cross reference resolution order from Sphinx. See https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-py-obj for an explanation, but in essence a standard cross reference role (e.g. `:py:func:`, `:meth:`, etc) performs a lookup *ignoring* the cross-reference type specified. For instance, in our case this means that the `` :func:`bisect` `` role here tries to resolve an object with the name ``bisect`` first, and succeeds when it finds the reference to the ``bisect`` module.

I'm not sure why cross-reference resolution was implemented with this behaviour, but in the spirit of Chesterton's fence I'm hesitant to change it. It does seem odd though that the explicit type specified is ignored by the resolution machinery: https://github.com/sphinx-doc/sphinx/blob/ba7408209e84ee413f240afc20f3c6b484a81f8f/sphinx/domains/python.py#L1344-L1356

I'll put up a PR with an (inelegant) fix, but this likely affects the other modules with an eponymous object.

A

**Comment by AlexWaygood** [comment] 2023-05-08 16:44
Fixed and backported. I'll close this for now; we can open a followup issue if we find other instances of this problem occuring.

**Closed as completed by AlexWaygood** 2023-05-08 16:44 UTC
Labels: type-bug, docs, 3.11, 3.12, 3.13
