### ISSUE TITLE
Allow bitwise operations between bytes objects of the same size

### ISSUE THREAD

**Issue by noamcohen97** [python/cpython#95361] opened 2022-07-28 08:48 UTC
# Feature or enhancement

Allow bitwise operations between bytes objects of the same size.
e.g.:
```python
b'value1' ^ b'value2' == b'\x00\x00\x00\x00\x03'
```

# Pitch

Bitwise operations involving long buffers are pretty common task when dealing with things such as cipher.
Pure Python implementations of this kind of things often implement their own `xor` function using `zip()` ([pyaes](https://github.com/ricmoo/pyaes/blob/23a1b4c0488bd38e03a48120dfda98913f4c87d2/pyaes/aes.py#L468)).
This leads to very poor performances.

```bash
$ ./python -m timeit -n 1000 -s 'import os; a = os.urandom(1024*1024); b = os.urandom(1024*1024)' 'bytes(x ^ y for x, y in zip(a, b))'
1000 loops, best of 3: 65 msec per loop
```

**Even with the most naive implementation in CPython**
```bash
$ ./python -m timeit -n 1000 -s 'import os; a = os.urandom(1024*1024); b = os.urandom(1024*1024)' 'a ^ b'
1000 loops, best of 5: 536 usec per loop
```
More than 120 times faster

**Comment by erlend-aasland** [comment] 2022-07-28 10:51
Duplicate of #63450

**Comment by erlend-aasland** [comment] 2022-07-28 10:55
I suggest you study the pros and cons from the previous discussion. If you choose to pursue this idea, please continue on that issue :)

Closing as a duplicate.

**Comment by erlend-aasland** [comment] 2022-07-28 10:56
(You can retarget your PR to the older issue.)

**Closed as not planned by erlend-aasland** 2022-07-28 10:55 UTC
Labels: type-feature
