### ISSUE TITLE
Null characters in strings cause a C SystemError

### ISSUE THREAD

**Issue by apccurtiss** [python/cpython#97556] opened 2022-09-26 07:30 UTC
# Crash report

Putting a null byte into a Python string causes a SystemError in Python 3.10, due to a call to strlen in the string parsing library. In Python 3.9, the following example runs without errors:

```
# -*- coding: latin-1 -*-
"""
<NULL>
"""
```

In Python 3.10, it raises `SystemError: ../Parser/string_parser.c:219: bad argument to internal function`.

Internally, the new string_parser library introduced in v3.10.0a1 uses a call to strlen to determine the string size, which is getting thrown off by the null byte. This call is actually unnecessary, as the length has already been calculated by the calling parser and can be retrieved with `PyBytes_AsStringAndSize`.

# Error messages

For single line strings, the error is `SystemError: Negative size passed to PyUnicode_New`

For multiline strings, the error is `SystemError: ../Parser/string_parser.c:219: bad argument to internal function`

### Linked PRs
* gh-104136

**Comment by vstinner** [comment] 2022-09-26 07:57
This issue seems like a duplicate of the issue #96670.

**Comment by apccurtiss** [comment] 2022-09-26 08:02
Ah, you're totally right. I found that one earlier, but misunderstood the core bug and re-discovered it. Thanks!

**Comment by apccurtiss** [comment] 2022-09-26 08:07
Actually, I just re-read that issue, and I was a bit over-eager with closing this. I feel like this is a very specific fix which doesn't actually solve their use case: This particular issue only shows up in 3.10, and causes an internal parse error. That linked issue is present in every 3.x version I've tested, including after this fix. I believe a patch elsewhere in the parser is needed for that.

**Comment by gvanrossum** [comment] 2022-09-26 14:37
Can you submit a fix?

**Comment by bskinn** [comment] 2023-04-24 23:03
I cannot repro OP's `SystemError` on this. I do observe Python 3.12's fix for null characters in *single-quoted* strings (`SyntaxError: source code cannot contain null bytes` per #97594, when run with 3.12.0a7), so going forward I'm focusing on *triple-quoted* strings.

For Python 3.8.16, 3.9.16, and 3.10.0a1 (Debian local builds), `crasher.py` with the following contents parses *successfully* when executed from the commandline (`$ python3.<#> crasher.py`):

```
<BLANKLINE>
'''
<NUL>
'''
```

For Python 3.10.0b1 (Debian local), 3.10.0 (Debian local), 3.10.11 (Debian local and Win11), 3.11.3 (Debian local and Win11), and 3.12.0a7 (Debian local), parsing *fails* with `SyntaxError: unterminated triple-quoted string literal`.

Interestingly, the attributed line number of the exception location changes in 3.12.0a7. It's reported as line 3 in 3.12.0a7, and as line 2 for all other versions tested.

Regardless, the triple-quoted string case is ***not yet fixed*** in the fashion indicated by https://github.com/python/cpython/issues/96670#issuecomment-1260161574, where strings containing null characters are explicitly rejected with an exception and message like `SyntaxError: source code cannot contain null bytes`.

**Comment by bskinn** [comment] 2023-04-25 01:58
Attn @pablogsal as author of #97594.

**Comment by gvanrossum** [comment] 2023-04-25 03:43
@lysnikolaou ^^

**Comment by lysnikolaou** [comment] 2023-04-25 17:18
I'll have a look at this some time either today or tomorrow during the sprints.

**Comment by vstinner** [comment] 2023-05-04 13:12
Script to reproduce the issues:

```py
with open("script.py", "w") as fp:
    print("# -*- coding: latin-1 -*-", file=fp)
    print('"""', file=fp)
    print('\0', file=fp)
    print('"""', file=fp)
```

Current behavior:

* main branch (3.12): SyntaxError: unterminated triple-quoted string literal (detected at line 3)
* 3.11: SystemError: Parser/string_parser.c:230: bad argument to internal function

Oh, it seems like the main branch was just changed (40 min ago) by PR #104136 (just merged).

@lysnikolaou: Do you consider backporting your change to Python 3.11?

**Comment by bskinn** [comment] 2023-05-04 13:51
With the merge of #97594 and #104136, I believe what OP has raised is now resolved in `main`/3.12, and per https://github.com/python/cpython/issues/96670#issuecomment-1260161574 the changes are not to be backported.

Thus, I think this issue can be closed.

**Comment by vstinner** [comment] 2023-05-04 13:55
``SystemError: Parser/string_parser.c:230: bad argument to internal function`` sounds like a bug in Python.

It's not as if Python 3.11 accepts NUL characters. The question is more about providing a better error message if it finds a NUL character.

**Comment by bskinn** [comment] 2023-05-04 14:12
It was @gvanrossum's call not to backport the original fix, and I wouldn't presume to speak authoritatively for him. But, I assume the motivation is the [xkcd 1172](https://xkcd.com/1172/) aspect of changing the error message string.

**Comment by pablogsal** [comment] 2023-05-04 14:16
I think we should backport this to 3.11

**Comment by gvanrossum** [comment] 2023-05-04 14:27
Okay let’s backport.

**Comment by bskinn** [comment] 2023-05-04 14:48
Should #97594 be backported also, then?

**Comment by lysnikolaou** [comment] 2023-05-04 15:26
Backporting both makes the most sense to me, since just improving the error message would require much more work with the tokenizer buffer working the way it is. If no one has any serious concerns over this, I can work on backporting the necessary PRs.

**Comment by pablogsal** [comment] 2023-05-04 15:30
> Backporting both makes the most sense to me, since just improving the error message would require much more work with the tokenizer buffer working the way it is. If no one has any serious concerns over this, I can work on backporting the necessary PRs.

Yeah, I prefer to backport the restriction to keep the changes to a minimum in 3.11 as making a bugfix for the error message can be much more complex 👍

**Comment by lysnikolaou** [comment] 2023-05-07 11:54
Raising a `SyntaxError` when parsing NULL bytes has been backported to 3.11. I'm closing this.

**Closed as completed by lysnikolaou** 2023-05-07 11:54 UTC
Labels: 3.11, 3.10, 3.9 (EOL), type-crash, 3.12

**Comment by vstinner** [comment] 2023-05-09 22:32
I confirm that 3.11 and main branches now display the same output for ``./python script.py`` (see https://github.com/python/cpython/issues/97556#issuecomment-1534758484 to generate script.py).

```
  File "/home/vstinner/python/main/../3.11/script.py", line 3
    
SyntaxError: source code cannot contain null bytes
```
