### ISSUE TITLE
``test_strptime`` raises a DeprecationWarning

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#117655] opened 2024-04-08 20:27 UTC
# Bug report

### Bug description:

```pytb
./python -m test -v test_strptime
== CPython 3.13.0a5+ (heads/main:ac45766673, Apr 8 2024, 23:14:32) [GCC 9.4.0]
== Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31 little-endian
== Python build: debug
== cwd: /home/eclips4/CLionProjects/cpython/build/test_python_worker_28987æ
== CPU count: 16
== encodings: locale=UTF-8 FS=utf-8
== resources: all test resources are disabled, use -u option to unskip tests

Using random seed: 3103978630
0:00:00 load avg: 29.90 Run 1 test sequentially
0:00:00 load avg: 29.90 [1/1] test_strptime
test_TimeRE_recreation_locale (test.test_strptime.CacheTests.test_TimeRE_recreation_locale) ... sys:1: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
skipped 'test needs de_DE.UTF8 locale'
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-117668
* gh-118956

**Comment by nineteendo** [comment] 2024-04-09 07:49
So, we just need to do this? Can I make a pull request for that?

```diff
-_strptime._strptime_time("10", "%d")
+_strptime._strptime_time("10 2004", "%d %Y")
```

**Comment by Eclips4** [comment] 2024-04-09 09:48
Yes, that's looks good to me. I'm dislike the approach of catching `DeprecationWarning` because in future versions it can raise an exception.

**Comment by Eclips4** [comment] 2024-04-09 09:53
However, there's also a similar warning in the `test_datetime`:
```python
./python.exe -m test -q test_datetime
Using random seed: 2525252452
0:00:00 load avg: 41.62 Run 1 test sequentially
sys:1: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
sys:1: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
sys:1: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
sys:1: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
sys:1: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
sys:1: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.

== Tests result: SUCCESS ==

Total duration: 3.6 sec
Total tests: run=1,012 skipped=28
Total test files: run=1/1
Result: SUCCESS
```

**Comment by nineteendo** [comment] 2024-04-09 11:55
That's caused by the tests of #70647:

https://github.com/python/cpython/blob/22b25d1ebaab7b8c4833a8c120c8b4699a830f40/Lib/test/datetimetester.py#L2796-L2807

**Comment by nineteendo** [comment] 2024-04-09 12:03
And we also have these tests that will still raise a DeprecationWarning:

https://github.com/python/cpython/blob/22b25d1ebaab7b8c4833a8c120c8b4699a830f40/Lib/test/test_strptime.py#L500-L506

Those will have to be removed in 3.15.

**Comment by erlend-aasland** [comment] 2024-04-09 20:55
See commit 33ee5cb3e92ea8798e7f1a2f3a13b92b39cee6d6. Please follow the existing practice for how to deal with deprecation warnings in tests. See Greg's commit for inspiration. There also `test.support.warnings_helper.ignore_warnings`.

**Comment by nineteendo** [comment] 2024-04-09 21:46
Yeah, `test.support.warnings_helper.ignore_warnings()` works here. (It even works on tests checking for deprecation warnings).
I've added it to the functions were necessary, and updated the others to not use the deprecated behaviour.

**Comment by nineteendo** [comment] 2024-05-09 14:31
@Eclips4 can you review this, or should I ask on Discourse right away? erlend-aasland said he's not going to review this.

**Comment by Eclips4** [comment] 2024-05-09 14:37
> @Eclips4 can you review this, or should I ask on Discourse right away? erlend-aasland said he's not going to review this.

Will do it later today. Please note that before merging, we should also get a review from Greg or Paul.

**Comment by gpshead** [comment] 2024-05-11 21:50
thanks for the PR & pings.  merged!  =)

cpython workflow wise... IIRC we don't have anything in our CI or buildbots treating warnings emitted by the test suite as a _hard_ error so it they can be easily overlooked.  I should've tried to do this with my original PR.

There could be an argument made that test coverage of some code paths without the year specified is important to retain, but I believe we've got enough other explicit intentional tests for that behavior already so this issues PR change still the best way forward.

**Closed as completed by gpshead** 2024-05-11 21:50 UTC
Labels: type-bug, tests
