### ISSUE TITLE
Supporting path-like objects in sys.path

### ISSUE THREAD

**Issue by jeanas** [python/cpython#96482] opened 2022-09-01 18:58 UTC
A lot of Python now accept path-like objects (e.g., everything in `os.path`), but path-like entries in `sys.path` are not supported. Furthermore, against the principle “Errors should never pass silently”, they cause no error or warning but are entirely ignored. Since `sys.path` conceptually contains paths and has "path" in the name, I would like to suggest support for adding path-like objects to it.

**Comment by noamcohen97** [comment] 2022-10-07 22:43
duplicate of #76823

**Closed as not planned** 2022-10-07 22:53 UTC
Labels: type-feature
