### ISSUE TITLE
dis.py hard-codes that ENTER_EXECUTOR is a backwards jump (it isn't always)

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#116972] opened 2024-03-18 21:02 UTC
Since we introduced side exits, ENTER_EXECUTOR doesn't always overwrite a JUMP_BACKWARD opcode -- it may overwrite any other opcode too. This requires changes to the logic of ENTER_EXECUTOR.

CC: @iritkatriel

**Comment by gvanrossum** [comment] 2024-03-18 21:54
Also, the oparg for ENTER_EXECUTOR is printed as the original oparg, whereas it is typically a different value (the index in the code object's array of executors). E.g. in a function with just one executor I'd expect to see
```
    ENTER_EXECUTOR    0
```
but actually I see e.g.
```
    ENTER_EXECUTOR    13
```
where `13` is the oparg of the JUMP_BACKWARD it has overwritten.

**Comment by iritkatriel** [comment] 2024-03-23 13:52
Duplicate of #112383.

**Closed as completed by iritkatriel** 2024-03-23 13:52 UTC
