### ISSUE TITLE
build with openssl failed

### ISSUE THREAD

**Issue by cjdxhjj** [python/cpython#114544] opened 2024-01-25 01:41 UTC
# Bug report

### Bug description:

```python
3.12.1

```
when i use pip to install package, it report the follow error
![image](https://github.com/python/cpython/assets/5616997/b328d785-3ea6-4086-9800-f26d5d6c0246)
after some reasearch, i know it should compile with openssl,
then i download the openssl 3.2 that use perl 5 to compile, i make and install the perl and the make and install the openssl, add the soft link to openssl, and and openssl lib to lib library and reload the ldconf
![image](https://github.com/python/cpython/assets/5616997/f881a6fc-fc2e-4a43-843c-31be5ff73c28)
then i config the python with openssl

./configure --prefix=/usr/local/python3.12 --with-openssl=/usr/local/openssl3.2

when i run the make
![image](https://github.com/python/cpython/assets/5616997/7a55a8d7-1dd5-4192-b679-ce3c288d0535)
the ssl module build failed, why my openssl 3.2 is old than 1.1.1 ?

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by cjdxhjj** [comment] 2024-01-25 01:45
![image](https://github.com/python/cpython/assets/5616997/70640384-7bdf-471d-b274-2ad0687c8997)
![image](https://github.com/python/cpython/assets/5616997/1511356e-b0e5-4c0c-af1d-ecf95d564c52)

**Comment by cjdxhjj** [comment] 2024-01-25 01:46
![image](https://github.com/python/cpython/assets/5616997/824d5781-5d63-4bd8-9e16-d906ddddef73)

**Comment by cjdxhjj** [comment] 2024-01-25 01:48
![image](https://github.com/python/cpython/assets/5616997/4934666e-86ee-4639-8e67-9c4f0667d2d0)
![image](https://github.com/python/cpython/assets/5616997/ccb8cb14-fb5f-4432-ac97-e792cf1163d8)

**Comment by cjdxhjj** [comment] 2024-01-25 01:48
what can i do for it to make my pip to work

**Comment by cjdxhjj** [comment] 2024-01-25 01:49
how to make my pip works?

**Comment by aisk** [comment] 2024-01-25 11:58
I think you specified a wrong path of OpenSSL.

However, since Python 3.12.1 with OpenSSL enabled is widely used, I think this is not a bug in Python. So if you are looking for help, you can go to [discuss](https://discuss.python.org/c/users/7) for help, and feel free to methion me (same user name as GitHub).

**Comment by sunmy2019** [comment] 2024-01-25 17:10
It would help to have the openssl devel tools—headers, libs, etc.

You can `grep ssl config.log` in your python build directory to see the details.

**Comment by sunmy2019** [comment] 2024-01-25 17:12
However, the simplest way is to install `openssl-devel` or `openssl-dev` package from the system package manager.

And I will close this since it's not appropriate for user questions.

**Closed as not planned by sunmy2019** 2024-01-25 17:12 UTC
