### ISSUE TITLE
`TypeError` calling `Traversable.read_text()` via `importlib.resources`

### ISSUE THREAD

**Issue by zooba** [python/cpython#127340] opened 2024-11-27 16:15 UTC
# Bug report

`importlib.resources.abc.Traversable.read_text` [has a signature](https://github.com/python/cpython/blob/main/Lib/importlib/resources/abc.py#L85) that only takes an `encoding` parameter.

`importlib.resources._functional.read_text` [calls it](https://github.com/python/cpython/blob/main/Lib/importlib/resources/_functional.py#L32) passing `errors`.

This, unsurprisingly, causes a `TypeError`. My exact error message is `Traversable.read_text() got an unexpected keyword argument 'errors'`, but I believe it's an instance of `CompatibilityFiles.SpecPath` (as I've never bothered updating this code for the structural changes).

(Ping @jaraco)

**Comment by FFY00** [comment] 2024-11-27 23:36
Duplicate of GH-127012 :smiley:

**Closed as not planned by FFY00** 2024-11-27 23:36 UTC
Labels: type-bug, topic-importlib, 3.13, 3.14
