### ISSUE TITLE
`sock_accept` blocks asyncio tasks

### ISSUE THREAD

**Issue by cykerway** [python/cpython#91780] opened 2022-04-21 08:38 UTC
**Bug report**

Problem: When multiple asyncio tasks call `sock_accept` on the same loop, only one of them will succeed. All other tasks are blocked.

It seems the loop can have at most 1 reader on the same fd at any time. A later reader registration overwrites an earlier one. Could we have a list of readers on the same fd?

MWE: Start this server then run `nc 127.0.0.1 8080 --recv-only` a couple of times. The server has 3 tasks each can accept 5 TCP connections. So it is expected to accept 15 TCP connections. But only the first 5 TCP connections will succeed then the program hangs. The 5 successful connections are all accepted by the same task. Other tasks block on accept.

~~~
import asyncio
import socket

async def accept(sock):
    for i in range(5):
        conn, addr = await asyncio.get_running_loop().sock_accept(sock)
        print(asyncio.current_task().get_name())
        conn.close()

async def main():
    host = '127.0.0.1'
    port = 8080
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.setblocking(False)
    sock.bind(( host, port ))
    sock.listen()
    await asyncio.gather(accept(sock), accept(sock), accept(sock))

asyncio.run(main())
~~~

**Your environment**

- CPython versions tested on: 3.11
- Operating system and architecture: GNU/Linux

### Linked PRs
* gh-116509

**Comment by MauroAntonino** [comment] 2024-02-19 14:25
This bug seems to be already fixed.

**Comment by MauroAntonino** [comment] 2024-02-19 18:06
Hi Guido, it is a great honor to talk with you! I am a huge fan of yours. 
Yes, I tested it! I created a socket client like this one:
```
import socket

HOST = "127.0.0.1"  # The server's hostname or IP address
PORT = 8080  # The port used by the server

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    s.sendall(b"Hello, world")
    data = s.recv(1024)

print(f"Received {data!r}")
```

Then I executed the client script 16 times while running the commented server and I got the following result:
```
start server
Task-4
Task-4
Task-4
Task-4
Task-4
Task-3
Task-3
Task-3
Task-3
Task-3
Task-2
Task-2
Task-2
Task-2
Task-2
```
This seems to be the group of three tasks, each with  five connections, as mentioned in the comment.
I also didn't find a PR related to this issue; it might have been fixed by a PR not related to it.

**Comment by gvanrossum** [comment] 2024-02-19 21:25
If you wanted to, you could use `git bisect` (or manually bisect) to find the commit that fixed it. This would require you to first find a past commit where the example *fails*; the rest follows. The OP claims it was broken in 3.11, so I'd start there. (Or possibly with the commit where the 3.11 branch forked off the main branch; I've found that kind of thing is helpful for `git bisect`.)

**Comment by MauroAntonino** [comment] 2024-02-26 14:44
While attempting to perform this process with other commits, an intriguing situation arose. Initially, across several Python versions, the operation executed perfectly. However, upon using Linux OS rather than Windows, the process hangs as described for any Python version. I am currently trying to figure out what is happening.

**Comment by gvanrossum** [comment] 2024-03-09 00:32
On second thought I wonder if this isn't simply a case of "don't do that"? Why would this be useful functionality?

**Comment by gvanrossum** [comment] 2024-03-11 19:28
If we're talking about why the OP tried multiple tasks accepting on the same socket, we should ask them. But they seem to have left GitHub. My guess is that they were hoping to increase their server's speed by having multiple tasks blocked on accept simultaneously, But I don't actually believe that makes anything faster, since asyncio apps are still single-threaded.

It certainly wasn't about compatibility between Windows and Unix -- that's a red herring, which you only encountered because you attempted to reproduce the issue on Windows. Windows and Unix differ in many details and this is just one. It's not enough of an argument to attempt to "fix" it.

I don't understand what you're saying though -- are you saying that even if there was only one thread calling `sock_accept()`, it would get the same error? If that's not what you're saying, what exactly did you test?

**Comment by MauroAntonino** [comment] 2024-03-11 20:21
Yes, I performed a test with a single thread calling sock_accept(); it encountered Errno 11, but it was handled within the except block.

I have called:

```
await asyncio.gather(accept(sock))
```

and added a warning

```
try:
    conn, address = sock.accept()
    conn.setblocking(False)
except (BlockingIOError, InterruptedError) as e:
    logger.warning(e)
    self._ensure_fd_no_transport(fd)
    handle = self._add_reader(fd, self._sock_accept, fut, sock)
    fut.add_done_callback(
        functools.partial(self._sock_read_done, fd, handle=handle))
```

I've discovered that this errno 11 corresponds to an EAGAIN error, which, as mentioned in this post, is typically retried. -> https://stackoverflow.com/questions/32993000/opening-multiple-unix-domain-sockets-in-node-js-why-do-i-get-eagain-errors

**Comment by gvanrossum** [comment] 2024-03-11 23:12
Mauro, I understand you are new at contributing here. Could you please post a complete (but small) program that shows the code you ran? Saying "I have called `await asyncio.gather(accept(sock))` does not give me enough information to understand what you did or to reproduce it. (I understand what you changed to asyncio, no need to repeat that part.)

**Comment by MauroAntonino** [comment] 2024-03-12 01:19
Ofcourse, this is the server:

```
import asyncio
import socket

async def accept(sock):
    for i in range(5):
        print(asyncio.current_task().get_name())    
        loop  = asyncio.get_running_loop()
        conn, addr = await loop.sock_accept(sock)
        conn.close()
        
async def main():
    host = '127.0.0.1'
    port = 8081
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.setblocking(False)
    sock.bind(( host, port ))
    sock.listen()
    print("start server")
    await asyncio.gather(accept(sock))
    print("end")

asyncio.run(main())
```
and this is the client:
```
import socket

HOST = "127.0.0.1"  # The server's hostname or IP address
PORT = 8081  # The port used by the server

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    s.sendall(b"Hello, world")

```

**Comment by gvanrossum** [comment] 2024-03-13 00:05
@MauroAntonino, here's how you look up errno values:
```
>>> import errno
>>> errno.errorcode[11]
'EDEADLK'
>>> errno.errorcode[35]
'EAGAIN'
```
At least that's what I see on my Mac.

Note that if any syscall reports `EAGAIN`, Python raises `BlockingIOError` instead of `OSError`, since applications often want to treat it differently.

It looks like a red herring though -- the root cause of the OP's problem is that `sock_accept()` registers a callback with the event loop's "selector", and only one callback can be registered per file descriptor. Hence, creating 5 tasks that all call `sock_accept()` for the *same* file descriptor causes all but the last callback (usually that's Task-5 in this example) to be cancelled.

A workaround for the OP would be to use `sock.dup()` to create extra sockets with different file descriptors:
```py
async def accept(sock):
    for i in range(5):
        sock = sock.dup()    # <------------------- HERE
        conn, addr = await asyncio.get_running_loop().sock_accept(sock)
        # Etc.
```

**Comment by MauroAntonino** [comment] 2024-03-13 13:40
Absolutely, Guido! I tested duplicating the socket (sock = sock.dup()), and it successfully resolved the issue highlighted by cykerway.
```
async def accept(sock):
    for i in range(5):
        print(asyncio.current_task().get_name())    
        sock = sock.dup()
        conn, addr = await asyncio.get_running_loop().sock_accept(sock)
        conn.close()
        
async def main():
    host = '127.0.0.1'
    port = 8081
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.setblocking(False)
    sock.bind(( host, port ))
    sock.listen()
    await asyncio.gather(accept(sock), accept(sock), accept(sock))
```
Thus, I assume reusing the same socket file descriptor might not be considered a good practice.

Another interesting aspect is that I'm using Ubuntu on WSL, and the errno number is different.
```
>>> import errno
>>> errno.errorcode[11]
'EAGAIN'
>>> errno.errorcode[35]
'EDEADLOCK'
```
So, while running the test I mentioned earlier, the error still gets logged here, but the callback effectively handles it.

**Comment by gvanrossum** [comment] 2024-03-13 15:45
Okay, then let's close this issue as "not planned" -- the OP can solve their problem by using `sock.dup()`.

**Closed as not planned by gvanrossum** 2024-03-13 15:45 UTC
Labels: type-bug, topic-asyncio
