### ISSUE TITLE
argparse.ArgumentParser silently swallows multiple -- (double dash)

### ISSUE THREAD

**Issue by Nikratio** [python/cpython#95468] opened 2022-07-30 14:25 UTC
Consider this:

```
import argparse
p = argparse.ArgumentParser()
p.add_argument('arg1', type=str)
p.add_argument('args', nargs='*')
p.parse_args(['foo', '--', '--bar', '--', 'com'])
```

The semantics of  `--` are to not attempt to parse the remaining command line options as parameters. Therefore, the expected output is:

```
Namespace(arg1='foo', args=['--bar', '--', 'com'])
```

However, the actual output is:

```
Namespace(arg1='foo', args=['--bar', 'com'])
```

In other words, the second `--` has silently been dropped.

Interestingly enough, if the `arg1` parameter is dropped, this works correctly:

```
p = argparse.ArgumentParser()
p.add_argument('args', nargs='*')
p.parse_args(['foo', '--', '--bar', '--', 'com'])
--> Namespace(args=['foo', '--bar', '--', 'com'])
```

### Linked PRs
* gh-124145
* gh-124233
* gh-124274
* gh-124276
* gh-125068

**Comment by serhiy-storchaka** [comment] 2024-09-19 18:51
This is a duplicate of #81691.

**Closed as not planned by serhiy-storchaka** 2024-09-19 18:51 UTC
Labels: type-bug, stdlib
