### ISSUE TITLE
"configure: error: internal configure error for the platform triplet" on macOS with Clang supporting --print-multiarch:

### ISSUE THREAD

**Issue by 7fbef687-4647-45a2-902c-2995ce7ba6ea** [python/cpython#88231] opened 2021-05-07 06:45 UTC
BPO | [44065](https://bugs.python.org/issue44065)
--- | :---
Nosy | @ronaldoussoren, @tiran, @ned-deily, @ambv, @pablogsal

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-07.06:45:46.943>
labels = ['OS-mac', 'build', '3.9', '3.10', '3.11']
title = '"configure: error: internal configure error for the platform triplet" on macOS with Clang supporting --print-multiarch:'
updated_at = <Date 2021-05-07.18:52:47.709>
user = 'https://bugs.python.org/sberg'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-07.18:52:47.709>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build', 'macOS']
creation = <Date 2021-05-07.06:45:46.943>
creator = 'sberg'
dependencies = []
files = []
hgrepos = []
issue_num = 44065
keywords = []
message_count = 4.0
messages = ['393167', '393169', '393171', '393204']
nosy_count = 6.0
nosy_names = ['ronaldoussoren', 'christian.heimes', 'ned.deily', 'lukasz.langa', 'pablogsal', 'sberg']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue44065'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by eliteraspberries** [comment] 2022-08-25 15:35
Yeah I ran into this recently trying to rebuild 3.7 which used to build just fine.

For anyone else here from Google: this is a duplicate of https://github.com/python/cpython/issues/89568 and fixed with https://github.com/python/cpython/pull/31890.

**Comment by ned-deily** [comment] 2022-08-25 18:48
@eliteraspberries, thanks for the reminder!

**Closed as completed by ned-deily** 2022-08-25 18:48 UTC
Labels: OS-mac, build, 3.11, 3.10, 3.9 (EOL)
