### ISSUE TITLE
"WARNING: Secure coding is not enabled for restorable state"

### ISSUE THREAD

**Issue by thekartikpage15** [python/cpython#112394] opened 2023-11-25 07:56 UTC
# Bug report
> WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### Bug description:

```python
# Add a code block here, if required
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by hugovk** [comment] 2023-11-25 08:24
Please give precise information: what did you do and what exactly happened?

**Comment by terryjreedy** [comment] 2023-11-25 08:32
Duplicate of #110950 #111082 #111845.  Not a CPython issue.

**Closed as not planned by terryjreedy** 2023-11-25 08:32 UTC
Labels: type-bug
