### ISSUE TITLE
``test_concurrent_futures.test_init`` raises a ``UserWarning``

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#114062] opened 2024-01-14 19:37 UTC
# Bug report

### Bug description:

Full trace:

<details>

```python
./python.exe -m test -R 3:3 test_concurrent_futures.test_init      
Using random seed: 256345264
0:00:00 load avg: 26.64 Run 1 test sequentially
0:00:00 load avg: 26.64 [1/1] test_concurrent_futures.test_init
beginning 6 repetitions
123456
/Users/admin/Projects/cpython/Lib/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown: {'/mp-sirq4ugj', '/mp-rl_2jbw3', '/mp-xahxrhsh', '/mp-iizqar8w', '/mp-2hsbr18l', '/mp-0l_el3ow'}
  warnings.warn(
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
./Users/admin/Projects/cpython/Lib/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown: {'/mp-lylw1wiw', '/mp-4uiidj6c', '/mp-7_ynxysg', '/mp-fx5syuzw', '/mp-ee8we555', '/mp-txhnr28x'}
  warnings.warn(
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
./Users/admin/Projects/cpython/Lib/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown: {'/mp-mey7u772', '/mp-1vws0viu', '/mp-1afg36e2', '/mp-bjp0f0e8', '/mp-7rpmd8vy', '/mp-95_5xypk'}
  warnings.warn(
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
./Users/admin/Projects/cpython/Lib/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown: {'/mp-618trphi', '/mp-wumuoxh9', '/mp-67c83ehk', '/mp-gv1cs7ab', '/mp-58aupobv', '/mp-70_ec35j'}
  warnings.warn(
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
./Users/admin/Projects/cpython/Lib/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown: {'/mp-micqbsoj', '/mp-t8f_ctlr', '/mp-5ae_spee', '/mp-ukdpimut', '/mp-mzxz9i98', '/mp-z15yhv29'}
  warnings.warn(
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
./Users/admin/Projects/cpython/Lib/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown: {'/mp-hnbdlmxa', '/mp-jrz89bu_', '/mp-aqeivj6m', '/mp-5yqnp8sh', '/mp-ga8p0vrj', '/mp-ugk7l_je'}
  warnings.warn(
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 296, in _run_finalizers
    finalizer()
    ~~~~~~~~~^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/util.py", line 220, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
    ~~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
.

== Tests result: SUCCESS ==

1 test OK.

Total duration: 8.0 sec
Total tests: run=8
Total test files: run=1/1
Result: SUCCESS
```
</details>

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by Eclips4** [comment] 2024-01-14 19:39
FYI: I'm not able to reproduce it with ``--forever`` ( I mean ``./python.exe -m test -v  test_concurrent_futures.test_init --forever``)

**Comment by encukou** [comment] 2024-02-05 07:48
This just happened [on a Mac free-threading refleaks buildbot](https://buildbot.python.org/all/#/builders/1368/builds/122). The same test leaked a reference.

**Comment by encukou** [comment] 2024-02-05 07:51
Can reproduce consistently on Linux with `-R :` (that is, `./python -m test test_concurrent_futures.test_init -R:`).

**Comment by encukou** [comment] 2024-02-05 14:06
... or maybe these are supposed to be cleaned up *before* atexit finalizers, and the test should catch this?

**Comment by encukou** [comment] 2024-02-05 14:14
Oh, this is a duplicate of #104090. There's much more info there.

**Closed as not planned by encukou** 2024-02-05 14:14 UTC
Labels: type-bug, tests, topic-multiprocessing
