### ISSUE TITLE
OSError 9 when using KqueueSelector and multiprocessing

### ISSUE THREAD

**Issue by Emru1** [python/cpython#111395] opened 2023-10-27 12:50 UTC
# Bug report

### Bug description:

`KqueueSelector` fails when created in parent process and used in child process with an OSError 9.
Tested on FreeBSD 13 and Python 3.9
I am not sure if this is relatable to https://github.com/python/cpython/issues/110395

```python
import selectors
import multiprocessing

class Test(multiprocessing.Process):
    def __init__(self):
        super().__init__()
        self.s = selectors.KqueueSelector()

    def run(self):
        self.s.select()

if __name__ == '__main__':
    t = Test()
    t.start()

```

```
Process Test-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home/emru/test.py", line 10, in run
    self.s.select()
  File "/usr/local/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
OSError: [Errno 9] Bad file descriptor

```

### CPython versions tested on:

3.9

### Operating systems tested on:

Other
```[tasklist]
### Tasks
```

**Comment by ronaldoussoren** [comment] 2023-10-27 18:23
This is a duplicate of https://github.com/python/cpython/issues/110395, which mentions the root cause for the error.

**Closed as not planned by ronaldoussoren** 2023-10-27 18:23 UTC
Labels: type-bug

**Comment by ronaldoussoren** [comment] 2023-10-27 18:32
To expand on my previous message (and phrase it correctly):

This is related of https://github.com/python/cpython/issues/110395, but slightly different. The system kqueue API does not support creating the kqueue in a parent proces and use it in a child.  That's not something we can work around. 

That means that your code will give an error even if the https://github.com/python/cpython/issues/110395 is fixed (the PR on that issue will close all kqueue objects in the child proces).
