### ISSUE TITLE
Exception subclass can't be unpickled

### ISSUE THREAD

**Issue by youtux** [python/cpython#98873] opened 2022-10-30 09:57 UTC
# Bug report

This exception subclass can't be unpickled, but I think it should be able to be unpickled fine:

```python
import pickle

class MyException(Exception):
    def __init__(self, msg, another_arg):
        super().__init__(msg)
        self.another_arg = another_arg

m = MyException("hello", 12)

pickle.loads(pickle.dumps(m))  # error

# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# TypeError: MyException.__init__() missing 1 required positional argument: 'another_arg'
```

Discovered in https://github.com/celery/celery/issues/6990

# Your environment

- CPython versions tested on: python 3.10.8
- Operating system and architecture: MacOS 12.6, Intel

**Comment by hauntsaninja** [comment] 2022-10-30 10:02
Duplicate of https://github.com/python/cpython/issues/76877

**Closed as not planned** 2022-10-30 10:06 UTC
Labels: type-bug
