### ISSUE TITLE
configparser open UTF-8 with BOM file

### ISSUE THREAD

**Issue by jeanphilipperuijs** [python/cpython#116310] opened 2024-03-04 14:58 UTC
# Bug report

### Bug description:

Opening a .cfg file saved in `UTF-8 with BOM` throws an exception.

```python
import configparser
config = configparser.ConfigParser()
config.read("./config_with_utf8_bom.cfg")
```
throws
```
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/config_with_utf8_bom.cfg', line: 1
'\ufeff[umfufu]\n'
```

It is debatable if this is a bug or a feature request.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by CharlieZhao95** [comment] 2024-03-05 02:48
This exception is not related to `UTF-8 with BOM`. The documentation clearly states that the configuration file requires a `[section]`, which is also the best practice for `.ini` files. 

> A configuration file consists of sections, each led by a [section] header, ...

https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

To solve this problem, I suggest adding a **global [section]**(at least one) to the configuration file.

**Comment by terryjreedy** [comment] 2024-03-05 07:09
The file has a section `[umfufu]`.  The issue is that the file has some extra junk at the beginning before that, on the same line, while section headers must start the line.

@jeanphilipperuijs Unless you can find something in the docs that claims that opening a utf-8-bom file as utf-8 files with Python's open() deletes the BOM, this is not a bug but a feature request.  I presume it would be to ignore the encoding mismatch.  If so, since configparser.read takes an optional `encoding` argument to cover such cases, I think that this should be rejected.  If one does not know which of several, one can try several encodings.  Something like:
```python
for encoding in encodings:
    try:
        f = open(filename, encoding=encoding)
    except whateverError:
        continue
    break
else:
    Error('no encoding worked')

<read f with `config.read_file(f)`>
```

**Comment by jeanphilipperuijs** [comment] 2024-03-06 10:01
Thanks for you input @terryjreedy, I did a somewhat similar but different approach function that reads a file in binary mode and returns the string stripping the BOM if present:
```python
def read_file_without_bom(file_path):
    with open(file_path, "rb") as file:
        content = file.read()

    if content.startswith(codecs.BOM_UTF8):
        content = content[len(codecs.BOM_UTF8) :]  # remove the BOMb
        return content.decode("utf-8")
    return content.decode("utf-8")
```

then use `config.read_string` instead of `config.read` 
```python
        config.read_string(utils.read_file_without_bom("./thefile.cfg"]))
```

​Indeed, it's quite a multifaceted issue to decide where to tackle the BOM conundrum. Suggestions have surfaced about leveraging an .ini file linter to detect and flag the presence of a BOM, which is a sound idea.

Nonetheless, I'm leaning towards investigating the possibility of resolving this directly at its source, to circumvent added complexities or unnecessary use of resources that may come with interim solutions such as pre-commit hooks or tailored DevOps CI jobs.

This issue surfaced when working with configparser, raising the question: could a more fundamental solution be feasible?

Initiating a "Ban the BOM" campaign could raise awareness, but then again, considering the resources required for such initiatives, it seems counterproductive. How much resource is dedicated to removing BOMs compared to the potential outreach activities?

Reflecting on the past debates over ISO and UTF-8 inconsistencies gives perspective on the recurring nature of encoding issues.

Feel free to relocate this discussion to a more pertinent context if needed.

**Comment by terryjreedy** [comment] 2024-03-11 03:07
New features should generally be discussed on [Discourse](https://discuss.python.org/c/ideas/6) to get ideas and approval from a wider audience.  Since there is no specific proposal, closing this.

**Closed as not planned** 2024-03-11 03:07 UTC
Labels: type-feature
