### ISSUE TITLE
Kivy install not working

### ISSUE THREAD

**Issue by gdavidshaw** [python/cpython#99383] opened 2022-11-11 15:59 UTC

**Comment by gdavidshaw** [comment] 2022-11-11 16:16
When I try to install Kivy I get the following error:
C:\Users\gdavidshaw>pip install kivy
Collecting kivy
  Using cached Kivy-2.1.0.tar.gz (23.8 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Collecting setuptools
        Using cached setuptools-65.5.1-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting cython!=0.27,!=0.27.2,<=0.29.28,>=0.24
        Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
      Collecting kivy_deps.gstreamer_dev~=0.3.3
        Using cached kivy_deps.gstreamer_dev-0.3.3-cp311-cp311-win_amd64.whl (3.9 MB)
      ERROR: Could not find a version that satisfies the requirement kivy_deps.sdl2_dev~=0.4.5 (from versions: 0.5.1)
      ERROR: No matching distribution found for kivy_deps.sdl2_dev~=0.4.5
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by kumaraditya303** [comment] 2022-11-11 16:31
You should report this to the Kivy project tracker. Closing as it is not a bug in python.

**Closed as not planned by kumaraditya303** 2022-11-11 16:31 UTC
Labels: type-bug
