### ISSUE TITLE
installation fails with DESTDIR set

### ISSUE THREAD

**Issue by doko42** [python/cpython#102172] opened 2023-02-23 13:16 UTC
seen with 3.12 alpha5, 

a make install DESTDIR=<someplace> fails with

```
/usr/bin/install -c build/scripts-3.12/pydoc3.12 /home/packages/python/3.12/python3.12-3.12.0~a5/debian/tmp/usr/bin/pydoc3.12
/usr/bin/install -c -m 755 Modules/_asyncio.cpython-312-x86_64-linux-gnu.so /usr/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so
/usr/bin/install: cannot create regular file '/home/packages/python/3.12/python3.12-3.12.0~a5/debian/tmp/usr/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so': No such file or directory
```

if the directories for the "final" installation (/usr/lib/python3.12/lib-dynload/) already exist.

The sharedinstall target depends on $(DESTSHARED), which unconditionally depends on some directories without any DESTDIR prefix, and therefore the directories are not created in the temporary install location, and the installation fails.

**Comment by zware** [comment] 2023-02-23 16:14
I believe this was already fixed in gh-100221; can you reproduce with current `main`?

**Comment by zware** [comment] 2023-03-15 16:32
Closing as duplicate of gh-100221.

**Closed as not planned by zware** 2023-03-15 16:32 UTC
Labels: type-bug, build
