### ISSUE TITLE
`mock.Mock` does not record the value of arguments, but record reference of them

### ISSUE THREAD

**Issue by hoon0422** [python/cpython#94348] opened 2022-06-27 21:49 UTC
**Bug report**

When using `mock.call` to check the calls of `mock.Mock` instance with dictionary arguments, there seems to be a bug:

```python
from mock import Mock, call

mock = Mock()
arg = {}

mock(arg)
arg['el'] = 1

mock.assert_has_calls({})  # This raises assertion exception

"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python37/lib/python3.7/site-packages/mock/mock.py", line 969, in assert_has_calls
    ), cause)
  File "<string>", line 3, in raise_from
AssertionError: Calls not found.
Expected: [call({})]
Actual: [call({'el': 1})]
"""
```

I thought the last assertion should not create an exception

**Your environment**

- CPython versions, Operating system tested on: 3.9.7 (mac os 12.4), 3.7.13 (ubuntu 20.04)

**Comment by mdickinson** [comment] 2022-06-29 13:08
I think this is expected behaviour: the calls keep references to the actual Python objects that were passed, rather than making copies.

It's difficult to see how this could reasonably work in any other way: conditionally making copies of arguments would be fragile, both in terms of the heuristics that decided when to make a copy or not, and in terms of the copy itself (not everything can be copied cleanly).

**Comment by hoon0422** [comment] 2022-06-30 01:32
Thanks for the reply @mdickinson ! But I think at least we need a way to make an assertion for dictionary arguments. And I cannot come up with the nice solution...

**Comment by mdickinson** [comment] 2022-07-01 14:21
Closing; I accept and understand that there's a real problem to be solved, but there isn't a Python bug here - Python's behaving as intended. Well thought-out proposals on how to address the problem are welcome, but the right place to discuss those would be on a more general discussion forum like [discuss.python.org](https://discuss.python.org/).

**Closed as not planned by mdickinson** 2022-07-01 14:21 UTC
Labels: type-bug

**Comment by tirkarthi** [comment] 2022-07-12 15:13
Just to add this is a duplicate of https://github.com/python/cpython/issues/77848 and https://github.com/python/cpython/issues/72505. Relevant doc : https://docs.python.org/3/library/unittest.mock-examples.html#coping-with-mutable-arguments . There was an issue to add `CopyingMock` but it's not available in the core and can be used from PyPI as per discussion in https://bugs.python.org/issue28848
