### ISSUE TITLE
Multiprocessing shared memory duplicated with changed size

### ISSUE THREAD

**Issue by passcombo** [python/cpython#101623] opened 2023-02-06 22:06 UTC
# What I do:
Inside class create shared mem and store it on the list:
```
self.inner_np_mem=[]
shm = shared_memory.SharedMemory(name='zxcv', create=True, size=r_arr.nbytes) #r_arr is numpy array
self.inner_np_mem.append(shm)
```
few lines down yet in the same function inside the same class I load the mem:
`shm = shared_memory.SharedMemory(name='zxcv')`
and compare to the stored one in the list self.inner_np_mem this is what I got:
```
print(190, 'shm.size',shm.size,len(shm.buf),shm.buf,self.inner_np_mem[0].buf)	
print(191, 'shm.size',shm.size,len(shm.buf),shm ,self.inner_np_mem[0] )	
```

> line 190 shm.size 81920 81920 <memory at 0x0000016EF3EA5400> <memory at 0x0000016EF3EA51C0>
> line 191 shm.size 81920 81920 SharedMemory('zxcv', size=81920) SharedMemory('zxcv', size=80000)

# Bug report

So I have 2 shared mem objects with the same name and different size.

# Your environment

Python 3.9.10

**Comment by eryksun** [comment] 2023-02-06 22:42
If you're on Windows, subsequent opens of shared memory query the size of the allocated memory region. This will always be a multiple of the system page size, which is commonly 4096 bytes. In your case, since 19 pages, or 77824 bytes, would be too small, Windows allocates 20 pages, or 81920 bytes. 

Since virtual memory access is controlled at the page level, the extra 1920 bytes are really available just like the rest of shared-memory block. The internal `mmap` of the first instance is, however, limited to the specified size of 80000 bytes. For subsequent opens to use the exact same size as the first instance, the size would have to be stored as metadata in a header at the beginning of the shared memory block.

**Comment by passcombo** [comment] 2023-02-06 22:52
Yes, Windows 10. Is it OS-specific?

Thanks for quick answer, what you describe make sense with my experience of the issue. I have tested the problem with diff mem size and the memory of the second open object was always bigger. 

This is strange behavior since I basically followed the tutorial of populating the mem from np array (here https://docs.python.org/3/library/multiprocessing.shared_memory.html)

User could expect the object of shared mem itself has bigger size in bytes and actually stores the variable size, since it is an object and it has the attribute?

One simple alternative I have is using pickle with shared mem. Didn't have bad issue with pickle (I hope not by chance eg hope pickle marks some ending bytes to correctly unpickle).

**Comment by ericvsmith** [comment] 2023-02-06 23:07
The documentation you linked to does say:

size specifies the requested number of bytes when creating a new shared memory block. Because some platforms choose to allocate chunks of memory based upon that platform’s memory page size, the exact size of the shared memory block may be larger or equal to the size requested. When attaching to an existing shared memory block, the size parameter is ignored.

So I think it's working as expected. Typically you'll need to communicate between processes what's in the shared memory block, possibly using the shared memory itself for this communication.

**Comment by passcombo** [comment] 2023-02-07 19:46
As eryksun pointed sharing size fix the problem, however I feel it's kind of hack.
What I do is I read buffer to a variable 
`bb=bytes(shm.buf) `
then read to 
`np_arr=np.ndarray(shape,dtype,buffer=bb[:size] )`

**Comment by ericvsmith** [comment] 2023-02-07 22:22
I'm going to close this, since it's working as designed.

If you have ideas for improving the interface, I suggest bringing them up at https://discuss.python.org/c/ideas/6

Thanks!

**Closed as not planned** 2023-02-07 22:22 UTC
Labels: type-bug, pending, topic-multiprocessing
