### ISSUE TITLE
argparse incorrectly says arguments are required

### ISSUE THREAD

**Issue by eslindsey** [python/cpython#103219] opened 2023-04-03 18:34 UTC
When using `nargs='*'` with other required arguments, argparse incorrectly says the optional argument is required.

### Output (with no arguments)
```
usage: example [-h] foo [bar ...]
example: error: the following arguments are required: foo, bar
```
### Code
```python
import argparse

parser = argparse.ArgumentParser(prog='example')
parser.add_argument('foo')
parser.add_argument('bar', nargs='*')
args = parser.parse_args()
```
Python 3.9.16

### Linked PRs
* gh-123931

**Comment by eslindsey** [comment] 2023-04-03 20:01
Code:
```python
import argparse

parser = argparse.ArgumentParser(prog='example')
parser.add_argument('foo')
parser.add_argument('bar', nargs='*')
args = parser.parse_args()
```
Output (with no arguments):
```
usage: example [-h] foo [bar ...]
example: error: the following arguments are required: foo, bar
```

**Comment by sobolevn** [comment] 2023-04-03 21:39
The patch can look something like this:

```python
                if (action.required and
                    action.default is None and
                    action.nargs not in (ZERO_OR_MORE, OPTIONAL)):
                    required_actions.append(_get_action_name(action))
```

On line https://github.com/python/cpython/blob/24facd60f6e5458cc783e429fe63d6a80d476f84/Lib/argparse.py#L2127

Test case:

```python
    def test_required_args(self):  # gh-103219
        parser = ErrorRaisingArgumentParser(prog='example')
        parser.add_argument('foo_arg')
        parser.add_argument('baz_arg', default='baz')
        parser.add_argument('bar_arg', nargs='*')

        args = parser.parse_args(['a'])
        self.assertEqual(
            NS(foo_arg='a', baz_arg='baz', bar_arg=[]), args)

        args = parser.parse_args(['a', 'b', 'c', 'd'])
        self.assertEqual(
            NS(foo_arg='a', baz_arg='b', bar_arg=['c', 'd']), args)

        with self.assertRaises(ArgumentParserError) as cm:
            parser.parse_args([])
        self.assertRegex(
            cm.exception.stderr,
            'error: the following arguments are required: foo_arg\n$'
        )
```

But, I don't feel confident submitting `argparse` patches. I hope this will help someone else :)

**Comment by hpaulj** [comment] 2023-04-18 20:20
I don't think this needs to be fixed.   It's an attempt to correct minor issue in the error message.

Normally '*' and '?' positionals are 'seen', because an empty list of arguments meets their `nargs` requirments.  

In this case required 'foo' positional, blocks all further processing of positionals, including 'bar'.   'bar' can't be filled, with default or not, until 'foo' has been filled.

**Comment by sobolevn** [comment] 2023-04-19 07:43
> I don't think this needs to be fixed. It's an attempt to correct minor issue in the error message.

Why don't we need to fix an error message?

**Comment by serhiy-storchaka** [comment] 2024-09-21 22:25
This is a duplicate of #72795.

**Comment by ericvsmith** [comment] 2024-09-23 16:55
Since it's a duplicate, I'm closing this.

**Closed as not planned by ericvsmith** 2024-09-23 16:55 UTC
Labels: type-bug, stdlib
