### ISSUE TITLE
RuntimeWarning: coroutine method 'aclose' of '...' was never awaited when breaking out of async for

### ISSUE THREAD

**Issue by hroncok** [python/cpython#117536] opened 2024-04-04 10:36 UTC
# Bug report

*Edit: See https://github.com/python/cpython/issues/117536#issuecomment-2047428999 and https://github.com/python/cpython/issues/117536#issuecomment-2044591323 for simpler reproducers --@encukou*

### Bug description:

The following code is extracted from jinja2 tests, as I was debugging https://github.com/pallets/jinja/issues/1900 -- it uses no jinja:

```python
async def auto_aiter(iterable):
    for item in iterable:
        yield item

async def customfilter(iterable):
    items = []
    async for item in auto_aiter(iterable):
        items.append(item)
        if len(items) == 3:
            break
    return "".join(items)

import asyncio
print(asyncio.run(customfilter("yyyNNN")))
```

```bash
$ python3.12 asyncrepro.py 
yyy

$ python3.13 asyncrepro.py 
yyy
sys:1: RuntimeWarning: coroutine method 'aclose' of 'auto_aiter' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

$ python3.13 -X tracemalloc asyncrepro.py 
yyy
sys:1: RuntimeWarning: coroutine method 'aclose' of 'auto_aiter' was never awaited
Object allocated at (most recent call last):
  File ".../asyncrepro.py", lineno 10
    break
```

This seems to be related to https://github.com/python/cpython/issues/89091

I am not sure if this is a regression in Python or a bug in Jinja tests, but considering Jinja folks closed my issue, I decided to report it here instead.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-117577
* gh-117751
* gh-117851
* gh-117906

**Comment by TeamSpen210** [comment] 2024-04-04 11:16
With async generators, you have to take steps to clean them up properly if you don't iterate through them completely. In this case it's not entirely necessary, but it's good practice in general:

```py
async def customfilter(iterable):
    items = []
    agen = auto_aiter(iterable)
    try:
        async for item in agen:
            items.append(item)
            if len(items) == 3:
                break
        return "".join(items)
    finally:
        await agen.aclose()
```
This ensures any pending `with` statements or `finally` blocks get a chance to run. Instead of directly calling `aclose` you can also use `contextlib.aclosing()`. There is a mechanism built in to allow this to eventually be handled - once the generator is ready to be garbage collected, `asyncio` is able to step in and finalise it. But like file objects getting closed that happens at some arbitrary point, making it difficult to reason about. 

With `auto_aiter()`, there isn't anything to cleanup, so in this case it might not be necessary. But Python can't know that when producing its warnings. Though, maybe `auto_aiter()` should also attempt to `aclose()` the iterable it wraps, if that has such a method. Not sure.

**Comment by hroncok** [comment] 2024-04-05 10:02
Thank you. This solves the particular case I provided as a reproducer, but I keep getting more and more such problems in Jinja. I've tried to add this pattern at multiple places, but I failed miserably.

I still don't know whether what jinja does has always been "wrong" or whether the check is too strict :(

**Comment by graingert** [comment] 2024-04-05 11:54
asyncio.run is supposed to correctly shutdown async generator objects, I'm not sure what's happening here

**Comment by graingert** [comment] 2024-04-05 11:59
a smaller repro:

```python
async def agen():
    yield
    yield

async def main():
    a = agen()
    await anext(a)
    del a

import asyncio
asyncio.run(main())
```

**Comment by graingert** [comment] 2024-04-05 12:14
the problem is in _asyncgen_finalizer_hook, and exists in earlier versions of python - except generator.aclose() doesn't warn.

https://github.com/python/cpython/blob/9ceaee74db7da0e71042ab0b385d844e9f282adb/Lib/asyncio/base_events.py#L557-L561

what's happening is `self.create_task, agen.aclose()` is being added to the call_soon_threadsafe callback deque, and the async generator is removed from the `self._asyncgens` set, then the loop is being closed before the call_soon_threadsafe callback deque is consumed resulting in the async generator not being shutdown

**Comment by graingert** [comment] 2024-04-05 12:26
I think it should be something like this?

```python
    def _asyncgen_finalizer_hook(self, agen):
        def do_close():
            if self._asyncgens_shutdown_called:
                return
            self._asyncgens.discard(agen)
            asyncio.create_task(agen.close())

         if not self.is_closed():
             self.call_soon_threadsafe(do_close)
```

**Comment by graingert** [comment] 2024-04-09 09:44
my original diagnosis was incorrect - I've eliminated asyncio here:


```python
import contextlib

async def agen():
    while True:
        yield


class CancelledError(BaseException):
    pass


async def amain():
    async with contextlib.aclosing(agen()) as a:
        await anext(a)
        try:
            a.aclose().throw(CancelledError)
        except CancelledError:
            pass


try:
    amain().send(None)
except StopIteration as e:
    print(e.value)
```

output:

```
/home/graingert/projects/cpython/demo2.py:16: RuntimeWarning: coroutine method 'aclose' of 'agen' was never awaited
  a.aclose().throw(CancelledError)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
None
```

it looks like throwing into aclose() doesn't mark the coroutine as awaited

**Comment by graingert** [comment] 2024-04-09 17:05
it also seems explicitly "__await__()"ing the `.athrow()` coroutine doesn't mark it as awaited:


```python
import contextlib

async def agen():
    while True:
        yield


class CancelledError(BaseException):
    pass


async def amain():
    async with contextlib.aclosing(agen()) as a:
        await anext(a)
        a.aclose().__await__()


try:
    amain().send(None)
except StopIteration as e:
    print(e.value)
```

outputs:
```
/home/graingert/projects/cpython/demo2.py:15: RuntimeWarning: coroutine method 'aclose' of 'agen' was never awaited
  a.aclose().__await__()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
None
```

**Comment by encukou** [comment] 2024-04-10 12:36
Simple reproducer that keeps the `asyncio` and `async for`/`break` (this way it might be easier to see that it *should* work):
```python
async def agen():
    yield 0
    yield 1

async def reproducer():
    async for item in agen():
        break

import asyncio
asyncio.run(reproducer())
```
This gives:
```
sys:1: RuntimeWarning: coroutine method 'aclose' of 'agen' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by encukou** [comment] 2024-04-10 12:39
I'm marking this for consideration as a release blocker.

**Comment by gvanrossum** [comment] 2024-04-10 14:52
Who's taking point here? It can't be me, I don't know the first thing about async generators (no need to educate me -- I'm trying to delegate here :-).

**Comment by graingert** [comment] 2024-04-10 17:26
Adding the `await asyncio.sleep(0)` changes the call asyncio makes from `agen.aclose().throw(CancelledError)` to `agen.aclose().send(None)` in neither case is asyncio failing to await the aclose()

**Comment by encukou** [comment] 2024-04-11 11:22
@kumaraditya303 & @graingert Do you want to work on a fix, or should I look into it?

**Comment by vstinner** [comment] 2024-04-11 12:14
I proposed PR gh-117751 to fix this issue: make the finalization of asynchronous generators more reliable.

I don't think that the warning is a regression. The problem is more that the finalization of asynchronous generators is not reliable, but Python now emits a warning if the generator is not finalized properly. It's just that the bug becomes more visible. Correct me if I'm wrong.

**Comment by graingert** [comment] 2024-04-11 14:07
@vstinner this is the wrong diagnosis I originally made, throwing into the aclose() object should mark it as awaited

**Comment by graingert** [comment] 2024-04-11 19:28
here's a realistic example of the problem of the incorrect warning:

```python
import asyncio

async def agenfn():
    return
    yield

class MyExc(Exception):
    pass

async def amain():
    try:
        async with asyncio.TaskGroup() as tg:
            agen = agenfn()
            async for v in agen:
                break
            tg.create_task(agen.aclose())
            raise MyExc()
    except* MyExc:
        pass

asyncio.run(amain())
```

outputs:

```
/home/graingert/projects/cpython/Lib/asyncio/base_events.py:2046: RuntimeWarning: coroutine method 'aclose' of 'agenfn' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

when clearly the `agen.aclose()` was awaited by `tg.create_task(age.aclose())`

**Comment by arthur-tacca** [comment] 2024-04-12 16:05
> when clearly the `agen.aclose()` was awaited by `tg.create_task(age.aclose())`

Is it clear? Or could you be running into the unrelated issue #116048? Maybe you're not but it's worth double checking: either use eager task creation as suggested in that issue (but then you might as well not use the task factory) or by just put `agen.aclose()` into a coroutine with a `print()` and run that in the task group instead so you can at least see whether it really ran.

**Comment by graingert** [comment] 2024-04-13 15:08
@arthur-tacca yes this is true, but the aclose Coroutine should be considered awaited just like a regular async def

**Comment by encukou** [comment] 2024-04-24 13:43
Fixed in main; I'll close this.
The underlying issue is present in 3.12 too, but backporting is tracked in #117894.

**Closed as completed by encukou** 2024-04-24 13:43 UTC
Labels: type-bug, topic-asyncio, release-blocker, 3.13
