### ISSUE TITLE
__annotations__ lose type when a variable and its type have same name with default value None

### ISSUE THREAD

**Issue by youngrok** [python/cpython#121229] opened 2024-07-01 14:16 UTC
# Bug report

### Bug description:

```python
class MyField:
    pass

class MyClass:
    MyField: MyField = None

print(MyClass.__annotations__)
```
Expected:
```
{'MyField': __main__.MyField}
```
Actual:
```
{'MyField': None}
```

`__annotations__` lose type under these two conditions:
1. Field name of a class and its type have same name
2. `None` is assigned to the field as default value

Everything work fine except `__annotations__`. However, this issue also affects `dataclass`, causing `dataclasses.fields` to return the wrong value.

I understand that having a variable and a type with the same name is not ideal. However, in case-insensitive languages, it can sometimes be challenging to provide different names for fields and types. I encountered this issue while writing a class in Korean, as demonstrated in the following code:

```
from enum import Enum
from dataclasses import dataclass

class 납세자종류(Enum):
    개인 = '01'
    법인 = '03'

@dataclass
class 납세자:
    납세자종류: 납세자종류 = None
```

I assume that when the field MyField is assigned None, the type MyField in the class scope is also overwritten. Consequently, when `__annotations__` is built, it uses the class scope. Outside the class scope or within method scope, MyField functions correctly as a type.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by sobolevn** [comment] 2024-07-01 14:33
I don't think that there's anything to do here. 
Because you first write `MyField` name to the class-scope. Then you use `MyField` as annotation. In this class-scope it is `None`. I don't think that we can change the evaluation order :(

Solution:

```python
>>> class A: ...
... 
>>> _A = A
>>> class B:
...    A: _A = ...
... 
>>> B.__annotations__
{'A': <class '__main__.A'>}
```

**Comment by AlexWaygood** [comment] 2024-07-01 14:36
Duplicate of #108437

**Comment by AlexWaygood** [comment] 2024-07-01 14:37
See also https://github.com/python/cpython/issues/115844#issuecomment-1960960902

**Closed as not planned by AlexWaygood** 2024-07-01 14:36 UTC
Labels: type-bug, topic-typing
