### ISSUE TITLE
Interpreter crashes with `--with-trace-refs` on

### ISSUE THREAD

**Issue by sunmy2019** [python/cpython#103621] opened 2023-04-19 06:42 UTC
# Crash report
Interpreter crashes with `--with-trace-refs` on.

```sh
./configure --with-trace-refs
make -j
```

`./_bootstrap_python` has a segment fault. 

The compiler warns when initializing some PyObjects. I think it's due to an incorrect fill of fields with trace ref API.

# Your environment

- CPython versions tested on: current main d1e4917
- Operating system and architecture: ubuntu 22.04 x64

# Releated ideas

https://discuss.python.org/t/enhance-ref-trace-facilities/25990

**Comment by corona10** [comment] 2023-04-19 08:48
I can reproduce the issue on my local too.

**Comment by arhadthedev** [comment] 2023-04-21 13:32
@sunmy2019 gh-103561 is merged; could you check if the issue is fixed?

**Comment by sobolevn** [comment] 2023-04-21 13:35
I can confirm that it solved the issue:

```
» ./configure --with-trace-refs --with-pydebug && make -j

...

./python.exe -E -c 'import sys ; from sysconfig import get_platform ; print("%s-%d.%d" % (get_platform(), *sys.version_info[:2]))' >platform
The following modules are *disabled* in configure script:
xxlimited             xxlimited_35                             

The necessary bits to build these optional modules were not found:
_tkinter                                                       
To find the necessary bits, look in configure.ac and config.log.

Checked 111 modules (30 built-in, 76 shared, 2 n/a on macosx-10.14-x86_64, 2 disabled, 1 missing, 0 failed on import)
```

**Closed as completed by sobolevn** 2023-04-21 13:35 UTC
Labels: interpreter-core, build, release-blocker, type-crash
