### ISSUE TITLE
Python 3.8: Code blocks unreadable with darkmode enabled

### ISSUE THREAD

**Issue by GhislainC** [python/cpython#115464] opened 2024-02-14 16:07 UTC
# Documentation

For a few days, with darkmode enabled, the code blocks in the documentation are unreadable (white characters on light background)

Example from doc : https://docs.python.org/3.8/library/dataclasses.html
![image](https://github.com/python/cpython/assets/20724991/fe221ee3-e148-48ed-8a03-99691b9502cd)

Tested on Chrome for desktop, Chrome for mobile and Firefox for mobile : same results.

Can you fix it please?

**Comment by hugovk** [comment] 2024-02-14 16:15
Thanks for the report.

This is a duplicate of https://github.com/python/cpython/issues/115349 which has been fixed, and will be deployed when the next 3.8 and 3.9 releases go out, which I think should be this week.

In the meantime, you can visit the docs for 3.10 or later.

**Closed as not planned by hugovk** 2024-02-14 16:15 UTC
Labels: docs
