### ISSUE TITLE
symtable recursion depth updates seem inconsistent

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#122313] opened 2024-07-26 14:29 UTC
The symtable ``VISIT`` macro decrements ``st->recursion_depth`` (and returns) in case of error.
For explicit returns, visitor functions should use the ``VISIT_QUIT`` macro (which also decrements the recursion depth).

Each function should either always decrement it, or never. However, I can see that this doesn't always hold. For example, the following function decrements only in error cases:

```c
static int
symtable_handle_namedexpr(struct symtable *st, expr_ty e)
{   
    if (st->st_cur->ste_comp_iter_expr > 0) {
        /* Assignment isn't allowed in a comprehension iterable expression */
        PyErr_Format(PyExc_SyntaxError, NAMED_EXPR_COMP_ITER_EXPR);
        SET_ERROR_LOCATION(st->st_filename, LOCATION(e));
        return 0;
    }
    if (st->st_cur->ste_comprehension) {
        /* Inside a comprehension body, so find the right target scope */
        if (!symtable_extend_namedexpr_scope(st, e->v.NamedExpr.target))
            return 0; 
    }
    VISIT(st, expr, e->v.NamedExpr.value);
    VISIT(st, expr, e->v.NamedExpr.target);
    return 1;
}       
```

I think error handling in this file needs to be reviewed. 

### Linked PRs
* gh-122640

**Comment by iritkatriel** [comment] 2024-07-26 14:30
CC @JelleZijlstra @carljm

**Comment by iritkatriel** [comment] 2024-08-02 09:06
CC @serhiy-storchaka

**Comment by serhiy-storchaka** [comment] 2024-08-02 17:21
There is `VISIT_QUIT(st, 0)` outside of `symtable_raise_if_annotation_block()`:
```c
        if(!symtable_handle_namedexpr(st, e))
            VISIT_QUIT(st, 0);
```
But, if error happens in visiting `e->v.NamedExpr.value` or `e->v.NamedExpr.target`, the recursion depth will be decremented twice.

**Comment by serhiy-storchaka** [comment] 2024-08-03 07:33
I tried to sort this out and have found that calculating consistent value of `st->recursion_depth` in case of error is a difficult problem. Attempt to solve it leads to more complex and fragile code. Currently the part of the large function can be extracted into separate function, and the part of that functions can be extracted into another function, and so on. All these functions can contain `VISIT()` and `VISIT_SEQ()` and other variants, therefore implicit `VISIT_QUIT()` on error. If they are called with `VISIT_SEQ()`, `VISIT_QUIT()` will be used multiple times.

But I think that this problem is not worth solving. We only need balanced updates of `st->recursion_depth` if no errors happen. Once an error occurs -- it's the game end. The only valid action is to return up to the top. The value of `st->recursion_depth` is now irrelevant because no new deep recursion will be performed.

I suggest to close this as "not a bug".

**Comment by iritkatriel** [comment] 2024-08-03 08:28
If the recursion depth becomes irrelevant once an error occurs, then I think we should not decrement it in the error case. The way the code now pretends to try to keep it consistent is confusing.

**Closed as completed** 2024-08-03 10:49 UTC
Labels: interpreter-core
