### ISSUE TITLE
`PyEval_GetFrame` crashes when it returns incomplete frames

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#96975] opened 2022-09-20 22:58 UTC
Is it possible that `PyEval_GetFrame`  returns incomplete frames. When this happens, Python segfaults in release mode or crashes in debug mode because of the check for incomplete frames in `_PyFrame_GetFrameObject`. This is reproducible in many ways involving C extensions, the easier one may be by installing a custom memory allocator for all the domains and calling `PyEval_GetFrame`  from there. As the allocator can be called at random points of the eval loop (for example [here](https://github.com/python/cpython/blob/a3e2f054d285d72bca97667390bbc219d02ab364/Python/ceval.c#L6231)) is perfectly possible that a legitimate call to `PyEval_GetFrame` returns an incomplete frame.

**Comment by pablogsal** [comment] 2022-09-20 22:59
CC: @markshannon @brandtbucher @ericsnowcurrently @iritkatriel

**Comment by brandtbucher** [comment] 2022-09-20 23:00
Typo? Are you asking us if it's possible, or telling us it is?

**Comment by pablogsal** [comment] 2022-09-20 23:00
I am telling you

**Comment by pablogsal** [comment] 2022-09-20 23:03
It may be easier to reproduce by using generators.

**Comment by brandtbucher** [comment] 2022-09-20 23:05
It seems to me that the correct thing to do in this case is to walk back over the frames until we reach a "complete" one, like we do in other places. Not 100% sure yet.

**Comment by brandtbucher** [comment] 2022-09-20 23:11
It may also be possible in `sys._getframe()`. The logic for skipping incomplete frames doesn't seem to happen once you've walked back to the desired depth.

**Comment by brandtbucher** [comment] 2022-09-20 23:32
Ah wait, I think `sys._getframe()` is okay actually. I don't think it can be called from an incomplete frame.

**Comment by godlygeek** [comment] 2022-09-21 00:05
It is possible to trigger this assertion using the C API.

**Comment by brandtbucher** [comment] 2022-09-21 00:15
Thanks. I'll have to pick this back up tomorrow morning (might find some time tonight).

**Comment by ericsnowcurrently** [comment] 2022-09-21 15:56
> It is possible to trigger this assertion using the C API.

Thanks for the reproducer, which concisely demonstrates the bug.  That's super helpful.  There's a possible caveat, but only relating to the ways (and likelihood) the bug could be triggered in the wild.

FWIW, my understanding is that the CPython runtime expects the allocator to stay the same from initialization to finalization, so `PyMem_SetAllocator()` should be used only by embedders (before `Py_Initialize()`), not in extension modules.  I may be wrong though.  [The docs](https://docs.python.org/3/c-api/memory.html#c.PyMem_SetAllocator) don't mention this, nor (obviously) does the function check `Py_IsInitialized()` or `_Py_IsCoreInitialized()`.

@vstinner would probably know for sure.

**Comment by ericsnowcurrently** [comment] 2022-09-21 16:17
Looking at the code, shouldn't we just call `PyThreadState_GetFrame()` in `PyEval_GetFrame()`?

**Comment by ericsnowcurrently** [comment] 2022-09-21 16:22
FYI, this was fixed for signal handlers a week ago in https://github.com/python/cpython/pull/96776.

**Comment by vstinner** [comment] 2022-09-21 16:25
Python/initconfig.c calls ``_PyMem_SetDefaultAllocator()`` to force the usage of a specific memory allocator in function called before Python initialization (alloc) and during Python finalization (free): pymain_free() of Modules/main.c, called by Py_RunMain().

The Python memory allocator must be configured by the Python pre-initialization, or just after the pre-initialization, and before the Python initialization.

* https://docs.python.org/dev/c-api/init_config.html#pypreconfig
* https://docs.python.org/dev/c-api/init_config.html#pyconfig
* https://docs.python.org/dev/c-api/memory.html#c.PyMem_SetAllocator

Setting a hook on existing allocators, like what tracemalloc does, is different and safe while Python is running.

**Comment by ericsnowcurrently** [comment] 2022-09-21 16:25
The assertion was added by Mark in July in gh-94371.

**Comment by vstinner** [comment] 2022-09-21 16:25
> the CPython runtime expects the allocator to stay the same from initialization to finalization

sorry, short reply: yes :-)

**Comment by ericsnowcurrently** [comment] 2022-09-21 16:32
> All the other places that call _PyFrame_GetFrameObject() (where the assert actually lives) seem to do the right thing.

I didn't look very closely at `call_trace()` or `maybe_call_line_trace()` (in ceval.c) though.

**Comment by ericsnowcurrently** [comment] 2022-09-21 16:36
> Setting a hook on existing allocators, like what tracemalloc does, is different and safe while Python is running.

The reproducer from https://github.com/python/cpython/issues/96975#issuecomment-1253035781 does exactly that (simply wrapping the already-set allocator) so it's a legitimate example.

**Comment by brandtbucher** [comment] 2022-09-21 17:10
> I didn't look very closely at `call_trace()` or `maybe_call_line_trace()` (in ceval.c) though.

They look safe, since tracing doesn't happen if we're in an incomplete state. The definition of `_PyFrame_IsIncomplete` is basically "can tracing happen yet?".

**Comment by kumaraditya303** [comment] 2022-09-21 17:41
> Looking at the code, shouldn't we just call PyThreadState_GetFrame() in PyEval_GetFrame()?

That indeed fixes the issue and avoids code duplication.

**Comment by brandtbucher** [comment] 2022-09-22 17:37
Actually, I'll let Pablo close this once it's cherry picked to the stable release.

**Comment by pablogsal** [comment] 2022-09-28 15:01
I wonder if we should expose the `_PyFrame_IsIncomplete` function so if there are more cases like this extension authors can protect their code against this meanwhile we release a fix. Thoughts?

**Closed as completed** 2022-10-26 08:23 UTC
Labels: 3.11, 3.12
