### ISSUE TITLE
Exception while handling exception in email.msg.get('message-id')

### ISSUE THREAD

**Issue by DRSpalding** [python/cpython#94306] opened 2022-06-26 16:49 UTC
Possibly malformed Message-ID tag in header causes a raised exception but gets a second exception trying to deal with the defect and terminates.  The Message-ID tag in question was received in the real-world.

Windows 10 up to date, Python 64-bit 3.10.5.

Code in bad-email-hdr.py:
```
#! python3

import email
from email import policy

msg_id = 'Message-ID'
b_msg_hdr_bad2 = b'Message-ID: <[anu10].1c69fb81.7aec0.5503SMTPIN_ADDED_[au5]@[anu13].EURPRD10.PROD.OUTLOOK.COM>\r\n\r\n'

msg2 = email.message_from_bytes(b_msg_hdr_bad2, policy=policy.default)

print(f'bad header {msg_id} = {msg2.get(msg_id)}')
print(f'msg bytes = {msg2.as_bytes()}')

```

Traceback:
c:\tmp\PyTest> bad-email-hdr.py
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\email\_header_value_parser.py", line 2069, in get_msg_id
    token, value = get_dot_atom_text(value)
  File "C:\Program Files\Python310\lib\email\_header_value_parser.py", line 1334, in get_dot_atom_text
    raise errors.HeaderParseError("expected atom at a start of "
email.errors.HeaderParseError: expected atom at a start of dot-atom-text but found '[anu10].1c69fb81.7aec0.5503SMTPIN_ADDED_[au5]@[anu13].EURPRD10.PROD.OUTLOOK.COM>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\tmp\PyTest\bad-email-hdr.py", line 11, in <module>
    print(f'bad header {msg_id} = {msg2.get(msg_id)}')
  File "C:\Program Files\Python310\lib\email\message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "C:\Program Files\Python310\lib\email\policy.py", line 163, in header_fetch_parse
    return self.header_factory(name, value)
  File "C:\Program Files\Python310\lib\email\headerregistry.py", line 604, in __call__
    return self[name](name, value)
  File "C:\Program Files\Python310\lib\email\headerregistry.py", line 192, in __new__
    cls.parse(value, kwds)
  File "C:\Program Files\Python310\lib\email\headerregistry.py", line 532, in parse
    kwds['parse_tree'] = parse_tree = cls.value_parser(value)
  File "C:\Program Files\Python310\lib\email\_header_value_parser.py", line 2126, in parse_message_id
    token, value = get_msg_id(value)
  File "C:\Program Files\Python310\lib\email\_header_value_parser.py", line 2073, in get_msg_id
    token, value = get_obs_local_part(value)
  File "C:\Program Files\Python310\lib\email\_header_value_parser.py", line 1516, in get_obs_local_part
    if (obs_local_part[0].token_type == 'dot' or
IndexError: list index out of range

Also seen on 3.10.0.
Windows 10 x64, up to date.

Tried Ubuntu and Python 3.8.10 and got same result as on Windows 3.10.5 version.

Tried Debian (Raspbian) 32-bit Python 3.7.3 and it appears that it encodes the Message-ID header into a =?utf-8?q? format, possibly as expected to deal with the characters tripping it up.

**Comment by jheiss** [comment] 2022-10-23 21:10
I think this is the same bug as #90593

**Comment by jenicek** [comment] 2023-01-29 14:31
The issue here is not the truncated input as in #90593, but rather that the first character "[" is interpreted as a mark for the end of message id, so the atom is deemed invalid (empty). As I understand [RFC 2822](https://www.rfc-editor.org/rfc/rfc2822), only "<>" can be used to mark the beginning and end of an atom in message id (msg-id in the standard). Recently, I've started experiencing this issue as well with message ids that were surrounded with both "<>" and "[]", i.e. "<[id@domain]>".

I see the core of the issue is in the generic `get_dot_atom_text` function (in email/_header_value_parser.py) which does not distinguish between different contexts, so when called from `get_msg_id` function, it uses any character from ATOM_ENDS (`()<>@,:;.\"[]`) as a mark for the end of message id.

**Comment by jelle-eastground** [comment] 2023-08-17 15:17
As a quick fix, you could strip the '[' and ']' from the Message-ID by implementing your custom EmailPolicy:

```
import email
from email.policy import EmailPolicy

class CustomEmailPolicy(EmailPolicy):
    def header_fetch_parse(self, name, value):
        if name == 'Message-ID':
            if isinstance(value, str) and ('[' in value or ']' in value):
                return re.sub(r'[\[\]]', '', value)  # strip '[' and ']' from Message-ID
        return super().header_fetch_parse(name=name, value=value)
```

To use this `CustomEmailPolicy,` instantiate it and use it as policy-argument of `email.message_from_string`, `email.message_from_bytes` and/or `email.message_from_file`, like `email.message_from_bytes(source, policy=CustomEmailPolicy())`

**Comment by shamusfield-expel** [comment] 2023-08-23 16:42
I'm running into this as well. I can't remove the `[]` characters, since they're the true header value and I need to match it up to O365 later. This is how I'm currently getting around it
```
        ind = email_message.keys().index('Message-ID')
        print(email_message._headers[ind][1])
```

In case that helps anyone. you'll need to pre-handle checking to make sure the header exists etc

**Comment by bronger** [comment] 2024-01-02 20:55
> As a quick fix, you could strip the '[' and ']' from the Message-ID by implementing your custom EmailPolicy:
> 
> ```
> …
> 
> class CustomEmailPolicy(EmailPolicy):
>     def header_fetch_parse(self, name, value):
> …
> ```
> 
> To use this `CustomEmailPolicy,` instantiate it and use it as policy-argument of `email.message_from_string`, `email.message_from_bytes` and/or `email.message_from_file`, like `email.message_from_bytes(source, policy=CustomEmailPolicy())`

For some reason, the `header_fetch_parse` method is only called for `Content-Type` and `Content-Transfer-Encoding` for me. I pass the policy instance to `email.message_from_bytes`, and immediatly afterwards I call `my_message.as_bytes()`. Consequently, the broken Message-ID still aborts the latter call.

**Comment by fsc-eriker** [comment] 2024-02-09 12:35
Duplicate of https://github.com/python/cpython/issues/105802

**Closed as completed** 2024-04-17 07:47 UTC
Labels: type-bug, topic-email
