### ISSUE TITLE
Behavior of sequential calls to a list of lambda functions is not what I expected.

### ISSUE THREAD

**Issue by hideki1217** [python/cpython#100299] opened 2022-12-16 18:01 UTC
# Bug report

```python
def g(x, y):
    return x + y


func_ls = [
    lambda x: g(x, y)
    for y in [1, 2, 3]
]

for f in func_ls:
    c = f(1)
    print(c)
"""
expect:
2
3
4
"""
```
```bash
4
4
4
```

# Your environment

- CPython versions tested on: Python 3.8.2
- Operating system and architecture: 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by carljm** [comment] 2022-12-16 18:09
Hi! Thanks for the report. This is indeed a well-known "gotcha" that is unexpected by many users the first time they encounter it. Nonetheless, it's not a bug, but a necessary consequence of the way Python scopes and closures work, and it can't be changed without fundamentally changing the language and breaking a lot of code.

When a function (your lambda in this case) closes over a name in an outer scope, it does not capture a snapshot of the value referenced by the name at that point in time. Rather, it will always refer to the _current_ value of that name in the outer scope. All of your lambdas close over the name `y` from outer scope, and by the time you call them, the value of `y` in that scope is `3`; it doesn't matter what the value of `y` was at the time the lambda is defined.

One well-known workaround is to capture the value as an argument default, which does store the value at function definition time:

```
func_ls = [
    lambda x, y=y: g(x, y)
    for y in [1, 2, 3]
]
```

Closing because if you want to advocate for any change here (chance of success is low), it will definitely require discussion first at https://discuss.python.org/c/ideas/6 and a PEP.

**Closed as not planned by carljm** 2022-12-16 18:09 UTC
Labels: type-bug

**Comment by stevendaprano** [comment] 2022-12-16 22:30
By the way, before posting bug reports, you should check to see whether somebody has already made the same report. Sometimes it is hard to find relevant bug reports, but in this case [if you search for "lambda"](https://github.com/python/cpython/issues?q=lambda) you will find this issue reported twice in the last month and closed each time for the same reason.

Just a tip for next time :-)

**Comment by hideki1217** [comment] 2022-12-17 04:22
Thank you for your thoughtful response.
I will be careful from now on.

2022年12月17日(土) 7:30 stevendaprano ***@***.***>:
