### ISSUE TITLE
`./python -m test -v test_capi -m test_misc --forever` fails.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#105682] opened 2023-06-12 10:16 UTC
Maybe something to do with re-initializing the interpreter messing up the optimizer state?

**Comment by Eclips4** [comment] 2023-06-12 11:55
Duplicate of #105273

**Closed as completed** 2023-06-12 12:01 UTC
Labels: type-bug

**Comment by erlend-aasland** [comment] 2023-06-19 09:35
Sorry for the noise; resolved by:

- gh-105683
