### ISSUE TITLE
`PyCode_Addr2Line` and `PyFrame_GetLineNumber` return -1

### ISSUE THREAD

**Issue by notEvil** [python/cpython#111519] opened 2023-10-30 19:58 UTC
# Bug report

### Bug description:

Hi,

while testing line_profiler on 3.12 I saw `PyCode_Addr2Line` and `PyFrame_GetLineNumber` return -1. The following minimal example reproduces the issue for me:

<details>
<summary>line.py</summary>

```python
import pyximport

pyximport.install()

import _line
import asyncio


async def f():
    pass


print(_line.lines(f))


async def function_1(bool):
    if bool:
        async for _ in function_2():
            pass


async def function_2():
    if False:
        yield


_line.start()
asyncio.run(function_1(True))
_line.stop()
```

</details>

<details>
<summary>_line.pyx</summary>

```python
cdef extern from "Python.h":
    ctypedef struct PyObject
    ctypedef struct PyCodeObject
    ctypedef struct PyFrameObject
    ctypedef int (*Py_tracefunc)(PyObject* obj, PyFrameObject* frame, int what, PyObject* arg)
    cdef int PyTrace_CALL
    cdef int PyTrace_LINE
    cdef int PyTrace_RETURN
    cdef int PyCode_Addr2Line(PyCodeObject *co, int byte_offset)
    cdef void PyEval_SetTrace(Py_tracefunc func, PyObject* obj)
    cdef int PyFrame_GetLineNumber(PyFrameObject* frame)


def lines(function):
    code = function.__code__
    return [PyCode_Addr2Line(<PyCodeObject*>code, byte_offset) for byte_offset in range(0, len(code.co_code), 2)]


def start():
    PyEval_SetTrace(trace, NULL)


def stop():
    PyEval_SetTrace(NULL, NULL)


cdef int trace(PyObject* obj, PyFrameObject* frame, int what, PyObject* arg) noexcept:
    print(f"{PyFrame_GetLineNumber(frame):3}", {PyTrace_CALL: "call", PyTrace_LINE: "line", PyTrace_RETURN: "return"}.get(what, "other"))
```

</details>

On 3.11 it prints

```
[9, 9, 9, 10, 10]
 28 line
160 call
184 line
189 line
...
691 return
 63 return
189 return
 29 line
```

and on 3.12

```
[9, -1, 9, 10, -1, -1]
 28 line
160 call
188 line
193 line
...
 -1 return
...
702 return
 62 return
193 return
 29 line
```

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment] 2023-10-30 20:40
Are you able to reproduce this without Cython? Or it only happens on C level tracing function? What about a minimal tracer with C-extension?

**Comment by notEvil** [comment] 2023-10-30 22:19
> Are you able to reproduce this without Cython?

yes

> What about a minimal tracer with C-extension?

I've never created a C extension before, so don't expect this to be pretty.

<details>

```c
#include <Python.h>


static PyObject* lines(PyObject* self, PyObject* args) {
  PyObject* function = PyTuple_GetItem(args, 0);
  PyObject* code = PyFunction_GetCode(function);
  PyObject* co_code = PyCode_GetCode(code);
  printf("[");
  for (int byte_offset=0; byte_offset < PyObject_Length(co_code); byte_offset += 2) {
    printf("%i, ", PyCode_Addr2Line(code, byte_offset));
  }
  printf("]\n");
  Py_DECREF(co_code);
  return Py_None;
}


static int trace(PyObject* obj, PyFrameObject* frame, int what, PyObject* arg) {
  printf("%i %s\n", PyFrame_GetLineNumber(frame), what == PyTrace_CALL ? "call" : (what == PyTrace_LINE ? "line" : (what == PyTrace_RETURN ? "return" : "other")));
  return 0;
}


static PyObject* start(PyObject* self, PyObject* args) {
  PyEval_SetTrace(trace, NULL);
  return Py_None;
}


static PyObject* stop(PyObject* self, PyObject* args) {
  PyEval_SetTrace(NULL, NULL);
  return Py_None;
}


static PyMethodDef Methods[] = {
    {"lines", lines, METH_VARARGS, ""},
    {"start", start, METH_VARARGS, ""},
    {"stop", stop, METH_VARARGS, ""},
    {NULL, NULL, 0, NULL}        /* Sentinel */
};

static struct PyModuleDef module = {
    PyModuleDef_HEAD_INIT,
    "cline",   /* name of module */
    NULL, /* module documentation, may be NULL */
    -1,       /* size of per-interpreter state of the module,
                 or -1 if the module keeps state in global variables. */
    Methods
};

PyMODINIT_FUNC
PyInit_cline(void)
{
    return PyModule_Create(&module);
}
```

</details>

**Comment by notEvil** [comment] 2023-10-31 12:16
Backtracked `PyCode_Addr2Line` to this line

https://github.com/python/cpython/blob/dde5a99ba2173cf1ffbc1692d68000610250eacd/Objects/codeobject.c#L963

3.11.6 doesn't reach it and no other path that might lead to -1 is taken in both versions. I'm nowhere close to understand why.

**Comment by gaogaotiantian** [comment] 2023-10-31 22:59
So there's a simple repro:

```python
import dis

async def f():
    pass

print(list(f.__code__.co_lines()))
dis.dis(f)
```

3.11:
```
[(0, 2, 3), (2, 4, 3), (4, 6, 3), (6, 8, 4), (8, 10, 4)]
  3           0 RETURN_GENERATOR
              2 POP_TOP
              4 RESUME                   0

  4           6 LOAD_CONST               0 (None)
              8 RETURN_VALUE
```

3.12:
```
[(0, 2, 3), (2, 4, None), (4, 6, 3), (6, 8, 4), (8, 12, None)]
  3           0 RETURN_GENERATOR
              2 POP_TOP
              4 RESUME                   0

  4           6 RETURN_CONST             0 (None)
        >>    8 CALL_INTRINSIC_1         3 (INTRINSIC_STOPITERATION_ERROR)
             10 RERAISE                  1
ExceptionTable:
  4 to 6 -> 8 [0] lasti
```

3.13:
```
[(0, 6, 3), (6, 8, 4), (8, 12, None)]
   3           0 RETURN_GENERATOR
               2 POP_TOP
               4 RESUME                   0

   4           6 RETURN_CONST             0 (None)

None     >>    8 CALL_INTRINSIC_1         3 (INTRINSIC_STOPITERATION_ERROR)
              10 RERAISE                  1
ExceptionTable:
  4 to 6 -> 8 [0] lasti
```

As you can tell, the major difference between 3.12 and 3.11 is the exception table for the instrinsic call. For 3.13 (current main), the missing line number for `2 POP_TOP` is filled, but the line number for the exception table is still missing. I'm not sure if this is intentional - I don't know if there is a good "number" that should be there.

I believe the root cause for `PyFrame_GetLineNumber` is the same. It's not hard to imagine that when you try to get the line number while executing the byte code in the excpetion table, the line number would be `-1` (or converted to `None` at Python level).

I guess the question is to @iritkatriel or @markshannon : is this expected behavior? Should we have the line number assigned to the new-ish bytecode in the exception region?

**Comment by notEvil** [comment] 2023-10-31 23:37
Also found https://github.com/python/cpython/issues/107932#issuecomment-1679480161

Assuming these gaps are here to stay, how should line_profiler deal with them? Fill forward maybe?

**Comment by iritkatriel** [comment] 2023-11-03 19:33
This instructions should have line numbers. I think we should fix this.

**Comment by iritkatriel** [comment] 2023-11-03 21:08
On second thought maybe not - it's a "RERAISE 1" so it propagates the line number of the original RAISE, and we don't want it to create another line event.

**Comment by iritkatriel** [comment] 2024-03-23 22:21
Picking this up again - what is the actual issue here? Is it that a line number is `-1`?
I think this should be expected as possible.

**Comment by notEvil** [comment] 2024-03-24 14:09
I see. line_profiler reuses the last known line number and this didn't cause any trouble so far. Can be closed I guess.

**Comment by iritkatriel** [comment] 2024-03-24 18:28
Thanks.

**Closed as not planned by iritkatriel** 2024-03-24 18:28 UTC
Labels: type-bug, interpreter-core
