### ISSUE TITLE
Built-in function for generating UUIDv7 identifiers according to RFC9562

### ISSUE THREAD

**Issue by sergeyprokhorenko** [python/cpython#121095] opened 2024-06-27 13:13 UTC
# Feature or enhancement

### Proposal:

A long awaited new [RFC 9562](https://datatracker.ietf.org/doc/html/rfc9562) "Universally Unique IDentifiers (UUIDs)" has been recently published. There is a pressing need to implement UUIDv7 with [Fixed Bit-Length Dedicated Counter (Method 1)](https://datatracker.ietf.org/doc/html/rfc9562#name-monotonicity-and-counters) for Python for use as database keys.

The best choice is to take https://github.com/uuid-rs/uuid/issues/717 (it is perfect) as an example and add to it an optional formal parameter "timestamp offset" in milliseconds (positive or negative). Another good example: [UUID v7](https://commitfest.postgresql.org/47/4388/)

See also https://kodraus.github.io/rust/2024/06/24/uuid-v7-counters.html and https://www.reddit.com/r/rust/comments/1dn5ge4/uuid_now_properly_sorts_v7_ids/

Example of an existing implementation: [quwac/newnewid-python](https://github.com/quwac/newnewid-python)

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

[RFC 4122/9562: UUID version 7 and 8 implementation](https://discuss.python.org/t/rfc-4122-9562-uuid-version-7-and-8-implementation/56725)

**Comment by hugovk** [comment] 2024-06-27 13:15
Thanks for the issue, this is a duplicate of https://github.com/python/cpython/issues/89083 and there's already a couple of alternative PRs to implement it. 

Your input on the questions raised in the issue and [discussion](https://discuss.python.org/t/rfc-4122-9562-uuid-version-7-and-8-implementation/56725) are welcome!

**Closed as not planned by hugovk** 2024-06-27 13:15 UTC
Labels: type-feature
