### ISSUE TITLE
pathlib.Path accepts and ignores arbitrary kwargs

### ISSUE THREAD

**Issue by jaraco** [python/cpython#98094] opened 2022-10-08 16:24 UTC
The constructor (`__new__`) for `pathlib.Path` accepts arbitrary kwargs and just ignores them:

https://github.com/python/cpython/blob/4ed00be98f5b7dbac3ab71159dda907c931de486/Lib/pathlib.py#L794-L801

This lenience allowed bugs to leak into passing tests when someone accidentally passed the parameters in the wrong order:

```
zipfile.Path(pathlib.Path(filename, at='b/'))
```

That should have been written as:

```
zipfile.Path(pathlib.Path(filename), at='b/')
```

Because `pathlib.Path` accepted the `at` parameter, it masked the user's mistake.

```
>>> import pathlib
>>> pathlib.Path('foo', at='bar')
PosixPath('foo')
```

Is there a reason for the kwargs? I see no mention of it in the docs or source.

**Comment by JelleZijlstra** [comment] 2022-10-10 14:25
Duplicate of #74033

**Closed as not planned by JelleZijlstra** 2022-10-10 14:25 UTC
Labels: type-bug, topic-pathlib
