### ISSUE TITLE
netbsd CAN protocol flags addition

### ISSUE THREAD

**Issue by c9ed70e6-85ba-41dd-8968-859cb0429c8e** [python/cpython#89335] opened 2021-09-11 13:43 UTC
BPO | [45172](https://bugs.python.org/issue45172)
--- | :---
Nosy | @devnexen
PRs | <li>python/cpython#28288</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-11.13:43:46.891>
labels = ['type-feature', 'library', '3.11']
title = 'netbsd CAN protocol flags addition'
updated_at = <Date 2021-09-11.13:43:46.891>
user = 'https://github.com/devnexen'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-11.13:43:46.891>
actor = 'devnexen'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-09-11.13:43:46.891>
creator = 'devnexen'
dependencies = []
files = []
hgrepos = []
issue_num = 45172
keywords = []
message_count = None
messages = []
nosy_count = 1.0
nosy_names = ['devnexen']
pr_nums = ['28288']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45172'
versions = ['Python 3.11']
```

</p></details>

**Comment by erlend-aasland** [comment] 2022-05-18 07:59
Closing as duplicate of gh-74697

**Closed as completed by erlend-aasland** 2022-05-18 07:59 UTC
Labels: type-feature, stdlib, 3.11
