### ISSUE TITLE
Mutable optional parameters are re-used across multiple function calls

### ISSUE THREAD

**Issue by 80columns** [python/cpython#99142] opened 2022-11-05 20:05 UTC
# Bug report

When calling a function with a mutable optional parameter, the memory address of the optional parameter is the same across multiple calls. The optional parameter's object reference is reused without being set to the value specified in the function call. This behavior results in prior object modifications affecting the 2nd+ function calls.

```
def foo(a, b, c = {}):
    print(f"dictionary c is at memory location {id(c)}")
    c[a] = True
    c[b] = False
    print(f"dictionary c is {c}")
```

```
foo(1, 2)
```
dictionary c is at memory location 1908059683264
dictionary c is **{1: True, 2: False}**
```
foo(3, 4)
```
dictionary c is at memory location 1908059683264
dictionary c is **{1: True, 2: False, 3: True, 4: False}**
```
foo(5, 6)
```
dictionary c is at memory location 1908059683264
dictionary c is **{1: True, 2: False, 3: True, 4: False, 5: True, 6: False}**

# Your environment

- CPython versions tested on: 3.11
- Operating system and architecture: Windows 11 x64

**Comment by ajoino** [comment] 2022-11-05 20:18
If I understand this bug report correctly, this is intended behaviour. The parameter default values are evaluated once, at function creation time. This is a well known quirk of Python, and it is not recommended to use mutable default values for this reason.

**Comment by pochmann** [comment] 2022-11-05 20:33
Don't call something a bug just because you don't like it.

**Comment by 80columns** [comment] 2022-11-05 20:40
This is an interesting quirk, thanks for the clarification. I had not come across this behavior before. From my perspective, the behavior violates the function contract because I would expect that default parameter values are always the same. But from the perspective where they are set only once upon the creation of the function object itself, the behavior makes sense.

This may be particularly confusing to CS students when using Python for coding dynamic programming problems with memoization. If a recursive function is called from main() with a memo object set to an empty dictionary by default, then calling that recursive function multiple times from main() to test different input values can cause different results from subsequent recursive function calls because the memo object will be pre-populated with data from previous function calls.

I didn't expect the behavior but understand now why it is occurring. Out of curiosity, why does Python handle mutable optional parameters this way?

**Comment by ericvsmith** [comment] 2022-11-05 21:27
You might be interested in [PEP 671](https://peps.python.org/pep-0671/ ) "Syntax for late-bound function argument defaults". It discusses some of the issues, which if you read between the lines sort of explains why we have today's behavior. But note it hasn't been submitted to the Steering Council.

I'm going to close this as "not a bug".

**Closed as not planned by ericvsmith** 2022-11-05 21:27 UTC
Labels: type-bug

**Comment by stevendaprano** [comment] 2022-11-05 23:54
A couple of further comments:

1. This is a [FAQ](https://docs.python.org/3/faq/programming.html#why-are-default-values-shared-between-objects).
2. If you [google Python mutable default values](https://www.bing.com/search?q=python+mutable+default+values) you will find many places discussing this.
3. I don't know why Guido choose this behaviour 30+ years ago, but my guess is because it is faster and simpler to implement. To store the default value, you just keep a reference to the object, not an expression that needs to be evaluated; to recall it, you just fetch the object.
4. If a language supports only one of early-bound defaults (like Python) and late-bound defaults (like Ruby), it is better to use early-bound. Both cases are surprising under some circumstances, but early-binding is more flexible and allows you to emulate late-binding far more easily than late-binding allows you to emulate early-binding.
5. Your code mentions the "memory location" of the objects, but the number returned by `id()` is an abstract object ID, not a guaranteed memory location. CPython merely uses the memory location as a short-cut for generating IDs, which it can do because of its simple memory management and garbage collection. If CPython ever gets a compacting garbage collector (as Jython and IronPython have) objects can be relocated in memory and IDs will likely be changed to consecutive numbers like 1, 2, 3, 4, ... (as Jython and IronPython already do).

Further discussion should move off the bug tracker onto (say) Python's Discourse.

**Comment by 80columns** [comment] 2022-11-06 00:50
Thank you Steve, really appreciate you taking the time to share these resources. I asked a friend who is experienced with Python and did some google searches first but didn't find anything. I do more research in the future before coming here.
