### ISSUE TITLE
Bad error message from subprocess module

### ISSUE THREAD

**Issue by bobjalex** [python/cpython#96147] opened 2022-08-20 19:35 UTC
# Bug report

Got the following exception from subprocess when giving it nonexistent command name:

  File "C:\Users\bobja\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 546, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bobja\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bobja\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

The command name was in fact incorrect, but the message is not very helpful  :-)

# Your environment

- CPython versions tested on: Python 3.11.0rc1
- Operating system and architecture:
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22000 N/A Build 22000

**Comment by eryksun** [comment] 2022-08-20 22:06
`ERROR_BAD_EXE_FORMAT` (193) means that `CreateProcess()` tried to execute a file that's not a PE executable. If the file didn't exist, the error would be `ERROR_FILE_NOT_FOUND` (2). For a more complete and relevant explanation, you'll have to provide the details of the `subprocess.run()` call.

**Comment by bobjalex** [comment] 2022-08-21 07:34
I understand what the message means, and I know why the error occurred
in my case. The interesting thing is that instead of the name of the file
in question, "%1" appears in the message -- that should be fixed.

**Comment by eryksun** [comment] 2022-08-21 14:01
> instead of the name of the file in question, "%1" appears in the message -- that should be fixed.

This is duplicate of issue #70680.

The interpreter uses localized system error messages from [`FormatMessageW()`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessagew). The generic handling in the interpreter doesn't know the number and types of inserts in a message [^1], so the flag `FORMAT_MESSAGE_IGNORE_INSERTS` is used. This is the recommended approach, as discussed in the article ["The importance of the FORMAT_MESSAGE_IGNORE_INSERTS flag"](https://devblogs.microsoft.com/oldnewthing/20071128-00/?p=24353) by Raymond Chen.  

Either `subprocess.Popen` or [`_winapi.CreateProcess()`](https://github.com/python/cpython/blob/bcc4cb0c7d5e0590928e74cae86b0a7938c0f74b/Modules/_winapi.c#L1046) could include the filename in the `OSError` exception. This would be the `application_name` parameter if it's used, else the filename has to be parsed out of `command_line`. Numbered inserts would still be in some messages, but I don't think that's a problem that's worth solving. In #70680, I suggested replacing the error message entirely, but the downside is that custom error messages would be in English, while all other OS error messages would be localized in the user's preferred language.

[^1]: Some of the system error messages are unusual in that they contain captions enclosed in curly braces and C format specifiers instead of numbered inserts. Some of these messages can't even be read completely by `FormateMessageW()` because they unintentionally contain the "%0" escape (i.e. terminate message text). For example, `ERROR_UNHANDLED_EXCEPTION` (574) has the error message `"{Application Error}\r\nThe exception %s (0x%08lx) occurred in the application at location 0x%08lx"`. This message was copied from the system status code `STATUS_UNHANDLED_EXCEPTION` (0xC0000144). It's intended for the system's hard-error handler, by way of the system call `NtRaiseHardError()` and related functions in the kernel. It's not intended for `FormatMessageW()`.

**Closed as not planned by eryksun** 2022-08-21 14:01 UTC
Labels: type-bug
