### ISSUE TITLE
Exception when executing `python3 -m pprint`

### ISSUE THREAD

**Issue by YanHuaSuiMei** [python/cpython#93366] opened 2022-05-31 01:54 UTC
**Bug report**

```
> python -m pprint 
Traceback (most recent call last): 
  File "C:\Users\rwx1168020\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main 
    return _run_code(code, main_globals, None,
  File "C:\Users\rwx1168020\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rwx1168020\AppData\Local\Programs\Python\Python310\lib\pprint.py", line 670, in <module>
    _perfcheck()
  File "C:\Users\rwx1168020\AppData\Local\Programs\Python\Python310\lib\pprint.py", line 645, in _perfcheck
    p._safe_repr(object, {}, None, 0, True)
TypeError: PrettyPrinter._safe_repr() takes 5 positional arguments but 6 were given
```

In `pprint.py`:

```
class PrettyPrinter:
   ...
   self._safe_repr(self, object, context, maxlevels, level):
   ...

...

def _perfcheck(object=None):
    import time
    if object is None:
        object = [("string", (1, 2), [3, 4], {5: 6, 7: 8})] * 100000
    p = PrettyPrinter()
    t1 = time.perf_counter()
    p._safe_repr(object, {}, None, 0, True)
    t2 = time.perf_counter()
    p.pformat(object)
    t3 = time.perf_counter()
    print("_safe_repr:", t2 - t1)
    print("pformat:", t3 - t2)

...

if __name__ == "__main__":
    _perfcheck()
```

Incorrect function call: p._safe_repr(object, {}, None, 0, True)

**Your environment**

*Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32*

**Comment by ericvsmith** [comment] 2022-05-31 01:58
This is a duplicate of #92546.

**Closed as completed by ericvsmith** 2022-05-31 01:58 UTC
Labels: type-bug

**Comment by YanHuaSuiMei** [comment] 2022-05-31 02:02
well . . .

**Comment by iritkatriel** [comment] 2022-05-31 06:39
> well . . .

We’re discussing solutions on that issue. Can you explain why this is an actual problem for you? (That would inform our discussion).

**Comment by YanHuaSuiMei** [comment] 2022-05-31 07:56
I found the module 'pprint.py' can be executed as a module when i learned it.
When i learn, i always look docs first, code next. 

It's not an actual problem for me, just want to make python better. :)
