### ISSUE TITLE
"warning: ‘kind’ may be used uninitialized" in `longobject.c`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116592] opened 2024-03-11 10:53 UTC
# Bug report

New CI worker identified two possible problems: https://buildbot.python.org/all/#/builders/1379/builds/1

```
Objects/longobject.c: In function ‘long_format_binary’:
Objects/longobject.c:2321:13: warning: ‘kind’ may be used uninitialized [-Wmaybe-uninitialized]
 2321 |     else if (kind == PyUnicode_1BYTE_KIND) {
      |             ^
Objects/longobject.c:2197:9: note: ‘kind’ was declared here
 2197 |     int kind;
      |         ^~~~
Objects/longobject.c: In function ‘long_to_decimal_string_internal’:
Objects/longobject.c:2144:13: warning: ‘kind’ may be used uninitialized [-Wmaybe-uninitialized]
 2144 |     else if (kind == PyUnicode_1BYTE_KIND) {
      |             ^
Objects/longobject.c:1968:9: note: ‘kind’ was declared here
 1968 |     int kind;
      |         ^~~~
```

I don't think that this can ever happen, but, because of how code is written, static analysis is unsure about it:

https://github.com/python/cpython/blob/1cc02ca063f50b8c527fbdde9957b03c145c1575/Objects/longobject.c#L2076-L2097

Notice how `if (bytes_writer)` does not have `kind = ` part.

I think it is safe to assign `kind` as `0` by default. Because it is expected to be 1, 2, or 4.
And it is asserted to be in this range with `if`s and `assert (kind == PyUnicode_4BYTE_KIND);`

One more thing: right now it is possible to pass both `writer` and `bytes_writer` or both `NULL`s.
I think that we should also an assert: only one of them can be present.

### Linked PRs
* gh-116599

**Comment by erlend-aasland** [comment] 2024-03-11 13:51
Duplicate of #110819

**Closed as not planned** 2024-03-11 14:04 UTC
Labels: type-bug, interpreter-core
