### ISSUE TITLE
`property` assumes that its subclasses have __dict__

### ISSUE THREAD

**Issue by encukou** [python/cpython#98963] opened 2022-11-01 14:43 UTC
`property`'s `tp_init` has [this code](https://github.com/python/cpython/blob/f042646595d1cdd2ecdc15222b1766f746d010f0/Objects/descrobject.c#L1813-L1832):

```
    if (Py_IS_TYPE(self, &PyProperty_Type)) {
        Py_XSETREF(self->prop_doc, prop_doc);
    } else {
        /* If this is a property subclass, put __doc__
           in dict of the subclass instance instead,
           otherwise it gets shadowed by __doc__ in the
           class's dict. */

        /*...*/
         PyObject_SetAttr((PyObject *)self, &_Py_ID(__doc__), prop_doc);
        /*...*/
    }
```

This assumes that subclasses of `property` have a `__dict__` (or a `__doc__` attribute settable by other means). That is the case when subclassed using the `class` statement, but might not be true using C.
A C-API reproducer is at https://github.com/wjakob/inheritance_issue/blob/master/inheritance_issue.c

I don't see a good way to fix this. We could:
- document that subclasses need to set `Py_TPFLAGS_MANAGED_DICT` (or provide a `__doc__` descriptor), or 
- ignore the `AttributeError`, unless `__doc__` was set explicitly?

* PR: gh-99058

* PR: gh-105262

* PR: gh-105297

**Comment by rhettinger** [comment] 2022-11-02 04:50
I recommend ignoring the AttributeError.  Loss of a `__doc__` in this situation is of no consequence.

**Comment by encukou** [comment] 2022-11-02 08:54
Thinking about it more, I came to the opposite conclusion.

Ignoring `AttributeError` moves the surprising behavior elsewhere – now people would wonder why __doc__ isn't set as requested. (Worse, if the `property` subclass is defined in a library, it's likely that a *user* would bump into this, rather than the library author.)

The main issue here is that the error is *surprising* – it's not clear what's happening and what the right course of action is. If you're subclassing `property` in the C API, adding a `__doc__` descriptor (or adding `Py_TPFLAGS_MANAGED_DICT`/`tp_dictoffset`) shouldn't be an issue – *if* you know that's what's necessary. (If losing `__doc__` is OK, the descriptor can even ignore the data and always get `None`. Making it explicit sounds better in this case.)
So, another option is to just raise a better error – “property subclasses require a writable __doc__ instance attribute”?

**Comment by wjakob** [comment] 2022-11-02 08:57
I also don't think that losing the `__doc__` silently is a good behavior. Would it not be an option to relax the condition at the top? Instead of `Py_IS_TYPE(self, &PyProperty_Type)`, the test could be check if the type has an associated dictionary? If not, it could write to `self->prop_doc`, which would address the unexpected behavior when subclassing such types from C.

**Comment by encukou** [comment] 2022-11-02 09:28
> If somewhere in the type hierarchy, we expose a writable `__doc__` field via `tp_members`

`property` does that. But Python doesn't consider the superclass's descriptor (even when setting it) when there's a class attribute of the same name on the subclass. Here, that's the subclass's own docstring (`None` by default).

To make `__doc__` work, it needs to either be a descriptor on the subclass, or an attribute on the instance.

**Comment by encukou** [comment] 2022-11-03 08:45
> any proposed change should be minimally invasive.

I definitely agree with that! I hope to only touch the error case.

>  AFAICT, the only motivation for an edit is to accommodate single, new, and somewhat exotic C extension.

My opinion here is more nuanced though. The C API is not used only with C, and I've been trying to make it more useful with other languages (C++, Rust, Java). Language bindings work at a lower level than typical C extensions, so they run into subtle bugs we haven't seen before.
So, yes, it's a somewhat exotic C extension – but if we fix the issues it encounters, we'll hopefully get more extensions like it, and it'll become less exotic.

> It doesn't feel like my assessment is being valued.

I'm sorry I made you feel this way. I tried to react to you and explain my reasoning. How can I do better?

**Comment by wjakob** [comment] 2022-11-03 13:09
For what it's worth, I understand @rhettinger's concern that this is somewhat of a niche issue. While making Python behave more as expected is desirable, I would already be very happy simply with guidance on how to work around this issue in a stable manner (meaning that it works for past Python versions, and that I can have some reasonable assurance it won't break in the future).

Alas, that requirement of stability is what is making things very difficult:

- @encukou suggested that the subclass should expose a writeable `__doc__` member. However, the behavior of such a combination is unstable across Python versions. A minimal C-API reproducer can be found here: https://github.com/wjakob/inheritance_issue_2/blob/master/inheritance_issue_2.c

  To try:
  ```bash
  $ pip install git+https://github.com/wjakob/inheritance_issue_2
  ```

  In Python 3.10
  ```pycon
  >>> import inheritance_issue_2
  >>> print(inheritance_issue_2.my_property(lambda x: None, doc='test').__doc__)
  None
  ```

  In Python 3.12 (main)
  ```pycon
  >>> import inheritance_issue_2
  >>> print(inheritance_issue_2.my_property(lambda x: None, doc='test').__doc__)
  test
  ```

- ``Py_TPFLAGS_MANAGED_DICT`` suggested by @encukou is not in the limited API, which I require at least as an optional build configuration. So that one is out.

- Installing an unmanaged dictionary via ``__dictoffset__`` is unstable across Python versions. A minimal C-API reproducer can be found here: https://github.com/wjakob/inheritance_issue_3/blob/master/inheritance_issue_3.c

  To try:
  ```bash
  $ pip install git+https://github.com/wjakob/inheritance_issue_3
  ```

  In Python 3.10
  ```pycon
  >>> import inheritance_issue_3
  >>> print(inheritance_issue_3.my_property(lambda x: None, doc='test').__doc__)
  None
  ```

  In Python 3.12 (main)
  ```pycon
  >>> import inheritance_issue_3
  >>> print(inheritance_issue_3.my_property(lambda x: None, doc='test').__doc__)
  test
  ```

- The only thing I have discovered so far which _consistently_ works across Python versions is to set the new property type's ``tp_members`` pointer to ``PyProperty_Type.tp_members``. This can be done even in the limited API via `PyType_GetSlot`, but as @encukou pointed out this makes too many assumptions about the underlying implementation. So although it happens to compile and work with ``-DPy_LIMITED_API`` right now, it is not future-proof.

If you have advice on other things to try, I am all ears.. :)

**Comment by encukou** [comment] 2022-11-03 13:58
Aha! It turns out that this was not stable -- in fact this was just changed for 3.12: https://github.com/python/cpython/pull/23205
(If anything, this underscores the point that touching old code should be done extremely carefully.)

@wjakob: There's even some pybind11 fallout: https://github.com/pybind/pybind11/pull/4168

Given that silencing the `AttributeError` would essentially revert this case to pre-3.12 behavior, it would make sense.
But, before I wrote this I already wrote a patch for improving the error message, so I'll post it here: https://github.com/python/cpython/pull/99058

**Comment by wjakob** [comment] 2022-11-03 14:17
Aha, that is great to know that v3.12 is the place where this change happened. Incidentally, this is also the first Python version for which `-DPy_LIMITED_API` will be complete enough for my project.

So what I am thinking to do now as a workaround is:

- For Python < 3.12, set the new property's ``tp_members`` field to ``PyProperty_Type.tp_members``.

- For Python >= 3.12 and in particular limited API mode, declare an independent ``tp_members`` field that adds a ``__doc__`` field.

The error message in PR #99058 looks good to me.

**Comment by encukou** [comment] 2022-11-03 16:37
Actually, the Python 3.12 change was for the `doc` argument – when the docstring is being copied from a setter function, instantiation does fail as far back as Python 2. Pre-3.12, the `doc` argument doesn't work on subclasses at all.

**Comment by wjakob** [comment] 2022-11-03 23:21
Are you referring to the `doc` argument of the constructor? This evening's latest version of nanobind passes it to a subclass of `property` with the fixes mentioned above (https://github.com/wjakob/nanobind/commit/e82f14af43e460b80f62c6d3ac11422ec6976727). It passes the test suite, which checks that the docstring is set correctly. This works on Python 3.8-3.12, and on 3.12 with Py_LIMITED_API.

**Comment by gpshead** [comment] 2023-06-02 22:57
This came up in protobuf because it has a

```python
class _FieldProperty(property):
  __slots__ = ("DESCRIPTOR",)
```

calling `property.__init__()` on such a class instance fails the an exception.

```python
    property.__init__(self, getter, setter, doc=doc)
AttributeError: 'ExampleProperty' object attribute '__doc__' is read-only
```

If '"__doc__"' is added to the `__slots__` tuple, it works again.

In older versions of Python the the property constructor silently does not assign a docstring rather than causing an `AttributeError`.

**Comment by gpshead** [comment] 2023-06-02 23:00
That is narrower than the larger issue here, but I think we should mirror that silent doc-dropping behavior for 3.12 and consider if we're deprecating that behavior later or just want to make it official.

**Comment by gpshead** [comment] 2023-06-03 00:50
> That is narrower than the larger issue here

re-reading things, I don't think that is true. This issue title talks about a dict, but the issue is entirely about a the docstring being unsettable and whether that is ignored as it always has been or is an expected behavior changing error.

Existing code depends on it being ignored.

**Comment by gpshead** [comment] 2023-06-05 03:30
closing as the 3.12 PR is set to automerge; previous exception / ignored error behavior has been restored.

**Closed as completed by gpshead** 2023-06-05 03:30 UTC
Labels: type-bug, topic-C-API, 3.12

**Comment by gpshead** [comment] 2023-06-07 19:23
Related to this in general... CPython <=3.11 has some seriously smelly behavior:

```python
Python 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class slotted_property(property):
...   __slots__ = ()
... 
>>> slotted_property()
<__main__.slotted_property object at 0x7f36e189dad0>
>>> slotted_property(lambda x: None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'slotted_property' object attribute '__doc__' is read-only
>>> slotted_property(lambda x: None, doc='ignored').__doc__
>>> slotted_property(lambda x: None, doc='').__doc__
>>> slotted_property(lambda x: None, doc=None).__doc__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'slotted_property' object attribute '__doc__' is read-only
>>>
```

**Comment by encukou** [comment] 2023-06-12 14:16
Thank you for taking this on!

**Comment by wjakob** [comment] 2023-06-12 14:18
A thanks from me as well. With your change, I was able to remove the Python 3.12-specific workaround/hack from nanobind.
