### ISSUE TITLE
URL in PyType_Slot has repeated the type name

### ISSUE THREAD

**Issue by Ramin-RX7** [python/cpython#98184] opened 2022-10-11 15:28 UTC
In the documentation, URL of  [PyType_Slot.slot](https://docs.python.org/3/c-api/type.html?highlight=pytype_#c.PyType_Slot.PyType_Slot.slot) has repeated the "PyType_Slot".
Now I'm not sure if this is a mistake or not because it is also under [PyType_Slot](https://docs.python.org/3/c-api/type.html?highlight=pytype_#c.PyType_Slot) section (so the repetition might be true)

![Screenshot (572)](https://user-images.githubusercontent.com/52785580/195134039-a73241b5-1296-418c-8e41-464fb911094f.png)
Screenshot is taken from [PyType_Slot](https://docs.python.org/3/c-api/type.html?highlight=pytype_#c.PyType_Slot) and link in the bottom left is showing [PyType_Slot.slot](https://docs.python.org/3/c-api/type.html?highlight=pytype_#c.PyType_Slot.PyType_Slot.slot) URL.

**Comment by Ramin-RX7** [comment] 2022-10-11 15:52
After few minutes looking around, only found [PyType_Spec](https://docs.python.org/3/c-api/type.html?highlight=pytype_#c.PyType_Spec) as another example of this problem(?). But also found that PyType_Spec is already mentioned in #97908 so I'm not sure, this issue might be duplicate

**Comment by sobolevn** [comment] 2022-10-12 18:49
Yes, this looks like a duplicate of https://github.com/python/cpython/issues/97908

Thanks for noticing it, @Ramin-RX7!

**Closed as not planned by sobolevn** 2022-10-12 18:49 UTC
Labels: docs
