### ISSUE TITLE
`platform.processor()` and `platform.machine()` report inconsistent values under Rosetta on M1 macOS

### ISSUE THREAD

**Issue by rossng** [python/cpython#96993] opened 2022-09-21 14:06 UTC
# Bug report

When I run the Python interpreter in `x86_64` mode on an M1 MacBook, I get an unexpected result from `platform.machine()`.

In `arm64` mode:

```
ross@Rosss-MBP ~ % arch -arm64 python   
Python 3.10.6 (main, Sep 21 2022, 15:43:11) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.processor(), platform.machine()
('arm', 'arm64')
```

In `x86_64` mode:

```
ross@Rosss-MBP ~ % arch -x86_64 python
Python 3.10.6 (main, Sep 21 2022, 15:43:11) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.processor(), platform.machine()
('i386', 'arm64')
```

Not that the `processor` is correct, but the `machine` is not.

Using an `x86_64` [`cling`](https://root.cern/cling/) binary gives the expected result:

```
ross@Rosss-MBP ~ % file /usr/local/Cellar/cling/0.9/bin/cling
/usr/local/Cellar/cling/0.9/bin/cling: Mach-O 64-bit executable x86_64
ross@Rosss-MBP ~ % /usr/local/Cellar/cling/0.9/bin/cling 

[cling]$ #include <sys/utsname.h>
[cling]$ struct utsname u;
[cling]$ uname(&u);
[cling]$ u.machine
(char [256]) "x86_64\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
```

As does calling out to the `uname` utility as a subprocess:

```
ross@Rosss-MBP ~ % arch -x86_64 python
Python 3.10.6 (main, Sep 21 2022, 15:43:11) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.check_output(['uname', '-p'], stderr=subprocess.DEVNULL, text=True,)
'i386\n'
>>> subprocess.check_output(['uname', '-m'], stderr=subprocess.DEVNULL, text=True,)
'x86_64\n'
```

It looks like the [implementation of `platform.process()`](https://github.com/python/cpython/blob/4b81139aac3fa11779f6eedb6e621bde29e64b30/Lib/platform.py#L823) works the same way as this - by calling out to a subprocess - whereas `platform.machine()` [uses the `uname` syscall directly](https://github.com/python/cpython/blob/4b81139aac3fa11779f6eedb6e621bde29e64b30/Modules/posixmodule.c#L5113).

~Not sure what causes this - perhaps it's a fundamental problem for Universal Binaries? In any case, it might be a good idea to patch for this case (since the output makes no sense at the moment).~

Edit: not a universal binary issue - see below.

# Your environment

- CPython versions tested on: 3.10.6, installed through pyenv
- Operating system and architecture: macOS 12.6, M1 MacBook Pro

**Comment by rossng** [comment] 2022-09-21 14:29
A quick experiment shows that this does not appear to be inherent to universal binaries:

main.c:

```c
#include <stdio.h>
#include <sys/utsname.h>

int main(int argc, const char * argv[]) {
    struct utsname u;
    uname(&u);
    printf("uname machine: %s\n", u.machine);
    return 0;
}
```

```
ross@Rosss-MBP bin % file uname-tester          
uname-tester: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64
- Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64
- Mach-O 64-bit executable arm64]
uname-tester (for architecture x86_64):	Mach-O 64-bit executable x86_64
uname-tester (for architecture arm64):	Mach-O 64-bit executable arm64
ross@Rosss-MBP bin % arch -arm64 ./uname-tester
uname machine: arm64
ross@Rosss-MBP bin % arch -x86_64 ./uname-tester
uname machine: x86_64
```

**Comment by rossng** [comment] 2022-09-21 14:33
Aha - it seems that pyenv did not in fact install a universal Python binary, which would explain this behaviour.

I do still think the output is quite confusing, so maybe this is a case where it would be better to clarify the documentation.

**Comment by kwsp** [comment] 2022-10-17 05:29
Interesting... on my M1 mac with Python 3.8.9 (from `/usr/bin/python3`) that I assume is shipped as part of macOS Monterey, I get

```
~ /usr/bin/python3
Python 3.8.9 (default, Apr 13 2022, 08:48:06)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.processor(), platform.machine()
('arm', 'arm64')
```

```
~ arch -x86_64 /usr/bin/python3
Python 3.8.9 (default, Apr 13 2022, 08:48:07)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.processor(), platform.machine()
('i386', 'x86_64')
```

So this is possibly a regression. I can do a bisect when I get some time.

I agree with @ronaldoussoren that the documentation needs an update to clarify cases when the program runs under emulation. Possibly with the fix of this bug.

**Comment by kwsp** [comment] 2022-10-17 05:34
@rossng if pyenv didn't install a universal binary, how did the binary even execute under x86_64? When I try this on a arm64 binary, I get

```
~ file $(which python3)
/opt/homebrew/bin/python3: Mach-O 64-bit executable arm64
~ arch -x86_64 python3
arch: posix_spawnp: python3: Bad CPU type in executable
```

**Comment by rossng** [comment] 2022-11-17 11:20
I think the problem may stem from my default `python3` executable being the one from miniconda, which appears to be an `x86-64` binary.

```
❯ python3
Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'x86_64'
```

```
❯ which python3
/usr/local/Caskroom/miniconda/base/bin/python3

❯ objdump -a /usr/local/Caskroom/miniconda/base/bin/python3
/usr/local/Caskroom/miniconda/base/bin/python3:	file format mach-o 64-bit x86-64
```

I just ran into this issue again when trying to compile Blender - also reported before at https://developer.blender.org/T78710#1160643

**Comment by ronaldoussoren** [comment] 2023-12-08 16:42
On my laptop running macOS 14.1 I get:

```
arch -x86_64 /usr/bin/python3 -c 'import platform; print(platform.processor(), platform.machine())'                                     
i386 x86_64
```

This happens with all version I've installed, including 3.9 upto 3.13 installed using our installer.  This might be a change of behaviour in macOS though, can someone test this on an M1 system running macOS 11, 12 or 13? 

There doesn't seem to be anything to do here, the behaviour is consistent with the expected system behaviour when running under Rosetta 2: the launched application sees the system as if it is running on an x86_64 system.

**Comment by ronaldoussoren** [comment] 2023-12-30 11:11
Closing this issue because as mentioned earlier the behaviour I'm seeing on macOS 14 is consistent with the expected behaviour for applications running under Rosetta 2.

**Closed as completed by ronaldoussoren** 2023-12-30 11:11 UTC
Labels: type-bug, OS-mac
