### ISSUE TITLE
listobject.h:33:36: error: void value not ignored as it ought to be

### ISSUE THREAD

**Issue by AlexLuya** [python/cpython#94507] opened 2022-07-02 10:43 UTC
**Bug report**
When running a "python3 setup install",I got an error:

```
/usr/include/python3.10/cpython/listobject.h:33:36: error: void value not ignored as it ought to be
   33 | #define PyList_SET_ITEM(op, i, v) ((void)(_PyList_CAST(op)->ob_item[i] = (v)))
      |                                   ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Cursor.c:1088:13: note: in expansion of macro ‘PyList_SET_ITEM’
```

**Your environment**
- CPython versions tested on:   0.29.28
- Operating system and architecture: ubuntu 22.04 x86_64

**Comment by JelleZijlstra** [comment] 2022-07-02 13:12
What library are you installing? This looks like a bug in the library, not CPython itself.

**Comment by ericvsmith** [comment] 2022-07-02 13:16
And which version of Python? “ CPython versions tested on: 0.29.28” isn’t right.

**Comment by arhadthedev** [comment] 2022-07-02 13:23
@ericvsmith A path from the error message suggests it's 3.10.

@AlexLuya Can you write here an output of `python --version`? It gives a full version.

**Comment by AlexLuya** [comment] 2022-07-02 14:15
> @ericvsmith A path from the error message suggests it's 3.10.
> 
> @AlexLuya Can you write here an output of `python --version`? It gives a full version.

Python 3.10.4

**Comment by da-woods** [comment] 2022-07-03 07:00
> And which version of Python? “ CPython versions tested on: 0.29.28” isn’t right.

This looks like a recent Cython version to me. Post it on the Cython bug tracker instead. https://github.com/cython/cython/issues

Remember to include enough code to actually reproduce the bug

**Comment by da-woods** [comment] 2022-07-05 05:38
My conclusion having looked at it as a Cython issue: I don't think this is a Cython issue (even though a Cython version was quoted I don't think it looks like Cython-generated code).

Whatever library it was was probably broken by https://github.com/python/cpython/pull/19975. It looks from the description there that this change was expected and intended to break some C API code.

**Comment by da-woods** [comment] 2022-07-05 05:42
And you probably just want to replace `PyList_SET__ITEM` with `PyList_SetItem`. Maybe.

**Comment by JelleZijlstra** [comment] 2022-07-05 15:14
Closing since this doesn't seem to be a bug in CPython (and likely not in Cython either, thanks @da-woods for looking).

**Closed as not planned by JelleZijlstra** 2022-07-05 15:14 UTC
Labels: type-bug
