### ISSUE TITLE
random.choices undefined behavior when some weights are not finite or negative

### ISSUE THREAD

**Issue by leikdga** [python/cpython#118961] opened 2024-05-12 04:06 UTC
# Feature or enhancement

### Problem

In current [doc of random module](https://docs.python.org/3.14/library/random.html), it is mentioned that 

> Weights are assumed to be non-negative and finite. 

But what will happen if user violates this rule?

The program will just give strange result, which is also counter intuitive.

Here are some examples,

```python
from collections import Counter
import random

l = random.choices([1, 2, 3], weights=[2, -1, 1], k=1000)
print(Counter(l))  # Counter({3: 513, 1: 487})

l = random.choices([1, 2, 3], cum_weights=[2, float("inf"), 3], k=1000)
print(Counter(l))  # Counter({1: 658, 2: 342})

```

### Proposal

We could explicitly raise an exception in such cases.

### Has this already been discussed elsewhere?

As far as I'm aware, no.

### Links to previous discussion of this feature:

N/A

### Linked PRs
* gh-118962

**Comment by mdickinson** [comment] 2024-05-12 11:53
See #81805, #75870, #85939 for previous discussions.

**Comment by rhettinger** [comment] 2024-05-12 18:02
I've looked back over the previous discussions and think the outcome should be the same, leaving the code and docs as-is.

We do some inexpensive checks for to assure the weights total is positive and finite.  This seems to suffice in practice. There doesn't seem to be a compelling need to check each weight individually.  That adds a cost that makes everyone pay for a problem that almost no one has.

I'll leave this open a bit for more discussion, but I'm inclined to close it.  The current design is exactly what was intended.

**Closed as not planned** 2024-05-13 13:40 UTC
Labels: type-feature
