### ISSUE TITLE
argparse error with option with optional value

### ISSUE THREAD

**Issue by 5f801420-162a-49b2-85dd-2b8a66da31f2** [python/cpython#89836] opened 2021-10-29 17:06 UTC
BPO | [45673](https://bugs.python.org/issue45673)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-29.17:06:05.040>
labels = ['3.8', 'type-bug', 'library']
title = 'argparse error with option with optional value'
updated_at = <Date 2021-11-02.22:25:15.777>
user = 'https://bugs.python.org/paolobenve'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-02.22:25:15.777>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-10-29.17:06:05.040>
creator = 'paolobenve'
dependencies = []
files = []
hgrepos = []
issue_num = 45673
keywords = []
message_count = 5.0
messages = ['405322', '405523', '405561', '405562', '405564']
nosy_count = 2.0
nosy_names = ['paul.j3', 'paolobenve']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45673'
versions = ['Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment] 2024-09-25 18:47
Closed as a duplicate of #53584.

**Closed as not planned by serhiy-storchaka** 2024-09-25 18:47 UTC
Labels: type-bug, stdlib, 3.8 (EOL)
