### ISSUE TITLE
Large yellow boxes on many Python 3.10 documentation pages

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#95702] opened 2022-08-05 08:09 UTC
The "See also" boxes on Python 3.10 docs (but not Python 3.9, 3.11 or 3.12) seem broken in that they extend well past where they're meant to end.

For example on:
https://docs.python.org/3/library/re.html (the box starting with "The third-party regex module")
https://docs.python.org/3/library/collections.html (the box starting with "The MultiContext class")

**Comment by AlexWaygood** [comment] 2022-08-05 08:11
Duplicate of #91483

**Closed as not planned by AlexWaygood** 2022-08-05 08:11 UTC
Labels: type-bug, docs
