### ISSUE TITLE
ASCII related bug in python core built_in function

### ISSUE THREAD

**Issue by yingshaoxo** [python/cpython#122335] opened 2024-07-26 23:48 UTC
# Bug report

### Bug description:

```python
for i in range(0, 254):
     chr(i).encode("ascii")
```

It raises an error:
```
> UnicodeEncodeError: 'ascii' codec can't encode character '\x80' in position 0: ordinal not in range(128)
```

The chr documentation didn't mention anything about this, but I think ascii contains characters from 0 to 255.

https://docs.python.org/3/library/functions.html#chr

https://www.w3schools.com/python/ref_func_chr.asp

https://www.geeksforgeeks.org/chr-in-python/#:~:text=Print%20ASCII%20Values%20From%200%20to%20255%20In%20Python

___

Can we use `open(file, encoding="ascii_extended")` to open ascii code that in (0,255)?

The python documentation should say the ascii encoding in python only support 0 and 128, the chr() returned char only the 0 and 128 is ascii code, others are unicode.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by picnixz** [comment] 2024-07-27 00:20
This is not a bug. By definition, ASCII is a 7-bit encoding and supports characters from 0 to 127 included. Including range 128 to 255 is usually called the extended ASCII range. If you want to use the 'latin-1' encoding.

Closing as a non-issue.

**Closed as not planned by picnixz** 2024-07-27 00:20 UTC
Labels: invalid
