### ISSUE TITLE
Windows build of local repository main branch crashes

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#93036] opened 2022-05-21 01:13 UTC
Problem involves pylifecycle.c and PCbuild/_freeze_module.vcxproj and something else?
Windows 10, MSC v.1900 64 bit (2015 I believe.)
``` 
f:\dev\3x>pcbuild\build.bat -d  # same without -D
...
 pylifecycle.c
..\Python\pylifecycle.c(101): error C2061: syntax error: identifier '_PyRuntime
' [f:\dev\3x\PCbuild\_freeze_module.vcxproj]
..\Python\pylifecycle.c(101): error C2059: syntax error: ';' [f:\dev\3x\PCbuild
\_freeze_module.vcxproj]
..\Python\pylifecycle.c(105): error C2513: ' ': no variable declared before '='
 [f:\dev\3x\PCbuild\_freeze_module.vcxproj]

<A repeat of the error message>
```
Lines from lifecycle.c:
098: /* Suppress deprecation warning for PyBytesObject.ob_shash */
...
101: _PyRuntimeState _PyRuntime
...
105: = _PyRuntimeState_INIT;
```
After normal fetch and merge, git status says my repository is up to date.  I ran `>chkdsk -F` on the repository drive and nothing seem amiss.  I need this fixed to properly test new patches locally.

Problem began sometime after Mar 23 and before mid or maybe last April.  At the time, main was 3.11.0a+.  Problem continues today in 3.12.0?.  I presume newish 3.11.0b1 branch has the same issue.  Current 3.9 and 3.10 build fine.
@zooba Was _freeze_module patched near the end of March?
@eryksun Do you have any idea what could be wrong?

**Comment by zware** [comment] 2022-05-21 02:37
Duplicate of #93038 (technically the other way around, but the other one has been publicly linked to already).

**Closed as not planned by zware** 2022-05-21 02:37 UTC
Labels: type-bug, OS-windows, build
