### ISSUE TITLE
create_builtin() in _imp module trigger segfault if taking a builtin object as input

### ISSUE THREAD

**Issue by xiaxinmeng** [python/cpython#98354] opened 2022-10-17 11:56 UTC
# Crash report
In the following test program, _imp.create_builtin takes a object A as input. The object instance the name attribute as "self" at "self.name = self". This action triggers a segfault on CPython 3.10.7 and CPython 3.10.7. Similarly, if self.name = other keywords, e.g.,int, print, the program also crashes. It may need a checker for  _imp.create_builtin to avoid keywords.

```
import _imp

class FakeSpec:
	def __init__(self, name):
		self.name = self

A = FakeSpec("time")

imp_time = _imp.create_builtin(A)
```

# Error messages

Expected behavior on CPython 3.9.0
```
Traceback (most recent call last):
  File "/home/xxm/Desktop/imp.py", line 9, in <module>
    imp_time = _imp.create_builtin(A)
TypeError: bad argument type for built-in operation
```

Unexpected Behavior on CPython 3.10.8
Segmentation fault(core dumped)  

# Your environment

- CPython versions tested on:Python 3.10.8, Python 3.10.7

- Operating system and architecture: [GCC 7.5.0] on linux

**Comment by ericsnowcurrently** [comment] 2022-10-19 16:42
To be clear, code should not be using the `_imp` module directly.  That said, this would be relatively easy to reproduce with a metapath finder.

Regardless, I was able to reproduce this on main (3.12, c051d55ddb29) using the OP code.  It is not crashing on 3.8 (but does fail with a TypeError).  Likewise with 3.9.

It does start crashing in 3.10.  Looks like it started in 62230714213 (GH-23378).  It was probably caught before by the `PyUnicode_AsUTF8()` (which was removed).  Checking for `PyUnicode` should restore the pre-3.10 behavior.

**Comment by ericsnowcurrently** [comment] 2022-11-02 16:21
Per https://github.com/python/cpython/pull/98412#issuecomment-1287478504, this might not be completely fixed yet.

@xiaxinmeng, can you verify if the problem you had is fixed on [the main branch](https://github.com/python/cpython/tree/main) (i.e. `3.12a1`)?

**Comment by ericsnowcurrently** [comment] 2022-11-21 17:20
Additional info from @chgnrdv:

* https://github.com/python/cpython/pull/98412#issuecomment-1301020123
* https://github.com/python/cpython/pull/98412#issuecomment-1301934245

@chgnrdv, can you confirm this is fixed by gh-99642 (for gh-99578)?  If so, we can close this issue.

**Comment by michael199309** [comment] 2022-11-23 04:55
> Per [#98412 (comment)](https://github.com/python/cpython/pull/98412#issuecomment-1287478504), this might not be completely fixed yet.
> 
> @xiaxinmeng, can you verify if the problem you had is fixed on [the main branch](https://github.com/python/cpython/tree/main) (i.e. `3.12a1`)?

Sorry for being late. I think this problem has been fixed. 
It does not crash CPython any more, the behavior on the main branch [8f18ac0](https://github.com/python/cpython/commit/8f18ac04d32515eab841172c956a8cb14bcee9c3) is as follows:

```
Traceback (most recent call last):
  File "/home/xxm/Downloads/cpython-main/test.py", line 9, in <module>
    imp_time = _imp.create_builtin(A)
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: name must be string, not FakeSpec


```

**Comment by xiaxinmeng** [comment] 2022-11-23 04:57
> Per [#98412 (comment)](https://github.com/python/cpython/pull/98412#issuecomment-1287478504), this might not be completely fixed yet.
> 
> @xiaxinmeng, can you verify if the problem you had is fixed on [the main branch](https://github.com/python/cpython/tree/main) (i.e. `3.12a1`)?

Sorry for being late. I think this problem has been fixed.
It does not crash CPython any more, the behavior on the main branch [8f18ac0](https://github.com/python/cpython/commit/8f18ac04d32515eab841172c956a8cb14bcee9c3) is as follows:
```
Traceback (most recent call last):
  File "/home/xxm/Downloads/cpython-main(2)/test.py", line 9, in <module>
    imp_time = _imp.create_builtin(A)
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: name must be string, not FakeSpec
```

**Comment by chgnrdv** [comment] 2023-02-12 13:52
@ericsnowcurrently, sorry for the slow response. Yes, I confirm that refleak issue is fixed by [gh-99578](https://github.com/python/cpython/pull/99642), and therefore we can close this one.

**Closed as completed** 2023-02-12 14:42 UTC
Labels: 3.10, type-crash
