### ISSUE TITLE
can't specify generic types when instantiating frozen dataclass with slots

### ISSUE THREAD

**Issue by daddinuz** [python/cpython#116669] opened 2024-03-12 17:44 UTC
# Bug report

### Bug description:

```python
from dataclasses import dataclass

@dataclass(frozen=True, slots=True)
class Foo[T]:
  pass

foo = Foo() # this line works
foo = Foo[int]() # this one does not
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.12/typing.py", line 1142, in __call__
    result.__orig_class__ = self
    ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 5, in __setattr__
TypeError: super(type, obj): obj must be an instance or subtype of type
```

`Python 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]`

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment] 2024-03-12 17:48
FYI: this doesn't relate to the new (PEP 695) syntax.
Example with the old syntax:

```python
from dataclasses import dataclass
from typing import TypeVar, Generic


T = TypeVar("T")


@dataclass(frozen=True, slots=True)
class Foo(Generic[T]):
  pass

foo = Foo() # this line works
foo = Foo[int]() # this one does not
```
>
```python
Traceback (most recent call last):
  File "/home/eclips4/CLionProjects/cpython/example.py", line 13, in <module>
    foo = Foo[int]() # this one does not
          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/typing.py", line 1277, in __call__
    result.__orig_class__ = self
    ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 5, in __setattr__
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by AlexWaygood** [comment] 2024-03-12 17:51
Happily, this specific exception was fixed just last month, in https://github.com/python/cpython/pull/115213. The fix was backported, so it will be included in the next releases of Python 3.12 and Python 3.11. The `typing` module is in the clear here.

However, it looks like `dataclasses` might also be using `super()` incorrectly there? Not sure.

**Comment by Eclips4** [comment] 2024-03-12 17:51
Oh, this do not reproducible on the current main.

**Comment by JelleZijlstra** [comment] 2024-03-12 17:55
This is a symptom of the general problem where slotted dataclasses work by creating a new class, which breaks `super()`. There are several other similar issues and there's no obvious solution.

cc @ericvsmith for dataclasses.

**Comment by AlexWaygood** [comment] 2024-03-12 17:57
> This is a symptom of the general problem where slotted dataclasses work by creating a new class, which breaks `super()`. There are several other similar issues and there's no obvious solution.
> 
> cc @ericvsmith for dataclasses.

If there are already other similar issues regarding `super()` in dataclasses, then we can probably close this one, as the user-visible bug here has already been fixed by https://github.com/python/cpython/pull/115213

**Comment by AlexWaygood** [comment] 2024-03-12 18:00
Thanks for the report, @daddinuz! Your bug was valid; we'd just already fixed it before you filed the issue ;)

**Closed as completed** 2024-03-12 17:59 UTC
Labels: type-bug, stdlib, 3.11, 3.12, 3.13
