### ISSUE TITLE
Weird behaviour with file named logging.py

### ISSUE THREAD

**Issue by sc-ele** [python/cpython#95810] opened 2022-08-09 06:31 UTC
If I have a file named logging.py in a directory and try to execute python programs in that directory then the logging.py file is being parsed and executed instead of the python program which I am trying to execute.

How to reproduce:
- Create a file named logging.py in a directory
- In logging.py set the contents to "from xxx import yyy" and nothing else
- In the same directory run for example "pip3 list"

Error "ModuleNotFoundError: No module named 'xxx'" is reported and "pip3 list" fails!

I get the same problem for example executing Mercurial hg commands which are implemented in python.

Renaming logging.py to something else cures the problem. Not sure if this is a bug but pretty weird anyway!

**Comment by aroberge** [comment] 2022-08-09 12:39
logging is the name of a Python module which might be used by other programs.
https://docs.python.org/3/library/logging.html

In your case, your own file is imported instead of the desired logging module. As you found out, the solution is not to use the same name as that of a Python module.

**Comment by ronaldoussoren** [comment] 2022-08-09 12:57
@sc-ele : Do you have an environment variable named PYTHONPATH set and containing the current working directory?

By default the current working directory should not be in ``sys.path`` when running a script, unless that script is in the current directory (that is, by default ``sys.path[0]`` is set to the directory containing the script, or the current directory when running interactively).

**Comment by kumaraditya303** [comment] 2022-09-17 12:24
Closing as it is not a bug.

**Closed as not planned by kumaraditya303** 2022-09-17 12:24 UTC
Labels: type-bug
