### ISSUE TITLE
_PyInterpreterState_SetEvalFrameFunc slows down 3.11 by ~15% compared to baseline 3.11

### ISSUE THREAD

**Issue by itamarst** [python/cpython#104305] opened 2023-05-08 19:37 UTC
# Bug report

Let's say I define  passthrough eval function: it just calls `_PyEval_EvalFrameDefault()` with the same arguments it's given. I install it with `_PyInterpreterState_SetEvalFrameFunc`.

Measuring on 3.10, using `pystone.py` as a benchmark of lots of function calls, the overhead is negligible.

Measuring on 3.11, there's high overhead (15% reduction in speed) from doing this. Pretty sure `perf stat` is showing that part of the problem is more branch mispredictions.

## 3.10 vs 3.11: hypothesized reason for slowdown

3.10 version:

```c
static inline PyObject*
_PyEval_EvalFrame(PyThreadState *tstate, PyFrameObject *f, int throwflag)
{
    return tstate->interp->eval_frame(tstate, f, throwflag);
}
```

And `eval_frame` gets set to `_PyEval_EvalFrameDefault` by default.

In contrast, 3.11 uses NULL to mean default, and adds a branch:

```c

static inline PyObject*
_PyEval_EvalFrame(PyThreadState *tstate, struct _PyInterpreterFrame *frame, int throwflag)
{
    if (tstate->interp->eval_frame == NULL) {
        return _PyEval_EvalFrameDefault(tstate, frame, throwflag);
    }
    return tstate->interp->eval_frame(tstate, frame, throwflag);
}
```

Either normal compilation, PGO, or both, are then presumably doing a bunch of optimizations for the NULL path on 3.11, which result in the non-NULL path being slow (or the NULL path being fast, depending what actually happens in compilation).

On 3.10, in contrast, it's the same path.

## Should this be fixed?

If switching back to the 3.10 code structure results in normal Python usage being slower, I can see not wanting to switch back. But if it doesn't impact normal Python code much, this is somewhat frustrating since `_PyInterpreterState_SetEvalFrameFunc` was a helpful mechanism for getting trace-like hooks with much lower performance overhead (I'm using it for a profiler).

## Your environment

- CPython versions tested on: 3.11.3 vs. 3.10.6
- Operating system and architecture: Linux 6, on x86_64 (i7-12700K)

**Comment by carljm** [comment] 2023-05-08 19:48
In 3.11, many Python function calls are "inlined" into a single call to `PyEval_EvalFrameDefault`; i.e. the `CALL` opcode has an optimized path where it doesn't re-enter `PyEval_EvalFrameDefault`, it just updates the Python frame stack state and jumps to the top of the interpreter loop.

In order to maintain PEP 523 semantics, this optimization is necessarily disabled when there is a PEP 523 frame evaluation function set.

I don't know how much of your observed regression is due to the branch mispredictions you mentioned, and how much is due to disabling the inlining optimization. But the inlining optimization is definitely a case where the gap could only be closed by making the common case slower.

I suspect there might also be overhead from every frame entry following a function pointer indirection, too, in which case the branching might fall into the same category.

In general I think there is a commitment to keep 523 working (unless there is a PEP to remove it, anyway), but not a commitment to keep its performance on par with default; that would place too many constraints on optimizing the common case.

For 3.12+ there is another option for low-overhead profiling: PEP 669.

**Comment by carljm** [comment] 2023-05-08 20:21
Not sure which particular aspect of "C API" is important for your use case. PEP 669 is usable from C, but it works via Python objects; there's no "unboxed" API. You have to `PyImport_ImportModule("sys")` and then a couple `PyObject_GetAttr` to get `sys.monitoring` and some method off it, which you can then call with `PyObject_Call` or `PyObject_Vectorcall`.

**Comment by carljm** [comment] 2023-05-08 20:25
Labeling this as just a performance issue, and not a bug: I don't think it is a goal to maintain performance parity of PEP 523 with the no-523 case, and so I don't think this is a bug.

Will leave it open for now, since if you (or anyone else) does further exploration and are able to propose a specific change that shows performance improvement under PEP 523, without showing any regression in the common case (or limiting planned optimizations), that would be fine as an improvement.

**Comment by carljm** [comment] 2023-05-08 20:28
Also, I think the title of the issue should be changed, unless you have benchmarks showing that 3.11-with-523 is slower in absolute terms on the same workload than 3.10-with-523. Common-case 3.11 is quite a bit faster than 3.10 (typically much more than 15%), so given your relative benchmark numbers I suspect there is not an absolute regression here (likely some improvement.)

**Comment by itamarst** [comment] 2023-05-08 21:02
> Not sure which particular aspect of "C API" is important for your use case. PEP 669 is usable from C, but it works via Python objects; there's no "unboxed" API. You have to `PyImport_ImportModule("sys")` and then a couple `PyObject_GetAttr` to get `sys.monitoring` and some method off it, which you can then call with `PyObject_Call` or `PyObject_Vectorcall`.

I want the fastest possible performance, which is why I was using `_PyInterpreterState_SetEvalFrameFunc` for example. I want to have profiling running in production with minimal overhead (<5%, ideally <2%). Having the callbacks be Python functions that get Python objects will likely make that not viable performance-wise and I'll need a completely different approach.

**Comment by gaogaotiantian** [comment] 2023-05-09 02:42
Could you share your benchmark code or explain how you did the benchmark to get the 15% slower data? My guess was it was "relative" because the actual code(function calls) on 3.11 is faster. So the overhead ratio (time after instrumentation / time original) is larger. That happened on all instrumental profilers, including cprofile. The actual absolute instumentation cost is not change significantly.

The overhead for the profiler is significantly affected by the actual code being profiled. I don't think that you can achieve 5% overhead on ANY code(recursive factorial for example), I would be surprised if you can actually do that. For production code, instumental(determinisitic) profiler might not be the way to go.

Anyway, that's a bit digressed, I think the first thing to make this issue "valid" is to make sure if the overhead is increased in an absolute way, otherwise this is not an issue.

**Comment by carljm** [comment] 2023-05-09 13:32
@gaogaotiantian It's already clear from the OP that the measurement here is relative (3.11 with 523 vs 3.11 without).

I agree that we should probably just close this.

Also agree that a sampling profiler is the way to go for low-overhead profiling in production.

**Closed as not planned by carljm** 2023-05-09 13:32 UTC
Labels: performance

**Comment by itamarst** [comment] 2023-05-09 14:18
> For production code, instumental(determinisitic) profiler might not be the way to go.

The profiler does use sampling, but it injects itself into the eval loop to (in a very highly optimized way, with much lower overhead than full profiling) build an ancillary datastructure that includes each thread's stack, in a way that allows sampling to happen without the hoops py-spy/austin have to jump through. But as of 3.11 this technique appears no longer viable so I guess I will be switching to something more similar to what they use.

**Comment by markshannon** [comment] 2023-05-12 10:14
What does your eval function do? If it sets some per-frame data, then you can do the same relatively cheaply with a PEP 699 `PY_START` event callback. 

The callback mechanism uses the vectorcall protocol, so while it is designed to support Python callables, there is no reason why you can't implement the callback in C or rust.

**Comment by itamarst** [comment] 2023-05-12 12:59
I guess I'll at least measure if PEP 699 works, yeah.
