### ISSUE TITLE
datetime.strptime becomes None after first run in WASM environment

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#101026] opened 2023-01-14 00:14 UTC
# Bug report

The following code runs correctly the first time but then complains that `datetime.strptime` is of type `NoneType` the second time the code is run within the same browser session.

```python
"""Demonstrates WASM issue with datetime.strptime."""
from datetime import datetime

print(datetime.strptime("2023-01-13", "%Y-%m-%d"))
print(datetime.strptime("2023-01-13", "%Y-%m-%d"))
```

Live example here: https://pym.dev/p/2g6wn/

Note that running `datetime.strptime` twice doesn't cause an issue. The issue seems to be due to exiting Python and then re-entering it. For example in an interactive session, one would need to call `exit()` and then start the interactive session again in the same browser window ([example here](https://www.pythonmorsels.com/r/2zphj/)).

```pycon
>>> from datetime import datetime
>>> datetime.strptime("2023", "%Y")
datetime.datetime(2023, 1, 1, 0, 0)
>>> exit()  # The REPL is automatically re-entered after this
>>> from datetime import datetime
>>> datetime.strptime("2023", "%Y")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not callable
```

# Your environment

CPython 3.11.0 compiled to Emscripten for the browser.

**Comment by brettcannon** [comment] 2023-01-20 20:09
How are you re-initializing the Python runtime between sessions?

**Comment by treyhunner** [comment] 2023-01-26 23:38
To re-initialize I'm posting a `run` message to the web worker, which calls `callMain(event.data.args)` again.

**Comment by abalkin** [comment] 2023-02-09 09:13
This looks like another manifestation of the issue reported at GH-71587.

**Comment by brettcannon** [comment] 2023-02-10 00:56
I think @abalkin is right as to the cause, so I'm closing this as a duplicate.

**Closed as not planned by brettcannon** 2023-02-10 00:56 UTC
Labels: type-bug, OS-wasi
