### ISSUE TITLE
`test_exceptions.ExceptionTests.testMemoryErrorBigSource` fails on certain platforms

### ISSUE THREAD

**Issue by FFY00** [python/cpython#110800] opened 2023-10-13 05:42 UTC
# Bug report

### Bug description:

Example: https://buildbot.python.org/all/#/builders/1056/builds/3329/steps/10/logs/stdio

```
======================================================================
FAIL: testMemoryErrorBigSource (test.test_exceptions.ExceptionTests.testMemoryErrorBigSource)
----------------------------------------------------------------------
OverflowError: cannot fit 'int' into an index-sized integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-dl/build/Lib/test/test_exceptions.py", line 322, in testMemoryErrorBigSource
    with self.assertRaisesRegex(OverflowError, "column offset overflow"):
AssertionError: "column offset overflow" does not match "cannot fit 'int' into an index-sized integer"
----------------------------------------------------------------------
Ran 95 tests in 1.969s
```

This seems to be due to the `PySequence_Repeat` taking a `Py_ssize_t`, which is platform dependent.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-110801

**Comment by AlexWaygood** [comment] 2023-10-13 06:34
Duplicate of #110767

**Closed as not planned by AlexWaygood** 2023-10-13 06:34 UTC
Labels: type-bug, tests
