### ISSUE TITLE
A staticmethod object can be __get__, to behave in a wrong manner!

### ISSUE THREAD

**Issue by takuom** [python/cpython#111686] opened 2023-11-03 09:21 UTC
# Bug report

### Bug description:

I've reported a [related issue](https://github.com/python/cpython/issues/111595), but this one seems more urgent.

Firstly, the following code leads to a problem.
```python
def get(instance, owner=None):
    return owner if instance is None\
           else type(instance) # say


class MyDescriptor:
    def __get__(self, instance, owner=None):
        return get(instance, owner)


class MyDescriptor_static:
    __get__ = staticmethod(get)

class O:
    a = MyDescriptor()
    s = MyDescriptor_static()

o = O()
a = o.a

assert a is vars(O)["a"].__get__(o, O) # No problem.
assert a is vars(O)["s"].__get__(o, O) # No problem.
o.s # TypeError: get() takes from 1 to 2
    # positional arguments but 3 were given
```
You might already decide that this is `staticmethod`'s fault, but let me not yet but try to fix it.  Thus,
```python
# A "repaired" version of `MyDescriptor_static`
class MyDescriptor_static1:
    @staticmethod
    def __get__(self, instance, owner=None):
        return get(instance, owner)

# Override "s" of `O`.
class O1(O):
    s = MyDescriptor_static1()

o1 = O1()

assert o1.s is o1.a # Working now.  However, ...

assert o1.s == vars(O1)["s"].__get__(o1, O1)
# AssertionError
```
So it must really be `staticmethod` that's responsible for the problems.  For instance,
```python
class x:
    def __get__(self, *args):
        return super().__get__(*args)


class MyDescriptor1(x, MyDescriptor):
    pass

class MyDescriptor2(x, MyDescriptor_static1):
    pass

class O2(O1):
    a2 = MyDescriptor1()
    s2 = MyDescriptor2()
    
o2 = O2()

# Reference for a normal behaviour
assert o2.a2 is o2.a # Expected result

# Failure
assert o2.s2 == o2.s # AssertionError
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by rhettinger** [comment] 2023-11-03 19:47
I don't think this is a bug — there is no promise that descriptors will chain together.  We did try that with `classmethod` and came to regret it.  For the most part, the current API seems to fulfill most use cases and it allows the implementation to be clean and fast.

Out of curiousity, what was the point of wrapping `__get__` with `staticmethod`?  Was it just something you were experimenting with or is there some practical use case that can't be addressed with the current tooling?

**Comment by takuom** [comment] 2023-11-04 08:47
Thanks for checking this.  I think this one is more a problem of `staticmethod`than of the API.

I don't know why but a `staticmethod` object is callable at least in Python 3.11.  (I always thought it wasn't, and I think it wasn't till some time.)  When an unbound method (which may be a `staticmethod` object) is ever callable, apparently it should be only so in a way equivalent to
```python
def __call__(self, instance, /, *args, **kwargs):
    return self.__get__(
        instance, type(instance)
    )(*args, **kwargs)
```
In the case where `self` is `staticmethod(g)`, this means that `self(instance, *args, **kwargs)` should only possibly return `g(*args, **kwargs)` but never `g(instance, *args, **kwargs)` as it currently does.  (I think it would be just simpler if a `staticmethod` object were never callable.)

**Comment by takuom** [comment] 2023-11-04 08:48
By the way, I just noticed that `callable(staticmethod(object()))` was `True`, which might be OK, but just felt funny to me since a `staticmethod` object doesn't have to be a method (despite the name...).

**Comment by takuom** [comment] 2023-11-04 08:53
> Out of curiousity, what was the point of wrapping `__get__` with `staticmethod`? Was it just something you were experimenting with or is there some practical use case that can't be addressed with the current tooling?

I reported it since I noticed a behaviour which might be a potential problem, but no, it's not from my own use case.  (I might not report a problem I get with my own code since it would be too late to report in such a case.  I would find a way out by myself no matter what.)

I wasn't trying to chain descriptors either.  I thought `classmethod` didn't work with `property.__set__`?

**Comment by rhettinger** [comment] 2023-11-05 19:46
> I reported it since I noticed a behaviour which might be a potential problem, but no, it's not from my own use case. 

Okay, thanks for the dialog.  Given that you don't have an actual problem, that `staticmethod` is working as intended (including being callable), and that there doesn't seem to be any valid use case that cannot be satisfied, I'll close this and the other issue.

I get that it "feels funny to you" but the core design is somewhat set in stone (it is 20 years old) and seems to have worked out well in practice.

**Closed as not planned** 2023-11-05 19:54 UTC

**Comment by takuom** [comment] 2023-11-06 13:33
Thanks @rhettinger for further clarification.

> Given that you don't have an actual problem,

Right.  Unfortunately, when I already have an actual problem, I wouldn't be able to wait for a fix of the bug.  An improvisation or even another language if necessary would be better.

It appears that `staticmethod` objects have been callable since Python 3.10, for like 2 years now?  I might say that 2 years is much shorter than 18 years (20 = 18 + 2).  It may have been still fine if they were callable in ***the other*** way at least...

But people may wait to report an issue till they get an actual problem by themselves.
