### ISSUE TITLE
`list(FunctionType(a.gi_code, {})(0))` crashes Python

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#90847] opened 2022-02-09 11:31 UTC
BPO | [46689](https://bugs.python.org/issue46689)
--- | :---
Nosy | @tirkarthi, @sobolevn

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-09.11:31:51.245>
labels = ['interpreter-core', '3.10', '3.9', 'type-crash', '3.11']
title = '`list(FunctionType(a.gi_code, {})(0))` crashes Python'
updated_at = <Date 2022-02-09.17:16:46.319>
user = 'https://github.com/sobolevn'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-09.17:16:46.319>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-02-09.11:31:51.245>
creator = 'sobolevn'
dependencies = []
files = []
hgrepos = []
issue_num = 46689
keywords = []
message_count = 2.0
messages = ['412897', '412926']
nosy_count = 2.0
nosy_names = ['xtreak', 'sobolevn']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue46689'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by kumaraditya303** [comment] 2022-05-11 17:27
Duplicate of https://github.com/python/cpython/issues/81137

**Closed as completed by kumaraditya303** 2022-05-11 17:27 UTC
Labels: interpreter-core, 3.11, 3.10, 3.9 (EOL), type-crash
