### ISSUE TITLE
3.13.0+JIT+NoGIL build failure on Linux.

### ISSUE THREAD

**Issue by timkofu** [python/cpython#125246] opened 2024-10-10 10:14 UTC
# Bug report

### Bug description:

Building Python `3.13.0` with the options `--with-lto --enable-optimizations --enable-experimental-jit --disable-gil` fails with the error:
```text
Last 10 log lines:
0:03:24 load avg: 1.07 [42/44] test_time
test test_time failed
0:03:29 load avg: 1.07 [43/44] test_xml_etree -- test_time failed (1 error, 4 failures)
0:03:42 load avg: 1.06 [44/44] test_xml_etree_c

Total duration: 3 min 58 sec
Total tests: run=9,361 failures=172 skipped=202
Total test files: run=44/44 failed=12
Result: FAILURE
make: *** [Makefile:906: profile-run-stamp] Error 2
```
Attached is the full build-log.
[python-build.20241010124045.158033.log](https://github.com/user-attachments/files/17326404/python-build.20241010124045.158033.log)

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by ChrisLovering** [comment] 2024-10-12 09:31
This also fails when building 3.13.0 with the options `--disable-test-modules --enable-optimizations --with-lto --disable-gil`. Building free threaded seems to work if you use any combination of the first 3, but all 3 together causes to to fail tests.

```dockerfile
FROM buildpack-deps:bookworm
RUN apt-get -y update \
    && apt-get install -y --no-install-recommends libxmlsec1-dev tk-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone -b v3.13.0 --depth 1 https://github.com/python/cpython.git /opt/cpython
WORKDIR /opt/cpython

RUN ./configure --disable-test-modules --enable-optimizations --with-lto --disable-gil
RUN make -s -j
```
<details>
  <summary>Click for full build output</summary>

```
 > [6/6] RUN make -s -j:
0.351 Running code to generate profile data (this can take a while):
0.441 find: 'build': No such file or directory
0.442 find: 'build': No such file or directory
0.443 find: 'build': No such file or directory
0.449 find: 'build': No such file or directory
0.494 Building with support for profile generation:
8.231 In file included from ./Include/cpython/pyatomic.h:532,
8.231                  from ./Include/pyatomic.h:9,
8.231                  from ./Include/Python.h:70,
8.231                  from ./Modules/_struct.c:10:
8.231 In function '_Py_atomic_load_uint32_relaxed',
8.231     inlined from 'Py_DECREF' at ./Include/object.h:904:22,
8.231     inlined from 'cache_struct_converter.constprop.0' at ./Modules/_struct.c:2271:9:
8.240 ./Include/cpython/pyatomic_gcc.h:339:10: warning: '__atomic_load_4' writing 4 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
8.240   339 | { return __atomic_load_n(obj, __ATOMIC_RELAXED); }
8.240       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10.43 In function '_Py_atomic_load_uint32_relaxed',
10.43     inlined from 'Py_DECREF' at ./Include/object.h:904:22,
10.43     inlined from 'cache_struct_converter.constprop' at ./Modules/_struct.c:2271:9:
10.43 ./Include/cpython/pyatomic_gcc.h:339:10: warning: '__atomic_load_4' writing 4 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
10.43   339 | { return __atomic_load_n(obj, __ATOMIC_RELAXED); }
10.43       |          ^
233.2 The following modules are *disabled* in configure script:
233.2 _ctypes_test              _testbuffer               _testcapi
233.2 _testclinic               _testclinic_limited       _testexternalinspection
233.2 _testimportmultiple       _testinternalcapi         _testlimitedcapi       
233.2 _testmultiphase           _testsinglephase          _xxtestfuzz
233.2 xxlimited                 xxlimited_35              xxsubtype
233.2 
233.2 Checked 112 modules (33 built-in, 63 shared, 1 n/a on linux-x86_64, 15 disabled, 0 missing, 0 failed on import)
234.1 Using random seed: 3735351227
234.1 0:00:00 load avg: 2.26 Run 44 tests sequentially in a single process
234.1 0:00:00 load avg: 2.26 [ 1/44] test_array
235.1 0:00:01 load avg: 2.26 [ 2/44] test_base64
235.4 0:00:01 load avg: 2.26 [ 3/44] test_binascii
235.5 0:00:01 load avg: 2.26 [ 4/44] test_binop
235.6 0:00:01 load avg: 2.26 [ 5/44] test_bisect
235.6 0:00:01 load avg: 2.26 [ 6/44] test_bytes
235.7 0:00:01 load avg: 2.26 [ 7/44] test_bz2 -- test_bytes skipped
236.6 0:00:02 load avg: 2.26 [ 8/44] test_cmath
236.7 0:00:02 load avg: 2.26 [ 9/44] test_codecs
237.9 0:00:03 load avg: 2.16 [10/44] test_collections
238.6 0:00:04 load avg: 2.16 [11/44] test_complex
238.9 0:00:04 load avg: 2.16 [12/44] test_dataclasses
239.3 0:00:05 load avg: 2.16 [13/44] test_datetime
244.1 0:00:10 load avg: 2.06 [14/44] test_decimal
247.6 0:00:13 load avg: 1.98 [15/44] test_difflib
248.7 0:00:14 load avg: 1.98 [16/44] test_embed
251.2 0:00:17 load avg: 1.98 [17/44] test_float
251.5 0:00:17 load avg: 1.98 [18/44] test_fstring
252.4 0:00:18 load avg: 1.90 [19/44] test_functools
253.2 test test_functools failed
253.2 0:00:19 load avg: 1.90 [20/44] test_generators -- test_functools failed (2 failures)
253.8 0:00:19 load avg: 1.90 [21/44] test_hashlib
254.3 0:00:20 load avg: 1.90 [22/44] test_heapq
255.1 0:00:21 load avg: 1.90 [23/44] test_int
255.7 0:00:21 load avg: 1.90 [24/44] test_itertools
260.6 0:00:26 load avg: 1.83 [25/44] test_json
264.3 0:00:30 load avg: 1.76 [26/44] test_long
266.8 0:00:32 load avg: 1.76 [27/44] test_lzma
267.2 0:00:33 load avg: 1.70 [28/44] test_math
270.2 0:00:36 load avg: 1.70 [29/44] test_memoryview
271.6 0:00:37 load avg: 1.70 [30/44] test_operator
271.9 0:00:37 load avg: 1.70 [31/44] test_ordered_dict
274.5 test test_ordered_dict failed
274.5 0:00:40 load avg: 1.64 [32/44] test_patma -- test_ordered_dict failed (4 failures)
274.9 0:00:40 load avg: 1.64 [33/44] test_pickle
281.1 0:00:46 load avg: 1.59 [34/44] test_pprint
281.5 0:00:47 load avg: 1.59 [35/44] test_re
282.8 0:00:48 load avg: 1.54 [36/44] test_set
291.5 0:00:57 load avg: 1.50 [37/44] test_sqlite3
294.7 0:01:00 load avg: 1.46 [38/44] test_statistics
304.0 0:01:09 load avg: 1.39 [39/44] test_str
308.2 0:01:14 load avg: 1.36 [40/44] test_struct
310.2 test test_struct failed
310.2 0:01:16 load avg: 1.36 [41/44] test_tabnanny -- test_struct failed (1 failure)
311.9 0:01:17 load avg: 1.36 [42/44] test_time
315.3 0:01:21 load avg: 1.33 [43/44] test_xml_etree
322.5 0:01:28 load avg: 1.28 [44/44] test_xml_etree_c
331.9
331.9 Total duration: 1 min 37 sec
331.9 Total tests: run=9,067 failures=7 skipped=343
331.9 Total test files: run=44/44 failed=3 skipped=1
331.9 Result: FAILURE
332.6 make: *** [Makefile:904: profile-run-stamp] Error 2
```

</details>

**Comment by timkofu** [comment] 2024-10-25 09:30
Compiling with only `--enable-experimental-jit --disable-gil` works.

**Comment by ChrisLovering** [comment] 2024-10-25 09:34
Yeah, that's correct. Building free threaded seems to work if you use any combination of the first 3, but all 3 together causes tests to fail.

**Comment by vstinner** [comment] 2024-11-27 12:14
> test_time failed

I cannot reproduce the issue on the main branch. It seems like the issue has been fixed in the meanwhile. I close the issue.

I got:

```
Total duration: 1 min 25 sec
Total tests: run=9,206 skipped=346
Total test files: run=44/44 skipped=1
Result: SUCCESS
```

Reopen the issue if you can still reproduce it.

**Closed as completed by vstinner** 2024-11-27 12:14 UTC
Labels: type-bug, build, topic-free-threading, topic-JIT
