### ISSUE TITLE
Allow constructing a UUID from a UUID, similar to str("x") and int(1): uuid.UUID(a_uuid)

### ISSUE THREAD

**Issue by jankatins** [python/cpython#113266] opened 2023-12-19 01:08 UTC
# Feature or enhancement

### Proposal:

A lot of code of mine uses the pattern `string_value = str(string_ish)` or `int_value = int(int_ish)`. I was surprised that this doesn't work with UUIDs.

In a more generic way: 

```python
from typing import Any, TypeVar
ExpectedType = TypeVar("ExpectedType")
def coerce(input: Any, expected_type: type[ExpectedType]) -> ExpectedType:
    return expected_type(input)
coerce(1, str) # "1"
coerce(1, int) # 1
coerce("x", str) # "x"
```

But this doesn't work with UUIDs:

```python
>>> import uuid
>>> coerce(uuid.uuid4(), uuid.UUID)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in coerce
  File "/Users/jankatins/.local/share/rtx/installs/python/3.12.1/lib/python3.12/uuid.py", line 175, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
          ^^^^^^^^^^^
AttributeError: 'UUID' object has no attribute 'replace'
```

If there is interest to make this work, I can prepare a PR:

```diff
class UUID:
...
    def __init__(self, hex=None, bytes=None, bytes_le=None, fields=None,
                       int=None, version=None,
                       *, is_safe=SafeUUID.unknown):
...
         if [hex, bytes, bytes_le, fields, int].count(None) != 4:
            raise TypeError('one of the hex, bytes, bytes_le, fields, '
                            'or int arguments must be given')
+        if isinstance(hex, UUID):
+            # Allow creating uuids as copy of a uuid, similar to str("x") / int(1) works.
+            int = hex.int
-        if hex is not None:
+        elif hex is not None:
            hex = hex.replace('urn:', '').replace('uuid:', '')
            hex = hex.strip('{}').replace('-', '')
...
```

One question would be if this should also copy `is_safe` from the input UUID?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by sobolevn** [comment] 2023-12-19 19:51
Most object cannot create an instance from themselfs. This is not a common practice.
`str` and `int` can create such instances, because the input matches the expected protocol `__str__` and `__int__`.

We need a stronger motivation to do that.

**Comment by serhiy-storchaka** [comment] 2023-12-20 09:17
This is a duplicate of #76293 and #88872.

**Closed as completed by serhiy-storchaka** 2023-12-20 09:17 UTC
Labels: type-feature, stdlib, pending

**Comment by jankatins** [comment] 2023-12-20 13:13
First of all: sorry that I didn't search the closed issues for this.

I tried to figure out some good arguments for still having this, but also came to the conclusion that it gets murky, soon, when thinking this trough. I leave my though process here, maybe it helps with the next users having this problem:

My main arguments for having it are:
- While it is true that most objects do not support copy construction, most scalars (`int/float/str/...`) support it. Given the (now three) bug reports, people seem to have the mental model that there is no difference between int/str/float/.... and uuid and therefore `uuidUUID(uuid.uuid4())` should also work. This mental model is also supported by databases like postgresql treating UUIDs as a "regular" scalar like strings/int/bool. 
- it would make for a nicely consistent rule: if you want to be a scalar, define a protocol and also implement that protocol so that `Scalar(a_scalar)` works. 

On the other hand, the same argument could then be made about any other scalars. So if `UUID()` should get a protocol, `datetime()/date()` should get one, too. Or enums... And while i can see it happening for `datetime/date`, going as far as enums seems murky at best e.g. what would one use as a constructor of an enum member?

So when I anyway need some different code to support enums in the generic `coerce(input, type[ExpectedType]) -> ExpecteType` case, I can also make it generic enough to also support UUID. And live with the additional `str()` in `UUID(str(uuid_ish))` when validating inputs.

**Comment by tlandschoff-scale** [comment] 2024-07-09 14:57
I would be in favor of allowing `UUID(existing_uuid)`, or any other API to convert a str or UUID into a UUID instance.

In our code base, we unfortunately have a lot of legacy code that for various reasons (like reading from JSON or XML, and performance issues with hashing UUIDs) passes UUIDs around as str instances.

Due to this, there is some code to sanitize the type to UUID. The usual code to do this is something like

```python
self._field = parameter if isinstance(parameter, UUID) else UUID(parameter)
```

It would IMHO be much better to have a solution to that in the stdlib to make this

```python
self._field = UUID(parameter)
```

or maybe something like

```python
self._field = UUID.from_scalar(parameter)
```

As one argument against this was that this is not the usual way python does this, look at this:

```python
>>> t = (42, "test", None)
>>> tuple(t) is t
True
>>> list([1, 2, 3, ...])
[1, 2, 3, Ellipsis]
>>> dict({"foo": 1, "bar": 2})
{'foo': 1, 'bar': 2}
>>> set({"a", "b", "c"})
{'a', 'c', 'b'}
>>> str("already mentioned")
'already mentioned'
>>> int(42)
42
>>> s = frozenset("abc")
>>> frozenset(s) is s
True
>>> float(42.0)
42.0
```

I actually anticipated that `UUID(x)` would behave that way and got bitten by this like 10 years ago, and still see developers run into this.
