### ISSUE TITLE
os.sched_yield() + range() unexpected influence

### ISSUE THREAD

**Issue by socketpair** [python/cpython#121512] opened 2024-07-08 20:31 UTC
# Bug report

### Bug description:

The counters printed are expected to be almost the same. They are. But some arguments for `range()`, `sched_yield()` significantly change the picture. Note, `sched_yield()` slows down ANOTHER thread, and unexpectedly speeds up the current one.

```
python3 --version
Python 3.12.3
Linux Fedora 39, kernel 6.9.4-100.fc39.x86_64
```

```python
from os import sched_yield
from queue import SimpleQueue
from threading import Thread
from time import monotonic

period = 2


def _thread(queue1: SimpleQueue) -> None:
    consumed = 0
    start = monotonic()
    while queue1.get():
        consumed += 1
    end = monotonic()
    print(f'Consumed: {consumed / 1000 / (end - start):12.2f} Kitems/sec.')


def main():
    for arg in (1, 10, 100, 1000, 10_000, 100_000, 1000_000, 10_000_000):
        print(f'Testing for {arg=}')
        queue: SimpleQueue[bool] = SimpleQueue()
        thread = Thread(target=_thread, args=(queue,), daemon=True)
        thread.start()
        cnt = 0
        deadline = monotonic() + period
        while monotonic() < deadline:
            for i in range(arg):
                cnt += 1
                if queue.qsize() <= 1048576:
                    queue.put(True)
            sched_yield()  # with commented out - no bugs for any `range()`
            # time.sleep(0) # no bugs for any `range()`
        stop = monotonic()
        queue.put(False)
        thread.join()
        print(f'Produced: {cnt / 1000 / (stop - (deadline - period)):12.2f} Kitems/sec.')


main()
```

```
Testing for arg=1
Consumed:       644.82 Kitems/sec.
Produced:       644.83 Kitems/sec.
Testing for arg=10
Consumed:      3981.64 Kitems/sec.
Produced:      3981.68 Kitems/sec.
Testing for arg=100
Consumed:      3809.66 Kitems/sec.  <----- BUG
Produced:     15519.08 Kitems/sec.
Testing for arg=1000
Consumed:      1192.78 Kitems/sec.  <----- BUG
Produced:     19605.59 Kitems/sec.
Testing for arg=10000
Consumed:       585.87 Kitems/sec.  <----- BUG
Produced:     19829.86 Kitems/sec.
Testing for arg=100000
Consumed:     10839.18 Kitems/sec.
Produced:     10883.60 Kitems/sec.
Testing for arg=1000000
Consumed:     11005.64 Kitems/sec.
Produced:     11011.80 Kitems/sec.
Testing for arg=10000000
Consumed:     10800.30 Kitems/sec.
Produced:     10805.39 Kitems/sec.
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by socketpair** [comment] 2024-07-08 20:41
P.S.

```python
            for i in range(arg):
                cnt += 1
                queue.put(True)
```

gives the same, but in range `1000...100_000`

**Comment by socketpair** [comment] 2024-07-08 20:56
#96078 ?

**Comment by Zheaoli** [comment] 2024-07-09 06:20
@Eclips4 would you mind to assign this issue for me？

**Comment by Zheaoli** [comment] 2024-07-28 10:27
Problem solved.. I guess you use Intel CPU( >= 10th?)

sched_yield may move the process to a different CPU core. so we got different speed on the power core and efficiency core 

you can bind the core

```python
from os import sched_yield
from queue import SimpleQueue
from threading import Thread
from time import monotonic

period = 2

import os


pid = os.getpid()


cpu_set = {1}


mask = 0
for cpu in cpu_set:
    mask |= (1 << cpu)


os.sched_setaffinity(pid, cpu_set)


affinity = os.sched_getaffinity(pid)
print(f"Current CPU affinity: {affinity}")

def _thread(queue1: SimpleQueue) -> None:
    consumed = 0
    start = monotonic()
    while queue1.get():
        consumed += 1
    end = monotonic()
    print(f'Consumed: {consumed / 1000 / (end - start):12.2f} Kitems/sec.')


def main():
    for arg in (1, 10, 100, 1000, 10_000, 100_000, 1000_000, 10_000_000):
        print(f'Testing for {arg=}')
        queue: SimpleQueue[bool] = SimpleQueue()
        thread = Thread(target=_thread, args=(queue,), daemon=True)
        thread.start()
        cnt = 0
        deadline = monotonic() + period
        while monotonic() < deadline:
            for i in range(arg):
                cnt += 1
                if queue.qsize() <= 1048576:
                    queue.put(True)
            sched_yield()  # with commented out - no bugs for any `range()`
            # time.sleep(0) # no bugs for any `range()`
        stop = monotonic()
        queue.put(False)
        thread.join()
        print(f'Produced: {cnt / 1000 / (stop - (deadline - period)):12.2f} Kitems/sec.')


main()

**Comment by socketpair** [comment] 2024-07-28 11:42
Yes, `12th Gen Intel(R) Core(TM) i7-1260P`

**Comment by Zheaoli** [comment] 2024-07-28 11:49
> Yes, `12th Gen Intel(R) Core(TM) i7-1260P`

You can try `sched_setaffinity` to find out the problem has been solved

**Comment by CharlesChen0823** [comment] 2024-07-28 13:22
I using AMD 7950X, using first test case, the result is same as origin issue.
```
Testing for arg=1
Consumed:       366.76 Kitems/sec.
Produced:       366.77 Kitems/sec.
Testing for arg=10
Consumed:      1285.96 Kitems/sec.
Produced:      1286.00 Kitems/sec.
Testing for arg=100
Consumed:      3480.48 Kitems/sec.
Produced:      3480.84 Kitems/sec.
Testing for arg=1000
Consumed:      2465.20 Kitems/sec.
Produced:      9880.61 Kitems/sec.
Testing for arg=10000
Consumed:       721.14 Kitems/sec.
Produced:     13789.68 Kitems/sec.
Testing for arg=100000
Consumed:      6267.30 Kitems/sec.
Produced:      6282.66 Kitems/sec.
Testing for arg=1000000
Consumed:      6302.81 Kitems/sec.
Produced:      6303.78 Kitems/sec.
Testing for arg=10000000
Consumed:      6308.13 Kitems/sec.
Produced:      6313.53 Kitems/sec.
```

using `sched_setaffinity` the result is
```
Current CPU affinity: {1}
Testing for arg=1
Consumed:       196.37 Kitems/sec.
Produced:       196.38 Kitems/sec.
Testing for arg=10
Consumed:      1260.84 Kitems/sec.
Produced:      1260.85 Kitems/sec.
Testing for arg=100
Consumed:      4258.80 Kitems/sec.
Produced:      4258.86 Kitems/sec.
Testing for arg=1000
Consumed:      6396.30 Kitems/sec.
Produced:      6396.40 Kitems/sec.
Testing for arg=10000
Consumed:      6737.53 Kitems/sec.
Produced:      6737.63 Kitems/sec.
Testing for arg=100000
Consumed:      6772.95 Kitems/sec.
Produced:      6773.05 Kitems/sec.
Testing for arg=1000000
Consumed:      6747.36 Kitems/sec.
Produced:      6747.45 Kitems/sec.
Testing for arg=10000000
Consumed:      6703.82 Kitems/sec.
Produced:      6703.88 Kitems/sec.
```
If I remember correctly, AMD cpu doesn't have  power core and efficiency core?

**Comment by Zheaoli** [comment] 2024-07-28 14:59
> If I remember correctly, AMD cpu doesn't have power core and efficiency core?

Yes you are right

let's find more detail about this

**Comment by Zheaoli** [comment] 2024-07-28 15:14
Interesting, I write a C code

For no cpu binding version

```c
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <stdbool.h>
#include <sys/time.h>
#include <sched.h>
#include <errno.h>

#define QUEUE_SIZE 1048576
#define PERIOD 2
#define WAKEUP_INTERVAL 100

typedef struct {
    bool buffer[QUEUE_SIZE];
    int head;
    int tail;
    pthread_mutex_t lock;
} SimpleQueue;

void init_queue(SimpleQueue *queue) {
    queue->head = 0;
    queue->tail = 0;
    pthread_mutex_init(&queue->lock, NULL);
    for (int i = 0; i < QUEUE_SIZE; i++) {
        queue->buffer[i] = false;
    }
}

bool enqueue(SimpleQueue *queue, bool value) {
    pthread_mutex_lock(&queue->lock);
    int next_tail = (queue->tail + 1) % QUEUE_SIZE;

    if (next_tail == queue->head) {
        // Queue is full
        pthread_mutex_unlock(&queue->lock);
        return false;
    }

    queue->buffer[queue->tail] = value;
    queue->tail = next_tail;
    pthread_mutex_unlock(&queue->lock);
    return true;
}

bool dequeue(SimpleQueue *queue, bool *value) {
    pthread_mutex_lock(&queue->lock);

    if (queue->head == queue->tail) {
        // Queue is empty
        pthread_mutex_unlock(&queue->lock);
        return false;
    }

    *value = queue->buffer[queue->head];
    queue->head = (queue->head + 1) % QUEUE_SIZE;
    pthread_mutex_unlock(&queue->lock);
    return true;
}

double monotonic_time() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec / 1000000000.0;
}

void *thread_func(void *arg) {
    SimpleQueue *queue = (SimpleQueue *)arg;
    int consumed = 0;
    double start = monotonic_time();

    bool value;
    while (true) {
        if (dequeue(queue, &value) && value) {
            consumed++;
        } else {
            break; // exit loop when dequeue returns false or value is false
        }
    }

    double end = monotonic_time();
    printf("Consumed: %12.2f Kitems/sec.\n", consumed / 1000.0 / (end - start));

    return NULL;
}

int main() {
    int args[] = {1, 10, 100, 1000, 10000, 100000, 1000000, 10000000};

    for (int i = 0; i < sizeof(args) / sizeof(args[0]); i++) {
        int arg = args[i];
        printf("Testing for arg=%d\n", arg);

        SimpleQueue queue;
        init_queue(&queue);

        pthread_t thread;
        pthread_create(&thread, NULL, thread_func, &queue);

        int cnt = 0;
        double deadline = monotonic_time() + PERIOD;

        while (monotonic_time() < deadline) {
            for (int j = 0; j < arg; j++) {
                cnt++;
                if (enqueue(&queue, true)) {
                    if (cnt % WAKEUP_INTERVAL == 0) {
                        sched_yield(); 
                    }
                }
            }
        }

        double stop = monotonic_time();
        enqueue(&queue, false);
        pthread_join(thread, NULL);

        printf("Produced: %12.2f Kitems/sec.\n", cnt / 1000.0 / (stop - (deadline - PERIOD)));
    }

    return 0;
}
```

The result here

```text
╰─ ./demo1-binary 
Testing for arg=1
Consumed:     12440.90 Kitems/sec.
Produced:     41095.88 Kitems/sec.
Testing for arg=10
Consumed:     10455.09 Kitems/sec.
Produced:     86675.52 Kitems/sec.
Testing for arg=100
Consumed:     10505.89 Kitems/sec.
Produced:     97815.24 Kitems/sec.
Testing for arg=1000
Consumed:     10384.88 Kitems/sec.
Produced:     99435.68 Kitems/sec.
Testing for arg=10000
Consumed:     10458.63 Kitems/sec.
Produced:     99189.41 Kitems/sec.
Testing for arg=100000
Consumed:     10258.47 Kitems/sec.
Produced:     99326.16 Kitems/sec.
Testing for arg=1000000
Consumed:     10368.36 Kitems/sec.
Produced:     97798.35 Kitems/sec.
Testing for arg=10000000
Consumed:     10711.63 Kitems/sec.
Produced:     94015.14 Kitems/sec.
```

For CPU binding version

```c
#define _GNU_SOURCE
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <stdbool.h>
#include <sys/time.h>
#include <sched.h>
#include <errno.h>

#define QUEUE_SIZE 1048576
#define PERIOD 2
#define WAKEUP_INTERVAL 100

typedef struct {
    bool buffer[QUEUE_SIZE];
    int head;
    int tail;
    pthread_mutex_t lock;
} SimpleQueue;

void init_queue(SimpleQueue *queue) {
    queue->head = 0;
    queue->tail = 0;
    pthread_mutex_init(&queue->lock, NULL);
    for (int i = 0; i < QUEUE_SIZE; i++) {
        queue->buffer[i] = false;
    }
}

bool enqueue(SimpleQueue *queue, bool value) {
    pthread_mutex_lock(&queue->lock);
    int next_tail = (queue->tail + 1) % QUEUE_SIZE;

    if (next_tail == queue->head) {
        // Queue is full
        pthread_mutex_unlock(&queue->lock);
        return false;
    }

    queue->buffer[queue->tail] = value;
    queue->tail = next_tail;
    pthread_mutex_unlock(&queue->lock);
    return true;
}

bool dequeue(SimpleQueue *queue, bool *value) {
    pthread_mutex_lock(&queue->lock);

    if (queue->head == queue->tail) {
        // Queue is empty
        pthread_mutex_unlock(&queue->lock);
        return false;
    }

    *value = queue->buffer[queue->head];
    queue->head = (queue->head + 1) % QUEUE_SIZE;
    pthread_mutex_unlock(&queue->lock);
    return true;
}

double monotonic_time() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec / 1000000000.0;
}

void *thread_func(void *arg) {
    SimpleQueue *queue = (SimpleQueue *)arg;
    int consumed = 0;
    double start = monotonic_time();

    bool value;
    while (true) {
        if (dequeue(queue, &value) && value) {
            consumed++;
        } else {
            break; // exit loop when dequeue returns false or value is false
        }
    }

    double end = monotonic_time();
    printf("Consumed: %12.2f Kitems/sec.\n", consumed / 1000.0 / (end - start));

    return NULL;
}

void set_cpu_affinity() {
    cpu_set_t mask;
    CPU_ZERO(&mask);
    CPU_SET(1, &mask);  // 将进程和线程绑定到 CPU 1

    if (sched_setaffinity(0, sizeof(cpu_set_t), &mask) == -1) {
        perror("sched_setaffinity");
        exit(EXIT_FAILURE);
    }
}

int main() {
    // 设置全局的 CPU 亲和性
    set_cpu_affinity();

    // 检查当前 CPU 亲和性设置
    cpu_set_t mask;
    CPU_ZERO(&mask);
    if (sched_getaffinity(0, sizeof(cpu_set_t), &mask) == -1) {
        perror("sched_getaffinity");
        exit(EXIT_FAILURE);
    }

    printf("Current CPU affinity: ");
    for (int i = 0; i < CPU_SETSIZE; i++) {
        if (CPU_ISSET(i, &mask)) {
            printf("%d ", i);
        }
    }
    printf("\n");

    int args[] = {1, 10, 100, 1000, 10000, 100000, 1000000, 10000000};

    for (int i = 0; i < sizeof(args) / sizeof(args[0]); i++) {
        int arg = args[i];
        printf("Testing for arg=%d\n", arg);

        SimpleQueue queue;
        init_queue(&queue);

        pthread_t thread;
        pthread_create(&thread, NULL, thread_func, &queue);

        int cnt = 0;
        double deadline = monotonic_time() + PERIOD;

        while (monotonic_time() < deadline) {
            for (int j = 0; j < arg; j++) {
                cnt++;
                if (enqueue(&queue, true)) {
                    if (cnt % WAKEUP_INTERVAL == 0) {
                        sched_yield(); // 唤醒消费线程
                    }
                }
            }
        }

        double stop = monotonic_time();
        enqueue(&queue, false);
        pthread_join(thread, NULL);

        printf("Produced: %12.2f Kitems/sec.\n", cnt / 1000.0 / (stop - (deadline - PERIOD)));
    }

    return 0;
}
```

The result here

```text
╰─ ╰─ ./demo2-binary
Current CPU affinity: 1
Testing for arg=1
Consumed:     99700.91 Kitems/sec.
Produced:     42461.31 Kitems/sec.
Testing for arg=10
Consumed:     96153.85 Kitems/sec.
Produced:     91034.38 Kitems/sec.
Testing for arg=100
Consumed:     93984.99 Kitems/sec.
Produced:    102509.55 Kitems/sec.
Testing for arg=1000
Consumed:     82101.88 Kitems/sec.
Produced:    103914.51 Kitems/sec.
Testing for arg=10000
Consumed:     85397.10 Kitems/sec.
Produced:    104227.12 Kitems/sec.
Testing for arg=100000
Consumed:     83542.15 Kitems/sec.
Produced:    104308.01 Kitems/sec.
Testing for arg=1000000
Consumed:     95147.54 Kitems/sec.
Produced:    103941.68 Kitems/sec.
Testing for arg=10000000
Consumed:    100100.11 Kitems/sec.
Produced:    103952.10 Kitems/sec.
```

**Closed as completed** 2024-07-28 16:14 UTC
Labels: type-bug

**Comment by Eclips4** [comment] 2024-07-28 17:43
> @Eclips4 would you mind helping me reopen this issue? I think we do not find root cause yet.

Do you think the problem is on the CPython side?

**Comment by Zheaoli** [comment] 2024-07-28 17:44
> Do you think the problem is on the CPython side?

100%  not in CPython side... lol

**Comment by Eclips4** [comment] 2024-07-28 17:46
> > Do you think the problem is on the CPython side?
> 
> 99.999% not in CPython side... lol

If this isn't on the CPython side, then I think this issue doesn't need to be reopened. :)

**Comment by Zheaoli** [comment] 2024-07-28 17:48
> If this isn't on the CPython side, then I think this issue doesn't need to be reopened. :)

Got it, I will try to get more detail about this and I may ask you for reopen this if I find the issue in CPython side
