### ISSUE TITLE
Race with KeyboardInterrupt in asyncio loop run_forever() method

### ISSUE THREAD

**Issue by hetmankp** [python/cpython#94732] opened 2022-07-11 06:13 UTC
There is a race with the `KeyboardInterrupt` exception in the **asyncio.base_events.BaseEventLoop.run_forever()** method. While an attempt is made to restore the environment to its previous state before `run_forever()` completes with a `try...finally`, a couple items find themselves outside the `try...finally`. Specifically, a badly timed `KeyboardInterrupt` will mean that, neither the `self._thread_id` value or the hooks set by `sys.set_asyncgen_hooks()` will be correctly restored. Both of these should be moved inside the `try...finally`.

https://github.com/python/cpython/blob/c9118afd045a64ca22d4a8cc5d43532607083b2d/Lib/asyncio/base_events.py#L596-L600

This applies to all existing version of Python on all platforms.

**Comment by gvanrossum** [comment] 2022-10-03 21:41
Fixed!

@hetmankp: Thanks for being flexible regarding the CLA bot. I hope the problem is now fixed for you going forward?

**Closed as completed by gvanrossum** 2022-10-03 21:41 UTC
Labels: type-bug, topic-asyncio

**Comment by hetmankp** [comment] 2022-10-04 04:22
> Fixed!
> 
> @hetmankp: Thanks for being flexible regarding the CLA bot. I hope the problem is now fixed for you going forward?

Thanks @gvanrossum , yes as far as CPython is concerned I should be covered (not sure why the simpler email format wasn't working but I guess it will remain a mystery for now).
