### ISSUE TITLE
`unittest.mock.patch` ,`create=False` flag not working as expected?

### ISSUE THREAD

**Issue by noklam** [python/cpython#93290] opened 2022-05-27 13:28 UTC
**Bug report**

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

The 2nd test is expected to fail with `create=False` because it tries to access an attribute that does not exist.

# Code Sample
```python
import unittest
from unittest.mock import patch

class Dummy:
    def __init__(self, x) -> None:
        self.x = x

class MyTestCase(unittest.TestCase):
    @patch(f"{__name__}.Dummy", create=True)
    def test_mocker_non_exist_attrs_true(self, mock_class):
        dummy = mock_class(1)
        print(__name__)
        print(type(dummy), dummy)
        dummy.p

    @patch(f"{__name__}.Dummy", create=False)
    def test_mocker_non_exist_attrs_false(self, mock_class):
        dummy = mock_class(1)
        with self.assertRaises(Exception) as context:
            print(type(dummy), dummy)
            dummy.p

if __name__ == '__main__':
    unittest.main()
```
# Full Test Result
```
python -m unittest tests/  0.08s user 0.04s system 68% cpu 0.181 total
  0.01s user 0.01s system 77% cpu 0.015 total                                                              
Nok_Lam_Chan dummy % python tests/test_dummy.py
<class 'unittest.mock.MagicMock'> <MagicMock name='Dummy()' id='140512275384304'>
F__main__
<class 'unittest.mock.MagicMock'> <MagicMock name='Dummy()' id='140512541087248'>
.
======================================================================
FAIL: test_mocker_non_exist_attrs_false (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Nok_Lam_Chan/miniconda3/lib/python3.8/unittest/mock.py", line 1348, in patched
    return func(*newargs, **newkeywargs)
  File "tests/test_dummy.py", line 21, in test_mocker_non_exist_attrs_false
    dummy.p
AssertionError: Exception not raised

----------------------------------------------------------------------
Ran 2 tests in 0.005s

FAILED (failures=1)
```

**Your environment**

- CPython versions tested on: Python 3.8.2
- Operating system and architecture: MacOS

**Comment by AA-Turner** [comment] 2022-05-27 19:43
A simpler demonstration is:

```pycon
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:34:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest.mock import patch
>>> class Dummy:
...     def __init__(self, x) -> None:
...         self.x = x
...
>>> with patch(f"{__name__}.Dummy", create=False):
...     dummy = Dummy(1)
...     print(type(dummy), dummy)
...     print(dummy.y)
...
<class 'unittest.mock.MagicMock'> <MagicMock name='Dummy()' id='1765036855152'>
<MagicMock name='Dummy().y' id='1765036887344'>
>>> with patch(f"{__name__}.Dummy2", Dummy, create=False):
...     Dummy2(1)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\unittest\mock.py", line 1437, in __enter__
    original, local = self.get_original()
  File "C:\...\lib\unittest\mock.py", line 1410, in get_original
    raise AttributeError(
AttributeError: <module '__main__' (built-in)> does not have the attribute 'Dummy2'
```

`create=False` is for ensuring that the string passed as the first argument exists before patching it, rather than not creating new arguments on the returned mock object.

I think you actually want `spec=True`, as below:

```pycon
>>> with patch(f"{__name__}.Dummy", spec=True):
...     dummy = Dummy(1)
...     print(type(dummy), dummy)
...     print(dummy.y)
...
<class 'unittest.mock.NonCallableMagicMock'> <NonCallableMagicMock name='Dummy()' spec='Dummy' id='1765036674208'>
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "C:\ProgramData\Miniconda3\envs\sphinx-bugfixing\lib\unittest\mock.py", line 634, in __getattr__
    raise AttributeError("Mock object has no attribute %r" % name)
AttributeError: Mock object has no attribute 'y'
```

Closing as not a bug.

A

**Closed as not planned by AA-Turner** 2022-05-27 19:43 UTC
Labels: type-bug
