### ISSUE TITLE
Command + v is pasting twice in IDLE if Caps lock key is on in Mac OS 

### ISSUE THREAD

**Issue by mesoumyapaul** [python/cpython#100645] opened 2022-12-31 17:37 UTC

**Comment by aivarannamaa** [comment] 2023-05-22 07:24
According to my tests, this is fixed in Tk 8.6.13 (https://github.com/thonny/thonny/issues/2753)

**Comment by ronaldoussoren** [comment] 2023-12-08 13:35
@aivarannamaa: thanks for the updated.

I've checked that the issue is no longer present in the latest 3.12 installer which includes Tk 8.6.13 (and can be reproduced with an old 3.9 install with an older version of Tk).

**Closed as not planned by ronaldoussoren** 2023-12-08 13:35 UTC
Labels: OS-mac, topic-IDLE
