### ISSUE TITLE
Refleak in `test_importlib` on `aarch64 RHEL8`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#101766] opened 2023-02-09 23:14 UTC
I am not sure what is going on with this test run:

```
Ran 1377 tests in 3.713s
OK (skipped=18, expected failures=1)
......
test_importlib leaked [6, 4, 2] references, sum=12
test_importlib leaked [4, 4, 2] memory blocks, sum=10
0:32:52 load avg: 0.42 Re-running test_asyncio in verbose mode (matching: test_fork_asyncio_subprocess)
beginning 6 repetitions
123456
/home/buildbot/buildarea/pull_request.cstratak-RHEL8-aarch64.refleak/build/Lib/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=4145974) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
test_fork_asyncio_subprocess (test.test_asyncio.test_unix_events.TestFork.test_fork_asyncio_subprocess) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.072s
OK
./home/buildbot/buildarea/pull_request.cstratak-RHEL8-aarch64.refleak/build/Lib/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=4145974) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
test_fork_asyncio_subprocess (test.test_asyncio.test_unix_events.TestFork.test_fork_asyncio_subprocess) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.060s
OK
./home/buildbot/buildarea/pull_request.cstratak-RHEL8-aarch64.refleak/build/Lib/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=4145974) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
test_fork_asyncio_subprocess (test.test_asyncio.test_unix_events.TestFork.test_fork_asyncio_subprocess) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.059s
OK
./home/buildbot/buildarea/pull_request.cstratak-RHEL8-aarch64.refleak/build/Lib/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=4145974) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
test_fork_asyncio_subprocess (test.test_asyncio.test_unix_events.TestFork.test_fork_asyncio_subprocess) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.060s
OK
./home/buildbot/buildarea/pull_request.cstratak-RHEL8-aarch64.refleak/build/Lib/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=4145974) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
test_fork_asyncio_subprocess (test.test_asyncio.test_unix_events.TestFork.test_fork_asyncio_subprocess) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.061s
OK
./home/buildbot/buildarea/pull_request.cstratak-RHEL8-aarch64.refleak/build/Lib/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=4145974) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
test_fork_asyncio_subprocess (test.test_asyncio.test_unix_events.TestFork.test_fork_asyncio_subprocess) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.057s
OK
.
1 test failed again:
    test_importlib
```

See https://buildbot.python.org/all/#builders/802/builds/623

### Linked PRs
* gh-101942
* gh-101987
* gh-101988

**Comment by sobolevn** [comment] 2023-02-12 09:25
First failing build that I was able to find: https://buildbot.python.org/all/#/builders/802/builds/582

See https://github.com/python/cpython/pull/101394

**Comment by corona10** [comment] 2023-02-14 02:32
```

beginning 6 repetitions
123456
......
test_importlib leaked [134, 134, 134] references, sum=402
test_importlib leaked [56, 56, 56] memory blocks, sum=168
test_importlib failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_importlib

Total duration: 598 ms
Tests result: FAILURE
ran 1 tests/2
exit 2
Tests failed: continuing with this subtest

Tests (1):
* test.test_importlib.test_metadata_api.APITests.test_version_egg_info_file

Bisection completed in 16 iterations and 0:00:21
[root@65cf87cd990d cpython]#
```

**Comment by gvanrossum** [comment] 2023-02-14 21:07
@corona10 If you found a suspect can you link it here?

**Comment by corona10** [comment] 2023-02-15 01:18
> @corona10 If you found a suspect can you link it here?

Sure

**Comment by corona10** [comment] 2023-02-15 16:03
@gvanrossum @sobolevn @mdickinson @brettcannon 

I finally found the suspect:
commit: https://github.com/python/cpython/commit/3325f054e33b318aa56b74472f76a56b8afc0510
PR: https://github.com/python/cpython/pull/94504

I run `./python -m test test_importlib` repeatedly 10 times on `aarch64 RHEL8(rockylinux:8.7)`
When I revert the https://github.com/python/cpython/commit/3325f054e33b318aa56b74472f76a56b8afc0510, no more leak is detected.

The root cause has yet to be discovered.

**Comment by gvanrossum** [comment] 2023-02-15 16:53
Is the SEND fix it?

**Comment by sobolevn** [comment] 2023-02-15 17:29
@corona10 great work, thank you!

**Comment by corona10** [comment] 2023-02-15 20:58
> Is the SEND fix it?

Do you mean c7766245c14fa03b8afd3aff9be30b13d0069f95? No, it doesn't solve the issue.

**Comment by gvanrossum** [comment] 2023-02-15 21:23
Usually leaks are C code. There is no C code in the importlib PR. Maybe the blocking_on dict needs to be cleared?

**Comment by corona10** [comment] 2023-02-15 21:40
> Usually leaks are C code.

I think sameway.

> Maybe the blocking_on dict needs to be cleared?

I will try it.

**Comment by corona10** [comment] 2023-02-15 22:53
>  Maybe the blocking_on dict needs to be cleared?

Yeah, this was the root cause. Amazing intuition!!

````diff

diff --git a/Lib/importlib/_bootstrap.py b/Lib/importlib/_bootstrap.py
index bebe7e15cb..e42e7bc653 100644
--- a/Lib/importlib/_bootstrap.py
+++ b/Lib/importlib/_bootstrap.py
@@ -85,6 +85,7 @@ def __enter__(self):
     def __exit__(self, *args, **kwargs):
         """Remove self.lock from this thread's _blocking_on list."""
         self.blocked_on.remove(self.lock)
+        del _blocking_on[self.thread_id]
````

I am checking the proper solution.

**Comment by gvanrossum** [comment] 2023-02-15 23:03
Whenever there's a global cache you get things like this, I've debugged these since 2000. :-)

Good work finding the missing `del`! And thanks for the hard work doing bisection.

Also @sobolevn thanks for flagging this -- I had seen this occasionally but always just ignored it as being a flake. It was so much more than that!

All in all great teamwork.

**Comment by corona10** [comment] 2023-02-17 10:15
Close this issue
And thank you for reporting this issue @sobolevn!!!

**Closed as completed** 2023-02-20 15:46 UTC
Labels: type-bug
