### ISSUE TITLE
Docstring and fstring combination

### ISSUE THREAD

**Issue by rohanbatrain** [python/cpython#99624] opened 2022-11-20 17:36 UTC
**Is your feature request related to a problem? Please describe.**
I am working on a project and is writing docstrings pretty much with the same content and little changes. So, I thought why not add all the repetitive content and use a fstring in oppose to using docstring. But it didn't work as expected.

**Describe the solution you'd like**
Wouldn't that be great to add support for fstrings as docstrings?  

**Describe alternatives you've considered**
Nothing just writing repetitive text here and there for all my docstrings.

**Additional context**
Pylint still doesn't seem to recognise this as a docstring because it is an fstring obviously.

![2022-11-20_1364x750](https://user-images.githubusercontent.com/116573125/202917026-ba11cc5c-b26a-41d4-a4b0-3f232c8d7d98.png)

**Comment by rohanbatrain** [comment] 2022-11-20 18:36
> I'm moving this to the CPython project because it belongs there instead of on the Pythondotorg repo.
Thanks  and Sorry for posting it on the wrong repo. I got confused. First issue on python github :)

**Comment by ericvsmith** [comment] 2022-11-20 19:48
The original implementation supported this, but we removed it. The problem is that it's not clear when the f-string would be evaluated.

There's an old discussion here: https://bugs.python.org/issue28739 and here: https://bugs.python.org/issue25179

I'm going to close this. If you can address all of the prior objections and problems, it can be re-opened.

**Closed as not planned by ericvsmith** 2022-11-20 19:48 UTC
