### ISSUE TITLE
SSLObject does not raise SSLEOFError on OpenSSL 3

### ISSUE THREAD

**Issue by 1b708fa4-eb40-42d9-9dfe-9f0c3bf31a47** [python/cpython#90471] opened 2022-01-09 13:40 UTC
BPO | [46313](https://bugs.python.org/issue46313)
--- | :---
Nosy | @agronholm, @ambv

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-09.13:40:17.069>
labels = ['expert-SSL', 'type-bug', '3.8', '3.9', '3.10', '3.11']
title = 'SSLObject does not raise SSLEOFError on OpenSSL 3'
updated_at = <Date 2022-01-10.11:26:36.211>
user = 'https://github.com/agronholm'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-10.11:26:36.211>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['SSL']
creation = <Date 2022-01-09.13:40:17.069>
creator = 'alex.gronholm'
dependencies = []
files = []
hgrepos = []
issue_num = 46313
keywords = []
message_count = 8.0
messages = ['410146', '410150', '410159', '410162', '410164', '410165', '410199', '410201']
nosy_count = 2.0
nosy_names = ['alex.gronholm', 'lukasz.langa']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46313'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by gpshead** [comment] 2022-11-03 22:12
duplicate of https://github.com/python/cpython/issues/95494

**Closed as not planned by gpshead** 2022-11-03 22:12 UTC
Labels: type-bug, 3.11, 3.10, 3.9 (EOL), 3.8 (EOL), topic-SSL
