### ISSUE TITLE
object.h uses an anonymous union in a struct (older C incompatible)

### ISSUE THREAD

**Issue by zooba** [python/cpython#105059] opened 2023-05-29 13:04 UTC
An anonymous union was added recently, making this header produce warnings/errors for C++ compilers that have not enabled the relevant extensions/standards.

https://github.com/python/cpython/blame/1668b41dc477bc9562e4c50ab36a232839b4621b/Include/object.h#L168-L173

This code looks like it's making a few too many assumptions anyway. I suspect we ought to be wrapping up accesses to `ob_refcnt_split` in a macro and masking, rather than using a union. Or at least setting up the union to not assume that `SIZEOF_VOID_P > 4` implies `SIZEOF_VOID_P == 8`.

(Ping @eduardo-elizondo)

### Linked PRs
* gh-105275
* gh-105764
* gh-105767
* gh-107232
* gh-107236
* gh-107239
* gh-107248

**Comment by zooba** [comment] 2023-05-29 13:08
Seems the only use of it is later in object.h:

```
#if SIZEOF_VOID_P > 4
    // Portable saturated add, branching on the carry flag and set low bits
    PY_UINT32_T cur_refcnt = op->ob_refcnt_split[PY_BIG_ENDIAN];
    PY_UINT32_T new_refcnt = cur_refcnt + 1;
    if (new_refcnt == 0) {
        return;
    }
    op->ob_refcnt_split[PY_BIG_ENDIAN] = new_refcnt;
```

Is this really better than this code?:

```
    Py_ssize_t new_refcnt = op->ob_refcnt + 1;
    if (new_refcnt & ~0xFFFFFFFF) return;
    // or
    if ((PY_UINT32_T)new_refcnt != new_refcnt) return;
````

Seems we can rely on the compilers to figure out efficient ways to do these, no?

**Comment by sunmy2019** [comment] 2023-05-29 13:27
Note
```
    if (new_refcnt & ~0xFFFFFFFF) return;
```
This changes the definition of immortality. Previously `refcnt % 2^32 == -1`, now `refcnt >= 2^32 -1`.


```
    if ((PY_UINT32_T)new_refcnt != new_refcnt) return;
```
This changes the definition of immortality. Previously `refcnt % 2^32 == -1`, now `refcnt >= 2^32 -1 or refcnt < -1 (impossible)`.

I don't mean this isn't desired; I just want to bring attention that something has changed here.

**Comment by zooba** [comment] 2023-05-29 14:06
> Both change the definition of immortality. Previously `refcnt % 2^32 == -1`, now `refcnt >= 2^32 -1 or refcnt < -1 (impossible)`.

You mean before you could (manually?) set a refcount to `0x00000001_00000000` and it wouldn't saturate, but now it will? I guess that's true, but also irrelevant. The definition of immortality isn't changed, just the condition under which `Py_INCREF` stops incrementing the refcount. And at least by my reading, that's going to apply to all objects, it's just that immortal objects start there and non-immortal ones will never reach it.

Incidentally, after a bit of playing with godbolt.org, it seems that gcc generates the same code for these two snippets (the first is the current code, and remember to add `-O2` if you're trying to reproduce):

```
    PY_UINT32_T cur_refcnt = op->ob_refcnt_split[PY_BIG_ENDIAN];
    PY_UINT32_T new_refcnt = cur_refcnt + 1;
```

```
    PY_UINT32_T new_refcnt = (PY_UINT32)(op->ob_refcnt + 1);
```

The latter doesn't require a union at all, and so doesn't depend on the size of `void *`. Simpler code all around.

**Comment by sunmy2019** [comment] 2023-05-29 17:11
> ```
>     PY_UINT32_T new_refcnt = (PY_UINT32)(op->ob_refcnt + 1);
> ```

> The latter doesn't require a union at all, and so doesn't depend on the size of `void *`. Simpler code all around.

Indeed! But it should be `(PY_UINT32)(op->ob_refcnt) + 1;`

Since there is indeed a compiler switch to control the behavior of signed int overflow. UB happens at `op->ob_refcnt + 1`.

But on the other side, unsigned int overflow is a well-defined behavior. So `(PY_UINT32)(op->ob_refcnt) + 1;` is good.

**Comment by zooba** [comment] 2023-05-29 17:27
We don't actually overflow in the `op->ob_refcnt + 1` case (we've taken a different path if it's only 32 bits). So we get truncation at the cast, not an overflow.

Either way, I think we ought to get _something_ else in for b2, as this can block people from testing. Marking as a release blocker, and @Yhg1s can decide.

**Comment by sunmy2019** [comment] 2023-05-29 17:32
> So we get truncation at the cast, not an overflow.

If so, `(PY_UINT32)(op->ob_refcnt) + 1` should be equal to `(PY_UINT32)(op->ob_refcnt + 1)`. And the former is a little bit safer without any possible UB.

**Comment by eduardo-elizondo** [comment] 2023-05-31 04:43
@zooba @sunmy2019 thanks for bringing up the issue! I think I might be able to get rid of the union easily and I'll try to get a patch in the next couple of days.

Separately, let's be careful about making any changes into the IncRef logic, the current code was very carefully crafted to maximize performance in windows, linux, and mac and was thoroughly benchmarked. There are also subtle side effects that can happen if we don't perform the operations correctly. For example, the suggested fix:

```
PY_UINT32_T new_refcnt = (PY_UINT32)(op->ob_refcnt + 1);
```

Would eventually require us to do something like:
```
op->ob_refcnt = new_refcnt;
```

^ this will cause an implicit conversion from 32 to 64 bit as the generated code assigns the 32 bit register to the 64 bit register. This causes incorrect behavior since we can have Extension code that has increased the reference count beyond the maximum value and this implicit conversion would cause the reference count of the extension to be lost. Then, it will result in a crash since we will decref this to deletion even when there are valid references to the object.

Anyways, give me a couple of days to explore a couple of options and I'll get back to this thread! In the meantime, if we can get some repro examples, that would be great!

**Comment by encukou** [comment] 2023-05-31 06:36
> if we can get some repro examples, that would be great!

It would! Alas, compilers are weird and `distutils` is pining for fjords, so...

For anonymous structs/unions, Linux/GCC, with Python 3.13 installed (so that `python3.13-config` is in `PATH`):
```
$ cat repro.c
#include <Python.h>

int main () {
    return 0;
}
```

```
$ gcc $(python3.13-config --cflags --ldflags) -lpython3.13$(python3.13-config --abiflags) -std=c99 -pedantic repro.c
In file included from .../include/python3.13d/Python.h:44,
                 from repro.c:1:
.../include/python3.13d/object.h:173:6: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  173 |     };
      |      ^
```

**Comment by zooba** [comment] 2023-05-31 11:14
Yeah, it looks like it's actually C compatibility, not C++. When I dug further into my failing build, it's actually one of the `.c` files.

Reproing using Petr's code from above with MSVC:
```
> cl /c /I(python3.12 -c "import sysconfig; print(sysconfig.get_config_var('INCLUDEPY'), end='')") /W4 .\t.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32619.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

t.c
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.177.0_x64__3847v3x7pw1km\Include\object.h(173): warning C4201: nonstandard extension used: nameless struct/union
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.177.0_x64__3847v3x7pw1km\Include\cpython/unicodeobject.h(203): warning C4100: '_unused_op': unreferenced formal parameter
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.177.0_x64__3847v3x7pw1km\Include\cpython/unicodeobject.h(393): warning C4100: '_unused_op': unreferenced formal parameter
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.177.0_x64__3847v3x7pw1km\Include\cpython/pytime.h(192): warning C4115: 'timeval': named type definition in parentheses
```

All four warning disappear when you don't use `/W4`, which is our standard, but we shouldn't be warning even on high levels. The non-standard extension should definitely be avoided - I think the other two have been in there for a while.

I think we need a test that basically includes the headers and spits out warnings or errors. Shouldn't need to be anything more clever than a make target. That doesn't have to be part of this fix.

**Comment by zooba** [comment] 2023-05-31 11:33
> Would eventually require us to do something like:
> 
> ```
> op->ob_refcnt = new_refcnt;
> ```

Then perhaps this, if "lower 32-bits set == saturated"?

```
Py_ssize_t new_refcnt = op->ob_refcnt + 1;
if ((PY_UINT32)new_refcnt == 0) { // might have to be & 0xFFFFFFFF instead of the cast
    return;
}
op->ob_refcnt = new_refcnt;
```

**Comment by eduardo-elizondo** [comment] 2023-06-04 02:42
Some updates, I just removed the union in PR105059. I will follow-up with a couple of other different options and benchmark numbers. Will let you all know once it's ready to be reviewed.

**Comment by gpshead** [comment] 2023-06-04 18:41
Per https://peps.python.org/pep-0007/#c-dialect _"Python 3.11 and later use C11 without [optional features](https://en.wikipedia.org/wiki/C11_%28C_standard_revision%29#Optional_features)"_.

Anonymous Structs and Unions [**are part of C11**](https://en.wikipedia.org/wiki/C11_%28C_standard_revision%29#Changes_from_C99).

**Comment by eduardo-elizondo** [comment] 2023-06-04 18:48
> Per https://peps.python.org/pep-0007/#c-dialect "Python 3.11 and later use C11 without [optional features](https://en.wikipedia.org/wiki/C11_%28C_standard_revision%29#Optional_features)".
> Anonymous Structs and Unions [**are part of C11**](https://en.wikipedia.org/wiki/C11_%28C_standard_revision%29#Changes_from_C99).

@gpshead so does that mean that PEP007 guarantees that it's ok to have anonymous unions in Python 3.11?

**Comment by eduardo-elizondo** [comment] 2023-06-04 19:14
> Then perhaps this, if "lower 32-bits set == saturated"?

Also @zooba to close the loop, I had tested this in the past but I just did it again to get some fresh numbers [here](https://github.com/eduardo-elizondo/cpython/commit/b5568d74427c3160ec2f432c8c0eb1ffccf7fcc5). Looking at the generated code, it is not leveraging the saturated add which removes an extra instruction: https://godbolt.org/z/5rrdjPbMM. 

But generated code is just a proxy so I benchmarked it on a Linux machine with GCC-11.1 and it recorded a: *Geometric mean: 1.01x slower*. I'm testing it with the memset as well which looks neutral (since it generates almost the same code).

Ultimately, I'm indifferent what structure we end up using, so I'm open to use the option you suggested if there's consensus on the regression. However, perf was a core part of the original upstreaming, so I went for the most perf efficient option.

**Comment by gpshead** [comment] 2023-06-04 19:19
> > Per https://peps.python.org/pep-0007/#c-dialect "Python 3.11 and later use C11 without [optional features](https://en.wikipedia.org/wiki/C11_%28C_standard_revision%29#Optional_features)".
> > Anonymous Structs and Unions [**are part of C11**](https://en.wikipedia.org/wiki/C11_%28C_standard_revision%29#Changes_from_C99).
> 
> @gpshead so does that mean that PEP007 guarantees that it's ok to have anonymous unions in Python 3.11? Hence making the original issue invalid now?

That is _my interpretation_. This seems to tie in with another discussion on https://discuss.python.org/t/requiring-compilers-c11-standard-mode-to-build-cpython/26481.

---

Regardless of the primary issue about the union being modern, I do think the point about `SIZEOF_VOID_P > 4` being better written as `SIZEOF_VOID_P == 8` is valid. Just make an `#error` if compiling somewhere with a `> 8` pointer size. I'm not aware of any such systems but our code isn't ready to run on whatever they are.

**Comment by gpshead** [comment] 2023-06-05 14:51
Is there a reason the union has to be anonymous? Why can't we just give it a name?

**Comment by encukou** [comment] 2023-06-05 15:01
> Why can't we just give it a name?

That would mean all uses of [`obj->ob_refcnt`](https://docs.python.org/3/c-api/typeobj.html?highlight=ob_refcnt#c.PyObject.ob_refcnt) would change to to `obj->just_a_name.refcnt`.

Anonymous unions are a great tool for keeping API compatibility around changes like these. I wish we could use them :)

**Comment by eduardo-elizondo** [comment] 2023-06-05 15:11
Exactly as Petr said, it's just to keep the API compatibility so that we can still access `ob_refcnt` directly.

**Comment by gpshead** [comment] 2023-06-05 17:16
okay, that's what I assumed given the public header file.

**Comment by vstinner** [comment] 2023-06-06 14:20
> Exactly as Petr said, it's just to keep the API compatibility so that we can still access ob_refcnt directly.

While it's not officially deprecated, I would strongly suggest to use Py_REFCNT() and Py_SET_REFCNT() functions instead. See issue #83754.

**Comment by zooba** [comment] 2023-06-06 14:49
> But generated code is just a proxy so I benchmarked it on a Linux machine with GCC-11.1 and it recorded a: _Geometric mean: 1.01x slower_. I'm testing it with the memset as well which looks neutral (since it generates almost the same code).

Personally, I'd prefer the solution that benchmarks slightly slower but doesn't make assumptions about the representation. We're talking about public API that is inlined into every piece of code that _uses_ our API, not merely our own code.

Victor's proposed change to make incref/decref functions are 100% correct,[^1] but will represent a much larger performance regression than simply having reliable, portable code here. It will also be breaking for existing abi3 extensions, just like this one.

I totally get the perf benefits from being clever here, but as long as we're talking about code in the limited API/stable ABI, we don't really have the choice to be clever. We _must_ be compatible. Once limited API users are only touching ref counts through functions that are tied to the actual running CPython version, not the one used to compile, then we can change the code that gets inlined for speed.

[^1]: The concept, at least. I haven't looked at the actual code.

**Comment by vstinner** [comment] 2023-06-06 15:18
> Victor's proposed change to make incref/decref functions are 100% correct, but will represent a much larger performance regression than simply having reliable, portable code here.

I'm only thinking about changing the limited C API: issue #105387.

**Comment by gpshead** [comment] 2023-06-07 18:04
> based on the conversation here, it seems like we want to maintain C89 compatibility for the headers

I would not draw this conclusion. It isn't settled or agreed upon.  (further discussion on that I leave to the Discuss thread)

**Comment by zooba** [comment] 2023-06-07 20:42
> * As it stands, this version of `Py_INCREF` should be backwards compatible. The semantics _do change_ but it doesn't mean that it will not be compatible in the Limited API

The problem here is that it's _technically_ (and fairly obviously) not compatible. But hitting any issue is unlikely enough that the SC agreed it can be treated as backwards compatible.

I think the biggest problem will be if an immortalised object is de-immortalised by an abi3 extension built against 3.11 or earlier, which seems it would be as simple as a 3.12 `PyObject_GetAttr` followed by 3.11 `Py_DECREF`. That breaks the fast path/copy-on-write "support" in `INCREF`/`DECREF` (until the next unbalanced `INCREF`), even throughout other modules that were built for speed in 3.12. Perhaps the SC considered that it would be okay for a single abi3 extension to essentially globally disable the optimisation, and I just missed that statement (very likely!). There aren't many abi3 extensions out there, and we aren't really encouraging them with the number of ways we keep breaking them, so it's probably still unlikely for this case to be hit.

However, using a mask bit rather than a precise overflow would be significantly more robust here, and still avoid the expensive write (while costing a potentially large `test` instruction on architectures without an efficient bit-test opcode).

I don't know that there is any way to preserve abi3 across this change in both directions. An abi3 build with 3.12 could use "old style" INCREF, but adding an opaque `Py_IncRef` is breaking (doesn't exist on earlier versions).

It feels likely best (for correctness/compatibility) for the immortality flag to not be in the refcount, but to be only handled by `tp_dealloc`. Which was rejected because it doesn't help copy-on-write, but I don't think that case really gets helped anyway? Or at least can be broken inadvertently enough that it seems a weak motivation to justify breaking abi3 in this release. Especially since a major goal of immortal objects was to not break abi3.

**Comment by vstinner** [comment] 2023-06-14 01:16
```
cl /c /I(python3.12 -c "import sysconfig; print(sysconfig.get_config_var('INCLUDEPY'), end='')") /W4 .\t.c
(...)
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.177.0_x64__3847v3x7pw1km\Include\object.h(173): warning C4201: nonstandard extension used: nameless struct/union
```

Compiler Warning (level 4) C4201: https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4201?view=msvc-170

> Under **Microsoft extensions (/Ze), you can** specify a structure without a declarator as members of another structure or union. These structures generate an **error under ANSI compatibility** (/Za).

It seems like MSC compiler implements anonymous union, but it's an extension. Depending on the compiler options, it can be allowed or treated as an error. At least, it's treated as an error if a C extension is built with ``/Za`` option.

Is the problem here that when ``/Ze`` and  ``/Za`` are not specified (default case?), a **new compiler warning** is emitted with Python 3.12?

Note: I'm curious. Does someone know if it was possible to build a C extension with Python 3.11 and ``/Za`` option?

**Comment by vstinner** [comment] 2023-06-14 01:46
Test using [repro.c](https://github.com/python/cpython/issues/105059#issuecomment-1569578771) on Fedora 38 with GCC 13.1.1.

Python 3.11 **does not** emit any compiler warning using ``gcc -std=c99 -pedantic``.

Python 3.12 **emits a new compiler warning**  using ``gcc -std=c99 -pedantic``: I confirm that it's a regression.

The [GCC -pedantic option](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-pedantic-1) is not commonly used. It controls *compiler warnings*:

> Issue all the warnings demanded by **strict ISO C** and ISO C++

Should we really worry about the GCC -pedantic case? At least, it helps to reproduce the issue on Linux :-)

Compiler warning with Python 3.12 C API with ``-std=c99 -pedantic``:

```
$ gcc $(python3.12-config --cflags --ldflags) -lpython3.12$(python3.12-config --abiflags) -std=c99 -pedantic repro.c 
In file included from /usr/include/python3.12/Python.h:44,
                 from repro.c:1:
/usr/include/python3.12/object.h:173:6: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
  173 |     };
      |      ^
```

The warning is on PyObject anonymous union of ``/usr/include/python3.12/object.h``:

```c
struct _object {
    _PyObject_HEAD_EXTRA
    union {
       Py_ssize_t ob_refcnt;
#if SIZEOF_VOID_P > 4
       PY_UINT32_T ob_refcnt_split[2];
#endif
    };  // <========= WARNING HERE
    PyTypeObject *ob_type;
};
```

**Comment by vstinner** [comment] 2023-06-14 01:47
I wrote PR #105764 draft which allows to use a different PyObject.ob_refcnt, Py_INCREF() and Py_DECREF() implementation depending on the C++ and/or C standard.

**Comment by vstinner** [comment] 2023-06-14 01:49
At least, for GCC, a workaround is to ignore the ``-pendatic`` warning on anonymous union with  the``__extension__`` attribute:

```c
    __extension__ union {
        int ob_refcnt;
        char ob_refcnt_split[sizeof(int)];
    };
```

**Comment by h-vetinari** [comment] 2023-06-14 02:12
> Python 3.12 **emits a new compiler warning** using `gcc -std=c99 -pedantic`: I confirm that it's a regression.

I'm scratching my head how something using `-std=c99` could be a "regression" when the documentation says C11 is the minimum, much less when using `-pedantic`... (which is the kind of "yes, hit me with all you got" that I'm not sure is a realistic level to aim for. The C standard is broken/underspecified in various ways, so if all compiler vendors implement a given extension, what do we gain from keeping ourselves from using it?)

**Comment by vstinner** [comment] 2023-06-14 02:22
I fail to reproduce the issue with C++. Program in C++:

```
struct _object {
    // the evil anonymous union (!)
    union {
        int ob_refcnt;
        char ob_refcnt_split[sizeof(int)];
    };
    void *ob_type;
};

typedef struct _object PyObject;

int main()
{
    return 0;
}
```

I get no compiler warning or compiler error using the following command (g++ version 13.1.1):

```
g++ test.cpp -o test -Werror -Wall -Wextra -Wpedantic -std=c++03
```

**Comment by vstinner** [comment] 2023-06-14 02:23
> I'm scratching my head how something using -std=c99 could be a "regression" when the documentation says C11 is the minimum

See previous comments. C11 is the minimum to build Python, whereas we are trying to keep the Python C API usable in strict ISO C89.

**Comment by vstinner** [comment] 2023-06-14 02:26
The following pre-defined preprocessor macros can be used to detect the C standard:

* ``__STDC__``
* ``__STRICT_ANSI__``
* ``__STDC_VERSION__``

It's not possible to detect the usage of ``-pedantic``, but it should be tested. Non-standard C99 features like anonymous union must not be used in C99, otherwise we can get compiler warnings or errors. The only trade-off is the usage of ``__extension__`` when using GCC, it's documented as it should only be used in "system headers". Is Python falling in this category? :-)

**Comment by vstinner** [comment] 2023-06-14 02:38
I wrote PR #105767 to fix the C API for C99 and older:

* On C11 and newer and on C++, ``PyObject.ob_refcnt`` is an union, ``Py_INCREF()`` and ``Py_DECREF()`` are inlined.
* On C99 and older, ``PyObject.ob_refcnt`` type is Py_ssize, ``Py_INCREF()`` and ``Py_DECREF()`` are implemented as opaque functions.

Well, no longer inlining code on C99 and older can have an impact on performance which should be measured. For me, the first step is to fix the regression, and then design the most efficient implementation depending on the C or C++ standard, compiler flags, etc.

**Comment by h-vetinari** [comment] 2023-06-14 02:39
> some programs explicitly requires ISO C89 with warnings on C99 variable declarations in the middle of functions (pedantic mode). I don't know the rationale for treating these warnings as errors, but so far, it was cheap to keep ISO C89 compatibility.

I think something like `-pedantic` deserves at least a rationale, or to be thrown out as a requirement.

**Comment by vstinner** [comment] 2023-06-14 02:44
> no longer inlining code on C99 and older can have an impact on performance which should be measured.

I'm pretty sure that it can be avoided when building C extensions with GCC and clang which support ``__extension`` (no warning on the anonymous union, even with ``-pendantic``). But for now, I prefer to focus on C11 vs C99 code path in my PR. Well, see my PR #105767 where I added some comments.

**Comment by encukou** [comment] 2023-06-14 08:07
> I think something like `-pedantic` deserves at least a rationale,

It approximates the least common denominator of compilers we don't use in CI. 
If we say we're compatible with some standard, we should test that with `-pedantic`.

**Comment by vstinner** [comment] 2023-06-14 11:18
@zooba:
> I think we need a test that basically includes the headers and spits out warnings or errors.

tets_cppext checks for C++ compiler warnings and treats them as errors. Not only to include Python.h, but also use the most common APIs.

**Comment by vstinner** [comment] 2023-06-14 11:20
@eduardo-elizondo:
> This causes incorrect behavior since we can have Extension code that has increased the reference count beyond the maximum value and this implicit conversion would cause the reference count of the extension to be lost.

If it's not the case yet, we should have tests on these corner cases so they are no longer "undefined" behavior, but "tested" behavior 😁

**Comment by vstinner** [comment] 2023-06-14 11:25
@encukou:
> That would mean all uses of [obj->ob_refcnt](https://docs.python.org/3/c-api/typeobj.html?highlight=ob_refcnt#c.PyObject.ob_refcnt) would change to to obj->just_a_name.refcnt.

Well, I would strongly suggest C extensions to move away accessing directly PyObject members and use Py_REFCNT() and Py_SET_REFCNT() functions instead. It would be a Python 3.12 incompatible change that we should also consider.

**Comment by ndparker** [comment] 2023-07-13 10:53
FWIW, I'm using `-pedantic` (among other flags, including `-Werror`) for my extension development builds just to see what I'm doing wrong. Right now I'm basically missing a diagnostic tool right there for python 3.12 testing.

**Comment by encukou** [comment] 2023-07-13 11:11
If you use `-pedantic`, you should pair it with the appropriate C standard. That's [ `-std=c11` for Python 3.11+.](https://docs.python.org/3.11/whatsnew/3.11.html#build-changes)

**Comment by vstinner** [comment] 2023-07-25 11:57
I wrote PR #105767 to implement Py_INCREF() and Py_DECREF() as opaque function call on C99 and older. I'm worried that it can have a significant negative impact on performance. So I abandon it, and instead I try to get rid of the compiler warning: PR #107232 (use GCC and clang ``__extension__``).

**Comment by vstinner** [comment] 2023-07-25 15:00
I close the issue. Thanks everybody for your very useful feedback! I fixed the known compiler warnings (MSVC, GCC, clang).

Thanks @encukou for your reproducer, it was very useful on Linux and Windows.

---

C compilers try to implement latest standards, but they also have many extensions which may or may not be enabled by default. The GCC is famous for enabling many extensions by default: they are only disabled by ``-pedantic``. It took many years until the Linux kernel could be built with LLVM clang, time for clang to implement some GCC extensions, and to update the Linux kernel to avoid some other extensions.

While anonymous union is now standard in C11, the feature existed in C compilers before it was standardized.

In a perfect world, we should respect strictly the C standard and maximize C backward compatibility of the Python C API, by trying to stay compatible with C89. Well, in practice we use ``static inline`` which was not standardized in C89, but in C99.

There is a simple fix to **maximize backward compatibility**: **only expose opaque function** ``void Py_INCREF(PyObject *op)`` in the C API, and then use whatever we want in the hidden **implementation**. That's exactly what I did in the limited C API version 3.12 and newer. But it has a significant negative impact on performance since Py_INCREF/Py_DECREF are called frequently in C extensions.

For Python 3.12, we are trying to implement **immortal objects** with the **minimum performance overhead**. The chosen implementation is to use an anonymous union on 64-bit platforms (if ``sizeof(void*)`` is larger than 4 bytes).

What I did is to fix the annoying side effect: compiler warnings when the most pedantic warning mode is enabled, ``gcc -Wall -Wextra -pedantic`` (GCC) and ``cl /W4`` (MSC).

* For GCC and clang, I used ``__extension__`` to make the warning quiet: https://github.com/python/cpython/commit/6261585d63a31835b65d445d99dc14cca3fe9cf5
* For MSVC, I used ``__pragma`` to make the warning quiet: https://github.com/python/cpython/commit/1c8fe9bdb624d356643ee569151a9e4f2963179a

These changes are being backported to Python 3.12.

---

Maybe there is a another efficient implementation of Py_INCREF/Py_DECREF which can be inlined and be compatible with C99 or event C89. But apparently, @eduardo-elizondo spent **significant** time on designing the current implementation, and he failed to find a better silver bullet.

Well, at least now we know how to check for pedantic compiler warnings :-) If someone has a new clever implementation idea, please open a new issue!


---

> I fail to reproduce the issue with C++. Program in C++: (...)

I didn't get any warning with g++. If someone gets a new compiler warning with Python 3.12 Py_INCREF/Py_DECREF, please open a separated issue with details how to reproduce it.

**Closed as completed by vstinner** 2023-07-25 15:00 UTC
Labels: deferred-blocker, 3.12, 3.13

**Comment by vstinner** [comment] 2023-07-25 17:31
By the way, I fixed another class of compiler warnings when building ``Python.h`` with MSVC ``cl /W4``. I implemented ``Py_UNUSED()`` for MSVC in the main branch: PR #107250. It fix 2 warnings about unused arguments in ``unicodeobject.h``.
