### ISSUE TITLE
argparse does not handle hyphens in positional arguments

### ISSUE THREAD

**Issue by gregofi** [python/cpython#100411] opened 2022-12-21 16:17 UTC
# Bug report

argparse doesn't convert hyphens to underscores in positional arguments
```python
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('hyp-hens1')
parser.add_argument('--hyp-hens2')

args = parser.parse_args()

print(args.hyp_hens2)
print(args.hyp_hens1)
```

Should run fine when first arg is provided, instead
```
Traceback (most recent call last):
  File "/app/output.s", line 11, in <module>
    print(args.hyp_hens1)
          ^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'hyp_hens1'. Did you mean: 'hyp-hens1'?
```

# Your environment

- CPython versions tested on: 3.10.8
- Operating system and architecture: Linux x86

**Comment by ericvsmith** [comment] 2022-12-21 20:49
I don't think it's documented to do so, is it?

What I do is just change the positional argument to use underscores.

**Comment by vadmium** [comment] 2024-05-04 07:15
Looks the same as #95100

**Comment by serhiy-storchaka** [comment] 2024-10-09 21:51
Closing as a duplicate of #95100.

**Closed as not planned by serhiy-storchaka** 2024-10-09 21:51 UTC
Labels: type-feature, stdlib
