### ISSUE TITLE
psycopg2 2.9.8 not working with Python 3.12.0

### ISSUE THREAD

**Issue by uri-rodberg** [python/cpython#104830] opened 2023-05-24 03:29 UTC
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

I tried Python 3.12.0b1 (beta) and I ran tests of Speedy Net but it didn't work. I got this exception:
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module

My pip freeze --all:
asgiref==3.6.0
boto3==1.26.138
botocore==1.29.138
crispy-bootstrap4==2022.1
Django==4.2.1
django-admin-inline-paginator==0.3.0
django-crispy-forms==2.0
django-debug-toolbar==4.1.0
django-environ==0.10.0
django-friendship==1.9.6
django-translated-fields==0.12.0
factory-boy==3.2.1
Faker==18.9.0
haversine==2.8.0
jmespath==1.0.1
Pillow==9.5.0
pip==23.1.2
psycopg2==2.9.6
pymemcache==4.0.0
python-dateutil==2.8.2
pytz==2023.3
rules==3.3
s3transfer==0.6.1
setuptools==67.4.0
six==1.16.0
sorl-thumbnail==12.9.0
sqlparse==0.4.4
typing_extensions==4.5.0
tzdata==2023.3
urllib3==1.26.15
wheel==0.40.0

The above tests work with Python 3.10.11 and Python 3.11.3.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

Please complete the following information:

OS: Windows
Psycopg version: 2.9.6
Python version: Python 3.12.0b1 (beta)
PostgreSQL version: 13
pip version: 23.1.2

Repository - https://github.com/speedy-net/speedy-net
pip install the requirements and run tests with `./run_all_tests.sh`.

I also filed an issue with https://github.com/psycopg/psycopg2/issues/1578 which was closed.

**Comment by sunmy2019** [comment] 2023-05-24 03:53
looks like related to https://github.com/python/cpython/issues/104820

**Comment by uri-rodberg** [comment] 2023-06-07 17:29
Still not working with Python 3.12.0b2 - I get a pip error when installing requirements.

**Comment by uri-rodberg** [comment] 2023-08-06 14:18
Still not working with Python 3.12.0rc1 and psycopg2 2.9.7 (on Windows):

`django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: DLL load failed while importing _psycopg: The specified module could not be found.`

**Comment by sunmy2019** [comment] 2023-08-07 01:52
> pip error when installing requirements.

That's most likely not Python's fault. What's your pip error message?

> Error loading psycopg2 module: DLL load failed while importing _psycopg: The specified module could not be found.

This is likely due to an improper installation of `psycopg2`. A correct installation should also make `_psycopg` available.

---
Closed as it is most likely not fault in Python.

If you still think it's a fault from the Python side, you should remove all extensions, and provide a minimal reproducible example.

**Closed as not planned by sunmy2019** 2023-08-07 01:52 UTC
Labels: type-bug
