### ISSUE TITLE
[C API] Introduce a new slot in PyModuleDef to hold the classes

### ISSUE THREAD

**Issue by 1e2b3793-5146-46c5-b55f-27b9e782b291** [python/cpython#88265] opened 2021-05-10 09:50 UTC
BPO | [44099](https://bugs.python.org/issue44099)
--- | :---
Nosy | @vstinner, @tiran, @encukou, @erlend-aasland, @shreyanavigyan

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-10.09:49:59.507>
labels = ['extension-modules', 'expert-C-API', 'type-feature']
title = '[C API] Introduce a new slot in PyModuleDef to hold the classes'
updated_at = <Date 2021-05-20.15:22:46.540>
user = 'https://github.com/shreyanavigyan'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-20.15:22:46.540>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'C API']
creation = <Date 2021-05-10.09:49:59.507>
creator = 'shreyanavigyan'
dependencies = []
files = []
hgrepos = []
issue_num = 44099
keywords = []
message_count = 11.0
messages = ['393374', '393890', '393956', '393957', '394014', '394022', '394023', '394024', '394025', '394030', '394032']
nosy_count = 5.0
nosy_names = ['vstinner', 'christian.heimes', 'petr.viktorin', 'erlendaasland', 'shreyanavigyan']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44099'
versions = []
```

</p></details>

**Comment by erlend-aasland** [comment] 2023-06-22 07:58
Suggesting closing this as out-of-date, or perhaps as a duplicate of gh-86542.

**Closed as not planned** 2023-06-22 08:22 UTC
Labels: type-feature, extension-modules, topic-C-API
