### ISSUE TITLE
strftime %u not working (returns None)

### ISSUE THREAD

**Issue by Happily-Coding** [python/cpython#114037] opened 2024-01-13 20:05 UTC
# Bug report

### Bug description:

**strftime('%u', date) should return the day of the week starting from monday = 1 but always returns None.**

**This would be a minimal example**
```python
import sqlite3 as sqlite

cursor.execute(
'''
cursor = sqlite.connect('example_db').cursor() 
result = cursor.execute(
'''
SELECT
strftime('%w', '2015-04-05') AS day_of_week_number_from_0,
strftime('%u', '2015-04-05') AS day_of_week_number
'''
).fetchall()
print(result)

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by OnyxianSoul** [comment] 2024-01-13 20:07
<img width="616" alt="sqlite_bug_example" src="https://github.com/python/cpython/assets/74385137/50bfc3cf-e6fa-477c-a4a3-7049ac31f446">

**Comment by ericvsmith** [comment] 2024-01-13 20:09
The documentation https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior notes that this isn’t available for all platforms.

**Comment by OnyxianSoul** [comment] 2024-01-13 20:16
> The documentation https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior notes that this isn’t available for all platforms.

I see. It is still a bug though, since it returns None instead of yielding any errors.

But I guess want i want more is an enhancement allowing that functionality, since there is no real reason it shouldn't exist.

**Comment by ronaldoussoren** [comment] 2024-01-13 20:23
This is not so much a bug in Python, as not yet using the most recent version of SQLite.

First of all I can reproduce the problem without using Python (system install of sqlite on macOS):
```sql
sqlite> SELECT
   ...> strftime('%w', '2015-04-05') AS day_of_week_number_from_0,
   ...> strftime('%u', '2015-04-05') AS day_of_week_number
   ...> ;
day_of_week_number_from_0|day_of_week_number
0|
```

Support for the %u format string was added in Sqlite 3.44, released November 1st last year (https://www.sqlite.org/releaselog/3_44_0.html).

SQLite 3.44 will be included in a future release, see https://github.com/python/cpython/issues/111973.

**Closed as not planned** 2024-01-13 20:24 UTC
Labels: type-bug, topic-sqlite3

**Comment by ericvsmith** [comment] 2024-01-13 21:02
Good point on this being a SQLite issue, @ronaldoussoren.

As far as Python supporting `%u`, and in general being more consistent across platforms: there have been a number of suggestions over the years to support cross-platform strftime/strptime libraries, but it's hard and the efforts always die out. If you (the generic "you") have any specific suggestions on how to proceed, you should open an idea on discuss.python.org.
