### ISSUE TITLE
Py_NewInterpreter causes bogus fatal error along the failure path

### ISSUE THREAD

**Issue by c89120f3-1d68-4039-acdc-e84ecab5fea3** [python/cpython#90128] opened 2021-12-03 05:35 UTC
BPO | [45970](https://bugs.python.org/issue45970)
--- | :---
Nosy | @@hackhaslam
PRs | <li>python/cpython#29900</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-03.05:35:05.839>
labels = ['expert-C-API', 'type-crash', '3.11']
title = 'Py_NewInterpreter causes bogus fatal error along the failure path'
updated_at = <Date 2021-12-03.05:44:54.364>
user = 'https://github.com/hackhaslam'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-03.05:44:54.364>
actor = 'python-dev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2021-12-03.05:35:05.839>
creator = 'jason.haslam'
dependencies = []
files = []
hgrepos = []
issue_num = 45970
keywords = ['patch']
message_count = 1.0
messages = ['407566']
nosy_count = 2.0
nosy_names = ['python-dev', 'jason.haslam']
pr_nums = ['29900']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue45970'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment] 2022-11-23 21:06
@hackhaslam   can you provide a test to reproduce what you are reporting?

**Comment by hackhaslam** [comment] 2022-11-23 21:59
I can't remember any more what I did to cause `Py_NewInterpreter` to fail. It's okay. I gave up on this after I tried several times to sign the CLA without success.

**Comment by iritkatriel** [comment] 2022-11-23 22:12
We've moved to within since then and the CLA process has changed. Do you want to try again?

Also, the PR would need a unit test so we need to know how to reproduce the bug.

**Comment by iritkatriel** [comment] 2022-11-23 22:12
CC @ericsnowcurrently

**Comment by hackhaslam** [comment] 2022-11-23 22:18
I don't remember what I was doing to get into the failure path. I can see a few different cases (lines with `goto error` in `new_interpreter`) but I don't know how to trigger any of them. The only obvious thing is not holding the GIL when calling `Py_NewInterpreter`, but that causes its own more immediate fatal error. As far as I'm concerned, this isn't worth pursuing any farther.

**Comment by iritkatriel** [comment] 2022-11-23 22:20
Ok, thanks. I'll close it then.

**Closed as completed by iritkatriel** 2022-11-23 22:20 UTC
Labels: 3.11, type-crash, topic-C-API, pending
