### ISSUE TITLE
Possible segfault if globals dict is NULL in run_eval_code_obj

### ISSUE THREAD

**Issue by ngr-ilmarh** [python/cpython#116180] opened 2024-03-01 08:10 UTC
# Bug report

### Bug description:

Possible interpreter crash condition was found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.

[run_eval_code_obj](https://github.com/python/cpython/blob/3.10/Python/pythonrun.c#L1266) is called with globals dict passed as pointer without NULL check and that may cause segmentation fault in 

[PyEval_EvalCode](https://github.com/python/cpython/blob/339c8e1c13adc299a0e2e49c93067e7817692380/Python/ceval.c#L574)->[_PyEval_BuiltinsFromGlobals](https://github.com/python/cpython/blob/339c8e1c13adc299a0e2e49c93067e7817692380/Objects/frameobject.c#L1542)->[PyDict_GetItemWithError](https://github.com/python/cpython/blob/7895a61168aad4565a1d953104c9ec620e7c588f/Objects/dictobject.c#L2265) line [2272](https://github.com/python/cpython/blob/main/Objects/dictobject.c#L2272) in PyDict_Check(op).

Some functions, for example, [_run_script](https://github.com/python/cpython/blob/3.10/Modules/_xxsubinterpretersmodule.c#L1863) or [builtin_eval_impl](https://github.com/python/cpython/blob/3.10/Python/bltinmodule.c#L915) have globals NULL check.

Other, like [PyRun_SimpleStringFlags](https://github.com/python/cpython/blob/3.10/Python/pythonrun.c#L496), 
 [PyRun_InteractiveOneObjectEx](https://github.com/python/cpython/blob/3.10/Python/pythonrun.c#L196) or [PyRun_FileExFlags](https://github.com/python/cpython/blob/3.10/Python/pythonrun.c#L1220) just use the pointer from the PyObject struct.

For my understanding the globals dict should always be present and it is an error condition, when it is NULL.
And no one encounted with such faults, so the patch will have cosmetic effect (is on the way).

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

### Linked PRs
* gh-116182
* gh-116637

**Comment by NGRsoftlab** [comment] 2024-03-12 13:14
Yes, this patch has a cosmetic effect, should i mention it somehow in other issues, that will follow?

Testcase is difficult for me to offer right now, i'll try to figure it out, but with no guarantees that i succeed.

**Comment by zooba** [comment] 2024-04-02 14:37
This looks pretty trivially reproducible - just pass `globals=NULL` to `PyRun_FileExFlags` or any of the functions that wrap it up. They all just pass through without checking.

Prior to https://github.com/python/cpython/commit/d6c33fbd346765c6a8654dccacb2338006bf2b47 there was a NULL check deeper in that raised an error. The place where it was no longer exists, but we should probably add the check closer to where it's being used.

**Comment by NGRsoftlab** [comment] 2024-04-03 07:43
Yes, finally i've figured it out and left comment in PR thread with example and outcome.
Tried assert(), but when you pass NULL everything just segfaults with no visible notification, same behaviour without assert().

**Comment by serhiy-storchaka** [comment] 2024-04-03 08:01
There are two ways to fix this issue:

* Make the code working with `globals = NULL`. The part of the code already supports this case, you should add workarounds for other parts.
* If this case should not be supported, make the code raising an exception with clear and precise error message. Why `globals` is NULL? If it is passed by the user of the C API, the arguments should be validated and SystemError should be passed. If it is the result of other operations, it should be checked after performing these operations, and the error message should be more specific.

You perhaps need to try both ways to determine what way is more correct.

**Comment by NGRsoftlab** [comment] 2024-04-03 08:09
I thought that it's better to check NULL in one place, and there it's hard to figure out where NULL came from.
Ok, i'll try to make more research on the topic. Maybe you are right and it's better check NULL in C API functions directly.

**Comment by zooba** [comment] 2024-04-03 15:42
The fix is to bring back the null check that Mark deleted in his refactoring. It used to be in `_PyEval_EvalCode`:

```
    if (globals == NULL) {
        _PyErr_SetString(tstate, PyExc_SystemError,
                         "PyEval_EvalCodeEx: NULL globals");
        return NULL;
    }
```

(See lines 4386-4390 of ceval.c in d6c33fbd346765c6a8654dccacb2338006bf2b47 - sorry Github won't let me link directly for some reason)

**Comment by NGRsoftlab** [comment] 2024-04-03 15:54
It seems you should check discussion in PR. Unfortunately it forked

**Comment by serhiy-storchaka** [comment] 2024-04-17 11:39
After working on the proposed PR and tests, I think that it is not a bug. The lack of the validation in the C API is not a bug. You are supposed to pass valid arguments, and if it fails for invalid arguments, it is your fault.

Of course, it would be nice to handle the user error and raise a SystemError, but this is a new feature, not a bug fix. This API is high-level, so adding few new checks will not add much overhead.

**Comment by NGRsoftlab** [comment] 2024-04-27 06:31
I've logged-in to check PR status and sync sources. And found out, that our changes were merged through https://github.com/python/cpython/issues/117968. Should i close this PR then?

**Closed as completed** 2024-05-02 13:49 UTC
Labels: type-bug, 3.13
