### ISSUE TITLE
Unable to call iterdump method for Sqlite3 connections

### ISSUE THREAD

**Issue by kesry** [python/cpython#118221] opened 2024-04-24 09:17 UTC
# Bug report

### Bug description:

```python
import sqlite3


def dict_factory(cursor, row):
    d = {}
    for idx, col in enumerate(cursor.description):
        d[col[0]] = row[idx]
    return d


def main():
    conn = sqlite3.connect(":memory:")
    cur = conn.cursor()
    # conn.row_factory = sqlite3.Row # is ok
    conn.row_factory = dict_factory # is fail
    cur.executescript("""    
        create table if not exists test(
            id integer primary key AUTOINCREMENT
        );
    """)
    cur.close()
    for line in conn.iterdump():
        print(line)


main()

```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-118223
* gh-118270

**Comment by erlend-aasland** [comment] 2024-04-24 09:21
FTR, the traceback is:

```console
Traceback (most recent call last):
  File "../iterdump.py", line 26, in <module>
    main()
  File "../iterdump.py", line 22, in main
    for line in conn.iterdump():
  File "/opt/homebrew/Cellar/python@3.8/3.8.19/Frameworks/Python.framework/Versions/3.8/lib/python3.8/sqlite3/dump.py", line 55, in _iterdump
    query_res = cu.execute(q)
sqlite3.OperationalError: no such table: name
```

Happens on Python versions from 3.8 through 3.13. Using the `sqlite3.Row` factory seems to work fine.

**Comment by kesry** [comment] 2024-04-24 09:27
> FTR, the traceback is:
> 
> ```
> Traceback (most recent call last):
>   File "../iterdump.py", line 26, in <module>
>     main()
>   File "../iterdump.py", line 22, in main
>     for line in conn.iterdump():
>   File "/opt/homebrew/Cellar/python@3.8/3.8.19/Frameworks/Python.framework/Versions/3.8/lib/python3.8/sqlite3/dump.py", line 55, in _iterdump
>     query_res = cu.execute(q)
> sqlite3.OperationalError: no such table: name
> ```
> 
> Happens on Python versions from 3.8 through 3.13. Using the `sqlite3.Row` factory seems to work fine.

sqlite3. Row can't meet the needs of the production environment, is there any other way?

**Comment by erlend-aasland** [comment] 2024-04-24 09:39
The problem is that `iterdump` does not work with a custom row factory like this. Perhaps we should save the row factory before doing `iterdump` and restore it upon completion.

**Comment by kesry** [comment] 2024-04-24 09:52
> iterdump

Well, Thanks!

**Comment by erlend-aasland** [comment] 2024-04-24 10:12
I still think we should fix this. Perhaps a mention in the docs is sufficient.

**Comment by erlend-aasland** [comment] 2024-04-24 11:02
> The problem is that `iterdump` does not work with a custom row factory like this. Perhaps we should save the row factory before doing `iterdump` and restore it upon completion.

The solution is easier: overriding the row factory of a cursor does not impact the row factory of the parent connection, so all we need to do is to make sure the cursor used by `iterdump()` uses the default row factory by explicitly setting `cursor.row_factory = None`.

**Comment by erlend-aasland** [comment] 2024-04-25 08:14
Resolved by:

- #118223 
- #118270 (auto-merge enabled)

Thanks for the report, @kesry!

**Closed as completed by erlend-aasland** 2024-04-25 08:14 UTC
Labels: type-bug, 3.11, 3.12, topic-sqlite3

**Comment by kesry** [comment] 2024-04-25 09:36
> Resolved by:
> 
> * [gh-118221: Always use the default row factory in sqlite3.iterdump() #118223](https://github.com/python/cpython/pull/118223)
> * [[3.12] gh-118221: Always use the default row factory in sqlite3.iterdump() (#118223) #118270](https://github.com/python/cpython/pull/118270) (auto-merge enabled)
> 
> Thanks for the report, @kesry!

Greet!👍
