### ISSUE TITLE
list insert method truncates out of range index position, instead of throwing an error

### ISSUE THREAD

**Issue by ediznj** [python/cpython#116564] opened 2024-03-10 16:27 UTC
```python
my_list = [1,2,3]
my_list.insert(-5, 99) #Expected: index out of range. Instead: val 99 inserted at my_list[0]
print(my_list) # output: [99, 1, 2, 3]
del my_list[0]
my_list.insert(6, 99) #Expected: index out of range. Instead: 99 inserted at my_list[3]
print(my_list) # output: [1, 2, 3, 99]
```
Is there a reason behind to cover up programmers mistake instead of throwing error?
Also this behavior neither mentioned in documentation as well.

Code Responsible for this behavior:
https://github.com/python/cpython/blame/main/Objects/listobject.c#L466
Alternative:
```
         PyErr_SetString(PyExc_IndexError, "insert index out of range");
         ret = -1;
```
Version: 3.10
Operating systems tested on: Windows

**Comment by rhettinger** [comment] 2024-03-10 16:43
`list.insert` is documented as follows: `inserts x into s at the index given by i (same as s[i:i] = [x])` and that is indeed what it does in this case.  It is an intended, documented, and tested behavior (see `test_insert` in `Lib/test/list_tests.py`.   So, this is not a bug.  Marking as closed.

To discuss the reasons for the long-standing design decision, consider making a post to discourse or StackOverlow.

**Closed as not planned by rhettinger** 2024-03-10 16:43 UTC
Labels: type-bug

**Comment by terryjreedy** [comment] 2024-03-10 18:14
In other words, `i` indicates the position of the 0-width slice that is replaced by `x`.  I believe in this case, "same as" should be taken literally, as in "is executed as".  AFAIK, slice indexes, as opposed to item indexes, are always handled in a forgiving manner as in the example.  This is often quite useful and cannot be changed.

**Comment by ediznj** [comment] 2024-03-10 18:26
Thanks for the response @rhettinger and @terryjreedy 
I too agree to the act of forgiviness for slice index
