### ISSUE TITLE
Complex number as string with whitespace throws malformed string error

### ISSUE THREAD

**Issue by LimaBD** [python/cpython#121456] opened 2024-07-07 13:30 UTC
# Bug report

### Bug description:

Then converting `complex number as string` with whitespace to `float`, throws malformed string error

```python
print(complex("12 - 98j"))
```
Output

```bash
Traceback (most recent call last):
  File "/home/angrygingy/Desktop/temporal/./to_run.py", line 1, in <module>
    print(complex("12 - 98j"))
          ~~~~~~~^^^^^^^^^^^^
ValueError: complex() arg is a malformed string
```

I will create a new PR fixing this and adding tests.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121457

**Comment by skirpichev** [comment] 2024-07-08 02:28
> Then converting complex number as string with whitespace to float, throws malformed string error

This is expected behaviour.  Now it's [well documented](https://docs.python.org/3.12/library/functions.html#complex): "The string must not contain whitespace between '+', '-', the 'j' or 'J' suffix, and the decimal number." (c)  So, it's definitely not a bug.

That also doesn't make sense as a feature request.  This already was discussed and rejected, sorry: https://github.com/python/cpython/issues/53783

Probably, issue should be closed as "not planned".

**Comment by terryjreedy** [comment] 2024-07-08 03:07
Note that `int('- 1')` and `float('- 1.0')` also raise, as also explicitly documented. [Int doc](https://docs.python.org/3/library/functions.html#int): "Optionally, the string can be preceded by + or - (with no space in between)".  Closing.

**Closed as not planned by terryjreedy** 2024-07-08 03:07 UTC
Labels: type-bug
