### ISSUE TITLE
Acos inconsistency from math and cmath module

### ISSUE THREAD

**Issue by WiserOrb** [python/cpython#104353] opened 2023-05-10 10:29 UTC
# Bug report

Given the same angle, acos functions from math and cmath module produce slightly different results.

```python
import math
import cmath
print(math.acos(0.234))
print(cmath.acos(0.234))
```
Result:
```
 1.3346064424467945
(1.3346064424467943-0j)
```
Wolfram result for reference
`1.3346064424467944588079170460591632894189039264348864725986640459...`

As you can see, the real part differ for the last digit.

In the documentation I don't see a mention to this detail.
# Your environment

- CPython versions tested on: Python 3.10.10
- Operating system and architecture: openSUSE Tumbleweed, 20230420

**Comment by sobolevn** [comment] 2023-05-10 12:03
I think that this is a `float` vs `complex` precision "issue". I am not sure that this is a bug, though.

**Comment by sunmy2019** [comment] 2023-05-10 13:31
These floating-point errors are likely to be caused by different algorithms.

The precise value may be achieved when calculating with longer floating point number types.

**Comment by terryjreedy** [comment] 2023-05-10 15:02
@mdickinson, @rhettinger Should this be closed as not a bug?

**Comment by mdickinson** [comment] 2023-05-10 16:07
@terryjreedy Yes. It's not an explicit design goal or a documented guarantee that `math.somefunc` exactly matches `cmath.somefunc` for real arguments, so it's not a bug when the two values don't exactly match.

I'd certainly agree that it's nice to have bit-for-bit agreement in the absence of other constraints, but for the particular algorithm being used here in the cmath module there's no obvious way to make that happen.

**Comment by WiseroOrb** [comment] 2023-05-10 16:13
Question, does complex numbers use different rounding methods?

**Comment by mdickinson** [comment] 2023-05-10 16:21
FWIW, the "exact" value is, to 53 decimal places:

```
1.33460644244679444487641009997798721593566898041685194
```

(Note that this takes into account that the input value is not exactly `0.234`.)

Both of the values being returned are within 1 ulp of this (the float value `1.3346064424467945` has an error of around 0.222 ulps, while the float value `1.3346064424467943` has an error of 0.778 ulps. So both answers have a more-than-acceptable level of accuracy here.

@WiseroOrb 

> Question, does complex numbers use different rounding methods?

No - same rounding methods; just a different (and more complicated) algorithm in the complex case. You can see the core of the algorithm [here](https://github.com/python/cpython/blob/a7a2dbbf72aceef61bfb50901bfa39bfb8d6d229/Modules/cmathmodule.c#L245-L252). It makes multiple calls to the underlying math library, in contrast to `math.acos`, which is a direct wrapper around the C math library's `acos`. FWIW, the cmath algorithm is based on Kahan's famous "Much ado about nothing's sign bit" paper.

**Comment by mdickinson** [comment] 2023-05-10 16:29
Closing here as suggested by @terryjreedy - I don't think there's anything actionable for CPython. (@WiseroOrb You should feel free to bring this up on discuss.python.org if you want to discuss further, though.)

**Closed as not planned by mdickinson** 2023-05-10 16:29 UTC
Labels: type-bug, stdlib
