### ISSUE TITLE
`clear` method of `list` class in `multiprocessing.Manager()` is missing

### ISSUE THREAD

**Issue by YvesDup** [python/cpython#119176] opened 2024-05-19 11:34 UTC
# Bug report

### Bug description:

```python
import multiprocessing as mp

if __name__ == '__main__':
    mp.freeze_support()
    m = mp.Manager()
    l = m.list([None, True, 2.9001])
    print(l)
    l.clear()
```
Result is:
```python
[None, True, 2.9001]
Traceback (most recent call last):
  File "/Users/yves/Desktop/Bugs/gh-xxxxxxx1.py", line 8, in <module>
    l.clear()
    ^^^^^^^
AttributeError: 'ListProxy' object has no attribute 'clear'
```

The `clear` method is missing.  Is there a particular reason for this, or is it just an oversight ?

PS: The `clear` method exists with the `dict` class of multiprocessing.Manager().

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-119202

**Comment by sobolevn** [comment] 2024-05-20 17:36
Solved by https://github.com/python/cpython/commit/bbb49888a752869ae93423c42039a3a8dfab34d4
Closing as a duplicate of https://github.com/python/cpython/issues/103134

**Closed as not planned by sobolevn** 2024-05-20 17:36 UTC
Labels: type-bug

**Comment by YvesDup** [comment] 2024-05-20 20:09
Sorry for not seing this previous issue !
