### ISSUE TITLE
`asyncio.gather` doesn't work with generator and `return_exceptions=True`

### ISSUE THREAD

**Issue by ArtemIsmagilov** [python/cpython#112572] opened 2023-12-01 06:26 UTC
# Bug report

### Bug description:

Don't working gather with argument generator type. but if remove `return_exceptions=True` then working.

from source code

```python
asyncio.tasks
@overload def gather(__coro_or_future1: Future[_T1] | Generator[Any, None, _T1] | Awaitable[_T1],
           *,
           return_exceptions: Literal[False] = ...) -> Future[tuple[_T1]]
```

Main code
```python
@app_error
async def bg_continue_create_notification(
        user: Row,
        principal: Principal,
        cals_form: list,
        daily_clock: str,
        e_c: bool,
        ch_stat: bool,
):
    h, m = get_h_m_utc(daily_clock, user.timezone)

    result_cals_cal_id = await asyncio.gather((
        asyncio.create_task(caldav_calendar_by_cal_id(principal, cal_id=c['value'])) for c in cals_form
    ), return_exceptions=True)

    try:
        result_sync_cals = await asyncio.gather((
            asyncio.create_task(caldav_objects_by_sync_token(result_cal, load_objects=True))
            for result_cal in result_cals_cal_id
        ), return_exceptions=True)

    except caldav_errs.NotFoundError as exp:

        return dict_responses.calendar_not_found()

    sync_cals_in_db = [
        {'mm_user_id': user.mm_user_id, 'cal_id': sync_cal.calendar.id,
         'sync_token': sync_cal.sync_token}
        for sync_cal in result_sync_cals
    ]

    async with get_conn() as conn:
        await asyncio.gather(
            asyncio.create_task(User.update_user(conn, user.mm_user_id, e_c=e_c, ch_stat=ch_stat)),
            asyncio.create_task(YandexCalendar.add_many_cals(conn, sync_cals_in_db)),
            return_exceptions=True
        )

    async with get_conn() as conn:
        updated_user = UserView(user.mm_user_id, user.login, user.token, user.timezone, e_c, ch_stat, user.status)
        await asyncio.gather((
            asyncio.create_task(tasks.load_updated_added_deleted_events(conn, updated_user, sync_cal, notify=False))
            for sync_cal in result_sync_cals
        ), return_exceptions=True)

    delay = get_delay_daily(h, m)
    tasks.task1.send_with_options(args=(user.mm_user_id, h, m), delay=delay)

```

Error message:

```
Traceback (most recent call last):

microservice-app-1       |   File "/app/app/decorators/account_decorators.py", line 79, in wrapped

microservice-app-1       |     result = await func(*args, **kwargs)

microservice-app-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^

microservice-app-1       |   File "/app/app/notifications/notification_backgrounds.py", line 27, in bg_continue_create_notification

microservice-app-1       |     result_cals_cal_id = await asyncio.gather((

microservice-app-1       |                                ^^^^^^^^^^^^^^^^

microservice-app-1       |   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 821, in gather

microservice-app-1       |     fut = ensure_future(arg, loop=loop)

microservice-app-1       |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

microservice-app-1       |   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 679, in ensure_future

microservice-app-1       |     raise TypeError('An asyncio.Future, a coroutine or an awaitable '

microservice-app-1       | TypeError: An asyncio.Future, a coroutine or an awaitable is required


```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment] 2023-12-01 08:22
The ``asyncio.gather`` API is [documented as taking a variable number of arguments](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather), not a sequence of callable.

That is, use sequence unpacking here (the ``*`` in the block below):

```python3
await asyncio.gather(*(
            asyncio.create_task(tasks.load_updated_added_deleted_events(conn, updated_user, sync_cal, notify=False))
            for sync_cal in result_sync_cals
        ), return_exceptions=True)
```

**Comment by ArtemIsmagilov** [comment] 2023-12-01 08:55
I agree that you just need to add *, but I created a problem because the source code says that a generator can be accepted as input and it works without the return_exception argument, but it does not work with the aggrum. It is necessary to describe gather more precisely

**Comment by AlexWaygood** [comment] 2023-12-01 09:00
To be clear, @ArtemIsmagilov, the issue as you see it is that the type hints your editor is showing you don't seem to be accurate — they say the function accepts a generator in situations that it doesn't?

If so, then this is a typeshed issue rather than a CPython issue — but I can easily transfer the issue over

**Comment by kumaraditya303** [comment] 2024-05-29 15:05
Please create issue on typeshed, it is not a bug of asyncio so closing.

**Closed as not planned by kumaraditya303** 2024-05-29 15:05 UTC
Labels: type-bug, topic-asyncio, pending
