### ISSUE TITLE
Incremental GC causes a significant slowdown for Sphinx

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#124567] opened 2024-09-26 00:02 UTC
# Bug report

## A significant performance regression in Sphinx caused by changes in CPython 3.13

Here is a script that does the following things:
1. Replaces the contents of all CPython documentation files except `Doc/library/typing.rst` with simply `"foo"`
2. Creates a virtual environment
3. Installs our doc dependencies into the environment (making sure that we use pure-Python versions for all doc dependencies rather than built wheels that might include C extensions)
4. Times how long it takes to build the docs using that environment
5. Restores all the modified docs files and deletes the virtual environment again

<details>
<summary>The script</summary>

```py
import contextlib
import shutil
import subprocess
import time
import venv
from pathlib import Path

def run(args):
    try:
        subprocess.run(args, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(e.stdout)
        print(e.stderr)
        raise


with contextlib.chdir("Doc"):
    try:
        for path in Path(".").iterdir():
            if path.is_dir() and not str(path).startswith("."):
                for doc_path in path.rglob("*.rst"):
                    if doc_path != Path("library/typing.rst"):
                        doc_path.write_text("foo")

        venv.create(".venv", with_pip=True)

        run([
            ".venv/bin/python",
            "-m",
            "pip",
            "install",
            "-r",
            "requirements.txt",
            "--no-binary=':all:'",
        ])

        start = time.perf_counter()

        run([
            ".venv/bin/python",
            "-m",
            "sphinx",
            "-b",
            "html",
            ".",
            "build/html",
            "library/typing.rst",
        ])

        print(time.perf_counter() - start)
        shutil.rmtree(".venv")
        shutil.rmtree("build")
    finally:
        subprocess.run(["git", "restore", "."], check=True, capture_output=True)
```

</details>

Using a PGO-optimized build with LTO enabled, the script reports that there is a significant performance regression in Sphinx's parsing and building of `library/typing.rst` between `v3.13.0a1` and https://github.com/python/cpython/commit/909c6f718913e713c990d69e6d8a74c05f81e2c2:
- On `v13.0a1` the script reports a Sphinx build time of between 1.27s and 1.29s (I ran the script several times)
- On https://github.com/python/cpython/commit/ede1504c4b37b98636bf935679746ba2932f5677, a Sphinx build time of between 1.76 and 1.82s is reported by the script (a roughly 48% regression).

A similar regression is reported in this (much slower) variation of the script that builds the entire set of CPython's documentation rather than just `library/typing.rst`.

<details>
<summary>More comprehensive variation of the script</summary>

```py
import contextlib
import shutil
import subprocess
import time
import venv

def run(args):
    subprocess.run(args, check=True, text=True)


with contextlib.chdir("Doc"):
    venv.create(".venv", with_pip=True)

    run([
        ".venv/bin/python",
        "-m",
        "pip",
        "install",
        "-r",
        "requirements.txt",
        "--no-binary=':all:'",
    ])

    start = time.perf_counter()

    run([
        ".venv/bin/python",
        "-m",
        "sphinx",
        "-b",
        "html",
        ".",
        "build/html",
    ])

    print(time.perf_counter() - start)
    shutil.rmtree(".venv")
    shutil.rmtree("build")
```

</details>

The PGO-optimized timings for building the entire CPython documentation is as follows:
- `v3.13.0a1`: 45.5s
- https://github.com/python/cpython/commit/ede1504c4b37b98636bf935679746ba2932f5677: 62.7s

This indicates a 38% performance regression for building the entire set of CPython's documentation.

## Cause of the performance regression

This performance regression was initially discovered in #118891: in our own CI, we use a fresh build of CPython in our Doctest CI workflow (since otherwise, we wouldn't be testing the tip of the `main` branch), and it was observed that the CI job was taking significantly longer on the `3.13` branch than the `3.12` branch. In the context of our CI, the performance regression is even worse, because of the fact that our Doctest CI workflow uses a debug build rather than a PGO-optimized build, and the regression is even more pronounced in a Debug build.

Using a debug build, I used the first script posted above to bisect the performance regression to commit 15309329b65a285cb7b3071f0f08ac964b61411b (below), which seemed to cause a performance regression of around 300% in a debug build

```
15309329b65a285cb7b3071f0f08ac964b61411b is the first bad commit
commit 15309329b65a285cb7b3071f0f08ac964b61411b
Author: Mark Shannon <mark@hotpy.org>
Date:   Wed Mar 20 08:54:42 2024 +0000

    GH-108362: Incremental Cycle GC (GH-116206)

 Doc/whatsnew/3.13.rst                              |  30 +
 Include/internal/pycore_gc.h                       |  41 +-
 Include/internal/pycore_object.h                   |  18 +-
 Include/internal/pycore_runtime_init.h             |   8 +-
 Lib/test/test_gc.py                                |  72 +-
 .../2024-01-07-04-22-51.gh-issue-108362.oB9Gcf.rst |  12 +
 Modules/gcmodule.c                                 |  25 +-
 Objects/object.c                                   |  21 +
 Objects/structseq.c                                |   5 +-
 Python/gc.c                                        | 806 +++++++++++++--------
 Python/gc_free_threading.c                         |  23 +-
 Python/import.c                                    |   2 +-
 Python/optimizer.c                                 |   2 +-
 Tools/gdb/libpython.py                             |   7 +-
 14 files changed, 684 insertions(+), 388 deletions(-)
 create mode 100644 Misc/NEWS.d/next/Core and Builtins/2024-01-07-04-22-51.gh-issue-108362.oB9Gcf.rst
```

Performance was then significantly improved by commit e28477f214276db941e715eebc8cdfb96c1207d9 (below), but it's unfortunately still the case that Sphinx is far slower on Python 3.13 than on Python 3.12:

```
commit e28477f214276db941e715eebc8cdfb96c1207d9
Author: Mark Shannon <mark@hotpy.org>
Date:   Fri Mar 22 18:43:25 2024 +0000

    GH-117108: Change the size of the GC increment to about 1% of the total heap size. (GH-117120)

 Include/internal/pycore_gc.h                       |  3 +-
 Lib/test/test_gc.py                                | 35 +++++++++++++++-------
 .../2024-03-21-12-10-11.gh-issue-117108._6jIrB.rst |  3 ++
 Modules/gcmodule.c                                 |  2 +-
 Python/gc.c                                        | 30 +++++++++----------
 Python/gc_free_threading.c                         |  2 +-
 6 files changed, 47 insertions(+), 28 deletions(-)
 create mode 100644 Misc/NEWS.d/next/Core and Builtins/2024-03-21-12-10-11.gh-issue-117108._6jIrB.rst
```

See https://github.com/python/cpython/issues/118891#issuecomment-2375334948 for more details on the bisection results.

Profiling by @nascheme in https://github.com/python/cpython/issues/118891#issuecomment-2375362608 and https://github.com/python/cpython/issues/118891#issuecomment-2375446761 also confirms that Sphinx spends a significant amount of time in the GC, so it seems very likely that the changes to introduce an incremental GC in Python 3.13 is the cause of this performance regression.

Cc. @markshannon for expertise on the new incremental GC, and cc. @hugovk / @AA-Turner for Sphinx expertise.

### CPython versions tested on:

3.12, 3.13, CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-124717
* gh-124770
* gh-126777
* gh-127009

**Comment by picnixz** [comment] 2024-09-26 00:13
I think I wanted to investigate it in https://github.com/sphinx-doc/sphinx/issues/12181 but then I didn't have the motivation nor the time... (and we wanted to avoid keeping opened issues for too long).

**Comment by AlexWaygood** [comment] 2024-09-26 00:15
> I think I wanted to investigate it in [sphinx-doc/sphinx#12181](https://github.com/sphinx-doc/sphinx/issues/12181) but then I didn't have the motivation nor the time... (and we wanted to avoid keeping opened issues for too long).

Yes, @AA-Turner mentioned as much in https://github.com/python/cpython/issues/118891#issuecomment-2375279122. This seems like the kind of issue that could cause slowdowns for other workloads as well as Sphinx, however. (But I'll defer to our performance and GC experts on if there are obvious ways to mitigate it.)

**Comment by AlexWaygood** [comment] 2024-09-26 00:37
Prompted by @ned-deily, I reran my PGO-optimized timings using `--with-lto=full --enable-optimizations` builds rather than simply `--with-lto --enable-optimizations` builds. (Since I'm benchmarking using a Mac, this [could have been relevant](https://github.com/python/cpython/issues/122580).) The timings on `v3.13.0a1` and `main` using this build configuration were essentially identical to the ones I reported above, however.

**Comment by willingc** [comment] 2024-09-26 00:46
@AlexWaygood Let's rerun after https://github.com/python/cpython/issues/124538 lands.

**Comment by Privat33r-dev** [comment] 2024-09-26 05:56
I suggest to add time test for doctests to notice such performance degradations in the future automatically. Preferably, with high margin, so new additions to the doctests do not cause it to trigger.

**Comment by hauntsaninja** [comment] 2024-09-26 06:08
Could be cool to make the sphinx build a pyperformance benchmark (I think there might be a docutils pyperf benchmark, wonder if that saw a regression)

**Comment by JelleZijlstra** [comment] 2024-09-26 06:13
@willingc I think that's unlikely to make a difference; that issue is related to capsules and probably doesn't interact with the regression we're seeing here.

@hauntsaninja there is a docutils benchmark, https://github.com/python/pyperformance/tree/main/pyperformance/data-files/benchmarks/bm_docutils. Looks like it builds a bunch of RST files, though not CPython's own docs. According to Michael that benchmark didn't show a regression, so it would be interesting to figure out what's different about the CPython docs relative to that benchmark.

**Comment by picnixz** [comment] 2024-09-26 10:20
> According to Michael that benchmark didn't show a regression

There is a bit of a regression actually, at least in the memory usage as reported by https://github.com/faster-cpython/ideas/issues/668 (roughly a 20% increase of memory). I don't think that's all there is to actually make Sphinx slower.

**Comment by AA-Turner** [comment] 2024-09-26 13:16
Thanks Alex for the excellent write-up. A note for reproduction, in my local tests the slowdown was could be reproduced just in the parsing step, so you can use ``'dummy'`` instead of ``'html'`` in the reproduction script to save time (as no output files are written).

> `library/typing.rst`

Interestingly I found that when building just that document, timings were broadly the same. However when building everything, 3.13.0a5 was consistently 1.6x faster than 3.13.0a6 (using the built optimised releases from https://www.python.org/downloads/ for Windows, 64 bit).

> Could be cool to make the sphinx build a pyperformance benchmark

When I added the Docutils benchmark, Michael Droettboom requested that I/O variables (reading & writing files) be removed as it adds too much noise. There isn't a good way to avoid I/O in Sphinx, unlike with Docutils, unfortunatley. I would be keen to add Sphinx to the benchmark suite.

> Looks like it builds a bunch of RST files

Docutils' documentation, we can't use Python's as the Python documentation uses Sphinx-only extensions.

A

**Comment by mdboom** [comment] 2024-09-26 18:05
> According to Michael that benchmark didn't show a regression, so it would be interesting to figure out what's different about the CPython docs relative to that benchmark.

Here's [the timing benchmark of 3.13.0rc2 vs 3.12.0](https://github.com/faster-cpython/benchmarking/blob/main/results/bm-20240906-3.13.0rc2-ec61006/bm-20240906-linux-x86_64-python-v3.13.0rc2-3.13.0rc2-ec61006-vs-3.12.0.svg).  docutils is actually slightly faster (0.8%) but that's within the noise.

There is a [33% increase in memory usage](https://gist.github.com/mdboom/94a9aa1f2bd41a33078ba0318c87ec12) however.

**Comment by Yhg1s** [comment] 2024-10-01 02:07
This is still an issue that needs more investigation for 3.14, but for 3.13 the incremental GC has been reverted and that solves the problem. I'll edit the issue title accordingly (and remove the release-blocker label).

**Comment by Privat33r-dev** [comment] 2024-10-01 08:48
> This is still an issue that needs more investigation for 3.14, but for 3.13 the incremental GC has been reverted and that solves the problem. I'll edit the issue title accordingly (and remove the release-blocker label).

Wouldn't reverting it resolve the issue for 3.13 and hence the title should be that it's "slower in 3.14 than in 3.13", instead of "than in 3.12"?

**Comment by AlexWaygood** [comment] 2024-10-01 09:51
> Wouldn't reverting it resolve the issue for 3.13 and hence the title should be that it's "slower in 3.14 than in 3.13", instead of "than in 3.12"?

If we're being pedantic, strictly speaking the title was still accurate ;) but I have modified the title in such a way that it will still be accurate even if the `main` branch becomes 3.15 and the issue is stil unresolved ;)

**Comment by Privat33r-dev** [comment] 2024-10-01 10:05
> If we're being pedantic, strictly speaking the modified title was still accurate ;) but I have modified the title again so that it doesn't reference any specific version of Python

I concur. The previous title made a grey zone for 3.13 and my primary intent was to disambiguate it :)

**Comment by ned-deily** [comment] 2024-10-01 20:20
For what it's worth, another performance datapoint: a couple of microbenchmarks whose performance were somewhat negatively impacted by the incremental GC revert in 3.13.0rc3.

Background: since there were performance regressions in two microbenchmarks reported when using the python.org macOS binary installer for 3.13.0rc1 (#122580 and #122832) and resolved with the 3.13.0rc2 installer build (changing `--with-lto=thin` to `--with-lto=full`), I have been using these two microbenchmarks as a performance "smoke test" for macOS installers. With the 3.13.0rc3 release installer, I noticed some performance differences

For the gh-122580 microbenchmark:
```
 3.13.0rc2 ran  1.17 ± 0.02 times faster than 3.13.0rc3 on Apple Silicon M3 macBook Pro
           ran ~1.13 ± 0.02 times faster than 3.13.0rc3 on Intel macBook Pro

```
For the gh-122832 microbenchmark:
```
 3.13.0rc2 ran  1.17 ± 0.02 times faster than 3.13.0rc3 on Apple Silicon M3 macBook Pro
           ran ~1.04 ± 0.02 times faster than 3.13.0rc3 on Intel macBook Pro

```

(FTR, the M3 macBook Pro used was the same hardware as using in the earlier issues; but a faster and bigger Intel iMac was used for the earlier issues rather than a slow Intel macBook Pro.)

I have subsequently run some bisecting between the v3.13.0rc2 and v3.13.0rc3 tags using a simple build configuration (on macOS with optimizations and --with-lto=full) and it appears that the above degradations from rc2 are entirely attributable to the revert of the incremental GC in e0eb44ad49926dd131dc639f5506c6769e45b4eb from PR #124770.

**Comment by mdboom** [comment] 2024-10-01 21:30
I finally have complete benchmarking results for this, and the results are mainly neutral or slightly better for reverting this change.  The outlier is macOS, where I am seeing a 4% performance regression similar to @ned-deily.  Note that these are our own builds on our own benchmarking machine (not the official python.org release).

| commit | change |
| -- | -- |
| darwin arm64 | 1.05x ↓ |
| linux x86_64 | 1.00x ↑ |
| linux aarch64 | 1.00x ↑ |
| windows x86 | 1.01x ↑ |
| windows x86_64 | 1.01x ↑ |

**Comment by iritkatriel** [comment] 2024-11-13 11:52
I think I may have found a micro benchmark that shows slowdown on main vs 3.13. 
I guessed that it might be due to large unreachable cycles, so:

```
N = 1000000

class C:
    def __init__(self, x):
        self.next = x

def f():
    head = C(None)
    x = head
    for i in range(N):
        x = C(x)
    head.next = x

import timeit
import sys
print(sys.version_info[:2], timeit.timeit(f, number=100))
```

I ran it on Mac, on debug builds of 3.13 and main (because the sphinx test uses a debug build).

```
% repeat 4 {../python3.13/python.exe ttt.py; ./python.exe ttt.py}
(3, 13) 49.409357415977865
(3, 14) 63.12042100299732
(3, 13) 50.696041971008526
(3, 14) 57.32344063199707
(3, 13) 53.82498657301767
(3, 14) 57.68169612000929
(3, 13) 50.13815074498416
(3, 14) 55.76091634799377
```

Average is 51 vs 58.

**Comment by markshannon** [comment] 2024-11-15 18:39
This is what was causing the slowdown: https://github.com/python/cpython/pull/126502/commits/278059b79277200bed9597e73d1828163ab5bceb#diff-a848a0ef178aa113a092e72403da0e344f37bd141bb90a7aa65015c77bfe7385L1380
It is validating the entire increment each time we increase the increment size, so is potentially quadratic.
Presumably sphinx makes it quadratic.

With that line removed, `Doc/Doctest` now runs in [3 minutes](https://github.com/python/cpython/actions/runs/11861578730/job/33059213092?pr=126502)

**Comment by AA-Turner** [comment] 2024-11-18 14:47
> Do we also need to check how the Sphinx benchmark looks with a PGO-optimized release build relative to 3.13? (The CI doctest job uses a debug build.)

I agree, for completeness we should confirm that the slowdown has gone from release builds (it was always much more pronounced in debug builds).

A

**Comment by mdboom** [comment] 2024-11-18 15:29
> Do we also need to check how the Sphinx benchmark looks with a PGO-optimized release build relative to 3.13?

On PGO builds on our benchmarking hardware, the Sphinx benchmark is now [not significantly different than 3.13.0](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20241115-3.14.0a1%2B-278059b/bm-20241115-linux-x86_64-faster%252dcpython-mark_first_gc-3.14.0a1%2B-278059b-vs-3.13.0.md] and [about 2% faster than prior to #126502 being merged](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20241115-3.14.0a1%2B-278059b/bm-20241115-linux-x86_64-faster%252dcpython-mark_first_gc-3.14.0a1%2B-278059b-vs-base.md).

**Comment by AlexWaygood** [comment] 2024-11-18 15:47
Performance is also now unchanged for me locally relative to Python 3.13 (or maybe even _slightly_ better!) using the script I posted in https://github.com/python/cpython/issues/118891#issuecomment-2375450873:

- `main` (`--enable-optimisations --with-lto=full`): 37.22s
- 3.13: 38.15s

Closing as completed. Thanks everybody who helped investigate, and thanks @markshannon for fixing! 🥳

**Comment by AlexWaygood** [comment] 2024-11-19 09:34
Reopening since https://github.com/python/cpython/pull/126502 was reverted in https://github.com/python/cpython/pull/126983 due to buildbot failures

**Comment by markshannon** [comment] 2024-11-19 14:03
And closing again 🙂

**Closed as completed** 2024-11-19 14:10 UTC
Labels: type-bug, performance, 3.14
