### ISSUE TITLE
asyncio: wrong traceback when 2 coroutines await the same future

### ISSUE THREAD

**Issue by d-maurer** [python/cpython#93528] opened 2022-06-06 08:10 UTC
Observed in Python 3.9 and 3.11 (but likely more widespread)

Assume 2 `asyncio` coroutines await the same future; set an exception for this future. Then the traceback for one of the coroutines contains parts of the traceback of the other coroutine.
The cause of the problem is the use of the same exception (and its `__traceback__` attribute) to manage 2 different tracebacks.

The following script demonstrates the problem:
```python
from asyncio import get_event_loop
from traceback import print_exc

loop = get_event_loop()

async def coordinate():
  fut = loop.create_future()

  async def f(): return await fut
  async def g(): return await fut

  fut.set_exception(Exception())

  try: await f()
  except Exception:
    print_exc()

  try: await g()
  except Exception:
    print_exc()

loop.run_until_complete(coordinate())
```
It produces the following output:
```
.../py311/test_task_exception.py:4: DeprecationWarning: There is no current event loop
  loop = get_event_loop()
Traceback (most recent call last):
  File ".../py311/test_task_exception.py", line 13, in coordinate
    try: await f()
         ^^^^^^^^^
  File ".../py311/test_task_exception.py", line 9, in f
    async def f(): return await fut
                          ^^^^^^^^^
Exception
Traceback (most recent call last):
  File ".../py311/test_task_exception.py", line 16, in coordinate
    try: await g()
         ^^^^^^^^^
  File ".../py311/test_task_exception.py", line 10, in g
    async def g(): return await fut
                          ^^^^^^^^^
  File ".../py311/test_task_exception.py", line 13, in coordinate
    try: await f()
         ^^^^^^^^^
  File ".../py311/test_task_exception.py", line 9, in f
    async def f(): return await fut
                          ^^^^^^^^^
Exception
```
The first `print_exc()` is correct, but the second one is wrong; it contains beside the correct traceback for coroutine `g` also that for coroutine `f`.

**Comment by kumaraditya303** [comment] 2022-06-06 09:06
Duplicate of #90082

**Comment by iritkatriel** [comment] 2022-06-06 09:09
While it's the same problem, I think this issue proposes another test case that should be added as a unit test.

**Comment by iritkatriel** [comment] 2022-06-06 09:11
Or maybe not, it's essentially the same scenario. Sorry about the noise.

**Closed as not planned by iritkatriel** 2022-06-06 09:11 UTC
Labels: type-bug

**Comment by kumaraditya303** [comment] 2022-06-06 09:13
It is awaiting the same future in two different coroutines, so it is same scenario just awaited differently.
